import { createDriftScene } from './drift-scene.js';
const $=id=>document.getElementById(id),key='rhythm-drop.echo.identities.v1';
const publicDemo=location.hostname.endsWith('.github.io')||new URLSearchParams(location.search).get('mode')==='preview';
const moodColor={'平静':'#9fb389','想念':'#b5a68e','有点累':'#9caeb0','期待':'#c4b681'},intentName={listen:'想被听见',create:'一起创作',moment:'分享此刻'};
let identities=[],active='',data={mine:[],threads:[],incoming:null},online=false,identityIssue=false,view='listen',mode=null,draft=null,draftURL='',pending=null,busy=false,recording=false,recorder,stream,recordStart=0,recordTimer,context,analyser,recordSource,playing=null,playURL='',ambience=[],ambiTimers=[],level=0,playEpoch=0,titleRevision=0;
let scene,statusTimer,draftMeter,draftSource;
const say=message=>{clearTimeout(statusTimer);$('status').textContent=message;$('status').classList.remove('idle');statusTimer=setTimeout(()=>$('status').classList.add('idle'),8000);};
const current=()=>identities.find(p=>p.token===active);
try{const saved=JSON.parse(localStorage.getItem(key)||'{"profiles":[],"active":""}');if(!Array.isArray(saved.profiles)||saved.profiles.length>8||saved.profiles.some(p=>typeof p.name!=='string'||p.name.length>16||typeof p.token!=='string'||p.token.length!==43)||typeof saved.active!=='string')throw Error();identities=saved.profiles;active=identities.some(p=>p.token===saved.active)?saved.active:'';}catch{identityIssue=true;say('本机身份记录暂时无法读取，旧记录保留。');}
function saveIdentities(){try{localStorage.setItem(key,JSON.stringify({profiles:identities,active}));}catch{identityIssue=true;say('身份暂未保存。请保留当前页面，避免丢失身份入口。');}}
async function api(path,body){const controller=new AbortController(),timer=setTimeout(()=>controller.abort(),15000);try{
  const response=await fetch(path,{method:body===undefined?'GET':'POST',headers:{'Content-Type':'application/json',...(active?{Authorization:'Bearer '+active}:{})},body:body===undefined?undefined:JSON.stringify(body),signal:controller.signal});
  if(!(response.headers.get('Content-Type')||'').includes('application/json'))throw Error('社区服务尚未启动。请用项目中的声音社区服务打开这页。');
  const value=await response.json();if(!response.ok)throw Error(value.error||'声音暂时无法送达。');return value;
}catch(error){if(error.name==='AbortError')throw Error('连接有点慢，声音仍保留在当前页面，可以安全重试。');throw error;}finally{clearTimeout(timer);}}
function controls(){const available=online&&!!active&&!busy&&!recording&&!!draft;
  $('send').disabled=!available||!$('consent').checked||pending?.visibility==='private';$('keep').disabled=!available||!!mode||(!!pending&&pending.visibility!=='private');$('keep').textContent=pending?.visibility==='private'?'重试本机保存':'留给自己';
  $('record').disabled=busy||!!pending;$('audio-file').disabled=busy||recording||!!pending;$('discard-draft').disabled=busy;$('new-identity').disabled=!online||busy||identityIssue;
  $('send').textContent=pending?'重试上次提交 ↗':mode?.type==='reply'?'把回应交给对方 ↗':mode?.type==='message'?'留下新的声音 ↗':'让声音漂流';
}
function setView(next){
  if(next!=='leave'){if(recording&&recorder?.state==='recording'){recorder.stop();closeMic();}$('draft-audio').pause();}
  view=next;scene?.stopStory();document.querySelectorAll('[data-view]').forEach(button=>button.setAttribute('aria-current',button.dataset.view===next?'page':'false'));
  for(const name of ['leave','listen','garden'])$('view-'+name).hidden=name!==next||(name==='listen'&&!data.incoming);
  $('identity-panel').hidden=true;document.querySelector('.shore').classList.toggle('has-incoming',next==='listen'&&!!data.incoming);
  if(next==='garden')requestAnimationFrame(()=>$('view-garden').scrollIntoView({behavior:matchMedia('(prefers-reduced-motion: reduce)').matches?'instant':'smooth'}));
  else if(next==='listen')window.scrollTo({top:0,behavior:'instant'});
}
function el(tag,text,className){const node=document.createElement(tag);if(text!==undefined)node.textContent=text;if(className)node.className=className;return node;}
function action(text,handler,className='secondary'){const button=el('button',text,className);button.onclick=()=>Promise.resolve(handler()).catch(error=>say(error.message));return button;}
function empty(title,description){const node=el('div',undefined,'empty');node.append(el('span','✳'),el('h3',title),el('p',description));return node;}
async function mutate(path,body){stopPlayer();const identity=active,next=await api(path,body);if(active===identity){data=next;render();}return next;}
function stateLabel(clip){return clip.visibility==='private'?'只在我的花园':({active:'等待被接住',claimed:'已被接住 · 等待回应',paired:'已经长出共同植物',withdrawn:'已收回 · 对方暂时无法重听',review:'暂停漂流 · 等待处理',blocked:'已停止开放 · 处理已完成'}[clip.status]||'声音回应');}
function voiceCard(clip,options={}){
  const card=el('article',undefined,'voice-card'),top=el('div',undefined,'voice-top');top.append(el('span','✳','avatar'),el('span',clip.name),el('small',new Intl.DateTimeFormat('zh-CN',{month:'short',day:'numeric',timeZone:'Asia/Shanghai'}).format(clip.created*1000)));
  card.append(top,el('h3',clip.playable?clip.title:'这段声音已收回'),el('p',clip.playable?clip.note:'作者收回了这段表达，植物保留相遇的记录。','voice-note'));
  const tags=el('div',undefined,'tags');tags.append(el('span',clip.mood),el('span',intentName[clip.intention]),el('span',`${clip.duration.toFixed(1)} 秒`));card.append(tags);
  const actions=el('div',undefined,'voice-actions'),listen=action(clip.heard?'▷ 再听一次':'▷ 听这段声音',()=>playSequence([clip]));listen.disabled=!clip.playable;actions.append(listen);
  if(clip.mine){actions.append(action('下载原声音',()=>downloadVoice(clip),'quiet'));if(clip.visibility!=='private'&&!['review','blocked'].includes(clip.status))actions.append(action(clip.status==='withdrawn'?'重新开放':'收回声音',async()=>{await mutate('/api/withdraw',{id:clip.id,restore:clip.status==='withdrawn'});say(clip.status==='withdrawn'?'声音重新开放，原录音保持不变。':'声音已收回，对方不能再打开这段原声音。');},'quiet'));}else if(clip.playable&&!options.incoming){actions.append(action('举报这段声音',async()=>{await mutate('/api/report',{id:clip.id,reason:'相遇参与者认为这段声音不适合交流'});say('举报已记录，这段声音暂停开放，后续交流也暂停。');},'quiet'));}
  card.append(actions);if(options.own)card.append(el('p',stateLabel(clip),'voice-status'));return card;
}
function render(){
  const profile=current();$('identity-label').textContent=data.profile?.name||profile?.name||'未署名';if(document.activeElement!==$('profile-name'))$('profile-name').value=data.profile?.name||profile?.name||'';$('identities').replaceChildren();identities.forEach(p=>{const option=new Option(p.name,p.token);option.selected=p.token===active;$('identities').add(option);});
  $('garden-count').textContent=String(data.mine.length+data.threads.length);$('incoming-dot').hidden=!data.incoming;
  $('incoming').replaceChildren();const incoming=data.incoming;
  if(incoming){const card=voiceCard(incoming,{incoming:true});card.append(el('p',incoming.heard?'你已经听完。可以用自己的声音接住这份表达。':'完整听完这段声音，再用自己的声音回应。','voice-status'));
    const row=el('div',undefined,'voice-actions'),reply=action('用声音回应 ↗',()=>openCompose({type:'reply',id:incoming.id,title:incoming.title}),'primary');reply.disabled=!incoming.heard;row.append(reply,action('让它继续漂流',async()=>{await mutate('/api/skip',{id:incoming.id});say('这段声音继续漂流，你不会再接到同一段。');},'quiet'),action('不适合交流 · 举报',async()=>{await mutate('/api/report',{id:incoming.id,reason:'接收者认为这段声音不适合交流'});say('已记录举报，这段声音暂停漂流，并从你的接收页移除。');},'quiet'));card.append(row);$('incoming').append(card);
  }else $('incoming').append(empty('湖面暂时安静。','还没有其他参与者的声音在漂流。你可以先留下一段声音，或听一段场景演示。'));
  const ownVoices=data.mine.length+data.threads.reduce((n,t)=>n+t.messages.filter(c=>c.mine).length,0);$('garden-summary').replaceChildren();for(const [count,label]of [[ownVoices,'段我的声音'],[data.threads.length,'株共同植物'],[data.threads.filter(t=>t.connected).length,'次持续交流']]){const span=el('span');span.append(el('strong',String(count)),document.createTextNode(label));$('garden-summary').append(span);}
  $('connections').replaceChildren();for(const thread of data.threads){
    const card=el('article',undefined,'connection-card'),emblem=el('div','✳','plant-emblem');emblem.append(el('span',thread.messages.length>1?'继续生长':'第一次共生'));card.append(emblem,el('h3',thread.original.title),el('p',`${thread.original.name} 的声音，得到 ${thread.messages[0]?.name||'一个人'} 的回应。${thread.messages.length+1} 段声音保留各自来历。`));
    const row=el('div',undefined,'voice-actions');row.append(action('▷ 一起听这株植物',()=>playSequence([thread.original,...thread.messages].filter(c=>c.playable),thread),'primary'));card.append(row);const voices=el('div',undefined,'conversation-voices');voices.append(voiceCard(thread.original));for(const message of thread.messages.slice(-2))voices.append(voiceCard(message));card.append(voices);if(thread.messages.length>2){const earlier=document.createElement('details');earlier.className='earlier-voices';earlier.append(el('summary',`更早的 ${thread.messages.length-2} 段声音`));for(const message of thread.messages.slice(0,-2))earlier.append(voiceCard(message));card.append(earlier);}
    const soundscape=el('div',undefined,'soundscape'),select=document.createElement('select');select.setAttribute('aria-label','共同植物的背景声音');for(const [v,l]of [['none','只有我们的声音'],['rain','雨声陪伴'],['wind','微风陪伴'],['bells','钟声陪伴']])select.add(new Option(l,v));select.value=thread.ambience;
    const slider=document.createElement('input');slider.type='range';slider.min=0;slider.max=100;slider.value=thread.level*100;slider.setAttribute('aria-label','背景声音的音量');const volume=el('label','背景音量');volume.append(slider);const update=async()=>{await mutate(`/api/thread/${thread.id}/soundscape`,{ambience:select.value,level:Number(slider.value)/100});say('共同植物的背景声音已保存，人声录音保持原样。');};select.onchange=()=>update().catch(e=>say(e.message));slider.onchange=select.onchange;soundscape.append(el('span','声音搭配'),select,volume);card.append(soundscape);
    const relation=['withdrawn','review','blocked'].includes(thread.original.status)?'原声音暂未开放，持续交流暂停。':thread.connected?'你们都愿意继续交流，可以留下新的声音。':thread.myWish?'你的心意已经留下，等待对方也愿意。':thread.theirWish?'对方愿意继续听见你，由你决定是否回应。':'双方都愿意时，这株植物会开放持续交流。';card.append(el('p',relation));
    const contact=el('div',undefined,'voice-actions');contact.append(action(thread.myWish?'收回继续交流意愿':'愿意继续听见彼此',async()=>{await mutate(`/api/thread/${thread.id}/wish`,{want:!thread.myWish});say('交流意愿已更新，双方都愿意才开放新留言。');},'secondary'));
    if(thread.connected)contact.append(action('再留一段声音 ↗',()=>openCompose({type:'message',id:thread.id,title:thread.original.title}),'primary'));card.append(contact);$('connections').append(card);
  }
  if(!data.threads.length)$('connections').append(empty('共同植物，会从一次回应开始。','接住一段声音，听完后回应；或等待有人接住你的漂流。'));
  $('my-clips').replaceChildren();const solo=data.mine.filter(clip=>!data.threads.some(t=>t.original.id===clip.id));solo.forEach(clip=>$('my-clips').append(voiceCard(clip,{own:true})));if(!solo.length)$('my-clips').append(empty(data.threads.length?'声音已经留在共同植物里。':'先种下属于自己的声音。',data.threads.length?'你也可以继续种下新的独立声音。':'可以只保留给自己，也可以让它漂流。'));
  controls();
}
function openCompose(next){if(recording||draft||pending){say('当前还有未提交的声音。先提交或点“重新录制”清空，再开始另一段回应。');return;}mode=next;setView('leave');$('compose-heading').textContent=next?'把回应交给这个人。':'此刻，你想留下什么？';$('compose-context').textContent=next?`回应「${next.title}」。你的声音会与原声音一起长成共同植物。`:'可以是一句想说的话，也可以是窗外的雨、今天经过的一条街。';$('mode-badge').textContent=next?'声音回应':'新的声音';$('consent-copy').textContent=next?'我愿意把这段回应交给对方，并留在共同植物中。':'我愿意让接住它的一位体验者听见这段声音。';$('keep').hidden=!!next;$('cancel-reply').hidden=!next;$('consent').checked=false;controls();$('clip-title').value='';$('clip-note').value='';$('record').focus({preventScroll:true});}
function audioContext(){if(!context)context=new AudioContext();return context;}
function stopAmbience(){ambiTimers.forEach(clearTimeout);ambiTimers=[];for(const node of ambience){try{node.stop?.();node.disconnect();}catch{}}ambience=[];}
function startAmbience(kind,amount){stopAmbience();if(kind==='none'||amount<=0||!context)return;const gain=context.createGain();gain.gain.value=amount*.09;gain.connect(scene.output());ambience.push(gain);
  if(kind==='rain'||kind==='wind'){const buffer=context.createBuffer(1,context.sampleRate*3,context.sampleRate),samples=buffer.getChannelData(0);let n=713,previous=0;for(let i=0;i<samples.length;i++){n=n*16807%2147483647;const white=n/1073741824-1;previous=(previous+.04*white)/1.04;samples[i]=kind==='wind'?previous*3:white;}const source=context.createBufferSource(),filter=context.createBiquadFilter();source.buffer=buffer;source.loop=true;filter.type='lowpass';filter.frequency.value=kind==='rain'?1800:500;source.connect(filter);filter.connect(gain);source.start();ambience.push(source,filter);
  }else{const bell=()=>{if(!playing)return;const osc=context.createOscillator(),envelope=context.createGain(),at=context.currentTime;osc.frequency.value=[523.25,659.25,783.99][Math.floor(performance.now()/2000)%3];envelope.gain.setValueAtTime(.15,at);envelope.gain.exponentialRampToValueAtTime(.0001,at+1.6);osc.connect(envelope);envelope.connect(gain);osc.start();osc.stop(at+1.7);ambience.push(osc,envelope);ambiTimers.push(setTimeout(bell,2400));};bell();}
}
function stopPlayer(){scene?.stopStory();playEpoch++;if(playing){playing.audio.onended=null;playing.audio.onerror=null;playing.audio.pause();playing.audio.src='';playing.source?.disconnect();playing=null;}if(playURL)URL.revokeObjectURL(playURL);playURL='';stopAmbience();$('player-dock').hidden=true;level=0;}
async function audioBlob(clip){const response=await fetch('/api/audio/'+encodeURIComponent(clip.id),{headers:{Authorization:'Bearer '+active}});if(!response.ok){const error=await response.json();throw Error(error.error||'无法打开声音。');}return response.blob();}
async function playSequence(clips,thread){if(!clips.length){say('这株植物暂时没有开放的声音。');return;}stopPlayer();if(recording){say('先结束录音，再倾听其他声音。');return;}setView('listen');if(thread||clips[0].id!==data.incoming?.id){$('view-listen').hidden=true;document.querySelector('.shore').classList.remove('has-incoming');}const identity=active,epoch=playEpoch;
  try{await audioContext().resume();if(active!==identity||epoch!==playEpoch)return;const audio=new Audio(),source=context.createMediaElementSource(audio),meter=context.createAnalyser();meter.fftSize=128;source.connect(meter);meter.connect(scene.output());playing={audio,source,meter};const session=playing;
    async function next(index){if(playing!==session||active!==identity)return;const clip=clips[index];scene.selectClip(clip,thread);const blob=await audioBlob(clip);if(playing!==session||active!==identity)return;try{const decoded=await context.decodeAudioData(await blob.arrayBuffer());if(playing!==session||active!==identity)return;scene.fingerprint(decoded);}catch{}if(playURL)URL.revokeObjectURL(playURL);playURL=URL.createObjectURL(blob);audio.src=playURL;$('player-label').textContent=`正在听 · ${clip.name} / ${clip.title}`;$('player-dock').hidden=false;$('play-progress').value=0;audio.ontimeupdate=()=>{$('play-progress').value=Math.min(1,audio.currentTime/clip.duration);};audio.onended=async()=>{try{const nextState=await api('/api/heard',{id:clip.id});if(active!==identity||playing!==session)return;data=nextState;scene.heard(!!thread);render();if(index+1<clips.length)await next(index+1);else{stopPlayer();say('这段声音已听完。你可以回应，或再听一次。');}}catch(error){if(playing===session){stopPlayer();say(error.message);}}};audio.onerror=()=>{if(playing===session){stopPlayer();say('这个音频暂时无法播放，原声音仍保留。');}};await audio.play();}
    await next(0);if(playing===session)startAmbience(thread?.ambience||scene.weather(),thread?.level??.12);
  }catch(error){stopPlayer();say(error.message||'声音未能打开，请再点一次试听。');}
}
async function downloadVoice(clip){const blob=await audioBlob(clip),url=URL.createObjectURL(blob),link=document.createElement('a');link.href=url;link.download=clip.title.replace(/[<>:"/\\|?*]/g,'_')+'.'+({'audio/wav':'wav','audio/webm':'webm','audio/ogg':'ogg','audio/mp4':'m4a'}[blob.type]||'audio');link.click();setTimeout(()=>URL.revokeObjectURL(url),60000);say('已生成原声音下载；文件保留原始录音。');}
function releaseDraft(){if(draftURL)URL.revokeObjectURL(draftURL);draftURL='';draft=null;pending=null;$('draft-audio').pause();$('draft-audio').removeAttribute('src');$('draft-tools').hidden=true;$('record-caption').textContent='1–30 秒 · 先试听，再决定交给谁';$('record-clock').textContent='00:00';controls();}
async function loadDraft(blob,name='这一刻的声音'){const revision=titleRevision;if(blob.size>6*1024*1024)throw Error('请选择小于 6 MB 的声音文件。');const bytes=await blob.arrayBuffer(),decoded=await audioContext().decodeAudioData(bytes.slice(0));if(decoded.duration<1||decoded.duration>30)throw Error('请选择 1–30 秒的声音。');
  let mime=blob.type.split(';')[0];if(mime==='audio/x-wav'||name.toLowerCase().endsWith('.wav'))mime='audio/wav';if(name.toLowerCase().endsWith('.m4a'))mime='audio/mp4';if(!['audio/webm','audio/ogg','audio/wav','audio/mp4'].includes(mime))throw Error('请选择 WAV、WebM、OGG 或 M4A 音频。');
  releaseDraft();scene.previewDraft(decoded);draft={blob:new Blob([bytes],{type:mime}),duration:decoded.duration,mime,requestId:crypto.randomUUID()};draftURL=URL.createObjectURL(draft.blob);$('draft-audio').src=draftURL;$('draft-tools').hidden=false;$('draft-description').textContent=`${decoded.duration.toFixed(1)} 秒 · 还未提交`;$('record-clock').textContent='00:'+String(Math.ceil(decoded.duration)).padStart(2,'0');$('record-caption').textContent='先给自己听，再决定是否送出去。';if(revision===titleRevision&&!$('clip-title').value)$('clip-title').value=name.replace(/\.[^.]+$/,'').slice(0,40);controls();say('声音已准备好，试听后可以投放、回应，或只种在自己的花园。');}
function closeMic(){clearInterval(recordTimer);stream?.getTracks().forEach(t=>t.stop());stream=null;recordSource?.disconnect();recordSource=null;analyser=null;recording=false;document.body.classList.remove('recording');$('record').textContent='开始录音';controls();}
async function record(){if(recording){recorder.stop();closeMic();return;}if(busy)return;stopPlayer();if(!navigator.mediaDevices?.getUserMedia||!window.MediaRecorder){say('这个浏览器暂不支持录音，可以选择已有的声音文件。');return;}
  busy=true;controls();try{releaseDraft();stream=await navigator.mediaDevices.getUserMedia({audio:{echoCancellation:true,noiseSuppression:true},video:false});if(document.hidden)throw Error('页面已离开');await audioContext().resume();if(document.hidden)throw Error('页面已离开');analyser=context.createAnalyser();analyser.fftSize=128;recordSource=context.createMediaStreamSource(stream);recordSource.connect(analyser);const mime=['audio/webm;codecs=opus','audio/ogg;codecs=opus','audio/mp4'].find(m=>MediaRecorder.isTypeSupported(m));recorder=new MediaRecorder(stream,{...(mime?{mimeType:mime}:{}),audioBitsPerSecond:64000});const chunks=[];recorder.ondataavailable=e=>{if(e.data.size)chunks.push(e.data);};const capture=recorder;recorder.onstop=async()=>{busy=true;const blob=new Blob(chunks,{type:capture.mimeType});closeMic();try{await loadDraft(blob,mode?'回应这一刻':'这一刻的声音');}catch(error){say(error.message||'录音暂时无法解码，可以再试一次或选择声音文件。');}finally{busy=false;controls();}};recorder.onerror=()=>{closeMic();say('录音中断，请重新录制或选择文件。');};recording=true;document.body.classList.add('recording');$('record').textContent='结束录音';$('record-caption').textContent='正在听见你 · 最长 30 秒';recordStart=performance.now();recorder.start();recordTimer=setInterval(()=>{const seconds=Math.floor((performance.now()-recordStart)/1000);$('record-clock').textContent='00:'+String(seconds).padStart(2,'0');if(performance.now()-recordStart>=29500&&recorder.state==='recording'){recorder.stop();closeMic();}},200);controls();say('正在录音，结束后先在本机试听。');
  }catch(error){closeMic();say(error.name==='NotAllowedError'?'录音权限未打开。你可以选择声音文件，或在浏览器中允许麦克风后重试。':'麦克风暂时无法打开，可以选择已有声音文件。');}finally{busy=false;controls();}
}
async function submit(visibility){if(!draft||busy||recording||!online)return;if(pending&&pending.visibility!==visibility){say('上一份提交尚未确认，请先点击原按钮安全重试。');return;}if((visibility==='drift'||mode)&&!$('consent').checked){say('请先确认是否愿意把这段声音交给对方。');return;}
  const title=$('clip-title').value.trim();if(!title){$('clip-title').focus();say('给这段声音起个名字，接住它的人会更容易理解。');return;}busy=true;controls();
  try{if(!pending){const encoded=await new Promise((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(String(reader.result).split(',')[1]);reader.onerror=reject;reader.readAsDataURL(draft.blob);});const path=mode?.type==='reply'?'/api/reply':mode?.type==='message'?`/api/thread/${mode.id}/message`:'/api/clips';pending={visibility,path,body:{requestId:draft.requestId,audio:encoded,mime:draft.mime,duration:draft.duration,title,note:$('clip-note').value.trim(),intention:$('intention').value,mood:$('mood').value,visibility,consent:$('consent').checked,...(mode?.type==='reply'?{id:mode.id}:{})}};}
    data=await api(pending.path,pending.body);const wasReply=!!mode;releaseDraft();mode=null;$('clip-title').value='';$('clip-note').value='';openCompose(null);render();setView('listen');scene.submitted(wasReply,visibility);say(wasReply?'你的声音已经抵达对方，共同植物记住了这次回应。':visibility==='drift'?'声音已经出发。有人接住并回应时，会在花园里留下共同植物。':'这段声音只种在自己的花园，没有投放漂流。');
  }catch(error){say(error.message+' 录音仍保留，可重试同一份提交。');}finally{busy=false;controls();}
}
async function newIdentity(name){if(identityIssue)throw Error('请先保留原身份记录；本机记录不可写时不能新建身份。');if(identities.length>=8)throw Error('当前浏览器最多保留 8 个体验身份。');const result=await api('/api/session',{name});identities.push(result);active=result.token;saveIdentities();data=await api('/api/state');render();say(`现在是「${result.name}」。可以留下声音，或接住其他身份的漂流。`);}
function switchingSafe(){if(recording||draft||busy){say('先提交当前声音，或点“重新录制”清空，再切换身份。');return false;}stopPlayer();mode=null;return true;}
async function poll(){if(!active||!online||document.hidden||recording||busy)return;const identity=active;try{const oldCount=data.threads.reduce((n,t)=>n+t.messages.length,0),next=await api('/api/state');if(active!==identity)return;if(JSON.stringify(data)!==JSON.stringify(next)){data=next;render();}$('service-label').textContent='本机社区试用 · 声音保存在这台服务，相遇来自实际参与者';if(next.threads.reduce((n,t)=>n+t.messages.length,0)>oldCount){scene.received();say('花园收到新的声音回应。');}}catch(error){$('service-label').textContent='连接暂时中断 · 原录音留在本机服务';}}
$('settings-open').onclick=()=>{$('identity-panel').hidden=!$('identity-panel').hidden;};$('settings-close').onclick=()=>{$('identity-panel').hidden=true;};
$('new-identity').onclick=async()=>{if(!switchingSafe())return;try{await newIdentity($('profile-name').value.trim()||'未署名');openCompose(null);}catch(error){say(error.message);}};
$('switch-identity').onclick=async()=>{if(!switchingSafe())return;active=$('identities').value;saveIdentities();try{data=await api('/api/state');render();openCompose(null);say('已切换体验身份；双方的声音与交流意愿独立保存。');}catch(error){say(error.message);}};
$('rename').onclick=async()=>{try{data=await api('/api/profile',{name:$('profile-name').value.trim()});current().name=data.profile.name;saveIdentities();render();say('公开昵称已更新。');}catch(error){say(error.message);}};
document.querySelectorAll('[data-view]').forEach(button=>button.onclick=()=>setView(button.dataset.view));$('clip-title').addEventListener('input',()=>titleRevision++);$('record').onclick=()=>void record();$('audio-file').onchange=async event=>{const file=event.target.files[0];if(!file)return;stopPlayer();busy=true;controls();try{if(pending)throw Error('上一份提交尚未确认，请先重试或清空草稿。');await loadDraft(file,file.name);}catch(error){say(error.message||'这个声音无法解码，请换一个文件。');}finally{event.target.value='';busy=false;controls();}};
$('discard-draft').onclick=()=>{releaseDraft();scene.clearDraft();say('未提交的录音已清空，可以重新录制。');};$('consent').onchange=controls;$('send').onclick=()=>void submit('drift');$('keep').onclick=()=>void submit('private');$('cancel-reply').onclick=()=>{mode=null;pending=null;$('compose-heading').textContent='此刻，你想留下什么？';$('compose-context').textContent='声音草稿保留，你可以只种在自己的花园。';$('mode-badge').textContent='新的声音';$('consent-copy').textContent='我愿意让接住它的一位体验者听见这段声音。';$('consent').checked=false;$('keep').hidden=false;$('cancel-reply').hidden=true;controls();};
$('find-voice').onclick=async()=>{try{if(recording||busy)return;await mutate('/api/next',{});setView('listen');$('view-listen').hidden=false;document.querySelector('.shore').classList.add('has-incoming');if(data.incoming)scene.selectClip(data.incoming);say(data.incoming?'一段声音抵达了。先听完，再决定是否回应。':'暂时没有其他体验者的声音在漂流。可以先留下声音，稍后再来。');}catch(error){say(error.message);}};$('refresh').onclick=()=>void poll();$('stop-player').onclick=stopPlayer;
document.addEventListener('visibilitychange',()=>{if(document.hidden){stopPlayer();$('draft-audio').pause();if(recording&&recorder?.state==='recording'){recorder.stop();closeMic();}if(context)void context.suspend();}else void poll();});window.addEventListener('pagehide',()=>{closeMic();stopPlayer();});
for(let i=0;i<27;i++)$('wave-bars').append(el('i'));
scene=createDriftScene({publicDemo,getContext:audioContext,getMeter:()=>recording?analyser:playing?.meter||(!$('draft-audio').paused?draftMeter:null),onWeather:kind=>{if(playing)startAmbience(kind,.16);},onBeforeStory:()=>{
  if(recording||busy){say('先结束录音，再听这段相遇。');return false;}stopPlayer();$('draft-audio').pause();
  for(const name of ['leave','listen','garden'])$('view-'+name).hidden=true;$('identity-panel').hidden=true;document.querySelector('.shore').classList.remove('has-incoming');window.scrollTo({top:0,behavior:'instant'});return true;
},onMessage:say});
$('close-compose').onclick=()=>setView('listen');$('close-listen').onclick=()=>{$('view-listen').hidden=true;document.querySelector('.shore').classList.remove('has-incoming');};
$('draft-audio').onplay=async()=>{stopPlayer();const ctx=audioContext();if(!draftSource){draftSource=ctx.createMediaElementSource($('draft-audio'));draftMeter=ctx.createAnalyser();draftMeter.fftSize=256;draftSource.connect(draftMeter);draftMeter.connect(scene.output());}await ctx.resume();};
document.addEventListener('keydown',event=>{if(event.key==='Escape'){setView('listen');$('view-listen').hidden=true;$('identity-panel').hidden=true;document.querySelector('.shore').classList.remove('has-incoming');}});
render();setView('listen');statusTimer=setTimeout(()=>$('status').classList.add('idle'),10000);
async function boot(){
  // Pages publishes the score and scene; real voice exchange needs the local server.
  if(publicDemo){
    online=false;controls();$('settings-open').hidden=true;
    document.querySelectorAll('[data-view="garden"]').forEach(button=>button.hidden=true);
    const leave=document.querySelector('.shore-actions [data-view="leave"]');leave.textContent='体验声音种植';leave.onclick=()=>location.href='../';
    $('find-voice').textContent='查看研究摘要 ↗';$('find-voice').onclick=()=>location.href='../../';
    $('scene-credit').textContent='公开声景演示 · 原创音乐与文字，无真人配音';
    say('点击听一段相遇。真实声音漂流与社区仅在本机服务中运行。');return;
  }
  try{await api('/api/health');online=true;document.querySelectorAll('[data-legacy]').forEach(link=>link.href='http://127.0.0.1:8940/garden/'+(link.dataset.legacy==='ecosystem'?'ecosystem/':''));$('service-label').textContent='本机社区试用 · 声音保存在这台服务，相遇来自实际参与者';if(identityIssue){controls();return;}if(!active)await newIdentity('未署名');else{data=await api('/api/state');render();say('戴上耳机。先听一段相遇，再留下属于你的声音。');}}catch(error){online=false;$('service-label').textContent='社区服务未连接 · 原版本与本机录音入口保留';say(error.message+' 请运行 server/drift_server.py 并打开 8941 端口。');controls();}}
void boot();setInterval(()=>void poll(),15000);
