import {PLAN_VERSION,normalizeBrief,normalizePlan,briefExample,briefKey,assertPlanMatches,classifyProduct} from './planning-contract.js';
export {briefExample,briefKey};
const baseRequirements=[{area:'可读与布局',requirement:'主要产品、标题与操作在桌面和手机保持完整，文字和控件不互相遮挡。',verify:'检查 1440、768、390 像素视口的真实截图与点击目标。'},{area:'状态与交付',requirement:'选择、说明、结果和下载使用同一状态源；独立包携带实际使用的素材。',verify:'修改选项后实际下载并核对，再解压阻断外部资源运行。'}];
const profiles={
  headphones:{direction:'静谧棚拍 / 夜色声场',composition:'左侧简短标题与选型入口，右侧完整头戴轮廓；下方材质特写连接实时选配。',materials:'区分铝制外壳、柔软耳垫与头梁包覆，检查弧线、接缝、柔光高光和金属控制件。',interactions:['旋转观察','选择配色','比较表面','折叠观察','部件展开'],flow:['看系列外观','看材质细节','调整配色与表面','观察折叠与部件','导出配置'],missing:['厂商确认的型号、重量、续航和连接规格','真实照片、标准模型与允许的折叠结构'],asset:'头戴轮廓、耳罩近景、手机竖版、环境反射',verify:'各配色、正面/侧面、折叠 0/50/100% 和展开状态分别捕获，检查穿模、接缝与高光。'},
  toilet:{direction:'卫浴产品展示',composition:'完整产品与生活空间建立首屏，细节、型号选型和现场条件分段组织。',materials:'陶瓷连续曲面、釉面高光、盖板与金属控制件；环境有明确接地关系。',interactions:['旋转观察','选择配色','开盖观察','型号比较','现场条件核对'],flow:['看产品','比较型号','观察外观与开盖','核对现场条件','导出选型'],missing:['真实型号与厂商图纸','坑距、供水、电源与安装服务确认'],asset:'系列影像、陶瓷近景、手机竖版、石材与反射环境',verify:'三款正面/侧面、盖板 0/50/100% 和现场缺失/冲突样本逐项验收。'},
  lamp:{direction:'灯具与材质展示',composition:'先看灯具外观与照明氛围，再比较配色和结构。',materials:'灯罩涂层、金属与扩散部件分别呈现，灯光影响实际画面。',interactions:['旋转观察','选择配色','比较表面','调整灯光','部件展开'],flow:['看灯具','调整配色','比较表面与灯光','观察结构','导出配置'],missing:['厂商真实型号与照明参数','真实尺寸、图片或模型'],asset:'灯具影像、材质细节、竖版构图、反射环境',verify:'配色、表面、灯光与结构改变后对照实际画面和下载。'},
  other:{direction:'待确定的产品专属视觉',composition:'围绕本次用户任务组织产品介绍、差异与下一步；关键画面在制作前形成。',materials:'根据真实产品图片和材料清单确定表面与细节，当前不预设产品形体。',interactions:['查看产品信息','比较已提供选项','保留需求'],flow:['看懂产品','比较已提供的信息','确认选择或需求','导出制作要求'],missing:['该产品的目录、素材与任务规则','产品专属展示或交互模块尚未实现'],asset:'产品专属主视觉、必要细节、手机构图',verify:'先实现对应模块再完成实际任务；不得用耳机或马桶改名冒充。'}
};
export function localPlan(raw){const b=normalizeBrief(raw),category=classifyProduct(b.product),p=profiles[category];return normalizePlan({schemaVersion:PLAN_VERSION,category,product:b.product,summary:`为${b.audience||'产品访客'}实现：${b.goal}`,headline:category==='headphones'?'把世界，调成自己的节奏。':b.product+'，看得更清楚。',tagline:b.goal,userFlow:p.flow,visual:{direction:b.preference||p.direction,composition:p.composition,materials:p.materials,mobile:'制作独立竖版，标题和按钮置于产品之外；模型与选项改为纵向。',palette:['#ece6da','#292a28','#91806b']},requirements:[{area:'本次任务',requirement:b.goal,verify:'实际完成输入目标对应的任务；尚未实现的部分列入缺失项。'},{area:'产品表现',requirement:p.materials,verify:p.verify},{area:'优先级与风格',requirement:[b.priority,b.preference].filter(Boolean).join('；')||'先保证产品可理解，再检查细节。',verify:'把实际关键画面与选定方向一起比较。'},...baseRequirements],assets:[{name:'系列视觉',role:p.asset,status:b.materials||'待提供或制作'}],interactions:p.interactions,missing:p.missing,acceptance:[p.verify,'完成一次选择，核对画面与实际导出一致。','解压交付包独立运行，并检查手机布局。'],assumptions:['这是按已知任务规则整理的草案，不是本次在线模型输出。','资料缺失时先保留缺口；示例参数不当作真实产品性能。']});}
// Authored by the assistant in this build, stored so the complete demonstration runs without API credentials.
export const headphoneDemo=normalizePlan({...localPlan(briefExample),summary:'为关注外观的购买者制作 AURA 原创耳机系列展示。用暖色棚拍建立印象，以可操作的金属/耳垫/头梁模型比较配色、表面和结构，留下当前选择。',headline:'把世界，调成自己的节奏。',tagline:'从一条弧线，到每一次聆听。看清材质，也找到自己的配色。',requirements:[{area:'品牌首屏',requirement:'暖白摄影空间、完整银色耳机、左文右物。手机使用同一产品的独立竖版。',verify:'1440×820 与 390×844 下主体、标题和主按钮都完整可见。'},{area:'材质细节',requirement:'银色铝壳、深色皮革耳垫、弧形头梁与金属旋钮保持同一设计语言。',verify:'首屏与近景并排检查产品识别点，不以泛化耳机图补图。'},{area:'实时选配',requirement:'银、石墨与橄榄配色；哑光/亮面；旋转、折叠和分层观察实际改变模型。',verify:'每种操作检查实际像素与配置，折叠 0/50/100% 检查部件关系。'},{area:'观察环境',requirement:'可切暖色摄影棚与夜色声场，轮廓与材质保持可读。',verify:'环境实际改变灯光与背景；操作后导出保存该环境。'},...baseRequirements],assets:[{name:'横版系列影像',role:'暖色首屏产品构图',status:'本次 ImageGen 制作并接入'},{name:'竖版系列影像',role:'手机专用完整构图',status:'本次 ImageGen 制作并接入'},{name:'材质特写',role:'铝壳、皮革接缝与金属控制件',status:'本次 ImageGen 制作并接入'},{name:'原创三维形体',role:'实际换色、折叠、旋转和展开',status:'原创参数化概念模型'}],assumptions:['本方案由本次制作中的模型生成并预置，不是点击按钮后调用在线模型。','AURA 为原创概念案例，固定系列影像与实时模型分别表达。','没有厂商规格，不生成续航、音质或降噪性能承诺。']});
export function modelServiceURL(route){return ['localhost','127.0.0.1','[::1]'].includes(globalThis.location?.hostname)?'http://127.0.0.1:8952/api/'+route:null;}
export async function requestModelPlan(brief,{signal}={}){const endpoint=modelServiceURL('plan');if(!endpoint)throw new Error('公开静态演示尚未部署在线模型服务，请使用预置示例或本地规则整理。');const b=normalizeBrief(brief),r=await fetch(endpoint,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(b),signal});let data;try{data=await r.json();}catch{throw new Error('模型服务返回格式不可读取。');}if(!r.ok)throw new Error(data.error||'在线生成失败，请稍后重试。');return {plan:assertPlanMatches(normalizePlan(data.plan),b),provider:'model',model:data.model,requestId:data.requestId};}
