import {presentPlan,productionBrief} from './studio-presentation.js?v=20261003-16';
import {clone,escapeHTML as esc} from './core.js?v=20261003-16';
import {planToProduct,planSources as sources} from './studio-product.js';
import {normalizeBrief,normalizePlan,adapterNames,assertPlanMatches} from './planning-contract.js';
import {briefExample,briefKey,headphoneDemo,localPlan,requestModelPlan,modelServiceURL} from './planner.js';
const $=s=>document.querySelector(s),key='011.foundry.plan.v1',fields=Object.keys(briefExample);let record=null,dirty=false,reviewDirty=false,busy=false,request=0,controller;
const input=()=>normalizeBrief(Object.fromEntries(fields.map(k=>[k,$('#brief-'+k).value])));
function fill(b){fields.forEach(k=>$('#brief-'+k).value=b[k]||'');}
let live=null,previewRequest=0,previewSaveTimer;
function persistRecord(){try{localStorage.setItem(key,JSON.stringify(record));}catch{status('当前修改未能存入浏览器，请下载保留。');}}
function invalidateLive(){previewRequest++;live?.dispose();live=null;$('#studio-live').hidden=true;document.body.classList.remove('has-live-preview');clearTimeout(previewSaveTimer);}
async function refreshLive(){
  invalidateLive();if(record.plan.category!=='headphones')return;
  const id=previewRequest,owner=record,cfg=planToProduct(owner);
  try{const {mountStudioLive}=await import('./studio-live.js?v=20261003-16');if(id!==previewRequest||dirty||reviewDirty)return;
    $('#studio-live').hidden=false;document.body.classList.add('has-live-preview');
    live=mountStudioLive($('#studio-live'),cfg,{onOpen:openProduct,onChange(selection){if(owner!==record||id!==previewRequest||dirty||reviewDirty)return;owner.previewSelection=selection;clearTimeout(previewSaveTimer);previewSaveTimer=setTimeout(persistRecord,250);}});
  }catch{if(id===previewRequest){invalidateLive();status('工作台内的模型暂未加载，可点击试用对应产品重新尝试。',true);}}
}
addEventListener('pagehide',()=>{clearTimeout(previewSaveTimer);if(record&&!dirty&&!reviewDirty)persistRecord();invalidateLive();});
function status(v,error=false){$('#studio-status').textContent=v;$('#studio-status').dataset.error=String(error);}
function stale(){dirty=true;request++;controller?.abort();busy=false;invalidateLive();$('#generate-plan').disabled=false;$('#generate-plan').innerHTML='整理制作方案 <span>↗</span>';$('#open-plan-product').disabled=true;$('#download-plan').disabled=true;$('#download-brief').disabled=true;$('#plan-source').textContent=record?'目标已修改':'等待目标';status('目标或偏好已修改，重新整理后更新方案与产品。');if($('#plan-provider').value==='demo'){try{if(briefKey(input())!==briefKey(briefExample))$('#plan-provider').value='local-rules';}catch{$('#plan-provider').value='local-rules';status('请填写产品名称和目标，再整理方案。');}}}
function render(){const p=record.plan;$('#plan-empty').hidden=true;$('#plan-content').hidden=false;$('#plan-actions').hidden=false;$('#plan-source').textContent=sources[record.provider]||'导入方案';$('#plan-content').innerHTML=`<p class="s-plan-summary">${esc(p.summary)}</p><ol class="s-plan-flow">${p.userFlow.map((v,i)=>`<li>${i+1} / ${esc(v)}</li>`).join('')}</ol><section class="s-plan-section"><h3>视觉方向</h3><dl class="s-plan-visual"><dt>风格</dt><dd>${esc(p.visual.direction)}</dd><dt>构图</dt><dd>${esc(p.visual.composition)}</dd><dt>材质</dt><dd>${esc(p.visual.materials)}</dd><dt>手机</dt><dd>${esc(p.visual.mobile)}</dd><dt>配色</dt><dd class="s-palette">${p.visual.palette.map(v=>`<i style="background:${v}" title="${v}"></i>`).join('')}</dd></dl></section><section class="s-plan-section"><h3>具体制作要求与验收</h3>${p.requirements.map(v=>`<article class="s-requirement"><h4>${esc(v.area)}</h4><p>${esc(v.requirement)}</p><small>验收：${esc(v.verify)}</small></article>`).join('')}</section><section class="s-plan-section"><h3>需要的操作</h3><p>${p.interactions.map(esc).join(' · ')}</p><details><summary>素材、缺失资料与验收任务</summary><ul>${p.assets.map(v=>`<li>${esc(v.name)} / ${esc(v.role)} / ${esc(v.status)}</li>`).join('')}</ul><h3>还需提供</h3><ul>${p.missing.map(v=>`<li>${esc(v)}</li>`).join('')}</ul><h3>验收任务</h3><ul>${p.acceptance.map(v=>`<li>${esc(v)}</li>`).join('')}</ul><h3>方案依据</h3><ul>${p.assumptions.map(v=>`<li>${esc(v)}</li>`).join('')}</ul></details></section>`;
  presentPlan(record,{isStale:()=>dirty||busy,onEdit(){reviewDirty=true;invalidateLive();$('#open-plan-product').disabled=true;$('#download-plan').disabled=true;$('#download-brief').disabled=true;},onApply(plan,options){record={...record,plan,implementationOptions:options,revisions:[...(record.revisions||[]).slice(-19),{at:new Date().toISOString(),by:'user'}]};reviewDirty=false;render();persistRecord();},status});
  if(record.revisions?.length)$('#plan-source').textContent+=' · 已调整';const supported=p.category!=='other';$('#adapter-status').dataset.pending=String(!supported);$('#adapter-status').textContent=supported?`${adapterNames[p.category]}已有运行模块：可以带着本次目标试用，再下载独立包。专属素材与形体仍采用已实现的概念系列。`:'制作要求已整理。该产品的形体、素材与业务模块尚未实现；可下载清单继续制作，不会套用耳机画面。';$('#open-plan-product').disabled=!supported||dirty;$('#download-plan').disabled=dirty||reviewDirty;$('#download-brief').disabled=dirty||reviewDirty;status(record.provider==='demo'?'已载入本次模型生成的耳机示例方案；点击试用可验证实际画面。':record.provider==='model'?'在线模型已生成方案，仍需按具体要求检查画面和任务。':'已按本地规则整理草案，输入目标和偏好已进入要求。');
  refreshLive();
}
async function generate(e){e?.preventDefault();if(busy)return;let b;try{b=input();}catch(error){status(error.message,true);return;}const mode=$('#plan-provider').value,id=++request;busy=true;invalidateLive();$('#generate-plan').disabled=true;$('#open-plan-product').disabled=true;$('#download-plan').disabled=true;$('#download-brief').disabled=true;status('正在整理本次制作要求…');controller=new AbortController();const timeout=setTimeout(()=>controller.abort(),45000);
  try{let data;if(mode==='model')data=await requestModelPlan(b,{signal:controller.signal});else if(mode==='demo'){if(briefKey(b)!==briefKey(briefExample))throw new Error('耳机示例只对应示例目标；修改后请选择本地整理或在线生成。');data={plan:clone(headphoneDemo),provider:'demo',model:'本次制作中的 Codex 模型'};}else data={plan:localPlan(b),provider:'local-rules'};if(id!==request)return;record={schemaVersion:'1.0',brief:b,...data,createdAt:new Date().toISOString()};dirty=false;reviewDirty=false;render();persistRecord();const url=new URL(location);url.searchParams.delete('example');url.searchParams.set('revision','20261003-16');history.replaceState(null,'',url);
  }catch(error){if(id===request){dirty=true;$('#open-plan-product').disabled=true;$('#download-plan').disabled=true;$('#download-brief').disabled=true;status(error.name==='AbortError'?'生成已取消或超时，可以重新整理。':error.message,true);}}finally{clearTimeout(timeout);if(id===request){busy=false;$('#generate-plan').disabled=false;}}
}
$('#studio-form').addEventListener('submit',generate);fields.forEach(k=>$('#brief-'+k).addEventListener('input',()=>{try{stale();}catch{dirty=true;request++;controller?.abort();$('#open-plan-product').disabled=true;$('#download-plan').disabled=true;$('#download-brief').disabled=true;status('请填写产品名称和目标，再整理方案。');}}));$('#plan-provider').addEventListener('change',stale);
$('#use-headphone-example').addEventListener('click',()=>{request++;controller?.abort();busy=false;invalidateLive();fill(briefExample);$('#plan-provider').value='demo';$('#generate-plan').disabled=false;dirty=true;$('#open-plan-product').disabled=true;$('#download-plan').disabled=true;$('#download-brief').disabled=true;status('已填入耳机目标，整理后查看具体制作要求。');});
function openProduct(){try{if(!record||dirty||reviewDirty||busy)throw new Error('先整理当前目标。');assertPlanMatches(record.plan,input());const cfg=planToProduct(record);persistRecord();localStorage.setItem('011.foundry.studio-product.v1',JSON.stringify(cfg));location.href='./?from=studio&step=preview&revision=20261003-16';}catch(error){status(error.message,true);}}
$('#open-plan-product').addEventListener('click',openProduct);
$('#download-plan').addEventListener('click',()=>{if(!record||dirty||reviewDirty||busy)return;const url=URL.createObjectURL(new Blob([JSON.stringify(record,null,2)],{type:'application/json'})),a=document.createElement('a');a.href=url;a.download='experience-plan.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),10000);status('已下载本次输入、制作要求、来源与缺失项。');});
$('#download-brief').addEventListener('click',()=>{if(!record||dirty||reviewDirty||busy)return;const url=URL.createObjectURL(new Blob([productionBrief(record)],{type:'text/markdown'})),a=document.createElement('a');a.href=url;a.download='production-brief.md';a.click();setTimeout(()=>URL.revokeObjectURL(url),10000);status('已下载可阅读、可交接的制作简报。');});
fill(briefExample);try{const old=JSON.parse(localStorage.getItem(key)||'null');if(old&&new URLSearchParams(location.search).get('example')!=='headphones'){old.brief=normalizeBrief(old.brief);old.plan=assertPlanMatches(normalizePlan(old.plan),old.brief);record=old;fill(old.brief);$('#plan-provider').value=['demo','local-rules'].includes(old.provider)?old.provider:'local-rules';render();}}catch{status('上次方案无法恢复，已载入耳机目标。');}
async function health(){const endpoint=modelServiceURL('status');if(!endpoint){$('#model-status').textContent='公开静态演示：预置示例与本地规则可用；在线模型服务尚未部署。';return;}try{const r=await fetch(endpoint,{signal:AbortSignal.timeout(1600)}),data=await r.json();$('#plan-provider option[value=model]').disabled=!data.available;$('#model-status').textContent=data.available?'在线生成已连接；模型：'+data.model:'在线生成未配置 API 密钥，当前可验证示例与本地草案。';}catch{$('#model-status').textContent='在线服务尚未启动；示例与本地草案仍可使用。';}}health();
if(new URLSearchParams(location.search).get('example')==='headphones')generate();
