(() => {
  const data=window.DEMO_DATA,$=selector=>document.querySelector(selector),number=id=>String(id).padStart(2,'0');
  const escape=value=>String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  let current=0,active=document.body.dataset.activeView==='demo',observer;
  $('#product-art-gallery').innerHTML=data.map(item=>{const art=window.CASE_ART_DIRECTION[item.id],revision=art.revision||15,source=window.SOURCE_DATA.cases.find(s=>s.id===item.id);return `<article class="product-art-card" data-art-case="${item.id}" data-revision="${revision}"><div class="product-art-heading"><span>CASE ${number(item.id)} / ${escape(art.focus)}</span><b data-revised="${art.revised}">${art.revised?`v${revision} ${revision===16?'本轮精修':'主体重做'}`:'待主体重做'}</b></div><div class="product-art-pair"><figure><img src="${escape(art.source||source.poster)}" alt="${escape(source.title)}的原作参考画面" loading="lazy" width="640" height="360"><figcaption>原作参考 · ${escape(source.author)}</figcaption></figure><figure><img src="media/demo-${number(item.id)}.webp?v=${revision}" alt="${escape(item.title)}的当前真实渲染" loading="lazy" width="640" height="360"><figcaption>当前原型 · 实际运行画面</figcaption></figure></div><div class="product-art-copy"><h3>${escape(item.product)}</h3><p>${escape(art.gap)}</p><button type="button" data-demo-id="${item.id}">进入本例演示 <span aria-hidden="true">↗</span></button></div></article>`;}).join('');
  $('#prototype-product-rows').innerHTML=data.map(item=>`<tr><td>${number(item.id)} · ${escape(window.SOURCE_DATA.cases.find(source=>source.id===item.id).title)}</td><td>${escape(item.product)}</td><td>${escape(item.task)}</td><td><button type="button" data-demo-id="${item.id}">操作本例 ↗</button></td></tr>`).join('');
  $('#demo-selector').innerHTML=data.map(item=>`<button class="demo-option" type="button" data-demo-id="${item.id}" aria-pressed="false"><img src="media/demo-${number(item.id)}.webp?v=${window.CASE_ART_DIRECTION[item.id]?.revision||15}" alt="${escape(item.title)}的实际演示画面" loading="lazy" width="420" height="263"><div class="demo-option-text"><span class="meta"><b>CASE ${number(item.id)}</b><span>${escape(item.kind)}</span></span><strong>${escape(item.title)}</strong><small>${escape(item.product)}</small></div></button>`).join('');
  $('#demo-selector').querySelectorAll('img').forEach(img=>img.addEventListener('error',()=>{img.dataset.missing='true';const cover=document.createElement('div');cover.className='demo-option-placeholder';cover.textContent='CASE '+number(img.closest('button').dataset.demoId);img.after(cover);},{once:true}));
  function visibility(){ $('#lab-frame').contentWindow?.postMessage({type:'lab-visibility',visible:active},location.origin); }
  function select(id){
    const item=data.find(record=>record.id===Number(id))||data[0];if(current===item.id)return;current=item.id;
    const source=window.SOURCE_DATA.cases.find(record=>record.id===current);
    $('#demo-selector').querySelectorAll('button').forEach(button=>button.setAttribute('aria-pressed',String(Number(button.dataset.demoId)===current)));
    $('#demo-stage-header').innerHTML=`<div class="demo-stage-heading"><div><p class="eyebrow">CASE ${number(current)} / ${escape(item.kind)}</p><h3>${escape(item.title)}</h3><p>${escape(item.scenario)}</p></div><div class="demo-stage-actions"><a href="labs/?id=${current}&v=16" target="_blank" rel="noreferrer">独立打开本例 ↗</a><button type="button" data-case-link="${current}">查看原案例拆解 ↗</button></div></div>`;
    const ref=item.reference,analysis=window.CASE_OPTIMIZATION_DATA?.[current];
    const list=values=>`<ul>${values.map(value=>`<li>${escape(value)}</li>`).join('')}</ul>`;
    $('#demo-mapping').dataset.analysisCaseId=String(current);
    $('#demo-mapping').innerHTML=`<div><b>01 / 本例的原作目标</b><p>${escape(analysis?.sourceTarget||ref.focus)}</p></div><div><b>02 / 本例优化前的问题</b><p>${escape(analysis?.diagnosis||'本例的独立分析尚未加载，请刷新本页。')}</p></div><div><b>03 / 本例的优化重点</b><p>${escape(analysis?.priority||'加载本例的优化记录后可查看。')}</p></div>`;
    const specific=analysis?`<div class="case-optimization" data-analysis-case-id="${current}"><p class="eyebrow">CASE ${number(current)} / 独立分析与验收</p><h4>这一个项目，改了什么。</h4><dl><div><dt>本次具体改动</dt><dd>${list(analysis.changes)}</dd></div><div><dt>本例验收结果</dt><dd>${list(analysis.verify)}</dd></div><div><dt>本例仍有的差距</dt><dd>${list(analysis.remaining)}</dd></div></dl></div>`:'';
    $('#demo-reference').innerHTML=`${specific}<details class="case-technical"><summary>本例的技术依据与产品方向</summary><dl><div><dt>原作依据</dt><dd>${escape(ref.evidence)} <a href="${escape(source.url)}" target="_blank" rel="noreferrer">查看原帖 ↗</a></dd></div><div><dt>原作披露的技术</dt><dd>${escape(ref.sourceTech)}</dd></div><div><dt>我们的实现</dt><dd>${escape(ref.tech)}</dd></div><div><dt>可复用的实现思路</dt><dd>${escape(ref.kernel)} <a href="labs/${escape(item.module)}.js" target="_blank" rel="noreferrer">查看演示代码 ↗</a>${current===6?' · <a href="labs/pipeline/music_blender.py" target="_blank" rel="noreferrer">Python / Blender 配方 ↗</a>':''}</dd></div><div><dt>对应产品</dt><dd>${escape(item.product)}。${escape(ref.value)}</dd></div><div><dt>技术范围</dt><dd>${escape(ref.boundary)}</dd></div></dl></details>`;
    observer?.disconnect();$('#lab-frame').style.height='1100px';$('#lab-frame').title=item.title+' · 对应产品演示';$('#lab-frame').src=`labs/?id=${current}&embedded=1&v=16`;
    const sourcePanel=$('.demo-source');sourcePanel.open=true;window.EffectGallery?.renderInto($('#demo-original-effect'),[current]);
  }
  $('#lab-frame').addEventListener('load',()=>{const frame=$('#lab-frame');visibility();let previous=0;const resize=()=>{const height=Math.ceil(frame.contentDocument?.body.scrollHeight||1100);if(height>0&&Math.abs(height-previous)>1){previous=height;frame.style.height=height+'px';}};resize();if(frame.contentDocument?.body){observer?.disconnect();observer=new ResizeObserver(resize);observer.observe(frame.contentDocument.body);}});
  window.DemoGallery=Object.freeze({select,setActive(value){active=value;visibility();},getCurrentId:()=>current});
  select(Number(location.hash.match(/^#demo-(\d+)$/)?.[1])||1);
})();
