"""Verify the real 019 client at its own subpath, with exact model permissions.

The client must already be built. Sentinels represent private files; no scene
fixtures or replacement assets are generated by these checks.
"""
import hashlib
import json
import shutil
import struct
import sys
import tempfile
import unittest
from html.parser import HTMLParser
from pathlib import Path
from urllib.parse import unquote, urlsplit

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "scripts"))
from build_site import build


class ClientLinks(HTMLParser):
    def __init__(self):
        super().__init__()
        self.links = []

    def handle_starttag(self, tag, attrs):
        attrs = dict(attrs)
        if tag == "script" and attrs.get("src"):
            self.links.append(attrs["src"])
        if tag == "link" and attrs.get("rel") in {"stylesheet", "modulepreload"}:
            self.links.append(attrs["href"])


class RidgeExplorerPackagingTests(unittest.TestCase):
    PUBLIC_ASSETS = (
        "assets/horse.glb", "assets/HORSE-LICENSE.txt",
        "assets/THREE-LICENSE.txt", "assets/SOURCE-NOTICE.txt",
        "assets/POLYHAVEN-LICENSE.txt", "assets/foliage-clump.png",
        "assets/pbr/ground-diff.jpg", "assets/pbr/ground-nor_gl.jpg",
        "assets/pbr/ground-rough.jpg",
        "assets/exploration/tent_detailedOpen.glb",
        "assets/exploration/campfire_stones.glb", "assets/exploration/log.glb",
        "assets/exploration/License.txt", "assets/exploration/NOTICE.txt",
    )
    PRIVATE_ASSETS = (
        "assets/private-horse.glb", "assets/internal-notes.txt",
        "other/horse.glb", "other/HORSE-LICENSE.txt",
        "assets/baseline.zip", "releases/20261003-polished-baseline.zip",
        "assets/exploration/private-tent.glb", "other/tent_detailedOpen.glb",
        "other/License.txt", "assets/exploration/internal-notes.txt",
        ".private/render.png", "node_modules/private.js",
    )

    @classmethod
    def setUpClass(cls):
        records = json.loads((ROOT / "projects.json").read_text(encoding="utf-8"))
        record = next(item for item in records if item["slug"] == "ridge-explorer")
        cls.relative = Path(f"projects/{record['id']:03d}-{record['slug']}")
        cls.real_project = ROOT / cls.relative
        cls.real_web = cls.real_project / "web"
        missing = [name for name in ("index.html", *cls.PUBLIC_ASSETS)
                   if not (cls.real_web / name).is_file()]
        if missing:
            raise AssertionError("Build the 019 client before packaging checks; missing: " + ", ".join(missing))

        cls.temp = tempfile.TemporaryDirectory()
        cls.addClassCleanup(cls.temp.cleanup)
        cls.root = Path(cls.temp.name)
        copied = cls.root / cls.relative
        shutil.copytree(cls.real_web, copied / "web")
        shutil.copy2(cls.real_project / "README.md", copied / "README.md")
        if record["cover"]:
            cover = copied / record["cover"]
            cover.parent.mkdir(parents=True, exist_ok=True)
            shutil.copy2(cls.real_project / record["cover"], cover)
        for name in cls.PRIVATE_ASSETS:
            sentinel = copied / "web" / name
            sentinel.parent.mkdir(parents=True, exist_ok=True)
            sentinel.write_bytes(b"must not ship")

        unrelated = dict(record, id=record["id"] + 1, slug="unrelated-explorer-check", cover="")
        unrelated_path = cls.root / f"projects/{unrelated['id']:03d}-{unrelated['slug']}"
        shutil.copytree(cls.real_web, unrelated_path / "web")
        shutil.copy2(cls.real_project / "README.md", unrelated_path / "README.md")
        cls.unrelated_public = cls.root / "_site" / unrelated_path.relative_to(cls.root)
        (cls.root / "projects.json").write_text(json.dumps([record, unrelated], ensure_ascii=False), encoding="utf-8")
        build(cls.root)
        cls.public = cls.root / "_site" / cls.relative

    def test_real_model_textures_and_notices_survive_byte_for_byte(self):
        for name in self.PUBLIC_ASSETS:
            with self.subTest(asset=name):
                self.assertEqual(hashlib.sha256((self.public / name).read_bytes()).digest(),
                                 hashlib.sha256((self.real_web / name).read_bytes()).digest())
        model = (self.public / "assets/horse.glb").read_bytes()
        self.assertEqual(struct.unpack("<4sII", model[:12]), (b"glTF", 2, len(model)))
        self.assertGreater(len(model), 100_000)
        notice = (self.public / "assets/HORSE-LICENSE.txt").read_text(encoding="utf-8")
        self.assertIn("Mirada", notice)
        self.assertIn("Attribution-NonCommercial-ShareAlike 3.0", notice)
        nature_license = (self.public / "assets/exploration/License.txt").read_text(encoding="utf-8")
        self.assertIn("Creative Commons Zero", nature_license)
        for name in self.PUBLIC_ASSETS:
            if name.startswith("assets/exploration/") and name.endswith(".glb"):
                with self.subTest(model=name):
                    model = (self.public / name).read_bytes()
                    self.assertEqual(struct.unpack("<4sII", model[:12]), (b"glTF", 2, len(model)))

    def test_real_client_assets_resolve_under_019_subpath(self):
        parser = ClientLinks()
        parser.feed((self.public / "index.html").read_text(encoding="utf-8"))
        self.assertTrue(parser.links)
        for link in parser.links:
            with self.subTest(link=link):
                parts = urlsplit(link)
                self.assertFalse(parts.scheme or parts.netloc)
                self.assertFalse(parts.path.startswith("/"))
                path = (self.public / unquote(parts.path)).resolve()
                self.assertTrue(path.is_relative_to(self.public.resolve()))
                self.assertTrue(path.is_file())
                self.assertEqual(hashlib.sha256(path.read_bytes()).digest(),
                                 hashlib.sha256((self.real_web / unquote(parts.path)).read_bytes()).digest())
        javascript = "\n".join(path.read_text(encoding="utf-8") for path in self.public.rglob("*.js"))
        self.assertIn("assets/horse.glb", javascript)
        self.assertIn("assets/exploration/", javascript)
        self.assertIn("tent_detailedOpen", javascript)
        self.assertIn("campfire_stones", javascript)

    def test_model_allowlist_does_not_publish_private_files_or_other_projects(self):
        for name in self.PRIVATE_ASSETS:
            with self.subTest(private=name):
                self.assertFalse((self.public / name).exists())
        for name in self.PUBLIC_ASSETS:
            if name.endswith(".glb") or (name.endswith(".txt") and Path(name).name != "THREE-LICENSE.txt"):
                with self.subTest(unrelated=name):
                    self.assertFalse((self.unrelated_public / name).exists())


if __name__ == "__main__":
    unittest.main()
