const {Stage,Sprite,useTime,useSprite,interpolate,Easing}=window.Animations;
const green='#163c34', lime='#c3ee87';
function Reveal({children,delay=0}){const {elapsed}=useSprite();const p=interpolate(elapsed,[delay,delay+.65],[0,1],Easing.expoOut);return <div style={{opacity:p,transform:`translateY(${(1-p)*32}px)`}}>{children}</div>}
function SceneIntro(){const {elapsed}=useSprite();return <div className="scene opening"><div className="overline">RESEARCH DESK / 研选</div><h1>这个开源项目，<br/>值得继续研究吗？</h1><Reveal delay={.6}><p>把资料、证据与采用判断，放进同一个工作台。</p></Reveal><div className="intro-line" style={{width:interpolate(elapsed,[.5,2],[0,550],Easing.expoOut)}}/><small>工作流概念演示 · 样本为真实仓库</small></div>}
function SceneLibrary(){const {elapsed}=useSprite();return <div className="scene light"><div className="scene-label">01 / 项目筛选</div><Reveal><h2>先找到适合当前任务的工具。</h2></Reveal><div className="shot" style={{transform:`translateY(${interpolate(elapsed,[0,.7],[80,0],Easing.expoOut)}px) scale(${interpolate(elapsed,[.7,4.7],[.91,.96])})`}}><img src="assets/prototype-library.png"/><div className="cursor" style={{left:interpolate(elapsed,[1.2,2.5],[850,700]),top:interpolate(elapsed,[1.2,2.5],[500,367])}}>↖<span style={{opacity:elapsed>2.6?1:0}}>打开研究</span></div></div><p className="caption">按用途搜索，查看项目摘要。</p></div>}
function SceneEvidence(){const {elapsed}=useSprite();return <div className="scene light"><div className="scene-label">02 / 证据与边界</div><Reveal><h2>看清能力，也看清还缺什么。</h2></Reveal><div className="shot" style={{transform:`translateX(${interpolate(elapsed,[0,.75],[140,0],Easing.expoOut)}px) scale(.96)`}}><img src="assets/prototype-detail.png"/></div><p className="caption">每个来源都指向固定版本，避免把愿景当作已实现功能。</p></div>}
function SceneDecision(){const {elapsed}=useSprite();return <div className="scene closing"><div className="scene-label">03 / 采用判断</div><div className="closing-copy"><Reveal><h2>让下一步，<br/>有据可查。</h2></Reveal><Reveal delay={.7}><p>记录采用理由<br/>写下真实验证任务<br/>把结论下载留档</p></Reveal><Reveal delay={1.5}><div className="end-label">研选 / 开源项目研究工作台</div></Reveal></div><img className="decision-shot" src="assets/prototype-decision.png" style={{transform:`translateX(${interpolate(elapsed,[.2,1],[150,0],Easing.expoOut)}px)`}}/><small>原型交互在浏览器体验 · 本视频为预设流程，无配音</small></div>}
function ClockEvidence(){const t=useTime();return <div className="time-evidence" data-time={t.toFixed(3)} style={{width:(t/20*1280)+'px'}}/>}
ReactDOM.createRoot(document.getElementById('root')).render(<Stage duration={20} width={1280} height={720} loop={false} bgColor={green}><Sprite start={0} end={4}><SceneIntro/></Sprite><Sprite start={4} end={9}><SceneLibrary/></Sprite><Sprite start={9} end={14}><SceneEvidence/></Sprite><Sprite start={14} end={20}><SceneDecision/></Sprite><ClockEvidence/></Stage>);
