'use strict';
const records=[{id:'detail',name:'Huashu Design',icon:'H',category:'design',desc:'把真实材料做成原型、幻灯片与视觉交付物',tags:'视觉设计 / HTML / Agent',version:'0830494'}, {id:'witr',name:'witr',icon:'w',category:'ops',desc:'从端口和进程出发，追溯运行来源',tags:'本地排障 / CLI / Go',version:'dc4fa1d'}];
const storage={read(k,fallback){try{return JSON.parse(localStorage.getItem('research-desk:'+k))??fallback}catch{return fallback}},write(k,v){try{localStorage.setItem('research-desk:'+k,JSON.stringify(v));return true}catch{return false}}};
const names={library:'项目库',detail:'Huashu Design',compare:'用途对照',decision:'我的决策',witr:'witr'};
const $=s=>document.querySelector(s);
function route(){const id=names[location.hash.slice(1)]?location.hash.slice(1):'library';document.querySelectorAll('.screen').forEach(s=>s.hidden=s.id!==id);document.querySelectorAll('nav a').forEach(a=>{a.classList.toggle('active',a.hash==='#'+id);a.setAttribute('aria-current',a.hash==='#'+id?'page':'false')});$('#breadcrumb').textContent=names[id];if(id==='witr')$('#decision-project').value='witr';if(id==='detail')$('#decision-project').value='Huashu Design';window.scrollTo(0,0)}
function list(){const q=$('#query').value.trim().toLowerCase(),cat=$('#category').value;const found=records.filter(r=>(cat==='all'||cat===r.category)&&(r.name+' '+r.desc+' '+r.tags).toLowerCase().includes(q));$('#project-list').innerHTML=found.length?found.map(r=>`<a class="project" href="#${r.id}"><span class="project-icon">${r.icon}</span><div><h2>${r.name}</h2><p>${r.desc}</p><span class="tag">${r.tags} · ${r.version}</span></div><span class="open-project">打开研究 ↗</span></a>`).join(''):'<div class="empty">没有匹配的项目。试试“设计”或清空筛选。</div>'}
const upstream='https://github.com/alchaincyf/huashu-design/blob/0830494ecb1c117e25b313a8114fe55a6bf2b125/';
const tabs={overview:`<div class="summary-grid"><article><h2>适合把研究成果<br>做成可以展示的内容。</h2><p>它提供设计规范、参考资料、页面组件和导出工具。Agent 根据需求编写 HTML，再由浏览器呈现效果。</p><p>对当前研究集，直接的试用任务是：做一个可点击工作台，并把研究结论变成汇报和短视频。</p></article><dl class="facts"><dt>主要输入</dt><dd>任务说明、真实资料、视觉方向</dd><dt>常见产物</dt><dd>交互 HTML、PDF、PPTX、MP4</dd><dt>源码许可</dt><dd>MIT</dd><dt>本次研究版本</dt><dd>0830494 · 2026-09-22</dd></dl></div>`,evidence:[['assets/ios_frame.jsx','移动设备展示容器','设备边框用于呈现移动端原型，业务界面仍需编写。'],['assets/deck_stage.js','浏览器幻灯片外壳','支持键盘翻页、缩放、页码和备注。'],['scripts/html2pptx.js','可编辑 PPT 对象转换','读取 DOM 布局，把文本等元素转成 PowerPoint 对象。'],['assets/animations.jsx','时间轴组件','Stage / Sprite 根据统一时间更新画面。']].map(([p,t,d])=>`<article class="evidence-row"><a href="${upstream+p}" target="_blank" rel="noopener">${t} ↗</a><p>${d}</p><small>${p}</small></article>`).join(''),limits:`<article class="note"><h2>视觉交付之外，还需要工程建设。</h2><p>原型中的搜索、收藏与记录只在浏览器运行。真实产品需要持久化服务、用户权限、同步策略和部署维护。</p><p>PPT 导出要求受约束的 HTML；复杂网页视觉可能转成图片。视频导出要求动画受统一时间控制。</p><p>这套演示测试指定组件与导出路线，没有测试所有云服务、配音和模板继承功能。</p></article>`};
function tab(id){$('#detail-content').innerHTML=tabs[id];document.querySelectorAll('[data-tab]').forEach(b=>b.setAttribute('aria-selected',String(b.dataset.tab===id)))}
let saved=storage.read('saved',false);function bookmark(){$('#save-project').textContent=saved?'★ 已收藏':'☆ 收藏项目';$('#save-project').setAttribute('aria-pressed',String(saved))}
$('#save-project').onclick=()=>{saved=!saved;bookmark();if(!storage.write('saved',saved))message('浏览器未允许保存，本次状态仍可体验。')};
function message(s){$('#toast').textContent=s;$('#toast').classList.add('show');setTimeout(()=>$('#toast').classList.remove('show'),2500)}
function decision(){return{project:$('#decision-project').value,verdict:$('#verdict').value,reason:$('#reason').value.trim()}}
const note=storage.read('decision',null);if(note){$('#decision-project').value=note.project;$('#verdict').value=note.verdict;$('#reason').value=note.reason}
$('#decision-form').onsubmit=e=>{e.preventDefault();const n=decision();$('#save-status').textContent=storage.write('decision',n)?'已保存到当前浏览器。刷新页面后仍可查看。':'浏览器未允许本地保存，请下载 Markdown。'};
$('#download-note').onclick=()=>{const n=decision();if(!n.reason){$('#reason').focus();$('#save-status').textContent='请先写下采用理由。';return}const text=`# ${n.project} · 采用判断\n\n结论：${n.verdict}\n\n${n.reason}\n\n---\n来源：研选交互原型，本地个人记录。\n`;const u=URL.createObjectURL(new Blob([text],{type:'text/markdown;charset=utf-8'}));const a=document.createElement('a');a.href=u;a.download='research-decision.md';a.click();setTimeout(()=>URL.revokeObjectURL(u),1000)};
document.querySelectorAll('[data-tab]').forEach(b=>b.onclick=()=>tab(b.dataset.tab));$('#query').oninput=list;$('#category').onchange=list;window.addEventListener('hashchange',route);list();tab('overview');bookmark();route();
