import {createRequire} from 'node:module';
import {mkdir,writeFile,readFile} from 'node:fs/promises';
import path from 'node:path';
import {fileURLToPath,pathToFileURL} from 'node:url';
const require=createRequire('C:/Users/yun68/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright/package.json');
const {chromium}=require('playwright');
const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'..');
const out=path.resolve(root,'../../.cache/forma-qa');
await mkdir(out,{recursive:true});await mkdir(path.join(root,'assets/products'),{recursive:true});
const browser=await chromium.launch({headless:true});const context=await browser.newContext({viewport:{width:1440,height:1040},acceptDownloads:true,permissions:['clipboard-read','clipboard-write']});const page=await context.newPage();
const errors=[],checks=[];page.on('pageerror',e=>errors.push(e.message));page.on('response',r=>{if(r.status()>=400&&r.url().includes('127.0.0.1'))errors.push(`${r.status()} ${r.url()}`);});
const url='http://127.0.0.1:8949/projects/009-sprite-destruction-lab/products/';
function check(name,pass,details=''){checks.push({name,passed:Boolean(pass),details});if(!pass)throw Error(`${name}: ${details}`);}
async function shot(name){await page.screenshot({path:path.join(root,'assets/products',`${name}.png`),fullPage:true,style:'.toast{visibility:hidden!important}'});}
async function goto(tool){await page.locator(`[data-tool="${tool}"]`).click();await page.waitForFunction(t=>window.forma.tool===t,tool);}
async function exported(id){const waiting=page.waitForEvent('download',{timeout:25000});await page.locator(`#${id}`).click();const download=await waiting;const dest=path.join(out,download.suggestedFilename());await download.saveAs(dest);return dest;}
try{
  await page.goto(url,{waitUntil:'networkidle'});check('Six product tools and default motion editor',await page.locator('[data-tool]').count()===6&&await page.locator('#motion-source h2').textContent()==='把春天带回家。');
  await shot('motion');
  await page.locator('#motion-title').fill('产品测试\n真实文案');check('Edited text changes the actual rendered source',await page.locator('#motion-source h2').textContent()==='产品测试真实文案');
  const png=await exported('motion-png');check('PNG export has real PNG bytes',(await readFile(png)).subarray(1,4).toString()==='PNG');
  await page.evaluate(()=>{window.originalDecode=HTMLImageElement.prototype.decode;HTMLImageElement.prototype.decode=function(){const img=this;return new Promise(resolve=>setTimeout(resolve,1200)).then(()=>window.originalDecode.call(img));};});
  await page.locator('#motion-play').click();await goto('compare');await page.waitForTimeout(1600);check('Switching tools during image decoding leaves no old engine or page error',await page.evaluate(()=>window.forma.engine===null)&&errors.length===0);
  await goto('motion');await page.locator('#motion-video').click();await page.locator('#cancel-export').click();await page.waitForTimeout(1600);check('Cancelling during image decoding does not recreate a stale engine',await page.evaluate(()=>window.forma.engine===null&&!window.forma.recording)&&await page.locator('#motion-play').isEnabled());
  await page.evaluate(()=>{HTMLImageElement.prototype.decode=window.originalDecode;delete window.originalDecode;});
  const image=await page.evaluate(()=>{const c=document.createElement('canvas');c.width=320;c.height=240;const x=c.getContext('2d');x.fillStyle='#315f49';x.fillRect(0,0,320,240);x.fillStyle='white';x.font='30px sans-serif';x.fillText('USER IMAGE',38,125);return c.toDataURL('image/png').split(',')[1];});
  await page.locator('#motion-image').setInputFiles({name:'user-image.png',mimeType:'image/png',buffer:Buffer.from(image,'base64')});await page.waitForFunction(()=>window.forma.getState().motion.image.startsWith('data:image/png'));check('Uploaded image is used by the motion source',await page.locator('#motion-source img').getAttribute('src')===await page.evaluate(()=>window.forma.getState().motion.image));
  for(const effect of ['glass','paper','pixels','neon','ripple']){
    await page.locator('#motion-effect').selectOption(effect);await page.locator('#motion-play').click();await page.waitForFunction(e=>window.forma.engine?.state==='running'&&window.forma.engine.effect===e,effect,{timeout:12000});await page.waitForTimeout(750);
    check(`${effect} animates actual content`,await page.evaluate(()=>window.forma.engine.getState().hits>0&&window.forma.engine.getState().ratio>0));await page.locator('#motion-reset').click();
  }
  await page.locator('#motion-duration').fill('3');await page.locator('#motion-effect').selectOption('paper');
  const video=await exported('motion-video');check('WebM export has substantial video bytes',(await readFile(video)).length>15000);
  const probe=await context.newPage();await writeFile(path.join(out,'probe.html'),`<video id="v" src="${pathToFileURL(video).href}" controls></video>`);await probe.goto(pathToFileURL(path.join(out,'probe.html')).href);await probe.waitForFunction(()=>Number.isFinite(document.querySelector('video').duration));const metadata=await probe.evaluate(()=>({duration:v.duration,width:v.videoWidth,height:v.videoHeight}));check('Exported WebM has playable duration and dimensions',metadata.duration>2.5&&metadata.duration<4&&metadata.width>100&&metadata.height>100,JSON.stringify(metadata));await probe.close();
  await page.locator('#motion-video').click();await page.waitForFunction(()=>window.forma.recording);await page.locator('#cancel-export').click();await page.waitForFunction(()=>!window.forma.recording);check('Cancelling video resets the editor without blocked controls',await page.locator('#motion-play').isEnabled()&&await page.locator('#export-dialog').isHidden());
  await page.locator('#motion-video').click();await page.waitForFunction(()=>window.forma.recording);await page.evaluate(()=>{Object.defineProperty(document,'hidden',{configurable:true,value:true});document.dispatchEvent(new Event('visibilitychange'));delete document.hidden;});await page.waitForFunction(()=>!window.forma.recording);check('Backgrounding the page cancels recording instead of waiting forever',await page.locator('#motion-status').textContent().then(t=>t.includes('转入后台'))&&await page.locator('#export-dialog').isHidden());
  await goto('compare');await shot('compare');await page.locator('#compare-slider').fill('22');check('Slider changes actual image mask',await page.locator('#compare-after-mask').evaluate(e=>e.style.clipPath.includes('22%')));
  const box=await page.locator('.compare-stage').boundingBox();await page.mouse.move(box.x+box.width*.22,box.y+box.height/2);await page.mouse.down();await page.mouse.move(box.x+box.width*.7,box.y+box.height/2);await page.mouse.up();check('Dragging the picture moves the real boundary',await page.evaluate(()=>Math.abs(window.forma.getState().compare.split-70)<1));
  await page.locator('[data-style="garden"]').click();await page.locator('#compare-note').fill('采用植绿方案，保留阅读角。');await page.locator('#compare-select').click();check('Selected proposal and reason are recorded',await page.locator('#compare-choice').textContent()==='已采用：植绿 · 自然休息角 · 采用植绿方案，保留阅读角。');
  await page.locator('#compare-upload-after').setInputFiles({name:'new-plan.png',mimeType:'image/png',buffer:Buffer.from(image,'base64')});await page.waitForFunction(()=>window.forma.getState().compare.after.startsWith('data:image/png'));await page.locator('#compare-select').click();const compare=await exported('compare-export');const compareText=await readFile(compare,'utf8');check('Comparison report embeds uploaded image and actual choice',compareText.includes('data:image/png;base64')&&compareText.includes('选择：上传方案')&&compareText.includes('采用植绿方案'));
  await goto('manual');await shot('manual');await page.locator('[data-part="2"]').click();check('Hotspot exposes the matching component description',await page.locator('#part-title').textContent()==='可拆水箱');await page.locator('#manual-explode').click();check('Parts have a real exploded state',await page.locator('#manual-stage').evaluate(e=>e.classList.contains('exploded')));for(let i=0;i<3;i++)await page.locator(`[data-step="${i}"]`).check();check('Maintenance checklist completes the workflow',await page.locator('#manual-progress').textContent()==='已完成 3 / 3 步');const record=await exported('manual-export');check('Maintenance export contains the checked steps',((await readFile(record,'utf8')).match(/\[x\]/g)||[]).length===3);
  await goto('data');await page.locator('[data-story="2"]').click();await page.waitForTimeout(900);await shot('data');
  const fixture='category,value\nA,40\nA,30\nB,20\n"邮件,订阅",10\n';await page.locator('#data-upload').setInputFiles({name:'actual.csv',mimeType:'text/csv',buffer:Buffer.from(fixture)});await page.waitForFunction(()=>window.forma.getState().data.rows[0].category==='A');
  check('CSV duplicates aggregate and quoted categories remain intact',await page.evaluate(()=>{const r=window.forma.getState().data.rows;return r.length===3&&r[0].value===70&&r[2].category==='邮件,订阅';}));check('Summary recalculates from imported values',await page.locator('#data-insight').textContent()==='A贡献最多：70，占 70.0%。');
  await page.locator('#data-upload').setInputFiles({name:'bad.csv',mimeType:'text/csv',buffer:Buffer.from('category,value\nA,-50\n')});await page.waitForTimeout(100);check('Invalid CSV is rejected and current data survives',await page.evaluate(()=>window.forma.getState().data.rows[0].value===70)&&await page.locator('#toast').isVisible());
  await page.locator('#data-play').click();await page.waitForTimeout(2700);check('Story playback actually advances the visualization',await page.evaluate(()=>window.forma.getState().data.stage===1));await page.locator('#data-play').click();
  const summary=await exported('data-report');check('Analysis summary exports exact imported data',(await readFile(summary,'utf8')).includes('最大类别：A（70，70.0%）'));const chart=await exported('data-png');check('Data chart is a real PNG',(await readFile(chart)).subarray(1,4).toString()==='PNG');
  await goto('brand');await page.locator('#brand-open').click();await page.waitForTimeout(1450);await shot('brand');check('Brand cover reveals content',await page.locator('#brand-gate').evaluate(e=>e.classList.contains('open')));await page.locator('[data-chapter="1"]').click();await page.locator('#brand-edit-title').fill('新的品牌故事');check('Chapter edit appears in the live exhibition',await page.locator('#brand-title').textContent()==='新的品牌故事');await page.locator('#brand-collect').click();check('Brand collection is a stored project state',await page.evaluate(()=>window.forma.getState().brand.collected));const lookbook=await exported('brand-export');check('Brand lookbook contains edited three-chapter content',(await readFile(lookbook,'utf8')).includes('新的品牌故事')&&((await readFile(lookbook,'utf8')).match(/<section>/g)||[]).length===3);
  await goto('embed');await shot('embed');for(const effect of ['ripple','paper','neon']){await page.locator('#embed-effect').selectOption(effect);await page.locator('forma-reveal .cover').click();check(`${effect} component emits a real reveal event`,await page.locator('#embed-events').textContent().then(v=>v.includes(`"effect":"${effect}"`)));await page.locator('forma-reveal .reset').click();}
  await page.locator('#embed-copy').click();check('Copied snippet contains the real module and event API',(await page.evaluate(()=>navigator.clipboard.readText())).includes("addEventListener('forma:reveal'"));
  const offline=await exported('embed-html'),offlinePage=await context.newPage();const offlineErrors=[];offlinePage.on('pageerror',e=>offlineErrors.push(e.message));await offlinePage.goto(pathToFileURL(offline).href);await offlinePage.locator('forma-reveal .cover').click();check('Offline HTML works without local server',await offlinePage.locator('#event').textContent()==='已揭晓 1 次 · neon'&&offlineErrors.length===0);await offlinePage.close();
  await page.locator('#save-project').click();await page.reload({waitUntil:'networkidle'});check('Local project restores uploads and completion after reload',await page.evaluate(()=>{const s=window.forma.getState();return s.motion.image.startsWith('data:image/png')&&s.manual.done.length===3&&s.brand.titles[1]==='新的品牌故事'&&s.data.rows[0].value===70;}));
  const project=await exported('export-project');check('Exported project is valid versioned JSON',JSON.parse(await readFile(project,'utf8')).format==='forma-project');await page.locator('#import-project').setInputFiles({name:'broken.json',mimeType:'application/json',buffer:Buffer.from('{"version":1}')});check('Invalid project does not erase current state',await page.evaluate(()=>window.forma.getState().manual.done.length===3));
  await goto('manual');await page.locator('#manual-clear').click();await page.locator('#import-project').setInputFiles(project);await page.waitForFunction(()=>window.forma.getState().manual.done.length===3);check('Importing the exported project restores all tool settings',await page.locator('#manual-progress').textContent()==='已完成 3 / 3 步');
  await goto('data');await page.locator('#data-upload').setInputFiles({name:'tiny.csv',mimeType:'text/csv',buffer:Buffer.from('category,value\n极小值,0.0000001\n其他,1\n')});await page.waitForFunction(()=>window.forma.getState().data.rows[0].value===1e-7);await page.locator('#save-project').click();await page.reload({waitUntil:'networkidle'});check('Small decimal CSV values survive local project restore and display',await page.evaluate(()=>window.forma.getState().data.rows[0].value===1e-7)&&await page.locator('.data-table tbody tr:first-child td:nth-child(2)').textContent()==='1e-7');
  await page.setViewportSize({width:390,height:844});for(const tool of ['motion','compare','manual','data','brand','embed']){await goto(tool);check(`${tool} has no mobile horizontal overflow`,await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),await page.evaluate(()=>({scrollWidth:document.documentElement.scrollWidth,innerWidth})));}await shot('mobile');
  check('No uncaught errors or missing local assets',errors.length===0,JSON.stringify(errors));
}catch(error){checks.push({name:'Products browser run',passed:false,details:error.message});console.error(error);await shot('failure');process.exitCode=1;}
finally{await writeFile(path.join(root,'notes/products-checks.json'),JSON.stringify({checkedAt:new Date().toISOString(),url,browser:browser.version(),checks,errors},null,2)+'\n');console.log(JSON.stringify({checks:checks.length,passed:checks.filter(c=>c.passed).length,failed:checks.filter(c=>!c.passed),errors},null,2));await browser.close();}
