import {createRequire} from 'node:module';
import {mkdir,writeFile,readFile} from 'node:fs/promises';
import path from 'node:path';
import {fileURLToPath} from 'node:url';
const require=createRequire('C:/Users/yun68/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright/package.json');
const {chromium}=require('playwright'),root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'..'),out=path.resolve(root,'../../.cache/toolbox-qa');
await mkdir(out,{recursive:true});await mkdir(path.join(root,'assets/toolbox'),{recursive:true});
const browser=await chromium.launch({headless:true}),context=await browser.newContext({viewport:{width:1440,height:1040},acceptDownloads:true,permissions:['clipboard-read','clipboard-write']}),page=await context.newPage();
const checks=[],errors=[],network=[];page.on('pageerror',e=>errors.push(e.message));
page.on('response',r=>{if(r.url().startsWith('https://api.mymemory.translated.net/get'))network.push({status:r.status(),url:r.url()});});
const live=process.argv.includes('--live');
const url='http://127.0.0.1:8949/projects/009-sprite-destruction-lab/toolbox/';
const panel=id=>page.locator(`#forma-toolbox-host #${id}`);
function check(name,pass,details=''){checks.push({name,passed:Boolean(pass),details});if(!pass)throw Error(`${name}: ${details}`);}
async function shot(name){await page.screenshot({path:path.join(root,'assets/toolbox',`${name}.png`),fullPage:false,style:'#forma-toolbox-host .toast{visibility:hidden!important}'});}
async function exported(id){const waiting=page.waitForEvent('download');await panel(id).click();const d=await waiting,dest=path.join(out,d.suggestedFilename());await d.saveAs(dest);return dest;}
try{
  await page.goto(url,{waitUntil:'networkidle'});await page.waitForFunction(()=>window.FormaToolbox?.isMounted());check('Toolbox mounts without modifying page text',await page.locator('#first-paragraph').textContent().then(v=>v.startsWith('You can translate selected text')));await shot('overview');
  await page.locator('#try-translation').click();const original=await page.locator('#first-paragraph').textContent();check('Real document selection populates translation input',await panel('translation-source').inputValue()===original&&await page.evaluate(()=>getSelection().toString())===original);
  let translation=null,service={attempted:live};
  if(live){await panel('translate').click();await page.waitForFunction(()=>!window.FormaToolbox.getState().translating,undefined,{timeout:60000});translation=await page.evaluate(()=>window.FormaToolbox.getState().translation);service.status=await panel('translation-status').textContent();service.available=Boolean(translation);if(translation){check('Online service returns actual Chinese translation',/[\u4e00-\u9fff]/.test(translation.text)&&translation.text!==original&&network.some(r=>r.status===200));await panel('translation-inline').click();check('Live bilingual text is inserted under the actual selected paragraph',await page.locator('#first-paragraph + .forma-inline-translation').textContent().then(v=>v.includes(translation.text)));await shot('translation');}else{check('An unavailable live service shows its actual error without a fabricated translation',await panel('translation-result').isHidden()&&/429|服务|网络|额度|超时/.test(service.status),service.status);await shot('translation-service-limit');}}
  if(translation)await panel('translation-save').click();else{await page.locator('#forma-toolbox-host [data-tab="notes"]').click();await panel('note-save').click();}await page.waitForFunction(()=>window.FormaToolbox.getState().notes.length===1);check('Excerpt includes actual selected text and correct page source',await page.evaluate(u=>{const n=window.FormaToolbox.getState().notes[0];return n.quote===document.getElementById('first-paragraph').textContent&&n.sourceUrl===u&&n.origin==='selection'&&n.createdAt;},url));
  const notes=await exported('notes-json'),payload=JSON.parse(await readFile(notes,'utf8'));check('Excerpt JSON contains actual source and selected content',payload.format==='forma-excerpts'&&payload.notes[0].quote===original&&payload.notes[0].translation===(translation?.text||''));await shot('notes');
  await page.reload({waitUntil:'networkidle'});await page.waitForFunction(()=>window.FormaToolbox.getState().notes?.length===1);check('Saved excerpt survives reload',await page.evaluate(()=>window.FormaToolbox.getState().notes[0].quote)===original);
  await page.locator('#try-table').click();const matrix=await page.evaluate(()=>window.FormaToolbox.getState().matrix);check('Real catalog cells become the extracted matrix',matrix.length===await page.locator('#catalog-table tr').count()&&matrix[0][0]==='编号'&&matrix[1][1]===await page.locator('#catalog-table tbody tr:first-child td:nth-child(2)').textContent());
  const csv=await exported('table-csv');check('CSV contains real project records',(await readFile(csv,'utf8')).includes('witr · 运行来源诊断')&&(await readFile(csv,'utf8')).includes('projects/001-witr/'));const table=await exported('table-json');check('Table JSON keeps provenance and exact rows',JSON.parse(await readFile(table,'utf8')).sourceUrl===url&&JSON.stringify(JSON.parse(await readFile(table,'utf8')).rows)===JSON.stringify(matrix));await shot('tables');
  await page.evaluate(()=>{const table=document.createElement('table');table.id='qa-spans';table.innerHTML='<tbody><tr><th rowspan="2">Group</th><th colspan="2">Values</th></tr><tr><td>A<br>B<table><tr><td>DO NOT READ</td></tr></table></td><td>=1+1</td></tr></tbody>';document.getElementById('reading-source').append(table);window.FormaToolbox.selectTable(table);});
  check('Merged cells expand and nested table text stays out',await page.evaluate(()=>JSON.stringify(window.FormaToolbox.getState().matrix)===JSON.stringify([['Group','Values','Values'],['Group','A\nB','=1+1']])));const safeCSV=await exported('table-csv');check('CSV export prevents formula interpretation',(await readFile(safeCSV,'utf8')).includes("'=1+1"));await page.evaluate(()=>document.getElementById('qa-spans').remove());
  await page.locator('#forma-toolbox-host [data-tab="tools"]').click();await panel('tool-input').fill('apple\napple\n梨');await page.locator('#forma-toolbox-host [data-transform="dedupe"]').click();check('Text tool actually deduplicates lines',await panel('tool-output').inputValue()==='apple\n梨');check('Text statistics reflect user input',await panel('stat-lines').textContent()==='3'&&await panel('stat-chars').textContent()==='13');
  await panel('tool-input').fill('{"name":"Forma","count":3}');await page.locator('#forma-toolbox-host [data-transform="json"]').click();const formatted=await panel('tool-output').inputValue();check('JSON tool returns parsed formatting',JSON.parse(formatted).count===3&&formatted.includes('\n'));await panel('tool-input').fill('{broken');await page.locator('#forma-toolbox-host [data-transform="json"]').click();check('Invalid JSON clears prior output',await panel('tool-output').inputValue()==='');
  await panel('unit-convert').click();check('Unit conversion calculates inches to centimeters',await panel('unit-result').textContent()==='12 in = 30.48 cm');await panel('unit-from').selectOption('C');await panel('unit-to').selectOption('F');await panel('unit-value').fill('100');await panel('unit-convert').click();check('Temperature conversion works',await panel('unit-result').textContent()==='100 C = 212 F');await shot('tools');
  await panel('close').click();check('Closing removes UI and inserted translations',await page.locator('#forma-toolbox-host').count()===0&&await page.locator('.forma-inline-translation').count()===0&&await page.locator('#forma-toolbox-page-style').count()===0);await page.locator('#open-toolbox').click();await page.waitForFunction(()=>window.FormaToolbox.getState().notes.length===1);check('Reopening retains local notes without duplicate hosts',await page.locator('#forma-toolbox-host').count()===1);
  await page.locator('#try-table').click();await panel('table-pick').click();await page.locator('#forma-toolbox-host [data-tab="notes"]').click();check('Leaving the tables tab exits page picking',!await page.evaluate(()=>window.FormaToolbox.getState().picking)&&await page.locator('[data-forma-pick]').count()===0);
  const other=await context.newPage();await other.goto(url,{waitUntil:'networkidle'});await other.waitForFunction(()=>window.FormaToolbox.getState().notes.length===1);
  await page.locator('#forma-toolbox-host [data-tab="translate"]').click();await panel('translation-source').fill('My own research observation');await page.locator('#forma-toolbox-host [data-tab="notes"]').click();await panel('note-save').click();await page.waitForFunction(()=>JSON.parse(localStorage.getItem('forma-toolbox-notes-v1')).length===2);
  check('Manual input is explicitly labelled rather than quoted as page text',await panel('notes-list').textContent().then(v=>v.includes('用户输入'))&&await page.evaluate(()=>window.FormaToolbox.getState().notes.at(-1).origin==='manual'));
  await other.evaluate(()=>{const r=document.createRange();r.selectNodeContents(document.getElementById('second-paragraph'));getSelection().removeAllRanges();getSelection().addRange(r);FormaToolbox.captureSelection();FormaToolbox.showTab('notes');});await other.locator('#forma-toolbox-host #note-save').click();await other.waitForFunction(()=>JSON.parse(localStorage.getItem('forma-toolbox-notes-v1')).length===3);
  check('Two tabs preserve each other’s newly saved excerpts',await page.evaluate(()=>JSON.parse(localStorage.getItem('forma-toolbox-notes-v1')).some(n=>n.quote==='My own research observation'))&&await other.evaluate(()=>JSON.parse(localStorage.getItem('forma-toolbox-notes-v1')).some(n=>n.quote===document.getElementById('second-paragraph').textContent)));
  const manualId=await page.evaluate(()=>window.FormaToolbox.getState().notes.find(n=>n.origin==='manual').id);await page.locator(`#forma-toolbox-host [data-note-delete="${manualId}"]`).click();await page.waitForFunction(()=>JSON.parse(localStorage.getItem('forma-toolbox-notes-v1')).length===2);
  await other.evaluate(()=>{const r=document.createRange();r.selectNodeContents(document.getElementById('quote-paragraph'));getSelection().removeAllRanges();getSelection().addRange(r);FormaToolbox.captureSelection();});await other.locator('#forma-toolbox-host #note-save').click();await other.waitForFunction(()=>JSON.parse(localStorage.getItem('forma-toolbox-notes-v1')).length===3);
  check('A stale tab does not resurrect another tab’s deleted excerpt',await page.evaluate(()=>!JSON.parse(localStorage.getItem('forma-toolbox-notes-v1')).some(n=>n.quote==='My own research observation')));await other.close();
  // A delayed test transport checks cancellation only; it never supplies the live demo translation.
  await page.evaluate(()=>FormaTranslate.configureTranslationTransport(()=>new Promise(resolve=>{window.__finishTestRequest=()=>resolve({responseStatus:200,responseData:{translatedText:'测试竞态结果'}});})));await page.locator('#forma-toolbox-host [data-tab="translate"]').click();await panel('translation-source').fill('Pending uncached test sentence');await panel('translate').click();await page.waitForFunction(()=>Boolean(window.__finishTestRequest));await page.locator('#try-translation').click();await page.evaluate(()=>{window.__finishTestRequest();FormaTranslate.configureTranslationTransport(null);delete window.__finishTestRequest;});await page.waitForFunction(()=>!window.FormaToolbox.getState().translating);check('Selecting a new paragraph cancels the prior translation',await panel('translation-result').isHidden()&&await panel('translation-source').inputValue()===original);
  await page.evaluate(()=>FormaTranslate.configureTranslationTransport(async()=>({responseStatus:200,responseData:{translatedText:'QA fixture: DOM insertion check'}})));await panel('translate').click();await page.waitForFunction(()=>!window.FormaToolbox.getState().translating);await panel('translation-inline').click();check('Element-container selection inserts below its own paragraph (isolated UI fixture)',await page.locator('#first-paragraph + .forma-inline-translation').textContent().then(v=>v.includes('QA fixture: DOM insertion check'))&&await page.locator('#first-paragraph').textContent()===original);await page.evaluate(()=>{FormaTranslate.configureTranslationTransport(null);FormaTranslate.clearTranslationCache();});
  await page.locator('#try-translation').click();await panel('provider').selectOption('local');await panel('translate').click();await page.waitForFunction(()=>!window.FormaToolbox.getState().translating,undefined,{timeout:15000});const local=await panel('translation-status').textContent();check('Local mode reports actual browser model availability',await panel('translation-result').isVisible()||/不可用|不支持|无法|超时|模型/.test(local),local);
  await panel('provider').selectOption('online');await panel('translation-source').fill('Change this text while a request is running.');await page.evaluate(()=>FormaTranslate.configureTranslationTransport(()=>new Promise(()=>{})));await panel('translate').click();await panel('translation-source').fill('New text');await page.evaluate(()=>FormaTranslate.configureTranslationTransport(null));await page.waitForFunction(()=>!window.FormaToolbox.getState().translating);check('Changing input cancels old translation output',await panel('translation-result').isHidden()&&await panel('translation-source').inputValue()==='New text');
  const zipWait=page.waitForEvent('download');await page.locator('.download').click();const zip=await zipWait;await zip.saveAs(path.join(out,zip.suggestedFilename()));check('Real extension ZIP is downloadable',(await readFile(path.join(out,zip.suggestedFilename()))).subarray(0,2).toString()==='PK');
  await page.setViewportSize({width:390,height:844});await page.locator('#try-table').click();await shot('mobile');check('Mobile page and panel have no horizontal overflow',await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)&&await panel('panel').evaluate(e=>e.getBoundingClientRect().right<=innerWidth));await panel('minimize').click();check('Mobile panel can be minimized',await panel('panel').evaluate(e=>e.getBoundingClientRect().height<80));
  check('No uncaught errors across actual tool operations',errors.length===0,JSON.stringify(errors));
}catch(error){checks.push({name:'Toolbox browser run',passed:false,details:error.message});console.error(error);await shot('failure');process.exitCode=1;}
finally{await writeFile(path.join(root,'notes/toolbox-checks.json'),JSON.stringify({checkedAt:new Date().toISOString(),url,browser:browser.version(),checks,network,errors,liveTranslationRequested:live},null,2)+'\n');console.log(JSON.stringify({checks:checks.length,passed:checks.filter(c=>c.passed).length,failed:checks.filter(c=>!c.passed),network,errors},null,2));await browser.close();}
