import {STYLES,EXTRA_STYLES} from './styles.js';
import {render2D} from './render2d.js';
import {World3D} from './render3d.js';
const $=s=>document.querySelector(s),canvas=$('#canvas2d'),ctx=canvas.getContext('2d'),mount=$('#webgl-mount');
const state={t:0,style:'pixel',opened:false,collected:0,care:0,popAge:2,squash:0,squashV:0,held:false,night:false,particles:[],bunColor:'#e9b1ca',plantStage:0,ingredients:0,fishAge:3,furniture:false,painted:false,avatar:{x:372,y:315,tx:372,ty:315},paused:false};
state.detail=.65;
let activeFilter='all';
let world3D=null,webglError=null,audio=null,sound=false,soundTimer=null;
const reduced=matchMedia('(prefers-reduced-motion: reduce)').matches;
function say(text){$('#stage-message').textContent=text;$('#lab-result').textContent=text}
function chime(kind='open'){if(!sound)return;try{audio??=new (window.AudioContext||window.webkitAudioContext)();audio.resume();const now=audio.currentTime;for(let i=0;i<(kind==='open'?4:1);i++){const o=audio.createOscillator(),g=audio.createGain();o.type='sine';o.frequency.setValueAtTime((kind==='squish'?240:523.25)*[1,1.25,1.5,2][i],now+i*.085);if(kind==='squish')o.frequency.exponentialRampToValueAtTime(110,now+.18);g.gain.setValueAtTime(.0001,now+i*.085);g.gain.exponentialRampToValueAtTime(.12,now+i*.085+.015);g.gain.exponentialRampToValueAtTime(.0001,now+i*.085+.38);o.connect(g);g.connect(audio.destination);o.start(now+i*.085);o.stop(now+i*.085+.4)}}catch{sound=false;$('#toggle-sound').textContent='声音不可用'}}
function particles(heart=false){for(let i=0;i<(heart?7:32);i++)state.particles.push({x:503+(Math.random()-.5)*55,y:280,vx:(Math.random()-.5)*180,vy:-70-Math.random()*130,age:0,life:1.1+Math.random(),r:2+Math.random()*3,col:['#ed9cbf','#ffd38d','#8fc9ac','#c5a5dc'][i%4],heart})}
function updateCounts(){$('#collect-count').textContent=state.collected;$('#care-count').textContent=state.care}
function openBun(){state.opened=true;state.collected++;state.popAge=0;state.bunColor=['#e9b1ca','#eac899','#b4d0af','#c9b7e1','#abd5dc'][state.collected%5];particles();chime();say(`打开蒸笼，发现第 ${state.collected} 位新伙伴。按住它试试！`);updateCounts();try{localStorage.setItem('dumpling-style-lab-count',String(state.collected))}catch{}}
function hold(on){if(on&&!state.opened)openBun();state.held=on;if(on){particles(true);chime('squish');say('伙伴被轻轻压扁，松开后回弹。')}}
function chooseBase(id){const s=STYLES.find(x=>x.id===id)||STYLES[0];state.style=s.id;state.opened=false;state.popAge=2;state.held=false;state.squash=0;state.squashV=0;state.particles=[];$('#style-stage-title').textContent=s.name+' · 蒸笼世界';$('#style-engine').textContent=s.engine;$('#style-en').textContent=s.en;$('#style-name').textContent=s.name;$('#style-definition').textContent=s.definition;$('#style-features').replaceChildren(...s.features.map(x=>{const li=document.createElement('li');li.textContent=x;return li}));$('#style-interaction').textContent=s.interaction;$('#style-use').textContent=s.use;$('#style-method').textContent=s.method;document.querySelectorAll('.style-tab').forEach(b=>{const on=b.dataset.style===s.id;b.setAttribute('aria-selected',String(on));b.tabIndex=on?0:-1});$('#stage').setAttribute('aria-labelledby','style-tab-'+s.id);$('#mechanism-controls').hidden=s.id!=='pixel';const three=['lowpoly','clay','realistic'].includes(s.id);canvas.style.display=three?'none':'block';mount.style.display=three?'block':'none';$('#stage-hint').textContent=three?'拖动旋转 · 滚轮缩放 · 按钮开盖与挤压':'点击蒸笼开盖 · 按住伙伴挤压';if(three){try{world3D??=new World3D(mount,action=>{if(action==='open')openBun();else{hold(true);setTimeout(()=>hold(false),400)}});world3D.setup(s.id);webglError=null}catch(e){webglError=e.message;say('浏览器未能启用三维渲染，请启用 WebGL 或选择二维风格。')}}if(!webglError||!three)say(`正在体验${s.name}。点击中央蒸笼，或使用「打开蒸笼」。`);const u=new URL(location.href);u.searchParams.set('style',s.id);history.replaceState(null,'',u.pathname+u.search+u.hash);}
function matchesFilter(s,f=activeFilter){return f==='all'||f==='new'&&s.group!=='core'||s.group===f}
function setFilter(filter,select=true){if(!['all','new','core','craft','print','digital'].includes(filter))filter='all';activeFilter=filter;document.querySelectorAll('[data-style-filter]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.styleFilter===filter)));document.querySelectorAll('.style-tab,.gallery-card').forEach(b=>{b.hidden=!matchesFilter(STYLES.find(s=>s.id===b.dataset.style))});$('#style-visible-count').textContent=STYLES.filter(s=>matchesFilter(s)).length+' 种风格';const u=new URL(location.href);if(filter==='all')u.searchParams.delete('group');else u.searchParams.set('group',filter);history.replaceState(null,'',u.pathname+u.search+u.hash);if(select&&!matchesFilter(STYLES.find(s=>s.id===state.style)))choose(STYLES.find(s=>matchesFilter(s)).id)}
function choose(id){const s=STYLES.find(s=>s.id===id)||STYLES[0];if(!matchesFilter(s))setFilter('all',false);chooseBase(s.id);const extra=!!s.effect;$('#style-effect-controls').hidden=!extra;if(extra){$('#effect-label').textContent=s.effect;$('#effect-strength').value=String(Math.round(state.detail*100));$('#effect-value').textContent=Math.round(state.detail*100)+'%'}const tab=$('#style-tab-'+s.id),list=$('#style-list');if(tab){if(matchMedia('(max-width: 720px)').matches)list.scrollLeft=tab.offsetLeft-list.offsetLeft-list.clientWidth/2+tab.clientWidth/2;else list.scrollTop=tab.offsetTop-list.offsetTop-list.clientHeight/2+tab.clientHeight/2}}
document.querySelectorAll('[data-style-filter]').forEach(b=>b.addEventListener('click',()=>setFilter(b.dataset.styleFilter)));
$('#effect-strength').addEventListener('input',e=>{state.detail=Number(e.target.value)/100;$('#effect-value').textContent=e.target.value+'%'});
$('#style-list').replaceChildren(...STYLES.map((s,i)=>{const b=document.createElement('button');b.type='button';b.className='style-tab';b.id='style-tab-'+s.id;b.dataset.style=s.id;b.setAttribute('role','tab');b.setAttribute('aria-controls','stage');b.style.setProperty('--swatch',s.color);const sw=document.createElement('i'),label=document.createElement('span');label.textContent=s.name;const sub=document.createElement('small');sub.textContent=`${String(i+1).padStart(2,'0')} / ${s.effect?'新增':s.engine.startsWith('WEBGL')?'3D':'2D'}`;label.append(sub);b.append(sw,label);b.addEventListener('click',()=>choose(s.id));b.addEventListener('keydown',e=>{if(!['ArrowDown','ArrowUp','ArrowLeft','ArrowRight','Home','End'].includes(e.key))return;e.preventDefault();const visible=STYLES.filter(s=>matchesFilter(s)),current=visible.findIndex(x=>x.id===s.id),next=e.key==='Home'?0:e.key==='End'?visible.length-1:(current+(['ArrowDown','ArrowRight'].includes(e.key)?1:-1)+visible.length)%visible.length;choose(visible[next].id);$('#style-tab-'+visible[next].id).focus()});return b}));
$('#style-gallery').replaceChildren(...STYLES.map(s=>{const b=document.createElement('button');b.className='gallery-card';b.type='button';b.dataset.style=s.id;const img=document.createElement('img');img.src='assets/style-'+s.id+'.webp';img.alt=s.name+'实时场景截图';img.loading='lazy';const label=document.createElement('span');label.textContent=s.name+' ↗';b.append(img,label);b.addEventListener('click',()=>{choose(s.id);$('#lab').scrollIntoView({behavior:reduced?'instant':'smooth'})});return b}));
$('#open-bun').addEventListener('click',openBun);const squish=$('#squish-bun');squish.addEventListener('pointerdown',e=>{e.preventDefault();hold(true);squish.setPointerCapture(e.pointerId)});for(const ev of ['pointerup','pointercancel','lostpointercapture'])squish.addEventListener(ev,()=>hold(false));squish.addEventListener('keydown',e=>{if(e.code==='Space'||e.code==='Enter'){e.preventDefault();hold(true)}});squish.addEventListener('keyup',()=>hold(false));squish.addEventListener('blur',()=>hold(false));
$('#toggle-night').addEventListener('click',()=>{state.night=!state.night;$('#toggle-night').textContent=state.night?'切到白天':'切到夜晚';$('#toggle-night').setAttribute('aria-pressed',String(state.night));say(state.night?'夜色落下，观察光线和背景的变化。':'回到白天，观察轮廓、色块和材质。')});
$('#toggle-sound').addEventListener('click',()=>{sound=!sound;$('#toggle-sound').textContent='声音：'+(sound?'开':'关');$('#toggle-sound').setAttribute('aria-pressed',String(sound));if(sound)chime()});
$('#reset-scene').addEventListener('click',()=>{Object.assign(state,{opened:false,collected:0,care:0,particles:[],plantStage:0,ingredients:0,fishAge:3,furniture:false,painted:false,night:false,held:false,squash:0,squashV:0});try{localStorage.removeItem('dumpling-style-lab-count')}catch{}$('#toggle-night').textContent='切到夜晚';$('#toggle-night').setAttribute('aria-pressed','false');state.detail=.65;$('#effect-strength').value='65';$('#effect-value').textContent='65%';updateCounts();say('场景已重置，可以重新体验。')});
function localAction(action){if(action==='plant'){state.plantStage=state.plantStage%3+1;if(state.plantStage===3)state.ingredients++;say(['','种下种子，嫩芽出现。再浇水看看。','浇水后长出花苞，等待收获。','花朵成熟，已收获 '+state.ingredients+' 份原料。'][state.plantStage]);particles()}if(action==='care'){if(!state.opened)openBun();state.care++;particles(true);say(`喂食完成，好感 ${state.care}。伙伴现在会跟着你。`);updateCounts()}if(action==='furniture'){state.furniture=!state.furniture;say(state.furniture?'小屋里放入了一张新桌子。':'收起桌子，重新布置房间。')}if(action==='paint'){if(!state.opened)openBun();state.painted=!state.painted;say(state.painted?'在伙伴身上画出了新花纹。':'清除花纹，回到原来的颜色。')}if(action==='fish'){state.fishAge=0;openBun();say('从池塘钓到一只新伙伴，收藏数量已增加。')}chime('tap')}
document.querySelectorAll('[data-action]').forEach(b=>b.addEventListener('click',()=>localAction(b.dataset.action)));
canvas.addEventListener('pointerdown',e=>{const r=canvas.getBoundingClientRect(),x=(e.clientX-r.left)/r.width*960,y=(e.clientY-r.top)/r.height*560;if(Math.abs(x-503)<105&&y>210&&y<395){state.opened?hold(true):openBun();canvas.setPointerCapture(e.pointerId)}else if(state.style==='pixel'){state.avatar.tx=x;state.avatar.ty=y;say('点击位置，角色向那里走去。')}});for(const ev of ['pointerup','pointercancel','lostpointercapture'])canvas.addEventListener(ev,()=>hold(false));canvas.addEventListener('keydown',e=>{if(e.code==='Enter')openBun();if(e.code==='Space'){e.preventDefault();hold(true)}const d={ArrowLeft:[-35,0],ArrowRight:[35,0],ArrowUp:[0,-35],ArrowDown:[0,35]}[e.code];if(d){e.preventDefault();state.avatar.tx=Math.max(30,Math.min(920,state.avatar.tx+d[0]));state.avatar.ty=Math.max(60,Math.min(530,state.avatar.ty+d[1]))}});canvas.addEventListener('keyup',()=>hold(false));
$('#reload-original').addEventListener('click',()=>$('#original-frame').src='https://dumpling-dell.pages.dev/');$('#full-original').addEventListener('click',()=>$('#original-frame').requestFullscreen?.().catch(()=>say('请使用原作独立窗口体验。')));
const shotNames={world:'地图探索：原作真实浏览器截图，2026-10-01',reveal:'开盖奖励：Pink Sparkle 与金币反馈，2026-10-01',book:'图鉴收藏：1 / 168 个角色，2026-10-01'};document.querySelectorAll('[data-shot]').forEach(b=>b.addEventListener('click',()=>{const key=b.dataset.shot;$('#shot-image').src='assets/original-'+key+'.png';$('#shot-image').alt=shotNames[key];$('#shot-caption').textContent=shotNames[key];$('#shot-dialog').showModal()}));$('#shot-close').addEventListener('click',()=>$('#shot-dialog').close());$('#shot-dialog').addEventListener('click',e=>{if(e.target===$('#shot-dialog'))$('#shot-dialog').close()});
try{state.collected=Number(localStorage.getItem('dumpling-style-lab-count'))||0}catch{}updateCounts();choose(new URLSearchParams(location.search).get('style')||'pixel');setFilter(new URLSearchParams(location.search).get('group')||'all');
let last=performance.now();function loop(now){const dt=Math.min(2,(now-last)/1000);last=now;if(!document.hidden&&!state.paused&&document.querySelector('#visual-archive')?.open){state.t+=dt;state.popAge+=dt;state.fishAge+=dt;const springSteps=Math.max(1,Math.ceil(dt*120)),springDt=dt/springSteps;for(let i=0;i<springSteps;i++){state.squashV+=((state.held?.85:0)-state.squash)*180*springDt-state.squashV*10*springDt;state.squash+=state.squashV*springDt;}for(const p of state.particles){p.age+=dt;p.x+=p.vx*dt;p.y+=p.vy*dt;p.vy+=120*dt}state.particles=state.particles.filter(p=>p.age<p.life);const dx=state.avatar.tx-state.avatar.x,dy=state.avatar.ty-state.avatar.y;state.avatar.x+=dx*Math.min(1,dt*3);state.avatar.y+=dy*Math.min(1,dt*3);if(['lowpoly','clay','realistic'].includes(state.style)){if(!webglError)world3D?.render(state)}else render2D(ctx,canvas,state.style,state)}requestAnimationFrame(loop)}requestAnimationFrame(loop);
window.styleLab={styles:STYLES.map(s=>s.id),select:choose,open:openBun,hold,state,get rendererType(){return ['lowpoly','clay','realistic'].includes(state.style)?(webglError?'failed':'WebGL'):'Canvas2D'},get rotation(){return world3D?.azimuth||0},get webglError(){return webglError},extraStyles:EXTRA_STYLES.map(s=>s.id),filter:setFilter};



