import { COLS, ROWS, HEART, ROOMS, createDungeon, advance, dig, buildRoom, recruit, setJob, possess, leavePossession, startAssault, encode, restore, status } from './direction-dungeon-engine.js';
import { VIEW, cellFromPoint, drawDungeon, prepareMaterials } from './direction-dungeon-render.js';
const $ = id => document.getElementById(id), canvas = $('dungeon-canvas'), ctx = canvas.getContext('2d'), STORAGE = 'world-play-direction-dungeon-v1';
const tools = [...document.querySelectorAll('[data-dungeon-tool]')], touchButtons = [...document.querySelectorAll('[data-dungeon-input]')], assets = {}, keys = new Set(), touches = new Map(), guardViews = new Map(), reducedMotion = matchMedia('(prefers-reduced-motion: reduce)').matches;
const toolOrder = ['dig', 'workshop', 'training', 'sanctuary', 'treasury', 'trap'], jobs = { guard: '巡守', train: '训练', rest: '休养' };
let w = createDungeon('demo'), ready = false, tool = 'dig', selectedGuard = w.guards[0]?.id || null, previous = false, grid = false, speed = 1, hover = null, pointerId = null, lastTile = null, lastPointerX = null, dragTurn = 0, lastTime = 0, hudTime = 0, saveTime = 0, hintUntil = 0, manualHint = '', rosterOrder = '';
try { const saved = JSON.parse(localStorage.getItem(STORAGE) || 'null'), recovered = saved?.version === 1 && restore(saved.world); if (recovered) { w = recovered; selectedGuard = w.guards.some(g => g.id === saved.selectedGuard) ? saved.selectedGuard : w.guards[0]?.id || null; tool = toolOrder.includes(saved.tool) ? saved.tool : 'dig'; grid = saved.grid === true; previous = true; $('d-resume').hidden = false; } } catch { /* Invalid or unavailable storage leaves a fresh paused keep. */ }
function text(id, value) { if ($(id).textContent !== String(value)) $(id).textContent = value; }
function say(value, duration = 5000) { if (!value) return; manualHint = value; hintUntil = Date.now() + duration; text('d-hint', value); }
function save() { if (!ready) return; try { localStorage.setItem(STORAGE, JSON.stringify({ version: 1, world: encode(w), selectedGuard, tool, grid })); text('d-save-status', '地下城与岗位已独立保存'); } catch { text('d-save-status', '浏览器未开放保存，可继续这一局'); } }
function clearMapPointer() { if (pointerId !== null && canvas.hasPointerCapture(pointerId)) canvas.releasePointerCapture(pointerId); pointerId = null; lastTile = null; lastPointerX = null; dragTurn = 0; }
function clearInput() { keys.clear(); clearMapPointer(); for (const [id, value] of touches) { value.button.setAttribute('aria-pressed', 'false'); if (value.button.hasPointerCapture(id)) value.button.releasePointerCapture(id); } touches.clear(); }
function changed(result, quiet = false) { if (result?.ok) { previous = false; $('d-resume').hidden = true; if (!quiet) say(result.reason, 3200); updateHud(); save(); return true; } if (!quiet) say(result?.reason || '目前无法进行这项操作。'); return false; }
function selectTool(value) { clearMapPointer(); tool = value; tools.forEach(b => b.setAttribute('aria-pressed', String(b.dataset.dungeonTool === value))); updateHud(); }
function reset(layout) { if (!ready) return; clearInput(); w = createDungeon(layout); w.paused = layout !== 'demo'; selectedGuard = w.guards[0]?.id || null; previous = false; $('d-resume').hidden = true; grid = layout !== 'demo'; $('d-grid').setAttribute('aria-pressed', String(grid)); hover = layout === 'guided' ? [9, 5] : null; lastTime = 0; selectTool('dig'); say(layout === 'blank' ? '堡垒已暂停，留时间规划。标记岩层，开始运转后矿工会开凿；建造房间、安排守卫，准备好后迎接入侵。' : layout === 'guided' ? '接通训练场：标记高亮的 9,5，由矿工实际挖通房间入口。守卫就能前往训练；主防御通道已连通，准备好后可迎接入侵。' : '守卫按岗位工作，矿工开凿岩层，工坊生产储备。18 秒后第一批入侵者到来；你可以暂停布局，或选择守卫亲自迎战。', 9500); updateHud(); save(); }
function mapPointer(e) { const r = canvas.getBoundingClientRect(); return cellFromPoint((e.clientX - r.left) / r.width * VIEW.width, (e.clientY - r.top) / r.height * VIEW.height); }
function act(x, y, quiet = false) { if (!ready || w.view === 'possession' || w.phase !== 'playing' || x < 0 || y < 0 || x >= COLS || y >= ROWS) return; changed(tool === 'dig' ? dig(w, x, y) : buildRoom(w, tool, x, y), quiet); }
function selectMapGuard(x, y) { const guard = w.guards.find(g => g.hp > 0 && Math.hypot(g.x - x, g.y - y) < .8); if (!guard) return false; selectedGuard = guard.id; updateHud(); save(); say(`已选守卫 ${guard.id}。调整岗位，或进入他的视角。`, 2400); return true; }
canvas.addEventListener('pointerdown', e => { if (!ready || e.button !== 0) return; e.preventDefault(); canvas.focus({ preventScroll: true }); if (w.view === 'possession') { clearMapPointer(); pointerId = e.pointerId; lastPointerX = e.clientX; canvas.setPointerCapture(pointerId); return; } hover = mapPointer(e); if (selectMapGuard(...hover)) return; act(...hover); if (tool === 'dig') { pointerId = e.pointerId; lastTile = hover; canvas.setPointerCapture(pointerId); } });
canvas.addEventListener('pointermove', e => { if (w.view === 'possession') { if (pointerId === e.pointerId && lastPointerX !== null) { dragTurn += Math.max(-1, Math.min(1, (e.clientX - lastPointerX) / 60)); lastPointerX = e.clientX; } return; } hover = mapPointer(e); if (pointerId !== e.pointerId || !lastTile || tool !== 'dig') return; const tx = Math.max(0, Math.min(COLS - 1, hover[0])), ty = Math.max(0, Math.min(ROWS - 1, hover[1])); let [x, y] = lastTile; if (x >= 0 && x < COLS && y >= 0 && y < ROWS) { while (x !== tx) { x += Math.sign(tx - x); act(x, y, true); } while (y !== ty) { y += Math.sign(ty - y); act(x, y, true); } } lastTile = [tx, ty]; });
canvas.addEventListener('pointerup', clearMapPointer); canvas.addEventListener('pointercancel', clearMapPointer); canvas.addEventListener('lostpointercapture', () => { pointerId = null; lastTile = null; lastPointerX = null; dragTurn = 0; }); canvas.addEventListener('pointerleave', () => { if (pointerId === null) hover = null; });
tools.forEach(b => b.addEventListener('click', () => { if (!ready || w.view === 'possession') return; selectTool(b.dataset.dungeonTool); }));
function input() { const down = action => [...touches.values()].some(v => v.action === action), pressed = code => keys.has(code); return { forward: Number(pressed('KeyW') || pressed('ArrowUp') || down('forward')) - Number(pressed('KeyS') || pressed('ArrowDown') || down('back')), strafe: Number(pressed('KeyD') || down('right')) - Number(pressed('KeyA') || down('left')), turn: Math.max(-1, Math.min(1, Number(pressed('KeyE') || pressed('ArrowRight') || down('turnRight')) - Number(pressed('KeyQ') || pressed('ArrowLeft') || down('turnLeft')) + dragTurn)), attack: pressed('Space') || down('attack') }; }
touchButtons.forEach(button => { const action = button.dataset.dungeonInput; button.setAttribute('aria-pressed', 'false'); button.addEventListener('pointerdown', e => { if (!ready || w.view !== 'possession' || w.paused || w.phase !== 'playing') return; e.preventDefault(); touches.set(e.pointerId, { action, button }); button.setPointerCapture(e.pointerId); button.setAttribute('aria-pressed', 'true'); }); const release = e => { if (!touches.has(e.pointerId)) return; touches.delete(e.pointerId); if (button.hasPointerCapture(e.pointerId)) button.releasePointerCapture(e.pointerId); button.setAttribute('aria-pressed', String([...touches.values()].some(t => t.button === button))); }; button.addEventListener('pointerup', release); button.addEventListener('pointercancel', release); button.addEventListener('lostpointercapture', release); });
function togglePossession() { if (!ready || w.phase !== 'playing') return; clearInput(); const result = w.view === 'possession' ? leavePossession(w) : possess(w, selectedGuard); if (changed(result)) { if (w.view === 'possession') { w.paused = false; speed = 1; text('d-speed', '速度 ×1'); say('已进入守卫视角。WASD 移动，QE 或左右键转向，空格攻击。P 返回；触屏按钮可同时按住。', 9000); if (!document.fullscreenElement) $('d-stage').scrollIntoView?.({ block: 'center', behavior: reducedMotion ? 'auto' : 'instant' }); } else say('已返回经营视角，守卫继续执行他的岗位。'); canvas.focus({ preventScroll: true }); updateHud(); save(); } }
window.addEventListener('keydown', e => { if (!ready || /^(INPUT|TEXTAREA|SELECT|BUTTON)$/.test(e.target?.tagName || '')) return; if (e.code === 'KeyP') { e.preventDefault(); if (!e.repeat) togglePossession(); return; } if (w.view === 'possession' && ['KeyW', 'KeyA', 'KeyS', 'KeyD', 'KeyQ', 'KeyE', 'ArrowLeft', 'ArrowRight', 'ArrowUp', 'ArrowDown', 'Space'].includes(e.code)) { e.preventDefault(); keys.add(e.code); return; } if (document.activeElement !== canvas && e.target !== canvas) return; if (/^Digit[1-6]$/.test(e.code)) { e.preventDefault(); if (!e.repeat) selectTool(toolOrder[Number(e.code.slice(-1)) - 1]); } else if (e.code === 'Space') { e.preventDefault(); if (!e.repeat) $('d-pause').click(); } else if (['ArrowLeft', 'ArrowRight', 'ArrowUp', 'ArrowDown'].includes(e.code)) { e.preventDefault(); hover ||= [HEART[0], HEART[1]]; const d = { ArrowLeft: [-1, 0], ArrowRight: [1, 0], ArrowUp: [0, -1], ArrowDown: [0, 1] }[e.code]; hover = [Math.max(0, Math.min(COLS - 1, hover[0] + d[0])), Math.max(0, Math.min(ROWS - 1, hover[1] + d[1]))]; } else if (e.code === 'Enter') { e.preventDefault(); if (!e.repeat) { hover ||= [HEART[0], HEART[1]]; if (!selectMapGuard(...hover)) act(...hover); } } });
window.addEventListener('keyup', e => { keys.delete(e.code); });
$('d-demo').addEventListener('click', () => reset('demo')); $('d-guided').addEventListener('click', () => reset('guided')); $('d-blank').addEventListener('click', () => reset('blank')); $('d-retry').addEventListener('click', () => reset(w.layout)); $('d-rewatch').addEventListener('click', () => reset('demo'));
$('d-pause').addEventListener('click', () => { if (!ready || w.phase !== 'playing') return; clearInput(); previous = false; $('d-resume').hidden = true; w.paused = !w.paused; updateHud(); save(); });
$('d-assault').addEventListener('click', () => { if (!ready) return; changed(startAssault(w)); });
$('d-recruit').addEventListener('click', () => { if (!ready) return; const result = recruit(w); if (result.ok) selectedGuard = result.id ?? w.guards.at(-1)?.id; changed(result); });
$('d-job').addEventListener('change', () => { if (!ready) return; changed(setJob(w, selectedGuard, $('d-job').value)); const actual = w.guards.find(g => g.id === selectedGuard); if (actual) $('d-job').value = actual.job; updateHud(); });
$('d-possess').addEventListener('click', togglePossession); $('d-leave').addEventListener('click', togglePossession);
$('d-speed').addEventListener('click', () => { if (w.view === 'possession') { say('守卫视角保持正常速度，方便移动与战斗。'); return; } speed = speed === 1 ? 2 : 1; text('d-speed', `速度 ×${speed}`); });
$('d-grid').addEventListener('click', () => { grid = !grid; $('d-grid').setAttribute('aria-pressed', String(grid)); save(); });
async function fullscreen(exitOnly = false) { try { if (document.fullscreenElement) await document.exitFullscreen(); else if (!exitOnly) await $('d-stage').requestFullscreen(); } catch { say('当前浏览器未开放全屏，可以继续在这里操作。'); } }
$('d-fullscreen').addEventListener('click', () => fullscreen()); $('d-stage-exit').addEventListener('click', () => fullscreen(true));
$('d-stage-pause').addEventListener('click', () => $('d-pause').click()); $('d-stage-possess').addEventListener('click', () => $('d-possess').click());
$('d-resume').addEventListener('click', () => { if (!ready || !previous) return; clearInput(); previous = false; $('d-resume').hidden = true; if (w.phase === 'playing') w.paused = false; updateHud(); save(); say('已继续上次的堡垒布局、岗位与进度。'); });
function backgroundPause() { clearInput(); if (ready && w.phase === 'playing') { w.paused = true; say('页面暂离，堡垒已暂停。点击“继续运转”恢复。'); updateHud(); save(); } }
window.addEventListener('blur', backgroundPause); document.addEventListener('visibilitychange', () => { if (document.hidden) backgroundPause(); }); window.addEventListener('pagehide', () => { clearInput(); save(); });
function updateHud() {
  text('d-gold', Math.floor(w.gold)); text('d-heart', `${Math.ceil(w.heart)} / 180`); text('d-guards', `${w.guards.filter(g => g.hp > 0).length} 人 / ${w.miners.length} 矿工`); text('d-charges', w.charges); text('d-wave', w.assault ? `第 ${w.wave} 批` : '准备中'); text('d-pause', w.paused ? w.time ? '继续运转' : '开始运转' : '暂停'); $('d-pause').disabled = !ready || w.phase !== 'playing'; $('d-assault').disabled = !ready || w.phase !== 'playing' || w.assault; text('d-assault', w.assault ? '入侵进行中' : '迎接入侵'); text('d-hint', Date.now() < hintUntil ? manualHint : previous ? '上次的堡垒已经恢复并暂停。继续上次，或重新选择一种开局。' : status(w));
  const firstPerson = w.view === 'possession', controlled = firstPerson && w.guards.find(g => g.id === w.controlled); $('d-leave').hidden = !firstPerson; $('d-touch').hidden = !firstPerson || w.phase !== 'playing'; $('d-possession-tip').hidden = true; text('d-view-name', firstPerson ? `守卫 ${w.controlled} · 生命 ${Math.ceil(controlled?.hp || 0)}/${controlled?.maxHp || 110}` : '堡垒经营视角'); text('d-map-info', firstPerson ? '按住控制按钮移动与迎战 · P 返回经营' : '点击守卫选择 · 岩层开凿后才可建设房间'); tools.forEach(b => { b.disabled = !ready || firstPerson || w.phase !== 'playing'; });
  const guards = w.guards.filter(g => g.hp > 0); if (!guards.some(g => g.id === selectedGuard)) selectedGuard = guards[0]?.id || null;
  const buttons = guards.map(g => { let view = guardViews.get(g.id); if (!view) { const button = document.createElement('button'), number = document.createElement('span'), copy = document.createElement('span'), title = document.createElement('b'), info = document.createElement('small'); button.className = 'guard-card'; number.className = 'guard-number'; number.textContent = String(g.id).padStart(2, '0'); copy.append(title, info); button.append(number, copy); button.addEventListener('click', () => { selectedGuard = g.id; updateHud(); save(); }); view = { button, title, info }; guardViews.set(g.id, view); } view.button.setAttribute('aria-pressed', String(selectedGuard === g.id)); view.title.textContent = `守卫 ${g.id} · 等级 ${g.level}`; view.info.textContent = `${Math.ceil(g.hp)} / ${g.maxHp} 体力 · ${w.controlled === g.id ? '亲自控制' : jobs[g.job] || g.job}`; return view.button; }); const nextOrder = guards.map(g => g.id).join(','); if (rosterOrder !== nextOrder) { $('d-roster').replaceChildren(...buttons); rosterOrder = nextOrder; }
  const guard = guards.find(g => g.id === selectedGuard); text('d-guard-name', guard ? `守卫 ${guard.id} · 等级 ${guard.level}` : '暂无可选守卫'); text('d-guard-info', guard ? `${Math.ceil(guard.hp)} / ${guard.maxHp} 体力 · ${w.controlled === guard.id ? '亲自控制' : jobs[guard.job] || guard.job}` : '可通过招募增加守卫'); $('d-guard-health').style.width = `${guard ? Math.max(0, Math.min(100, guard.hp / guard.maxHp * 100)) : 0}%`; $('d-job').disabled = !ready || !guard || w.phase !== 'playing' || firstPerson; if (guard && document.activeElement !== $('d-job')) $('d-job').value = guard.job; $('d-possess').disabled = !ready || !guard || w.phase !== 'playing'; text('d-possess', firstPerson ? '返回经营视角 · P' : '进入守卫视角'); text('d-guard-detail', guard ? w.controlled === guard.id ? '你正在直接控制这名守卫。其他矿工、守卫和房间仍按真实时间运转。' : `岗位：${jobs[guard.job] || guard.job}。${guard.job === 'train' ? '训练需要能够抵达训练室。' : guard.job === 'rest' ? '休养需要能够抵达圣所。' : '守卫会主动迎战进入堡垒的入侵者。'}进入视角后可以亲自接管移动与攻击。` : '没有可选的守卫，先查看预算与招募条件。');
  $('d-recruit').disabled = !ready || w.phase !== 'playing' || guards.length >= 5; const def = ROOMS[tool]; text('d-tool-name', tool === 'dig' ? '开凿岩层' : def?.name || '走廊陷阱'); text('d-tool-detail', tool === 'dig' ? '点击岩层标记工作，矿工沿通路前往并实际开凿。金矿开凿后会带来建设资金。拖动可连续标记。' : `${def?.description || '在已开凿的走廊布置机关，入侵者经过时实际触发。'}${def?.cost !== undefined ? ` 建设费用 ${def.cost}。` : ''}`); text('d-room-count', `已建 ${w.rooms.length} 座房间 · ${w.traps.length} 处陷阱 · ${w.queue.length} 处开凿任务`);
  $('d-stage-actions').dataset.view = firstPerson ? 'possession' : 'management'; text('d-stage-pause', $('d-pause').textContent); $('d-stage-pause').disabled = $('d-pause').disabled; text('d-stage-possess', firstPerson ? '返回经营' : guard ? `进入守卫 ${guard.id}` : '暂无可选守卫'); $('d-stage-possess').disabled = $('d-possess').disabled; text('d-stage-tool', `当前：${tool === 'dig' ? '开凿岩层' : def?.name || '走廊陷阱'} · 1–6 切换工具 · 方向键＋Enter 操作`);
  text('d-log', w.log.slice(-5).map(e => `${Math.floor(e.time)}s · ${e.message}`).join('\n')); $('d-end-card').hidden = w.phase === 'playing'; if (w.phase !== 'playing') { clearInput(); text('d-end-title', w.phase === 'won' ? '堡垒守住了。' : '堡垒之心熄灭了。'); text('d-end-detail', `用时 ${Math.round(w.time)} 秒，击退 ${w.stats.kills} 名入侵者，开凿 ${w.stats.dug} 处岩层，其中 ${w.stats.mined} 处金矿；工坊生产 ${w.stats.trapChargesProduced} 份机关储备，累计布置 ${w.stats.trapChargesUsed} 处陷阱。你亲自命中 ${w.stats.manualHits} 次。${w.phase === 'won' ? '可以换一种布局，或尝试更多亲自迎战。' : '检查通路、守卫岗位和休养安排，再重新布防。'}`); }
}
function frame(timestamp) { const dt = lastTime ? Math.min(.1, Math.max(0, (timestamp - lastTime) / 1000)) : 0; lastTime = timestamp; if (ready) { advance(w, dt * (w.view === 'possession' ? 1 : speed), w.view === 'possession' ? input() : {}); dragTurn = 0; drawDungeon(ctx, w, assets, { hover, tool, grid, selectedGuard, reducedMotion, embedded: true }); if (timestamp - hudTime > 200) { updateHud(); hudTime = timestamp; } if (timestamp - saveTime > 2200) { save(); saveTime = timestamp; } } requestAnimationFrame(frame); }
const load = file => new Promise((resolve, reject) => { const image = new Image(); image.onload = () => resolve(image); image.onerror = () => reject(new Error('地下城美术加载失败')); image.src = 'assets/directions/dungeon/' + file; });
try { [assets.stone, assets.props, assets.overhead, assets.front] = await Promise.all(['stone-atlas.png', 'chambers-atlas.png', 'overhead-actors.png', 'front-actors.png'].map(load)); prepareMaterials(assets, (width, height) => { const surface = document.createElement('canvas'); surface.width = width; surface.height = height; return surface; }); ready = true; $('d-load-status').hidden = true; tools.forEach(b => b.setAttribute('aria-pressed', String(b.dataset.dungeonTool === tool))); $('d-grid').setAttribute('aria-pressed', String(grid)); if (!previous && new URLSearchParams(location.search).get('demo') === '1') reset('demo'); updateHud(); save(); requestAnimationFrame(frame); }
catch { text('d-load-status', '地下城美术未能装载，请刷新重试。下方仍可查看方向说明与参考。'); ['d-demo', 'd-guided', 'd-blank', 'd-pause', 'd-assault', 'd-recruit', 'd-possess'].forEach(id => $(id).disabled = true); }

