import { STATIONS, CARGO, COLS, ROWS, createFreight, advance, build, createLine, addTruck, toggleLine, connected, truckStatus, status, encode, restore } from './direction-freight-engine.js';
import { drawFreight, VIEW, point, cellFromPoint, pickStation } from './direction-freight-render.js';
const $ = id => document.getElementById(id), canvas = $('freight-canvas'), ctx = canvas.getContext('2d'), STORAGE = 'world-play-direction-freight-v1', toolButtons = [...document.querySelectorAll('[data-freight-tool]')];
let w = createFreight(), previous = null, tool = 'road', selectedLine = 1, inspected = null, hover = null, ready = false, assets = {}, grid = false, paths = true, speed = 1, dragging = false, pointerId = null, lastTile = '';
let lastTime = 0, hudTime = 0, saveTime = 0, hintUntil = 0, manualHint = '', lineOrder = ''; const lineViews = new Map(), reducedMotion = matchMedia('(prefers-reduced-motion: reduce)').matches;
try { const saved = JSON.parse(localStorage.getItem(STORAGE)); const world = saved && restore(saved.world); if (world) { w = world; selectedLine = w.lines.some(l => l.id === saved.selectedLine) ? saved.selectedLine : w.lines[0]?.id || null; previous = { world, selectedLine }; $('f-resume').hidden = false; } } catch { /* Fresh paused network if storage is absent or invalid. */ }
$('f-from').value = 'forest'; $('f-to').value = 'mill'; $('f-cargo').value = 'logs';
function say(value, duration = 4500) { manualHint = value; hintUntil = Date.now() + duration; $('f-hint').textContent = value; }
function save() { if (!ready) return; try { localStorage.setItem(STORAGE, JSON.stringify({ world: encode(w), selectedLine })); $('f-save-status').textContent = '运输网络已独立保存'; } catch { $('f-save-status').textContent = '浏览器未开放保存，可继续本轮运输'; } }
function release() { dragging = false; lastTile = ''; if (pointerId !== null && canvas.hasPointerCapture(pointerId)) canvas.releasePointerCapture(pointerId); pointerId = null; }
function selectTool(value) { tool = value; toolButtons.forEach(b => b.setAttribute('aria-pressed', String(b.dataset.freightTool === tool))); }
function reset(layout) { if (!ready) return; release(); w = createFreight(layout); w.paused = layout !== 'demo'; previous = null; selectedLine = w.lines[0]?.id || null; inspected = null; hover = layout === 'guided' ? [6, 4] : null; lastTime = 0; grid = layout !== 'demo'; $('f-grid').setAttribute('aria-pressed', String(grid)); $('f-resume').hidden = true; selectTool('road'); say(layout === 'blank' ? '运输先暂停，留时间设计。连接建筑南侧前场，选择货物与起止站建立线路，准备好后点击“开始运输”。' : layout === 'guided' ? '补上高亮的北路地块，或在南路桥址建设桥梁。现有线路与车队已准备好。' : '六辆车正在实际装货、运送、卸货与返回。选择一条线路观察；也可直接修改网络。', 7000); updateHud(); save(); }
function act(x, y, quiet = false) { if (!ready) return; if (tool === 'inspect') { inspected = pickStation(x, y)?.id || null; updateHud(); return; } const result = build(w, tool, x, y); if (result.ok) { previous = null; $('f-resume').hidden = true; say(result.reason, 2200); updateHud(); save(); } else if (!quiet) say(result.reason, 3000); }
function pointer(e) { const r = canvas.getBoundingClientRect(); return cellFromPoint((e.clientX - r.left) / r.width * VIEW.width, (e.clientY - r.top) / r.height * VIEW.height); }
canvas.addEventListener('pointerdown', e => { if (!ready || e.button !== 0) return; e.preventDefault(); canvas.focus({ preventScroll: true }); hover = pointer(e); dragging = tool === 'road'; pointerId = e.pointerId; lastTile = hover.join(','); if (dragging) canvas.setPointerCapture(pointerId); act(...hover); });
canvas.addEventListener('pointermove', e => { hover = pointer(e); if (!dragging || pointerId !== e.pointerId || hover.join(',') === lastTile) return; let [x, y] = lastTile.split(',').map(Number); const tx = Math.max(0, Math.min(COLS - 1, hover[0])), ty = Math.max(0, Math.min(ROWS - 1, hover[1])); if (x >= 0 && x < COLS && y >= 0 && y < ROWS) { while (x !== tx) { x += Math.sign(tx - x); act(x, y, true); } while (y !== ty) { y += Math.sign(ty - y); act(x, y, true); } } else act(tx, ty, true); lastTile = [tx, ty].join(','); });
canvas.addEventListener('pointerup', release); canvas.addEventListener('pointercancel', release); canvas.addEventListener('lostpointercapture', () => { dragging = false; pointerId = null; }); canvas.addEventListener('pointerleave', () => { if (!dragging) hover = null; });
canvas.addEventListener('keydown', e => { if (!ready || e.repeat) return; if (/^Digit[1-4]$/.test(e.code)) { e.preventDefault(); selectTool(['road', 'bridge', 'erase', 'inspect'][Number(e.code.slice(-1)) - 1]); } else if (e.code === 'Space') { e.preventDefault(); $('f-pause').click(); } else if (['ArrowLeft', 'ArrowRight', 'ArrowUp', 'ArrowDown'].includes(e.code)) { e.preventDefault(); hover ||= [6, 4]; const d = { ArrowLeft: [-1, 0], ArrowRight: [1, 0], ArrowUp: [0, -1], ArrowDown: [0, 1] }[e.code]; hover = [Math.max(0, Math.min(COLS - 1, hover[0] + d[0])), Math.max(0, Math.min(ROWS - 1, hover[1] + d[1]))]; } else if (e.code === 'Enter') { e.preventDefault(); hover ||= [6, 4]; act(...hover); } });
toolButtons.forEach(b => b.addEventListener('click', () => { release(); selectTool(b.dataset.freightTool); }));
$('f-cargo').addEventListener('change', () => { const c = $('f-cargo').value; $('f-from').value = c === 'logs' ? 'forest' : c === 'boards' ? 'mill' : 'farm'; $('f-to').value = c === 'logs' ? 'mill' : c === 'boards' ? 'town' : 'market'; });
$('f-create-line').addEventListener('click', () => { if (!ready) return; const result = createLine(w, $('f-from').value, $('f-to').value, $('f-cargo').value); if (!result.ok) { say(result.reason); return; } selectedLine = result.id; previous = null; $('f-resume').hidden = true; say(connected(w, w.lines.find(l => l.id === selectedLine)) ? '线路与首辆货车已加入。开始运输后，会从出发站实际装货。' : '线路和货车已加入，当前道路还未接通；车辆会等待通路。'); updateHud(); save(); });
$('f-add-truck').addEventListener('click', () => { if (!ready) return; const result = addTruck(w, selectedLine); if (result.ok) { previous = null; $('f-resume').hidden = true; } say(result.ok ? '已增派一辆货车。货物不足或前车未通过时，它仍会等待。' : result.reason); updateHud(); save(); });
$('f-toggle-line').addEventListener('click', () => { if (ready && toggleLine(w, selectedLine)) { previous = null; $('f-resume').hidden = true; say('已更新发车安排。在途车辆会完成送达与返回。'); updateHud(); save(); } });
$('f-demo').addEventListener('click', () => reset('demo')); $('f-guided').addEventListener('click', () => reset('guided')); $('f-blank').addEventListener('click', () => reset('blank')); $('f-retry').addEventListener('click', () => reset(w.layout)); $('f-rewatch').addEventListener('click', () => reset('demo'));
$('f-pause').addEventListener('click', () => { if (!ready || w.phase !== 'playing') return; release(); previous = null; $('f-resume').hidden = true; w.paused = !w.paused; updateHud(); save(); });
$('f-speed').addEventListener('click', () => { speed = speed === 1 ? 2 : 1; $('f-speed').textContent = `速度 ×${speed}`; });
$('f-grid').addEventListener('click', () => { grid = !grid; $('f-grid').setAttribute('aria-pressed', String(grid)); }); $('f-paths').addEventListener('click', () => { paths = !paths; $('f-paths').setAttribute('aria-pressed', String(paths)); });
$('f-fullscreen').addEventListener('click', async () => { try { if (document.fullscreenElement) await document.exitFullscreen(); else await $('f-stage').requestFullscreen(); } catch { say('浏览器未开放全屏，可以继续在当前地图操作。'); } });
$('f-resume').addEventListener('click', () => { if (!ready || !previous) return; w = restore(encode(previous.world)); selectedLine = previous.selectedLine; previous = null; $('f-resume').hidden = true; if (w.phase === 'playing') w.paused = false; updateHud(); save(); say('已继续上次的运输网络，其他方向的存档保持独立。'); });
function backgroundPause() { release(); if (ready && !w.paused) { w.paused = true; say('页面暂离，车队已暂停。点击“继续运输”恢复。'); updateHud(); save(); } }
window.addEventListener('blur', backgroundPause); document.addEventListener('visibilitychange', () => { if (document.hidden) backgroundPause(); }); window.addEventListener('pagehide', () => { release(); save(); });
function text(id, value) { if ($(id).textContent !== String(value)) $(id).textContent = value; }
function updateHud() {
  text('f-credits', w.credits); text('f-boards', `${w.delivered.boards} / ${w.goal.boards}`); text('f-grain', `${w.delivered.grain} / ${w.goal.grain}`); text('f-fleet', `${w.lines.length} 线 / ${w.trucks.length} 车`); const rem = Math.max(0, Math.ceil(w.limit - w.time)); text('f-clock', `${String(Math.floor(rem / 60)).padStart(2, '0')}:${String(rem % 60).padStart(2, '0')}`);
  text('f-pause', w.paused ? w.time ? '继续运输' : '开始运输' : '暂停'); $('f-pause').disabled = !ready || w.phase !== 'playing'; text('f-hint', Date.now() < hintUntil ? manualHint : previous ? '上次的运输网络已恢复并暂停，可继续上次或重新规划。' : status(w));
  text('f-map-info', tool === 'inspect' ? '点建筑查看库存' : tool === 'bridge' ? '北路与南路的虚线框是桥址' : tool === 'erase' ? '在途车辆所在的路段会保留' : '点击或拖动连接站点前场'); text('f-line-count', `${w.lines.length} 条`);
  const buttons = w.lines.map(l => { let view = lineViews.get(l.id); if (!view) { const button = document.createElement('button'), title = document.createElement('b'), detail = document.createElement('small'); button.className = 'line-card'; button.dataset.freightLine = String(l.id); button.append(title, detail); button.addEventListener('click', () => { selectedLine = l.id; updateHud(); save(); }); view = { button, title, detail }; lineViews.set(l.id, view); } view.button.setAttribute('aria-pressed', String(l.id === selectedLine)); view.title.textContent = `${STATIONS.find(s => s.id === l.from).name} → ${STATIONS.find(s => s.id === l.to).name}`; view.detail.textContent = `${CARGO[l.cargo].name} · ${w.trucks.filter(v => v.lineId === l.id).length} 车 · ${!l.enabled ? '暂停发车' : connected(w, l) ? '已接通' : '通路中断'} · 已送 ${l.delivered}`; return view.button; }); const nextOrder = w.lines.map(l => l.id).join(','); if (nextOrder !== lineOrder) { $('f-lines').replaceChildren(...buttons); lineOrder = nextOrder; }
  const l = w.lines.find(l => l.id === selectedLine), fleet = l ? w.trucks.filter(v => v.lineId === l.id) : []; $('f-add-truck').disabled = !ready || !l || w.phase !== 'playing'; $('f-toggle-line').disabled = !ready || !l || w.phase !== 'playing'; text('f-toggle-line', l?.enabled ? '暂停发车' : '恢复发车'); text('f-line-info', l ? `${fleet.map(v => `车 ${v.id}：${truckStatus(w, v)}${v.cargo ? ` ${v.cargo} 份` : ''}`).join(' · ')}\n本线收入 ${l.revenue} · 完成 ${l.trips} 次运输` : '选择或建立一条线路，再调整车队。');
  const s = STATIONS.find(s => s.id === inspected), node = s && w.stations.find(n => n.id === inspected); text('f-station-name', s ? s.name : '查看站点'); text('f-station-info', s ? `${s.description}\n原木 ${node.stock.logs} · 建材 ${node.stock.boards} · 粮食 ${node.stock.grain}${s.id === 'town' ? `\n已收到 ${w.delivered.boards} 份建材` : s.id === 'market' ? `\n已收到 ${w.delivered.grain} 份粮食` : ''}` : '选择查看工具，点一座建筑，观察库存与作用。');
  text('f-log', w.log.slice(-4).map(e => `${Math.floor(e.time)}s · ${e.message}`).join('\n')); $('f-end-card').hidden = w.phase === 'playing'; if (w.phase !== 'playing') { text('f-end-title', w.phase === 'won' ? '这片地区，连起来了。' : '运输窗口结束了。'); text('f-end-detail', `用时 ${Math.round(w.time)} 秒，送达 ${w.delivered.boards} 份建材与 ${w.delivered.grain} 份粮食；${w.stats.transfers} 份货物经过中央货站接驳。运输收入 ${w.stats.revenue}，建设、购车及出车支出 ${w.stats.expenses}。${w.phase === 'won' ? '可以尝试不同的道路和接驳组织。' : '检查原料、通路与发车安排，再调整网络。'}`); }
}
function frame(timestamp) { const dt = lastTime ? Math.min(.1, Math.max(0, (timestamp - lastTime) / 1000)) : 0; lastTime = timestamp; if (ready) { advance(w, dt * speed); drawFreight(ctx, w, assets, { hover, tool, selectedLine, inspected, grid, paths, reducedMotion }); if (timestamp - hudTime > 250) { updateHud(); hudTime = timestamp; } if (timestamp - saveTime > 2500) { save(); saveTime = timestamp; } } requestAnimationFrame(frame); }
const load = file => new Promise((resolve, reject) => { const image = new Image(); image.onload = () => resolve(image); image.onerror = () => reject(new Error('湾岸素材加载失败')); image.src = 'assets/directions/freight/' + file; });
try { [assets.terrain, assets.stations, assets.vehicles, assets.empty] = await Promise.all(['coastal-valley.png', 'stations-atlas.png', 'loaded-trucks.png', 'empty-fleet.png'].map(load)); ready = true; $('f-load-status').hidden = true; if (!previous && new URLSearchParams(location.search).get('demo') === '1') reset('demo'); updateHud(); requestAnimationFrame(frame); }
catch { $('f-load-status').textContent = '湾岸素材未能装载，请刷新重试。下方仍可查看方向说明与原作参考。'; ['f-demo', 'f-guided', 'f-blank', 'f-pause', 'f-resume', 'f-create-line'].forEach(id => $(id).disabled = true); }
