import { ROLES, EQUIPMENT, createShift, advance, demonstration, order, move, tasksFor, task, target, reason, powered, status, encode, restore } from './direction-shift-engine.js';
import { drawShift, VIEW, point, cellFromPoint } from './direction-shift-render.js';
const $ = id => document.getElementById(id), canvas = $('shift-canvas'), ctx = canvas.getContext('2d'), STORAGE = 'world-play-direction-shift-v1';
const roleButtons = [...document.querySelectorAll('[data-shift-role]')], taskButtons = [...document.querySelectorAll('[data-shift-task]')];
const descriptions = { engineer: '封住泄漏，修好动力与接驳信标；发现短路后可以清理通道。', medic: '先用急救包稳定伤员。恢复供电后，继续为每位乘员完成治疗。', dispatcher: '隔离电路、接通供电与通风，准备好后协调伤员撤离和全员登船。' };
let w = createShift(), active = 'engineer', mode = 'play', previous = null, ready = false, paths = true, hover = null, speed = 1, assets = {};
let lastTime = 0, hudTime = 0, saveTime = 0, hintUntil = 0, manualHint = '';
const reducedMotion = matchMedia('(prefers-reduced-motion: reduce)').matches;
try { const saved = JSON.parse(localStorage.getItem(STORAGE)); if (saved && ['watch', 'play'].includes(saved.mode) && ROLES.some(r => r.id === saved.active)) { const world = restore(saved.world); if (world) { previous = { world, mode: saved.mode, active: saved.active }; w = world; mode = saved.mode; active = saved.active; $('s-resume').hidden = false; } } } catch { /* Invalid or unavailable saves leave a fresh paused station. */ }
function say(text, duration = 5000) { manualHint = text; hintUntil = Date.now() + duration; $('s-hint').textContent = text; }
function save() { if (!ready) return; try { localStorage.setItem(STORAGE, JSON.stringify({ mode, active, world: encode(w) })); $('s-save-status').textContent = '这轮夜班已独立保存'; } catch { $('s-save-status').textContent = '浏览器未开放保存，可继续本轮体验'; } }
function selectRole(id) { if (!ROLES.some(r => r.id === id)) return; active = id; roleButtons.forEach(b => b.setAttribute('aria-pressed', String(b.dataset.shiftRole === id))); updateHud(); }
function reset(scenario, watch = false) { if (!ready) return; w = createShift(scenario); w.paused = false; mode = watch ? 'watch' : 'play'; previous = null; hover = null; lastTime = 0; $('s-resume').hidden = true; selectRole('engineer'); say(watch ? '正在示范：三种职责使用与手动操作相同的派工规则。可切换角色观察，也可接管当前局。' : '调度先隔离电路；工程封漏；医护稳定伤员。派出任务后，切换角色让其他工作同时进行。', 7000); updateHud(); save(); }
function takeover() { mode = 'play'; previous = null; $('s-resume').hidden = true; if (w.phase === 'playing') w.paused = false; updateHud(); }
function assign(id) { if (!ready) return; const result = order(w, active, id); if (result.ok) { const watching = mode === 'watch'; takeover(); say(`${watching ? '已接管当前局。' : ''}${ROLES.find(r => r.id === active).name}开始${task(w, id).name}；可以切换角色安排其他工作。`); updateHud(); save(); } else say(result.reason); }
function consoleTask() { return tasksFor(w, 'dispatcher').find(id => !reason(w, id, 'dispatcher')) || 'evacuate'; }
function pick(sx, sy) { for (let i = 0; i < w.patients.length; i++) { const p = point(w.patients[i].x, w.patients[i].y); if (Math.hypot(sx - p[0], sy - p[1]) < 29) return 'care' + i; } for (const e of EQUIPMENT) { const p = point(e.x, e.y); if (Math.hypot(sx - p[0], sy - p[1]) < 32) return e.id === 'console' ? consoleTask() : e.id === 'bed' ? tasksFor(w, 'medic').find(id => !reason(w, id, 'medic')) || 'care0' : e.id; } return null; }
function pointer(e) { const rect = canvas.getBoundingClientRect(), sx = (e.clientX - rect.left) / rect.width * VIEW.width, sy = (e.clientY - rect.top) / rect.height * VIEW.height; return { sx, sy, tile: cellFromPoint(sx, sy) }; }
canvas.addEventListener('pointerdown', e => { if (!ready || e.button !== 0) return; e.preventDefault(); canvas.focus({ preventScroll: true }); const p = pointer(e); hover = p.tile; const id = pick(p.sx, p.sy); if (id) assign(id); else if (move(w, active, ...p.tile)) { takeover(); say('正在沿通道行走。点击设备或右侧任务可以分配工作。', 3000); updateHud(); save(); } else say('这里没有可行走的通路。请点舱室地面或任务按钮。', 2500); });
canvas.addEventListener('pointermove', e => { hover = pointer(e).tile; }); canvas.addEventListener('pointerleave', () => { hover = null; });
canvas.addEventListener('keydown', e => { if (!ready || e.repeat) return; if (/^Digit[1-3]$/.test(e.code)) { e.preventDefault(); selectRole(ROLES[Number(e.code.slice(-1)) - 1].id); save(); } else if (e.code === 'Space' || e.code === 'KeyP') { e.preventDefault(); $('s-pause').click(); } else if (['ArrowLeft', 'ArrowRight', 'ArrowUp', 'ArrowDown', 'KeyA', 'KeyD', 'KeyW', 'KeyS'].includes(e.code)) { e.preventDefault(); const a = w.crew.find(a => a.id === active), d = { ArrowLeft: [-1, 0], ArrowRight: [1, 0], ArrowUp: [0, -1], ArrowDown: [0, 1], KeyA: [-1, 0], KeyD: [1, 0], KeyW: [0, -1], KeyS: [0, 1] }[e.code]; if (move(w, active, Math.round(a.x) + d[0], Math.round(a.y) + d[1])) { takeover(); save(); } } else if (e.code === 'KeyE' || e.code === 'Enter') { e.preventDefault(); const a = w.crew.find(a => a.id === active), ids = tasksFor(w, active).filter(id => !reason(w, id, active)).sort((aId, bId) => { const aT = target(w, task(w, aId).target), bT = target(w, task(w, bId).target); return Math.hypot(a.x - aT.x, a.y - aT.y) - Math.hypot(a.x - bT.x, a.y - bT.y); }); if (ids.length) assign(ids[0]); else say('当前没有可执行任务。检查其他职业与站点状态。'); } });
roleButtons.forEach(b => b.addEventListener('click', () => { selectRole(b.dataset.shiftRole); save(); })); taskButtons.forEach(b => b.addEventListener('click', () => assign(b.dataset.shiftTask)));
$('s-demo').addEventListener('click', () => reset('standard', true)); $('s-standard').addEventListener('click', () => reset('standard')); $('s-pressure').addEventListener('click', () => reset('pressure'));
$('s-takeover').addEventListener('click', () => { takeover(); say('已接管这轮夜班。当前任务会继续，接下来由你安排。'); save(); });
$('s-pause').addEventListener('click', () => { if (!ready || w.phase !== 'playing') return; previous = null; $('s-resume').hidden = true; w.paused = !w.paused; updateHud(); save(); });
$('s-speed').addEventListener('click', () => { speed = speed === 1 ? 2 : 1; $('s-speed').textContent = `速度 ×${speed}`; });
$('s-paths').addEventListener('click', () => { paths = !paths; $('s-paths').setAttribute('aria-pressed', String(paths)); });
$('s-fullscreen').addEventListener('click', async () => { try { if (document.fullscreenElement) await document.exitFullscreen(); else await $('s-stage').requestFullscreen(); } catch { say('浏览器未开放全屏，可以继续在当前舱室图操作。'); } });
$('s-resume').addEventListener('click', () => { if (!ready || !previous) return; w = restore(encode(previous.world)); mode = previous.mode; active = previous.active; previous = null; $('s-resume').hidden = true; if (w.phase === 'playing') w.paused = false; selectRole(active); say('已继续上次的夜班，其他方向的保存保持独立。'); save(); });
$('s-retry').addEventListener('click', () => reset(w.scenario)); $('s-rewatch').addEventListener('click', () => reset('standard', true));
function backgroundPause() { hover = null; if (ready && !w.paused) { w.paused = true; say('页面暂离，夜班已暂停。点击“继续值守”恢复。'); updateHud(); save(); } }
window.addEventListener('blur', backgroundPause); document.addEventListener('visibilitychange', () => { if (document.hidden) backgroundPause(); }); window.addEventListener('pagehide', save);
function text(id, value) { if ($(id).textContent !== String(value)) $(id).textContent = value; }
function doing(a) { return a.boarded ? '已登船' : w.boarding ? '走向接驳舱' : a.job ? `${a.state === 'working' ? '工作中' : '前往'} · ${task(w, a.job).name}` : a.state === 'walking' ? '行走中' : '待命'; }
function updateHud() {
  const role = ROLES.find(r => r.id === active), remaining = Math.max(0, Math.ceil(w.limit - w.time));
  text('s-oxygen', `${Math.round(w.oxygen)}%`); text('s-power', powered(w) ? '已上线' : w.isolated ? '已隔离' : '离线'); text('s-arrived', `${w.patients.filter(p => p.boarded).length} / ${w.patients.length}`); text('s-kits', w.kits); text('s-clock', `${String(Math.floor(remaining / 60)).padStart(2, '0')}:${String(remaining % 60).padStart(2, '0')}`);
  text('s-role-name', `${role.name} · ${role.title}`); text('s-role-description', descriptions[active]); for (const a of w.crew) text('s-role-' + a.id, doing(a));
  const available = tasksFor(w, active), selected = w.crew.find(a => a.id === active);
  taskButtons.forEach(b => { const id = b.dataset.shiftTask; b.hidden = !available.includes(id); if (b.hidden) return; const t = task(w, id), why = reason(w, id, active), busy = selected.job === id; b.querySelector('b').textContent = t.name; b.querySelector('small').textContent = busy ? selected.state === 'working' ? `执行中 · ${Math.min(100, Math.round(selected.progress / selected.duration * 100))}%` : '正在前往作业地点' : why || `可分配 · 到达后 ${t.duration} 秒`; b.classList.toggle('available', !why); b.classList.toggle('busy', busy); b.disabled = !ready || w.phase !== 'playing' || busy; b.setAttribute('aria-label', `${t.name}，${busy ? '正在执行' : why || '可以分配'}`); });
  text('s-mode', `${mode === 'watch' ? '协作示范' : '亲自值守'} · ${w.scenario === 'pressure' ? '紧急夜班' : '标准夜班'}`); text('s-pause', w.time === 0 && w.paused ? '开始值守' : w.paused ? '继续值守' : '暂停'); $('s-pause').disabled = !ready || w.phase !== 'playing'; $('s-takeover').hidden = mode !== 'watch' || w.phase !== 'playing';
  text('s-hint', Date.now() < hintUntil ? manualHint : previous ? '检测到上次夜班，当前已暂停。可继续上次，也可选择一个新场景。' : status(w));
  text('s-patients', w.patients.map(p => `${p.name} · ${p.boarded ? '已抵达接驳舱' : w.evacuation ? '前往接驳舱' : p.health >= 90 ? '已恢复' : p.stable ? '已稳定，待治疗' : '需要急救'} · ${Math.round(p.health)}%`).join('\n'));
  text('s-log', w.log.slice(-4).map(e => `${String(Math.floor(e.time)).padStart(2, '0')}s / ${e.role} · ${e.message}`).join('\n'));
  $('s-end-card').hidden = w.phase === 'playing'; if (w.phase !== 'playing') { text('s-end-tag', mode === 'watch' ? 'DEMONSTRATION / SHIFT REPORT' : 'SHIFT REPORT'); text('s-end-title', w.phase === 'won' ? '这一班，大家一起完成了。' : '这轮夜班，还差一步。'); text('s-end-detail', w.phase === 'won' ? `用时 ${Math.round(w.time)} 秒，${w.patients.length} 位乘员与 3 位值守人员已登船。工程完成 ${w.stats.repairs} 项修复，医护完成 ${w.stats.stabilized} 次急救与 ${w.stats.treated} 次治疗，调度接通系统并安排撤离。` : w.message); }
}
function frame(timestamp) { const dt = lastTime ? Math.min(.1, Math.max(0, (timestamp - lastTime) / 1000)) : 0; lastTime = timestamp; if (ready) { if (mode === 'watch') demonstration(w); advance(w, dt * speed); drawShift(ctx, w, assets, { active, paths, hover, reducedMotion }); if (timestamp - hudTime > 180) { updateHud(); hudTime = timestamp; } if (timestamp - saveTime > 2500) { save(); saveTime = timestamp; } } requestAnimationFrame(frame); }
const load = url => new Promise((resolve, reject) => { const image = new Image(); image.onload = () => resolve(image); image.onerror = () => reject(new Error('轨道站素材加载失败')); image.src = url; });
try { [assets.background, assets.rooms, assets.equipment, assets.people] = await Promise.all(['orbital-night.png', 'rooms-atlas.png', 'equipment-atlas.png', 'crew-atlas.png'].map(file => load('assets/directions/shift/' + file))); ready = true; $('s-load-status').hidden = true; selectRole(active); if (!previous && new URLSearchParams(location.search).get('demo') === '1') reset('standard', true); updateHud(); requestAnimationFrame(frame); }
catch { $('s-load-status').textContent = '轨道站素材未能装载，请刷新重试。下方仍可查看方向说明与参考。'; ['s-demo', 's-standard', 's-pressure', 's-pause', 's-resume'].forEach(id => $(id).disabled = true); }
