import {gameForms,gameFormMap} from './game-forms-catalog.js?v=20261004-17';
import {directionMap} from './showcase-catalog.js?v=20261004-20';
const params=new URLSearchParams(location.search),qa=params.has('qa'),sides=[],grid=document.querySelector('#comparison-grid');let activeSide=-1;
const element=(tag,cls,text)=>{const node=document.createElement(tag);if(cls)node.className=cls;if(text)node.textContent=text;return node};
const observer=new IntersectionObserver(entries=>{for(const entry of entries)entry.target.contentWindow?.postMessage({type:'game-form-visible',visible:entry.isIntersecting},location.origin)});
function select(side,id){const form=gameFormMap[id]||gameForms[0],d=directionMap[form.play];side.id=form.id;side.select.value=form.id;side.title.textContent=form.name;side.copy.textContent=form.compare;side.actions.textContent=form.action;side.view.textContent=(form.dimension?form.dimension+' · ':'')+form.view;side.rhythm.textContent=form.rhythm;
 const url=new URL('showcase.html',location.href);url.searchParams.set('play',form.play);if(qa)url.searchParams.set('qa','1');if(params.get('edition')==='original')url.searchParams.set('edition','original');url.hash='play';side.link.href=url;
 const embed=new URL(url);embed.hash='';embed.searchParams.set('present','1');side.frame.allow=form.play==='cantor'?'autoplay; fullscreen; microphone':'autoplay; fullscreen';side.frame.src=embed;side.frame.title=form.name+' / '+d.title+'试玩';
 const page=new URL(location.href);page.searchParams.set(side.index===0?'left':'right',form.id);history.replaceState(null,'',page);renderCards();
 if(sides.every(s=>s.id)){const [a,b]=sides.map(s=>gameFormMap[s.id]);document.querySelector('#comparison-title').textContent=a.id===b.id?'在两侧体验同一种形态。':[a,b].every(f=>/横版|侧面/.test(f.view))?'同样横版，操作与场面很不同。':a.name+' × '+b.name+'，比较游戏形态。'}
}
for(let index=0;index<2;index++){
 const panel=element('article','compare-panel'),top=element('div','compare-top'),title=element('h3'),selectBox=element('select');selectBox.setAttribute('aria-label',(index?'右':'左')+'侧游戏形态');for(const f of gameForms){const option=element('option','',f.name+' · '+f.reference);option.value=f.id;selectBox.append(option)}
 const link=element('a','standalone','独立试玩 ↗');link.target='_blank';link.rel='noopener';const focus=element('button','focus-scene','放大画面');focus.type='button';focus.setAttribute('aria-pressed','false');focus.onclick=()=>{const focused=panel.classList.toggle('is-focused');grid.classList.toggle('focused',focused);for(const s of sides){s.focus.textContent=s.panel.classList.contains('is-focused')?'返回对照':'放大画面';s.focus.setAttribute('aria-pressed',String(s.panel.classList.contains('is-focused')))}document.querySelector('#compare').scrollIntoView({block:'start'})};top.append(title,selectBox,link,focus);
 const meta=element('div','form-meta'),view=element('span'),actions=element('span');meta.append(view,actions);const rhythm=element('p','form-rhythm'),copy=element('p','compare-copy'),frame=element('iframe');frame.allow='autoplay; fullscreen';frame.loading=index?'lazy':'eager';const reading=element('details','compare-reading'),summary=element('summary','','形态说明与操作');reading.append(summary,meta,rhythm,copy);panel.append(top,frame,reading);grid.append(panel);
 const side={index,panel,focus,title,select:selectBox,link,view,actions,rhythm,copy,frame,id:null};sides.push(side);selectBox.onchange=()=>select(side,selectBox.value);observer.observe(frame);
}
function renderCards(){const cards=document.querySelector('#form-cards');cards.replaceChildren(...gameForms.map((f,index)=>{const d=directionMap[f.play],card=element('article','form-card'),image=element('img');image.src=d.cover;image.alt=d.title+(d.previewKind||'实际游戏画面');image.loading='lazy';const content=element('div','form-card-content');content.append(element('small','',String(index+1).padStart(2,'0')+' / '+(f.dimension?f.dimension+' · ':'')+f.view),element('h3','',f.name),element('p','',f.description),element('span','form-reference','参考形态：'+f.reference),element('p','form-extension',f.next));const buttons=element('div','form-card-actions');for(const side of sides){const button=element('button','',(side.index?'放到右侧':'放到左侧')+(side.id===f.id?' ✓':''));button.type='button';button.setAttribute('aria-label','将'+f.name+'放到'+(side.index?'右':'左')+'侧');button.setAttribute('aria-pressed',String(side.id===f.id));button.onclick=()=>{select(side,f.id);document.querySelector('#compare').scrollIntoView({behavior:'smooth',block:'start'})};buttons.append(button)}content.append(buttons);card.append(image,content);return card}))}
window.addEventListener('message',event=>{if(event.origin!==location.origin)return;const side=sides.find(s=>s.frame.contentWindow===event.source);if(!side)return;const data=event.data;if(data?.type==='game-form-height'&&Number.isFinite(data.height))side.frame.style.height=Math.min(1400,Math.max(420,data.height))+'px';if(data?.type==='game-form-focused'&&activeSide!==side.index){activeSide=side.index;for(const other of sides)if(other!==side)other.frame.contentWindow.postMessage({type:'game-form-pause'},location.origin)}});
select(sides[0],params.get('left')||'platform');select(sides[1],params.get('right')||'run-gun');
