export const PLAY_WORLDS=[
 {id:'cozy',name:'治愈生活',title:'小谷，留一会儿',art:'粉彩像素 × 生活与陪伴',emotion:'安心 · 被需要 · 归属',invitation:'一个安静的小谷，有个伙伴正在等你。',reason:'你照顾它，它会认出你、回应你。熟悉的小地方开始与你有关。',loop:'摘一颗莓果 → 送给小团 → 决定一起散步或让它休息',observe:['温暖色彩和低威胁场景，让靠近变得轻松。','伙伴的回应，让动作具有关系意义。','花开和随行，把你的行动留在世界里。'],boundary:'这是一段照顾与关系的小体验，不是完整农场经营。'},
 {id:'wonder',name:'神秘探索',title:'森林里，谁留了灯？',art:'发光幻想插画 × 探索与发现',emotion:'好奇 · 期待 · 惊叹',invitation:'远处有一扇暗门，林间散落着微光。',reason:'未知不只是一幅背景。靠近光、留下足迹之后，新的路和故事会出现。',loop:'循光行走 → 点亮三处灯石 → 进入重新苏醒的门',observe:['明暗和藏露，让视线落在可探索的地方。','每次发现都揭示一点线索，推动下一次行动。','门与森林的变化，兑现一开始的未知感。'],boundary:'这里演示一个短探索闭环，不含大型地图、战斗或复杂谜题。'},
 {id:'playful',name:'欢乐卡通',title:'三只小淘气，藏好了吗？',art:'圆润玩具 3D × 捉迷藏与惊喜',emotion:'轻松 · 好笑 · 小成就',invitation:'树叶在晃，朋友们似乎躲得并不太好。',reason:'看懂一点小线索，亲手找到一个朋友，就得到一个有性格的回应。',loop:'观察摇晃的树 → 靠近找朋友 → 找齐后领取帽子',observe:['圆润角色、清楚的造型，让玩法显得友善。','藏得不太好的耳朵和小台词，形成轻微幽默。','朋友加入和戴上帽子，把成功变成可见变化。'],boundary:'原创程序化玩具小场景，未达到商业游戏的角色与场景资产精度。'}
];
export function createWorld(id){return {id,player:{x:448,y:392,heading:0,step:0,moving:false},route:[],pending:null,time:0,particles:[],trail:[],berry:false,friendFed:false,choice:null,flowers:0,runes:[],found:[],reward:false,complete:false,gateGlow:0,events:[],message:'',visit:[],tapCount:0,paused:false}}
export function hotspots(s){if(s.id==='cozy')return [{id:'berry',x:230,y:270,name:s.berry?'莓果已经摘好了':'摘一颗莓果',active:true},{id:'friend',x:s.friendFed&&s.choice==='follow'?s.player.x-37:657,y:s.friendFed&&s.choice==='follow'?s.player.y+16:339,name:s.friendFed?'小团':'在等你的小团',active:true},{id:'garden',x:722,y:437,name:'给小花浇水',active:true}];if(s.id==='wonder')return [{id:'rune-a',x:258,y:292,name:'林间的微光',active:true},{id:'rune-b',x:607,y:217,name:'石上的微光',active:true},{id:'rune-c',x:716,y:417,name:'水边的微光',active:true},{id:'gate',x:786,y:166,name:s.runes.length===3?'走进苏醒的门':'远处的暗门',active:true}];return [{id:'hide-0',x:240,y:257,name:'这棵树在晃',active:!s.found.includes('hide-0')},{id:'hide-1',x:738,y:239,name:'好像露出了一对耳朵',active:!s.found.includes('hide-1')},{id:'hide-2',x:718,y:432,name:'这里传来小笑声',active:!s.found.includes('hide-2')},{id:'gift',x:361,y:259,name:s.found.length===3?'打开朋友的礼物':'朋友留下的礼物',active:true}]}
export function blocked(id,x,y){if(x<45||x>915||y<106||y>500)return true;if(id==='cozy')return ((x-157)/113)**2+((y-424)/43)**2<1||(x>736&&x<856&&y>117&&y<223);if(id==='wonder')return ((x-408)/86)**2+((y-443)/32)**2<1;return hotspots({id,found:[]}).slice(0,3).some(h=>Math.hypot(x-h.x,y-h.y)<28)}
// Grid routes make clicks actual travel through a world, rather than remote rewards.
export function routeTo(s,x,y){const size=32,nx=30,ny=18,key=(x,y)=>y*nx+x,cell=(x,y)=>[Math.max(0,Math.min(nx-1,Math.floor(x/size))),Math.max(0,Math.min(ny-1,Math.floor(y/size)))];const start=cell(s.player.x,s.player.y),target=cell(x,y),queue=[start],seen=new Map([[key(...start),null]]);let nearest=start,best=1e9;
 for(let i=0;i<queue.length;i++){const a=queue[i],dist=Math.hypot(a[0]-target[0],a[1]-target[1]);if(dist<best){best=dist;nearest=a}if(dist<.5)break;for(const [dx,dy] of [[1,0],[-1,0],[0,1],[0,-1]]){const xx=a[0]+dx,yy=a[1]+dy,k=key(xx,yy);if(xx<0||yy<0||xx>=nx||yy>=ny||seen.has(k)||blocked(s.id,xx*size+16,yy*size+16))continue;seen.set(k,a);queue.push([xx,yy])}}
 const result=[];let a=nearest;while(a&&key(...a)!==key(...start)){result.push({x:a[0]*size+16,y:a[1]*size+16});a=seen.get(key(...a))}return result.reverse()}
export function goal(s){if(s.id==='cozy')return s.friendFed?(s.choice?'你们的小谷，已经有了新的故事':'小团吃饱了。让它跟你走，还是在树下休息？'):s.berry?'把莓果送给小团':'给在树边等你的小团，摘一颗莓果';if(s.id==='wonder')return s.complete?'门后的光，原来是整个森林的星空':s.runes.length===3?'三盏灯都亮了，去看看远处的门':'循着微光，唤醒三处灯石';return s.complete?'朋友们给你戴上了小帽子':s.found.length===3?'都找到啦，打开朋友的礼物':'找找摇晃的树，三只朋友藏在这里'}
export function progress(s){if(s.id==='cozy')return s.friendFed?'小团：愿意亲近你':s.berry?'手里有一颗莓果':'今天，从一颗莓果开始';if(s.id==='wonder')return '灯石 '+s.runes.length+' / 3';return '朋友 '+s.found.length+' / 3'}
export function emit(s,type,x,y,count=14){for(let i=0;i<count;i++)s.particles.push({type,x,y,vx:(Math.random()-.5)*80,vy:-25-Math.random()*65,age:0,life:1.2+Math.random()*.7});s.events.push({type,time:s.time});if(s.events.length>80)s.events.shift()}
export function interact(s,id){s.tapCount++;const h=hotspots(s).find(h=>h.id===id);if(!h||Math.hypot(s.player.x-h.x,s.player.y-h.y)>68)return {text:'再靠近一点，看看它会怎样回应你。',changed:false};if(s.id==='cozy'){
 if(id==='berry'){if(s.berry)return {text:s.friendFed?'那颗甜莓果已经送给小团了。莓丛在阳光下，慢慢准备下一次结果。':'口袋里已经有一颗。小团还在树边等你。',changed:false};s.berry=true;emit(s,'berry',h.x,h.y);return {text:'摘到一颗甜莓果。也许，小团会喜欢它。',changed:true}}
 if(id==='friend'){if(s.friendFed){emit(s,'heart',h.x,h.y,5);return {text:s.choice==='rest'?'小团在树下打了个小哈欠：“我会等你回来。”':'小团蹭了蹭你：“还想和你多待一会儿。”',changed:true}}if(!s.berry)return {text:'小团悄悄看着你的口袋。它好像有一点饿。',changed:false};s.friendFed=true;emit(s,'heart',h.x,h.y);return {text:'“谢谢你。”小团第一次主动靠过来。',changed:true}}
 s.flowers++;emit(s,'flower',h.x,h.y,8);return {text:'小花抬起头。你来过的地方，留下了一点颜色。',changed:true}}
 if(s.id==='wonder'){if(id.startsWith('rune')){if(s.runes.includes(id))return {text:'微光仍在。脚下的线索指向下一处灯石。',changed:false};s.runes.push(id);emit(s,'light',h.x,h.y,22);const words=['灯石上写着：“有人曾在这里，为归来的人留灯。”','第二盏灯亮起，森林里多了一条细细的光路。','三道微光连在一起。远处的门，终于有了回应。'];return {text:words[s.runes.length-1],changed:true}}if(s.runes.length<3)return {text:'门没有打开。旁边刻着三枚尚未亮起的符号。',changed:false};s.complete=true;emit(s,'wonder',h.x,h.y,55);return {text:'门后没有宝箱。整个森林的星光，都为你亮了起来。',changed:true}}
 if(id.startsWith('hide')){if(s.found.includes(id))return {text:'这个朋友已经跟上你了。',changed:false};s.found.push(id);emit(s,'pop',h.x,h.y,20);return {text:['“我可没有偷笑！”第一只朋友自己跳了出来。','“你怎么猜到我在这里？”它的耳朵一直露在外面。','“再玩一轮嘛。”最后一只朋友不舍得结束。'][s.found.length-1],changed:true}}if(s.found.length<3)return {text:'礼物里有张小纸条：“找到我们，再一起打开！”',changed:false};s.reward=true;s.complete=true;emit(s,'party',h.x,h.y,45);return {text:'三只朋友给你戴上小帽子：“现在你也是小淘气啦！”',changed:true}}
export function updateWorld(s,dt,input){if(s.paused)return;s.time+=dt;const p=s.player;let dx=input.x,dy=input.y;if(dx||dy){s.route=[];s.pending=null;const len=Math.hypot(dx,dy);dx/=len;dy/=len;const xx=p.x+dx*155*dt,yy=p.y+dy*155*dt;if(!blocked(s.id,xx,p.y))p.x=xx;if(!blocked(s.id,p.x,yy))p.y=yy;p.moving=true;p.heading=Math.atan2(dx,dy)}else if(s.route.length){const next=s.route[0],x=next.x-p.x,y=next.y-p.y,d=Math.hypot(x,y),v=160*dt;if(d<v){p.x=next.x;p.y=next.y;s.route.shift()}else{p.x+=x/d*v;p.y+=y/d*v;p.heading=Math.atan2(x,y)}p.moving=true}else p.moving=false;
 if(p.moving){p.step+=dt*10;if(!s.trail.length||Math.hypot(p.x-s.trail.at(-1).x,p.y-s.trail.at(-1).y)>17)s.trail.push({x:p.x,y:p.y,t:s.time});if(s.trail.length>65)s.trail.shift();if(!s.visit.some(v=>Math.hypot(v.x-p.x,v.y-p.y)<55))s.visit.push({x:p.x,y:p.y})}for(const q of s.particles){q.age+=dt;q.x+=q.vx*dt;q.y+=q.vy*dt;q.vy+=30*dt}s.particles=s.particles.filter(q=>q.age<q.life);s.gateGlow+=(s.runes.length===3?1-s.gateGlow:-s.gateGlow)*dt*1.8}
