import {W,H,clamp,hash,canvasSurface,images,image,cover,label,glow,vignette,action,safeSaved,cardButton} from './showcase-core.js';

export const DECK=Array.from({length:30},(_,i)=>{const kind=i<18?'cargo':i<24?'route':'support',names=['铜矿','茶叶','药品','零件','布匹','粮食'],j=i%6;return {id:i,kind,name:kind==='cargo'?names[j]:kind==='route'?['夜行铁路','河港渡口','山间驿路','旧桥捷径','双程运输','秘密航线'][j]:['提灯领路','同行商队','修复时钟','仓库清点','医师同行','守约回信'][j],value:kind==='cargo'?6+j*2:kind==='route'?1.5+j*.12:8+j*2,art:kind==='cargo'?[2,1,3,5,1,2][j]:kind==='route'?[4,6,0,6,4,0][j]:[7,8,5,2,3,10][j]}});
export function scoreHand(ids,upgrade=0,bonuses={}){const cards=ids.map(id=>DECK[id]).filter(Boolean),cargo=cards.filter(c=>c.kind==='cargo'),routes=cards.filter(c=>c.kind==='route'),supports=cards.filter(c=>c.kind==='support');if(!cargo.length)return {score:0,reason:'至少选择一张货物牌'};let base=cargo.reduce((n,c)=>n+c.value+upgrade,0)+supports.reduce((n,c)=>n+c.value+(bonuses.supportBonus||0),0),mult=routes.reduce((m,c)=>m*(c.value+(bonuses.routeBonus||0)),1),pair=cargo.length>=2&&cargo.some((c,i)=>cargo.some((d,j)=>i!==j&&c.name===d.name));if(pair)mult*=1.8;return {score:Math.round(base*mult),reason:(pair?'同类货物 ×1.8 · ':'')+'基础 '+base+' × 路线 '+mult.toFixed(2)}}
export async function createLedger({host,saved,notify,sfx}){
 const element=document.createElement('div');element.className='tabletop ledger-table';host.append(element);const s=safeSaved(saved,{round:1,score:0,hands:3,discards:2,hand:[0,6,2,18,24,4,20],selected:[],upgrade:0,phase:'play',seed:4292,credits:0,history:[],supportBonus:0,routeBonus:0,relics:[]}),targets=[36,70,105,150,200],contracts=[['重新开张','把第一趟货送到夜市，让熄灯的摊位重新开门。'],['工坊的冬天','供暖管还缺零件，工坊等着下一班车。'],['山路来信','山里需要药，也需要一条有人继续走的路。'],['桥那边的人','旧桥修好了。让两岸重新做起生意。'],['守住约定','最后一趟货送达，商队终于能一起回家。']];let rendered='';
 function drawCard(){s.seed=(s.seed*1664525+1013904223)>>>0;return Math.floor(s.seed/4294967296*30)}
 function refill(){s.hand=s.hand.filter((_,i)=>!s.selected.includes(i));while(s.hand.length<7)s.hand.push(drawCard());s.selected=[]}
 function play(){if(s.phase!=='play'||!s.selected.length)return;const result=scoreHand(s.selected.map(i=>s.hand[i]),s.upgrade,s);if(!result.score){notify(result.reason);return}s.score+=result.score;s.hands--;s.history.push('第 '+s.round+' 轮：'+result.reason+'，收入 '+result.score);refill();sfx('cards');if(s.score>=targets[s.round-1]){s.credits+=s.hands+4;if(s.round===5){s.phase='won';sfx('success')}else s.phase='upgrade'}else if(s.hands===0){s.phase='lost';notify('这一趟的货款不足。下一次可以尝试货物配路线，或组合相同货物。')}render()}
 function discard(){if(s.phase!=='play'||!s.selected.length||s.discards<=0)return;s.discards--;refill();sfx('shuffle');render()}
 function upgrade(i){if(s.phase!=='upgrade')return;if(i===0)s.upgrade+=4;if(i===1){s.credits+=8;s.supportBonus+=6}if(i===2){s.upgrade+=2;s.routeBonus+=.15}s.relics.push(['货仓扩建','同行商队','灵活调度'][i]);sfx('success');s.round++;s.score=0;s.hands=i===1?4:3;s.discards=i===2?3:2;s.phase='play';s.selected=[];render()}
 function node(tag,cls,text){const n=document.createElement(tag);n.className=cls;if(text!==undefined)n.textContent=text;return n}
 function render(){const signature=JSON.stringify(s);if(rendered===signature)return;rendered=signature;element.replaceChildren();const top=node('div','table-title'),heading=node('div','');heading.append(node('small','','NIGHT MARKET / 01'),node('h2','','黑市账本'));const values=node('div','table-values');values.append(node('span','','第 '+s.round+' / 5 轮'),node('strong','',s.score+' / '+targets[s.round-1]));top.append(heading,values);element.append(top);
 const contract=node('div','round-contract');contract.append(node('b','',contracts[s.round-1][0]),node('span','',contracts[s.round-1][1]));element.append(contract);
 const progress=node('div','contract-progress');progress.setAttribute('role','progressbar');progress.setAttribute('aria-valuemin','0');progress.setAttribute('aria-valuemax',String(targets[s.round-1]));progress.setAttribute('aria-valuenow',String(Math.min(s.score,targets[s.round-1])));progress.setAttribute('aria-label','本轮货款进度');const fill=node('i','');fill.style.width=Math.min(100,s.score/targets[s.round-1]*100)+'%';progress.append(fill);element.append(progress);
 if(s.relics.length){const perks=node('div','run-upgrades');s.relics.forEach((text,i)=>{const item=node('span','',text),im=node('img','');im.src='assets/showcase/card-'+[2,8,6][['货仓扩建','同行商队','灵活调度'].indexOf(text)] +'.webp';im.alt='';item.prepend(im);perks.append(item)});element.append(perks)}

 if(s.phase==='upgrade'){const panel=node('div','upgrade-panel');panel.append(node('p','eyebrow','这一趟顺利抵达'),node('h3','','把收获变成下一趟的优势'));[['货仓扩建','每张货物收入 +4，持续到最后一轮',2],['同行商队','支援收入永久 +6；下一轮多一次出牌',8],['灵活调度','路线倍率永久 +0.15、货物 +2；下一轮多一次弃牌',6]].forEach(([title,detail,art],i)=>{const button=cardButton(title,detail,()=>upgrade(i)),im=node('img','');im.src='assets/showcase/card-'+art+'.webp';im.alt='';button.prepend(im);panel.append(button)});element.append(panel);return}
 if(s.phase==='won'||s.phase==='lost'){const end=node('div','table-ending');end.append(node('img','',''));end.firstChild.src='assets/showcase/card-8.webp';end.append(node('h3','',s.phase==='won'?'五趟生意，守住了约定':'这一趟，没能抵达'),node('p','',s.phase==='won'?'商队带回的不只是货款，还有下一次有人愿意与你同行的信誉。':'相同货物会形成组合，路线牌会放大货款。带着这条经验再试一次。'));const log=node('details','trade-log');log.append(node('summary','','回看这五趟交易'));s.history.forEach(text=>log.append(node('p','',text)));end.append(log,cardButton('再做一轮生意','重新选择成长路线',()=>{Object.assign(s,{round:1,score:0,hands:3,discards:2,hand:[0,6,2,18,24,4,20],selected:[],upgrade:0,phase:'play',seed:4292,credits:0,history:[],supportBonus:0,routeBonus:0,relics:[]});render()}));element.append(end);return}
 const preview=scoreHand(s.selected.map(i=>s.hand[i]),s.upgrade,s),center=node('div','deal-preview');center.append(node('span','','选择货物，再配路线或支援'),node('strong','',s.selected.length?'预计收入 '+preview.score:'等待你的组合'),node('small','',s.selected.length?preview.reason:'最多选择三张 · 同类货物产生额外组合'));element.append(center);const hand=node('div','card-hand');s.hand.forEach((id,index)=>{const c=DECK[id],button=node('button','trade-card'+(s.selected.includes(index)?' selected':''));button.type='button';button.setAttribute('aria-pressed',String(s.selected.includes(index)));button.setAttribute('aria-label',c.name+'，'+(c.kind==='cargo'?'货物收入 '+(c.value+s.upgrade):c.kind==='route'?'路线倍率 '+(c.value+s.routeBonus).toFixed(2):'支援收入 '+(c.value+s.supportBonus)));const portrait=node('img','');portrait.src='assets/showcase/card-'+c.art+'.webp';portrait.alt='';button.append(node('small','card-kind',{cargo:'货物',route:'路线',support:'支援'}[c.kind]),portrait,node('b','',c.name),node('span','',c.kind==='route'?'× '+(c.value+s.routeBonus).toFixed(2):'+ '+(c.value+(c.kind==='cargo'?s.upgrade:s.supportBonus))));button.onclick=()=>{if(s.selected.includes(index))s.selected=s.selected.filter(i=>i!==index);else if(s.selected.length<3)s.selected.push(index);else notify('这一手最多选择三张牌。');render()};hand.append(button)});element.append(hand);const buttons=node('div','table-buttons');buttons.append(cardButton('出牌','剩余 '+s.hands+' 次',play,!preview.score),cardButton('弃牌重抽','剩余 '+s.discards+' 次',discard,!s.selected.length||s.discards<=0));element.append(buttons);if(s.history.length){const log=node('div','recent-trade');log.append(node('small','','上一笔交易'),node('span','',s.history.at(-1)));element.append(log)}}
 render();return {element,getState:()=>s,getStatus:()=>({preview:scoreHand(s.selected.map(i=>s.hand[i]),s.upgrade,s),goal:s.phase==='won'?'五轮交易已完成':'通过组合达到第 '+s.round+' 轮的货款目标',message:s.history.at(-1)||'先选择一张货物，再试着配一张路线和一张支援。',stats:['出牌 '+s.hands,'弃牌 '+s.discards,'信誉 '+s.credits,'货仓 +'+s.upgrade,'支援 +'+s.supportBonus,'路线 +'+s.routeBonus.toFixed(2)],actions:[]}),tick(){render()},draw(){},dispose(){element.remove()}};
}

export const TRAVELERS=[
 {name:'米拉',permit:'米拉',origin:'北岸',expires:'2026-10-30',portrait:8,story:'我带了三箱茶叶，镇上的店还等着开门。'},
 {name:'洛安',permit:'洛安娜',origin:'灰堡',expires:'2026-10-25',portrait:10,story:'一路上换过两次车，证件是代理人帮我办的。'},
 {name:'苏禾',permit:'苏禾',origin:'北岸',expires:'2026-09-30',portrait:8,story:'证件过期了，但孩子需要的药就在关口另一边。'},
 {name:'贺川',permit:'贺川',origin:'灰堡',expires:'2026-11-12',portrait:11,story:'工坊请我来修供暖管。入冬前要把它修好。'},
 {name:'安弥',permit:'安弥',origin:'旧港',expires:'2026-11-02',portrait:10,story:'旧港已经没有我的住处了。这里还有一位愿意收留我的亲人。'},
 {name:'方守',permit:'方守',origin:'北岸',expires:'2026-10-15',portrait:9,story:'我回来接家人。你今天的决定，会留在他们的记忆里。'}
];
export function inspectTraveler(t){return {name:t.name===t.permit,date:t.expires>='2026-10-03',origin:['北岸','灰堡'].includes(t.origin)}}
export async function createCheckpoint({host,saved,sfx}){
 const element=document.createElement('div');element.className='tabletop checkpoint-table';host.append(element);const s=safeSaved(saved,{index:0,credits:8,correct:0,exceptions:0,phase:'inspect',history:[],field:null,end:null,lastDecision:null});let signature='';
 const n=(tag,cls,text)=>{const e=document.createElement(tag);e.className=cls;if(text!==undefined)e.textContent=text;return e};
 function fieldReview(){if(s.phase!=='inspect'||!s.field)return null;const t=TRAVELERS[s.index],ok=inspectTraveler(t)[s.field];return {ok,text:s.field==='name'?'护照「'+t.name+'」 / 许可「'+t.permit+'」':s.field==='date'?'证件截止 '+t.expires+' / 今日 2026-10-03':'来源「'+t.origin+'」 / 今日准许北岸与灰堡居民'};}
 function decide(kind){if(s.phase!=='inspect')return;const t=TRAVELERS[s.index],checks=inspectTraveler(t),valid=Object.values(checks).every(Boolean),correct=(kind==='allow'&&valid)||(kind==='deny'&&!valid);if(kind==='exception'){s.credits-=1;s.exceptions++;s.history.push(t.name+'：例外放行，承担 1 枚罚款。')}else{s.credits+=correct?3:-2;if(correct)s.correct++;s.history.push(t.name+'：'+(kind==='allow'?'放行':'拒绝')+'，'+(correct?'核验正确 +3':'核验有误 −2'))}s.lastDecision={kind,valid,correct,name:t.name};s.phase='result';s.field=null;sfx(kind==='exception'?'stamp':correct?'success':'hurt');render()}
 function next(){s.index++;if(s.index>=TRAVELERS.length){s.credits-=12;s.phase='ended';s.end=s.credits>=0?'今天的收入支付了食物与供暖。': '工资没能支付全部生活开支。';s.end+=s.exceptions?'你留下了 '+s.exceptions+' 次例外，几位旅人记住了关口这张桌子。':'你严格遵守了规则，关口的秩序维持到了夜里。'}else s.phase='inspect';s.lastDecision=null;render()}
 function render(){const key=JSON.stringify(s);if(key===signature)return;signature=key;element.replaceChildren();const title=n('div','table-title'),h=n('div','');h.append(n('small','','BORDER OFFICE / 2026.10.03'),n('h2','','边境值班室'));title.append(h,n('span','office-money','生活费 '+s.credits));element.append(title);
 const rules=n('div','office-rules');rules.append(n('b','','今日通行规则'),n('span','','姓名一致 · 证件未过期 · 仅北岸 / 灰堡居民'));element.append(rules);
 if(s.phase==='ended'){element.append(n('div','office-ending',s.end));const log=n('ol','office-log');s.history.forEach(text=>log.append(n('li','',text)));element.append(log);return}
 const t=TRAVELERS[s.index],desk=n('div','office-desk'),person=n('div','traveler-window'),portrait=n('img','');portrait.src='assets/showcase/card-'+t.portrait+'.webp';portrait.alt=t.name+'的肖像';person.append(portrait,n('b','',t.name),n('p','',t.story));const docs=n('div','documents');const passport=n('article','passport'),permit=n('article','permit');passport.append(n('small','','护照 / PASSPORT'),n('h3','',t.name));permit.append(n('small','','入境许可 / ENTRY PERMIT'),n('h3','',t.permit));
 for(const [field,a,b] of [['name','姓名：'+t.name,'姓名：'+t.permit],['origin','签发地：'+t.origin,'来源：'+t.origin],['date','有效期：'+t.expires,'许可截止：'+t.expires]]){for(const [doc,text] of [[passport,a],[permit,b]]){const button=n('button','document-field'+(s.field===field?' inspected':''),text);button.type='button';button.onclick=()=>{s.field=field;render()};doc.append(button)}}docs.append(passport,permit);
 if(s.phase==='inspect'&&s.field){const checks=inspectTraveler(t),review=n('div','field-review '+(checks[s.field]?'valid':'invalid'));review.setAttribute('role','status');review.append(n('b','',checks[s.field]?'字段符合规则':'字段需要注意'),n('span','',fieldReview().text));docs.append(review)}
 if(s.phase==='result'&&s.lastDecision){const stamp=n('span','document-stamp stamp-'+s.lastDecision.kind,{allow:'准许通行',deny:'退回申请',exception:'例外放行'}[s.lastDecision.kind]);permit.append(stamp)}
 desk.append(person,docs);element.append(desk);
 if(s.phase==='result'){const result=n('div','stamp-result',s.history.at(-1));element.append(result);element.append(cardButton(s.index===5?'结算今天':'下一位旅人','这次决定已记录',next));}else{const buttons=n('div','table-buttons stamp-buttons');buttons.append(cardButton('放行','按规定准许通行',()=>decide('allow')),cardButton('拒绝','退回本次申请',()=>decide('deny')),cardButton('例外放行','承担 1 枚罚款',()=>decide('exception')));element.append(buttons)}}
 render();return {element,getState:()=>s,getStatus:()=>({fieldReview:fieldReview(),goal:s.phase==='ended'?'今天的值班已结算':'核对第 '+(s.index+1)+' 位旅人的证件，再作出决定',message:s.end||s.history.at(-1)||'可以点选姓名、来源与日期，在两份证件之间对照。',stats:['旅人 '+Math.min(6,s.index+1)+'/6','正确核验 '+s.correct,'例外 '+s.exceptions,'生活费 '+s.credits],actions:[]}),tick:render,draw(){},dispose(){element.remove()}};
}

export const DIRECTIONS=[[1,0],[0,1],[-1,0],[0,-1]];
export const BUILD_COST={belt:2,smelt:6,generator:5};
export function factoryStep(s){const occupied=new Set(s.items.map(p=>p.x+':'+p.y)),next=[];for(const p of s.items){const here=s.cells[p.x+':'+p.y];if(!here)continue;const [dx,dy]=DIRECTIONS[here.dir||0],x=p.x+dx,y=p.y+dy,dest=s.cells[x+':'+y];if(!dest||occupied.has(x+':'+y)){next.push(p);continue}if(dest.type==='smelt'){const powered=DIRECTIONS.some(([gx,gy])=>s.cells[(x+gx)+':'+(y+gy)]?.type==='generator');if(!powered){next.push(p);continue}next.push({x,y,kind:'ingot'});}else if(dest.type==='depot'){if(p.kind==='ingot')s.delivered++;else next.push(p)}else if(dest.type==='belt'){next.push({x,y,kind:p.kind})}else next.push(p)}if(!occupied.has('0:3'))next.push({x:0,y:3,kind:'ore'});s.items=next;return s}
export async function createFactory({host,input,saved,notify,sfx}){
 const {element,ctx}=canvasSurface(host),art=await images(Array.from({length:6},(_,i)=>'machine-'+i)),s=safeSaved(saved,{cells:{'0:3':{type:'mine',dir:0},'1:3':{type:'belt',dir:0},'2:3':{type:'belt',dir:0},'6:3':{type:'smelt',dir:0},'9:3':{type:'depot',dir:0}},items:[],budget:18,delivered:0,tool:'belt',dir:0,won:false,productionPaused:false,edits:[]});let t=0,timer=0,flash=0;const cell=85,bx=135,by=87;
 function place(x,y){if(x<0||x>=10||y<0||y>=6||s.won)return;const k=x+':'+y,old=s.cells[k];if(s.tool==='remove'){if(old&&BUILD_COST[old.type]){s.edits.push({key:k,before:structuredClone(old),after:null,delta:BUILD_COST[old.type]});s.edits=s.edits.slice(-20);s.budget+=BUILD_COST[old.type];delete s.cells[k];s.items=s.items.filter(p=>p.x!==x||p.y!==y);sfx('pickup')}return}if(old){notify('格子已有设施。先选择拆除，回收后再放置。');return}const cost=BUILD_COST[s.tool];if(s.budget<cost){notify('建设预算不足。可拆除已有设施回收。');return}s.cells[k]={type:s.tool,dir:s.dir};s.edits.push({key:k,before:null,after:structuredClone(s.cells[k]),delta:-cost});s.edits=s.edits.slice(-20);s.budget-=cost;sfx('build')}
 function undo(){const edit=s.edits.pop();if(!edit||s.won)return;if(edit.before)s.cells[edit.key]=edit.before;else delete s.cells[edit.key];s.budget-=edit.delta;s.items=s.items.filter(p=>p.x+':'+p.y!==edit.key);notify('已撤销上一处设施编辑。已交付铜锭与生产时间保留。');sfx('pickup')}
 return {element,getState:()=>s,getStatus:()=>({goal:s.won?'十件铜锭已交付':'连接矿机、熔炉与仓库，交付十件铜锭',message:'矿机在左，仓库在右。补齐中间传送带，并在熔炉相邻格放一台发电机。',stats:['交付 '+s.delivered+'/10','预算 '+s.budget,'方向 '+['右','下','左','上'][s.dir],'工具 '+({belt:'传送带',smelt:'熔炉',generator:'发电机',remove:'拆除'}[s.tool])],actions:[action('传送带 · 2',()=>s.tool='belt'),action('熔炉 · 6',()=>s.tool='smelt'),action('发电机 · 5',()=>s.tool='generator'),action('旋转 R',()=>s.dir=(s.dir+1)%4),action('拆除并回收',()=>s.tool='remove'),action(s.productionPaused?'恢复输送':'暂停输送 · 施工',()=>s.productionPaused=!s.productionPaused,s.won),action('撤销上次编辑',undo,!s.edits.length||s.won)]}),tick(dt){t+=dt;if(input.pressed.has('KeyR'))s.dir=(s.dir+1)%4;for(const p of input.pointers)place(Math.floor((p.x-bx)/cell),Math.floor((p.y-by)/cell));if(s.won||s.productionPaused)return;timer+=dt;if(timer>1){timer-=1;factoryStep(s);if(s.delivered>=10){s.won=true;notify('第十件铜锭进入仓库。你设计的生产线完成了交付。');sfx('success')}}},draw(){ctx.fillStyle='#121e26';ctx.fillRect(0,0,W,H);glow(ctx,580,320,450,'#3e655433');label(ctx,'COPPER / 铜轨工坊',W/2,43,'#e9d4ad',24);for(let y=0;y<6;y++)for(let x=0;x<10;x++){ctx.fillStyle=(x+y)%2?'#233038':'#29363d';ctx.fillRect(bx+x*cell,by+y*cell,cell-1,cell-1);ctx.strokeStyle='#435257';ctx.strokeRect(bx+x*cell,by+y*cell,cell-1,cell-1);const c=s.cells[x+':'+y];if(c){const index={mine:0,belt:1,smelt:2,depot:3,generator:4}[c.type];ctx.drawImage(art['machine-'+index],bx+x*cell+2,by+y*cell-8,81,84);if(c.type!=='generator'){ctx.save();ctx.translate(bx+x*cell+65,by+y*cell+69);ctx.rotate(c.dir*Math.PI/2);ctx.fillStyle='#e7cb94';ctx.beginPath();ctx.moveTo(-9,-4);ctx.lineTo(2,-4);ctx.lineTo(2,-8);ctx.lineTo(10,0);ctx.lineTo(2,8);ctx.lineTo(2,4);ctx.lineTo(-9,4);ctx.fill();ctx.restore()}}}
 const hover=input.hover;if(hover&&!s.won){const x=Math.floor((hover.x-bx)/cell),y=Math.floor((hover.y-by)/cell);if(x>=0&&x<10&&y>=0&&y<6){const old=s.cells[x+':'+y],valid=s.tool==='remove'?!!BUILD_COST[old?.type]:!old&&s.budget>=BUILD_COST[s.tool];ctx.save();ctx.globalAlpha=.55;if(s.tool!=='remove')ctx.drawImage(art['machine-'+({belt:1,smelt:2,generator:4}[s.tool])],bx+x*cell+2,by+y*cell-8,81,84);ctx.globalAlpha=1;ctx.strokeStyle=valid?'#b7edbc':'#ed9f94';ctx.lineWidth=3;ctx.strokeRect(bx+x*cell+2,by+y*cell+2,cell-5,cell-5);ctx.restore();label(ctx,valid?(s.tool==='remove'?'拆除回收 +'+BUILD_COST[old.type]:'建设费用 '+BUILD_COST[s.tool]):old?'已有设施':'预算不足',bx+x*cell+42,by+y*cell-14,valid?'#cbe7bd':'#edac9e',13)}}
 for(const p of s.items){const c=s.cells[p.x+':'+p.y],d=DIRECTIONS[c?.dir||0],progress=clamp(timer,0,.75);ctx.drawImage(art['machine-5'],bx+(p.x+.32+d[0]*progress*.42)*cell,by+(p.y+.32+d[1]*progress*.42)*cell,27,27);if(p.kind==='ingot'){ctx.fillStyle='#ffc07d';ctx.fillRect(bx+(p.x+.4)*cell,by+(p.y+.36)*cell,18,10)}}if(s.won)label(ctx,'生产线已经兑现了你的设计',W/2,320,'#ffdeb0',28)},dispose(){element.remove()}};
}

export function advanceGarden(s){s.plots.forEach(p=>{if(p.seed&&p.water){p.growth=Math.min(2,p.growth+1);p.water=false}});s.day++;s.energy=9;if(s.day>3)s.phase='ended';return s}
export async function createGarden({host,input,saved,notify,sfx}){
 const {element,ctx}=canvasSurface(host),town=await image('assets/showcase/town/tilemap_packed.png'),farm=await image('assets/showcase/farm/tilemap_packed.png'),s=safeSaved(saved,{day:1,energy:9,seeds:6,harvest:0,gifts:0,tool:'seed',selected:0,plots:Array.from({length:6},()=>({seed:false,water:false,growth:0})),phase:'play',letter:null});let t=0;
 const pos=i=>({x:305+(i%3)*95,y:280+Math.floor(i/3)*95});
 function work(i=s.selected){if(s.phase!=='play')return;const p=s.plots[i];if(s.energy<=0){notify('今天的体力用完了，结束一天后会恢复。');return}if(s.tool==='seed'){if(p.seed||s.seeds<=0){notify(p.seed?'所选田地已经播种。先选择空田再播种。':'种子已经用完。');return}p.seed=true;s.seeds--;s.energy--;sfx('plant')}if(s.tool==='water'){if(!p.seed||p.water||p.growth>=2){notify(!p.seed?'所选田地还没有种子。':p.growth>=2?'这块田地已经成熟，可以收获。':'这块田地今天已经浇水。');return}p.water=true;s.energy--;sfx('water')}if(s.tool==='harvest'){if(p.growth<2){notify('作物需要两次浇水并跨过两个夜晚，才会成熟。');return}p.seed=false;p.water=false;p.growth=0;s.harvest++;s.energy--;sfx('pickup')}}
 function endDay(){if(s.phase!=='play')return;advanceGarden(s);notify(s.phase==='ended'?'三天结束了。你种出的作物和送出的礼物，留在了这座小镇。':'第 '+s.day+' 天，邻居的窗又打开了。昨天浇过水的作物长大了一些。');sfx('day')}
 function gift(){if(s.harvest<=0){notify('邻居希望尝尝你亲手种出的作物。成熟后收获，再送来。');return}s.harvest--;s.gifts++;s.letter='邻居：我把你送来的菜放进了今晚的汤里。明天来，一起吃吧。';sfx('success');notify(s.letter)}
 function tile(atlas,index,x,y,size=48){ctx.drawImage(atlas,index%12*16,Math.floor(index/12)*16,16,16,x,y,size,size)}
 return {element,getState:()=>s,command(id){if(id.startsWith('plot-')){const i=Number(id.slice(5));if(Number.isInteger(i)&&i>=0&&i<6)s.selected=i}},getStatus:()=>({goal:s.phase==='ended'?'三日农场已留下记录':'种植、浇水，收获后把作物送给邻居',message:s.letter||'播种和浇水会消耗体力。浇过水的作物在夜里生长，第二次生长后可收获。',stats:['第 '+Math.min(s.day,3)+' / 3 天','体力 '+s.energy,'种子 '+s.seeds,'收获 '+s.harvest,'送礼 '+s.gifts],actions:[action('播种所选田地',()=>{s.tool='seed';work()},s.phase!=='play'),action('浇水所选田地',()=>{s.tool='water';work()},s.phase!=='play'),action('收获所选田地',()=>{s.tool='harvest';work()},s.phase!=='play'),action('送礼给邻居',gift,s.harvest<=0),action('结束一天 · '+s.plots.filter(p=>p.seed&&p.water&&p.growth<2).length+' 块将生长',endDay,s.phase!=='play')]}),tick(dt){t+=dt;for(const p of input.pointers){const i=s.plots.findIndex((_,i)=>{const point=pos(i);return Math.abs(point.x+40-p.x)<45&&Math.abs(point.y+40-p.y)<45});if(i>=0){s.selected=i;work(i)}else if(p.x>760&&p.y<380)gift()}},draw(){ctx.imageSmoothingEnabled=false;
 for(let y=0;y<14;y++)for(let x=0;x<25;x++)tile(town,(x*7+y*3)%19===0?2:0,x*48,y*48,48);
 for(let x=0;x<24;x++){tile(town,13,x*48,495,48);tile(town,37,x*48,543,48)}
 for(let y=6;y<11;y++)for(let x=17;x<19;x++)tile(town,25,x*48,y*48,48);
 const houseRows=[[52,53,54],[64,65,66],[72,73,75],[84,86,87]];houseRows.forEach((row,y)=>row.forEach((index,x)=>tile(town,index,790+x*48,175+y*48,48)));
 for(const [x,y] of [[40,75],[215,78],[510,75],[680,80],[1000,90],[35,270],[60,410],[950,395]]){
  tile(town,(x%3)?16:28,x+12,y,72);
 }
 for(let x=0;x<6;x++)tile(town,x===0?80:x===5?82:81,680+x*48,445,48);
 tile(farm,109,240,365,44);tile(farm,108,855,378,44);tile(farm,120,740,350+Math.sin(t)*3,32);tile(farm,121,970,435,32);
 for(let i=0;i<6;i++){const p=s.plots[i],point=pos(i);tile(farm,p.water?1:0,point.x,point.y,82);if(p.seed)tile(farm,[16,17,20][p.growth],point.x+15,point.y+5,54);if(p.water){ctx.fillStyle='#84d3e0';ctx.fillRect(point.x+63,point.y+62,7,9)}if(i===s.selected){ctx.strokeStyle='#fff0a9';ctx.lineWidth=4;ctx.strokeRect(point.x-3,point.y-3,88,88)}}label(ctx,'你的田地',445,244,'#fff5d9',23);label(ctx,'邻居的小屋',880,155,'#fff5d9',20);label(ctx,s.phase==='ended'?'这一季的小小收获':'第 '+s.day+' 天 · '+['','晴晨','午后微风','成熟的早晨'][Math.min(s.day,3)],W/2,40,'#fff5d9',22);ctx.imageSmoothingEnabled=true},dispose(){element.remove()}};
}
