import {W,H,clamp,images,image,canvasSurface,cover,sprite,shadow,glow,label,vignette,action,safeSaved} from './showcase-core.js';

export async function createSuspense({host,input,saved,notify,sfx}){
 const {element,ctx}=canvasSurface(host),art=await images(['night','checkpoint-scene','radio-scene',...Array.from({length:4},(_,i)=>'worker-'+i),...Array.from({length:6},(_,i)=>'rail-prop-'+i)]),props=Array.from({length:6},(_,i)=>art['rail-prop-'+i]);
 const s=safeSaved(saved,{chapter:0,x:100,y:412,vy:0,battery:false,power:false,log:false,end:null,choice:null,alerts:0,exposure:0,decision:null}),floor=412;let time=0,walk=0,flash=0,cooldown=0,facing=false;
 function message(){return s.end?s.end:s.chapter===0?(s.power?'闸门通电了。走向右边的出口。':s.battery?'把电池送到控制台，E 接通电路。':'广播：最后一班列车停在封锁线外。先找到备用电池。'):s.chapter===1?(s.log?'记录显示：封锁是为了隐藏一次错误调度。继续前往广播室。':'探照灯仍在巡逻。按住 S 蹲下，在货箱附近避开光束；找到右侧的值班记录。'):'广播室里还有一条可以发出的消息。走近控制台，决定谁应该听见真相。'}
 function interact(){if(s.end)return;if(s.chapter===0){if(!s.battery&&Math.abs(s.x-330)<100){s.battery=true;sfx('pickup');notify('备用电池到手。广播中有人说：别把门关上。')}else if(s.battery&&Math.abs(s.x-700)<95){s.power=true;sfx('success');notify('控制台重新亮起，维修闸门缓缓打开。')}}else if(s.chapter===1&&Math.abs(s.x-820)<100){s.log=true;sfx('pickup');notify('你发现一页记录：有人在事故之前，手动关闭了信号。')}else if(s.chapter===2&&Math.abs(s.x-820)<120){s.choice=true;notify('发送完整记录，可能暴露你的位置；只恢复列车，可以安全离开。')}}
 function finish(choice){s.decision=choice;s.end=choice==='truth'?'你把记录送进公共广播。远处一盏盏窗灯亮起来，列车上的人终于知道这一夜发生了什么。':'你恢复了最后一班列车的信号。列车离站，记录留在值班室，你带着尚未回答的问题回家。';s.choice=null;sfx('success')}
 return {element,getState:()=>s,getStatus:()=>({goal:s.end?'这一夜的决定已经留下': ['找到电池，接通控制台，打开闸门','避开探照灯，找到值班记录','走进广播室，作出最后的决定'][s.chapter],message:message(),stats:['维修段 '+(s.chapter+1)+'/3',s.battery?'电池：已取得':'电池：未取得',s.log?'事故记录：已取得':'事故记录：未取得','被发现 '+s.alerts+' 次'],actions:s.end?[action('重走这一夜',()=>{Object.assign(s,{chapter:0,x:100,y:412,vy:0,battery:false,power:false,log:false,end:null,choice:null,alerts:0,exposure:0,decision:null});cooldown=flash=0})]:s.choice?[action('公开完整记录',()=>finish('truth')),action('只恢复列车',()=>finish('train'))]:[action('互动 E',interact)]}),command:interact,
 tick(dt){time+=dt;flash=Math.max(0,flash-dt);cooldown=Math.max(0,cooldown-dt);if(s.end||s.choice)return;const crouch=input.keys.has('KeyS')||input.keys.has('ArrowDown');s.x=clamp(s.x+input.x*(crouch?85:225)*dt,45,1060);walk+=Math.abs(input.x)*dt;if(input.x)facing=input.x<0;
 if(input.pressed.has('Space')&&s.y>=floor-1&&!crouch)s.vy=-540;s.vy+=1400*dt;s.y=Math.min(floor,s.y+s.vy*dt);if(s.y===floor)s.vy=0;
 if(input.pressed.has('KeyE')||input.pointers.length)interact();
 if(s.chapter===0&&!s.power)s.x=Math.min(s.x,925);
 if(s.chapter===1){const beam=560+Math.sin(time*.62)*350,hidden=crouch&&Math.abs(s.x-510)<100;s.exposure=clamp(s.exposure+(Math.abs(s.x-beam)<55&&!hidden&&cooldown===0?dt:-dt*2),0,.6);if(s.exposure>=.6){s.alerts++;s.x=450;s.exposure=0;flash=.4;cooldown=3;notify('灯光扫到了你。货箱是可以藏身的地方，再试一次。');sfx('hurt')}if(!s.log)s.x=Math.min(s.x,995)}
 if(s.x>1020&&s.chapter<2){s.chapter++;s.x=80;s.y=floor;s.vy=0;notify(message());sfx('door')}
 },draw(){ctx.save();cover(ctx,art[['night','checkpoint-scene','radio-scene'][s.chapter]]);ctx.fillStyle=['rgba(5,15,24,.10)','rgba(12,21,28,.08)','rgba(19,18,12,.05)'][s.chapter];ctx.fillRect(0,0,W,H);if(s.chapter<2)for(let i=0;i<48;i++){const x=(i*109+time*25)%W,y=(i*71+time*310)%H;ctx.strokeStyle='rgba(180,205,220,.13)';ctx.beginPath();ctx.moveTo(x,y);ctx.lineTo(x-5,y+14);ctx.stroke()}
 if(s.chapter===0){if(!s.battery){sprite(ctx,props[0],330,floor,50);glow(ctx,330,floor-20,65,'#4ba5a177');label(ctx,'备用电池',330,floor-61)}sprite(ctx,props[1],700,floor,150);glow(ctx,700,330,120,s.power?'#d5a25566':'#48b8b533');label(ctx,s.power?'控制台 · 已通电':'控制台',700,265);if(!s.power){ctx.fillStyle='rgba(5,9,13,.86)';ctx.fillRect(945,195,55,218);ctx.strokeStyle='#78433d';for(let i=0;i<5;i++){ctx.beginPath();ctx.moveTo(945+i*12,195);ctx.lineTo(945+i*12,412);ctx.stroke()}label(ctx,'闸门 · 未通电',970,175)}else label(ctx,'前往封锁线 →',975,220)}
 if(s.chapter===1){sprite(ctx,props[2],510,floor,120);const beam=560+Math.sin(time*.62)*350;ctx.fillStyle='rgba(225,194,134,.15)';ctx.beginPath();ctx.moveTo(beam-90,100);ctx.lineTo(beam-80,floor);ctx.lineTo(beam+95,floor);ctx.closePath();ctx.fill();glow(ctx,beam,floor-10,130,'#cdae6344');sprite(ctx,props[3],820,floor,42);label(ctx,s.log?'值班记录 · 已取得':'值班记录',820,340);label(ctx,'货箱 · 蹲下藏身',510,270)}
 if(s.chapter===2){sprite(ctx,props[4],820,floor,148);glow(ctx,820,320,145,'#d6a26155');label(ctx,'公共广播控制台',820,250)}
 const crouch=input.keys.has('KeyS')||input.keys.has('ArrowDown'),frame=crouch?3:Math.abs(input.x)?1+Math.floor(walk*7)%2:0;shadow(ctx,s.x,s.y,25);sprite(ctx,art['worker-'+frame],s.x,s.y,crouch?100:142,facing);glow(ctx,s.x+18,s.y-65,80,'#50c7ca24');vignette(ctx);
 const prompt=s.chapter===0?(!s.battery&&Math.abs(s.x-330)<100?'E · 取得备用电池':s.battery&&!s.power&&Math.abs(s.x-700)<95?'E · 接通电源':''):s.chapter===1?(Math.abs(s.x-510)<100&&crouch?'正在货箱后藏身':!s.log&&Math.abs(s.x-820)<100?'E · 读取值班记录':''):Math.abs(s.x-820)<120&&!s.end?'E · 打开广播控制台':'';
 if(prompt)label(ctx,prompt,s.x,floor+45,'#bde9e7',17);
 label(ctx,['01 / 维修通路','02 / 封锁线','03 / 广播室'][s.chapter],155,48,'#c3d4d6',15);
 if(s.chapter===1&&s.exposure>0){ctx.fillStyle='#3b2428';ctx.fillRect(440,40,240,6);ctx.fillStyle='#e7ac81';ctx.fillRect(440,40,240*s.exposure/.6,6);label(ctx,'探照灯正在锁定你',560,75,'#e7b894',15)}
 if(s.chapter===2&&s.end&&s.decision==='truth')for(let i=0;i<5;i++)glow(ctx,110+i*85,135+(i%2)*35,25,'#ffc37d66');
 if(flash>0){ctx.fillStyle=`rgba(160,43,36,${flash})`;ctx.fillRect(0,0,W,H)}if(s.end)label(ctx,'这一夜，结束了',W/2,210,'#efc989',30);ctx.restore()},dispose(){element.remove()}};
}

export {createCombat} from './showcase-combat.js';

export const SHAPES=[[[1,1,1,1]],[[1,1],[1,1]],[[0,1,0],[1,1,1]],[[0,1,1],[1,1,0]],[[1,1,0],[0,1,1]],[[1,0,0],[1,1,1]],[[0,0,1],[1,1,1]]];
export const rotate=m=>m[0].map((_,i)=>m.map(row=>row[i]).reverse());
export function sevenBag(random=Math.random){const bag=[0,1,2,3,4,5,6];for(let i=bag.length-1;i>0;i--){const j=Math.floor(random()*(i+1));[bag[i],bag[j]]=[bag[j],bag[i]]}return bag}
export function collides(board,m,x,y){return m.some((row,j)=>row.some((v,i)=>v&&(x+i<0||x+i>=10||y+j>=18||(y+j>=0&&board[y+j][x+i]))))}
export function settle(board,m,x,y,type){for(let j=0;j<m.length;j++)for(let i=0;i<m[j].length;i++)if(m[j][i]&&y+j>=0)board[y+j][x+i]=type+1;const kept=board.filter(row=>row.some(v=>!v)),cleared=18-kept.length;while(kept.length<18)kept.unshift(Array(10).fill(0));return {board:kept,cleared}}
export async function createOrder({host,input,saved,sfx}){
 const {element,ctx}=canvasSurface(host),gems=await Promise.all(['blue','green','red','yellow'].map(c=>image('assets/showcase/platform2d/gem_'+c+'.png'))),s=safeSaved(saved,{board:Array.from({length:18},()=>Array(10).fill(0)),score:0,lines:0,type:0,next:2,x:3,y:0,matrix:SHAPES[0],over:false,hold:null,heldThisTurn:false,bag:sevenBag().filter(t=>t!==0&&t!==2)}),colors=['#64c8ed','#eee1a0','#be92dd','#69d9b9','#ea8b7c','#7195e0','#f0b46b'];let timer=0,repeat=0,time=0;
 function drop(){if(s.over)return;if(!collides(s.board,s.matrix,s.x,s.y+1)){s.y++;return}const result=settle(s.board,s.matrix,s.x,s.y,s.type);s.board=result.board;s.lines+=result.cleared;s.score+=[0,100,300,500,800][result.cleared]*(1+Math.floor(s.lines/8));if(result.cleared)sfx('success');s.type=s.next;if(!s.bag.length)s.bag=sevenBag();s.next=s.bag.pop();s.matrix=structuredClone(SHAPES[s.type]);s.x=3;s.y=0;s.heldThisTurn=false;s.over=collides(s.board,s.matrix,s.x,s.y)}
 function hold(){
  if(s.over||s.heldThisTurn)return;const current=s.type;
  if(s.hold===null){s.type=s.next;if(!s.bag.length)s.bag=sevenBag();s.next=s.bag.pop()}else s.type=s.hold;
  s.hold=current;s.matrix=structuredClone(SHAPES[s.type]);s.x=3;s.y=0;s.heldThisTurn=true;timer=0;s.over=collides(s.board,s.matrix,s.x,s.y);sfx('turn');
 }
 function move(dx){if(!s.over&&!collides(s.board,s.matrix,s.x+dx,s.y))s.x+=dx}
 function turn(){const m=rotate(s.matrix);for(const offset of [0,-1,1,-2,2])if(!collides(s.board,m,s.x+offset,s.y)){s.matrix=m;s.x+=offset;break}}
 function hard(){if(s.over)return;while(!collides(s.board,s.matrix,s.x,s.y+1)){s.y++;s.score+=2}drop();sfx('drop')}
 function block(x,y,t,alpha=1){ctx.save();ctx.globalAlpha=alpha;ctx.fillStyle=colors[t%7];ctx.shadowColor=colors[t%7];ctx.shadowBlur=8;ctx.fillRect(x+2,y+2,29,29);ctx.shadowBlur=0;ctx.drawImage(gems[t%4],x+2,y+2,29,29);ctx.restore()}
 return {element,getState:()=>s,getStatus:()=>({goal:'旋转、排列、消除完整的一行',message:s.over?'晶格已经堆到顶端。可以重新开始挑战。':'半透明晶格是落点预览。每组七种形状都会出现一次，速度随消行增加。',stats:['得分 '+s.score,'消行 '+s.lines,'速度等级 '+(1+Math.floor(s.lines/8))],actions:[action('← 左移',()=>move(-1),s.over),action('旋转 ↑',turn,s.over),action('右移 →',()=>move(1),s.over),action('直接落底',hard,s.over),action('暂存 / 交换 C',hold,s.over||s.heldThisTurn)]}),tick(dt){time+=dt;if(s.over)return;timer+=dt;repeat-=dt;if(input.pressed.has('ArrowUp')||input.pressed.has('KeyW'))turn();if(input.pressed.has('KeyC'))hold();if(input.pressed.has('Space'))hard();if(input.x&&repeat<=0){move(input.x);repeat=.13}if(timer>(input.y>0?.045:Math.max(.12,.8-s.lines*.025))){timer=0;drop()}},draw(){ctx.fillStyle='#0b1020';ctx.fillRect(0,0,W,H);glow(ctx,290,270,390,'#18496b66');glow(ctx,800,330,300,'#52315c44');const bx=320,by=17,cell=33;ctx.fillStyle='#080d18';ctx.fillRect(bx-6,by-6,342,606);for(let y=0;y<18;y++)for(let x=0;x<10;x++){ctx.strokeStyle='#202a3b';ctx.strokeRect(bx+x*cell,by+y*cell,cell,cell);if(s.board[y][x])block(bx+x*cell,by+y*cell,s.board[y][x]-1)}let ghost=s.y;while(!collides(s.board,s.matrix,s.x,ghost+1))ghost++;for(let j=0;j<s.matrix.length;j++)for(let i=0;i<s.matrix[j].length;i++)if(s.matrix[j][i]){block(bx+(s.x+i)*cell,by+(ghost+j)*cell,s.type,.15);block(bx+(s.x+i)*cell,by+(s.y+j)*cell,s.type)}label(ctx,'暂存 C',170,130,'#b5c7d9',21);if(s.hold!==null)SHAPES[s.hold].forEach((row,j)=>row.forEach((v,i)=>{if(v)block(110+i*33,160+j*33,s.hold,s.heldThisTurn?.5:1)}));label(ctx,'下一枚',785,130,'#b5c7d9',21);SHAPES[s.next].forEach((row,j)=>row.forEach((v,i)=>{if(v)block(720+i*33,160+j*33,s.next)}));label(ctx,String(s.score).padStart(5,'0'),790,340,'#eee1bd',40);label(ctx,'旋转秩序，留住空间',785,410,'#b5c7d9');if(s.over)label(ctx,'本次得分 '+s.score,W/2,300,'#ffcc95',28)},dispose(){element.remove()}};
}

export async function createPlatformer({host,input,saved,notify,sfx}){
 const {element,ctx}=canvasSurface(host),names=['background_color_hills','terrain_grass_block_top','terrain_grass_block_center','character_purple_idle','character_purple_walk_a','character_purple_walk_b','character_purple_jump','coin_gold','flag_green_a','spring','slime_normal_walk_a','slime_normal_walk_b'];const art={};await Promise.all(names.map(async n=>art[n]=await image('assets/showcase/platform2d/'+n+'.png')));
 const s=safeSaved(saved,{x:80,y:560,vy:0,stamps:[],checkpoint:80,hits:0,won:false,movingClock:0}),platforms=[{x:0,y:560,w:650},{x:260,y:470,w:150},{x:430,y:395,w:120},{x:820,y:560,w:560},{x:880,y:465,w:145},{x:1040,y:375,w:140},{x:1450,y:560,w:1000},{x:1510,y:465,w:140},{x:1700,y:395,w:170}],coins=[{x:475,y:348},{x:1090,y:325},{x:1750,y:345}],moving={x:685+Math.sin(s.movingClock*.8)*45,y:510,w:100};platforms.push(moving);let t=s.movingClock,camera=0,ground=false,jumpBuffer=0,coyote=0,invuln=0;
 function jump(){jumpBuffer=.12}function reset(){s.x=s.checkpoint;s.y=530;s.vy=0;s.hits++;invuln=1;sfx('hurt')}
 return {element,getState:()=>s,getStatus:()=>({goal:s.won?'三枚邮票和信件都已送达':'收集三枚邮票，抵达云端邮局',message:s.won?'收件人：原来信真的会从山谷那边送来。谢谢你跑过这一程。':'金色邮票在高处。踩上平台再跳，遇见弹簧会跳得更高。',stats:['邮票 '+s.stamps.length+' / 3','路程 '+Math.min(100,Math.round(s.x/2250*100))+'%','重新落脚 '+s.hits+' 次'],actions:[action('跳跃',jump,s.won)]}),tick(dt){t+=dt;s.movingClock=t;const oldX=moving.x;moving.x=685+Math.sin(t*.8)*45;if(ground&&Math.abs(s.y-moving.y)<1&&s.x+22>oldX&&s.x-22<oldX+moving.w)s.x+=moving.x-oldX;invuln=Math.max(0,invuln-dt);if(s.won)return;if(input.pressed.has('Space')||input.pressed.has('KeyW')||input.pressed.has('ArrowUp')||input.pointers.length)jump();jumpBuffer-=dt;coyote=ground?.09:Math.max(0,coyote-dt);if(jumpBuffer>0&&coyote>0){s.vy=-660;jumpBuffer=0;coyote=0;ground=false;sfx('jump')}s.x=clamp(s.x+input.x*285*dt,30,2310);const previous=s.y;s.vy+=1550*dt;s.y+=s.vy*dt;ground=false;for(const p of platforms)if(s.x+22>p.x&&s.x-22<p.x+p.w&&previous<=p.y+3&&s.y>=p.y&&s.vy>=0){s.y=p.y;s.vy=0;ground=true;break}
 if(s.x>900&&s.x<1360)s.checkpoint=850;if(s.x>1500)s.checkpoint=1480;if(ground&&s.x>1195&&s.x<1250){s.vy=-900;ground=false;sfx('jump')}if(s.y>730)reset();for(let i=0;i<coins.length;i++)if(!s.stamps.includes(i)&&Math.hypot(s.x-coins[i].x,s.y-45-coins[i].y)<48){s.stamps.push(i);sfx('pickup')}
 const enemyX=1840+Math.sin(t)*65;if(invuln===0&&Math.abs(s.x-enemyX)<35&&s.y>520){if(s.vy>100&&previous<540){s.vy=-540;invuln=1;sfx('pickup')}else reset()}
 if(s.x>2240){if(s.stamps.length===3){s.won=true;sfx('success')}else{notify('邮局还在等三枚路线邮票。高处的平台上还有没拿到的。');s.x=2220}}camera+=((clamp(s.x-350,0,1330))-camera)*Math.min(1,dt*6);
 },draw(){ctx.fillStyle='#a9d9eb';ctx.fillRect(0,0,W,H);cover(ctx,art.background_color_hills);ctx.save();ctx.translate(-camera,0);for(const p of platforms){for(let x=p.x;x<p.x+p.w;x+=64){ctx.drawImage(art.terrain_grass_block_top,x,p.y,64,64);if(p.y===560)ctx.drawImage(art.terrain_grass_block_center,x,p.y+64,64,64)}}for(let i=0;i<coins.length;i++)if(!s.stamps.includes(i)){const c=coins[i];ctx.drawImage(art.coin_gold,c.x-20,c.y-20+Math.sin(t*3+i)*5,40,40);glow(ctx,c.x,c.y,55,'#f8e19466')}ctx.drawImage(art.flag_green_a,2210,400,95,160);ctx.drawImage(art.spring,1190,520,64,40);const enemyX=1840+Math.sin(t)*65;ctx.drawImage(art['slime_normal_walk_'+(Math.floor(t*5)%2?'a':'b')],enemyX-30,515,60,45);let name=!ground?'character_purple_jump':input.x?'character_purple_walk_'+(Math.floor(t*10)%2?'a':'b'):'character_purple_idle';sprite(ctx,art[name],s.x,s.y,84,input.x<0,invuln>0?.6:1);label(ctx,'云端邮局',2250,375,'#fff6dd',19);ctx.restore();if(s.won)label(ctx,'今天，信终于到了',W/2,170,'#ffedc4',32)},dispose(){element.remove()}};
}
