import {W,H,clamp,images,canvasSurface} from './showcase-core.js';
import {pointerPosition} from './showcase-precision-kit.js';
import {sceneHeading,completion} from './showcase-observation-kit.js?v=20261004-2';
import {logicPanel,atlasSprite} from './showcase-logic-kit.js?v=20261004-1';

export const BUBBLE={cols:8,rows:10,radius:23,dx:48,dy:Math.sqrt(3)*24,x:380,y:110,launch:{x:560,y:551},budget:40};
export function bubblePoint(i){const r=Math.floor(i/BUBBLE.cols),c=i%BUBBLE.cols;return {x:BUBBLE.x+c*BUBBLE.dx+(r%2)*24,y:BUBBLE.y+r*BUBBLE.dy}}
export function bubbleNeighbors(i){const r=Math.floor(i/8),c=i%8,offset=r%2?1:-1,out=[];for(const [dc,dr] of [[-1,0],[1,0],[0,-1],[offset,-1],[0,1],[offset,1]]){const x=c+dc,y=r+dr;if(x>=0&&x<8&&y>=0&&y<10)out.push(y*8+x)}return out}
export function bubbleFresh(){const cells=Array(80).fill(-1);for(let r=0;r<4;r++)for(let c=0;c<8;c++)cells[r*8+c]=(Math.floor(c/2)+Math.floor(r/2))%4;return {version:1,cells,angle:-90,current:2,next:3,shots:0,popped:0,dropped:0,phase:'play',won:false,preview:true,projectile:null}}
export function bubbleGroup(cells,index,same=false){const color=cells[index];if(color<0)return [];const seen=new Set([index]),queue=[index];for(let n=0;n<queue.length;n++)for(const k of bubbleNeighbors(queue[n]))if(!seen.has(k)&&cells[k]>=0&&(!same||cells[k]===color)){seen.add(k);queue.push(k)}return queue}
export function bubbleResolve(s,index){const matched=bubbleGroup(s.cells,index,true),removed=[];if(matched.length>=3){matched.forEach(i=>{removed.push({i,color:s.cells[i],drop:false});s.cells[i]=-1});s.popped+=matched.length;const anchored=new Set();for(let i=0;i<8;i++)if(s.cells[i]>=0)bubbleGroup(s.cells,i).forEach(k=>anchored.add(k));s.cells.forEach((color,i)=>{if(color>=0&&!anchored.has(i)){removed.push({i,color,drop:true});s.cells[i]=-1;s.dropped++}})}s.won=s.cells.every(v=>v<0);s.phase=s.won?'won':s.shots>=BUBBLE.budget||s.cells.slice(72).some(v=>v>=0)?'lost':'play';return removed}
export function bubbleLanding(s,p,hit){const choices=hit===-1?Array.from({length:8},(_,i)=>i):bubbleNeighbors(hit);return choices.filter(i=>s.cells[i]<0).sort((a,b)=>{const x=bubblePoint(a),y=bubblePoint(b);return Math.hypot(x.x-p.x,x.y-p.y)-Math.hypot(y.x-p.x,y.y-p.y)})[0]??-1}
export function bubbleFlight(s,p,dt){if(!Number.isFinite(dt)||dt<=0)return null;let remaining=Math.min(.25,dt);while(remaining>0){const step=Math.min(.004,remaining);remaining-=step;p.x+=p.vx*step;p.y+=p.vy*step;const left=BUBBLE.x-1,right=BUBBLE.x+7*48+24+1;if(p.x<left){p.x=2*left-p.x;p.vx=Math.abs(p.vx)}if(p.x>right){p.x=2*right-p.x;p.vx=-Math.abs(p.vx)}if(p.y<=BUBBLE.y)return bubbleLanding(s,p,-1);let closest=-1,distance=Infinity;s.cells.forEach((color,i)=>{if(color<0)return;const q=bubblePoint(i),d=Math.hypot(p.x-q.x,p.y-q.y);if(d<45.5&&d<distance){closest=i;distance=d}});if(closest>=0)return bubbleLanding(s,p,closest)}return null}
export function bubbleShoot(s){if(s.phase!=='play'||s.projectile)return false;const a=s.angle*Math.PI/180;s.projectile={...BUBBLE.launch,vx:Math.cos(a)*720,vy:Math.sin(a)*720,color:s.current};s.shots++;return true}
function reload(s){const available=[...new Set(s.cells.filter(v=>v>=0))];if(!available.length)return;s.current=available.includes(s.next)?s.next:available[s.shots%available.length];s.next=available[(s.shots+1)%available.length]}
export function bubbleStep(s,dt){if(!s.projectile||s.phase!=='play')return null;const index=bubbleFlight(s,s.projectile,dt);if(index===null)return null;if(index<0){s.phase='lost';s.projectile=null;return {blocked:true,removed:[]}}s.cells[index]=s.projectile.color;s.projectile=null;const removed=bubbleResolve(s,index);reload(s);return {index,removed}}
export function bubbleProjection(s){const p={...BUBBLE.launch,vx:Math.cos(s.angle*Math.PI/180)*720,vy:Math.sin(s.angle*Math.PI/180)*720},path=[{...BUBBLE.launch}];for(let n=0;n<240;n++){const index=bubbleFlight(s,p,.01);if(n%4===0)path.push({x:p.x,y:p.y});if(index!==null)return {path,index,point:index>=0?bubblePoint(index):null}}return {path,index:-1,point:null}}
export function bubbleRestore(raw){const s=bubbleFresh();if(raw?.version!==1||!Array.isArray(raw.cells)||raw.cells.length!==80||!raw.cells.every(v=>Number.isInteger(v)&&v>=-1&&v<4))return s;s.cells=[...raw.cells];for(const k of ['shots','popped','dropped'])s[k]=Number.isInteger(raw[k])?clamp(raw[k],0,100000):0;s.angle=Number.isFinite(raw.angle)?clamp(raw.angle,-158,-22):-90;for(const k of ['current','next'])s[k]=Number.isInteger(raw[k])?clamp(raw[k],0,3):s[k];s.preview=raw.preview!==false;const p=raw.projectile;if(p&&['x','y','vx','vy'].every(k=>Number.isFinite(p[k]))&&p.y>=BUBBLE.y-30&&p.y<=H&&p.x>=BUBBLE.x-30&&p.x<=BUBBLE.x+400&&p.vy<0&&Math.hypot(p.vx,p.vy)<=721&&Number.isInteger(p.color)&&p.color>=0&&p.color<4)s.projectile={...p};s.won=s.cells.every(v=>v<0);s.phase=s.won?'won':!s.projectile&&(raw.phase==='lost'||s.shots>=40||s.cells.slice(72).some(v=>v>=0))?'lost':'play';if(s.won)s.projectile=null;return s}

export async function createBubble({host,input,saved,sfx=()=>{}}){
 const art=await images(['dome','orbs'],'assets/game-forms/bubble/'),{element,ctx}=canvasSurface(host);element.style.touchAction='none';element.setAttribute('aria-label','琉璃穹顶：点画面瞄准发射，左右键调角，空格发射，E 换球');
 let s=bubbleRestore(saved),active=false,time=0,particles=[],message=s.won?'整座穹顶已经清空。':s.shots?'已恢复球阵与上次发射进度。':'三颗同色连通即可消除；切断支撑，让整串琉璃掉落。';
 const ui=logicPanel(host,'bubble',`<div class="logic-toolbar"><span class="readout"></span><button class="primary shoot">发射琉璃</button><button class="swap">交换待发球</button><label>瞄准角度 <input class="angle" type="range" min="-158" max="-22" value="-90" aria-label="瞄准角度"></label><button class="preview" aria-pressed="true">反弹预览：开</button><button class="retry">重新布阵</button></div><p class="logic-note">点场地直接瞄准发射，侧壁可以反弹。颜色同时用 ◆ / △ / ✦ / ○ 区分。方向键调角 · 空格发射 · E 换球；40 发内清空穹顶。</p>`);
 const q=k=>ui.panel.querySelector('.'+k),shoot=q('shoot'),swap=q('swap'),angle=q('angle'),preview=q('preview'),retry=q('retry'),readout=q('readout');
 function sync(){shoot.disabled=swap.disabled=angle.disabled=!active||s.phase!=='play'||!!s.projectile;preview.disabled=retry.disabled=!active;angle.value=String(s.angle);preview.textContent='反弹预览：'+(s.preview?'开':'关');preview.setAttribute('aria-pressed',String(s.preview));readout.textContent=`剩余 ${s.cells.filter(v=>v>=0).length} 颗 · ${40-s.shots} 发 · 消除 ${s.popped} / 掉落 ${s.dropped}`}
 function fire(){if(active&&bubbleShoot(s)){message='琉璃正在飞行，落点由反弹和碰撞决定。';sfx('shoot');sync()}}
 shoot.onclick=fire;swap.onclick=()=>{if(active&&!s.projectile&&s.phase==='play'){[s.current,s.next]=[s.next,s.current];sync()}};angle.oninput=()=>{if(active&&!s.projectile)s.angle=Number(angle.value)};preview.onclick=()=>{if(active){s.preview=!s.preview;sync()}};retry.onclick=()=>{if(active){s=bubbleFresh();particles=[];message='已重新布阵。先寻找两颗同色相连的琉璃。';sync()}};
 const click=e=>{if(!active||s.projectile||s.phase!=='play')return;const p=pointerPosition(element,e);if(p.y>BUBBLE.launch.y-30)return;s.angle=clamp(Math.atan2(p.y-BUBBLE.launch.y,p.x-BUBBLE.launch.x)*180/Math.PI,-158,-22);fire()};element.addEventListener('click',click);
 function tick(dt){if(!active)return;dt=Number.isFinite(dt)?clamp(dt,0,.25):0;time+=dt;particles=particles.filter(p=>p.life>0);for(const p of particles){p.life-=dt;p.x+=p.vx*dt;p.vy+=350*dt;p.y+=p.vy*dt}if(!s.projectile&&s.phase==='play'){s.angle=clamp(s.angle+input.x*dt*72,-158,-22);if(input.pressed.has('Space'))fire();if(input.pressed.has('KeyE'))swap.click()}const result=bubbleStep(s,dt);if(result){for(const p of result.removed){const pos=bubblePoint(p.i);particles.push({...pos,color:p.color,vx:Math.sin(p.i*12.7)*70,vy:p.drop?45:-80,life:p.drop?1.3:.6,drop:p.drop})}message=s.won?'所有琉璃已清空，穹顶重获光亮。':s.phase==='lost'?'本次布阵结束，可重新布阵再试。':result.removed.length?`本发释放 ${result.removed.length} 颗琉璃，悬空球会继续掉落。`:'已落入邻格；继续凑齐三颗同色。';sfx(result.removed.length?'success':'turn');sync()}else if(input.x)sync()}
 function orb(color,x,y,size,alpha=1){ctx.save();ctx.globalAlpha=alpha;atlasSprite(ctx,art.orbs,color,x,y,size);ctx.restore()}
 function draw(){ctx.drawImage(art.dome,0,0,W,H);ctx.save();ctx.fillStyle='#071a343b';ctx.beginPath();ctx.roundRect(BUBBLE.x-35,82,7*48+24+70,425,15);ctx.fill();ctx.strokeStyle='#cbb58c70';ctx.lineWidth=2;ctx.stroke();ctx.setLineDash([5,9]);ctx.strokeStyle='#dd938a88';ctx.beginPath();ctx.moveTo(BUBBLE.x-25,505);ctx.lineTo(BUBBLE.x+7*48+49,505);ctx.stroke();ctx.restore();
 if(s.preview&&!s.projectile&&s.phase==='play'){const guide=bubbleProjection(s);ctx.save();ctx.fillStyle='#f8e6bbb0';for(const p of guide.path){ctx.beginPath();ctx.arc(p.x,p.y,2,0,Math.PI*2);ctx.fill()}if(guide.point){ctx.strokeStyle='#f6db9b';ctx.lineWidth=2;ctx.setLineDash([5,5]);ctx.beginPath();ctx.arc(guide.point.x,guide.point.y,23,0,Math.PI*2);ctx.stroke()}ctx.restore()}
 s.cells.forEach((color,i)=>{if(color>=0){const p=bubblePoint(i);orb(color,p.x,p.y,51)}});for(const p of particles)orb(p.color,p.x,p.y,p.drop?49:49*(p.life/.6),clamp(p.life/.5,0,1));if(s.projectile)orb(s.projectile.color,s.projectile.x,s.projectile.y,51);orb(s.current,560,551,63);orb(s.next,654,565,43);ctx.save();ctx.textAlign='center';ctx.fillStyle='#ebdbb9';ctx.font='12px "Microsoft YaHei",sans-serif';ctx.fillText('待发',560,601);ctx.fillText('下一颗',654,603);ctx.restore();sceneHeading(ctx,'琉璃穹顶',`瞄准与反弹 · 三颗连通消除 · 悬空掉落     ${s.shots}/40 发`);if(s.won)completion(ctx,'穹顶重获光亮',`${s.shots} 发 · 消除 ${s.popped} 颗 · 掉落 ${s.dropped} 颗`);else if(s.phase==='lost')completion(ctx,'本次布阵结束','下方重新布阵，试着从侧面切断支撑')}
 sync();return {tick,draw,onStart(){active=true;sync()},setActive(v){if(active===v)return;active=v;sync()},getState(){return structuredClone(s)},getStatus(){return {goal:s.won?'琉璃穹顶已清空':s.phase==='lost'?'重新布阵再试':'40 发内清空全部琉璃',message,stats:[`剩余 ${s.cells.filter(v=>v>=0).length} 颗`,`发射 ${s.shots}/40`,`悬空掉落 ${s.dropped}`],actions:[]}},dispose(){element.removeEventListener('click',click);ui.dispose()}};
}
