import * as THREE from './vendor/showcase/three.module.js';
import {GLTFLoader} from './vendor/showcase/GLTFLoader.js';
import {clone as cloneSkeleton} from './vendor/showcase/SkeletonUtils.js';
import {clamp,action,safeSaved} from './showcase-core.js';
const loader=new GLTFLoader(),modelCache=new Map();
async function model(pack,name){const key=pack+'/'+name;if(!modelCache.has(key))modelCache.set(key,loader.loadAsync('assets/showcase/'+key+'.glb'));return modelCache.get(key)}
export async function loadModels(pack,names){const models={};await Promise.all(names.map(async name=>models[name]=await model(pack,name)));return models}
function copy(gltf){const object=cloneSkeleton(gltf.scene);object.traverse(n=>{if(n.isMesh){n.castShadow=true;n.receiveShadow=true}});return object}
export function batchStatic(scene,objects){scene.updateMatrixWorld(true);const groups=new Map();for(const o of objects)o.traverse(n=>{if(!n.isMesh||n.isSkinnedMesh||Array.isArray(n.material))return;const id=n.geometry.uuid+'/'+n.material.uuid;const list=groups.get(id)||[];list.push(n);groups.set(id,list)});for(const list of groups.values()){if(list.length<4)continue;const first=list[0],instanced=new THREE.InstancedMesh(first.geometry,first.material,list.length);list.forEach((n,i)=>{instanced.setMatrixAt(i,n.matrixWorld);n.visible=false});instanced.castShadow=first.castShadow;instanced.receiveShadow=first.receiveShadow;scene.add(instanced)}}
export function roomBase(host,night=true){const scene=new THREE.Scene();scene.background=new THREE.Color(night?'#081321':'#c4dfe5');scene.fog=new THREE.Fog(scene.background,night?15:27,night?42:75);const camera=new THREE.PerspectiveCamera( sixty(),16/9,.05,100),renderer=new THREE.WebGLRenderer({antialias:true,alpha:false});renderer.setPixelRatio(Math.min(devicePixelRatio,1.75));renderer.setSize(1120,630,false);renderer.shadowMap.enabled=true;renderer.shadowMap.type=THREE.PCFSoftShadowMap;renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=night?1.15:1.1;renderer.domElement.className='play-canvas';renderer.domElement.tabIndex=0;renderer.domElement.setAttribute('aria-label','可移动的立体游戏场景');host.append(renderer.domElement);
 scene.add(new THREE.HemisphereLight(night?0xa3c7e4:0xe9f5ff,night?0x10151c:0x5f7851,night?.8:1.4));const sun=new THREE.DirectionalLight(night?0xa9c9f0:0xffdeb3,night?1.6:2.8);sun.position.set(8,17,9);sun.castShadow=true;sun.shadow.mapSize.set(1024,1024);sun.shadow.camera.left=sun.shadow.camera.bottom=-22;sun.shadow.camera.right=sun.shadow.camera.top=22;sun.shadow.camera.far=65;sun.shadow.bias=-.001;scene.add(sun);if(night){renderer.shadowMap.autoUpdate=false;renderer.shadowMap.needsUpdate=true}let lastDraw=0,slowFrames=0,adaptive=false;const resize=()=>{const width=host.clientWidth||1120,height=host.clientHeight||width*9/16;renderer.setSize(width,height,false);camera.aspect=width/height;camera.updateProjectionMatrix()},observer=new ResizeObserver(resize);observer.observe(host);return {scene,camera,renderer,element:renderer.domElement,draw(){const now=performance.now();slowFrames=lastDraw&&now-lastDraw>90?slowFrames+1:Math.max(0,slowFrames-1);lastDraw=now;if(slowFrames>=12&&!adaptive){adaptive=true;renderer.setPixelRatio(.8);renderer.shadowMap.enabled=false;resize()}renderer.render(scene,camera)},dispose(){observer.disconnect();renderer.dispose();renderer.forceContextLoss();renderer.domElement.remove()}}}
function sixty(){return 60}
export function put(scene,gltf,x,y,z,scale=1,rotation=0){const o=copy(gltf);o.position.set(x,y,z);o.scale.setScalar(scale);o.rotation.y=rotation;scene.add(o);return o}
export function light(scene,x,y,z,color=0xffba66,power=8,range=9){const l=new THREE.PointLight(color,power,range,2);l.position.set(x,y,z);scene.add(l);return l}
export function sign(scene,text,x,y,z,width=1.8){const c=document.createElement('canvas');c.width=512;c.height=160;const g=c.getContext('2d');g.fillStyle='#101b27';g.fillRect(0,0,512,160);g.strokeStyle='#c8ad76';g.strokeRect(6,6,500,148);g.fillStyle='#e7dbbf';g.font='29px Microsoft YaHei';g.textAlign='center';g.fillText(text,256,93);const t=new THREE.CanvasTexture(c);t.colorSpace=THREE.SRGBColorSpace;const plane=new THREE.Mesh(new THREE.PlaneGeometry(width,width*160/512),new THREE.MeshBasicMaterial({map:t,side:THREE.DoubleSide}));plane.position.set(x,y,z);scene.add(plane);return plane}
function line(scene,color,points){const beam=new THREE.Group();beam.userData.color=color;scene.add(beam);setBeam(beam,points);return beam}
function setBeam(beam,points){while(beam.children.length<points.length-1){const material=new THREE.MeshBasicMaterial({color:beam.userData.color,transparent:true,opacity:.8});beam.add(new THREE.Mesh(new THREE.CylinderGeometry(.022,.022,1,8),material))}for(let i=0;i<points.length-1;i++){const a=new THREE.Vector3(...points[i]),b=new THREE.Vector3(...points[i+1]),d=b.clone().sub(a),o=beam.children[i];o.position.copy(a).add(b).multiplyScalar(.5);o.scale.y=d.length();o.quaternion.setFromUnitVectors(new THREE.Vector3(0,1,0),d.normalize())}}
const key=(x,z)=>Math.round(x)+':'+Math.round(z);
export function hasBridge(blocks){const queue=Object.keys(blocks).filter(cell=>cell.startsWith('0:')&&blocks[cell]),seen=new Set(queue);while(queue.length){const cell=queue.shift(),[x,z]=cell.split(':').map(Number);if(x===2)return true;for(const [dx,dz] of [[1,0],[-1,0],[0,1],[0,-1]]){const next=key(x+dx,z+dz);if(x+dx>=0&&x+dx<=2&&Math.abs(z+dz)<=4&&blocks[next]&&!seen.has(next)){seen.add(next);queue.push(next)}}}return false}

export async function createStation({host,input,saved,notify,sfx,mode='station'}){
 const world=roomBase(host,true),{scene,camera}=world,art=await loadModels('station',['floor','wall','wall-door-wide','wall-window','door-single','container','container-tall','computer','computer-wide','table-display-small','wall-switch','pipe','chair','wall-detail']);
 const isRange=mode==='range',s=safeSaved(saved,isRange?{x:0,z:8,yaw:0,pitch:0,hp:100,ammo:12,reload:0,dead:[],shots:0,hits:0,won:false}:{x:0,z:3,yaw:0,pitch:0,solved:[false,false,false],mirror:0,battery:'floor',order:[],won:false});let time=0,shootCD=0,flash=0,stepClock=0;const uses=[],doors=[],occluders=[],targets=[],beams=[],roomLights=[];const hud=document.createElement("div");hud.className="scene-hud";host.append(hud);const disposeWorld=world.dispose;world.dispose=()=>{hud.remove();disposeWorld()};
 camera.position.set(s.x,1.65,s.z);camera.rotation.set(s.pitch,s.yaw,0,'YXZ');scene.add(camera);
 const addUse=(o,x,z,type,index=0)=>{o.userData.use={x,z,type,index};uses.push(o);return o};
 function tiles(cx,cz,w=3,d=3){for(let x=0;x<w;x++)for(let z=0;z<d;z++){const px=cx+(x-(w-1)/2)*3,pz=cz+(z-(d-1)/2)*3;put(scene,art.floor,px,-.9,pz,3);const roof=put(scene,art.floor,px,3.9,pz,3);roof.rotation.x=Math.PI}}
 if(!isRange){for(let r=0;r<3;r++){const cz=-r*10;tiles(0,cz);for(let i=-1;i<=1;i++){const left=put(scene,art[i===0?'wall-window':'wall'],-4.5,0,cz+i*3,3,Math.PI/2),right=put(scene,art[i===0?'wall-detail':'wall'],4.5,0,cz+i*3,3,Math.PI/2);occluders.push(left,right);for(const zz of [cz+4.5,cz-4.5]){const panel=put(scene,art[i===0?'wall-door-wide':'wall'],i*3,0,zz,3);occluders.push(panel)}}for(const zz of [cz-4.8,cz-5.2])put(scene,art.floor,0,-.9,zz,3);roomLights.push(light(scene,-2.8,2.3,cz+1,0x73bad0,8,9));light(scene,2.5,2.2,cz-2,0xffbc6f,7,8);put(scene,art.pipe,-4.15,2.7,cz,2.5,Math.PI/2);put(scene,art.chair,3,0,cz+2,1.4,Math.PI);sign(scene,['01 / 光路','02 / 能源','03 / 信号'][r],0,2.5,cz-4.3,2.2);const door=put(scene,art['door-single'],0,0,cz-4.4,3);doors.push(door)}
  const mirror=addUse(put(scene,art['table-display-small'],0,0,0,2),0,0,'mirror');sign(scene,'E · 转动光路',0,.8,.35,1.1);const reflector=new THREE.Mesh(new THREE.PlaneGeometry(.8,.65),new THREE.MeshStandardMaterial({color:0xd2eaf5,metalness:.95,roughness:.09,side:THREE.DoubleSide}));reflector.position.set(0,1.05,0);scene.add(reflector);mirror.userData.reflector=reflector;beams.push(line(scene,0x79e8f0,[[-3,1.05,0],[0,1.05,0],[3,1.05,0]]));put(scene,art.computer,-3.2,0,-2.5,2,Math.PI/2);sign(scene,'接通北侧接收器',-2,1.9,-3.9,2);
  const battery=addUse(put(scene,art.container,-2,0,-8,1),-2,-8,'battery');const socket=addUse(put(scene,art.computer,2,0,-12,2.2,Math.PI),2,-12,'socket');sign(scene,'备用电池',-2,.95,-8,1.4);sign(scene,'能源插槽',2,1.6,-11.7,1.4);
  for(let i=0;i<3;i++){const x=(i-1)*2,panel=addUse(put(scene,art['wall-switch'],x,.7,-23.7,2),x,-23,'panel',i);light(scene,x,1.5,-23.2,[0x60d9ed,0xf0ebe1,0xf5ad56][i],4,3)}sign(scene,'蓝 → 琥珀 → 白',0,2,-23.5,2.4);sign(scene,'最后一班列车',0,2.5,-26.2,2.8);
  function use(target){if(s.won||!target)return;const u=target.userData.use;if(Math.hypot(s.x-u.x,s.z-u.z)>2.2){notify('走近这个设备，再按 E 互动。');return}if(u.type==='mirror'){s.mirror=(s.mirror+1)%4;s.solved[0]=s.mirror===1;if(s.solved[0])sfx('door');notify(s.solved[0]?'光束到达北侧接收器，第一道门打开了。':'光束转向了另一面，接收器仍然暗着。');sfx('turn')}if(u.type==='battery'&&s.battery==='floor'){s.battery='held';notify('电池已经拿起，送到房间另一端的能源插槽。');sfx('pickup')}if(u.type==='socket'){if(s.battery==='held'){s.battery='installed';s.solved[1]=true;notify('能源接通，第二道门打开。');sfx('success')}else notify('这个插槽需要备用电池。')}if(u.type==='panel'&&!s.solved[2]){const correct=[0,2,1];if(u.index===correct[s.order.length]){s.order.push(u.index);sfx('pickup');if(s.order.length===3){s.solved[2]=true;notify('最后一道门打开了。向前走，列车还在等你。');sfx('success')}else notify('信号 '+s.order.length+'/3 正确。')}else{s.order=[];notify('信号顺序不符。看墙上的提示，再从蓝色开始。');sfx('hurt')}}}
  function nearest(){return uses.filter(o=>!(o.userData.use.type==='battery'&&s.battery!=='floor')).sort((a,b)=>Math.hypot(s.x-a.userData.use.x,s.z-a.userData.use.z)-Math.hypot(s.x-b.userData.use.x,s.z-b.userData.use.z))[0]}function nearUse(){use(nearest())}

  function syncStation(dt=0){
    const dirs=[[3,0],[0,-3],[-3,0],[0,3]],p=dirs[s.mirror];
    setBeam(beams[0],[[-3,1.05,0],[0,1.05,0],[p[0],1.05,p[1]]]);
    reflector.rotation.y=s.mirror*Math.PI/2+.78;
    doors.forEach((d,i)=>{d.position.y=dt?THREE.MathUtils.lerp(d.position.y,s.solved[i]?2.7:0,Math.min(1,dt*5)):s.solved[i]?2.7:0});
    roomLights.forEach((l,i)=>{l.color.set(s.solved[i]?0x92efc7:0x73bad0);l.intensity=s.solved[i]?12:7});
    if(s.battery==='held'){if(battery.parent!==camera)camera.add(battery);battery.position.set(.43,-.48,-.78);battery.rotation.y=.2;battery.scale.setScalar(.45)}
    else {if(battery.parent!==scene)scene.add(battery);battery.rotation.y=0;battery.position.set(s.battery==='installed'?2:-2,s.battery==='installed'?.2:0,s.battery==='installed'?-12:-8);battery.scale.setScalar(s.battery==='installed'?.55:1)}
    const target=nearest(),u=target?.userData.use,close=u&&Math.hypot(s.x-u.x,s.z-u.z)<2.2;
    const names={mirror:'转动光路',battery:'拿起备用电池',socket:s.battery==='held'?'装入备用电池':'检查能源插槽',panel:'接通信号'};
    hud.textContent=s.won?'通路已恢复 · 列车还在等你':close?'E · '+names[u.type]:'通路 '+s.solved.filter(Boolean).length+'/3 · '+(s.battery==='held'?'电池搬运中':'靠近设备按 E');
  }
  syncStation();
  batchStatic(scene,scene.children.filter(o=>!uses.includes(o)&&!doors.includes(o)&&!beams.includes(o)&&o!==reflector));
  return {...world,getState:()=>s,getStatus:()=>({goal:s.won?'你已恢复车站的最后一条通路':!s.solved[0]?'转动光路，照亮北侧接收器':!s.solved[1]?'搬运备用电池，接通第二间的能源插槽':!s.solved[2]?'按墙上顺序接通信号':'穿过最后一道门，离开车站',message:s.won?'广播：这不是一座空站。谢谢你把通往回家的门重新打开。':'拖动画面转头，WASD 移动。设备必须走近才能操作。',stats:['通路 '+s.solved.filter(Boolean).length+' / 3','电池 '+({floor:'未取得',held:'搬运中',installed:'已接通'}[s.battery]),'信号 '+s.order.length+' / 3'],actions:[action('互动 E',nearUse,s.won),action('向左转头',()=>s.yaw+=.3),action('向右转头',()=>s.yaw-=.3)]}),tick(dt){time+=dt;if(!s.won){move(dt);if(input.pressed.has('KeyE'))nearUse();clickUse(use)}camera.position.set(s.x,1.65+(input.x||input.y?Math.sin(time*9)*.018:0),s.z);camera.rotation.set(s.pitch,s.yaw,0,'YXZ');syncStation(dt);if(!s.won&&s.z<-25&&s.solved.every(Boolean)){s.won=true;sfx('success');notify('你走出了封闭车站。最后一班列车的灯，亮了。')}},draw:world.draw};
 }
 tiles(0,-2,5,9);for(let i=-4;i<=4;i++){occluders.push(put(scene,art.wall,-7.5,0,i*3-2,3,Math.PI/2),put(scene,art.wall,7.5,0,i*3-2,3,Math.PI/2))}for(let i=-2;i<=2;i++){occluders.push(put(scene,art.wall,i*3,0,11.5,3),put(scene,art.wall,i*3,0,-15.5,3))}for(const [x,z] of [[-3,4],[2,0],[-1,-5],[4,-9]]){const cover=put(scene,art['container-tall'],x,0,z,2.7);cover.userData.cover={x,z,r:.85};occluders.push(cover)}
 for(let i=0;i<8;i++){const x=i%2?-4.8:4.8,z=5-Math.floor(i/2)*5,o=put(scene,art['computer-wide'],x,.4,z,1.7,Math.PI);o.userData.target=i;const l=light(scene,x,1.5,z,0x4cd6e1,5,4);targets.push({object:o,x,z,l,clock:2+i*.21,warn:false,dead:s.dead.includes(i)});o.visible=!s.dead.includes(i)}for(let i=0;i<5;i++){light(scene,-6,2.4,7-i*5,0xffb16b,9,8);light(scene,6,2.4,7-i*5,0x6dc8e2,9,8)}sign(scene,'SIGNAL / TRAINING',0,2.3,-15.2,4);
 batchStatic(scene,scene.children.filter(o=>!targets.some(t=>t.object===o)));
 const raycaster=new THREE.Raycaster(),muzzle=light(scene,0,1.6,0,0xffbb66,0,4),weapon=copy(await model('blaster','blaster-a'));weapon.scale.setScalar(.75);weapon.position.set(.24,-.22,-.6);weapon.rotation.y=Math.PI;camera.add(weapon);scene.add(camera);const damageOverlay=document.createElement('div');damageOverlay.style.cssText='position:absolute;inset:0;pointer-events:none;background:radial-gradient(ellipse,transparent 35%,#af3434a0);opacity:0';host.append(damageOverlay);let hurt=0,hitmark=0;const hitMarker=document.createElement('div');hitMarker.className='hit-marker';hitMarker.textContent='×';hitMarker.hidden=true;host.append(hitMarker);const stationDispose=world.dispose;world.dispose=()=>{damageOverlay.remove();hitMarker.remove();stationDispose()};
 function shoot(){if(shootCD>0||s.reload>0||s.hp<=0||s.won)return;if(s.ammo<=0){reload();return}s.ammo--;s.shots++;shootCD=.22;flash=.055;sfx('shot');raycaster.setFromCamera(new THREE.Vector2(0,0),camera);const hits=raycaster.intersectObjects([...targets.filter(t=>!t.dead).map(t=>t.object),...occluders],true);if(hits.length){let o=hits[0].object;while(o&&o.userData.target===undefined)o=o.parent;if(o){const i=o.userData.target,t=targets[i];t.dead=true;t.object.visible=false;t.l.intensity=0;s.dead.push(i);s.hits++;hitmark=.3;sfx('pickup')}}if(s.dead.length===8){s.won=true;sfx('success');notify('全部靶机已停机。你完成了这一段训练。')}}
 function reload(){if(s.reload===0&&s.ammo<12){s.reload=1.25;sfx('reload')}}
 return {...world,getState:()=>s,getStatus:()=>({goal:s.won?'八台无人靶机全部停机':'移动、利用掩体并击中八台无人靶机',message:s.hp<=0?'训练中断。重新开始后，可以先利用货箱挡住靶机视线。':s.won?'训练完成。命中率 '+Math.round(s.hits/Math.max(1,s.shots)*100)+'%。':s.reload>0?'正在换弹……':s.shots===0?'先观察场地、移动并试着瞄准。第一次开火之后，无人靶机会启动。':'准星对准靶机，点击或按 J 开火。红灯表示靶机即将攻击。',stats:['生命 '+Math.ceil(s.hp),'弹药 '+s.ammo+'/12','停机 '+s.dead.length+'/8','射击 '+s.shots],actions:[action('开火 J',shoot,s.hp<=0||s.won),action('换弹 R',reload,s.reload>0||s.won||s.hp<=0||s.ammo===12),action('左转',()=>s.yaw+=.3),action('右转',()=>s.yaw-=.3)]}),tick(dt){time+=dt;hitmark=Math.max(0,hitmark-dt);hitMarker.hidden=hitmark<=0;hud.textContent='生命 '+Math.ceil(s.hp)+' · '+(s.reload>0?'正在换弹':'弹药 '+s.ammo+'/12')+' · 靶机 '+s.dead.length+'/8';hurt=Math.max(0,hurt-dt);damageOverlay.style.opacity=String(hurt*2);shootCD=Math.max(0,shootCD-dt);flash=Math.max(0,flash-dt);if(s.reload>0){s.reload=Math.max(0,s.reload-dt);if(s.reload===0)s.ammo=12}weapon.position.set(.24,-.22+(input.x||input.y?Math.sin(time*9)*.008:0),-.6+(flash>0?.05:0));weapon.rotation.z=s.reload>0?Math.sin(s.reload/1.25*Math.PI)*-.55:0;if(s.hp<=0||s.won)return;move(dt);camera.position.set(s.x,1.65,s.z);camera.rotation.set(s.pitch,s.yaw,0,'YXZ');if(input.keys.has('KeyJ')||input.pointers.length)shoot();if(input.pressed.has('KeyR'))reload();muzzle.position.copy(camera.position);muzzle.intensity=flash>0?8:0;for(const t of targets.filter(t=>!t.dead)){if(s.shots>0)t.clock-=dt;t.warn=s.shots>0&&t.clock<1.1;t.l.color.set(t.warn?0xff5344:0x4cd6e1);t.l.intensity=t.warn?10:5;if(t.clock<=0){const start=new THREE.Vector3(t.x,1.55,t.z),dest=new THREE.Vector3(s.x,1.65,s.z),dist=start.distanceTo(dest);raycaster.set(start,dest.clone().sub(start).normalize());const block=raycaster.intersectObjects(occluders,true)[0];if(dist<10&&(!block||block.distance>dist)){s.hp=Math.max(0,s.hp-5);hurt=.45;sfx('hurt')}t.clock=3.6}t.object.position.y=.4+Math.sin(time*2+t.x)*.045}},draw:world.draw};
 function move(dt){if(input.x||input.y){stepClock+=dt;if(stepClock>.45){stepClock=0;sfx('step')}}s.yaw-=input.look.x*.005;s.pitch=clamp(s.pitch-input.look.y*.004,-.9,.9);const norm=Math.hypot(input.x,input.y)||1,speed=3.5,x=s.x+(Math.cos(s.yaw)*input.x+Math.sin(s.yaw)*input.y)/norm*speed*dt,z=s.z+(-Math.sin(s.yaw)*input.x+Math.cos(s.yaw)*input.y)/norm*speed*dt;if(isRange){const blocked=occluders.some(o=>o.userData.cover&&Math.abs(x-o.userData.cover.x)<1.15&&Math.abs(z-o.userData.cover.z)<1.15);if(!blocked){s.x=clamp(x,-6.7,6.7);s.z=clamp(z,-14.7,10.5)}}else{let zz=clamp(z,-27,4);for(let i=0;i<3;i++){const dz=-4.5-i*10;if((s.z>dz&&zz<dz+.2)||(s.z<dz&&zz>dz-.2)){if(!s.solved[i]||Math.abs(x)>.8)zz=s.z}}const blocked=(xx,zz)=>uses.some(o=>{const u=o.userData.use;if(u.type==='panel'||u.type==='battery'&&s.battery!=='floor')return false;return Math.hypot(xx-u.x,zz-u.z)<(u.type==='mirror'?.74:u.type==='socket'?.65:.38)});if(!blocked(x,s.z))s.x=clamp(x,-3.8,3.8);if(!blocked(s.x,zz))s.z=zz}}
 function clickUse(use){if(!input.pointers.length)return;const p=input.pointers.at(-1),caster=new THREE.Raycaster();caster.setFromCamera(new THREE.Vector2(p.x/1120*2-1,-p.y/630*2+1),camera);const hits=caster.intersectObjects(uses.filter(o=>o.visible&&!(o.userData.use.type==='battery'&&s.battery!=='floor')),true);if(hits.length){let o=hits[0].object;while(o&&!o.userData.use)o=o.parent;use(o)}}
}

export {createLandscape} from './showcase-landscape.js';
