import {W,H,clamp,images,canvasSurface,glow} from './showcase-core.js';
import {pointerPosition} from './showcase-precision-kit.js';
import {sceneHeading,completion} from './showcase-observation-kit.js?v=20261004-2';
import {gesturePanel} from './showcase-gesture-kit.js?v=20261004-3';

export const SWING_LEVELS=[
 {name:'垂直落灯',anchors:[{x:560,y:105}],start:{x:560,y:265},target:{x:560,y:452,width:146}},
 {name:'双绳侧摆',anchors:[{x:450,y:108},{x:650,y:108}],start:{x:550,y:258},target:{x:735,y:452,width:166}}
];
const G=430,R=25,finite=(v,f)=>Number.isFinite(v)?v:f;
export function swingFresh(level=0){const def=SWING_LEVELS[level];return {version:1,level,p:{...def.start,vx:0,vy:0},ropes:def.anchors.map(a=>({cut:false,length:Math.hypot(def.start.x-a.x,def.start.y-a.y)})),phase:'hanging',running:true,slow:true,preview:true,time:0,cuts:0,retries:0,completed:level,won:false}}
export function swingRestore(raw){const level=Number.isInteger(raw?.level)?clamp(raw.level,0,1):0,s=swingFresh(level);if(raw?.version!==1)return s;
 if(raw.p&&['x','y','vx','vy'].every(k=>Number.isFinite(raw.p[k])))s.p={x:clamp(raw.p.x,-150,W+150),y:clamp(raw.p.y,0,H+150),vx:clamp(raw.p.vx,-1000,1000),vy:clamp(raw.p.vy,-1000,1000)};
 if(Array.isArray(raw.ropes)&&raw.ropes.length===s.ropes.length)s.ropes=s.ropes.map((r,i)=>({...r,cut:raw.ropes[i]?.cut===true}));
 s.phase=['hanging','flying','miss','cleared','won'].includes(raw.phase)?raw.phase:'hanging';s.running=raw.running!==false;s.slow=raw.slow!==false;s.preview=raw.preview!==false;s.time=clamp(finite(raw.time,0),0,86400);s.cuts=Number.isInteger(raw.cuts)?clamp(raw.cuts,0,10000):0;s.retries=Number.isInteger(raw.retries)?clamp(raw.retries,0,10000):0;s.completed=Number.isInteger(raw.completed)?clamp(raw.completed,0,2):level;
 if(s.ropes.every(r=>r.cut)&&s.phase==='hanging')s.phase='flying';if(s.ropes.some(r=>!r.cut)&&s.phase==='flying')s.phase='hanging';
 const t=SWING_LEVELS[level].target,caught=Math.abs(s.p.x-t.x)<=t.width/2-R&&Math.abs(s.p.y-(t.y-R))<1;
 if(['cleared','won'].includes(s.phase)&&(!caught||s.ropes.some(r=>!r.cut)))s.phase=s.ropes.every(r=>r.cut)?'flying':'hanging';
 if(s.phase==='won'&&level!==1)s.phase='cleared';s.won=s.phase==='won';if(s.phase==='cleared')s.completed=1;if(s.won)s.completed=2;return s;
}
export function swingCut(s,i){if(!['hanging','flying'].includes(s.phase)||!Number.isInteger(i)||i<0||i>=s.ropes.length||s.ropes[i].cut)return false;s.ropes[i].cut=true;s.cuts++;if(s.ropes.every(r=>r.cut))s.phase='flying';return true}
export function swingProjection(s){const t=SWING_LEVELS[s.level].target,dy=t.y-R-s.p.y,discriminant=s.p.vy*s.p.vy+2*G*dy;if(discriminant<0)return null;const time=(-s.p.vy+Math.sqrt(discriminant))/G;if(time<=0)return null;const x=s.p.x+s.p.vx*time;return {x,time,within:Math.abs(x-t.x)<=t.width/2-R}}
export function swingStep(s,dt){if(!['hanging','flying'].includes(s.phase))return null;dt=Number.isFinite(dt)?clamp(dt,0,.25):0;if(!dt)return null;const def=SWING_LEVELS[s.level],steps=Math.ceil(dt*240),h=dt/steps;
 for(let step=0;step<steps;step++){const old={x:s.p.x,y:s.p.y};s.p.vy+=G*h;s.p.x+=s.p.vx*h;s.p.y+=s.p.vy*h;
  for(let pass=0;pass<4;pass++)s.ropes.forEach((r,i)=>{if(r.cut)return;const a=def.anchors[i],dx=s.p.x-a.x,dy=s.p.y-a.y,d=Math.hypot(dx,dy);if(d<.001)return;s.p.x=a.x+dx/d*r.length;s.p.y=a.y+dy/d*r.length});
  s.ropes.forEach((r,i)=>{if(r.cut)return;const a=def.anchors[i],dx=(s.p.x-a.x)/r.length,dy=(s.p.y-a.y)/r.length,radial=s.p.vx*dx+s.p.vy*dy;s.p.vx=(s.p.vx-radial*dx)*Math.exp(-.02*h);s.p.vy=(s.p.vy-radial*dy)*Math.exp(-.02*h)});
  s.time+=h;const t=def.target,line=t.y-R;
  if(s.phase==='flying'&&s.p.vy>0&&old.y<=line&&s.p.y>=line){const fraction=(line-old.y)/(s.p.y-old.y),x=old.x+(s.p.x-old.x)*fraction;if(Math.abs(x-t.x)<=t.width/2-R){s.p={x,y:line,vx:0,vy:0};s.phase=s.level===1?'won':'cleared';s.won=s.phase==='won';s.completed=s.level+1;return 'caught'}}
  if(s.p.y>H+60||s.p.x< -100||s.p.x>W+100){s.phase='miss';return 'miss'}
 }return null;
}
const distanceToSegment=(p,a,b)=>{const dx=b.x-a.x,dy=b.y-a.y,t=clamp(((p.x-a.x)*dx+(p.y-a.y)*dy)/(dx*dx+dy*dy||1),0,1);return Math.hypot(p.x-a.x-t*dx,p.y-a.y-t*dy)};
export function swingIntersect(a,b,c,d){const cross=(p,q,r)=>(q.x-p.x)*(r.y-p.y)-(q.y-p.y)*(r.x-p.x);const ab1=cross(a,b,c),ab2=cross(a,b,d),cd1=cross(c,d,a),cd2=cross(c,d,b);return ab1*ab2<=0&&cd1*cd2<=0&&Math.max(Math.min(a.x,b.x),Math.min(c.x,d.x))<=Math.min(Math.max(a.x,b.x),Math.max(c.x,d.x))&&Math.max(Math.min(a.y,b.y),Math.min(c.y,d.y))<=Math.min(Math.max(a.y,b.y),Math.max(c.y,d.y))}
export function swingRetry(s){const fresh=swingFresh(s.level);fresh.retries=s.retries+1;fresh.slow=s.slow;fresh.preview=s.preview;return fresh}
export function swingNext(s){return s.phase==='cleared'?swingFresh(1):s}

export async function createSwing({host,input,saved,sfx=()=>{}}){
 const art=await images(['atelier','lantern','cradle'],'assets/game-forms/swing/'),{element,ctx}=canvasSurface(host);element.style.touchAction='none';element.setAttribute('aria-label','风铃工坊：点绳索或划过绳索切断，观察灯球摆动和落点；下方按钮可定格与步进');
 let s=swingRestore(saved),active=false,drag=null,stroke=null,strokeLife=0,message='第一幕：点中央绳索或按切绳 1，让灯球落入下方软垫托座。';
 if(s.won)message='两幕灯球都已送达，完成结果已保留。';else if(s.phase==='cleared')message='第一幕已完成，可进入双绳侧摆。';else if(s.level||s.cuts)message='已恢复绳索、位置与速度，可以继续观察摆动或切绳。';
 const ui=gesturePanel(host,'swing',`<div class="gesture-toolbar"><span class="readout" aria-live="polite"></span><button type="button" class="motion">定格观察</button><button type="button" class="step">推进一点</button><button type="button" class="slow">慢放：开</button><button type="button" class="preview">落点预览：开</button></div><div class="cut-buttons gesture-toolbar" style="margin-top:8px"><button type="button" class="cut primary" data-rope="0">切绳 1</button><button type="button" class="cut primary" data-rope="1">切绳 2</button><button type="button" class="retry">重试本幕</button><button type="button" class="next primary">下一幕</button></div><p class="gesture-note">点 / 划过绳索切断；1 / 2 键切绳，E 定格，方向键右推进 0.1 秒。第二幕先切左绳，再在右摆接近顶点时切右绳；虚线是此刻全部释放后的实际预测。</p>`);
 const motion=ui.panel.querySelector('.motion'),step=ui.panel.querySelector('.step'),slow=ui.panel.querySelector('.slow'),preview=ui.panel.querySelector('.preview'),retry=ui.panel.querySelector('.retry'),next=ui.panel.querySelector('.next'),readout=ui.panel.querySelector('.readout'),cuts=[...ui.panel.querySelectorAll('[data-rope]')];
 function sync(){const play=active&&['hanging','flying'].includes(s.phase);motion.disabled=!play;motion.textContent=s.running?'定格观察':'继续摆动';motion.setAttribute('aria-pressed',String(!s.running));step.disabled=!play||s.running;slow.disabled=preview.disabled=!active;slow.textContent='慢放：'+(s.slow?'开':'关');slow.setAttribute('aria-pressed',String(s.slow));preview.textContent='落点预览：'+(s.preview?'开':'关');preview.setAttribute('aria-pressed',String(s.preview));cuts.forEach((b,i)=>{b.hidden=i>=s.ropes.length;b.disabled=!play||s.ropes[i]?.cut;b.textContent=s.ropes[i]?.cut?'绳 '+(i+1)+' 已切断':'切绳 '+(i+1)});retry.disabled=!active;next.hidden=s.phase!=='cleared';next.disabled=!active;const p=swingProjection(s);readout.textContent=`${s.level+1}/2 · ${SWING_LEVELS[s.level].name} · `+(['cleared','won'].includes(s.phase)?'灯球已送达':s.phase==='miss'?'落点偏离，可重试':p&&s.preview?(p.within?'落点可达':'落点偏离')+' · '+Math.round(p.x):s.phase==='flying'?'灯球下落中':'观察摆动时机')}
 function cut(i){if(active&&swingCut(s,i)){strokeLife=.3;message=s.phase==='flying'?'绳索全部释放，灯球保留此刻的速度下落。':'一根绳已释放，灯球绕剩余挂点摆动。';sfx('pickup');sync()}}
 function result(r){if(r==='caught'){message=s.won?'两幕灯球都已送到托座。':'灯球稳稳落入托座，可以进入双绳侧摆。';sfx('success')}else if(r==='miss'){message='灯球越过了托座。重试本幕，利用定格与预览调整释放时机。';sfx('error')}if(r)sync()}
 cuts.forEach((b,i)=>b.onclick=()=>cut(i));motion.onclick=()=>{if(active&&['hanging','flying'].includes(s.phase)){s.running=!s.running;message=s.running?'灯球继续按当前位置和速度运动。':'物理时间已定格；可推进一点或切绳观察落点。';sync()}};
 step.onclick=()=>{if(active&&!s.running){result(swingStep(s,.1));sync()}};slow.onclick=()=>{if(active){s.slow=!s.slow;sync()}};preview.onclick=()=>{if(active){s.preview=!s.preview;sync()}};retry.onclick=()=>{if(active){s=swingRetry(s);drag=null;message='当前一幕已复位，可以重新安排切绳时机。';sync()}};next.onclick=()=>{if(active&&s.phase==='cleared'){s=swingNext(s);message='先切左绳，灯球会绕右挂点摆动。接近右侧顶点时释放，让它落入右侧托座。';sync()}};
 const attach=()=>({x:s.p.x,y:s.p.y-42});
 function down(e){if(!active||!['hanging','flying'].includes(s.phase))return;const p=pointerPosition(element,e);drag={last:p,start:p,moved:false,id:e.pointerId};element.setPointerCapture(e.pointerId)}
 function move(e){if(!active||!drag||e.pointerId!==drag.id)return;const p=pointerPosition(element,e);if(Math.hypot(p.x-drag.start.x,p.y-drag.start.y)>6)drag.moved=true;if(drag.moved){const end=attach();SWING_LEVELS[s.level].anchors.forEach((a,i)=>{if(!s.ropes[i].cut&&swingIntersect(drag.last,p,a,end))cut(i)});stroke={a:drag.last,b:p};strokeLife=.22}drag.last=p}
 function up(e){if(!drag||e.pointerId!==drag.id)return;if(active&&!drag.moved){const p=pointerPosition(element,e),end=attach(),anchors=SWING_LEVELS[s.level].anchors;let closest=-1,best=26;anchors.forEach((a,i)=>{if(s.ropes[i].cut)return;const d=distanceToSegment(p,a,end);if(d<best){closest=i;best=d}});if(closest>=0)cut(closest);else{message='点绳索的中段切断；也可使用下方对应的切绳按钮。';sync()}}drag=null}
 const cancel=()=>drag=null;const key=e=>{if(e.code==='Digit1'||e.code==='Digit2'){e.preventDefault();cut(Number(e.code.slice(-1))-1)}};element.addEventListener('pointerdown',down);element.addEventListener('pointermove',move);element.addEventListener('pointerup',up);element.addEventListener('pointercancel',cancel);element.addEventListener('keydown',key);
 function tick(dt){if(!active)return;dt=Number.isFinite(dt)?Math.max(0,dt):0;if(!dt)return;if(input.pressed.has('Digit1'))cut(0);if(input.pressed.has('Digit2'))cut(1);if(input.pressed.has('KeyE'))motion.click();if(input.pressed.has('ArrowRight')&&!s.running)step.click();if(s.running)result(swingStep(s,dt*(s.slow?.55:1)));strokeLife=Math.max(0,strokeLife-dt);sync()}
 function draw(){ctx.drawImage(art.atelier,0,0,W,H);const def=SWING_LEVELS[s.level],t=def.target,end=attach();
 ctx.save();ctx.fillStyle='#4b57411d';ctx.beginPath();ctx.ellipse(t.x,530,100,12,0,0,Math.PI*2);ctx.fill();const cw=224,ch=cw*art.cradle.height/art.cradle.width;ctx.drawImage(art.cradle,t.x-cw/2,t.y-39,cw,ch);
 ctx.strokeStyle='#b6d7b6';ctx.lineWidth=2;ctx.setLineDash([6,5]);ctx.beginPath();ctx.ellipse(t.x,t.y,t.width/2,11,0,0,Math.PI*2);ctx.stroke();ctx.setLineDash([]);
 def.anchors.forEach((a,i)=>{ctx.fillStyle='#c5a75d';ctx.strokeStyle='#6f5831';ctx.lineWidth=3;ctx.beginPath();ctx.arc(a.x,a.y,9,0,Math.PI*2);ctx.fill();ctx.stroke();ctx.fillStyle='#f9f1d4';ctx.textAlign='center';ctx.font='600 17px sans-serif';ctx.fillText(String(i+1),a.x,a.y-18);if(s.ropes[i].cut)return;ctx.lineCap='round';ctx.strokeStyle='#6c5127';ctx.lineWidth=5;ctx.beginPath();ctx.moveTo(a.x,a.y);ctx.lineTo(end.x,end.y);ctx.stroke();ctx.strokeStyle='#e1c080';ctx.lineWidth=2;ctx.stroke()});
 if(s.preview&&['hanging','flying'].includes(s.phase)){const pred=swingProjection(s);if(pred){ctx.fillStyle=pred.within?'#286758aa':'#977344aa';for(let i=1;i<=14;i++){const time=pred.time*i/14,x=s.p.x+s.p.vx*time,y=s.p.y+s.p.vy*time+.5*G*time*time;ctx.beginPath();ctx.arc(x,y,2.1,0,Math.PI*2);ctx.fill()}ctx.strokeStyle=pred.within?'#377d64':'#9b7440';ctx.lineWidth=2;ctx.beginPath();ctx.arc(pred.x,t.y-R,10,0,Math.PI*2);ctx.stroke();ctx.textAlign='center';ctx.font='13px "Microsoft YaHei",sans-serif';ctx.fillText(pred.within?'释放可达':'此刻释放会偏离',clamp(pred.x,160,960),t.y-45)}}
 glow(ctx,s.p.x,s.p.y,47,'#ffc75d50');const lw=118,lh=118;ctx.drawImage(art.lantern,s.p.x-lw/2,s.p.y-lh*.43,lw,lh);
 if(stroke&&strokeLife>0){ctx.strokeStyle='#f4f3d4';ctx.lineWidth=3;ctx.beginPath();ctx.moveTo(stroke.a.x,stroke.a.y);ctx.lineTo(stroke.b.x,stroke.b.y);ctx.stroke()}
 ctx.restore();sceneHeading(ctx,'风铃工坊',`${s.level+1}/2 · ${def.name}     切绳 · 摆荡 · 重力落点`);
 ctx.save();ctx.fillStyle='#f5efdbdf';ctx.beginPath();ctx.roundRect(363,565,394,36,8);ctx.fill();ctx.textAlign='center';ctx.font='14px "Microsoft YaHei",sans-serif';ctx.fillStyle='#37574b';ctx.fillText(!s.running?'物理时间已定格 · 可推进一点观察':s.level===0?'切断绳索，让光落进下方托座':'先切左绳 · 右摆近顶点再切右绳',560,588);ctx.restore();if(s.phase==='cleared')completion(ctx,'第一盏灯已安放','点击下方「下一幕」，体验双绳切断与侧摆');if(s.won)completion(ctx,'工坊重新亮起',`两幕灯球已送达 · 当前幕切绳 ${s.cuts} 次 · 重试 ${s.retries} 次`);if(s.phase==='miss')completion(ctx,'这次落点偏离','点击「重试本幕」，可以用定格与落点预览调整时机')}
 sync();return{tick,draw,onStart(){active=true;sync()},setActive(v){active=v;if(!v)cancel();sync()},getState(){return structuredClone(s)},getStatus(){return{goal:s.won?'两幕灯球都已安放':'把灯球送进软垫托座',message,stats:[`场景 ${s.level+1}/2`,`已切 ${s.cuts} 根`,`重试 ${s.retries} 次`],actions:[]}},dispose(){element.removeEventListener('pointerdown',down);element.removeEventListener('pointermove',move);element.removeEventListener('pointerup',up);element.removeEventListener('pointercancel',cancel);element.removeEventListener('keydown',key);ui.dispose()}};
}
