const art='assets/showcase/';
const item=(id,title,subtitle,family,view,reference,source,cover,description,scope,controls)=>({id,title,subtitle,family,view,reference,source,cover,description,scope,controls});
export const newDirections=[
 item('afterdark','停电之后','2.5D 都市悬疑','故事','横版','INSIDE','https://playdead.com/games/inside/',art+'night.webp','穿过被封锁的维修站。灯光、空间和广播一起揭开这一夜的秘密。','三段连续场景、专用道具美术、巡逻锁定预兆、货箱藏身与两种结局。','A/D 或左右移动 · S 蹲下藏身 · 空格跳跃 · E 互动'),
 item('hunter','灰烬猎手','等距暗黑动作','动作','俯视','Hades','https://www.supergiantgames.com/games/hades/',art+'arena.webp','读懂敌人的攻击预兆，用移动、闪避和能力组合走出熔炉。','三波十二名守卫、破盾、远程锁定、闪避残影、统领两阶段与能力选择。','WASD / 方向键移动 · J / 点击攻击 · 空格闪避'),
 item('station','封闭车站','第一人称空间解谜','空间','第一人称','Portal 2','https://www.thinkwithportals.com/about.php',art+'card-4.webp','走进真实立体空间，重新接通信号，让封闭车站的最后一道门打开。','三间相连车站机房，光束转向、持物搬运、设备碰撞、信号排序与终点。','WASD 移动 · 拖动画面转头 · E 互动'),
 item('ledger','黑市账本','插画卡牌策略','策略','牌桌','Balatro','https://www.playbalatro.com/',art+'card-0.webp','在有限出牌次数里组合货物、路线和加成，把这一趟生意做下去。','五轮委托、货物/路线/支援组合、三条成长路线、进度与交易回顾。','点选最多三张牌 · 出牌 / 弃牌 · 选择升级'),
 item('order','晶格秩序','抽象几何益智','策略','棋盘','Tetris','https://tetris.com/about',art+'platform2d/gem_blue.png','用旋转和排列整理不断落下的晶格，在越来越快的节奏里保持秩序。','七种方块、旋转与碰撞、落点预览、消行、加速、最高分。','左右移动 · 上旋转 · 下加速 · 空格落底'),
 item('wonder','云端邮路','明亮卡通平台','动作','横版','Super Mario Bros. Wonder','https://www.nintendo.com/us/store/products/super-mario-bros-wonder-switch/',art+'platform2d/background_color_hills.png','跳过山谷，拿到三枚邮票，把信送到云端邮局。','连续平台、移动平台、弹簧、敌人、检查点与终点。','A/D 或左右移动 · 空格 / W 跳跃'),
 item('breach','潮汐突围','横版跑射','动作','横版','魂斗罗 / Contra','https://www.konami.com/games/contra/og/eu/en/','assets/game-forms/breach/harbor.webp','在港区边移动边射击，用跳跃和蹲下避开脉冲，击退出口守卫。','连续滚屏、方向射击、蹲下、平台、散射模块、检查点与出口守卫。','A/D 或左右移动 · 空格跳跃 · S 蹲下 · J 连射 · ↑ / W 向上瞄准'),
 item('brawler','夜港清场','街道清版格斗','动作','横版','Final Fight / 快打旋风','https://us-store.captown.capcom.com/products/1340551-us','assets/game-forms/brawler/street.webp','在带纵深的街道上走位，用直拳、勾拳、踢击与抓取击退围来的对手。','三段街道、七名对手、三段连击、跳击、闪避、抓取投掷与重拳预兆。','WASD / 方向键走位 · J 连击 · 空格跳跃 · C 闪避 · E 抓取'),
 item('skyline','群岛航线','纵向飞行射击','动作','纵向','1942','https://news.capcomusa.com/2021/05/25/capcom-arcade-stadium-is-available-now-for-playstation-4-xbox-one-nintendo-switch-and-steam/','assets/game-forms/skyline/ocean.webp','穿过群岛航路，躲开敌机编队与扇形弹道，取得补给并击退大型守关机。','竖向滚动航路、八轮编队、倾斜驾驶、双路/三路火力、冲击波、补给与守关机。','WASD / 方向键或拖动驾驶 · 默认自动射击 · 空格 / C 冲击波'),
 item('coast','海岸疾驰','真实三维竞速','空间','车后 / 车头','Out Run','https://segaages.sega.com/project/out-run/index.htm','assets/game-forms/coast/raceCarOrange.glb','沿海岸弯道驾驶，借助加速能量超越其他车辆，在车后与车头镜头间切换。','1.80公里弯道、真实三维模型、四辆同行车、超车、碰撞、离路减速、赛段记录与双镜头。','W / ↑ 加速 · S / ↓ 刹车 · A/D 转向 · 空格加速推进 · E 切换镜头'),
 item('duel','钟楼试炼','固定竞技场对战格斗','动作','双人侧面','Street Fighter / 街头霸王','https://www.streetfighter.com/6/','assets/game-forms/duel/scene.webp','在钟楼竞技场控制双方距离，以出拳、踢击、防守和跳跃换边进行三局两胜的试炼。','两个原创成年角色、十六种动作姿态、攻击预兆、距离判定、格挡积能、击停、回合与重赛。','A/D 或左右移动 · 空格跳跃 · J 出拳 · E 踢击 · C 防守 · R 满能量破阵'),
 item('maze','霓虹回路','单屏迷宫追逐','动作','固定俯视棋盘','Pac-Man / 吃豆人','https://www.pacman.com/','assets/game-forms/maze/right.webp','在连通迷宫里转弯、收集信号，避开追踪器，获得强化后发起反追。','固定连通地图、转弯缓冲、路线规划、两种追踪器、强化反追、停滞脉冲与保留信号的续玩。','方向键 / WASD 移动 · J / 空格 脉冲 · 点走廊规划路线'),
 item('rhythm','拍点夜航','音乐节奏轨道','动作','透视音符轨道','Taiko no Tatsujin / 太鼓达人','https://www.bandainamcoent.com/games/taiko-no-tatsujin-drum-session','assets/game-forms/rhythm/scene.webp','听原创电子短曲，在三条轨道上打出左拍、右拍与重拍，感受声画同步与连击反馈。','108 BPM 原创短曲、八十个节拍、同一声音时钟、精准/良好/漏拍判定、触屏键、校准与成绩。','D 左拍 · J 右拍 · 空格重拍 · 或点三个打击键 · 开始即开启音乐'),
 item('command','铜沙指挥部','多单位即时战略','策略','俯视大地图','StarCraft / 星际争霸','https://starcraft2.blizzard.com/','assets/game-forms/command/scene.webp','框选多个单位，在可移动的大地图上调度编队、招募与战斗，接通三座信标。','原创战场、框选、编队移动、侦察车/飞行器、矿线收入、招募、守军与哨塔、占领和小地图。','框选 / 点击单位 · 点地面移动 / 点守军进攻 · WASD 移动地图 · 空格全选 · E 招募'),
 item('bastion','暮林守望','固定路线塔防','策略','固定通路','Kingdom Rush / 王国保卫战','https://www.kingdomrush.com/','assets/game-forms/bastion/scene.webp','在石路两侧部署连弩、霜塔和迫击，观察敌群沿通路行进，调整射程与火力组合。','五波敌群、八处部署点、三种塔、实体投射物、减速与范围伤害、升级回收、城门生命与波前重试。','先选择塔，再点部署点 · 点击已有塔查看范围 · R 升级 · 空格 / E 开始下一波'),
 item('tactics','星台棋阵','等距回合战棋','策略','等距棋盘','Final Fantasy Tactics / 最终幻想战略版','https://www.square-enix.com/','assets/game-forms/tactics/scene.webp','轮流操作近卫、弩手与医师，在等距棋盘上走格、选择攻击和治疗，预览敌方行动。','八乘八棋阵、三名队员、四名对手、阻挡与射线、移动范围、远近攻击、治疗、防守、敌方回合与回合重试。','点队员选择 · 点蓝格移动 / 点敌人攻击 · 医师可选治疗 · C 防守 · E / 空格结束回合'),
 item('sports','黄昏球场','整场俯视体育竞技','动作','球场俯视','小场足球 / 球队竞技','forms.html#forms','assets/game-forms/sports/scene.webp','控制青队的三名场上队员，传球、跑位、瞄准球门空隙射门，与主动追球的红队进行短场比赛。','双方三名场上队员与门将、真实球体、传球接球、抢断、扑救、三球或九十秒比赛、刷新续赛。','方向键 / WASD 移动 · R 冲刺 · E 传球 · 空格射门 · C 切人 · 点队友传球 / 点球门瞄准'),
 item('stealth','夜庭潜行','俯视隐蔽行动','故事','视野与遮挡','巡逻潜行 / 隐蔽路线','forms.html#forms','assets/game-forms/stealth/scene.webp','穿过夜间庭院，绕开巡逻视野，读取三处终端，再从东侧出口安全离场。','四组实体建筑、三名巡逻者、被建筑截断的视野、蹲行与脚步声、路线规划、声响引诱、终端检查点与重试。','方向键 / WASD 移动 · 点通路绕行 · C 蹲行 / 快走 · E 读取 / 离场 · R 向鼠标处投掷声响'),
 item('pinball','星轨弹球','实体机台物理弹球','动作','固定机台','物理弹球 / Pinball','forms.html#forms','assets/game-forms/pinball/scene.webp','在星图机台上发射钢球，用左右挡板接住回落，撞击弹击器并点亮四颗星灯。','连续重力与反弹、转动挡板表面速度、弹击器、四星奖励、蓄力开球、有限推台、三颗球与最高分。','A/D 或左右键控制挡板 · 按住空格蓄力 / 松开发球 · E 推台 · 按住机台左右半区操作'),
 item('pilot','星环试航','自由三维飞行驾驶','空间','机后 / 座舱','三维飞行驾驶 / 自由航向','https://kenney.nl/assets/space-kit','assets/game-forms/pilot/sky.webp','驾驶立体飞船，改变航向、俯仰与速度，飞过八座信标，在机后与座舱镜头之间切换。','原创全景天空、八座三维光环、自由航向与升降、真实模型、碰撞、加速、减速、双镜头与信标重定位。','WASD / 方向键转向与升降 · 拖动转向 · C 加速 · R 减速 · 空格恢复水平 · E 切换镜头'),
 item('rail','回廊巡航','镜头驱动轨道射击','动作','自动巡航视角','轨道射击 / 自动镜头','forms.html#forms','assets/game-forms/pilot/sky.webp','沿三维回廊自动推进，瞄准陆续进入场面的无人机，换弹、躲避红色弹道，完成三段巡航。','三段三维回廊、十二台无人机、射线命中、九发弹匣、换弹、敌方实体弹道、压低镜头、阶段重试与完成。','移动鼠标 / 方向键瞄准 · 点击 / J 开火 · R 换弹 · 空格压低镜头避弹'),
 item('archive','潮灯档案','固定场景点击解谜','故事','房间切换 / 道具栏','点击冒险 / 调查与使用','forms.html#forms','assets/game-forms/archive/lobby.webp','调查三个海岸档案馆房间，取得线索，组合工具，修复能源与望远镜，让远处航标重新点亮。','三张原创房间、六件道具美术、场景热点、道具选择与组合、三象锁盒、正确与错误反馈、能源与镜片修复。','点房间对象调查 · 点道具选择，再点场景使用 · 组合木柄与铁撬头 · 星图提示锁盒顺序'),
 item('cargo','潮箱仓库','网格推箱与压力机关','策略','网格机关','推箱子 / 机关通路','forms.html#forms','assets/game-forms/cargo/room.webp','在仓库中推动真正挡路的货箱，压住机关，打开出口并走出三间仓库。','三间原创可解仓库、推箱阻挡、压力板与出口、路径行走、撤销、当前仓库重试与完成。','方向键 / WASD 或触屏方向移动 · 点击地面行走 / 近邻箱子推动 · C 撤销 · R 重试'),
 item('jewel','绮晶工坊','交换、掉落与三消连锁','策略','交换棋盘','三消 / 连锁整理','forms.html#forms','assets/game-forms/jewel/room.webp','在珠宝工坊交换相邻晶石，看见它们实际消除、掉落、补齐并继续形成连锁，完成双色订单。','八乘八棋盘、六种独立形状晶石、无效交换退回、重力掉落、补齐连锁、有限步数、订单与刷新续玩。','点选两个相邻晶石 / 拖动交换 · 完成琥珀与蓝晶订单 · 可重新整理棋盘'),
 item('realm','十二郡沿岸','地区与势力回合战略','策略','地区地图','宏观战略 / 地区调度','forms.html#forms','assets/game-forms/realm/map.webp','在沿岸地图管理地区收入、军力与相邻调度，观察势力归属随回合与行动真正变化。','十二个原创地区、实体邻接、收入、招募、发展、出征预览、实际占领、对方回合、回合重试与短局完成。','点击地区选择 · 招募 / 发展 · 选择出征目标并确认 · 结束回合'),
 item('novel','海岸末班信','人物对白与分支选择','故事','人物对白','互动小说 / 对话选择','forms.html#forms','assets/game-forms/novel/station.webp','末班列车前，陪工程师与调度员走过一个港口之夜。选择怎样回应，留下不同对白与结局。','两个原创成年人物、两处场景、逐字对白、对话记录、两条中段路线、三次选择、三个结局与已读记录。','点击对白 / 空格继续 · 点击选项回应 · E 查看对话记录 · 可切换即显文字'),
 item('party','余烬旅团','队伍与技能指令战斗','策略','队伍战斗','指令式 RPG / 队伍与目标','forms.html#forms','assets/game-forms/party/scene.webp','在天文台试炼中依次指挥近卫、术师与医师，选择技能和目标，再观察对方的真实行动。','两场队伍战斗、三个角色、单体与全体攻击、护盾、治疗、灵力恢复、敌方意图与逐次行动、战况记录。','选择当前队员技能 · 点击角色目标或目标按钮 · 三名队员行动后对方行动'),
 item('district','晨湾街区','三维城市与交通规划','策略','三维街区','城市建设 / 通勤网络','forms.html#forms','assets/showcase/previews/district.webp','补齐街区道路，建设住宅与诊所，看见车辆沿实际连通路线通勤，让海湾街区恢复运转。','三维建筑与车辆、建设预算、道路铺设与拆除、住宅与服务、真实寻路通勤和断路反馈、短场景完成。','选择道路 / 住宅 / 诊所 / 拆除工具 · 点击街区格子建设 · 观察可达性和通勤'),
 item('balance','重力工坊','真实三维刚体机关','空间','固定三维工坊','物理机关 / 抓取与支撑','forms.html#forms','assets/game-forms/balance/stone.webp','抓住并旋转桥板，把重物放到压力台，依靠真实支撑、重力与碰撞让检验车通过地沟和闸门。','真实刚体与抓取约束、旋转和放下、桥板支撑、重物压力台、实体检验车通行、失败重置与刷新恢复。','点击物件抓取 · 操作移动 / 升降 / 旋转控制 · 放下物件 · 检验通行'),
 item('tandem','同步灯桥','本地双人合作机关','动作','双人同屏','双人合作 / 同时输入','forms.html#forms','assets/game-forms/tandem/scene.webp','两个玩家同时操作工程师，配合持续压板与锁定装置，接通灯桥，并让两个人一起到达出口。','两间合作场景、两个独立输入角色、真实跳跃与平台碰撞、持续压板和双人充能、检查点恢复、独立多指触控。','P1 A/D 移动 · W / 空格跳跃；P2 左右键移动 · ↑ 跳跃；手机使用两套独立控制区'),
 item('putt','海岬果岭','真实三维迷你高尔夫','空间','三维球道','挥杆与球道 / 迷你高尔夫','forms.html#forms','assets/showcase/previews/putt.webp','判断方向与力度，看球沿真实三维球道滚动、碰壁反弹并落入洞杯。','多洞短球场、方向与力度、实体滚动与球道碰撞、入洞判定、杆数与刷新恢复。','调整方向与力度 · 挥杆 · 等球停稳后继续下一杆'),
 item('signal','岔口信号','三维铁路信号调度','策略','三维轨道','铁路调度 / 道岔与信号','forms.html#forms','assets/showcase/previews/signal.webp','观察列车去向与共享区段，调整道岔和信号，让各班列车真正抵达正确车站。','实体列车和轨道、区段占用、道岔与红绿灯、正确与错误到站、冲突失败、短班次和刷新续程。','观察列车目的站 · 改道岔 · 信号停放 · 避免区段冲突'),
 item('angler','暮湾浮标','三维水面垂钓','生活','水面与鱼线','垂钓 / 咬钩与张力','forms.html#forms','assets/showcase/previews/angler.webp','在黄昏海湾选择落点，读浮标咬钩信号，用收线和松线控制鱼线张力。','三维岸边与水面、抛竿、咬钩时机、不同鱼的拉力、真实收线距离、断线与脱钩、短任务完成。','选择落点与力度 · 抛竿 · 及时扬竿 · 按住收线或松线'),
 item('battery','岬湾炮阵','回合弹道与可破坏山地','策略','固定山地侧面','回合炮战 / 风力与抛物线','forms.html#forms','assets/showcase/previews/battery.webp','调节炮口角度和力度，在风力与重力下发射炮弹，看实际落点改变地形和炮位装甲。','双方轮流发射、实际抛物线、风力、预估弧线、爆炸范围伤害、持续地形弹坑、胜败与刷新续战。','角度和力度滑杆 · 发射炮弹 · 左右调角 / 上下调力度 · 空格发射'),
 item('range','信号突围','第一人称射击','动作','第一人称','Counter-Strike','https://store.steampowered.com/app/730/CounterStrike_2/',art+'card-7.webp','沿工业训练场移动，在靶机的攻击预兆出现时寻找掩体、瞄准和开火。','八台有攻击节奏的无人靶机，射线命中、弹药、换弹与生命。','WASD 移动 · 拖动转头 · 点击 / J 开火 · R 换弹'),
 item('expedition','风之遗址','第三人称立体冒险','空间','第三人称','Zelda: Breath of the Wild','https://www.nintendo.com/us/store/products/the-legend-of-zelda-breath-of-the-wild-switch/',art+'platform2d/background_color_trees.png','亲自走过林地和遗址，跳上平台，找到灯石并开启远处的门。','岩岸、营地、林木与遗址高台，骨骼动画、地图、三枚灯石与营地检查点。','WASD / 方向键移动 · 空格跳跃 · 拖动调整镜头'),
 item('builder','造一座归岛','立体搭建与修复','空间','第三人称','Minecraft','https://www.minecraft.net/en-us/about-minecraft',art+'platform2d/terrain_grass_block.png','亲手拆除和放置方块，在断开的两岸之间造出自己的路。','网格木桥搭建与回收、连续通路判断、材料库存、地图与灯塔修复。','WASD 移动 · 点选方块 · 挖掘 / 建造 · 空格跳跃'),
 item('garden','三日小农场','像素生活经营','生活','俯视','Stardew Valley','https://www.stardewvalley.net/press/','assets/worlds/ecology-terrain.webp','耕种、浇水、收获，把自己种出的作物送给邻居。','三日生长、六块田、体力与种子、收获、送礼和邻居回信。','点击田地行动 · 播种 / 浇水 / 收获 · 结束一天'),
 item('factory','铜轨工坊','工业自动化','策略','俯视','Factorio','https://www.factorio.com/',art+'card-5.webp','把矿源、传送带和熔炉接成生产线，看见原料真的流向成品。','有方向的输送网、采矿与熔炼、建设预算、拆除回收、十件交付。','选建筑 · 点网格放置 · R 转向 · 拆除回收'),
 item('checkpoint','边境值班室','文书与道德抉择','故事','工作台','Papers, Please','https://papersplea.se/',art+'card-9.webp','核对证件中的矛盾，面对带着各自故事的旅人，决定放行还是拒绝。','六位旅人的证件对照、规则核验、工资与生活开支、结局记录。','点击证件检查 · 放行 / 拒绝 · 继续下一位')
];
newDirections.push(
 item('roll','云廊滚球','连续惯性三维滚球','空间','三维跟随 / 高差回廊','连续滚球 / 空间与惯性','forms.html?left=rolling-ball&right=mini-golf#compare','assets/game-forms/roll/preview.webp','控制琉璃球穿过象牙石回廊，转向与制动改变真实滚动，在高差、弯道和水庭之间找到平衡。','连续三维球道、刚体惯性与高差碰撞、检查点、坠落恢复与终点。','方向键 / WASD 或触屏方向控制 · 空格制动 · 检查点恢复'),
 item('chain','琉光回廊','弧形轨道珠链射击','策略','固定庭院 / 移动珠链','轨道珠链 / 瞄准与连消','forms.html?left=marble-chain&right=match-three#compare','assets/game-forms/chain/preview.webp','在观测庭院向不断推进的琉璃珠链发射彩珠。瞄准、插入和同色回拢构成节奏，让连锁在真实轨道上发生。','曲线推进、实体发射与插入、三颗同色消除、间隙回拢与连消、换珠、短局胜败与保存。','指向轨道点击发射 · 左右键瞄准 / 空格发射 · C 或按钮换珠'),
 item('watch','夜潮值守','多机位监控室悬疑','故事','固定多机位 / 值守台','固定监控 / 观察与远程干预','forms.html?left=surveillance&right=stealth#compare','assets/game-forms/watch/preview.webp','在雨夜海岸站切换固定机位，观察人物的真实动向，用有限电力操作灯光和闸门，带领值班员安全离场。','四个统一场景机位、人物路线与危险推进、灯光引导、闸门干预、电力与时间、完成或失败。','机位按钮 / 数字键切换 · 灯光与闸门按钮控制 · 观察路线和电量')
);
newDirections.push(
 item('cue','暮色台球','顶视台球清台','空间','固定顶视 / 球桌','台球 / 瞄准与球体碰撞','forms.html?left=billiards&right=mini-golf#compare','assets/game-forms/cue/preview.webp','在温暖的胡桃木球台上安排下一杆。白球、彩球、库边和六个袋口共同决定实际落点。','六球练习与十五球三角开球、瞄准接触预览、力度控制、球体碰撞、库边反弹、落袋、白球恢复与独立保存。','移动 / 拖动瞄准 · 调力度 · 空格或按钮击球'),
 item('prism','琉璃星阵','街机挡板打砖块','动作','固定球场 / 挡板反弹','打砖块 / 挡板与反弹','forms.html?left=breakout&right=pinball#compare','assets/game-forms/prism/preview.webp','在月色观测台接住回落的光球，利用挡板两侧改变方向，逐块点亮琉璃星阵。','两幕砖阵、双层砖、连续球体反弹、可控接球角度、三次机会、扩展挡板奖励、轻松/标准模式与独立保存。','鼠标 / 拖动或左右键控制挡板 · 点击 / 空格或按钮发球')
);
newDirections.push(
 item('seek','海岸藏物阁','可放大场景寻物','故事','完整房间 / 局部放大','场景寻物 / 观察与定位','forms.html?left=hidden-object&right=point-click#compare','assets/game-forms/seek/preview.webp','在夕照下的收藏温室寻找八件真实画在房间中的藏物。放大、拖动和局部提示帮助你在精细场景里辨认它们。','八件实际场景物件、对应缩略图清单、逐件标记、1–2.4 倍缩放与拖动、三次位置提示、完成归档与独立保存。','点击场景物件 · 选择清单目标 · 放大后拖动 / 方向键平移 · 滚轮缩放'),
 item('conduit','铜潮管网','旋转线路接通','策略','固定装置 / 接口网络','管线旋转 / 连通与输送','forms.html?left=pipe-network&right=train-dispatch#compare','assets/game-forms/conduit/preview.webp','转动铜管装置，让接口逐段吻合。启动水泵后观察水流沿实际线路通过，查找断口，恢复港口与灯塔的供水。','两套可解管网、材质铜管零件、接口匹配与连通预览、旋转和撤销、逐段水流、断口定位、键盘选格与独立保存。','点铜管旋转 · 方向键 / 下方按钮选格 · 空格旋转 · 启动水泵 / E · C 撤销')
);
newDirections.push(
 item('trace','霓境拓界','划线围地与壁画修复','动作','固定单屏 / 路径与区域','划线围地 / 安全边线与区域分割','forms.html?left=territory-capture&right=maze-chase#compare','assets/game-forms/trace/preview.webp','沿青色安全边线移动，在暗色玻璃上画出分界。闭合路径，让隐藏的月湖壁画逐步重见光亮。','完整原创玻璃壁画、网格路径移动、敌方区域连通判定、实际游光碰线、三枚光芯、68% 修复目标、舒缓/标准节奏与独立保存。','方向键 / WASD 移动 · 空格开启划线 · 点同排或同列目标格走直线 · 下方按钮转向或收回线'),
 item('swing','风铃工坊','切绳摆荡与重力释放','空间','固定侧面 / 挂点与落点','切绳机关 / 摆动与约束','forms.html?left=rope-cutting&right=physics-puzzle#compare','assets/game-forms/swing/preview.webp','在清晨玻璃工坊安放悬挂灯球。切绳改变支撑，让实际摆动与释放惯性把灯送到软垫托座。','两幕原创工坊、灯球与托座素材、单绳和双绳约束、点按与划线切绳、连续重力和摆动、落点预览、慢放/定格/步进、重试与独立保存。','点 / 划过绳索切断 · 切绳按钮或数字键 1 / 2 · E 定格 · 右方向键步进 · 预览与慢放')
);
newDirections.push(
 item('bubble','琉璃穹顶','泡泡发射与悬空掉落','动作','固定穹顶 / 六角连接','泡泡发射 / 反弹与连通','forms.html?left=bubble-shooter&right=marble-chain#compare','assets/game-forms/bubble/preview.webp','在暮色玻璃工坊把琉璃送进球阵。利用反弹连接同色，切断顶部支撑，释放整串悬挂的光。','原创工坊与四色符号玻璃球、连续发射碰撞、侧壁反弹、六角邻接、三颗连消、悬空掉落、真实落点预览、40 发布阵、换球与独立保存。','点场地瞄准发射 · 左右键 / 滑条调角 · 空格发射 · E 交换待发球'),
 item('sonar','深海测绘','数字线索与隐藏危险','策略','固定棋盘 / 数字证据','数字排雷 / 八邻格推理','forms.html?left=mine-deduction&right=hidden-object#compare','assets/game-forms/sonar/preview.webp','在沉没遗迹绘制一张安全地图。用八邻格数字逐步揭开海床，标记暗雷，以看得见的证据作出判断。','原创海底与陶瓷棋格、8×8 棋盘、10 枚暗雷、首击九格安全、零格展开、标记、数字邻格快开、可见线索解释、键盘与窄屏选格、重开与独立保存；布局可能需要进一步推理或猜测。','点格探测 / 切换标记模式 · 右键标记 · 方向键选格 · 空格探测 · E 标记 · C 邻格快开')
);
newDirections.push(
item('hook','风隙航渡','抓钩跑酷','空间','侧面峡谷 / 连续摆荡','A Story About My Uncle','https://store.steampowered.com/app/278360/','assets/game-forms/nine/previews/hook.webp','借挂点摆过峡谷，松绳时保留真实速度，落到平台继续前行。','一段峡谷、三挂点、重力和绳长约束、主动收绳、摆荡加速、惯性释放、中途平台和独立保存；首版采用侧面单屏。','← → / A D 摆荡 · 空格挂住/松绳 · E 收绳 · 按钮切换挂点 · P 暂停'),
item('fold','折光回廊','错视空间','空间','三维等距投影 / 可旋转镜头','Monument Valley','https://monumentvalleygame.squarespace.com/blog/2014/5/9/how-we-made-monument-valley-what-do-you-want-to-know-1','assets/game-forms/nine/previews/fold.webp','建筑桥端在不同视角下有不同的投影关系，对齐后才形成错视通路。','四组建筑、八个三维节点、真实等距投影、镜头平滑旋转、端点距离判定、步行和独立保存；使用 Canvas 软件投影。','按钮旋转镜头 / E 右转 · 空格或点画面前行 · P 暂停'),
item('repair','时光修复铺','物件拆装修复','故事','近距离工作台 / 分层物件','Assemble with Care','https://www.assemblegame.com/','assets/game-forms/nine/previews/repair.webp','在真实材质工作台拆开怀表，把机芯、表盘和后盖依次复位，最后测试运行。','原创怀表四层素材、移盖清洁、零件拖放、方向和前置层检查、拆下顶层、辅助选件/移动/安装、运行测试和独立保存。','拖动零件 / 方向按钮移动 · E 旋转 · 空格安装 · 按钮拆盖、清洁和测试 · P 暂停'),
item('delve','深层回声','地形挖掘','空间','侧面地层 / 纵向跟随','SteamWorld Dig','https://store.steampowered.com/app/252410/SteamWorld_Dig/','assets/game-forms/nine/previews/delve.webp','玩家挖出的地形持续变为洞道，深度变化带动镜头，矿脉逐步显露。','12×22 可挖地层、逐格开路、矿脉收集、纵向跟随、底层信标、键盘/邻格点按/原生按钮和独立保存。','方向键 / WASD 逐格挖掘 · 邻格点按 / 原生方向按钮 · P 暂停'),
item('cluster','收藏物语','滚动吸附成长','动作','俯视庭院 / 尺度变化','Katamari Damacy','https://www.bandainamcoent.com/games/katamari-damacy-reroll','assets/game-forms/nine/previews/cluster.webp','从小物件开始滚动收集，物件实际附着在球体上，体积逐渐增大。','28 件原创收藏物、吸附尺寸门槛、物件真实附着、体积增长、镜头拉远、目标导航/连续移动和独立保存；首版采用俯视。','方向键 / WASD / 方向按钮滚动 · 点地面选择移动目标 · P 暂停'),
item('paint','流彩工场','涂地与形态切换','动作','俯视场地 / 可覆盖地表','Splatoon','https://splatoon.nintendo.com/es/gameplay/','assets/game-forms/nine/previews/paint.webp','颜色覆盖实际场地，角色在自己的颜色中快速潜行，对手不断重涂。','24×12 实际地表、青色/珊瑚覆盖、移动对手、颜料消耗和恢复、自己的颜色内加速、75 秒短局、58% 目标和独立保存。','方向键 / WASD / 点地面移动 · 空格切换潜行 · 按钮开关喷涂 · P 暂停'),
item('swarm','苔庭小队','小队跟随搬运','策略','庭院 / 主角与群体','Pikmin 4','https://pikmin4.nintendo.com/','assets/game-forms/nine/previews/swarm.webp','一群队员跟随主角，根据实际人数搬运物件，送回材料后修复通路。','12 名独立队员、3/6/12 分队规模、人数到位后搬运、三件材料、左岸修桥后右岸通行、召回归队和独立保存。','方向键 / WASD / 点地面带队 · 空格派遣 · E 召回 · 按钮选货物和分队 · P 暂停'),
item('kitchen','夜港晚餐','订单服务与连续工序','动作','厨房 / 多工位服务','Overcooked! 2','https://store.steampowered.com/app/728880/Overcooked_2/','assets/game-forms/nine/previews/kitchen.webp','在多个工位间移动，连续加工食材，让同时等待的订单得到实际交付。','三份同时等待订单、四工位、手持食材状态、三次切配、四秒烹调、取汤交付、等待结束和独立保存；首版为单人厨房工序。','按钮选工位并走到台前 · 空格 / E 操作工位 · 方向键 / 点地面移动 · P 暂停'),
item('relay','雾海协作台','信息不对称合作','故事','操作端 / 说明端','Keep Talking and Nobody Explodes','https://keeptalkinggame.com/','assets/game-forms/nine/previews/relay.webp','两人分别看到装置序号和说明规则，交流后操作线路、旋钮与脉冲。','操作/说明端隔离、序号规则、两条线路、旋钮和脉冲核对、三步完成、错误反馈和独立保存；首版为同设备交接式双端，不含跨设备联机。','原生按钮分步操作 · E 切换说明端 · 空格核对 · P 暂停')
);
newDirections.push(
item("tempo","静时之庭","时间操控","动作","俯视建筑空间 / 行动推进时间","SUPERHOT","https://store.steampowered.com/app/322500/SUPERHOT/","assets/game-forms/frontier/previews/tempo.webp","世界时间随你的移动推进，停下来能看清红色脉冲轨迹。","原创红白建筑场景、三座信标、按移动幅度改变时间倍率、脉冲轨迹与碰撞、返回终点和独立保存。","下方原生按钮 / 场景操作 · 方向键 / WASD · P 暂停"),
item("flux","元素玻璃舱","材料模拟","空间","剖面实验舱 / 连续材料变化","Noita","https://www.noitagame.com/","assets/game-forms/frontier/previews/flux.webp","水、沙、木材、火和蒸汽在同一个实验舱里持续相互作用。","96×56 元胞材料场、沙水流动、木材引燃、清水灭火、上升蒸汽、拖动投放、水槽目标与独立保存；简化材料模型。","下方原生按钮 / 场景操作 · 方向键 / WASD · P 暂停"),
item("coil","盘鳞浮庭","异形身体操控","动作","真实三维 / 分节身体","Snake Pass","https://store.steampowered.com/app/544330/Snake_Pass/","assets/game-forms/frontier/previews/coil.webp","分节的蛇形身体绕柱形成支撑，再抬高头部取回信环。","Three.js 三维浮庭、原创鳞片材质、28 节身体跟随与柱体避碰、盘绕支撑门槛、爬高和重力回落、两枚信环、独立保存及软件投影兼容模式；简化身体模型。","下方原生按钮 / 场景操作 · 方向键 / WASD · P 暂停"),
item("axiom","字石航灯","规则改写","策略","规则文字 / 可推实体棋盘","Baba Is You","https://www.hempuli.com/gamelist/index.php?rule=id&ruleid=3","assets/game-forms/frontier/previews/axiom.webp","文字组成的规则会改变岩石的实际属性，新的规则打开新的通路。","原创石板和实体素材、横纵规则解析、可移动词块、STOP/PUSH/WIN 实际条件、岩石推动、灯台结局与独立保存；按钮移动词块而非角色推词。","下方原生按钮 / 场景操作 · 方向键 / WASD · P 暂停"),
item("folio","四页光旅","绘本画框解谜","故事","四幅绘本 / 局部空间重组","Gorogoa","https://store.steampowered.com/app/557600/Gorogoa/","assets/game-forms/frontier/previews/folio.webp","重排并放大四幅原创绘本，让光点穿过不同世界的圆门。","四幅原创完整绘本、拖动或按钮交换、圆门局部放大、相邻画框条件、三段光点穿行、结果保留和独立保存。","下方原生按钮 / 场景操作 · 方向键 / WASD · P 暂停"),
item("expose","取景造境","摄影造景","空间","第一人称三维 / 照片实体化","Viewfinder","https://store.steampowered.com/app/1382070/Viewfinder/","assets/game-forms/frontier/previews/expose.webp","把手中的照片展开为真实桥面，走过原本不存在的通路。","第一人称 Three.js、原创天空与石材、两个取景台、两张预设建筑照片、实体桥面生成与通行判定、完整跨桥路线、独立保存；首版为限定建筑模板。","下方原生按钮 / 场景操作 · 方向键 / WASD · P 暂停"),
item("script","指令邮局","编程式解谜","策略","指令编排 / 工人执行","Human Resource Machine","https://tomorrowcorporation.com/humanresourcemachine","assets/game-forms/frontier/previews/script.webp","自己编排动作程序，让邮务机器人逐条执行并绕开障碍投递。","七类指令、24 条程序上限、选择重排删除、运行/单步/复位、碰撞和错误反馈、500 步循环上限、三封实际投递与独立保存。","下方原生按钮 / 场景操作 · 方向键 / WASD · P 暂停"),
item("echo","听见雾港","声音定位探索","故事","空间声音 / 有限可视场景","A Blind Legend","https://store.steampowered.com/app/437530/A_Blind_Legend/","assets/game-forms/frontier/previews/echo.webp","戴耳机沿三座声音信标走进雾港，方向与距离由空间声音传达。","Web Audio HRTF、动态监听位置与朝向、距离衰减声标、脚步与风声、左右耳校准、可选训练地图、静音/暂停/离开停止声音与独立保存；非完整无障碍叙事游戏。","下方原生按钮 / 场景操作 · 方向键 / WASD · P 暂停"),
item("assembly","深蓝议会","社交推理与伪装","故事","真实玩家房间 / 隐藏身份","Among Us","https://www.innersloth.com/games/among-us/","assets/game-forms/frontier/previews/assembly.webp","真实玩家在同一个研究站同步行动，只知道自己的身份，交流判断潜伏者。","本机房间服务、3–6 位真实玩家、建房加入与分享链接、私密身份、三工位旋钮任务、危机与现场修复、限时会议、真实发言投票和双阵营结局；需要本机 8963 服务，同浏览器不同窗口会分别保存会话。","下方原生按钮 / 场景操作 · 方向键 / WASD · P 暂停")
);
for(const d of newDirections)if(['tempo','flux','coil','axiom','folio','expose','script','echo','assembly'].includes(d.id))d.previewKind=['coil','expose'].includes(d.id)?'同场景三维兼容渲染预览':'生产场景绘制预览';
newDirections.push(
item("mosaic","拼回海港","拼图旋转吸附","空间","桌面近景 / 不规则拼片","Super Jigsaw Puzzle: Generations","https://store.steampowered.com/app/1036950/Super_Jigsaw_Puzzle_Generations/","assets/game-forms/studio/previews/mosaic.webp","把十二片带有互补榫口的原创海港画作旋转并拼合。","一幅原创海港画作、12 块互补榫口拼片、真实轮廓点击、旋转拖动、方向与位置吸附判定、可选参考图、完整画作结局与独立保存。","场景操作 / 下方原生控件 · 方向键 · Q / E · 空格 · P 暂停"),
item("span","峡谷承重桥","物理造桥","策略","侧面峡谷 / 杆件结构","Poly Bridge 3","https://play.google.com/store/apps/details?id=com.drycactus.polybridge3","assets/game-forms/studio/previews/span.webp","连接上下节点搭建桁架，让邮车实际逐段驶过受力桥面。","原创峡谷和杆件、11 个节点、两种材料、预算与拆除、二维线性桁架刚度求解、逐段移动载荷、强度与变形反馈、失稳坠落和过桥结局；形变显示放大 8 倍，非完整刚体物理。","场景操作 / 下方原生控件 · 方向键 · Q / E · 空格 · P 暂停"),
item("lumen","折光镜庭","光线反射解谜","空间","俯视光学桌 / 连续光路","The Talos Principle / 光路解谜","https://www.croteam.com/talosprinciple/","assets/game-forms/studio/previews/lumen.webp","旋转镜面改变连续光路，绕过遮光石点亮接收晶体。","两套镜庭、三面可旋转镜、真实线段求交与镜面反射、遮光石、连续稳定照射判定、行进光点和独立保存；参考光路解谜方向，自制二维镜面机制。","场景操作 / 下方原生控件 · 方向键 · Q / E · 空格 · P 暂停"),
item("sonata","灯下乐句","音乐作曲","生活","录音桌 / 四轨乐谱","Incredibox / 音乐创作","https://www.incredibox.com/","assets/game-forms/studio/previews/sonata.webp","直接创作旋律、低音、鼓和晶铃，听见自己写出的乐句并导出 WAV。","四轨 16 步作曲、八音高、80–160 BPM、原生控件、实际 PCM 合成与 Web Audio 试听、两轮创作练习、浏览器 WAV 导出、静音暂停释放声音和独立保存；参考音乐创作参与方式，非人物口技复刻。","场景操作 / 下方原生控件 · 方向键 · Q / E · 空格 · P 暂停"),
item("afterimage","昨日同行","动作录制回放协作","动作","侧面时钟厅 / 过去的动作","The Talos Principle / 时间录制","https://www.croteam.com/talosprinciple/","assets/game-forms/studio/previews/afterimage.webp","让过去的自己重复实际走过的路线，在另一枚机关上与你协作。","30 Hz 实际位置记录、最多两个 12 秒动作分身、终点停留、同步回放、两机关持续协作、时间门与归岸结局、未完成录制和完整独立保存；二维位置回放，非完整世界回滚。","场景操作 / 下方原生控件 · 方向键 · Q / E · 空格 · P 暂停"),
item("weave","交叉光晶","图案交叉推理","策略","玻璃工坊 / 行列数字","PICROSS S","https://www.nintendo.com/es-mx/store/products/picross-s-switch/","assets/game-forms/studio/previews/weave.webp","从行列连续长度推理每一格，逐步镶嵌出光晶图案。","8×8 多段线索棋盘、填色划空擦除、拖涂与键盘、撤销、合法排布推导提示、矛盾反馈、无需猜测的一套光晶图案、完成实体显露和独立保存。","场景操作 / 下方原生控件 · 方向键 · Q / E · 空格 · P 暂停")
);
for(const d of newDirections)if(["mosaic", "span", "lumen", "sonata", "afterimage", "weave"].includes(d.id))d.previewKind='生产场景绘制预览';
newDirections.push(
item("desktop","雨港收件箱","仿桌面侦探","故事","桌面窗口 / 文件与照片","Hypnospace Outlaw / 仿界面探索","https://www.hypnospace.net/","assets/game-forms/horizons/previews/desktop.webp","在虚构桌面中打开邮件、出库单与照片，连接证据寻找物资去向。","四类原生 HTML 窗口、五份虚构本地资料、档案全文过滤、窗口拖动置顶关闭、四项证据记录、三项结案判断、错误反馈、完整结案与独立保存；卡片为界面状态绘制预览，不是浏览器截图。","下方原生控件 / 场景窗口 / 中文指令 / 点三维陶块 · P 暂停"),
item("inkwell","给灯塔一行话","输入文字冒险","故事","场景插画 / 指令与文字记录","Hadean Lands / 指令式互动小说","https://hadeanlands.com/how/","assets/game-forms/horizons/previews/inkwell.webp","用中文指令探索四处灯塔场景，道具和机关状态会改变每条指令的结果。","四处原创场景、有限中文动词解析、容器与钥匙、提灯与燃料、镜片安装、未知指令与前置条件反馈、指令撤回、原生输入记录、点灯结局和独立保存；不接入语言模型，不承诺任意自然语言理解。","下方原生控件 / 场景窗口 / 中文指令 / 点三维陶块 · P 暂停"),
item("atelier","雕出一盏灯","三维体素雕刻","空间","真实三维雕塑 / 分层切片","Teardown / 可改变体素空间","https://www.teardowngame.com/","assets/game-forms/horizons/previews/atelier.webp","直接改变 125 块三维陶土，雕出顶底完整、四角支撑的镂空陶灯。","Three.js 三维网格、真实射线选块、125 块纹理陶土、目标三维灯雕、五层切片编辑、补土撤销、相机环绕、完成点灯和独立保存；无 WebGL 时投影同一套三维网格；不包含 Teardown 的动态破坏物理。","下方原生控件 / 场景窗口 / 中文指令 / 点三维陶块 · P 暂停"),
item("submersible","深潜协奏","多工位载具驾驶","策略","水下侧面航行 / 工位仪表","Barotrauma / 多系统潜艇","https://barotraumagame.com/","assets/game-forms/horizons/previews/submersible.webp","切换推进、浮力、声呐和检修工位，在持续航行中回收三项样本并返航。","原创海底与透明潜艇、推进加速度与阻尼、浮力深度控制、传播声呐与有限探测范围、低速回收、船体压力损伤、密封维修与电能、三项样本、返航完成和独立保存；单人切换四工位，没有多人船员或全流体模拟。","下方原生控件 / 场景窗口 / 中文指令 / 点三维陶块 · P 暂停")
);
for(const d of newDirections)if(["desktop", "inkwell", "atelier", "submersible"].includes(d.id))d.previewKind=d.id==='desktop'?'界面状态绘制预览':d.id==='atelier'?'同场景三维兼容渲染预览':'生产场景绘制预览';
newDirections.push(
item("cartographer","把海岸走成地图","地图勘察旅行","策略","海岛地图 / 路线与旅行","80 Days / 路线旅行","https://www.inklestudios.com/80days/","assets/game-forms/voyages/previews/cartographer.webp","规划带有补给成本的旅行路线，在三个海岸地标记录观察，再返回营地。","八处地点、十条连线、渡船证、路线预算、沿线旅行、三项观察分类、缩放平移、返营完成与独立保存；是一座岛的短途地图勘察，没有完整环球旅行或分支小说。","拖动场景 / 下方操作按钮 · 方向键 · 空格 · P 暂停"),
item("tendril","潮间柔性臂","柔性多肢操控","动作","水下研究舱 / 三条柔性臂","Octodad / 独立肢体操控","https://store.steampowered.com/app/224480/Octodad__Dadliest_Catch/","assets/game-forms/voyages/previews/tendril.webp","分别控制三条会弯曲的机械臂，将真实携带的样本送进同色接口。","三条 24 节定长运动学链、末端跟随、可达范围约束、三样本抓放、同色接口验证、同时持物、完整装配和独立保存；机身固定，没有全身步行、完整软体碰撞或流体物理。","拖动场景 / 下方操作按钮 · 方向键 · 空格 · P 暂停"),
item("cutout","纸片成为归途","剪纸造路","空间","纸片舞台 / 可变通路","Tearaway / 剪纸世界创作","https://www.mediamolecule.com/tearaway-papercraft","assets/game-forms/voyages/previews/cutout.webp","把三片纸桥移动、旋转和拉长，让几何端点连通四个锚点，再让纸信使试走。","三片原创纸桥、自由拖动旋转缩放、四锚点几何连通、整段拖动撤销、实际沿桥试走、断路坠落、投递完成和独立保存；不含完整刚体碰撞或自由剪切工具。","拖动场景 / 下方操作按钮 · 方向键 · 空格 · P 暂停"),
item("panorama","环视潮声","360°环视勘察","空间","固定观察点 / 全景球面","Myst III: Exile / 360°全景观察","https://cyan.com/games/myst-iii/","assets/game-forms/voyages/previews/panorama.webp","在同一个观察点环视完整海岸，放大并对准三个地标，记录各自方位和仰角。","原创 2:1 全景、Three.js 纹理球面、完整水平环视、仰俯角、望远镜变焦、真实方位投影、稳定测量、三地标日志与独立保存；无 WebGL 时使用球面纹理分块近似投影，模式明确标注；没有自由行走与立体地形。","拖动场景 / 下方操作按钮 · 方向键 · 空格 · P 暂停")
);
for(const d of newDirections)if(["cartographer", "tendril", "cutout", "panorama"].includes(d.id))d.previewKind=d.id==='panorama'?'同场景球面兼容渲染预览':'生产场景绘制预览';
newDirections.push(
item("ribbon","把风画成路","绘线引导","空间","侧面单屏 / 自由绘制轨道","Kirby and the Rainbow Paintbrush / 绘线引导","https://www.nintendo.com/en-gb/Games/Wii-U-games/Kirby-and-the-Rainbow-Paintbrush-893013.html","assets/game-forms/kinetics/previews/ribbon.webp","在空中画出经过三枚风印的线路，让玻璃风信使沿真实线路抵达右岸。","1500 像素墨水、自由连续绘线、32 笔上限、轨道吸附与重力坠落、短暂加速、三风印、线路撤销与独立保存；是单屏绘线引导短场景，没有完整刚体滚动物理、无限绘制或敌人系统。","画面拖动 / 下方按钮 · 方向键 · 空格 · E · R 回溯 · P 暂停"),
item("rescue","矿井十二人","群体间接救援","策略","侧面矿井 / 自动行走群体","Lemmings / 地形指令与群体救援","https://exient.helpshift.com/hc/en/3-lemmings/faq/12-what-are-instructions/","assets/game-forms/kinetics/previews/rescue.webp","十二位队员自动穿越矿井，你安排造梯、阻挡和开凿，护送至少十人抵达出口。","十二名自动队员、分批入场、渐进造梯与真实支撑、开凿石墙、个体阻挡、技能数量、坠落损失、队伍暂停安排、救援结果与独立保存；是一座矿井的短场景，没有完整寻路、地形任意开挖或原作技能全集。","画面拖动 / 下方按钮 · 方向键 · 空格 · E · R 回溯 · P 暂停"),
item("rewind","钟楼的第二次","世界时间回溯","空间","横向钟楼 / 整个局部世界回退","Braid, Anniversary Edition / 时间回退","https://www.playstation.com/en-us/games/braid-anniversary-edition/","assets/game-forms/kinetics/previews/rewind.webp","让钟楼桥下沉，到下层取晶石，再带它回到过去锁桥，走向原先到不了的出口。","30 秒局部世界历史、两倍速回溯、时间分支、桥与配重同步恢复、唯一时间免疫晶石、控制台锁桥、实际下层与出口、跳跃和独立保存；只记录本场景定义的组件，不代表通用引擎任意对象的完整时间回退。","画面拖动 / 下方按钮 · 方向键 · 空格 · E · R 回溯 · P 暂停"),
item("nested","掌心里的庭院","双尺度嵌套世界","空间","真实三维 / 模型与庭院双视图","Maquette / 递归尺度空间","https://www.annapurna.com/interactive/maquette","assets/game-forms/kinetics/previews/nested.webp","小模型里的两座桥与大庭院中的桥联动；先在模型里搭路，再在八倍大的世界亲自走过。","Three.js 实时三维、生成石木材质、两个相连尺度、同场景实时模型视图、实际射线拖桥、几何通路、庭院行走、失足重试、镜头环绕与独立保存；无 WebGL 时明确标注同几何兼容投影；是两个有限尺度，没有无限递归世界。","画面拖动 / 下方按钮 · 方向键 · 空格 · E · R 回溯 · P 暂停")
);
for(const d of newDirections)if(["ribbon", "rescue", "rewind", "nested"].includes(d.id))d.previewKind=d.id==='nested'?'同场景三维兼容渲染预览':'生产场景绘制预览';
newDirections.push(
item("inverter","倒悬温室","重力翻转平台","动作","侧面单屏 / 地面与天花板","VVVVVV / 翻转重力平台","https://thelettervsixtim.es/","assets/game-forms/thresholds/previews/inverter.webp","翻转重力，让天花板成为脚下的路，绕过上下荆棘并收集三枚星印。","上下表面支撑、实体障碍和危险区、落地翻转、动作图集、三枚星印、中段重试检查点与独立保存；是一段二维原创短场景，没有滚屏关卡或任意方向重力。","方向键 / A D · 空格 · 下方按钮 · P 暂停"),
item("phasewalk","昼夜之间","双世界切换","空间","同坐标双层舞台 / 即时切换","Guacamelee! / 双世界空间切换","https://store.steampowered.com/app/275390/Guacamelee_Super_Turbo_Championship_Edition/","assets/game-forms/thresholds/previews/phasewalk.webp","在同一位置切换白昼和夜层，让两个世界独有的台面拼成一条通路。","昼夜原创场景、各自独有的平台、公共落脚区、四枚限定世界星印、切换重叠拒绝、幽影预览、检查点与独立保存；是一个双层单屏通路，没有战斗或完整双世界地图。","方向键 / A D · 空格 · 下方按钮 · P 暂停"),
item("transit","折向的航程","传送门惯性","空间","二维侧面 / 两端局部场景窗口","Portal / 门面与动量","https://www.thinkwithportals.com/about.php","assets/game-forms/thresholds/previews/transit.webp","先选传送门位置，让下落的胶囊穿越到墙面出口，保留速率飞上远端高台。","二维固定门位三选一、双向平面穿越、速度正交变换、实时另一端局部场景窗口、运动轨迹、瞬间速率读数、真实高台碰撞、三枚星印与独立保存；不是第一人称三维非欧空间，不支持任意墙面放门或无限递归渲染。","方向键 / A D · 空格 · 下方按钮 · P 暂停"),
item("cantor","以声音飞行","声音音高控制","动作","空中单屏 / 连续音高输入","One Hand Clapping / 唱声参与","https://www.thqnordicmobile.com/en/games/one-hand-clapping/","assets/game-forms/thresholds/previews/cantor.webp","持续哼唱让灯船前行，声音音高决定高度；也可按住低中高音键盘直接试玩。","显式启用的本地麦克风、PCM 音高识别、舒适最低音校准、音高与高度连续映射、信噪门槛、音环保持判定、明确标注的 Z/X/C 键盘替代与独立保存；音频不上传或存储，暂停和离开释放设备；没有语音文字识别、情绪识别或实际设备验收。","低/中/高音按钮或 Z/X/C · 空格飞行 · 显式启用麦克风 · 校准音域")
);
for(const d of newDirections)if(["inverter", "phasewalk", "transit", "cantor"].includes(d.id))d.previewKind="生产场景绘制预览";
newDirections.push(
item("prismcube","珐琅的六面","立体扭转复原","解谜","实时三维 / 可环绕观察","Rubik’s 2×2 / 表层扭转","https://www.rubiks.com/products/rubiks-2x2","assets/game-forms/circuitry/previews/prismcube.webp","选择一面转动四个角块，把八个角块复原成六面同色。","八个真实三维角块、24 张珐琅面片、六面正反转、连续转动动画、实际面片拾取、环绕镜头、撤销、可逆操作路径提示与中途保存；优先 WebGL，兼容路径投影同一套几何，明确标注。是固定五步打乱的二阶短段，没有任意打乱生成或最优求解器。","拖动画面环绕 · R L U D F B 转面 · Shift 反转 · 下方原生按钮"),
item("orbiter","十二道星环","径向环轨射击","动作","环形舞台 / 径向航道","Tempest / 管道射击形式","https://atari.com/products/tempest-4000","assets/game-forms/circuitry/previews/orbiter.webp","沿圆周换轨，对准向外逼近的探机，把十二条航道重新守住。","原创轨道观测站、透明飞船与探机、12 条离散航道、自动与手动连射、真实弹丸命中、双点耐久目标、越界护盾、失败重试与独立保存；是单波 12 目标的二维环轨短段，没有三维曲面关卡或多波进阶。","点击或拖动圆环换轨 · 左右 / A D · J 按住发射 · 下方按钮"),
item("automata","铜棋自走阵","自动战棋布阵","策略","等距棋盘 / 战前布阵","Teamfight Tactics / 部署后自动战斗","https://teamfighttactics.leagueoflegends.com/en-us/","assets/game-forms/circuitry/previews/automata.webp","先安排守卫、电弩与修复的位置，开战后看队员自行寻路、攻击与支援。","原创竞技厅与六台透明机械单位、三职业配比、左侧 4×6 部署区、9×6 交战棋盘、占位与目的地保留寻路、近远程攻击、有限修复、真实血量、两档速度、保留布阵重试和独立保存；是单轮三对三，没有金币、商店、招募、升星或多人匹配。","点队员或编号选择 · 点左侧空格部署 · 更换职业 · 开始自动对抗"),
item("receiver","夜潮调频台","无线电调谐","感知","实体仪表 / 连续调节","OXENFREE / 调谐作为交互","https://nightschoolstudio.com/oxenfree/","assets/game-forms/circuitry/previews/receiver.webp","转动三个旋钮，让三座本地信标模型从噪声里变得清晰，稳定后分别记录。","原创收音机台与透明旋钮、三个本地信标模型、频谱模型与波形反馈、真实旋钮拖动和原生滑杆、频率相位带宽质量公式、1.2 秒稳定门槛、显式试听的本地合成信号与噪声、暂停静音释放、独立保存；不接收真实无线电、不访问麦克风，不提供剧情广播或真实射频处理。","拖动画面旋钮或下方滑杆 · 选择信标 · 开始扫描 · 稳定后记录 · 声音按需监听")
);
for(const d of newDirections)if(["prismcube", "orbiter", "automata", "receiver"].includes(d.id))d.previewKind=d.id==="prismcube"?"同一套三维几何兼容投影预览":"生产场景绘制预览";
newDirections.push(
item("cascade","海窗落块台","落块消行","解谜","固定竖井 / 持续下落","Tetris / 下落与横排消除","https://play.tetris.com/about","assets/game-forms/parlor/previews/cascade.webp","在海窗前移动和旋转七种四格方块，填满横排，让堆叠空间重新打开。","原创海窗落块站与八色透明珐琅方块贴图，10×18 棋盘、七种四格形状、有限旋转让位、真实碰撞与落点预览、暂存交换、渐速下落、软降与硬降、消行闪光、顶出失败、引导开局两行和空板六行、暂停及独立保存。使用固定循环队列，是原创短段，不提供竞技随机袋、完整 SRS、无限模式或多人对战。","左右 / A D 移动 · 上 / E 顺转 · Q 反转 · 下 / S 加速 · 空格落下 · Shift 暂存 · 拖动与下方控件"),
item("patience","蓝绒接龙桌","纸牌接龙","解谜","俯视牌桌 / 遮盖与揭牌","Klondike / 揭牌与顺序整理","https://mobilityware.helpshift.com/hc/en/10-solitaire/faq/1362-how-do-i-play-solitaire/?contact=1&p=all","assets/game-forms/parlor/previews/patience.webp","在蓝绒牌桌上腾出空列，揭开压住的牌，把四种花色从 A 到 5 依次归位。","原创绒面牌桌、透明正反牌面、运行时点数与花色、四列二十张 A–5 的固定原创短牌局、红黑交替递减叠牌、同花顺序归位、空列从 5 开始、翻牌区顶牌、循环重新发牌、揭牌动画、实际卡牌拖动、选牌点击、撤销、合法动作提示和独立保存。不是完整 52 张七列 Klondike，没有随机发牌、竞技计时或多人。","点选或拖动明牌 · 点列或同花归位区 · 空格翻牌 · E 归位所选单牌 · 原生按钮撤销与提示"),
item("lexicon","字印的回声","字词位置推理","解谜","字母矩阵 / 逐格线索","Wordle 形式 / 字母与位置反馈","https://arxiv.org/abs/2309.02110","assets/game-forms/parlor/previews/lexicon.webp","把五字母单词压印在纸面上，用每一格的位置与数量反馈，在六次内找到谜词。","原创字印桌与透明陶瓷字母格、五列六行、24 个本地英文候选词与六个固定轮换谜词、逐格翻转揭示、重复字母精确计数、颜色与圆点菱形短横双重线索、原生输入与屏幕键盘、已试字母状态、中文词义提示、候选词填入、六次失败与新谜词、独立保存。不是在线每日谜题，不接入 NYT、不含完整词典或多人。","输入五字母词 · Enter 提交 · Backspace 删除 · 下方键盘、候选词与中文线索")
);
for(const d of newDirections)if(["cascade", "patience", "lexicon"].includes(d.id))d.previewKind="生产场景绘制预览";
newDirections.push(
item("dicework","鎏光五骰桌","掷骰锁定组合","策略","实体骰桌 / 结果保留","Yahtzee / 保留与重掷","https://instructions.hasbro.com/en-ca/instruction/yahtzee-classic","assets/game-forms/trajectories/previews/dicework.webp","选择保留五枚骰子中的哪些结果，把有限重掷机会用于三轮不同组合。","原创紫绒骰桌与透明象牙骰面、五枚真实点数、最多三次掷骰、单枚锁定和部分重掷、六类真实计分、选择后确认记录、每类一次、三轮完成、不同本地种子序列、滚动动画、原生键盘与独立保存。是六类三轮的原创短局，固定可复现伪随机序列，不是完整十三类 Yahtzee、三维刚体骰子或多人，没有金钱下注。","点骰子或 1–5 锁定 · R / 空格重掷 · 点击类别 · 下方确认记录"),
item("synchro","零点同步行动","同步规划战术","策略","俯视网格 / 规划与同步执行","Frozen Synapse / 同步回合形式","https://blog.playstation.com/2014/09/11/frozen-synapse-prime-combat-basics-on-ps-vita/","assets/game-forms/trajectories/previews/synchro.webp","先安排两台侦察机的四步路径，让双方在同一时段移动和交战，清除探机并抵达信标。","原创雨夜货场与四类透明实体素材、10×6 网格、两对两固定地图、公开探机意图、两台最多四步路线、原地等待、撤销与清空、同时移动与争格等待、箱体视线遮挡、三格攻击与伤害共同结算、路径与插值动画、正常与双倍速度、八轮限额、真实耐久、信标目标与半途保存。没有在线双方提交、战争迷雾或随机地图。","点侦察机或 1 / 2 · 点相邻格或方向键规划 · 等待与撤销 · 空格同步执行"),
item("perigee","近星交会","轨道引力航行","模拟","俯视轨道 / 惯性与引力","引力轨道导航 / 中心引力","https://science.nasa.gov/learn/basics-of-space-flight/chapter3-3/","assets/game-forms/trajectories/previews/perigee.webp","通过有限推力改变飞船速度，在行星引力下滑行，达到距离与相对速度门槛后完成交会。","原创星空、透明行星与飞船交会站、二维单中心反平方引力、Velocity Verlet 积分、圆轨速度校准、真实 delta-v 与燃料、方向选择和持续推力、轨迹预测与实际历史、三个时间倍率和视野、圆轨目标站、距离与相对速度共同门槛、行星碰撞与边界失败、暂停与独立保存。使用无量纲单位和固定初始交会练习，不是完整三维轨道、多天体或实际飞行器训练。","先校准圆轨速度再滑行 · 左右转向 · J 持续推力 · 空格脉冲 · 选择倍率和视野 · 接近后对接")
);
for(const d of newDirections)if(["dicework", "synchro", "perigee"].includes(d.id))d.previewKind="生产场景绘制预览";
newDirections.push(
item("rigworks","铆钉工坊","机械组装与试驾","空间","三维装配 / 机后与环绕镜头","Besiege / 拼装后检验机械的形式","https://store.steampowered.com/app/346010/Besiege/","assets/game-forms/foundry/previews/rigworks.webp","选择车轴、轮胎、动力和抓取臂，驾驶自己组装的运输车，停稳搬货，穿过缓坡完成交付。","可切换两到三个车轴、公路与越野轮胎、两种动力和抓取臂；独立车轮转动与贴地、车体缓冲和倾斜、停稳抓取、实际载货质量、缓坡试驾、边界碰撞、环绕与机后镜头、装配撤销、暂停与独立保存。当前是固定路线的原创运输练习，车辆运动采用简化模型，后续可以增加更多零件与任务。","先安装抓取臂并开始试驾 · W/S 前后 · A/D 转向 · 空格制动 · E 停稳抓取或交付 · 下方按钮也可操作"),
item("drift","失重航廊","六自由度三维行动","空间","三维失重 / 机后与第一人称","Overload / Descent 六自由度形式","https://store.steampowered.com/app/448850/Overload/","assets/game-forms/foundry/previews/drift.webp","在失重设施间自由升降、横移、前后推进和翻滚，依次通过四座不同位置与高度的信标。","真实三维空间和飞船模型、六向平移、三轴姿态旋转、姿态影响推进、惯性与辅助减速、主动制动、设施碰撞与船体耐久、四座空间信标、朝向目标辅助、机后与第一人称镜头、鼠标拖动转向、暂停与独立保存。当前是短程空间驾驶练习，可继续增加复杂空间路线与任务。","W/S 前后 · A/D 横移 · R/F 升降 · 方向键转向俯仰 · Q/E 翻滚 · 空格制动 · 可朝向信标和切换镜头"),
item("levelsmith","风谷造关室","关卡创作与即时试玩","空间","编辑画布 / 横版平台舞台","Super Mario Maker 2 / 创作与试玩形式","https://www.nintendo.com/us/store/products/super-mario-maker-2-switch/","assets/game-forms/foundry/previews/levelsmith.webp","亲手放置道路、晶石、尖刺和出口，一键切换到角色试玩，用实际跳跃和碰撞验证自己的设计。","原创山谷背景与透明探索者、石台、尖刺、晶石和出口美术；六种绘制工具、点按与连续拖动、整笔撤销、两套可通关模板、空白画布、唯一出生点和出口、设计检查、即时试玩、跳跃缓冲、真实平台碰撞、晶石收集、失败重试、返回编辑、当前版本通过记录和独立保存。当前为本地短关卡创作，后续可增加分享与更多机关。","1–6 选择工具 · 点按或拖动设计 · 立即试玩 · A/D 移动 · 空格跳跃 · 返回设计、撤销或重试")
);
for(const d of newDirections)if(["rigworks", "drift", "levelsmith"].includes(d.id))d.previewKind=d.id==="levelsmith"?"生产场景绘制预览":"同场景三维离线渲染预览";
newDirections.push(
item("satchel","行囊工坊","背包空间配装","策略","俯视工作台 / 空间装备","Backpack Hero / 空间摆放影响能力","https://store.steampowered.com/app/1970580/Backpack_Hero/","assets/game-forms/exchange/previews/satchel.webp","把不同形状的装备放进行囊，用位置和相邻组合改变攻击、防护和补给，再实际检验远行结果。","六种原创透明装备、6×5 行囊及两处封闭格、拖动与点按、四向旋转、实际形状碰撞与空间占用、三种正交邻接联动、移回托盘、撤销、真实逐轮配装检验、胜负与本地独立保存。当前为固定装备和一次守卫遭遇，没有完整随机冒险进程。","选择或拖动装备 · 点击行囊放置 · R 旋转 · 方向键调整 · Enter 放置 · 检验配装"),
item("gavel","钟声拍卖","限时竞价拍卖","策略","拍卖现场 / 鉴定与竞价席","Dealer’s Life 2 / 鉴定与拍卖决策","https://store.steampowered.com/app/1343670/Dealers_Life_2/","assets/game-forms/exchange/previews/gavel.webp","观察拍品鉴定、竞争者和倒计时，决定追价或放弃；只有真实成交才扣款，三件拍品形成实际收藏账目。","三件原创拍品、拍卖厅美术、鉴定范围、两个本地竞价角色、真实倒计时、近结束出价延时、预算限制、实际成交扣款、成交价与估值收益、三场结果、本地保存。当前对手是本地规则角色，不是联网真人拍卖，也不是现实资产交易。","查看鉴定 · 选择加价档位 · 看竞争与落槌 · 下一件拍品 · 可暂停观察"),
item("postway","月湾接力","跨窗口异步接力","空间","路线地图 / 制图与接棒两端","Death Stranding / 间接协作的参考方向","https://store.steampowered.com/app/1850570/DEATH_STRANDING_DIRECTORS_CUT/","assets/game-forms/exchange/previews/postway.webp","一个窗口留下经过驿站的路线，另一个窗口用接力码读取并继续运输；共享进度保存在本机服务中。","原创月湾地图、12×7 实际网格与岩脊、相邻不重复路线、三座驿站与港口、六位接力码、独立身份领取、权威一步移动、HTTP 与 SQLite 持久化、重复请求恢复、双方状态核对、暂停与本地身份保存。服务仅绑定本机 127.0.0.1:8971，当前不是互联网多人持久世界，没有模拟的另一玩家。","制图端点格或方向键画路线 · 发布后复制六位码 · 打开接棒窗口输入 · 沿金线逐步送达")
);
for(const d of newDirections)if(["satchel", "gavel", "postway"].includes(d.id))d.previewKind="生产 Canvas2D 场景绘制预览";
for(const direction of newDirections)if(!['roll','chain','watch','cue','prism','seek','conduit','trace','swing','bubble','sonar','hook','fold','repair','delve','cluster','paint','swarm','kitchen','relay',"tempo","flux","coil","axiom","folio","expose","script","echo","assembly","mosaic","span","lumen","sonata","afterimage","weave","desktop","inkwell","atelier","submersible","cartographer","tendril","cutout","panorama","ribbon","rescue","rewind","nested","inverter","phasewalk","transit","cantor","prismcube","orbiter","automata","receiver","cascade","patience","lexicon","dicework","synchro","perigee","rigworks","drift","levelsmith","satchel","gavel","postway"].includes(direction.id))direction.cover=art+'previews/'+direction.id+'.webp';
for(const direction of newDirections){
 if(!['putt','signal','angler','battery'].includes(direction.id))continue;
 direction.originalCover=direction.cover;
 if(new URLSearchParams(location.search).get('edition')!=='original')direction.cover='assets/game-forms/polish/previews/'+direction.id+'.webp';
}
newDirections.find(d=>d.id==='order').scope='七种方块按组轮换、旋转与碰撞、落点预览、消行、加速与当前得分。';
newDirections.find(d=>d.id==='wonder').scope='连续平台、三枚邮票、弹簧、敌人、检查点与终点。';
export const legacyDirections=[
 ['detective','旧城失物局','雨夜黑色电影','故事','俯视','调查证据、对照证词并作出归还判断。'],
 ['wuxia','山间小驿站','国风江湖','故事','俯视','山路调查、有限物资与救援安排。'],
 ['ecology','小小生态岛','自然微缩','生活','俯视','栽植、水文与三个季节的演替。'],
 ['wasteland','最后一座温室','废土生存','策略','俯视','维修设备与物资分配，面对三轮天气。'],
 ['dream','记忆渡船','梦境幻想','故事','横版','记忆物件改变通路与归岸选择。'],
 ['arcade','屋顶快递赛','都市霓虹跑酷','动作','横版','跳跃、冲刺、检查点与计时投递。'],
 ['inn','七日小旅店','暖色生活叙事','生活','俯视','家具布置、来客活动与回访书信。'],
 ['islands','浮岛探险社','低多边形幻想','空间','第三人称','工具、真实通路、遗迹与归航。'],
 ['movers','搬家日','手绘生活物理','生活','横版','三份委托，拿起、轻放、投掷与送达。']
].map(([game,title,subtitle,family,view,description])=>({id:'legacy-'+game,game,title,subtitle,family,view,description,legacy:true,reference:'原有独立短篇',cover:'assets/extension-'+(game==='movers'?'moving-day':game)+'.webp',scope:'保留当前版本、画风切换、已实现章节和原有浏览器存档。',controls:'操作说明与目标显示在游戏内部。'}));
export const directions=[...legacyDirections,...newDirections];
export const directionMap=Object.fromEntries(directions.map(d=>[d.id,d]));
