import {canvasSurface,images} from './showcase-core.js';import {sceneHeading} from './showcase-observation-kit.js?v=20261004-2';import {voyageText as text,voyagePlate as plate,voyageRing as ring,voyageComplete} from './showcase-voyages-kit.js';
import {parlorController,BLOCK_VIEW,CARD_VIEW,cardPositions} from './showcase-parlor-kit.js';import {blockCells,blockLanding,nextBlocks,selectedCards,SUITS,isRed,letterKnowledge,WORD_CLUES} from './showcase-parlor-rules.js';import {PARLOR_SPRITES as frames} from './showcase-parlor-sprites.js';
const base='assets/game-forms/parlor/';
function sprite(c,im,f,x,y,w,h){const [x0,y0,x1,y1]=f;c.drawImage(im,x0,y0,x1-x0,y1-y0,x,y,w,h);}
function footer(c,left,right){plate(c,28,594,1064,29,'#102831ed');text(c,left,44,614,12);text(c,right,1074,614,11,'#d2e5d5','right');}
function blockTile(c,art,kind,x,y,size,alpha=1){c.save();c.globalAlpha=alpha;sprite(c,art['block-tiles'],frames['block-tiles'][kind],x+1,y+1,size-2,size-2);c.restore();}
function preview(c,art,kind,x,y,size=27){const cells=blockCells({kind,x:0,y:0,rotation:0}),minX=Math.min(...cells.map(p=>p.x)),maxX=Math.max(...cells.map(p=>p.x)),minY=Math.min(...cells.map(p=>p.y)),maxY=Math.max(...cells.map(p=>p.y));for(const p of cells)blockTile(c,art,kind,x+(p.x-minX-(maxX-minX+1)/2)*size,y+(p.y-minY-(maxY-minY+1)/2)*size,size);}
function cascade(c,s,art){c.drawImage(art['block-room'],0,0,1120,630);const v=BLOCK_VIEW,w=v.cell*10,h=v.cell*18;c.save();c.fillStyle='#071e35aa';c.fillRect(v.x,v.y,w,h);c.strokeStyle='#98d4df70';c.lineWidth=1;c.strokeRect(v.x-.5,v.y-.5,w+1,h+1);for(let x=1;x<10;x++){c.beginPath();c.moveTo(v.x+x*v.cell,v.y);c.lineTo(v.x+x*v.cell,v.y+h);c.strokeStyle='#5e91b521';c.stroke();}for(let y=1;y<18;y++){c.beginPath();c.moveTo(v.x,v.y+y*v.cell);c.lineTo(v.x+w,v.y+y*v.cell);c.strokeStyle='#5e91b521';c.stroke();}c.beginPath();c.rect(v.x,v.y,w,h);c.clip();
 for(let y=0;y<18;y++)for(let x=0;x<10;x++)if(s.board[y][x]>=0)blockTile(c,art,s.board[y][x],v.x+x*v.cell,v.y+y*v.cell,v.cell);
 if(!s.clear&&!s.won&&!s.failed){const landing=blockLanding(s);for(const p of blockCells(landing)){c.save();c.fillStyle='#a3eeed1c';c.strokeStyle='#baf8e6b0';c.lineWidth=1.5;c.fillRect(v.x+p.x*v.cell+3,v.y+p.y*v.cell+3,v.cell-6,v.cell-6);c.strokeRect(v.x+p.x*v.cell+3,v.y+p.y*v.cell+3,v.cell-6,v.cell-6);c.restore();}for(const p of blockCells(s.piece))blockTile(c,art,s.piece.kind,v.x+p.x*v.cell,v.y+p.y*v.cell,v.cell);}
 if(s.dropFx){const e=s.dropFx,a=1-e.age/.55;c.save();c.globalAlpha=a*.5;for(const cell of blockCells(e.to)){const g=c.createLinearGradient(0,v.y+e.from.y*v.cell,0,v.y+cell.y*v.cell);g.addColorStop(0,'#b7f5eb00');g.addColorStop(1,'#b7f5ebaa');c.fillStyle=g;c.fillRect(v.x+cell.x*v.cell+9,v.y+(e.from.y+1)*v.cell,6,(cell.y-e.from.y)*v.cell);ring(c,v.x+(cell.x+.5)*v.cell,v.y+(cell.y+.5)*v.cell,8+(1-a)*17,'#ddfaed',1);}c.restore();}
 if(s.clear)for(const y of s.clear.rows){const a=Math.sin(Math.min(1,s.clear.time/.28)*Math.PI);c.fillStyle=`rgba(220,255,234,${.2+a*.6})`;c.fillRect(v.x,v.y+y*v.cell,w,v.cell);c.save();c.shadowBlur=18;c.shadowColor='#dcffee';c.strokeStyle='#dcffee';c.lineWidth=2;c.strokeRect(v.x,v.y+y*v.cell+1,w,v.cell-2);c.restore();}c.restore();
 sceneHeading(c,'每一次落下，都在重新整理空间','落点幽影 · 暂存交换 · 横排消除，方块持续落下');plate(c,36,114,195,98,'#14364be6');text(c,s.mode==='guided'?'引导开局':'自由堆叠',53,143,18,'#f4e4b6');text(c,`消行 ${s.lines} / ${s.mode==='guided'?2:6}`,53,172,15,'#d6f1d7');text(c,`分数 ${s.score}`,53,197,13,'#c7deed');
 plate(c,647,111,247,188,'#102d45b3');text(c,'接下来',670,143,17,'#f6e4b4');nextBlocks(s).forEach((kind,i)=>preview(c,art,kind,706+(i%2)*113,195+Math.floor(i/2)*65,24));plate(c,647,316,247,112,'#102d45b3');text(c,'暂存',670,347,15,'#f6e4b4');if(s.hold===null)text(c,'Shift 可保留一块备用',770,389,12,'#b9d4de','center');else{preview(c,art,s.hold,770,387,25);text(c,s.held?'本块已交换':'可与当前块交换',878,418,10,'#c8dbd2','right');}
 plate(c,647,447,247,86,'#102d45b3');text(c,s.won?'横排已经打开':s.failed?'堆叠到顶':s.running?'移动 → 旋转 → 落稳':'按下方按钮开始',670,476,15,'#f5e8c5');text(c,s.mode==='guided'?'右侧四格空槽，可用长条填满。':'空板开局，用不同形状整理横排。',670,506,11,'#ceddd8');footer(c,`落稳 ${s.drops} 块  ·  消行 ${s.lines}  ·  分数 ${s.score}`,'左右移动 · E/Q 旋转 · 空格落下 · Shift 暂存');if(s.failed){plate(c,300,318,420,87,'#1d3345f2');text(c,'上方空间不足',510,355,22,'#ffd5a0','center');text(c,'重新开始，利用幽影先检查落点。',510,381,12,'#dbe7d7','center');}if(s.won)voyageComplete(c,'落下的方块，打开了空间',s.mode==='guided'?'两行引导已完成，可切到空板堆叠继续体验。':'六行已经清空，保留这个整理结果。');}
function slot(c,x,y,label){c.save();c.strokeStyle='#d4dcc372';c.lineWidth=1.5;c.setLineDash([5,5]);c.beginPath();c.roundRect(x-CARD_VIEW.w/2,y,CARD_VIEW.w,CARD_VIEW.h,8);c.stroke();c.restore();text(c,label,x,y+75,23,'#bbcecca0','center');}
function card(c,art,card,x,y,{selected=false,flip=1}={}){const v=CARD_VIEW;c.save();c.translate(x,y+v.h/2);c.scale(Math.max(.06,Math.abs(flip)),1);if(selected){c.shadowColor='#c6eec8';c.shadowBlur=17;}else{c.shadowColor='#061426';c.shadowBlur=8;c.shadowOffsetY=4;}const im=art[card.up?'card-front':'card-back'],frame=frames[card.up?'card-front':'card-back'];sprite(c,im,frame,-v.w/2,-v.h/2,v.w,v.h);c.shadowBlur=0;c.shadowOffsetY=0;if(card.up){const color=isRed(card)?'#ae4c46':'#273f4f',rank=card.rank===1?'A':String(card.rank);text(c,rank,-v.w/2+14,-v.h/2+26,19,color);text(c,SUITS[card.suit],-v.w/2+13,-v.h/2+43,15,color);text(c,SUITS[card.suit],0,12,42,color,'center');c.save();c.rotate(Math.PI);text(c,rank,-v.w/2+14,-v.h/2+26,17,color);c.restore();}if(selected){c.strokeStyle='#cdf2c9';c.lineWidth=2;c.beginPath();c.roundRect(-v.w/2-2,-v.h/2-2,v.w+4,v.h+4,9);c.stroke();}c.restore();}
function patience(c,s,art,drag){c.drawImage(art['card-table'],0,0,1120,630);const v=CARD_VIEW,moving=drag?.moved&&s.selected,source=moving?s.selected:null;sceneHeading(c,'揭开下一张，给它留出位置','列内红黑交替、点数递减 · 同花从 A 到 5 归位');text(c,'发牌区',v.stock,105,12,'#d6e2d3','center');text(c,'翻牌区',v.waste,105,12,'#d6e2d3','center');if(s.stock.length)card(c,art,s.stock[0],v.stock,v.top);else slot(c,v.stock,v.top,'↻');text(c,'余 '+s.stock.length+' 张',v.stock,v.top+v.h+22,11,'#c5d9d1','center');slot(c,v.waste,v.top,'翻牌');if(s.waste.length&&source?.source!=='waste')card(c,art,s.waste.at(-1),v.waste,v.top,{selected:s.selected?.source==='waste'});
 for(let suit=0;suit<4;suit++){const x=v.foundations[suit];text(c,SUITS[suit]+' 归位 '+s.foundations[suit]+'/5',x,105,12,isRed({suit})?'#f0c9b8':'#dce7db','center');slot(c,x,v.top,SUITS[suit]);if(s.foundations[suit])card(c,art,{suit,rank:s.foundations[suit],up:true},x,v.top);}
 for(let col=0;col<4;col++){text(c,'第 '+(col+1)+' 列',v.columns[col],v.columnY-12,12,'#deead9','center');if(!s.columns[col].length)slot(c,v.columns[col],v.columnY,'5');const points=cardPositions(s,col);points.forEach((p,i)=>{if(source?.source==='column'&&source.col===col&&i>=source.i)return;const flip=s.flip?.col===col&&i===points.length-1?Math.sin(s.flip.age/.3*Math.PI/2):1;card(c,art,p.card,p.x,p.y,{selected:s.selected?.source==='column'&&s.selected.col===col&&i>=s.selected.i,flip});});}
 if(moving){const cards=selectedCards(s);cards.forEach((value,i)=>card(c,art,value,drag.p.x-drag.offset.x,drag.p.y-drag.offset.y+i*v.upGap,{selected:true}));}
 const count=s.foundations.reduce((a,b)=>a+b,0);footer(c,`归位 ${count}/20  ·  整理 ${s.moves} 次  ·  重新发牌 ${s.redeals} 次`,s.won?'全部归位 · 可撤销回看':s.hint||'点选或拖动明牌 · 空列只接 5 开头的牌序');if(s.won)voyageComplete(c,'每一张牌，都找到了归处','二十张牌通过揭牌、红黑整理与同花递增全部归位');}
const MARK_COLORS=['#697c7c','#b68c3f','#4d8667'],MARK_SIGNS=['−','◆','●'];
function lexicon(c,s,art){c.drawImage(art['word-room'],0,0,1120,630);const left=302,top=115,size=55,gap=8,knowledge=letterKnowledge(s);
 for(let row=0;row<6;row++)for(let col=0;col<5;col++){const g=s.guesses[row],current=!g&&row===s.guesses.length,letter=g?g.word[col]:current?s.draft[col]:null,age=s.reveal?.row===row?s.reveal.age-col*.11:1,shown=!!g&&age>.16,phase=s.reveal?.row===row?Math.max(0,Math.min(1,age/.3)):1,scale=phase<.5?1-phase*1.7:.15+(phase-.5)*1.7,x=left+col*(size+gap),y=top+row*(size+gap);c.save();c.translate(x+size/2,y+size/2);c.scale(1,Math.max(.12,scale));sprite(c,art['letter-tile'],frames['letter-tile'],-size/2,-size/2,size,size);if(shown){c.globalCompositeOperation='multiply';c.fillStyle=MARK_COLORS[g.marks[col]];c.beginPath();c.roundRect(-size/2+4,-size/2+4,size-8,size-8,7);c.fill();c.globalCompositeOperation='source-over';}if(current){c.strokeStyle=letter?'#716d46':'#b5ae8970';c.lineWidth=1.3;c.strokeRect(-size/2+3,-size/2+3,size-6,size-6);}if(letter){c.save();c.font='600 28px Georgia,serif';c.textAlign='center';c.fillStyle=shown?'#fff9dd':'#263d39';c.fillText(letter,0,9);c.restore();}if(shown)text(c,MARK_SIGNS[g.marks[col]],0,22,9,'#fff4cf','center');c.restore();}
 sceneHeading(c,'把一个词，逐格听清','每次猜词留下位置与数量线索 · 六次内找出五字母谜词');plate(c,717,121,339,166,'#17382deb');text(c,'三种线索，不只看颜色',735,150,18,'#f4e3b7');for(let i=0;i<3;i++){c.fillStyle=MARK_COLORS[2-i];c.beginPath();c.roundRect(735,170+i*31,22,22,4);c.fill();text(c,MARK_SIGNS[2-i],746,185+i*31,12,'#fff4d9','center');text(c,['位置正确','字母存在，位置待定','本次该字母无剩余匹配'][i],769,186+i*31,12,'#e0e8d2');}plate(c,717,303,339,122,'#17382deb');text(c,'已试过的字母',735,332,15,'#f4e3b7');const used=Object.keys(knowledge).sort();if(!used.length)text(c,'输入一个候选词，开始比较。',735,365,12,'#d2e5d0');used.forEach((ch,i)=>{const x=739+i%10*29,y=346+Math.floor(i/10)*31;c.fillStyle=MARK_COLORS[knowledge[ch]];c.beginPath();c.roundRect(x,y,23,26,4);c.fill();text(c,ch,x+11.5,y+18,13,'#fff5d4','center');});plate(c,717,441,339,73,'#17382deb');text(c,`本轮第 ${s.round+1} 个谜词 · ${s.guesses.length} / 6 次`,735,468,14,'#f0e5c9');text(c,'输入、候选词与中文线索在下方。',735,494,11,'#d2e5d0');footer(c,`五字母 · 本地 24 词 · 已试 ${s.guesses.length}/6`,s.reveal?'逐格揭示线索':s.failed?'答案 '+s.target:s.won?'本轮完成 · 可换谜词':'重复字母按实际数量匹配');if(s.failed){plate(c,280,521,620,55,'#1d3932f2');text(c,'本轮答案是 '+s.target+' · 可更换谜词继续',590,555,19,'#f4ddab','center');}if(s.won)voyageComplete(c,'每一格线索，都找到了位置',s.target+' · 用 '+s.guesses.length+' 次猜词完成了本轮');}
export async function createParlor(options){const {id,host}=options,names=id==='cascade'?['block-room','block-tiles']:id==='patience'?['card-table','card-front','card-back']:['word-room','letter-tile'],art=await images(names,base),surface=canvasSurface(host),draw={cascade,patience,lexicon}[id];if(!draw)throw Error('Unknown parlor '+id);return parlorController(options,{element:surface.element,draw(s,drag){draw(surface.ctx,s,art,drag);},dispose(){surface.element.remove();}});}
