import {THREE,modelsAt,fitModel,surface3D,projectPoint} from './showcase-3d-kit.js';
import * as CANNON from './vendor/physics/cannon-es-0.20.0.js';
import {action,clamp,safeSaved} from './showcase-core.js';

export const BALANCE_RULES={gravity:-9.81,step:1/120,bridge:[4.6,.18,1.05],weight:[.9,.9,.9],platformTop:.8,gap:2.4,plate:{x:3.25,y:.89,z:-1.75,size:1.3},stableSeconds:1.2,gripMaxForce:500};
const defaults={version:1,elapsed:0,score:0,won:false,phase:'arrange',held:null,hand:null,bodies:null,stable:0,bridge:false,pressure:false,gate:0,grabs:0,drops:0,rotations:0,tests:0,replays:0,contacts:[],lastMessage:'转过桥板，让它同时搭在两边。配重压下压力台后，检验车才能通过。'};
const initial={bridge:{position:[-3.2,.89,0],quaternion:[0,Math.SQRT1_2,0,Math.SQRT1_2]},weight:{position:[-3.6,1.25,1.7],quaternion:[0,0,0,1]},cart:{position:[-4.1,1.08,0],quaternion:[0,0,0,1]}};
export async function createBalance({host,input,saved,notify,sfx}){
 const [nature,station,blaster]=await Promise.all([modelsAt('assets/showcase/nature/',['bridge_center_woodRound','fence_planks','rock_smallFlatA']),modelsAt('assets/showcase/station/',['table-large','container','computer','pipe','wall-window','balcony-rail','door-double-closed']),modelsAt('assets/showcase/blaster/',['crate-medium'])]);
 const view=surface3D(host,{background:'#383b3b',fov:44,far:100,shadows:true}),{scene,camera,renderer,element}=view;renderer.toneMappingExposure=1.03;
 element.setAttribute('aria-label','重力工坊。抓住并转动木桥板，放到地沟两边；配重压下压力台，再运行检验车。抓取、移动、旋转和放开均可使用下方按钮。');element.style.touchAction='none';
 let s=safeSaved(saved,defaults),active=false,grip=null,dragging=false,pointerStart=null,turnLatch=0,previousPressure=false,previousBridge=false;
 const physics=new CANNON.World({gravity:new CANNON.Vec3(0,BALANCE_RULES.gravity,0),allowSleep:true});physics.solver.iterations=25;physics.defaultContactMaterial.friction=.62;physics.defaultContactMaterial.restitution=.025;physics.defaultContactMaterial.contactEquationStiffness=1e8;physics.defaultContactMaterial.contactEquationRelaxation=4;
 const wood=new CANNON.Material('wood'),metal=new CANNON.Material('metal');physics.addContactMaterial(new CANNON.ContactMaterial(wood,metal,{friction:.72,restitution:.02}));
 scene.fog=new THREE.Fog('#383b3b',22,54);scene.add(new THREE.HemisphereLight(0xc5e3e2,0x443128,2.1));const sun=new THREE.DirectionalLight(0xffd49a,3.8);sun.position.set(-6,12,6);sun.castShadow=true;sun.shadow.mapSize.set(2048,2048);sun.shadow.camera.left=-11;sun.shadow.camera.right=11;sun.shadow.camera.top=9;sun.shadow.camera.bottom=-9;sun.shadow.camera.near=.5;sun.shadow.camera.far=35;sun.shadow.bias=-.0004;sun.shadow.normalBias=.04;scene.add(sun);const fill=new THREE.DirectionalLight(0xa0c5d4,1.5);fill.position.set(8,7,-7);scene.add(fill);
 camera.position.set(11.2,12.5,13.3);camera.lookAt(.1,.35,-.35);camera.updateMatrixWorld(true);
 const stoneTexture=await new THREE.TextureLoader().loadAsync('assets/game-forms/balance/stone.webp');stoneTexture.colorSpace=THREE.SRGBColorSpace;stoneTexture.wrapS=stoneTexture.wrapT=THREE.RepeatWrapping;stoneTexture.repeat.set(2.2,2.2);stoneTexture.anisotropy=Math.min(8,renderer.capabilities.getMaxAnisotropy());const floorTexture=stoneTexture.clone();floorTexture.repeat.set(5,4);
 const materials={stone:new THREE.MeshStandardMaterial({color:0xb9c7b8,map:stoneTexture,roughness:.91}),floor:new THREE.MeshStandardMaterial({color:0x899585,map:floorTexture,roughness:.95}),brass:new THREE.MeshStandardMaterial({color:0xc4a577,metalness:.72,roughness:.4}),steel:new THREE.MeshStandardMaterial({color:0x405254,metalness:.63,roughness:.46}),inset:new THREE.MeshStandardMaterial({color:0x27363b,roughness:.81}),mint:new THREE.MeshStandardMaterial({color:0x89c5af,emissive:0x256853,emissiveIntensity:.45,roughness:.52})};
 function meshBox(size,position,material){const o=new THREE.Mesh(new THREE.BoxGeometry(...size),material);o.position.set(...position);o.castShadow=true;o.receiveShadow=true;scene.add(o);return o}
 function staticBox(id,size,position,material){const body=new CANNON.Body({mass:0,shape:new CANNON.Box(new CANNON.Vec3(size[0]/2,size[1]/2,size[2]/2)),material:metal,position:new CANNON.Vec3(...position)});body.name=id;physics.addBody(body);return {body,mesh:meshBox(size,position,material)}}
 const floor=staticBox('floor',[16,.6,11],[0,-.45,-.15],materials.floor),left=staticBox('left',[4,.8,5.6],[-3.2,.4,0],materials.stone),right=staticBox('right',[4,.8,5.6],[3.2,.4,0],materials.stone),plate=staticBox('plate',[1.3,.18,1.3],[3.25,.89,-1.75],materials.brass),gate=staticBox('gate',[.24,2.4,2],[4.8,2,0],materials.steel);
 gate.mesh.visible=false;const door=fitModel(station['door-double-closed'],2.3,'y');door.position.set(4.8,2,0);door.rotation.y=Math.PI/2;scene.add(door);
 // Authored Kenney models remain the visible objects. The boxes below are
 // their rigid collision volumes, not substitutes for the authored artwork.
 function sizedModel(gltf,size){const group=new THREE.Group(),o=gltf.scene.clone(true);o.updateMatrixWorld(true);let box=new THREE.Box3().setFromObject(o),dim=box.getSize(new THREE.Vector3());if(size[0]>size[2]&&dim.z>dim.x){o.rotation.y=Math.PI/2;o.updateMatrixWorld(true);box=new THREE.Box3().setFromObject(o);dim=box.getSize(new THREE.Vector3())}const center=box.getCenter(new THREE.Vector3());o.position.sub(center);group.add(o);group.scale.set(size[0]/(dim.x||1),size[1]/(dim.y||1),size[2]/(dim.z||1));o.traverse(n=>{if(n.isMesh){n.castShadow=true;n.receiveShadow=true;n.material=n.material.clone();if('roughness'in n.material)n.material.roughness=.69}});return group}
 const bridgeModel=new THREE.Group();for(let i=0;i<5;i++){const section=sizedModel(nature.bridge_center_woodRound,[BALANCE_RULES.bridge[0]/5,BALANCE_RULES.bridge[1],BALANCE_RULES.bridge[2]]);section.position.x=-BALANCE_RULES.bridge[0]/2+BALANCE_RULES.bridge[0]/10+i*BALANCE_RULES.bridge[0]/5;bridgeModel.add(section)}const weightModel=sizedModel(blaster['crate-medium'],BALANCE_RULES.weight);scene.add(bridgeModel,weightModel);
 const brassBand=new THREE.Mesh(new THREE.BoxGeometry(.045,.94,.94),materials.brass);weightModel.add(brassBand);brassBand.scale.set(1/weightModel.scale.x,1/weightModel.scale.y,1/weightModel.scale.z);brassBand.position.x=0;
 const dynamic={};for(const [id,size,mass,mesh] of [['bridge',BALANCE_RULES.bridge,6,bridgeModel],['weight',BALANCE_RULES.weight,5,weightModel]]){const body=new CANNON.Body({mass,shape:new CANNON.Box(new CANNON.Vec3(size[0]/2,size[1]/2,size[2]/2)),material:id==='bridge'?wood:metal,linearDamping:.13,angularDamping:.28,allowSleep:false});body.name=id;physics.addBody(body);dynamic[id]={body,mesh,size,mass};mesh.userData.balanceBody=id;mesh.traverse(n=>n.userData.balanceBody=id)}
 const cartBody=new CANNON.Body({mass:1.2,shape:new CANNON.Sphere(.26),material:new CANNON.Material('wheel'),linearDamping:.23,angularDamping:.2,allowSleep:false});cartBody.name='cart';physics.addBody(cartBody);physics.addContactMaterial(new CANNON.ContactMaterial(cartBody.material,metal,{friction:.15,restitution:0}));physics.addContactMaterial(new CANNON.ContactMaterial(cartBody.material,wood,{friction:.15,restitution:0}));
 const cart=new THREE.Group();const cartChassis=new THREE.Mesh(new THREE.BoxGeometry(.62,.24,.44),materials.brass);cartChassis.position.y=.02;cart.add(cartChassis);const cargoTop=new THREE.Mesh(new THREE.BoxGeometry(.3,.14,.32),materials.steel);cargoTop.position.set(-.04,.2,0);cart.add(cargoTop);for(const x of [-.22,.22])for(const z of [-.26,.26]){const wheel=new THREE.Mesh(new THREE.CylinderGeometry(.13,.13,.08,18),materials.inset);wheel.rotation.x=Math.PI/2;wheel.position.set(x,-.11,z);cart.add(wheel)}cart.traverse(o=>{if(o.isMesh){o.castShadow=true;o.receiveShadow=true}});scene.add(cart);
 const cursor=new CANNON.Body({type:CANNON.Body.KINEMATIC,collisionFilterGroup:0,collisionFilterMask:0});physics.addBody(cursor);const reticle=new THREE.Mesh(new THREE.TorusGeometry(.24,.018,8,40),new THREE.MeshBasicMaterial({color:0x99f2d3,transparent:true,opacity:.95}));reticle.rotation.x=Math.PI/2;scene.add(reticle);const tether=new THREE.Line(new THREE.BufferGeometry().setFromPoints([new THREE.Vector3(),new THREE.Vector3()]),new THREE.LineBasicMaterial({color:0x9be8cb,transparent:true,opacity:.8}));scene.add(tether);
 const plateLamp=new THREE.PointLight(0x8acdad,0,2);plateLamp.position.set(3.25,1.2,-1.75);scene.add(plateLamp);
 for(const x of [-3.2,3.2]){meshBox([4.02,.035,.09],[x,.828,2.68],materials.brass);meshBox([4.02,.035,.09],[x,.828,-2.68],materials.brass);for(let z=-2.4;z<2.5;z+=.6)meshBox([3.75,.008,.012],[x,.805,z],materials.inset)}
 // The unfilled gap visibly reaches the workshop floor. Physical bodies can
 // fall into it and never get repositioned or snapped onto target markers.
 for(const x of [-1.22,1.22])meshBox([.055,.08,5.5],[x,.85,0],materials.brass);for(const x of [-.78,0,.78])meshBox([.08,.03,5.5],[x,-.13,0],materials.steel);
 const furniture=[];function prop(model,size,position,rotation=0,axis='y'){const o=fitModel(model,size,axis);o.position.set(...position);o.rotation.y=rotation;scene.add(o);furniture.push(o);return o}
 prop(station['table-large'],1.6,[-5.5,.68,-4.05],.15);prop(station.computer,.65,[-5.6,1.57,-4.05],.28);for(let i=0;i<4;i++)prop(station.container,.65+i%2*.12,[4.9+i*.55,.25,-3.75],.3+i*.3);for(const x of [-7,-3,1,5])prop(station['wall-window'],3.5,[x,1.55,-5.0],0,'y');for(const x of [-6.8,-6.45])prop(station.pipe,3.5,[x,.65,-4.6],0,'x');for(let i=0;i<3;i++)prop(nature.fence_planks,2.4,[-5.5,-.02,3.9-i*1.8],Math.PI/2,'x');prop(nature.rock_smallFlatA,.5,[6.35,0,3.3]);
 const signs=[];function worldSign(text,position,color='#ede1bc'){const canvas=document.createElement('canvas');canvas.width=512;canvas.height=128;const ctx=canvas.getContext('2d');ctx.fillStyle='#1c302e';ctx.fillRect(0,0,512,128);ctx.strokeStyle='#bfa66f';ctx.lineWidth=4;ctx.strokeRect(5,5,502,118);ctx.font='600 39px "Microsoft YaHei", sans-serif';ctx.textAlign='center';ctx.fillStyle=color;ctx.fillText(text,256,78);const map=new THREE.CanvasTexture(canvas),o=new THREE.Mesh(new THREE.PlaneGeometry(2.8,.7),new THREE.MeshBasicMaterial({map,side:THREE.DoubleSide}));o.position.set(...position);scene.add(o);signs.push(o)}worldSign('GRAVITY / 04',[.1,2.8,-4.82]);
 const hud=document.createElement('div');hud.className='balance-hud';hud.innerHTML='<style>.balance-hud{position:absolute;inset:0;pointer-events:none;font-family:"Microsoft YaHei",sans-serif;color:#f5ead3}.balance-hud .bal-title{position:absolute;left:3%;top:4%;padding:12px 17px;background:#17302cde;border:1px solid #a3b89a77;border-radius:4px;box-shadow:0 6px 16px #0003}.bal-title small{display:block;color:#b9c9b5;font-size:10px;letter-spacing:.18em}.bal-title b{display:block;font-size:22px;margin:5px 0;font-weight:500}.bal-title em{font-size:11px;font-style:normal;color:#bfd1bb}.bal-help{position:absolute;right:3%;top:5%;text-align:right;font-size:12px;line-height:1.7;color:#e9dfc4;text-shadow:0 1px 4px #000}.bal-label{position:absolute;transform:translate(-50%,-50%);background:#152b29e6;border:1px solid #e1c88c80;padding:6px 9px;font-size:11px;border-radius:3px;white-space:nowrap}.bal-progress{position:absolute;bottom:4%;left:3%;right:3%;display:flex;gap:8px}.bal-progress span{padding:8px 11px;background:#17302de8;border:1px solid #638574;font-size:11px;border-radius:3px}.bal-progress span[data-ok=true]{background:#42684ee8;border-color:#a1d3b1}.bal-end{position:absolute;left:25%;right:25%;top:35%;padding:24px;text-align:center;background:#15392df0;border:1px solid #c6bc8a;box-shadow:0 12px 45px #0005}.bal-end b{display:block;font-size:26px;font-weight:500}.bal-end p{font-size:12px;line-height:1.8;color:#c6d8bf}.balance-hud [hidden]{display:none!important}@media(max-width:760px){.balance-hud .bal-title{padding:7px 9px}.bal-title b{font-size:15px;margin:3px 0}.bal-title small{font-size:7px}.bal-title em{font-size:8px}.bal-help{font-size:8px;max-width:45%}.bal-label{font-size:8px;padding:4px 6px}.bal-progress{gap:4px}.bal-progress span{padding:5px 6px;font-size:8px}.bal-end{left:13%;right:13%;padding:16px}.bal-end b{font-size:18px}.bal-end p{font-size:9px}}</style><div class="bal-title"><small>GRAVITY / WORKSHOP</small><b>重力工坊</b><em>桥板 · 配重 · 检验车</em></div><div class="bal-help">抓住物体 → 移动与旋转 → 放开<br>桥板搭两岸 · 配重压开闸</div><span class="bal-label" data-label="bridge"></span><span class="bal-label" data-label="weight"></span><span class="bal-label" data-label="plate">压力台 · 5 kg</span><div class="bal-progress"><span data-check="bridge"></span><span data-check="pressure"></span><span data-check="test"></span></div><div class="bal-end" hidden><b>重量，让道路成立</b><p>桥板承住了检验车，配重让闸门持续开启。<br>你搭建的结构完成了真实通行检验。</p></div>';host.append(hud);
 const abort=new AbortController();
 function bodySnapshot(body){return {position:body.position.toArray(),quaternion:body.quaternion.toArray(),velocity:body.velocity.toArray(),angularVelocity:body.angularVelocity.toArray(),sleepState:body.sleepState}}
 function restoreBody(id,body){const raw=s.bodies?.[id]||initial[id],valid=(a,n)=>Array.isArray(a)&&a.length===n&&a.every(Number.isFinite);body.position.set(...(valid(raw.position,3)?raw.position:initial[id].position));body.quaternion.set(...(valid(raw.quaternion,4)?raw.quaternion:initial[id].quaternion));body.quaternion.normalize();body.velocity.set(...(valid(raw.velocity,3)?raw.velocity:[0,0,0]));body.angularVelocity.set(...(valid(raw.angularVelocity,3)?raw.angularVelocity:[0,0,0]));body.aabbNeedsUpdate=true;if(raw.sleepState===CANNON.Body.SLEEPING)body.sleep();else body.wakeUp()}
 for(const [id,{body}] of Object.entries(dynamic))restoreBody(id,body);restoreBody('cart',cartBody);
 function message(text){s.lastMessage=text;notify(text)}
 function release(silent=false){if(!grip)return;physics.removeConstraint(grip);grip=null;s.held=null;s.hand=null;dragging=false;s.drops++;if(!silent){sfx('turn');message('已放开。物体会在重力和碰撞作用下落下，等待它停稳。')}}
 function grab(id,restoring=false){if(!dynamic[id]||s.won)return;if(grip)release(true);const body=dynamic[id].body;cursor.position.copy(body.position);cursor.quaternion.copy(body.quaternion);grip=new CANNON.LockConstraint(body,cursor,{maxForce:BALANCE_RULES.gripMaxForce});grip.collideConnected=false;physics.addConstraint(grip);body.wakeUp();s.held=id;if(!restoring){s.grabs++;s.hand={position:[body.position.x,clamp(body.position.y+1.25,1.3,4.2),body.position.z],quaternion:body.quaternion.toArray()};sfx('pickup');message(id==='bridge'?'桥板已抓住。转 90°，移动到地沟中央，再放开。':'配重已抓住。移到右上方的压力台，再放开。')}else cursor.quaternion.set(...s.hand.quaternion)}
 const oldHeld=s.held,oldHand=s.hand;if(oldHeld&&dynamic[oldHeld]&&oldHand?.position?.every(Number.isFinite)&&oldHand?.quaternion?.every(Number.isFinite)){s.hand=oldHand;grab(oldHeld,true)}else{s.held=null;s.hand=null}
 function move(dx,dy,dz){if(!s.held)return;s.hand.position[0]=clamp(s.hand.position[0]+dx,-5,5);s.hand.position[1]=clamp(s.hand.position[1]+dy,.85,4.2);s.hand.position[2]=clamp(s.hand.position[2]+dz,-2.75,2.75);dynamic[s.held].body.wakeUp()}
 function rotate(axis,angle){if(!s.held)return;const q=new CANNON.Quaternion(...s.hand.quaternion),delta=new CANNON.Quaternion();delta.setFromAxisAngle(new CANNON.Vec3(...axis),angle);delta.mult(q,q);q.normalize();s.hand.quaternion=q.toArray();s.rotations++;dynamic[s.held].body.wakeUp();sfx('turn')}
 function startTest(){if(s.won)return;if(s.held){message('先放开物体，让桥板和配重各自停稳。');return}if(!s.bridge||!s.pressure||s.stable<BALANCE_RULES.stableSeconds){message('还不能检验：桥板需要同时接触两岸，配重需要压住压力台，并保持稳定。');return}s.phase='testing';s.tests++;cartBody.position.set(...initial.cart.position);cartBody.quaternion.set(0,0,0,1);cartBody.velocity.set(0,0,0);cartBody.angularVelocity.set(0,0,0);cartBody.aabbNeedsUpdate=true;cartBody.wakeUp();message('检验车已出发。它会实际经过桥板和闸门；失去支撑就会落入地沟。');sfx('build')}
 function restart(){release(true);const replays=s.replays+1;s={...structuredClone(defaults),replays};for(const [id,{body}] of Object.entries(dynamic))restoreBody(id,body);restoreBody('cart',cartBody);previousBridge=previousPressure=false;message('重新搭建开始。桥板和配重已经回到各自的起点。')}
 function retryCar(){s.phase='arrange';cartBody.position.set(...initial.cart.position);cartBody.quaternion.set(0,0,0,1);cartBody.velocity.set(0,0,0);cartBody.angularVelocity.set(0,0,0);cartBody.aabbNeedsUpdate=true;cartBody.wakeUp();message('检验车已回到起点。保留现有搭建，调整之后可以再试。')}
 const raycaster=new THREE.Raycaster(),ndc=new THREE.Vector2();function screenRay(event){const r=element.getBoundingClientRect();ndc.set((event.clientX-r.left)/r.width*2-1,1-(event.clientY-r.top)/r.height*2);raycaster.setFromCamera(ndc,camera);return raycaster}
 function pointAtHand(event){if(!s.held)return;const point=new THREE.Vector3(),plane=new THREE.Plane(new THREE.Vector3(0,1,0),-s.hand.position[1]);screenRay(event).ray.intersectPlane(plane,point);if(!Number.isFinite(point.x))return;s.hand.position[0]=clamp(point.x,-5,5);s.hand.position[2]=clamp(point.z,-2.75,2.75);dynamic[s.held].body.wakeUp()}
 element.addEventListener('pointerdown',e=>{if(!active||s.won||s.phase==='testing')return;pointerStart={x:e.clientX,y:e.clientY};const hit=screenRay(e).intersectObjects(Object.values(dynamic).map(o=>o.mesh),true)[0],id=hit?.object.userData.balanceBody;if(!s.held&&id){grab(id);dragging=true;element.setPointerCapture(e.pointerId)}else if(s.held){dragging=true;pointAtHand(e);element.setPointerCapture(e.pointerId)}},{signal:abort.signal});
 element.addEventListener('pointermove',e=>{if(active&&dragging&&s.held&&pointerStart&&Math.hypot(e.clientX-pointerStart.x,e.clientY-pointerStart.y)>5)pointAtHand(e)},{signal:abort.signal});
 element.addEventListener('pointerup',()=>{dragging=false;pointerStart=null},{signal:abort.signal});element.addEventListener('pointercancel',()=>{dragging=false;pointerStart=null},{signal:abort.signal});
 function hasContact(a,b){return physics.contacts.some(c=>c.enabled!==false&&(c.bi===a&&c.bj===b||c.bi===b&&c.bj===a))}
 function checkSensors(dt){s.contacts=physics.contacts.map(c=>[c.bi.name,c.bj.name]).filter(p=>p.every(Boolean));const bridge=dynamic.bridge.body,weight=dynamic.weight.body;const supported=hasContact(bridge,left.body)&&hasContact(bridge,right.body),flat=new CANNON.Vec3();bridge.quaternion.vmult(new CANNON.Vec3(0,1,0),flat);s.bridge=supported&&Math.abs(flat.y)>.94&&Math.abs(bridge.position.z)<.35&&bridge.velocity.length()<.15&&bridge.angularVelocity.length()<.16&&s.held!=='bridge';s.pressure=hasContact(weight,plate.body)&&weight.position.y>plate.body.position.y&&weight.velocity.length()<.12&&s.held!=='weight';s.stable=s.bridge&&s.pressure?Math.min(2,s.stable+dt):0;if(s.pressure!==previousPressure){sfx('door');previousPressure=s.pressure}if(s.bridge&&!previousBridge)sfx('pickup');previousBridge=s.bridge;const target=s.pressure?1:0;s.gate=THREE.MathUtils.lerp(s.gate,target,Math.min(1,dt*4.5));gate.body.position.y=2+s.gate*2.7;gate.body.aabbNeedsUpdate=true}
 physics.addEventListener('preStep',()=>{if(s.phase==='testing')cartBody.applyForce(new CANNON.Vec3(clamp((1.2-cartBody.velocity.x)*40,-12,50),0,-cartBody.position.z*9-cartBody.velocity.z*2))});
 function tick(dt){if(s.won)return;s.elapsed+=dt;turnLatch=Math.max(0,turnLatch-dt);if(input.pressed.has('Space'))release();if(s.held){move(input.x*2.5*dt,(input.keys.has('KeyE')?1:0)*2*dt-(input.keys.has('KeyJ')?1:0)*2*dt,input.y*2.5*dt);if(input.pressed.has('KeyC'))rotate([0,1,0],Math.PI/12);if(input.pressed.has('KeyR'))rotate([0,1,0],-Math.PI/12);const target=s.hand.position;cursor.velocity.set((target[0]-cursor.position.x)*12,(target[1]-cursor.position.y)*12,(target[2]-cursor.position.z)*12);cursor.quaternion.set(...s.hand.quaternion);dynamic[s.held].body.wakeUp()}else{cursor.velocity.set(0,0,0)}
  if(s.phase==='testing'){cartBody.wakeUp();if(cartBody.position.y<.48||cartBody.position.x>6||Math.abs(cartBody.position.z)>2){s.phase='failed';message('检验车失去支撑。可以保留搭建，调整桥板的位置和角度后再检验。');sfx('hurt')}else if(cartBody.position.x>5.18&&cartBody.position.y>.75){s.won=true;s.phase='won';s.score=Math.max(1000,2200-s.tests*100-Math.floor(s.elapsed));message('通行检验完成：桥板承担了车的重量，配重保持闸门开启。');sfx('success')}}else if(s.phase==='arrange'){cartBody.velocity.x=0;cartBody.velocity.z=0}
  physics.step(BALANCE_RULES.step,Math.min(.08,dt),10);checkSensors(dt);sync();}
 function sync(){for(const {body,mesh} of Object.values(dynamic)){mesh.position.copy(body.position);mesh.quaternion.copy(body.quaternion)}cart.position.copy(cartBody.position);cart.rotation.y=0;door.position.y=2+s.gate*2.7;plate.mesh.material=s.pressure?materials.mint:materials.brass;plateLamp.intensity=s.pressure?1:0;reticle.visible=tether.visible=!!s.held;if(s.held){const body=dynamic[s.held].body;reticle.position.set(...s.hand.position);const a=tether.geometry.attributes.position;a.setXYZ(0,...s.hand.position);a.setXYZ(1,body.position.x,body.position.y,body.position.z);a.needsUpdate=true;tether.geometry.computeBoundingSphere()}
  for(const [id,label] of [['bridge','桥板 · 6 kg'],['weight','配重 · 5 kg'],['plate','压力台 · 5 kg']]){const node=hud.querySelector('[data-label='+id+']'),body=id==='plate'?plate.body:dynamic[id].body,q=projectPoint(camera,{x:body.position.x,y:body.position.y+(id==='bridge'?.4:.65),z:body.position.z});node.style.left=q.x/1120*100+'%';node.style.top=q.y/630*100+'%';node.hidden=!q.visible;node.textContent=label+(s.held===id?' · 抓取中':'')}
  const a=hud.querySelector('[data-check=bridge]'),b=hud.querySelector('[data-check=pressure]'),c=hud.querySelector('[data-check=test]');a.textContent=s.bridge?'✓ 桥板搭稳两岸':'① 桥板搭稳两岸';b.textContent=s.pressure?'✓ 配重压开闸门':'② 配重压开闸门';c.textContent=s.won?'✓ 真实通行完成':s.phase==='testing'?'检验车正在通过':s.phase==='failed'?'检验未通过，可调整':'③ 等待稳定后检验';a.dataset.ok=s.bridge;b.dataset.ok=s.pressure;c.dataset.ok=s.won;hud.querySelector('.bal-end').hidden=!s.won;
 }
 sync();
 return {setActive(value){active=value;if(!active){dragging=false;pointerStart=null}},tick,draw(){sync();view.draw()},getState(){const bodies=Object.fromEntries(Object.entries(dynamic).map(([id,{body}])=>[id,bodySnapshot(body)]));bodies.cart=bodySnapshot(cartBody);return {...structuredClone(s),bodies,physicsTime:physics.time,physicsStep:physics.stepnumber,rules:BALANCE_RULES,objects:Object.entries(dynamic).map(([id,o])=>({id,size:o.size,mass:o.mass,screen:projectPoint(camera,o.body.position)})),plateScreen:projectPoint(camera,plate.body.position),handScreen:s.hand?projectPoint(camera,{x:s.hand.position[0],y:s.hand.position[1],z:s.hand.position[2]}):null,projection:{bridgeTarget:projectPoint(camera,{x:0,y:s.hand?.position[1]||2.1,z:0}),plateTarget:projectPoint(camera,{x:3.25,y:s.hand?.position[1]||2.1,z:-1.75})}}},getStatus(){const held=!!s.held,locked=s.phase==='testing',ready=!held&&s.bridge&&s.pressure&&s.stable>=BALANCE_RULES.stableSeconds;return {goal:s.won?'重量，让道路成立':s.phase==='testing'?'检验车正在实际通过':s.phase==='failed'?'调整结构，再检验一次':'搭桥、压台，让检验车通行',message:s.lastMessage+' 抓取后可拖动或用方向键移动；C / R 转动，E 升高、J 降低，空格放开。按钮同样可以完成全程。',stats:['桥板 '+(s.bridge?'两岸接触':'未搭稳'),'压力台 '+(s.pressure?'有真实接触':'未压下'),'稳定 '+s.stable.toFixed(1)+'s','抓取 '+s.grabs+'次','检验 '+s.tests+'次'],actions:s.won?[action('重新搭建',restart)]:[action('抓取桥板',()=>grab('bridge'),locked),action('抓取配重',()=>grab('weight'),locked),action('左移 0.4 m',()=>move(-.4,0,0),!held||locked),action('右移 0.4 m',()=>move(.4,0,0),!held||locked),action('向后 0.4 m',()=>move(0,0,-.4),!held||locked),action('向前 0.4 m',()=>move(0,0,.4),!held||locked),action('升高 0.35 m',()=>move(0,.35,0),!held||locked),action('降低 0.35 m',()=>move(0,-.35,0),!held||locked),action('左转 15°',()=>rotate([0,1,0],Math.PI/12),!held||locked),action('右转 15°',()=>rotate([0,1,0],-Math.PI/12),!held||locked),action('倾斜 15°',()=>rotate([0,0,1],Math.PI/12),!held||locked),action('放开物体 · 空格',()=>release(),!held||locked),action(s.phase==='failed'?'检验车回到起点':'运行检验车',s.phase==='failed'?retryCar:startTest,s.phase==='failed'?false:!ready||locked),action('重新搭建',restart,locked)]}},dispose(){abort.abort();release(true);hud.remove();view.dispose()}};
}
