import {W,H,images,canvasSurface,clamp} from './showcase-core.js';
import {pointerPosition} from './showcase-precision-kit.js';
import {sceneHeading} from './showcase-observation-kit.js?v=20261004-2';
import {STUDIO_INFO,studioPanel} from './showcase-studio-panel.js';
import {freshStudio,restoreStudio,commandStudio,stepStudio,JIGSAW,BRIDGE_NODES,bridgeSolve,bridgeCost,OPTICS,traceLight,GLASS_CLUES,glassDeduction,ghostPositions} from './showcase-studio-rules.js';
import {ATLAS_BOUNDS} from './showcase-studio-atlas.js';
import {compositionDirector,SCALE} from './showcase-studio-audio.js';
const COLORS=['#80d7c6','#e9ae67','#e37f79','#aac4ed'];
function text(c,t,x,y,size=16,color='#f5e6c4',align='left'){c.save();c.font=`${size}px "Microsoft YaHei",sans-serif`;c.fillStyle=color;c.textAlign=align;c.fillText(t,x,y);c.restore()}
function plate(c,x,y,w,h,color='#0a2029e8'){c.save();c.fillStyle=color;c.strokeStyle='#c0a77a90';c.lineWidth=1;c.shadowColor='#0006';c.shadowBlur=10;c.beginPath();c.roundRect(x,y,w,h,10);c.fill();c.stroke();c.restore()}
function glow(c,x,y,r,color,fill=false){c.save();c.shadowColor=color;c.shadowBlur=16;c.strokeStyle=color;c.fillStyle=color;c.lineWidth=2;c.beginPath();c.arc(x,y,r,0,Math.PI*2);fill?c.fill():c.stroke();c.restore()}
function stamp(c,art,i,x,y,w,h=w,angle=0,alpha=1,stretch=false){const [sx,sy,sw,sh]=ATLAS_BOUNDS[i],scale=Math.min(w/sw,h/sh),dw=stretch?w:sw*scale,dh=stretch?h:sh*scale;c.save();c.translate(x,y);c.rotate(angle);c.globalAlpha=alpha;c.drawImage(art,sx,sy,sw,sh,-dw/2,-dh/2,dw,dh);c.restore()}
export function jigsawPath(c,index){const col=index%4,row=Math.floor(index/4),size=132,half=size/2,flags=[row===0?0:-((row-1+col+1)%2?1:-1),col===3?0:((row+col)%2?1:-1),row===2?0:((row+col+1)%2?1:-1),col===0?0:-((row+col-1)%2?1:-1)],points=[[-half,-half],[half,-half],[half,half],[-half,half],[-half,-half]];
 c.beginPath();c.moveTo(...points[0]);for(let i=0;i<4;i++){const [x,y]=points[i],[ex,ey]=points[i+1],dx=ex-x,dy=ey-y,nx=dy/size,ny=-dx/size,flag=flags[i],p=(t,h=0)=>[x+dx*t+nx*h,y+dy*t+ny*h];if(!flag){c.lineTo(ex,ey);continue;}const h=21*flag;c.lineTo(...p(.36));c.bezierCurveTo(...p(.43),...p(.42,h),...p(.5,h));c.bezierCurveTo(...p(.58,h),...p(.57),...p(.64));c.lineTo(ex,ey)}c.closePath()}
function drawPiece(c,s,art,i){const p=s.pieces[i],scale=p.tray?.49:1;c.save();c.translate(p.x,p.y);c.rotate(p.rotation*Math.PI/2);c.scale(scale,scale);jigsawPath(c,i);c.fillStyle='#f8e2b7';c.shadowColor='#0008';c.shadowBlur=p.locked?2:9;c.shadowOffsetY=3;c.fill();c.shadowBlur=0;c.shadowOffsetY=0;c.save();c.clip();c.drawImage(art.painting,-66-i%4*132,-66-Math.floor(i/4)*132,528,396);c.restore();c.strokeStyle=i===s.selected&&!p.locked?'#fff3ba':p.locked?'#44331977':'#3d352dcc';c.lineWidth=i===s.selected&&!p.locked?3:1.1;c.stroke();c.restore()}
function mosaicHit(c,s,point){for(const i of [...s.order].reverse()){const p=s.pieces[i];if(p.locked)continue;const scale=p.tray?.49:1,angle=-p.rotation*Math.PI/2,dx=(point.x-p.x)/scale,dy=(point.y-p.y)/scale,x=dx*Math.cos(angle)-dy*Math.sin(angle),y=dx*Math.sin(angle)+dy*Math.cos(angle);c.save();c.setTransform(1,0,0,1,0,0);jigsawPath(c,i);const hit=c.isPointInPath(x,y);c.restore();if(hit)return i}return -1}
export function drawStudioScene(c,s,art,clock=0){const info=STUDIO_INFO[s.id];c.drawImage(art[s.id],0,0,W,H);
 if(s.id==='mosaic'){c.save();c.fillStyle='#38534c20';c.fillRect(JIGSAW.x-4,JIGSAW.y-4,536,404);c.strokeStyle='#5c5d4b66';c.setLineDash([3,6]);for(let i=1;i<4;i++){c.beginPath();c.moveTo(JIGSAW.x+i*132,JIGSAW.y);c.lineTo(JIGSAW.x+i*132,JIGSAW.y+396);c.stroke()}for(let i=1;i<3;i++){c.beginPath();c.moveTo(JIGSAW.x,JIGSAW.y+i*132);c.lineTo(JIGSAW.x+528,JIGSAW.y+i*132);c.stroke()}c.restore();if(s.reference){c.save();c.globalAlpha=.28;c.drawImage(art.painting,JIGSAW.x,JIGSAW.y,528,396);c.restore()}for(const i of s.order.filter(i=>s.pieces[i].locked))drawPiece(c,s,art,i);for(const i of s.order.filter(i=>!s.pieces[i].locked))drawPiece(c,s,art,i);plate(c,306,526,406,47,'#f2e6caee');text(c,`拼合 ${s.pieces.filter(p=>p.locked).length}/12 · 选中拼片 ${s.selected+1}`,509,557,16,'#29453f','center');}
 if(s.id==='span'){const solve=s.solution||null,positions=solve?.stable?solve.positions:BRIDGE_NODES;
 s.edges.forEach((e,i)=>{const a=positions[e.a],b=positions[e.b],length=Math.hypot(b.x-a.x,b.y-a.y),angle=Math.atan2(b.y-a.y,b.x-a.x);stamp(c,art.props,e.material==='wood'?2:3,(a.x+b.x)/2,(a.y+b.y)/2,length+14,e.material==='deck'?15:11,angle,1,true);if(s.running&&solve?.forces[i]?.ratio>.75){c.save();c.strokeStyle=solve.forces[i].ratio>1?'#ed5149':'#ffe08a';c.lineWidth=3;c.beginPath();c.moveTo(a.x,a.y);c.lineTo(b.x,b.y);c.stroke();c.restore()}});
 BRIDGE_NODES.forEach((n,i)=>{const p=positions[i];if(n.fixed)stamp(c,art.props,1,p.x,p.y+8,43);glow(c,p.x,p.y,s.selected===i?13:7,s.selected===i?'#ffefb1':'#234450',true);text(c,String(i+1),p.x,p.y-18,12,'#183f40','center')});
 let y=229;if(s.car>=320&&s.car<=800&&solve?.stable){const z=(s.car-320)/96,i=Math.min(4,Math.floor(z));y=positions[i].y*(1-(z-i))+positions[i+1].y*(z-i)-26}stamp(c,art.props,0,s.car,y+s.fall,88,68,s.failed?Math.min(.75,s.fall*.005):0);plate(c,366,465,390,89);text(c,'二维桁架 · 变形放大 8 倍',561,491,13,'#d0dfd2','center');text(c,`预算 ${bridgeCost(s)}/540 · ${s.failed?'结构失效':s.running?'实车加载中':s.won?'已通过测试':'等待承重测试'}`,561,518,17,'#ffe1a0','center');text(c,solve?.stable?`强度使用 ${Math.round(s.stress*100)}% · 挠度 ${s.deflection.toFixed(2)}`:'上下层交叉连接，并连接上层节点',561,540,13,'#b8ddd5','center');}
 if(s.id==='lumen'){const level=OPTICS[s.level],ray=traceLight(s);for(const w of level.walls){plate(c,w.x,w.y,w.w,w.h,'#253940');text(c,'遮光石',w.x+w.w/2,w.y+w.h/2+5,13,'#bdd0cb','center')}stamp(c,art.props,6,level.source.x-20,level.source.y,70);stamp(c,art.props,5,level.receiver.x,level.receiver.y,78);if(ray.reached)glow(c,level.receiver.x,level.receiver.y,45,'#ffe99e');
 level.mirrors.forEach((m,i)=>{stamp(c,art.props,4,m.x,m.y,89);c.save();c.translate(m.x,m.y);c.rotate(s.angles[i]*Math.PI/4);c.shadowColor='#b9e8ec';c.shadowBlur=8;c.strokeStyle='#f3e3ad';c.lineWidth=6;c.beginPath();c.moveTo(-38,0);c.lineTo(38,0);c.stroke();c.strokeStyle='#73c9da';c.lineWidth=2;c.beginPath();c.moveTo(-38,-3);c.lineTo(38,-3);c.stroke();c.restore();if(i===s.selected)glow(c,m.x,m.y,51,'#caaf69');text(c,String(i+1),m.x,m.y+66,14,'#f2dba8','center')});
 let travelled=0;for(const seg of ray.segments){const len=Math.hypot(seg.b.x-seg.a.x,seg.b.y-seg.a.y);c.save();c.strokeStyle='#ffd97a';c.shadowColor='#ffcf69';c.shadowBlur=15;c.lineWidth=3;c.beginPath();c.moveTo(seg.a.x,seg.a.y);c.lineTo(seg.b.x,seg.b.y);c.stroke();c.strokeStyle='#fff6c9';c.shadowBlur=0;c.lineWidth=1;c.stroke();c.restore();for(let t=0;t<len;t+=52){const distance=(t+clock*110+travelled)%len,ratio=distance/len;glow(c,seg.a.x+(seg.b.x-seg.a.x)*ratio,seg.a.y+(seg.b.y-seg.a.y)*ratio,2.5,'#fff6c9',true)}travelled+=len}plate(c,330,544,460,51);text(c,`镜庭 ${s.level+1}/2 · ${s.completed>s.level?(s.level===0?'本片接通，进入下一片':'两片镜庭全部接通'):ray.reached?'稳定照射 '+Math.min(100,Math.round(s.lit/1.4*100))+'%':'旋转镜面，让光绕过遮挡'}`,560,576,15,'#f5e1aa','center');}
 if(s.id==='sonata'){const x=223,y=219,size=43,gap=2,names=['旋律','低音','鼓点','晶铃'];plate(c,177,155,767,297,'#071821b5');for(let tr=0;tr<4;tr++){text(c,names[tr],204,y+tr*53+27,13,COLORS[tr],'right');for(let k=0;k<16;k++){const xx=x+k*size,yy=y+tr*53,v=s.pattern[tr][k];c.save();c.fillStyle=v>=0?COLORS[tr]:'#203439cc';c.globalAlpha=v>=0?.8:1;c.beginPath();c.roundRect(xx+gap,yy,size-gap*2,43,5);c.fill();c.restore();if(v>=0)text(c,tr<2?['C','D','E','G','A','C','D','E'][v]+(tr===0?(v<5?4:5):(v<5?2:3)):'●',xx+size/2,yy+28,12,'#102d31','center');if(s.selected.track===tr&&s.selected.step===k){c.save();c.strokeStyle='#fff4ca';c.lineWidth=2;c.strokeRect(xx+1,yy-1,size-2,45);c.restore();}if(s.playing&&s.step===k){c.save();c.fillStyle='#ffefb31f';c.fillRect(xx,y-26,size,232);c.restore();}}glow(c,924,y+tr*53+23,5+5*s.pulse[tr],COLORS[tr],true)}for(let k=0;k<16;k++)text(c,k%4===0?String(k/4+1):'·',x+k*size+size/2,196,14,k%4===0?'#e9d29b':'#709894','center');plate(c,329,476,462,69);text(c,`${s.bpm} BPM · ${s.playing?'实时试听':'创作模式'} · 试听 ${Math.min(2,s.loops)}/2 轮`,560,503,18,'#f3d89b','center');text(c,'点击网格作曲 · 三音轨 / 六音符 · 可以导出 WAV',560,528,13,'#b2d5c8','center');}
 if(s.id==='afterimage'){const actors=[s.p,...ghostPositions(s)],on=[350,630].map(x=>actors.some(p=>Math.abs(p.x-x)<27));[350,630].forEach((x,i)=>{stamp(c,art.props,7,x,451,74,40);if(on[i])glow(c,x,446,27,'#8ef0d6');text(c,i===0?'机关 A':'机关 B',x,497,14,on[i]?'#8fefd6':'#f7e0aa','center')});stamp(c,art.props,s.open?11:10,865,389,139,143);text(c,s.open?'时间门已开启':'同时压住 A 与 B',858,526,14,'#eddda9','center');s.ghosts.forEach((g,i)=>{const p=ghostPositions(s)[i];c.save();c.strokeStyle=i?'#e6bda060':'#90e8e24d';c.setLineDash([2,6]);c.beginPath();g.forEach((v,j)=>j?c.lineTo(v.x,v.y):c.moveTo(v.x,v.y));c.stroke();c.restore();stamp(c,art.props,9,p.x,p.y-39,95,101,0,.68);text(c,'回放 '+(i+1),p.x,p.y-102,13,'#a5e5df','center')});stamp(c,art.props,8,s.p.x,s.p.y-39,95,101);if(s.recording)glow(c,s.p.x,s.p.y-90,6,'#e76864',true);glow(c,1014,423,27,'#a7dacf');plate(c,360,548,404,45);text(c,s.recording?`录制中 ${(s.take.length/30).toFixed(1)}/12 秒 · 到机关上结束`:`动作分身 ${s.ghosts.length}/2 · 同时保持 ${Math.min(1.5,s.hold).toFixed(1)} 秒`,562,577,15,'#e9dfbc','center');}
 if(s.id==='weave'){const x=337,y=174,size=43,d=glassDeduction(s.cells),badRow=new Set(d.bad.filter(v=>!v.axis).map(v=>v.i)),badCol=new Set(d.bad.filter(v=>v.axis).map(v=>v.i));plate(c,x-102,y-86,454,437,'#0b2430d9');for(let r=0;r<8;r++){text(c,GLASS_CLUES.rows[r].join(' '),x-18,y+r*size+28,17,badRow.has(r)?'#ff9c8d':'#f6d9a5','right');for(let col=0;col<8;col++){const i=r*8+col,xx=x+col*size,yy=y+r*size;c.save();c.fillStyle=s.cells[i]===1?['#82d2c8','#4d9faf','#9adfd1','#c3b177'][(r+col)%4]:'#173441';c.beginPath();c.roundRect(xx+1,yy+1,size-2,size-2,4);c.fill();if(s.cells[i]===1){const g=c.createLinearGradient(xx,yy,xx+size,yy+size);g.addColorStop(0,'#e5ffec55');g.addColorStop(.48,'#d0fff50a');g.addColorStop(1,'#0b444c55');c.fillStyle=g;c.fill();}if(s.cells[i]===2){c.strokeStyle='#6b9b9f';c.lineWidth=1.4;c.beginPath();c.moveTo(xx+15,yy+15);c.lineTo(xx+size-15,yy+size-15);c.moveTo(xx+size-15,yy+15);c.lineTo(xx+15,yy+size-15);c.stroke()}if(s.selected===i||s.hint?.index===i){c.strokeStyle=s.hint?.index===i?'#ffe393':'#fff4d5';c.lineWidth=2;c.strokeRect(xx+2,yy+2,size-4,size-4)}c.restore()}}for(let col=0;col<8;col++)GLASS_CLUES.cols[col].forEach((v,k)=>text(c,String(v),x+(col+.5)*size,y-16-(GLASS_CLUES.cols[col].length-1-k)*22,17,badCol.has(col)?'#ff9c8d':'#f6d9a5','center'));stamp(c,art.props,12,969,257,s.won?147:79,undefined,0,s.won?1:.28);text(c,s.won?'光晶已显露':'交叉推理',969,369,19,'#426a67','center');text(c,'行列数字相互印证',969,400,11,'#626750','center');text(c,'填色 ■    空格 ×',969,435,13,'#426a67','center');plate(c,322,542,443,45);text(c,`已判定 ${s.cells.filter(Boolean).length}/64 · ${d.bad.length?'存在 '+d.bad.length+' 条矛盾线索':'线索一致'}`,543,571,15,'#e7dbb5','center');}
 sceneHeading(c,info.title,info.detail);if(s.won){plate(c,302,581,516,40);text(c,s.id==='sonata'?'作品已试听两轮 · 可继续创作或导出':s.message,560,607,16,'#ffe7a4','center');}
}
export async function createStudio({host,input,saved,id,sfx=()=>{},getSound=()=>false,notify=()=>{}}){const art=await images([id,'props',...(id==='mosaic'?['painting']:[])],'assets/game-forms/studio/'),{element,ctx}=canvasSurface(host);element.style.touchAction='none';element.setAttribute('aria-label',STUDIO_INFO[id].title+'。'+STUDIO_INFO[id].help);let s=restoreStudio(id,saved),active=false,clock=0,drag=null,painting=false,repeat=0;const held=new Set(),events=new AbortController(),audio=id==='sonata'?compositionDirector(getSound,notify):null;
 function stats(){if(id==='mosaic')return [`拼合 ${s.pieces.filter(v=>v.locked).length}/12`,`选中 ${s.selected+1}`];if(id==='span')return [`杆件 ${s.edges.length}`,`预算 ${bridgeCost(s)}/540`,s.failed?'需要加固':s.running?'邮车加载':'建造模式'];if(id==='lumen')return [`接通镜庭 ${s.completed}/2`,`选中镜面 ${s.selected+1}`];if(id==='sonata')return [`${s.bpm} BPM`,`音符 ${s.pattern.flat().filter(v=>v>=0).length}`,getSound()?'声音已开启':'声音关闭',s.playing?'正在试听':'等待试听'];if(id==='afterimage')return [`分身 ${s.ghosts.length}/2`,s.recording?`录制 ${(s.take.length/30).toFixed(1)} 秒`:s.open?'时间门开启':'协作保持 1.5 秒'];return [`已判定 ${s.cells.filter(Boolean).length}/64`,['擦除','填色','划空'][s.brush],`第 ${Math.floor(s.selected/8)+1} 行 ${s.selected%8+1} 列`]}
 const sync=()=>ui.sync(active,s,stats());function run(value,override){if(!active)return false;let [key,arg]=value.split(':'),v=override??(arg!==undefined&&Number.isFinite(Number(arg))?Number(arg):arg);if(key==='restart'){s=freshStudio(id);held.clear();drag=null;painting=false;audio?.tick(s);sync();return true;}if(id==='mosaic'&&['previous','next-piece'].includes(key)){key='select';v=(s.selected+(value==='previous'?-1:1)+12)%12;}if(id==='sonata'&&key==='tempo')v=s.bpm+v;if(key==='export'){audio?.export(s);s.message='作品 WAV 已导出。';return true;}const ok=commandStudio(s,key,v);if(ok&&id!=='sonata')sfx('turn');sync();return ok}
 const ui=studioPanel(host,id,run,(key,v)=>v?held.add(key):held.delete(key)),point=e=>pointerPosition(element,e),glassCell=p=>p.x>=337&&p.x<681&&p.y>=174&&p.y<518?Math.floor((p.y-174)/43)*8+Math.floor((p.x-337)/43):-1;
 function musicCell(p){const step=Math.floor((p.x-223)/43),track=Math.floor((p.y-219)/53);return step>=0&&step<16&&track>=0&&track<4&&(p.y-219)%53<43?{track,step}:null}
 element.addEventListener('pointerdown',e=>{if(!active||s.won&&id!=='sonata')return;const p=point(e);element.focus();element.setPointerCapture(e.pointerId);if(id==='mosaic'){const i=mosaicHit(ctx,s,p);if(i>=0){run('select',i);const piece=s.pieces[i];drag=piece.tray?{dx:0,dy:0}:{dx:piece.x-p.x,dy:piece.y-p.y};run('move',{x:p.x+drag.dx,y:p.y+drag.dy})}}if(id==='span'){let i=-1,dist=24;BRIDGE_NODES.forEach((n,k)=>{const d=Math.hypot(n.x-p.x,n.y-p.y);if(d<dist){i=k;dist=d}});if(i>=0)run('node',i)}if(id==='lumen'){const i=OPTICS[s.level].mirrors.findIndex(m=>Math.hypot(m.x-p.x,m.y-p.y)<52);if(i>=0)run('select',i)}if(id==='sonata'){const v=musicCell(p);if(v){run('select',v);run('toggle')}}if(id==='weave'){const i=glassCell(p);if(i>=0){painting=true;run('mark',i)}}},{signal:events.signal});
 element.addEventListener('pointermove',e=>{if(!active)return;const p=point(e);if(drag)run('move',{x:p.x+drag.dx,y:p.y+drag.dy});if(painting){const i=glassCell(p);if(i>=0)run('mark',i)}},{signal:events.signal});element.addEventListener('pointerup',()=>{if(active&&drag)run('release');drag=null;painting=false},{signal:events.signal});for(const n of ['pointercancel','lostpointercapture'])element.addEventListener(n,()=>{drag=null;painting=false},{signal:events.signal});window.addEventListener('blur',()=>{held.clear();drag=null;painting=false},{signal:events.signal});
 host.closest('.play-mount').addEventListener('keydown',e=>{if(e.code==='KeyQ'&&!e.repeat){e.preventDefault();if(active)run(id==='sonata'?'pitch:-1':'rotate:-1')}},{signal:events.signal});
 function nudge(dx,dy){if(id==='mosaic'){const p=s.pieces[s.selected];run('move',{x:p.x+dx*12,y:p.y+dy*12})}if(id==='sonata')run('select',{track:clamp(s.selected.track+dy,0,3),step:clamp(s.selected.step+dx,0,15)});if(id==='weave')run('select',clamp(Math.floor(s.selected/8)+dy,0,7)*8+clamp(s.selected%8+dx,0,7))}
 sync();return {onStart(){active=true;audio?.start();audio?.setActive(true);sync()},setActive(v){if(active===v)return;active=v;audio?.setActive(v);if(!active){held.clear();drag=null;painting=false;}sync()},tick(dt){if(!active)return;dt=clamp(Number.isFinite(dt)?dt:0,0,.08);clock+=dt;const dx=clamp((input.x||0)+(held.has('right')?1:0)-(held.has('left')?1:0),-1,1),dy=clamp((input.y||0)+(held.has('down')?1:0)-(held.has('up')?1:0),-1,1);if(!s.won||id==='sonata'){repeat-=dt;if(id!=='afterimage'&&repeat<=0&&(dx||dy)){nudge(dx?Math.sign(dx):0,dx?0:Math.sign(dy));repeat=.13;}if(input.pressed.has('Space'))run(id==='mosaic'?'release':id==='sonata'?'toggle':id==='weave'?'mark':id==='span'?'test':id==='afterimage'?(s.recording?'stop':'record'):'rotate:1');if(input.pressed.has('KeyQ'))run(id==='sonata'?'pitch:-1':'rotate:-1');if(input.pressed.has('KeyE'))run(id==='sonata'?'pitch:1':'rotate:1');}const won=s.won;stepStudio(s,dt,{x:dx});audio?.tick(s);if(!won&&s.won)sfx('success');sync()},draw(){drawStudioScene(ctx,s,art,clock)},getState(){const copy=structuredClone(s);if(id==='span'){copy.solution=null;copy.stress=Number.isFinite(copy.stress)?copy.stress:0;copy.deflection=Number.isFinite(copy.deflection)?copy.deflection:0;}return copy},getStatus(){return {goal:s.won?STUDIO_INFO[id].title+' · 本段完成':STUDIO_INFO[id].goal,message:s.message||STUDIO_INFO[id].help,stats:stats(),actions:[]}},dispose(){active=false;events.abort();held.clear();audio?.dispose();ui.dispose()}};
}
