export const W=1120,H=630;
export const clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
export const distance=(a,b)=>Math.hypot(a.x-b.x,a.y-b.y);
export function hash(seed){let x=seed|0;return ()=>{x^=x<<13;x^=x>>>17;x^=x<<5;return (x>>>0)/4294967296}}
export function image(url){return new Promise((resolve,reject)=>{const im=new Image();im.onload=()=>resolve(im);im.onerror=()=>reject(new Error('素材未能加载：'+url));im.src=url})}
export async function images(names,base='assets/showcase/'){const out={};await Promise.all(names.map(async n=>{out[n]=await image(base+n+'.webp')}));return out}
export function canvasSurface(host){const element=document.createElement('canvas');element.width=W;element.height=H;element.tabIndex=0;element.className='play-canvas';element.setAttribute('aria-label','游戏场景，操作说明在画面下方');host.append(element);const ctx=element.getContext('2d',{alpha:false});return {element,ctx}}
export function cover(ctx,img,x=0,y=0,w=W,h=H){const ratio=Math.max(w/img.width,h/img.height),iw=img.width*ratio,ih=img.height*ratio;ctx.drawImage(img,x+(w-iw)/2,y+(h-ih)/2,iw,ih)}
export function sprite(ctx,img,x,y,height,flip=false,alpha=1){const width=height*img.width/img.height;ctx.save();ctx.globalAlpha=alpha;ctx.translate(x,y);if(flip)ctx.scale(-1,1);ctx.drawImage(img,-width/2,-height,width,height);ctx.restore()}
export function shadow(ctx,x,y,r=23){ctx.save();ctx.fillStyle='rgba(0,0,0,.35)';ctx.beginPath();ctx.ellipse(x,y+2,r,r*.24,0,0,Math.PI*2);ctx.fill();ctx.restore()}
export function glow(ctx,x,y,r,color){const g=ctx.createRadialGradient(x,y,0,x,y,r);g.addColorStop(0,color);g.addColorStop(1,'transparent');ctx.fillStyle=g;ctx.fillRect(x-r,y-r,r*2,r*2)}
export function label(ctx,text,x,y,color='#f2e6d1',size=17){ctx.save();ctx.font=`${size}px "Microsoft YaHei", sans-serif`;ctx.textAlign='center';ctx.fillStyle='rgba(10,15,20,.75)';const m=ctx.measureText(text).width;ctx.fillRect(x-m/2-12,y-size-8,m+24,size+17);ctx.fillStyle=color;ctx.fillText(text,x,y);ctx.restore()}
export function vignette(ctx){const g=ctx.createRadialGradient(W/2,H/2,180,W/2,H/2,650);g.addColorStop(0,'transparent');g.addColorStop(1,'rgba(3,6,12,.68)');ctx.fillStyle=g;ctx.fillRect(0,0,W,H)}
export function bindInput(element){const keys=new Set(),pressed=new Set(),pointers=[];const controller=new AbortController(),signal=controller.signal;let drag=null,look={x:0,y:0},hover=null;
 element.addEventListener('keydown',e=>{if(e.target.closest('button,input,select'))return;if(['ArrowUp','ArrowDown','ArrowLeft','ArrowRight','Space','KeyW','KeyA','KeyS','KeyD','KeyE','KeyJ','KeyR','KeyF','KeyC'].includes(e.code)){e.preventDefault();keys.add(e.code);if(!e.repeat)pressed.add(e.code)}},{signal});
 window.addEventListener('keyup',e=>keys.delete(e.code),{signal});window.addEventListener('blur',()=>{keys.clear();pressed.clear()},{signal});
 element.addEventListener('pointerdown',e=>{if(e.target.tagName!=='CANVAS')return;element.focus({preventScroll:true});e.target.setPointerCapture(e.pointerId);drag={x:e.clientX,y:e.clientY,dist:0};},{signal});
 element.addEventListener('pointermove',e=>{if(e.target.tagName==='CANVAS'){const r=e.target.getBoundingClientRect(),scale=Math.min(r.width/e.target.width,r.height/e.target.height),cw=e.target.width*scale,ch=e.target.height*scale;hover={x:(e.clientX-r.left-(r.width-cw)/2)/cw*W,y:(e.clientY-r.top-(r.height-ch)/2)/ch*H}}else hover=null;if(!drag)return;const dx=e.clientX-drag.x,dy=e.clientY-drag.y;look.x+=dx;look.y+=dy;drag.dist+=Math.abs(dx)+Math.abs(dy);drag.x=e.clientX;drag.y=e.clientY},{signal});
 element.addEventListener('pointerleave',()=>hover=null,{signal});
 element.addEventListener('pointerup',e=>{if(e.target.tagName==='CANVAS'&&drag&&drag.dist<8){const r=e.target.getBoundingClientRect(),scale=Math.min(r.width/e.target.width,r.height/e.target.height),cw=e.target.width*scale,ch=e.target.height*scale,ox=(r.width-cw)/2,oy=(r.height-ch)/2;pointers.push({x:(e.clientX-r.left-ox)/cw*W,y:(e.clientY-r.top-oy)/ch*H})}drag=null},{signal});element.addEventListener('pointercancel',()=>drag=null,{signal});
 return {keys,pressed,pointers,look,get hover(){return hover},get x(){return (keys.has('KeyD')||keys.has('ArrowRight')?1:0)-(keys.has('KeyA')||keys.has('ArrowLeft')?1:0)},get y(){return (keys.has('KeyS')||keys.has('ArrowDown')?1:0)-(keys.has('KeyW')||keys.has('ArrowUp')?1:0)},clear(){pressed.clear();pointers.length=0;look.x=look.y=0},release(){keys.clear();pressed.clear();drag=null;hover=null},dispose(){controller.abort();keys.clear()}};
}
export function cardButton(title,detail,onClick,disabled=false){const b=document.createElement('button');b.type='button';b.className='game-choice';const t=document.createElement('b'),s=document.createElement('span');t.textContent=title;s.textContent=detail;b.append(t,s);b.disabled=disabled;b.onclick=onClick;return b}
export function action(label,run,disabled=false){return {label,run,disabled}}
export function safeSaved(raw,defaults){if(!raw||typeof raw!=='object')return structuredClone(defaults);const s={...structuredClone(defaults),...raw};for(const [key,value] of Object.entries(defaults)){if(typeof value==='number'&&!Number.isFinite(s[key]))s[key]=value}return s}
