import {W,H,clamp,images,canvasSurface,cover,action} from './showcase-core.js';

export const CHAIN_SPACING=35,CHAIN_RADIUS=16.4,CHAIN_LAUNCHER={x:560,y:365};
const SPEED=13,CLOSE_SPEED=190,SEED=20261004,ORB_NAMES=['ruby','amber','cyan','violet','jade'];
const COLORS=['#ff8171','#ffd16b','#8ceafa','#d9a3fc','#a2ed97'],NAMES=['赤晶 △','金晶 ◇','月晶 ☾','星晶 ☆','翠晶 ○'];
const CONTROL_POINTS=[[86,354],[160,446],[263,491],[365,484],[417,428],[378,351],[272,318],[199,258],[214,195],[298,163],[792,163],[900,195],[929,276],[904,326],[844,340],[796,300],[735,260],[651,237],[488,233],[419,276],[420,340],[478,418],[607,469],[808,481],[934,470],[1006,447]];
function makePath(){const out=[],p=CONTROL_POINTS.map(([x,y])=>({x,y}));for(let i=0;i<p.length-1;i++){const a=p[Math.max(0,i-1)],b=p[i],c=p[i+1],d=p[Math.min(p.length-1,i+2)];for(let j=0;j<36;j++){const t=j/36,t2=t*t,t3=t2*t;out.push({x:.5*(2*b.x+(-a.x+c.x)*t+(2*a.x-5*b.x+4*c.x-d.x)*t2+(-a.x+3*b.x-3*c.x+d.x)*t3),y:.5*(2*b.y+(-a.y+c.y)*t+(2*a.y-5*b.y+4*c.y-d.y)*t2+(-a.y+3*b.y-3*c.y+d.y)*t3)})}}out.push(p.at(-1));let length=0;out.forEach((v,i)=>{if(i)length+=Math.hypot(v.x-out[i-1].x,v.y-out[i-1].y);v.d=length});return out}
const ROUTE=makePath();export const CHAIN_LENGTH=ROUTE.at(-1).d;
export function chainPoint(distance){const d=clamp(distance,0,CHAIN_LENGTH);let lo=0,hi=ROUTE.length-1;while(hi-lo>1){const mid=(lo+hi)>>1;if(ROUTE[mid].d<d)lo=mid;else hi=mid}const a=ROUTE[lo],b=ROUTE[hi],f=(d-a.d)/Math.max(.001,b.d-a.d),dx=b.x-a.x,dy=b.y-a.y,l=Math.hypot(dx,dy)||1;return {x:a.x+dx*f,y:a.y+dy*f,tx:dx/l,ty:dy/l}}
function random(s){let x=s.rng|0;x^=x<<13;x^=x>>>17;x^=x<<5;s.rng=x>>>0;return s.rng/4294967296}
function ammo(s){const counts=Array(5).fill(0);s.balls.forEach(b=>counts[b.c]++);const allowed=counts.map((n,c)=>({n,c})).filter(v=>v.n);if(!allowed.length)return 0;let pick=random(s)*allowed.reduce((n,v)=>n+v.n,0);for(const v of allowed){pick-=v.n;if(pick<0)return v.c}return allowed.at(-1).c}
export function chainFresh(){const balls=[];for(let i=0;i<34;i++)balls.push({id:i+1,c:Math.floor(i/2)%5,pos:150+i*CHAIN_SPACING});return {version:1,rng:SEED,nextId:35,balls,shots:[],phase:'playing',angle:-Math.PI/2,loaded:1,next:2,cooldown:0,elapsed:0,score:0,removed:0,fired:0,missed:0,swaps:0,combo:0,maxCombo:0,lastClear:0,won:false,message:'瞄准珠链中的一对同色晶球，点画面发射；三枚相连会消除，断开的珠链将回拢。'}}
export function chainRestore(raw){const fresh=chainFresh();if(!raw||raw.version!==1||!Array.isArray(raw.balls)||raw.balls.length>160||!Array.isArray(raw.shots)||raw.shots.length>8)return fresh;const s=structuredClone(raw);if(!['playing','won','lost'].includes(s.phase)||!s.balls.every(b=>b&&Number.isInteger(b.id)&&b.id>0&&Number.isInteger(b.c)&&b.c>=0&&b.c<5&&Number.isFinite(b.pos)&&b.pos>=0&&b.pos<=CHAIN_LENGTH+CHAIN_SPACING*2))return fresh;if(new Set(s.balls.map(b=>b.id)).size!==s.balls.length||s.phase==="playing"&&!s.balls.length||s.phase==="won"&&s.balls.length)return fresh;for(let i=1;i<s.balls.length;i++)if(s.balls[i].pos-s.balls[i-1].pos<CHAIN_SPACING-.1)return fresh;for(const k of ['rng','nextId','cooldown','elapsed','score','removed','fired','missed','swaps','combo','maxCombo','lastClear'])if(!Number.isFinite(s[k])||s[k]<0)return fresh;if(!Number.isFinite(s.angle)||![s.loaded,s.next].every(c=>Number.isInteger(c)&&c>=0&&c<5))return fresh;if(!s.shots.every(b=>b&&Number.isInteger(b.c)&&b.c>=0&&b.c<5&&['x','y','vx','vy','age'].every(k=>Number.isFinite(b[k]))&&b.age>=0&&b.age<=3&&Math.abs(b.vx)<=1200&&Math.abs(b.vy)<=1200))return fresh;s.rng=(s.rng>>>0)||SEED;s.nextId=Math.max(Math.floor(s.nextId),1,...s.balls.map(b=>b.id+1));s.cooldown=clamp(s.cooldown,0,.45);s.angle=Math.atan2(Math.sin(s.angle),Math.cos(s.angle));s.won=s.phase==='won';s.message=typeof s.message==='string'?s.message.slice(0,240):fresh.message;s.shots=s.shots.map(b=>({...b,trail:[]}));return {...fresh,...s}}
export function chainMatches(balls,index){if(!balls[index])return [];let a=index,b=index;while(a>0&&balls[a-1].c===balls[index].c&&balls[a].pos-balls[a-1].pos<=CHAIN_SPACING+.65)a--;while(b<balls.length-1&&balls[b+1].c===balls[index].c&&balls[b+1].pos-balls[b].pos<=CHAIN_SPACING+.65)b++;return b-a+1>=3?Array.from({length:b-a+1},(_,i)=>a+i):[]}
function clear(s,cells,combo=1){if(!cells.length)return null;const removed=cells.map(i=>({...s.balls[i]})),set=new Set(cells);s.balls=s.balls.filter((_,i)=>!set.has(i));s.removed+=cells.length;s.score+=cells.length*120*combo;s.combo=combo;s.maxCombo=Math.max(s.maxCombo,combo);s.lastClear=cells.length;s.message=combo>1?'回拢连锁 × '+combo+' · '+cells.length+' 枚晶球共鸣。':'同色共鸣 · '+cells.length+' 枚晶球已消除。';if(!s.balls.length){s.phase='won';s.won=true;s.shots=[];s.message='回廊已被点亮。所有琉璃晶球都已归入星图。'}return {type:'clear',balls:removed,combo,won:s.won}}
export function chainInsert(s,index,color,ahead=true){if(s.phase!=='playing'||!s.balls[index]||!Number.isInteger(color)||color<0||color>4)return null;const slot=index+(ahead?1:0),pos=s.balls[index].pos+(ahead?CHAIN_SPACING:0),ball={id:s.nextId++,c:color,pos};s.balls.splice(slot,0,ball);for(let i=slot+1;i<s.balls.length;i++)s.balls[i].pos=Math.max(s.balls[i].pos,s.balls[i-1].pos+CHAIN_SPACING);const cells=chainMatches(s.balls,slot),event=clear(s,cells,1);if(!event){s.combo=0;s.message='晶球已接入珠链 · 继续寻找三枚同色相连。'}return event||{type:'insert',id:ball.id,index:slot}}
function segmentDistance(p,a,b){const dx=b.x-a.x,dy=b.y-a.y,t=clamp(((p.x-a.x)*dx+(p.y-a.y)*dy)/(dx*dx+dy*dy||1),0,1);return {d:Math.hypot(p.x-a.x-dx*t,p.y-a.y-dy*t),t}}
export function chainFire(s){if(s.phase!=='playing'||s.cooldown>0)return false;const {x,y}=CHAIN_LAUNCHER,dx=Math.cos(s.angle),dy=Math.sin(s.angle);s.shots.push({x:x+dx*52,y:y+dy*52,vx:dx*850,vy:dy*850,c:s.loaded,age:0,trail:[]});s.fired++;s.cooldown=.36;s.loaded=s.next;s.next=ammo(s);return true}
export function chainSwap(s){if(s.phase!=='playing')return false;[s.loaded,s.next]=[s.next,s.loaded];s.swaps++;s.message='当前晶球与下一枚已交换。';return true}
export function chainStep(s,dt){const events=[];if(s.phase!=='playing')return events;dt=clamp(dt,0,.05);s.elapsed+=dt;s.cooldown=Math.max(0,s.cooldown-dt);
 let gap=-1;for(let i=1;i<s.balls.length;i++)if(s.balls[i].pos-s.balls[i-1].pos>CHAIN_SPACING+.65){gap=i;break}if(gap>0){const delta=Math.min(CLOSE_SPEED*dt,s.balls[gap].pos-s.balls[gap-1].pos-CHAIN_SPACING);for(let i=0;i<gap;i++)s.balls[i].pos+=delta;if(s.balls[gap].pos-s.balls[gap-1].pos<=CHAIN_SPACING+.65){const cells=chainMatches(s.balls,gap);if(cells.length){const e=clear(s,cells,Math.max(1,s.combo)+1);if(e)events.push(e)}else s.combo=0}}else s.balls.forEach(b=>b.pos+=SPEED*dt);
 if(s.phase!=='playing')return events;const remaining=[];for(const shot of s.shots){const prev={x:shot.x,y:shot.y};shot.x+=shot.vx*dt;shot.y+=shot.vy*dt;shot.age+=dt;shot.trail.push(prev);shot.trail=shot.trail.slice(-7);let hit=-1,best=2;for(let i=0;i<s.balls.length;i++){const p=chainPoint(s.balls[i].pos),d=segmentDistance(p,prev,shot);if(d.d<CHAIN_RADIUS*1.85&&d.t<best){best=d.t;hit=i}}if(hit>=0){const p=chainPoint(s.balls[hit].pos),ix=prev.x+(shot.x-prev.x)*best,iy=prev.y+(shot.y-prev.y)*best,ahead=(ix-p.x)*p.tx+(iy-p.y)*p.ty>=0,event=chainInsert(s,hit,shot.c,ahead);if(event)events.push(event)}else if(shot.age>2||shot.x<-40||shot.x>W+40||shot.y<-40||shot.y>H+40){s.missed++;events.push({type:'miss',x:shot.x,y:shot.y})}else remaining.push(shot)}s.shots=s.phase==='playing'?remaining:[];if(s.balls.at(-1)?.pos>=CHAIN_LENGTH-2){s.phase='lost';s.won=false;s.shots=[];s.message='晶球抵达了暗门。已点亮 '+s.removed+' 枚，重新开启回廊再试一次。';events.push({type:'lost'})}return events}

export async function createChain({host,input,saved,notify=()=>{},sfx=()=>{},getSound=()=>false}){
 const art=await images(['observatory','launcher',...ORB_NAMES],'assets/game-forms/chain/'),{element,ctx}=canvasSurface(host),controller=new AbortController();let s=chainRestore(saved),active=false,particles=[],rings=[],floatText=[],recoil=0,visualTime=0,lastAmmo='',visualPositions=new Map(s.balls.map(b=>[b.id,b.pos]));
 element.setAttribute('aria-label','琉光回廊。移动指针或拖动瞄准，点击画面发射晶球。三枚同色相连会消除，回拢后再次成线可连锁。左右方向键瞄准，空格发射，C 键交换当前与下一枚。');element.style.touchAction='none';
 const controls=document.createElement('div');controls.className='chain-controls';controls.innerHTML='<style>.chain-controls{display:flex;gap:10px;align-items:center;justify-content:space-between;padding:12px 16px;margin-top:8px;border:1px solid #86704470;border-radius:8px;background:linear-gradient(110deg,#112538,#081722);color:#e7e2d5;font:14px "Microsoft YaHei",sans-serif}.chain-controls .chain-readout{display:flex;gap:16px;align-items:center;flex-wrap:wrap}.chain-controls .chain-ammo{display:flex;align-items:center;gap:6px}.chain-controls img{width:30px;height:30px;object-fit:contain}.chain-controls .chain-next{opacity:.74}.chain-controls .chain-buttons{display:flex;gap:8px}.chain-controls button{min-width:90px;min-height:46px;border:1px solid #b69762;border-radius:6px;padding:8px 14px;background:#203748;color:#f6ead1;font:600 14px "Microsoft YaHei",sans-serif;cursor:pointer}.chain-controls button.chain-fire{background:linear-gradient(#a3844e,#796237);color:#fff3d4}.chain-controls button:disabled{opacity:.4;cursor:default}.chain-controls button:focus-visible{outline:3px solid #a8e9e8;outline-offset:3px}.chain-controls .chain-help{font-size:12px;color:#b3c6cc}@media(max-width:600px){.chain-controls{flex-wrap:wrap;padding:10px;gap:8px}.chain-controls .chain-readout{width:100%;justify-content:space-between;gap:8px}.chain-controls .chain-buttons{width:100%}.chain-controls button{flex:1;min-height:46px}.chain-controls .chain-help{display:none}}.chain-player-frame:fullscreen .chain-controls{flex-shrink:0;width:min(1120px,100%);margin:8px auto}.chain-player-frame:fullscreen .play-mount{height:calc(100% - 86px)!important;aspect-ratio:auto}@media(max-width:600px){.chain-player-frame:fullscreen .play-mount{height:calc(100% - 126px)!important}}</style><div class="chain-readout"><span class="chain-ammo"><img alt=""><span></span></span><span class="chain-ammo chain-next"><span>下一枚</span><img alt=""></span><span class="chain-help">移动 / 拖动瞄准 · 点击发射</span></div><div class="chain-buttons"><button type="button" class="chain-swap">交换 · C</button><button type="button" class="chain-fire">发射 · 空格</button></div>';
 (host.closest('.play-mount')||host).after(controls);const frame=host.closest('.player-frame')||host;frame.classList.add('chain-player-frame');const swapButton=controls.querySelector('.chain-swap'),fireButton=controls.querySelector('.chain-fire'),ammoImages=controls.querySelectorAll('img'),ammoName=controls.querySelector('.chain-ammo span');fireButton.onclick=fire;swapButton.onclick=swap;
 function sync(){const ok=active&&s.phase==='playing';fireButton.disabled=!ok||s.cooldown>.02;swapButton.disabled=!ok;const key=s.loaded+':'+s.next;if(key!==lastAmmo){lastAmmo=key;ammoImages[0].src=art[ORB_NAMES[s.loaded]].src;ammoImages[0].alt=NAMES[s.loaded];ammoImages[1].src=art[ORB_NAMES[s.next]].src;ammoImages[1].alt=NAMES[s.next];ammoName.textContent=NAMES[s.loaded]}}
 function aim(p){if(!p||!active||s.phase!=='playing'||Math.hypot(p.x-CHAIN_LAUNCHER.x,p.y-CHAIN_LAUNCHER.y)<40)return;s.angle=Math.atan2(p.y-CHAIN_LAUNCHER.y,p.x-CHAIN_LAUNCHER.x)}
 function point(e){const r=element.getBoundingClientRect(),scale=Math.min(r.width/W,r.height/H);return {x:(e.clientX-r.left-(r.width-W*scale)/2)/scale,y:(e.clientY-r.top-(r.height-H*scale)/2)/scale}}
 element.addEventListener('pointermove',e=>{if(e.pointerType!=='touch'||e.buttons)aim(point(e))},{signal:controller.signal});element.addEventListener('pointerdown',e=>{if(!active)return;aim(point(e));element.setPointerCapture(e.pointerId)},{signal:controller.signal});
 function fire(){if(active&&chainFire(s)){recoil=.2;sfx('shot');sync()}}
 function swap(){if(active&&chainSwap(s)){sfx('turn');sync()}}
 function effects(event){if(event.type==='clear'){for(const b of event.balls){const p=chainPoint(b.pos);rings.push({...p,c:b.c,age:0});for(let i=0;i<10;i++)particles.push({x:p.x,y:p.y,vx:Math.cos(i*2.399+b.id)*(26+i*7),vy:Math.sin(i*2.399+b.id)*(26+i*7),c:b.c,age:0,duration:.5+i%3*.16})}const p=chainPoint(event.balls[Math.floor(event.balls.length/2)].pos);floatText.push({x:p.x,y:p.y,age:0,text:event.combo>1?'连锁 × '+event.combo:'+'+event.balls.length*120});sfx(event.combo>1?'success':'pickup');if(event.won){notify('琉光回廊完成 · 消除 '+s.removed+' 枚，最高 '+s.maxCombo+' 段连锁。');sfx('success')}}else if(event.type==='insert')sfx('turn');else if(event.type==='lost')sfx('hurt')}
 function restart(){s=chainFresh();particles=[];rings=[];floatText=[];recoil=0;visualPositions=new Map(s.balls.map(b=>[b.id,b.pos]));sfx('shuffle');sync()}
 function tick(dt){if(!active)return;dt=clamp(dt,0,.05);visualTime+=dt;recoil=Math.max(0,recoil-dt);if(input.keys.has('ArrowLeft')||input.keys.has('KeyA'))s.angle-=dt*1.8;if(input.keys.has('ArrowRight')||input.keys.has('KeyD'))s.angle+=dt*1.8;if(input.pressed.has('Space'))fire();if(input.pressed.has('KeyC'))swap();for(const p of input.pointers){aim(p);fire()}for(const e of chainStep(s,dt))effects(e);const nextVisual=new Map();for(const b of s.balls){const prev=visualPositions.get(b.id)??b.pos;nextVisual.set(b.id,prev+(b.pos-prev)*(1-Math.exp(-dt*24)))}visualPositions=nextVisual;particles.forEach(p=>{p.age+=dt;p.x+=p.vx*dt;p.y+=p.vy*dt;p.vx*=Math.max(0,1-dt*1.6);p.vy*=Math.max(0,1-dt*1.6)});particles=particles.filter(p=>p.age<p.duration);rings.forEach(p=>p.age+=dt);rings=rings.filter(p=>p.age<.65);floatText.forEach(p=>p.age+=dt);floatText=floatText.filter(p=>p.age<1.2);sync()}
 function text(t,x,y,size=16,color='#f0dfb4',align='left',weight=400){ctx.font=weight+' '+size+'px "Microsoft YaHei",sans-serif';ctx.textAlign=align;ctx.fillStyle=color;ctx.fillText(t,x,y)}
 function box(x,y,w,h,alpha=.78){ctx.fillStyle='rgba(4,18,29,'+alpha+')';ctx.strokeStyle='#bd9a5e70';ctx.lineWidth=1;ctx.beginPath();ctx.roundRect(x,y,w,h,9);ctx.fill();ctx.stroke()}
 function orb(c,x,y,size=34,angle=0,alpha=1){const im=art[ORB_NAMES[c]];ctx.save();ctx.globalAlpha=alpha;ctx.translate(x,y);ctx.rotate(angle);ctx.shadowColor='#01070dcc';ctx.shadowBlur=5;ctx.shadowOffsetY=3;ctx.drawImage(im,-size/2,-size/2,size,size);ctx.restore()}
 function draw(){cover(ctx,art.observatory);ctx.fillStyle='#06182712';ctx.fillRect(0,0,W,H);const path=()=>{ctx.beginPath();ROUTE.forEach((p,i)=>i?ctx.lineTo(p.x,p.y):ctx.moveTo(p.x,p.y))};ctx.save();ctx.lineJoin='round';ctx.lineCap='round';path();ctx.strokeStyle='#010d192d';ctx.lineWidth=39;ctx.stroke();path();ctx.strokeStyle='#102b353c';ctx.lineWidth=34;ctx.stroke();for(const side of [-1,1]){ctx.beginPath();ROUTE.forEach((p,i)=>{const prev=ROUTE[Math.max(0,i-1)],next=ROUTE[Math.min(ROUTE.length-1,i+1)],dx=next.x-prev.x,dy=next.y-prev.y,l=Math.hypot(dx,dy)||1,x=p.x-dy/l*18.4*side,y=p.y+dx/l*18.4*side;i?ctx.lineTo(x,y):ctx.moveTo(x,y)});ctx.strokeStyle=side<0?'#dac1858c':'#78552e90';ctx.lineWidth=1.3;ctx.stroke()}path();ctx.strokeStyle='#9bd4c11c';ctx.lineWidth=.8;ctx.stroke();ctx.restore();
  for(let d=24;d<CHAIN_LENGTH;d+=72){const p=chainPoint(d);ctx.save();ctx.translate(p.x,p.y);ctx.rotate(Math.atan2(p.ty,p.tx));ctx.strokeStyle='#c0a36755';ctx.lineWidth=1;ctx.beginPath();ctx.moveTo(-1,-21);ctx.lineTo(-1,-18);ctx.moveTo(-1,18);ctx.lineTo(-1,21);ctx.stroke();ctx.restore()}
  const end=chainPoint(CHAIN_LENGTH),danger=(s.balls.at(-1)?.pos||0)>CHAIN_LENGTH-390;ctx.save();ctx.shadowColor=danger?'#f67c57':'#4bcec7';ctx.shadowBlur=danger?18+8*Math.sin(visualTime*6):12;ctx.strokeStyle=danger?'#ffab73':'#74d2cc';ctx.lineWidth=2;ctx.beginPath();ctx.arc(end.x,end.y,23,0,Math.PI*2);ctx.stroke();ctx.restore();
  for(const b of s.balls){const p=chainPoint(visualPositions.get(b.id)??b.pos);orb(b.c,p.x,p.y,34,Math.sin(visualTime*.8+b.id)*.035)}
  for(const shot of s.shots){ctx.save();ctx.strokeStyle=COLORS[shot.c]+'80';ctx.lineWidth=3;ctx.lineCap='round';ctx.beginPath();shot.trail.forEach((p,i)=>i?ctx.lineTo(p.x,p.y):ctx.moveTo(p.x,p.y));ctx.lineTo(shot.x,shot.y);ctx.stroke();ctx.restore();orb(shot.c,shot.x,shot.y,33)}
  const {x,y}=CHAIN_LAUNCHER;ctx.save();ctx.translate(x,y);ctx.rotate(s.angle+Math.PI/2);ctx.shadowColor='#000b';ctx.shadowBlur=14;ctx.shadowOffsetY=7;ctx.drawImage(art.launcher,-50,-62+recoil*20,100,112);ctx.restore();orb(s.loaded,x+Math.cos(s.angle)*40,y+Math.sin(s.angle)*40,28);orb(s.next,x+49,y+46,21,0,.85);
  if(s.phase==='playing'){ctx.save();ctx.strokeStyle=COLORS[s.loaded]+'80';ctx.fillStyle=COLORS[s.loaded]+'88';for(let d=76;d<176;d+=17){const px=x+Math.cos(s.angle)*d,py=y+Math.sin(s.angle)*d;ctx.beginPath();ctx.arc(px,py,1.4,0,Math.PI*2);ctx.fill()}ctx.restore()}
  for(const p of rings){ctx.save();ctx.globalAlpha=1-p.age/.65;ctx.strokeStyle=COLORS[p.c];ctx.lineWidth=2;ctx.beginPath();ctx.arc(p.x,p.y,16+p.age*52,0,Math.PI*2);ctx.stroke();ctx.restore()}for(const p of particles){ctx.save();ctx.globalAlpha=1-p.age/p.duration;ctx.fillStyle=COLORS[p.c];ctx.shadowColor=COLORS[p.c];ctx.shadowBlur=6;ctx.translate(p.x,p.y);ctx.rotate(p.age*3);ctx.fillRect(-2,-2,4,4);ctx.restore()}for(const p of floatText){ctx.save();ctx.globalAlpha=Math.min(1,(1.2-p.age)*2);text(p.text,p.x,p.y-24-p.age*27,18,'#ffe2a0','center',600);ctx.restore()}
  box(27,23,241,61,.78);text('琉光回廊',43,51,21,'#f5dfad','left',600);text('同色共鸣 · 珠链回拢',43,72,12,'#b9d4d5');box(838,24,253,54,.76);text('点亮 '+s.removed+' 枚',854,47,17,'#d6e4cf');text(s.score.toLocaleString()+' 分  /  连锁 '+s.maxCombo,854,65,12,'#e0c78e');
  if(['won','lost'].includes(s.phase)){ctx.fillStyle='#04121b69';ctx.fillRect(0,0,W,H);box(345,231,430,165,.92);text(s.won?'星图已被点亮':'再开启一次回廊',560,276,27,'#fce8b8','center',600);text(s.won?'所有晶球都已归位，回廊重新恢复了光。':'暗门已吸入珠链，下一次留意前端的距离。',560,310,15,'#c5d8d7','center');text(s.score.toLocaleString()+' 分 · 点亮 '+s.removed+' 枚 · 最高 '+s.maxCombo+' 段连锁',560,343,15,'#ddc696','center');text('下方「重新开启回廊」再试一次',560,375,13,'#bacacf','center')}
 }
 sync();return {tick,draw,onStart(){active=true;sync()},setActive(v){active=!!v;sync()},getState:()=>structuredClone(s),getStatus:()=>({goal:s.phase==='won'?'星图已点亮':s.phase==='lost'?'回廊已结束':'让珠链在进入暗门前全部共鸣消除',message:s.message,stats:['余下 '+s.balls.length+' 枚','点亮 '+s.removed+' 枚','得分 '+s.score,'最高 '+s.maxCombo+' 段连锁'],actions:[action('交换当前与下一枚',swap,!active||s.phase!=='playing'),action('重新开启回廊',restart)]}),command(type,value){if(type==='aim'&&Number.isFinite(value)){s.angle=value;return true}if(type==='fire'){const before=s.fired;fire();return s.fired>before}if(type==='swap'){swap();return true}return false},dispose(){controller.abort();controls.remove();frame.classList.remove('chain-player-frame');particles=[];rings=[];floatText=[]}};
}
