import {W,H,images,canvasSurface,cover,sprite,shadow,glow,action,safeSaved} from './showcase-core.js';

const heroSpecs=[{id:'captain',name:'岚 · 近卫',hp:80,mp:0},{id:'mage',name:'衡 · 术师',hp:58,mp:12},{id:'healer',name:'葵 · 医师',hp:64,mp:12}];
const enemySpecs=[{id:'sentinel',name:'铜卫',hp:40,damage:10},{id:'hound',name:'影兽',hp:32,damage:12},{id:'orb',name:'星轮',hp:30,damage:8}];
export const PARTY_SKILLS={
 captain:[{id:'strike',name:'斩击',target:'enemy',cost:0,detail:'单体伤害 16'},{id:'protect',name:'护卫',target:'allies',cost:0,detail:'全队获得 8 点护盾'}],
 mage:[{id:'arcane',name:'奥术',target:'enemy',cost:3,detail:'消耗 3 灵力，单体伤害 24'},{id:'echo',name:'回响',target:'enemies',cost:4,detail:'消耗 4 灵力，每名敌人伤害 12'},{id:'focus',name:'专注',target:'self',cost:0,detail:'恢复 4 灵力，获得 4 点护盾'}],
 healer:[{id:'toss',name:'投掷',target:'enemy',cost:0,detail:'单体伤害 12'},{id:'heal',name:'治疗',target:'ally',cost:3,detail:'消耗 3 灵力，恢复队友 24 生命'},{id:'focus',name:'专注',target:'self',cost:0,detail:'恢复 4 灵力，获得 4 点护盾'}]
};
const newHeroes=()=>heroSpecs.map(h=>({...h,maxHP:h.hp,maxMP:h.mp,shield:0}));
const newEnemies=stage=>enemySpecs.map((e,i)=>({...e,hp:stage===0?e.hp:[78,38,36][i],maxHP:stage===0?e.hp:[78,38,36][i],shield:0}));
const defaults={version:1,stage:0,round:1,phase:'player',heroIndex:0,skill:'strike',heroes:newHeroes(),enemies:newEnemies(0),pending:null,enemyQueue:[],enemyCursor:0,log:[],score:0,won:false,elapsed:0,actions:0,damageDealt:0,healed:0,prevented:0};
const heroSpots=[{x:190,y:395,h:245},{x:305,y:468,h:252},{x:405,y:515,h:224}],enemySpots=[{x:797,y:399,h:260},{x:938,y:484,h:185},{x:768,y:519,h:204}];
export async function createParty({host,input,saved,notify,sfx}){
 const art=await images(['scene','captain','mage','healer','sentinel','hound','orb'],'assets/game-forms/party/'),{element,ctx}=canvasSurface(host);let s=safeSaved(saved,defaults);
 element.setAttribute('aria-label','余烬旅团，指令式战斗。依次选择队员技能与目标，观察敌方行动；无需移动或走格。');
 const alive=side=>s[side].map((u,i)=>u.hp>0?i:-1).filter(i=>i>=0),hero=()=>s.heroes[s.heroIndex],skills=()=>PARTY_SKILLS[hero().id],selected=()=>skills().find(k=>k.id===s.skill)||skills()[0];
 function record(message){s.log.push(message);if(s.log.length>18)s.log.shift()}
 function setHero(i){s.heroIndex=i;s.skill=PARTY_SKILLS[s.heroes[i].id][0].id;s.phase='player'}
 function chooseSkill(id){if(s.phase!=='player')return;const skill=skills().find(k=>k.id===id);if(!skill||hero().mp<skill.cost)return;s.skill=id;sfx('cards')}
 function issue(target){if(s.phase!=='player')return;const k=selected(),h=hero();if(h.mp<k.cost)return;if(k.target==='enemy'&&s.enemies[target]?.hp<=0||k.target==='ally'&&s.heroes[target]?.hp<=0)return;h.mp-=k.cost;s.actions++;s.pending={side:'hero',index:s.heroIndex,target,skill:k.id,title:k.name,elapsed:0,duration:.62};s.phase='anim';sfx(k.id==='heal'?'water':k.id==='strike'?'slash':'cards')}
 function damage(side,i,amount){const unit=s[side][i],blocked=Math.min(unit.shield,amount);unit.shield-=blocked;unit.hp=Math.max(0,unit.hp-amount+blocked);if(side==='heroes')s.prevented+=blocked;else{s.damageDealt+=amount-blocked;if(unit.hp===0)s.score+=100}return amount-blocked}
 function enemyIntent(index){const e=s.enemies[index];if(e.id==='sentinel')return {target:s.heroes.findIndex(h=>h.hp>0),amount:s.round%3===0?18:e.damage,title:s.round%3===0?'蓄力重击':'铜刃'};if(e.id==='hound'){const live=alive('heroes');return {target:live.reduce((a,b)=>s.heroes[a].hp<=s.heroes[b].hp?a:b),amount:e.damage,title:'追击低生命'} }return {target:alive('heroes')[s.round%alive('heroes').length],amount:e.damage,title:'星轮脉冲'}}
 function checkEnd(){if(!alive('heroes').length){s.phase='lost';s.pending=null;record('队伍倒下了。可以重新开始这段试炼。');notify('队伍倒下。护卫能吸收下一轮攻击，医师也可以治疗受伤队员。');return true}if(!alive('enemies').length){s.pending=null;s.score+=300;s.phase=s.stage===0?'between':'won';s.won=s.stage===1;record(s.won?'两场试炼完成。天文台重新回应了旅团。':'第一场完成。整队后进入内环。');sfx('success');notify(s.won?'两场试炼完成，队伍的选择决定了这一战。':'第一场完成，可以整队进入第二场。');return true}return false}
 function beginEnemy(){s.enemyQueue=alive('enemies');s.enemyCursor=0;nextEnemy()}
 function nextEnemy(){if(checkEnd())return;if(s.enemyCursor>=s.enemyQueue.length){s.round++;for(const h of s.heroes)h.shield=0;setHero(alive('heroes')[0]);return}const index=s.enemyQueue[s.enemyCursor++];if(s.enemies[index].hp<=0){nextEnemy();return}const intention=enemyIntent(index);s.pending={side:'enemy',index,target:intention.target,amount:intention.amount,title:intention.title,elapsed:0,duration:.7};s.phase='anim';sfx('hurt')}
 function resolve(){const p=s.pending;if(!p)return;if(p.side==='hero'){const h=s.heroes[p.index],k=p.skill;let result='';if(k==='strike'||k==='arcane'||k==='toss'){const amount={strike:16,arcane:24,toss:12}[k],n=damage('enemies',p.target,amount);result=s.enemies[p.target].name+' −'+n}else if(k==='echo'){for(const i of alive('enemies'))damage('enemies',i,12);result='所有敌人 −12'}else if(k==='heal'){const target=s.heroes[p.target],gain=Math.min(24,target.maxHP-target.hp);target.hp+=gain;s.healed+=gain;result=target.name+' +'+gain}else if(k==='protect'){for(const i of alive('heroes'))s.heroes[i].shield=Math.min(16,s.heroes[i].shield+8);result='全队护盾 +8'}else{const gain=Math.min(4,h.maxMP-h.mp);h.mp+=gain;h.shield+=4;result='灵力 +'+gain+' · 护盾 +4'}record(h.name+'：'+p.title+'，'+result);s.pending=null;if(checkEnd())return;const next=alive('heroes').find(i=>i>p.index);if(next!==undefined)setHero(next);else beginEnemy()}else{const n=damage('heroes',p.target,p.amount);record(s.enemies[p.index].name+'：'+p.title+' → '+s.heroes[p.target].name+' −'+n);s.pending=null;nextEnemy()}}
 function nextStage(){if(s.phase!=='between')return;s.stage=1;s.round=1;s.enemies=newEnemies(1);for(const h of s.heroes){h.hp=Math.min(h.maxHP,h.hp+25);h.mp=Math.min(h.maxMP,h.mp+4);h.shield=0}s.enemyQueue=[];setHero(alive('heroes')[0]);record('进入天文台内环，全队恢复 25 生命与 4 灵力。');sfx('door')}
 function restart(){s=structuredClone(defaults);notify('回到第一场。已完成的展厅记录继续保留。')}
 function tick(dt){s.elapsed+=dt;if(s.pending){s.pending.elapsed+=dt;if(s.pending.elapsed>=s.pending.duration)resolve();return}if(s.phase!=='player')return;const k=selected();for(const p of input.pointers){if(k.target==='enemy'){const i=enemySpots.findIndex(v=>Math.abs(p.x-v.x)<65&&p.y>v.y-v.h&&p.y<v.y+28);if(i>=0&&s.enemies[i].hp>0)issue(i)}else if(k.target==='ally'){const i=heroSpots.findIndex(v=>Math.abs(p.x-v.x)<65&&p.y>v.y-v.h&&p.y<v.y+28);if(i>=0&&s.heroes[i].hp>0)issue(i)}}}
 function rect(x,y,w,h,color='#091d28df',stroke='#b08c5866'){ctx.fillStyle=color;ctx.fillRect(x,y,w,h);ctx.strokeStyle=stroke;ctx.strokeRect(x,y,w,h)}
 function txt(value,x,y,size=17,color='#e8dfcc'){ctx.font=size+'px "Microsoft YaHei",sans-serif';ctx.fillStyle=color;ctx.textAlign='left';ctx.fillText(value,x,y)}
 function bar(x,y,width,value,max,color){ctx.fillStyle='#030a10cc';ctx.fillRect(x,y,width,6);ctx.fillStyle=color;ctx.fillRect(x,y,width*Math.max(0,value)/max,6)}
 function draw(){cover(ctx,art.scene);if(s.stage===1){ctx.fillStyle='#20305a26';ctx.fillRect(0,0,W,H)}const pulse=Math.sin(s.elapsed*3)*.5+.5,pending=s.pending;for(const [side,spots] of [['heroes',heroSpots],['enemies',enemySpots]])s[side].forEach((u,i)=>{const v=spots[i],moving=pending&&pending.side===(side==='heroes'?'hero':'enemy')&&pending.index===i,progress=moving?Math.sin(Math.min(1,pending.elapsed/pending.duration)*Math.PI):0,dx=progress*(side==='heroes'?28:-24);shadow(ctx,v.x,v.y,48);if(u.shield>0)glow(ctx,v.x,v.y-90,90,'#50dac33e');if(side==='heroes'&&s.heroIndex===i&&s.phase==='player'){ctx.strokeStyle='#efc177';ctx.lineWidth=2;ctx.beginPath();ctx.ellipse(v.x,v.y,49,10,0,0,Math.PI*2);ctx.stroke()}sprite(ctx,art[u.id],v.x+dx,v.y,v.h,false,u.hp>0?1:.22);if(side==='enemies'){rect(v.x-64,v.y+12,128,43,'#06151bdc');txt(u.name+' '+u.hp+'/'+u.maxHP,v.x-53,v.y+29,13);bar(v.x-53,v.y+39,106,u.hp,u.maxHP,'#df926e')}});
  rect(30,24,446,78);txt('余烬旅团',49,58,28,'#e7c990');txt((s.stage+1)+' / 2 场 · 第 '+s.round+' 回合 · 指令式队伍战斗',50,84,14,'#adc6cd');rect(821,25,270,53);txt(s.phase==='player'?'轮到 '+hero().name:s.phase==='anim'?pending.title:s.phase==='between'?'整队，准备进入内环':s.won?'天文台重新点亮':'队伍需要休整',839,57,18,'#e4c58b');
  if(s.phase==='player'){const k=selected();rect(468,98,465,40,'#071923bd');txt(k.name+' · '+k.detail,483,124,16,'#bde0dc');if(k.target==='enemy'||k.target==='ally'){const side=k.target==='enemy'?'enemies':'heroes',spots=k.target==='enemy'?enemySpots:heroSpots;for(const i of alive(side)){const v=spots[i];ctx.strokeStyle='#e7c17f';ctx.lineWidth=1.5;ctx.globalAlpha=.35+pulse*.35;ctx.beginPath();ctx.ellipse(v.x,v.y,57,12,0,0,Math.PI*2);ctx.stroke();ctx.globalAlpha=1}}}
  s.heroes.forEach((h,i)=>{const x=28+i*277;rect(x,555,263,62,s.phase==='player'&&i===s.heroIndex?'#173c43f2':'#071925ed');txt(h.name,x+12,578,16,h.hp>0?'#eed19b':'#8d969a');txt('生命 '+h.hp+'/'+h.maxHP+'  灵力 '+h.mp+'  盾 '+h.shield,x+12,598,13,'#b6d0d0');bar(x+12,606,238,h.hp,h.maxHP,'#71cbbb')});rect(869,555,222,62);txt('战况记录',881,577,15,'#c6d5d4');txt('伤害 '+s.damageDealt+' · 治疗 '+s.healed,881,600,13,'#9cb9c4');
  if(pending){const target=(pending.side==='hero'?pending.skill==='heal'?heroSpots:enemySpots:heroSpots)[pending.target];if(target&&pending.elapsed>pending.duration*.25){const color=pending.skill==='heal'?'#7ff5c660':pending.side==='hero'?'#f1cc8760':'#eb765750';glow(ctx,target.x,target.y-80,90,color);ctx.strokeStyle=color;ctx.lineWidth=5;ctx.beginPath();ctx.arc(target.x,target.y-80,20+pending.elapsed*45,0,Math.PI*2);ctx.stroke()}}
  if(['won','lost','between'].includes(s.phase)){rect(332,204,456,177,'#081923ee','#d6b57d99');txt(s.won?'两场试炼完成':s.phase==='lost'?'队伍倒下了':'第一场完成',373,253,31,'#eed099');txt(s.phase==='between'?'整队后恢复生命和灵力，再进入内环。':s.won?'每一名队员的回应，组成了这一场胜利。':'护卫、治疗与灵力恢复，可以改变下一次战局。',365,293,16,'#b9d3d2');txt('使用下方按钮继续',454,340,14,'#adc0c2')}
 }
 return {tick,draw,getState:()=>({...structuredClone(s),skills:PARTY_SKILLS,heroSpots,enemySpots,intents:alive('enemies').map(i=>({enemy:i,...(alive('heroes').length?enemyIntent(i):{})}))}),getStatus:()=>({goal:s.won?'完成两场天文台试炼':s.phase==='lost'?'休整并重新安排队伍':s.phase==='between'?'整队进入第二场':s.phase==='player'?'选择 '+hero().name+' 的行动与目标':'观察敌我行动结果',message:s.log.at(-1)||'三名队员各行动一次，随后敌方行动。选择技能，再点击场中目标或下方目标按钮。',stats:['场次 '+(s.stage+1)+'/2','回合 '+s.round,'行动 '+s.actions],actions:s.phase==='player'?[...skills().map(k=>action(k.name+(k.cost?' · '+k.cost+' 灵力':'' )+(s.skill===k.id?' ✓':''),()=>chooseSkill(k.id),hero().mp<k.cost)),...(selected().target==='enemy'?alive('enemies').map(i=>action('目标：'+s.enemies[i].name,()=>issue(i))):selected().target==='ally'?alive('heroes').map(i=>action('治疗：'+s.heroes[i].name,()=>issue(i))):[action('施放 '+selected().name,()=>issue(s.heroIndex))])]:s.phase==='between'?[action('整队进入内环',nextStage)]:['won','lost'].includes(s.phase)?[action('重新出发',restart)]:[]}),dispose(){element.remove()}};
}
