import {W,H,images,canvasSurface,cover,sprite,action,safeSaved} from './showcase-core.js';

const speakers={narrator:'这一夜',lin:'林岚 · 航标工程师',zhou:'周衡 · 港口调度员',you:'你'};
const line=(speaker,text)=>({speaker,text});
export const NOVEL_NODES={
 opening:{scene:'station',chapter:'海岸候车厅',lines:[line('narrator','雨沿着玻璃往下走。最后一班列车停在窗外，港口的航标却迟迟没有亮。'),line('zhou','这封信晚了七年。今晚再不送去，我大概又会把它带回家。'),line('lin','我要去灯塔核对最后一段记录。你若不急着上车，可以陪我们走一程。')],choices:[{id:'letter',text:'陪周衡走一趟灯塔',next:'letter',route:'letter',trust:1},{id:'signal',text:'先去核对航标记录',next:'signal',route:'signal',rigor:1}]},
 letter:{scene:'control',chapter:'灯塔里的旧信',lines:[line('zhou','信是写给我的老搭档的。那年我替他做了一个决定，却从没问他愿不愿意。'),line('lin','他离开前在这里留过一句话：有些事情，收到解释比收到道歉更难。'),line('you','纸上的字还在。现在要怎样把它们交出去？')],choices:[{id:'voice',text:'让周衡亲口读出这封信',next:'voice',promise:'voice',trust:1},{id:'record-letter',text:'将信收入档案，留下来由',next:'recordLetter',promise:'record',rigor:1}]},
 signal:{scene:'control',chapter:'没有接通的频段',lines:[line('lin','我师父留下的记录少了一页。设备没有坏，只是没人敢确认最后的频段。'),line('zhou','他以前总说，值夜班最难的，是承认自己需要另一个人。'),line('you','灯塔可以重新亮起来。这一页，又应该由谁写完？')],choices:[{id:'together',text:'请林岚一起确认这段记录',next:'together',promise:'together',trust:1},{id:'record-signal',text:'独自把记录补完整',next:'recordSignal',promise:'record',rigor:2}]},
 voice:{scene:'control',chapter:'把话说完',lines:[line('zhou','“那天我以为替你留下，是为了你好。现在我知道，留下或离开都该由你自己选。”'),line('lin','她没有接话，只把收信人的名字写进值班册。窗外第一束航标光越过了海面。')],next:'platform'},
 recordLetter:{scene:'control',chapter:'让来由留下',lines:[line('you','你把迟到的信放在那份离岗记录旁边，没有替任何人写下原谅。'),line('zhou','谢谢。至少以后有人问起那年，我们不用只剩下一句“都过去了”。')],next:'platform'},
 together:{scene:'control',chapter:'一起确认',lines:[line('lin','“这里是东岸灯塔，请确认收到。”她念出记录，你在另一端重复了一遍。'),line('zhou','两次声音合在同一个频段上，灯终于亮了。没有谁把功劳写成自己的名字。')],next:'platform'},
 recordSignal:{scene:'control',chapter:'写完这一页',lines:[line('you','你逐项核对时间与频段，在记录末尾留下自己的签名。'),line('lin','灯亮起来的时候，她说：“明天我会再检查一遍。谢谢你先把这一页写完。”')],next:'platform'},
 platform:{scene:'station',chapter:'回到末班车前',lines:[line('narrator','回到候车厅时，雨小了。那封信有了去处，港口也有了回应。'),line('zhou',s=>s.promise==='voice'?'我以为把信送出去，就能立刻轻松。原来还要学着等一个不一定会来的回音。':'明天还要继续值班。今晚留下来的事，终于不必再由一个人记着。')],choices:[{id:'stay',text:'留在港口，等天亮',finish:'stay'},{id:'depart',text:'登上末班列车',finish:'depart'}]}
};
const endings={
 together:{title:'并肩的灯火',text:'你留下来，听见两个人从旧事聊到明天的值班。有人愿意把话说完，也有人愿意陪他等。天亮时，港口的灯照常熄下。'},
 record:{title:'记在纸上的灯',text:'你留下来，把信与新记录一起放进档案。事情没有被一个夜晚解决，但它们终于有了准确的来由。明天，另一位值班人可以接着读。'},
 depart:{title:'寄向下一站',text:'列车开动时，你从车窗看见海面上的航标。你没有替他们决定以后。这个夜晚留下的回应，已经足够陪你走向下一站。'}
};
const defaults={version:1,node:'opening',line:0,visible:0,phase:'read',route:null,promise:null,trust:0,rigor:0,choices:[],log:[],logOffset:0,backlog:false,review:false,instant:false,ending:null,endings:[],decision:null,won:false,score:0,elapsed:0};
export async function createNovel({host,input,saved,notify,sfx}){
 const art=await images(['station','control','lin','zhou'],'assets/game-forms/novel/'),{element,ctx}=canvasSurface(host);let s=safeSaved(saved,defaults),fade=0,previous='station';
 if(!NOVEL_NODES[s.node])s.node='opening';
 element.setAttribute('aria-label','海岸末班信，互动小说。点击对白或按空格继续，点击选项决定走向；E查看对话记录。');
 const node=()=>NOVEL_NODES[s.node],currentLine=()=>{const l=node().lines[Math.min(s.line,node().lines.length-1)];return {...l,text:typeof l.text==='function'?l.text(s):l.text}};
 function remember(){const l=currentLine(),key=s.node+':'+s.line;if(!s.log.some(e=>e.key===key)){s.log.push({key,speaker:speakers[l.speaker],text:l.text});if(s.log.length>40)s.log.shift()}}
 function enter(id){previous=node().scene;s.node=id;s.line=0;s.visible=s.instant?currentLine().text.length:0;s.phase='read';s.backlog=s.review=false;fade=.55;remember();sfx('door')}
 function advance(){if(s.won||s.backlog||s.review||s.phase==='choice')return;const l=currentLine();if(s.visible<l.text.length){s.visible=l.text.length;return}if(s.line<node().lines.length-1){s.line++;s.visible=s.instant?currentLine().text.length:0;remember();sfx('turn')}else if(node().choices){s.phase='choice';sfx('cards')}else enter(node().next)}
 function finish(kind){const id=kind==='depart'?'depart':s.promise==='voice'||s.promise==='together'?'together':'record';s.ending=id;s.decision=id;s.won=true;s.phase='won';s.score=100+s.choices.length*100+s.trust*50+s.rigor*50;s.endings=[...new Set([...s.endings,id])];sfx('success');notify('这一夜结束：'+endings[id].title+'。不同选择会留下不同的对话与结局记录。')}
 function choose(id){if(s.phase!=='choice'||s.won)return;const choice=node().choices.find(c=>c.id===id);if(!choice)return;s.choices.push({node:s.node,id,text:choice.text});s.log.push({key:s.node+':choice',speaker:'你的选择',text:choice.text});s.trust+=choice.trust||0;s.rigor+=choice.rigor||0;if(choice.route)s.route=choice.route;if(choice.promise)s.promise=choice.promise;sfx('pickup');if(choice.finish)finish(choice.finish);else enter(choice.next)}
 function restart(){const ledger=[...s.endings],instant=s.instant;s=structuredClone(defaults);s.endings=ledger;s.instant=instant;fade=0;remember();notify('回到这一夜的开头。已读结局继续保留。')}
 function text(text,x,y,width,size=23,color='#e4e2d9',height=35,max=5){ctx.font=size+'px "Microsoft YaHei",sans-serif';ctx.textAlign='left';ctx.fillStyle=color;let row='',count=0;for(const char of text){if(ctx.measureText(row+char).width>width){ctx.fillText(row,x,y+count*height);row=char;count++;if(count>=max)return}else row+=char}ctx.fillText(row,x,y+count*height)}
 function box(x,y,w,h,fill='#071621ed',stroke='#b7986866'){ctx.fillStyle=fill;ctx.fillRect(x,y,w,h);ctx.strokeStyle=stroke;ctx.lineWidth=1;ctx.strokeRect(x,y,w,h)}
 function choiceRects(){return (node().choices||[]).map((c,i)=>({...c,x:252,y:245+i*82,w:616,h:65}))}
 remember();
 function tick(dt){s.elapsed+=dt;fade=Math.max(0,fade-dt);if(input.pressed.has('KeyE')){s.backlog=!s.backlog;s.review=false;s.logOffset=0;sfx('cards')}if(s.backlog||s.review){for(const p of input.pointers)if(p.x>986&&p.y<116)s.backlog=s.review=false;return}if(s.phase==='read')s.visible=Math.min(currentLine().text.length,s.visible+(s.instant?10000:35)*dt);if(input.pressed.has('Space'))advance();for(const p of input.pointers){if(s.phase==='choice'){const c=choiceRects().find(c=>p.x>=c.x&&p.x<=c.x+c.w&&p.y>=c.y&&p.y<=c.y+c.h);if(c)choose(c.id)}else if(p.y>408&&p.y<600)advance()}}
 function draw(){
  cover(ctx,art[node().scene]);if(fade>0){ctx.save();ctx.globalAlpha=fade/.55;cover(ctx,art[previous]);ctx.restore()}
  const l=currentLine();sprite(ctx,art.lin,253,H+8,535,false,l.speaker==='zhou'?.52:1);sprite(ctx,art.zhou,867,H+8,541,false,l.speaker==='lin'?.52:1);
  const gradient=ctx.createLinearGradient(0,345,0,H);gradient.addColorStop(0,'transparent');gradient.addColorStop(1,'#02101bc9');ctx.fillStyle=gradient;ctx.fillRect(0,345,W,H-345);
  box(35,27,331,77,'#071725bc','#b7986844');ctx.font='11px sans-serif';ctx.fillStyle='#a8c4ce';ctx.fillText('A NIGHT / A LETTER',54,48);ctx.font='27px "Microsoft YaHei",sans-serif';ctx.fillStyle='#efdab2';ctx.fillText('海岸末班信',53,85);box(825,29,261,42,'#071725bb','#799ba455');text(node().chapter,846,57,220,15,'#d3dcda',23,1);
  box(57,412,1006,184);ctx.fillStyle='#e0be82';ctx.fillRect(57,412,4,184);text(speakers[l.speaker],91,446,860,18,'#e4bc7a',28,1);text(l.text.slice(0,Math.floor(s.visible)),91,487,923,23,'#e6e3db',35,3);ctx.font='12px sans-serif';ctx.fillStyle='#9cb6c0';ctx.fillText(s.phase==='choice'?'选择会影响后续对白与结局':'点击对白 / 空格继续',91,578);ctx.textAlign='right';ctx.fillText((s.line+1)+' / '+node().lines.length,1030,578);ctx.textAlign='left';
  if(s.phase==='choice'){ctx.fillStyle='#0714218c';ctx.fillRect(0,108,W,305);text('此刻，你想怎样回应？',385,225,460,20,'#efdfbb',30,1);for(const c of choiceRects()){const hover=input.hover&&input.hover.x>=c.x&&input.hover.x<=c.x+c.w&&input.hover.y>=c.y&&input.hover.y<=c.y+c.h;box(c.x,c.y,c.w,c.h,hover?'#33565ce8':'#09232bef',hover?'#e2c68e':'#8dadac99');text(c.text,c.x+27,c.y+41,c.w-54,21,'#e4e3d5',30,1)}}
  if(s.won&&!s.backlog&&!s.review){box(238,173,644,250,'#081a23f2','#bdac7d99');text('这一夜的结局',277,209,560,13,'#afc2c4',22,1);text(endings[s.ending].title,277,252,560,32,'#edc998',42,1);text(endings[s.ending].text,277,300,560,20,'#d4deda',32,3);text('已读 '+s.endings.length+' / 3 个结局 · 可从头选择另一条路',277,397,560,14,'#a5c6c3',24,1)}
  if(s.backlog||s.review){ctx.fillStyle='#03121dec';ctx.fillRect(29,81,1062,521);text(s.review?'这一夜的结局记录':'对话记录',68,119,880,24,'#e6c48f',33,1);text('×',1029,116,40,28,'#ded8c5',35,1);if(s.review){Object.entries(endings).forEach(([id,e],i)=>{text((s.endings.includes(id)?'已读 · ':'待探索 · ')+e.title,71,188+i*118,930,23,s.endings.includes(id)?'#c5e3d2':'#8b9fa8',35,1);if(s.endings.includes(id))text(e.text,71,228+i*118,913,16,'#b8c9cb',24,2)})}else{const end=Math.max(0,s.log.length-s.logOffset);s.log.slice(Math.max(0,end-7),end).forEach((e,i)=>{text(e.speaker,70,164+i*60,220,13,'#dbbd8c',20,1);text(e.text,262,164+i*60,762,16,'#c2d0d0',23,2)})}}
 }
 return {tick,draw,getState:()=>({...structuredClone(s),scene:node().scene,chapter:node().chapter,current:currentLine(),choicesAvailable:node().choices?.map(c=>({id:c.id,text:c.text}))||[],choiceRects:choiceRects(),endingNames:Object.fromEntries(Object.entries(endings).map(([k,v])=>[k,v.title]))}),getStatus:()=>({goal:s.won?'这一夜结束：'+endings[s.ending].title:s.phase==='choice'?'选择此刻的回应':'读完这一夜，决定自己的去向',message:s.won?endings[s.ending].text:s.backlog?'可以查看已读对白，返回后仍停在同一处。':currentLine().text,stats:['场景 '+node().chapter,'回应 '+s.choices.length+' 次','已读结局 '+s.endings.length+'/3'],actions:s.backlog?[action('返回对白',()=>s.backlog=false),action('更早对话',()=>s.logOffset=Math.min(Math.max(0,s.log.length-7),s.logOffset+6),s.log.length-s.logOffset<=7),action('更近对话',()=>s.logOffset=Math.max(0,s.logOffset-6),s.logOffset===0)]:s.review?[action('返回这一夜',()=>s.review=false)]:s.won?[action('重读此夜',restart),action('查看结局记录',()=>s.review=true),action('对话记录 · E',()=>{s.backlog=true;s.logOffset=0})]:[...(s.phase==='choice'?node().choices.map(c=>action(c.text,()=>choose(c.id))):[action(s.visible<currentLine().text.length?'显示全文':'继续 · 空格',advance)]),action('对话记录 · E',()=>{s.backlog=true;s.logOffset=0}),action(s.instant?'文字：即显':'文字：逐字',()=>{s.instant=!s.instant;if(s.instant)s.visible=currentLine().text.length})]}),dispose(){element.remove()}};
}
