import {W,H,clamp,images,canvasSurface,cover,label,glow,action} from './showcase-core.js';

const GRAVITY=220,STEP=1/120,WINDS=[-10,18,-16,8],TANK_X=[146,968];
function initialTerrain(){return Array.from({length:281},(_,i)=>{const x=i*4;return 498-52*Math.exp(-(((x-565)/172)**2))+11*Math.sin(x*.012)+5*Math.sin(x*.035)})}
function heightAt(terrain,x){const p=clamp(x/4,0,280),i=Math.floor(p);return terrain[i]+((terrain[i+1]??terrain[i])-terrain[i])*(p-i)}
function launch(terrain,side,angle,power){const radians=angle*Math.PI/180,d=side? -1:1,x=TANK_X[side],y=heightAt(terrain,x)-34;return {x:x+d*57*Math.cos(radians),y:y-57*Math.sin(radians),vx:d*(180+power*4)*Math.cos(radians),vy:-(180+power*4)*Math.sin(radians),side,age:0,trail:[]}}
function moveBall(b,dt,wind){b.vx+=wind*dt;b.vy+=GRAVITY*dt;b.x+=b.vx*dt;b.y+=b.vy*dt;b.age+=dt}
function trace(terrain,side,angle,power,wind){const b=launch(terrain,side,angle,power),points=[];for(let i=0;i<1400;i++){moveBall(b,STEP,wind);if(i%22===0)points.push({x:b.x,y:b.y});if(b.x<0||b.x>W||b.y>H)return {x:b.x,y:b.y,points};if(b.y>=heightAt(terrain,b.x))return {x:b.x,y:heightAt(terrain,b.x),points}}return {x:b.x,y:b.y,points}}
function fresh(best=null){return {version:1,terrain:initialTerrain(),hp:[110,110],angle:45,power:55,enemyAngle:45,enemyPower:55,wind:WINDS[0],round:1,shots:0,phase:'aim',ball:null,delay:0,craters:0,damage:0,won:false,score:0,best,log:['调整角度和力度，观察风向与预估弧线。'],fx:[],elapsed:0}}

export async function createBattery({host,input,saved,sfx=()=>{}}){
 const art=await images(['scene','olive','azure','olive-barrel','azure-barrel'],'assets/game-forms/battery/'),stone=(await images(['stone'],'assets/game-forms/balance/')).stone;
 const surface=canvasSurface(host),{ctx}=surface;surface.element.setAttribute('aria-label','回合炮战山地，抛物线弹道和可破坏地形');
 let s=saved&&Array.isArray(saved.terrain)&&saved.terrain.length===281?{...fresh(),...structuredClone(saved)}:fresh(),active=false;
 const controls=document.createElement('div');controls.className='battery-settings';controls.innerHTML='<style>.battery-settings{display:grid;grid-template-columns:1fr 1fr;gap:18px;padding:16px 20px;border:1px solid #29414b;border-radius:12px;background:#13232c;margin-top:14px;color:#e9e0ce}.battery-settings label{display:grid;grid-template-columns:1fr auto;align-items:center;gap:8px;font:14px "Microsoft YaHei",sans-serif}.battery-settings input{grid-column:1/-1;width:100%;height:44px;accent-color:#d6aa60}.battery-settings output{color:#efca7c;font-size:18px;font-variant-numeric:tabular-nums}@media(max-width:520px){.battery-settings{padding:12px;gap:12px}.battery-settings label{font-size:13px}}</style><label>发射角度 <output></output><input type="range" min="15" max="80" step="1" aria-label="发射角度"></label><label>发射力度 <output></output><input type="range" min="20" max="100" step="1" aria-label="发射力度"></label>';
 const frame=host.closest('.player-frame')||host;frame.after(controls);const ranges=[...controls.querySelectorAll('input')],outputs=[...controls.querySelectorAll('output')];
 ranges.forEach((r,i)=>{r.oninput=()=>{if(!active||s.phase!=='aim'){sync();return}s[i?'power':'angle']=Number(r.value);sync()};r.onkeydown=e=>{if(e.code==='Space'){e.preventDefault();fire()}}});
 function sync(){ranges[0].value=s.angle;ranges[1].value=s.power;outputs[0].textContent=s.angle+'°';outputs[1].textContent=s.power+'%';ranges.forEach(r=>r.disabled=!active||s.phase!=='aim')}
 function note(text){s.log.unshift(text);s.log=s.log.slice(0,5)}
 function fire(side=0,angle=s.angle,power=s.power){if(side===0&&(!active||s.phase!=='aim'))return;s.ball=launch(s.terrain,side,angle,power);s.phase=side?'enemyFlight':'flight';if(!side)s.shots++;sfx('shot');sync()}
 function enemyShot(){const target=TANK_X[0]+[72,-45,16,0][Math.min(s.round-1,3)];let selected={angle:45,power:55,error:Infinity};for(let angle=28;angle<=76;angle+=2)for(let power=25;power<=100;power++){const p=trace(s.terrain,1,angle,power,s.wind),error=Math.abs(p.x-target);if(error<selected.error)selected={angle,power,error}}s.enemyAngle=selected.angle;s.enemyPower=selected.power;note('蓝队调整炮口，准备回击。');fire(1,selected.angle,selected.power)}
 function impact(x,y,side){s.ball=null;sfx('hurt');s.fx=Array.from({length:26},(_,i)=>({x,y,vx:Math.cos(i*2.4)*(70+i*3),vy:Math.sin(i*2.4)*(70+i*3)-35,life:.85+i%4*.1}));
  const damage=[0,0];for(let i=0;i<2;i++){const d=Math.hypot(x-TANK_X[i],y-(heightAt(s.terrain,TANK_X[i])-28));damage[i]=d<106?Math.round(48*(1-d/106)+(d<44?8:0)):0;s.hp[i]=Math.max(0,s.hp[i]-damage[i])}s.damage+=damage[1];
  if(x>=0&&x<=W){const radius=59;for(let i=Math.max(0,Math.floor((x-radius)/4));i<=Math.min(280,Math.ceil((x+radius)/4));i++){const dx=i*4-x;if(Math.abs(dx)<radius)s.terrain[i]=Math.min(592,Math.max(s.terrain[i],y+Math.sqrt(radius*radius-dx*dx)*.64))}s.craters++}
  note((side?'蓝队':'你的')+'落点 '+Math.round(x)+' · '+(damage[1]?'蓝队 −'+damage[1]:'')+(damage[0]?' 绿队 −'+damage[0]:'')+(!damage[0]&&!damage[1]?'地形形成新弹坑':''));
  if(s.hp[1]<=0&&s.hp[0]>0){s.won=true;s.phase='won';s.score=Math.max(1,1200-s.shots*70+s.hp[0]*3);s.best=Math.max(s.best||0,s.score);note('炮战完成：'+s.shots+' 发炮弹，保留 '+s.hp[0]+' 点装甲。');sfx('success')}else if(s.hp[0]<=0){s.phase='lost';note('绿队装甲耗尽。可以重新布置炮位，再来一局。')}else{s.phase=side?'next':'enemy';s.delay=side?.8:1.0}sync();
 }
 function tick(dt){if(!active)return;s.elapsed+=dt;if(s.phase==='aim'){if(input.pressed.has('ArrowLeft')||input.pressed.has('KeyA'))s.angle=clamp(s.angle-1,15,80);if(input.pressed.has('ArrowRight')||input.pressed.has('KeyD'))s.angle=clamp(s.angle+1,15,80);if(input.pressed.has('ArrowUp')||input.pressed.has('KeyW'))s.power=clamp(s.power+1,20,100);if(input.pressed.has('ArrowDown')||input.pressed.has('KeyS'))s.power=clamp(s.power-1,20,100);if(input.pressed.has('Space')||input.pressed.has('KeyJ'))fire();sync()}
  if(['flight','enemyFlight'].includes(s.phase)&&s.ball){let left=dt;while(left>0&&s.ball){const h=Math.min(STEP,left),b=s.ball;moveBall(b,h,s.wind);if(b.trail.length===0||Math.hypot(b.x-b.trail.at(-1).x,b.y-b.trail.at(-1).y)>8){b.trail.push({x:b.x,y:b.y});if(b.trail.length>55)b.trail.shift()}if(b.x<0||b.x>W||b.y>H||b.age>10){impact(clamp(b.x,0,W),Math.min(b.y,H),b.side);break}let hit=false;for(let i=0;i<2;i++)if(b.age>.2&&Math.hypot(b.x-TANK_X[i],b.y-(heightAt(s.terrain,TANK_X[i])-28))<31){impact(b.x,b.y,b.side);hit=true;break}if(!hit&&s.ball&&b.y>=heightAt(s.terrain,b.x))impact(b.x,heightAt(s.terrain,b.x),b.side);left-=h}}
  else if(['enemy','next'].includes(s.phase)){s.delay-=dt;if(s.delay<=0){if(s.phase==='enemy')enemyShot();else{s.round++;s.wind=WINDS[(s.round-1)%WINDS.length];s.phase='aim';note('第 '+s.round+' 回合 · 风力 '+s.wind+'，重新判断落点。');sync()}}}
  for(const f of s.fx){f.x+=f.vx*dt;f.y+=f.vy*dt;f.vy+=240*dt;f.life-=dt}s.fx=s.fx.filter(f=>f.life>0)
 }
 const pattern=ctx.createPattern(stone,'repeat');
 function terrainPath(){ctx.beginPath();ctx.moveTo(0,H);s.terrain.forEach((y,i)=>ctx.lineTo(i*4,y));ctx.lineTo(W,H);ctx.closePath()}
 function drawTank(i){const x=TANK_X[i],y=heightAt(s.terrain,x),dir=i?-1:1,a=(i?s.enemyAngle:s.angle)*Math.PI/180,body=art[i?'azure':'olive'],barrel=art[i?'azure-barrel':'olive-barrel'];ctx.save();ctx.translate(x,y);const slope=Math.atan2(heightAt(s.terrain,x+25)-heightAt(s.terrain,x-25),50);ctx.rotate(clamp(slope,-.15,.15));ctx.scale(dir,1);ctx.drawImage(body,-67,-57,134,57);ctx.restore();ctx.save();ctx.translate(x,y-34);ctx.scale(dir,1);ctx.rotate(-a);ctx.drawImage(barrel,-12,-12,76,24);ctx.restore();label(ctx,i?'蓝队炮位':'绿队炮位',x,y+29,i?'#a9dbe7':'#d1e0b1',15);ctx.fillStyle='rgba(10,19,23,.86)';ctx.fillRect(x-50,y-93,100,9);ctx.fillStyle=i?'#83b9cc':'#b0c780';ctx.fillRect(x-50,y-93,100*s.hp[i]/110,9);label(ctx,s.hp[i]+' / 110',x,y-102,'#edebe1',13)}
 function draw(){cover(ctx,art.scene);ctx.fillStyle='rgba(8,22,30,.12)';ctx.fillRect(0,0,W,H);terrainPath();ctx.save();ctx.clip();ctx.fillStyle=pattern;ctx.fillRect(0,395,W,H-395);const earth=ctx.createLinearGradient(0,420,0,H);earth.addColorStop(0,'rgba(60,80,62,.48)');earth.addColorStop(1,'rgba(14,32,38,.91)');ctx.fillStyle=earth;ctx.fillRect(0,400,W,H-400);ctx.restore();ctx.beginPath();s.terrain.forEach((y,i)=>i?ctx.lineTo(i*4,y):ctx.moveTo(0,y));ctx.strokeStyle='#bec18b';ctx.lineWidth=5;ctx.stroke();ctx.strokeStyle='rgba(205,211,143,.33)';ctx.lineWidth=2;ctx.stroke();
  if(s.phase==='aim'){const p=trace(s.terrain,0,s.angle,s.power,s.wind);ctx.save();ctx.setLineDash([3,11]);ctx.lineWidth=2;ctx.strokeStyle='rgba(241,217,152,.7)';ctx.beginPath();p.points.forEach((v,i)=>i?ctx.lineTo(v.x,v.y):ctx.moveTo(v.x,v.y));ctx.stroke();ctx.setLineDash([]);if(p.x>=0&&p.x<=W){ctx.strokeStyle='#efcd7a';ctx.beginPath();ctx.ellipse(p.x,p.y,12,4,0,0,Math.PI*2);ctx.stroke();label(ctx,'预估落点',clamp(p.x,62,W-62),p.y+31,'#e9d495',13)}ctx.restore()}
  drawTank(0);drawTank(1);
  if(s.ball){ctx.save();ctx.lineWidth=3;ctx.strokeStyle=s.ball.side?'rgba(160,212,233,.65)':'rgba(240,209,142,.8)';ctx.beginPath();s.ball.trail.forEach((v,i)=>i?ctx.lineTo(v.x,v.y):ctx.moveTo(v.x,v.y));ctx.stroke();ctx.restore();glow(ctx,s.ball.x,s.ball.y,21,'rgba(255,204,93,.48)');ctx.fillStyle='#fff4c4';ctx.beginPath();ctx.arc(s.ball.x,s.ball.y,5,0,Math.PI*2);ctx.fill()}
  for(const f of s.fx){ctx.globalAlpha=Math.min(1,f.life);ctx.fillStyle=f.life>.4?'#e0b46a':'#495b52';ctx.fillRect(f.x,f.y,5,5)}ctx.globalAlpha=1;
  ctx.fillStyle='rgba(10,24,31,.87)';ctx.fillRect(28,26,300,84);ctx.fillRect(W-281,26,253,84);ctx.textAlign='left';ctx.font='12px "Microsoft YaHei",sans-serif';ctx.fillStyle='#d8b880';ctx.fillText('BALLISTIC / WIND / TERRAIN',46,49);ctx.font='bold 25px "Microsoft YaHei",sans-serif';ctx.fillStyle='#f3ecdb';ctx.fillText('岬湾炮阵',46,82);ctx.textAlign='right';ctx.font='15px "Microsoft YaHei",sans-serif';ctx.fillStyle='#d4e2dd';ctx.fillText('第 '+s.round+' 回合 · '+(s.wind<0?'←':'→')+' 风力 '+Math.abs(s.wind),W-46,54);ctx.fillStyle='#e6bd72';ctx.fillText(s.phase==='aim'?'你的指令':s.phase==='won'?'炮战完成':s.phase==='lost'?'装甲耗尽':'弹道结算中',W-46,83);
  if(['won','lost'].includes(s.phase)){ctx.fillStyle='rgba(8,21,27,.88)';ctx.fillRect(355,213,410,128);label(ctx,s.won?'炮阵试炼完成':'重新判断风向与射角',560,255,s.won?'#e7d39b':'#e4b0a0',24);label(ctx,s.won?s.shots+' 发 · 装甲 '+s.hp[0]:'点击下方“重新开局”',560,303,'#d9e4dd',17)}
 }
 function reset(){s=fresh(s.best);sync()}
 sync();return {tick,draw,getState:()=>({...structuredClone(s),physics:{gravity:GRAVITY,step:STEP,tankX:TANK_X},predicted:trace(s.terrain,0,s.angle,s.power,s.wind)}),getStatus:()=>({goal:s.won?'岬湾炮阵已完成':s.phase==='lost'?'装甲耗尽，重新开局':'调节角度和力度，击破蓝队炮位',message:s.log[0],stats:['回合 '+s.round,'角度 '+s.angle+'°','力度 '+s.power+'%','绿队 '+s.hp[0],'蓝队 '+s.hp[1],'弹坑 '+s.craters],actions:[action('发射炮弹',()=>fire(),s.phase!=='aim'),action('角度 −5°',()=>{s.angle=clamp(s.angle-5,15,80);sync()},s.phase!=='aim'),action('角度 +5°',()=>{s.angle=clamp(s.angle+5,15,80);sync()},s.phase!=='aim'),action('力度 −5%',()=>{s.power=clamp(s.power-5,20,100);sync()},s.phase!=='aim'),action('力度 +5%',()=>{s.power=clamp(s.power+5,20,100);sync()},s.phase!=='aim'),action('重新开局',reset)]}),setActive(value){active=value;sync()},dispose(){controls.remove();surface.element.remove()}};
}
