import {W,H,clamp,hash,images,canvasSurface} from './showcase-core.js';
import {pointerPosition} from './showcase-precision-kit.js';
import {sceneHeading,completion} from './showcase-observation-kit.js?v=20261004-2';
import {logicPanel,atlasSprite} from './showcase-logic-kit.js?v=20261004-1';

export const SONAR={cols:8,rows:8,mines:10};
export function sonarNeighbors(i){const x=i%8,y=Math.floor(i/8),out=[];for(let dy=-1;dy<=1;dy++)for(let dx=-1;dx<=1;dx++){if(!dx&&!dy)continue;const a=x+dx,b=y+dy;if(a>=0&&a<8&&b>=0&&b<8)out.push(b*8+a)}return out}
export function sonarFresh(seed=314159){return {version:1,seed,mines:[],open:Array(64).fill(false),flags:Array(64).fill(false),selected:35,first:-1,phase:'play',won:false,mode:'open',elapsed:0,moves:0,large:false}}
export function sonarNumber(s,i){return sonarNeighbors(i).filter(k=>s.mines.includes(k)).length}
export function sonarGenerate(s,first){const forbidden=new Set([first,...sonarNeighbors(first)]),available=Array.from({length:64},(_,i)=>i).filter(i=>!forbidden.has(i)),random=hash(s.seed^first*1664525);for(let n=available.length-1;n>0;n--){const k=Math.floor(random()*(n+1));[available[n],available[k]]=[available[k],available[n]]}s.mines=available.slice(0,10).sort((a,b)=>a-b);s.first=first}
export function sonarReveal(s,index){if(s.phase!=='play'||!Number.isInteger(index)||index<0||index>=64||s.flags[index]||s.open[index])return {opened:[],hit:false};if(!s.mines.length)sonarGenerate(s,index);s.selected=index;s.moves++;if(s.mines.includes(index)){s.open[index]=true;s.phase='lost';return {opened:[index],hit:true}}const queue=[index],seen=new Set(),opened=[];for(let n=0;n<queue.length;n++){const i=queue[n];if(seen.has(i)||s.open[i]||s.flags[i]||s.mines.includes(i))continue;seen.add(i);s.open[i]=true;opened.push(i);if(sonarNumber(s,i)===0)queue.push(...sonarNeighbors(i))}s.won=s.open.every((v,i)=>v||s.mines.includes(i));if(s.won)s.phase='won';return {opened,hit:false}}
export function sonarFlag(s,index=s.selected){if(s.phase!=='play'||!Number.isInteger(index)||index<0||index>=64||s.open[index])return false;if(!s.flags[index]&&s.flags.filter(Boolean).length>=10)return false;s.flags[index]=!s.flags[index];s.selected=index;s.moves++;return true}
export function sonarChord(s,index=s.selected){if(s.phase!=='play'||!s.open[index]||s.mines.includes(index))return {opened:[],hit:false,unready:true};const neighbors=sonarNeighbors(index);if(neighbors.filter(k=>s.flags[k]).length!==sonarNumber(s,index))return {opened:[],hit:false,unready:true};const result={opened:[],hit:false};for(const k of neighbors){const r=sonarReveal(s,k);result.opened.push(...r.opened);if(r.hit){result.hit=true;break}}return result}
export function sonarHint(s){if(!s.mines.length)return {kind:'first',index:s.selected,source:-1};if(s.phase!=='play')return null;for(let i=0;i<64;i++){if(!s.open[i]||s.mines.includes(i))continue;const nearby=sonarNeighbors(i),hidden=nearby.filter(k=>!s.open[k]&&!s.flags[k]),flags=nearby.filter(k=>s.flags[k]).length,n=sonarNumber(s,i);if(!hidden.length)continue;if(flags===n)return {kind:'safe',index:hidden[0],source:i};if(n-flags===hidden.length)return {kind:'mine',index:hidden[0],source:i}}return null}
export function sonarRestore(raw){const s=sonarFresh(Number.isInteger(raw?.seed)?raw.seed:314159);if(raw?.version!==1||!Array.isArray(raw.open)||!Array.isArray(raw.flags)||raw.open.length!==64||raw.flags.length!==64||!raw.open.every(v=>typeof v==='boolean')||!raw.flags.every(v=>typeof v==='boolean'))return s;s.selected=Number.isInteger(raw.selected)?clamp(raw.selected,0,63):35;s.mode=raw.mode==='flag'?'flag':'open';s.large=raw.large===true;s.elapsed=Number.isFinite(raw.elapsed)?clamp(raw.elapsed,0,86400):0;s.moves=Number.isInteger(raw.moves)?clamp(raw.moves,0,100000):0;if(Number.isInteger(raw.first)&&raw.first>=0&&raw.first<64){sonarGenerate(s,raw.first);if(!Array.isArray(raw.mines)||JSON.stringify(raw.mines)!==JSON.stringify(s.mines))return sonarFresh(s.seed);s.open=[...raw.open];s.flags=raw.flags.map((v,i)=>v&&!s.open[i]);if(s.flags.filter(Boolean).length>10)s.flags.fill(false);const hit=s.mines.some(i=>s.open[i]);s.won=!hit&&s.open.every((v,i)=>v||s.mines.includes(i));s.phase=hit?'lost':s.won?'won':'play'}else{s.flags=[...raw.flags];if(s.flags.filter(Boolean).length>10)s.flags.fill(false)}return s}
export function sonarGeometry(s){const size=s.large?61:55;return {size,x:(W-8*size)/2,y:s.large?91:111}}
const address=i=>String.fromCharCode(65+i%8)+(Math.floor(i/8)+1);

export async function createSonar({host,input,saved,sfx=()=>{}}){
 const art=await images(['sea','tiles'],'assets/game-forms/sonar/'),{element,ctx}=canvasSurface(host);element.style.touchAction='none';element.setAttribute('aria-label','深海测绘：点格探测，右键标记；方向键选格，空格探测，E 标记，C 邻格快开');
 let s=sonarRestore(saved),active=false,time=0,highlight=null,ripples=[],message=s.won?'这片遗迹已完成安全测绘。':s.phase==='lost'?'上次探测触发了暗雷，可重开测绘。':s.first>=0?'已恢复上次测绘，数字表示周围八格的暗雷数。':'第一格和周围八格保证安全。先探测，再用数字推理。';
 const ui=logicPanel(host,'sonar',`<div class="logic-toolbar"><span class="readout"></span><button class="primary reveal">探测选中格</button><button class="flag">标记选中格</button><button class="chord">邻格快开</button><button class="hint">解释一条线索</button><button class="mode" aria-pressed="false">点格：探测</button><button class="zoom" aria-pressed="false">棋盘放大：关</button><button class="retry">重开测绘</button></div><div class="logic-pad" role="group" aria-label="选择探测格"><button data-dir="left">← 左格</button><button data-dir="up">↑ 上格</button><button data-dir="down">↓ 下格</button><button data-dir="right">→ 右格</button></div><p class="logic-note">数字表示周围八格中的暗雷数。标记齐某个数字周围的暗雷，再选该数字“邻格快开”。解释只根据可见数字与现有标记，错误标记可能误导判断。窄屏可用选格按钮探测。</p>`);
 const q=k=>ui.panel.querySelector('.'+k),reveal=q('reveal'),flag=q('flag'),chord=q('chord'),hint=q('hint'),mode=q('mode'),zoom=q('zoom'),retry=q('retry'),readout=q('readout'),pad=[...ui.panel.querySelectorAll('[data-dir]')];
 function sync(){const playing=active&&s.phase==='play';reveal.disabled=!playing||s.open[s.selected]||s.flags[s.selected];flag.disabled=!playing||s.open[s.selected];chord.disabled=!playing||!s.open[s.selected]||!s.mines.length;hint.disabled=mode.disabled=!playing;zoom.disabled=retry.disabled=!active;pad.forEach(b=>b.disabled=!playing);mode.textContent='点格：'+(s.mode==='open'?'探测':'标记');mode.setAttribute('aria-pressed',String(s.mode==='flag'));zoom.textContent='棋盘放大：'+(s.large?'开':'关');zoom.setAttribute('aria-pressed',String(s.large));readout.textContent=`选中 ${address(s.selected)} · 标记 ${s.flags.filter(Boolean).length}/10 · 安全 ${s.open.filter((v,i)=>v&&!s.mines.includes(i)).length}/54 · ${Math.floor(s.elapsed)} 秒`}
 function report(result){if(result.unready){message='先选已揭开的数字，并让相邻标记数等于该数字。';return}highlight=null;for(const i of result.opened)ripples.push({i,life:1});message=result.hit?'探测触发暗雷。查看数字与标记，重开测绘再试。':s.won?'全部 54 个安全格已揭开，遗迹测绘完成。':result.opened.length?`已探测 ${result.opened.length} 格。数字表示八个邻格中的暗雷数量。`:'这格已经揭开或被标记，先取消标记再探测。';if(result.opened.length)sfx(result.hit?'hurt':s.won?'success':'turn');sync()}
 reveal.onclick=()=>{if(active)report(sonarReveal(s,s.selected))};flag.onclick=()=>{if(active&&sonarFlag(s)){highlight=null;message=s.flags[s.selected]?address(s.selected)+' 已标记疑似暗雷。':address(s.selected)+' 已取消标记。';sfx('turn');sync()}};chord.onclick=()=>{if(active)report(sonarChord(s))};hint.onclick=()=>{if(!active)return;highlight=sonarHint(s);if(!highlight){message='当前没有简单的确定线索。结合多个数字推理；这轮布局可能需要进一步判断。';return}s.selected=highlight.index;message=highlight.kind==='first'?'先探测 '+address(s.selected)+'，第一格和周围八格保证安全。':highlight.kind==='safe'?`${address(highlight.source)} 的数字已被邻格标记满足：未标记的 ${address(s.selected)} 可探测（前提是标记正确）。`:`${address(highlight.source)} 缺少的暗雷数等于未揭格数：${address(s.selected)} 应标记（前提是标记正确）。`;sync()};mode.onclick=()=>{if(active){s.mode=s.mode==='open'?'flag':'open';sync()}};zoom.onclick=()=>{if(active){s.large=!s.large;sync()}};retry.onclick=()=>{if(active){s=sonarFresh(s.seed+1);highlight=null;ripples=[];message='新测绘已准备好，首击周围仍保证安全。';sync()}};
 function move(d){if(!active||s.phase!=='play')return;const x=s.selected%8,y=Math.floor(s.selected/8);s.selected=clamp(y+(d==='down'?1:d==='up'?-1:0),0,7)*8+clamp(x+(d==='right'?1:d==='left'?-1:0),0,7);sync()}pad.forEach(b=>b.onclick=()=>move(b.dataset.dir));
 const cell=e=>{const p=pointerPosition(element,e),g=sonarGeometry(s),x=Math.floor((p.x-g.x)/g.size),y=Math.floor((p.y-g.y)/g.size);return x>=0&&x<8&&y>=0&&y<8?y*8+x:-1};
 const click=e=>{if(!active||s.phase!=='play')return;const i=cell(e);if(i<0)return;s.selected=i;if(s.mode==='flag')flag.click();else if(s.open[i])chord.click();else reveal.click();sync()},context=e=>{e.preventDefault();if(!active||s.phase!=='play')return;const i=cell(e);if(i>=0){s.selected=i;flag.click()}};element.addEventListener('click',click);element.addEventListener('contextmenu',context);
 function tick(dt){if(!active)return;dt=Number.isFinite(dt)?clamp(dt,0,.25):0;time+=dt;if(s.mines.length&&s.phase==='play')s.elapsed+=dt;for(const p of ripples)p.life-=dt;ripples=ripples.filter(p=>p.life>0);for(const [key,d] of [['ArrowLeft','left'],['KeyA','left'],['ArrowUp','up'],['KeyW','up'],['ArrowDown','down'],['KeyS','down'],['ArrowRight','right'],['KeyD','right']])if(input.pressed.has(key))move(d);if(input.pressed.has('Space'))reveal.click();if(input.pressed.has('KeyE'))flag.click();if(input.pressed.has('KeyC'))chord.click();sync()}
 function draw(){ctx.drawImage(art.sea,0,0,W,H);const g=sonarGeometry(s);ctx.save();ctx.shadowColor='#000';ctx.shadowBlur=22;ctx.fillStyle='#061e27cc';ctx.beginPath();ctx.roundRect(g.x-11,g.y-11,g.size*8+22,g.size*8+22,10);ctx.fill();ctx.strokeStyle='#b1c6a67a';ctx.lineWidth=2;ctx.stroke();ctx.restore();for(let i=0;i<64;i++){const x=g.x+(i%8+.5)*g.size,y=g.y+(Math.floor(i/8)+.5)*g.size,isMine=s.mines.includes(i),shownMine=isMine&&(s.phase==='lost'||s.open[i]);atlasSprite(ctx,art.tiles,shownMine?3:s.flags[i]?2:s.open[i]?1:0,x,y,g.size+1);if(s.open[i]&&!isMine){const n=sonarNumber(s,i);ctx.save();ctx.textAlign='center';ctx.textBaseline='middle';if(n){ctx.font=`700 ${g.size*.49}px Georgia,serif`;ctx.fillStyle=['','#10383d','#144948','#503b19','#413956','#6c3534','#27496c','#50394c','#284439'][n];ctx.fillText(n,x,y+1)}else{ctx.fillStyle='#30716e';ctx.beginPath();ctx.arc(x,y,2,0,Math.PI*2);ctx.fill()}ctx.restore()}if(s.flags[i]&&!isMine&&s.phase==='lost'){ctx.save();ctx.strokeStyle='#fc9b81';ctx.lineWidth=3;ctx.beginPath();ctx.moveTo(x-11,y-11);ctx.lineTo(x+11,y+11);ctx.moveTo(x+11,y-11);ctx.lineTo(x-11,y+11);ctx.stroke();ctx.restore()}}
 ctx.save();ctx.strokeStyle='#ffe6a9';ctx.lineWidth=2.5;ctx.strokeRect(g.x+s.selected%8*g.size+3,g.y+Math.floor(s.selected/8)*g.size+3,g.size-6,g.size-6);if(highlight&&highlight.source>=0){ctx.strokeStyle='#97f4e6';ctx.setLineDash([4,4]);ctx.strokeRect(g.x+highlight.source%8*g.size+4,g.y+Math.floor(highlight.source/8)*g.size+4,g.size-8,g.size-8)}for(const p of ripples){ctx.strokeStyle=`rgba(161,245,224,${p.life*.5})`;ctx.beginPath();ctx.arc(g.x+(p.i%8+.5)*g.size,g.y+(Math.floor(p.i/8)+.5)*g.size,(1-p.life)*g.size*.7+8,0,Math.PI*2);ctx.stroke()}ctx.setLineDash([]);ctx.textAlign='center';ctx.fillStyle='#e8e3c3';ctx.font='12px sans-serif';for(let x=0;x<8;x++)ctx.fillText(String.fromCharCode(65+x),g.x+(x+.5)*g.size,g.y-16);ctx.textAlign='right';for(let y=0;y<8;y++)ctx.fillText(y+1,g.x-17,g.y+(y+.5)*g.size+4);ctx.restore();sceneHeading(ctx,'深海测绘',`八邻格数字推理 · 首击安全 · 10 枚暗雷     ${s.mode==='flag'?'标记模式':'探测模式'}`);if(s.won)completion(ctx,'遗迹安全测绘完成',`${Math.floor(s.elapsed)} 秒 · ${s.moves} 次操作 · 54 格已探明`);else if(s.phase==='lost')completion(ctx,'探测触发暗雷','暗雷位置已揭示 · 下方可开始新的测绘')}
 sync();return {tick,draw,onStart(){active=true;sync()},setActive(v){if(active===v)return;active=v;sync()},getState(){return structuredClone(s)},getStatus(){return {goal:s.won?'54 个安全格全部探明':s.phase==='lost'?'重开测绘再试':'用数字推理，揭开全部 54 个安全格',message,stats:[`安全 ${s.open.filter((v,i)=>v&&!s.mines.includes(i)).length}/54`,`标记 ${s.flags.filter(Boolean).length}/10`,`选中 ${address(s.selected)}`],actions:[]}},dispose(){element.removeEventListener('click',click);element.removeEventListener('contextmenu',context);ui.dispose()}};
}
