import {THREE,modelsAt,fitModel,surface3D,projectPoint} from './showcase-3d-kit.js';
import {clamp,action,safeSaved,hash} from './showcase-core.js';

export const FLIGHT_GATES=[{x:0,y:25,z:-180},{x:65,y:40,z:-430},{x:-35,y:25,z:-700},{x:80,y:60,z:-980},{x:-70,y:32,z:-1240},{x:15,y:80,z:-1500},{x:-15,y:50,z:-1760},{x:0,y:35,z:-2050}];
const defaults={version:1,x:0,y:25,z:70,yaw:0,pitch:0,roll:0,speed:34,boost:100,integrity:100,gate:0,camera:'chase',elapsed:0,collisions:0,distance:0,score:0,won:false,phase:'flight',checkpoint:{x:0,y:25,z:70,gate:0},respawns:0};
export async function createPilot({host,input,saved,notify,sfx}){
 const models=await modelsAt('assets/game-forms/pilot/',['craft_speederA','craft_speederB','meteor_detailed','hangar_roundGlass','satelliteDish']);
 const world=surface3D(host,{fov:64,far:7000}),{scene,camera,element,renderer}=world;let s=safeSaved(saved,defaults),hitCD=0,boostLatch=0,levelLatch=0,engineTick=0;
 element.setAttribute('aria-label','星环试航，真正三维飞行。左右转向，上下升降，C加速，R减速，空格恢复水平，E切换机后与座舱镜头。');
 const sky=await new THREE.TextureLoader().loadAsync('assets/game-forms/pilot/sky.webp');sky.mapping=THREE.EquirectangularReflectionMapping;sky.colorSpace=THREE.SRGBColorSpace;scene.background=sky;scene.environment=sky;
 scene.add(new THREE.HemisphereLight(0xbfecff,0x33496d,2));const sun=new THREE.DirectionalLight(0xffdcc3,3);sun.position.set(-150,220,100);scene.add(sun);
 const ship=fitModel(models.craft_speederA,6.5,'x');scene.add(ship);ship.traverse(o=>{if(o.isMesh){o.material=o.material.clone();o.material.metalness=.25;o.material.roughness=.48}});
 const driveMaterial=new THREE.MeshBasicMaterial({color:0x83e8ff,transparent:true,opacity:.8}),drive=new THREE.Mesh(new THREE.ConeGeometry(.08,.85,14),driveMaterial);drive.rotation.x=-Math.PI/2;drive.position.set(0,0,-.75);ship.add(drive);
 const gateObjects=FLIGHT_GATES.map((p,i)=>{const group=new THREE.Group();group.position.set(p.x,p.y,p.z);const ring=new THREE.Mesh(new THREE.TorusGeometry(32,1.05,10,64),new THREE.MeshStandardMaterial({color:i===s.gate?0x9ee8dd:0x376977,emissive:i===s.gate?0x76dec9:0x143b4e,emissiveIntensity:.8,metalness:.55,roughness:.24}));group.add(ring);for(let n=0;n<4;n++){const plate=new THREE.Mesh(new THREE.BoxGeometry(6,2,4),new THREE.MeshStandardMaterial({color:0xe7bc77,metalness:.6,roughness:.32}));plate.position.set(Math.cos(n*Math.PI/2)*32,Math.sin(n*Math.PI/2)*32,0);plate.rotation.z=n*Math.PI/2;group.add(plate)}scene.add(group);return group});
 const random=hash(734261),asteroids=[];
 for(let i=0;i<65;i++){const object=fitModel(models.meteor_detailed,10+random()*16,'x'),x=(random()>.5?1:-1)*(100+random()*310),y=-80+random()*240,z=130-random()*2500;object.position.set(x,y,z);object.rotation.set(random()*4,random()*4,random()*4);scene.add(object);asteroids.push({object,x,y,z,r:8+random()*7})}
 for(let i=0;i<3;i++){const station=fitModel(models.hangar_roundGlass,50,'x');station.position.set(i===1?-110:150,10,-350-i*800);station.rotation.y=.5;scene.add(station);const dish=fitModel(models.satelliteDish,18,'y');dish.position.set(station.position.x,station.position.y+26,station.position.z);scene.add(dish)}
 const escorts=[0,1].map(i=>{const object=fitModel(models.craft_speederB,7,'x');scene.add(object);return object});
 const stars=new Float32Array(2400*3);for(let i=0;i<stars.length;i++)stars[i]=(random()-.5)*4300;const starGeo=new THREE.BufferGeometry();starGeo.setAttribute('position',new THREE.BufferAttribute(stars,3));scene.add(new THREE.Points(starGeo,new THREE.PointsMaterial({color:0xc7e9f1,size:1.9,transparent:true,opacity:.65,depthWrite:false})));
 const hud=document.createElement('div');hud.className='flight3d-hud';hud.innerHTML='<div class="nav-brand"><small>ORBIT / FLIGHT</small><b>星环试航</b><span></span></div><div class="flight-meter"><strong></strong><small>M / S</small><span></span></div><div class="flight-attitude"><i></i><b>+</b><em></em></div><div class="flight-target"><i>◇</i><b></b></div><div class="flight-compass"></div><div class="flight-cockpit" hidden></div><div class="nav-end" hidden><b></b><p></p></div>';host.append(hud);
 const forward=()=>new THREE.Vector3(Math.sin(s.yaw)*Math.cos(s.pitch),Math.sin(s.pitch),-Math.cos(s.yaw)*Math.cos(s.pitch));
 function toggleView(){s.camera=s.camera==='chase'?'cockpit':'chase';sfx('turn')}
 function retry(){const cp=s.checkpoint;Object.assign(s,{...cp,speed:34,yaw:0,pitch:0,roll:0,integrity:100,phase:'flight',won:false});s.respawns++;hitCD=2;notify('已返回最近信标之后。对准下一座光环继续飞行。')}
 function restart(){s=structuredClone(defaults);hitCD=boostLatch=levelLatch=0;sync();notify('新的试航开始。方向键转向和升降，对准下一座光环。')}
 function tick(dt){
  hitCD=Math.max(0,hitCD-dt);boostLatch=Math.max(0,boostLatch-dt);levelLatch=Math.max(0,levelLatch-dt);if(s.won||s.phase==='down')return;s.elapsed+=dt;
  if(input.pressed.has('KeyE'))toggleView();if(input.pressed.has('Space'))levelLatch=1.4;
  s.yaw+=input.x*.58*dt+input.look.x*.0021;s.pitch=clamp(s.pitch-input.y*.43*dt-input.look.y*.0017,-1.05,1.05);if(levelLatch>0)s.pitch*=Math.exp(-3.4*dt);s.roll=THREE.MathUtils.lerp(s.roll,-input.x*.62,Math.min(1,dt*5));
  const boosting=(input.keys.has('KeyC')||boostLatch>0)&&s.boost>0,braking=input.keys.has('KeyR');s.boost=clamp(s.boost+(boosting?-22:8)*dt,0,100);s.speed=THREE.MathUtils.lerp(s.speed,braking?14:boosting?65:38,Math.min(1,dt*1.5));
  const f=forward(),before={x:s.x,y:s.y,z:s.z};s.x+=f.x*s.speed*dt;s.y+=f.y*s.speed*dt;s.z+=f.z*s.speed*dt;s.distance+=s.speed*dt;
  const gate=FLIGHT_GATES[s.gate];if(gate){const crossed=(before.z-gate.z)*(s.z-gate.z)<=0;if(crossed&&Math.hypot(s.x-gate.x,s.y-gate.y)<30){s.gate++;s.score+=500;s.checkpoint={x:gate.x,y:gate.y,z:gate.z-35,gate:s.gate};sfx('pickup');notify('光环 '+s.gate+'/8 已通过。下一座信标已点亮。');if(s.gate===FLIGHT_GATES.length){s.won=true;s.score+=Math.max(0,Math.round(s.integrity*10));sfx('success');notify('八座信标航线完成。自由控制的航向、俯仰与速度已记录。')}}}
  if(hitCD===0){const obstacle=asteroids.find(a=>Math.hypot(a.x-s.x,a.y-s.y,a.z-s.z)<a.r+2);if(obstacle){s.integrity=Math.max(0,s.integrity-20);s.speed*=.5;s.collisions++;hitCD=1.5;sfx('hurt')}}
  if(s.integrity<=0||Math.abs(s.x)>1100||s.y< -600||s.y>900||s.z>1300||s.z< -2900){s.phase='down';notify('离开试航区域，可以返回最近已通过的信标。')}
  engineTick-=dt;if(engineTick<=0){sfx(boosting?'engineBoost':'engine',s.speed);engineTick=.28}sync(dt,boosting);
 }
 function sync(dt=0,boosting=false){
  const f=forward(),p=new THREE.Vector3(s.x,s.y,s.z);ship.position.copy(p);ship.quaternion.setFromUnitVectors(new THREE.Vector3(0,0,1),f);ship.rotateZ(s.roll);ship.visible=s.camera==='chase';drive.scale.y=boosting?1.7:1+Math.sin(s.elapsed*31)*.15;
  escorts.forEach((o,i)=>{o.position.copy(p).add(new THREE.Vector3(i?44:-44,Math.sin(s.elapsed*.45+i)*9, -65));o.quaternion.copy(ship.quaternion)});
  const eye=p.clone().addScaledVector(f,s.camera==='chase'?-16:1.6);eye.y+=s.camera==='chase'?5.5:.5;camera.position.copy(eye);camera.up.set(Math.sin(-s.roll*.25),Math.cos(s.roll*.25),0);camera.lookAt(p.clone().addScaledVector(f,80));camera.fov=64+(boosting?7:0);camera.updateProjectionMatrix();
  gateObjects.forEach((o,i)=>{o.visible=i>=s.gate;const m=o.children[0].material;m.color.set(i===s.gate?'#91edd7':'#385e76');m.emissive.set(i===s.gate?'#53bca6':'#173249')});
  hud.querySelector('.nav-brand span').textContent='信标 '+s.gate+'/8 · 船体 '+Math.round(s.integrity)+'%';hud.querySelector('.flight-meter strong').textContent=Math.round(s.speed);hud.querySelector('.flight-meter span').textContent='高度 '+Math.round(s.y)+' m · 加速 '+Math.round(s.boost)+'%';hud.querySelector('.flight-attitude i').style.transform='translateY('+s.pitch*55+'px) rotate('+(-s.roll*180/Math.PI)+'deg)';hud.querySelector('.flight-attitude em').textContent='航向 '+((s.yaw*180/Math.PI%360+360)%360).toFixed(0)+'°';hud.querySelector('.flight-cockpit').hidden=s.camera!=='cockpit';
  const target=hud.querySelector('.flight-target'),gate=FLIGHT_GATES[s.gate];target.hidden=!gate;
  if(gate){const q=projectPoint(camera,gate);target.style.left=clamp(q.x/1120*100,7,93)+'%';target.style.top=clamp(q.y/630*100,16,83)+'%';target.querySelector('b').textContent=Math.round(p.distanceTo(new THREE.Vector3(gate.x,gate.y,gate.z)))+' m';const desired=Math.atan2(gate.x-s.x,s.z-gate.z),delta=Math.atan2(Math.sin(desired-s.yaw),Math.cos(desired-s.yaw));hud.querySelector('.flight-compass').textContent=q.visible?'飞向绿色光环 · C 加速 · R 减速':'下一光环在'+(delta>0?'右侧 →':'← 左侧')+' · 转向寻找'}else hud.querySelector('.flight-compass').textContent='八座信标航线完成';
  const end=hud.querySelector('.nav-end');end.hidden=!(s.won||s.phase==='down');if(!end.hidden){end.querySelector('b').textContent=s.won?'星环航线完成':'返回信标，再次试航';end.querySelector('p').textContent='信标 '+s.gate+'/8 · 飞行 '+s.elapsed.toFixed(1)+' 秒 · 碰撞 '+s.collisions+' 次'}
 }
 sync();return {tick,draw(){sync();world.draw()},getState:()=>({...structuredClone(s),gates:FLIGHT_GATES,forward:forward().toArray(),nextScreen:FLIGHT_GATES[s.gate]?projectPoint(camera,FLIGHT_GATES[s.gate]):null}),getStatus:()=>({goal:s.won?'八座信标航线完成':s.phase==='down'?'返回最近信标':'自由驾驶，穿过八座信标光环',message:'方向键或 WASD：左右改变航向，上下改变俯仰。飞船持续推进，C 加速、R 减速、空格恢复水平、E 切换机后与座舱。也可拖动画面转向。漏过光环可转弯返回或重新定位到最近信标。',stats:['信标 '+s.gate+'/8','高度 '+Math.round(s.y)+'m','速度 '+Math.round(s.speed)+'m/s','船体 '+Math.round(s.integrity)+'%','飞行 '+s.elapsed.toFixed(1)+'秒'],actions:s.won?[action('重新试航',restart)]:[action('镜头：'+(s.camera==='chase'?'机后':'座舱')+' · E',toggleView),action('恢复水平 · 空格',()=>{levelLatch=1.4}),action('短时加速 · C',()=>{boostLatch=1},s.boost<15),action('返回最近信标',retry)]}),dispose(){hud.remove();world.dispose()}};
}
