import {W,H,clamp,images,canvasSurface} from './showcase-core.js';
import {pointerPosition} from './showcase-precision-kit.js';
import {observationPanel,sceneHeading} from './showcase-observation-kit.js?v=20261004-2';
import {freshNine,restoreNine,commandNine,stepNine,coverage,foldProject,foldConnected,FOLD_NODES,HOOK_ANCHORS,HOOK_TERRACES,REPAIR_NAMES,KITCHEN_STATIONS} from './showcase-nine-rules.js?v=20261004-1';

export const NINE_INFO={
 hook:{title:'风隙航渡',detail:'抓钩摆荡 · 惯性释放 · 峡谷通行',goal:'借三个挂点抵达右侧灯台',help:'左右方向增加摆动，挂点按钮切换目标；挂住、收绳或松绳保持惯性。第三个挂点适当收绳，松绳后向左减速落到灯台。落到中间平台记录起点。',actions:[['attach','挂住目标'],['release','松绳'],['reel','收绳'],['anchor:0','挂点 1'],['anchor:1','挂点 2'],['anchor:2','挂点 3'],['return','返回灯台']]},
 fold:{title:'折光回廊',detail:'旋转视角 · 断桥接续 · 错视行走',goal:'旋转视角，让断桥投影相接，抵达高台',help:'旋转镜头观察桥端，只有端点在画面中重合才能前行。青绿色环表示已经相接；先走到断桥边，再转动视角。',actions:[['rotate:-1','镜头左转'],['rotate:1','镜头右转'],['walk','沿路前行']]},
 repair:{title:'时光修复铺',detail:'工作台拆装 · 零件方向 · 安装顺序',goal:'修好一枚古旧怀表，并实际测试',help:'移开盖板→清洁→转正并装入机芯→表盘→后盖→测试。可拖动零件，也可选中后用方向按钮移动或移到表壳。装错方向和顺序不会通过。',actions:[['cover','移开 / 放回盖板'],['clean','清洁表壳'],['select:0','机芯'],['select:1','表盘'],['select:2','后盖'],['rotate','旋转 90°'],['center','移到表壳'],['place','安装选中'],['remove','拆下顶层'],['test','测试运行']]},
 delve:{title:'深层回声',detail:'挖掘地形 · 晶矿显露 · 纵向镜头',goal:'自行挖出路线，找到底层信标',help:'方向键或下方按钮逐格挖掘并移动；打开的洞壁永久留下，晶矿累计收集。镜头随深度向下，最底层第 G 列藏着古井信标。',actions:[['dig:0','↑ 向上挖'],['dig:3','← 向左挖'],['dig:1','→ 向右挖'],['dig:2','↓ 向下挖']]},
 cluster:{title:'收藏物语',detail:'滚动吸附 · 体积成长 · 镜头拉远',goal:'滚动收集庭院中的 28 件收藏物',help:'方向键或点地面滚动，只有当前体积能吸附的物件才会加入。已吸附物件真实附着在球体，体积和镜头尺度随收集变化。首版为俯视球体成长。',actions:[]},
 paint:{title:'流彩工场',detail:'涂地覆盖 · 形态切换 · 对手重涂',goal:'75 秒内让青色覆盖达到 58%',help:'方向键或点地面移动。喷涂消耗颜料，在自己的青色地面潜行可恢复颜料、加快移动；空白或珊瑚色地面会减慢潜行。',actions:[['spray','喷涂开 / 关'],['swim','切换潜行形态']]},
 swarm:{title:'苔庭小队',detail:'群体跟随 · 分队 · 搬运与修桥',goal:'分配小队，运回三件材料',help:'先搬左岸两件材料修桥，再派至少六个队员去右岸。每件货物需要足够队员到位才会移动；交付后自动归队，也可召回。',actions:[['select:0','左岸种箱 · 3 人'],['select:1','左岸石材 · 5 人'],['select:2','右岸灯箱 · 6 人'],['group','切换分队规模'],['dispatch','派遣小队'],['recall','召回全部']]},
 kitchen:{title:'夜港晚餐',detail:'同时订单 · 连续工序 · 工位服务',goal:'在顾客等待结束前完成三份热汤',help:'选工位走到台前，按操作工位：取番茄→切三次→入锅→等四秒→取汤→交付。三个订单同时等待；可先查看路线再开始。',actions:[['station:0','去取料台'],['station:1','去切配台'],['station:2','去灶台'],['station:3','去出餐台'],['work','操作当前工位']]},
 relay:{title:'雾海协作台',detail:'操作端 / 说明端 · 信息分工',goal:'按说明核对线路、旋钮和脉冲，恢复航灯',help:'操作端只能看装置序号，说明端只给规则。两人轮流看各自的端并交流，也可单人切换学习。首版为同设备交接式双端演示。',actions:[['role','切换操作 / 说明端'],['wire:teal','断开青绿线'],['wire:coral','断开珊瑚线'],['dial','旋钮 +1'],['button','脉冲 +1'],['verify','确认当前步骤']]}
};
function stamp(ctx,im,index,x,y,w,h=w,columns=4,angle=0,alpha=1){const sw=im.width/columns,sh=im.height/columns;ctx.save();ctx.globalAlpha=alpha;ctx.translate(x,y);ctx.rotate(angle);ctx.drawImage(im,(index%columns)*sw,Math.floor(index/columns)*sh,sw,sh,-w/2,-h/2,w,h);ctx.restore()}
function text(ctx,t,x,y,size=15,color='#f8e7bf',align='left'){ctx.save();ctx.font=`${size}px "Microsoft YaHei",sans-serif`;ctx.fillStyle=color;ctx.textAlign=align;ctx.fillText(t,x,y);ctx.restore()}
function plate(ctx,x,y,w,h,light=false){ctx.save();ctx.fillStyle=light?'#ede4cced':'#102830e8';ctx.strokeStyle=light?'#977c51':'#beae8388';ctx.lineWidth=1.5;ctx.shadowColor='#0006';ctx.shadowBlur=12;ctx.beginPath();ctx.roundRect(x,y,w,h,10);ctx.fill();ctx.stroke();ctx.restore()}
function ring(ctx,x,y,r,color='#ffd79a'){ctx.save();ctx.strokeStyle=color;ctx.lineWidth=2;ctx.shadowColor=color;ctx.shadowBlur=10;ctx.beginPath();ctx.arc(x,y,r,0,Math.PI*2);ctx.stroke();ctx.restore()}
function shadow(ctx,x,y,r){ctx.save();ctx.fillStyle='#0005';ctx.beginPath();ctx.ellipse(x,y,r,r*.34,0,0,Math.PI*2);ctx.fill();ctx.restore()}
function arrow(ctx,a,b,color='#e9d7a3'){ctx.save();ctx.strokeStyle=color;ctx.lineWidth=2;ctx.setLineDash([4,7]);ctx.beginPath();ctx.moveTo(a.x,a.y);ctx.lineTo(b.x,b.y);ctx.stroke();ctx.restore()}

export function drawNineScene(ctx,s,art,clock=0){const id=s.id,info=NINE_INFO[id];ctx.drawImage(art[id],0,0,W,H);
 if(id==='hook'){
  HOOK_TERRACES.forEach((p,i)=>{for(let j=0;j<Math.ceil(p.w/75);j++)stamp(ctx,art.props,14,p.x+j*65+35,p.y+16,93,56);text(ctx,i===0?'出发灯台':i===1?'中途灯台':'终点灯台',p.x+p.w/2,p.y+63,13,'#f3deaf','center')});
  HOOK_ANCHORS.forEach((a,i)=>{stamp(ctx,art.props,15,a.x,a.y,55);ring(ctx,a.x,a.y,27,i===s.selected?'#bdf2e4':'#dbc099');text(ctx,String(i+1),a.x,a.y-34,15,'#f7dfae','center')});
  if(s.anchor>=0){const a=HOOK_ANCHORS[s.anchor];ctx.save();ctx.strokeStyle='#273431';ctx.lineWidth=5;ctx.beginPath();ctx.moveTo(a.x,a.y);ctx.lineTo(s.p.x,s.p.y);ctx.stroke();ctx.strokeStyle='#f4d9aa';ctx.lineWidth=2;ctx.stroke();ctx.restore()}shadow(ctx,s.p.x,s.p.y+17,22);stamp(ctx,art.props,0,s.p.x,s.p.y,64,64,4,clamp(s.p.vx/1200,-.35,.35));
 }
 if(id==='fold'){
  // All faces and connections use the same rotating 3D coordinates.
  const p=(x,y,z)=>foldProject([x,y,z],s.yaw),path=points=>{ctx.beginPath();points.forEach((q,i)=>i?ctx.lineTo(q.x,q.y):ctx.moveTo(q.x,q.y));ctx.closePath()},poly=(points,color,top=false)=>{ctx.save();path(points);ctx.fillStyle=color;ctx.fill();ctx.clip();const xs=points.map(q=>q.x),ys=points.map(q=>q.y),x=Math.min(...xs),y=Math.min(...ys),w=Math.max(...xs)-x,h=Math.max(...ys)-y;ctx.globalAlpha=top?.65:.32;ctx.drawImage(art.stone,0,0,art.stone.width,art.stone.height,x,y,w,h);ctx.restore();path(points);ctx.strokeStyle=top?'#fbf1d5c9':'#86795666';ctx.lineWidth=top?2:1;ctx.stroke()};
  const walks=[0,2,4,6].map(j=>{const a=FOLD_NODES[j],b=FOLD_NODES[j+1],dx=b[0]-a[0],dz=b[2]-a[2],length=Math.hypot(dx,dz),ox=-dz/length*.31,oz=dx/length*.31,top=[p(a[0]+ox,a[1],a[2]+oz),p(b[0]+ox,b[1],b[2]+oz),p(b[0]-ox,b[1],b[2]-oz),p(a[0]-ox,a[1],a[2]-oz)];return {j,a,b,top,depth:top.reduce((v,q)=>v+q.y,0)/4}}).sort((a,b)=>a.depth-b.depth);
  for(const walk of walks){const {top,a,b}=walk,bottom=top.map(q=>({x:q.x,y:q.y+92}));ctx.save();ctx.shadowColor='#42665c55';ctx.shadowBlur=18;ctx.shadowOffsetY=12;path(bottom);ctx.fillStyle='#2e4f4930';ctx.fill();ctx.restore();const edges=top.map((q,i)=>({i,q,next:top[(i+1)%4],depth:(q.y+top[(i+1)%4].y)/2})).sort((a,b)=>a.depth-b.depth);for(const e of edges.slice(2))poly([e.q,e.next,bottom[(e.i+1)%4],bottom[e.i]],e.i%2?'#b9b298':'#d1c7a8');poly(top,'#f1e6cb',true);const aa=foldProject(a,s.yaw),bb=foldProject(b,s.yaw);ctx.save();ctx.strokeStyle='#ad9c7366';ctx.setLineDash([2,12]);ctx.beginPath();ctx.moveTo(aa.x,aa.y);ctx.lineTo(bb.x,bb.y);ctx.stroke();ctx.restore();}
  for(const j of [1,3,5]){const a=foldProject(FOLD_NODES[j],s.yaw),b=foldProject(FOLD_NODES[j+1],s.yaw);ring(ctx,a.x,a.y-5,10,Math.hypot(a.x-b.x,a.y-b.y)<2?'#70c9b6':'#cb986b');arrow(ctx,a,b,'#ad926d88')}
  const a=FOLD_NODES[s.node],b=FOLD_NODES[Math.min(7,s.node+1)],pos=foldProject(a.map((v,i)=>v+(b[i]-v)*s.walk),s.yaw);stamp(ctx,art.props,2,pos.x,pos.y-24,43);const end=foldProject(FOLD_NODES[7],s.yaw);ring(ctx,end.x,end.y-12,24,'#eee2a1');text(ctx,'旋转镜头，让桥端重合',560,576,17,'#365b53','center');
 }
 if(id==='repair'){
  stamp(ctx,art.parts,0,553,323,386,386,2);if(s.clean){ring(ctx,553,323,151,'#c0e0c49f')}for(const [i,p]of s.parts.entries())if(p.placed&&!(i===2&&s.tested))stamp(ctx,art.parts,i+1,p.x,p.y,i===0?290:i===1?323:340,undefined,2,p.angle*Math.PI/180);if(s.cover&&!s.tested)stamp(ctx,art.parts,3,553,323,352,352,2);
  for(const [i,p]of s.parts.entries())if(!p.placed){shadow(ctx,p.x,p.y+53,58);stamp(ctx,art.parts,i+1,p.x,p.y,143,143,2,p.angle*Math.PI/180);text(ctx,REPAIR_NAMES[i],p.x,p.y+76,14,'#f5e3b9','center');if(i===s.selected)ring(ctx,p.x,p.y,77)}
  plate(ctx,190,495,510,62);text(ctx,s.tested?'翻到正面 · 秒针开始走动':s.cover?'表壳封闭 · 先移开盖板':s.clean?'表壳已清洁 · 对正零件后分层安装':'表壳已打开 · 需要清洁',211,521,14);text(ctx,`已安装 ${s.parts.filter(p=>p.placed).length}/3 层`,211,545,13,'#b8dad2');if(s.tested){ring(ctx,553,323,165,'#9cf0d5');text(ctx,'机芯测试正常',553,132,20,'#f8db94','center');ctx.save();ctx.translate(553,323);ctx.rotate(clock*Math.PI/30);ctx.strokeStyle='#a05034';ctx.lineWidth=2.5;ctx.beginPath();ctx.moveTo(0,22);ctx.lineTo(0,-100);ctx.stroke();ctx.fillStyle='#b49357';ctx.beginPath();ctx.arc(0,0,6,0,Math.PI*2);ctx.fill();ctx.restore()}
 }
 if(id==='delve'){
  const size=43,x=302,offset=clamp((s.p.y-5)*size,0,22*size-460);ctx.save();ctx.beginPath();ctx.rect(x-10,98,12*size+20,474);ctx.clip();ctx.fillStyle='#071b25ed';ctx.fillRect(x-10,98,12*size+20,474);ctx.save();ctx.beginPath();s.cells.forEach((v,i)=>{if(v===1||v===2)ctx.rect(x+i%12*size,108+Math.floor(i/12)*size-offset,size+.5,size+.5)});ctx.clip();ctx.drawImage(art.delve,450,180,870,700,x,108-offset,12*size,22*size);ctx.fillStyle='#95816647';ctx.fillRect(x,108-offset,12*size,22*size);ctx.restore();s.cells.forEach((v,i)=>{const cx=i%12,cy=Math.floor(i/12),px=x+(cx+.5)*size,py=108+(cy+.5)*size-offset;if(py<70||py>610)return;if(v===2){stamp(ctx,art.props,13,px,py,size*.92);ring(ctx,px,py,15,'#7cb7ba50')}if(v===1||v===2){for(const [dx,dy]of [[1,0],[-1,0],[0,1],[0,-1]]){const nx=cx+dx,ny=cy+dy;if(nx>=0&&nx<12&&ny>=0&&ny<22&&s.cells[ny*12+nx]!==0)continue;ctx.save();ctx.strokeStyle='#b7bc9f9c';ctx.lineWidth=3;ctx.shadowColor='#9edbd566';ctx.shadowBlur=5;ctx.beginPath();if(dx){const xx=px+dx*size/2;ctx.moveTo(xx,py-size/2);ctx.lineTo(xx-dx*4,py-9);ctx.lineTo(xx+dx*2,py+8);ctx.lineTo(xx,py+size/2)}else{const yy=py+dy*size/2;ctx.moveTo(px-size/2,yy);ctx.lineTo(px-7,yy-dy*3);ctx.lineTo(px+8,yy+dy*2);ctx.lineTo(px+size/2,yy)}ctx.stroke();ctx.restore()}}if(v===3){stamp(ctx,art.props,5,px,py,40);ring(ctx,px,py,22,'#82f2e8')}});const px=x+(s.p.x+.5)*size,py=108+(s.p.y+.5)*size-offset;const g=ctx.createRadialGradient(px,py,5,px,py,100);g.addColorStop(0,'#b2e8d920');g.addColorStop(1,'transparent');ctx.fillStyle=g;ctx.fillRect(px-100,py-100,200,200);stamp(ctx,art.props,1,px,py,51);ring(ctx,px,py,27,'#edd394');ctx.restore();plate(ctx,848,127,210,117);text(ctx,'地层记录',866,156,19);text(ctx,`最深 ${s.depth+1}/22 层`,866,187);text(ctx,`晶矿 ${s.ore} 枚`,866,217,15,'#8ee5e0');text(ctx,'G 列 · 底层信标',560,597,16,'#ecddba','center');
 }
 if(id==='cluster'){
  const scale=1-clamp((s.radius-22)/180,0,.32);ctx.save();ctx.translate(560,330);ctx.scale(scale,scale);ctx.translate(-560,-330);s.items.filter(v=>!v.taken).sort((a,b)=>a.y-b.y).forEach(v=>{shadow(ctx,v.x,v.y+v.size*.5,v.size*.55);stamp(ctx,art.props,v.type,v.x,v.y,v.size*2.1);if(v.size>s.radius*1.2)ring(ctx,v.x,v.y,v.size*.85,'#a8895966')});shadow(ctx,s.p.x,s.p.y+s.radius*.65,s.radius);ctx.save();const g=ctx.createRadialGradient(s.p.x-s.radius*.4,s.p.y-s.radius*.45,4,s.p.x,s.p.y,s.radius);g.addColorStop(0,'#d6e9cf');g.addColorStop(1,'#466359');ctx.fillStyle=g;ctx.beginPath();ctx.arc(s.p.x,s.p.y,s.radius,0,Math.PI*2);ctx.fill();ctx.restore();s.items.filter(v=>v.taken).forEach((v,i)=>{const a=i*2.399+s.angle,r=s.radius*Math.sqrt((i+.8)/Math.max(1,s.collected));stamp(ctx,art.props,v.type,s.p.x+Math.cos(a)*r,s.p.y+Math.sin(a)*r*.85,Math.min(48,v.size*1.4),undefined,4,a*.2)});ring(ctx,s.p.x,s.p.y,s.radius+3,'#c9b576');ctx.restore();plate(ctx,32,470,214,103);text(ctx,'收藏进度',48,500,18);text(ctx,`${s.collected}/28 件 · 体积 ${Math.round(s.radius)}`,48,530);text(ctx,'由小物件开始吸附',48,555,12,'#b7d7ce');
 }
 if(id==='paint'){
  ctx.save();for(const color of [1,2]){ctx.fillStyle=color===1?'#41bec6bd':'#e68a70bd';ctx.beginPath();s.cells.forEach((v,i)=>{if(v!==color)return;const x=196+i%24*32,y=128+Math.floor(i/24)*36;ctx.moveTo(x+22,y);for(let k=0;k<=12;k++){const a=k*Math.PI/6,r=22+Math.sin(i*13+k*7)*3;ctx.lineTo(x+Math.cos(a)*r,y+Math.sin(a)*r*1.08)}ctx.closePath()});ctx.fill()}s.cells.forEach((v,i)=>{if(!v||i%7)return;const x=196+i%24*32,y=128+Math.floor(i/24)*36;ctx.fillStyle=v===1?'#b2f4ed35':'#ffd4b936';ctx.beginPath();ctx.ellipse(x-5,y-7,8,3,-.4,0,Math.PI*2);ctx.fill()});ctx.restore();if(!s.swim&&s.paint&&s.ink>0&&s.phase==='play'){ctx.save();ctx.fillStyle='#80eee7a0';for(let i=0;i<8;i++){const a=i*2.399+clock*.3,r=30+(clock*28+i*7)%32;ctx.beginPath();ctx.arc(s.p.x+Math.cos(a)*r,s.p.y+Math.sin(a)*r,2+(i%2),0,Math.PI*2);ctx.fill()}ctx.restore()}stamp(ctx,art.props,1,s.p.x,s.p.y,s.swim?36:55,undefined,4,s.swim?.35:0);ring(ctx,s.p.x,s.p.y,s.swim?22:34,'#b8fcf0');stamp(ctx,art.props,0,s.bot.x,s.bot.y,52);ring(ctx,s.bot.x,s.bot.y,26,'#f1a78d');plate(ctx,34,460,266,102);text(ctx,`青色覆盖 ${coverage(s).toFixed(1)}% / 58%`,51,490,17);text(ctx,`颜料 ${Math.round(s.ink)}% · ${s.swim?'潜行恢复':'行走喷涂'}`,51,520,14,'#ace5dc');text(ctx,`剩余 ${Math.ceil(s.timer)} 秒`,51,546,14);
 }
 if(id==='swarm'){
  if(!s.bridge){ctx.save();ctx.fillStyle='#153934a0';ctx.fillRect(781,102,54,470);ctx.restore();text(ctx,'桥面未接通',809,387,13,'#f8dfad','center')}else{for(let j=0;j<3;j++)stamp(ctx,art.props,14,781+j*31,337,74,44)}
  s.cargo.forEach((c,i)=>{if(!c.delivered){shadow(ctx,c.x,c.y+22,32);stamp(ctx,art.props,i===1?12:6,c.x,c.y,76);text(ctx,`需 ${c.need} 人`,c.x,c.y-43,13,'#f4e5c0','center');if(i===s.selected)ring(ctx,c.x,c.y,47,'#eed6a0')}});for(const w of [...s.workers].sort((a,b)=>a.y-b.y)){shadow(ctx,w.x,w.y+13,11);stamp(ctx,art.props,2,w.x,w.y,29+Math.sin(clock*7+w.x)*1.8);if(w.job>=0)ring(ctx,w.x,w.y,15,'#ade4c5')}stamp(ctx,art.props,1,s.p.x,s.p.y,52);ring(ctx,s.p.x,s.p.y,30);plate(ctx,31,457,263,113);text(ctx,`分队 ${s.group} 人 · 空闲 ${s.workers.filter(w=>w.job<0).length}`,47,489,16);text(ctx,`材料 ${s.cargo.filter(c=>c.delivered).length}/3 件`,47,519);text(ctx,s.bridge?'桥面已接通，可去右岸':'搬回左岸两件材料修桥',47,548,12,'#bbdfcb');
 }
 if(id==='kitchen'){
  KITCHEN_STATIONS.forEach((p,i)=>{ring(ctx,p.x,p.y+114,27,i===s.station?'#ffe09d':'#c1b58f88');text(ctx,['取料','切配','烹调','交付'][i],p.x,p.y+165,14,'#f5e3bd','center')});stamp(ctx,art.props,8,180,282,73);if(s.chop)stamp(ctx,art.props,9,447,281,76);if(s.stove){stamp(ctx,art.props,10,677,281,78);for(let i=0;i<3;i++){ctx.save();ctx.strokeStyle='#f6e2c28f';ctx.lineWidth=2;ctx.beginPath();const x=662+i*14,y=252-(clock*23+i*13)%42;ctx.moveTo(x,y+17);ctx.quadraticCurveTo(x+8,y+7,x,y);ctx.stroke();ctx.restore()}text(ctx,s.cook>=4?'可以取汤':`烹调 ${s.cook.toFixed(1)}/4 秒`,677,230,13,'#f5dd9c','center')}
  shadow(ctx,s.p.x,s.p.y+25,26);stamp(ctx,art.props,3,s.p.x,s.p.y,67);if(s.holding>=0)stamp(ctx,art.props,s.holding,s.p.x+32,s.p.y-16,40);s.orders.forEach((o,i)=>{plate(ctx,270+i*211,82,194,67);stamp(ctx,art.props,11,300+i*211,116,49);text(ctx,`订单 ${o.id} · 热汤`,329+i*211,110,13);text(ctx,`${Math.ceil(o.patience)} 秒等待`,329+i*211,133,12,o.patience<20?'#f8a089':'#b8d7c9')});text(ctx,`已交付 ${s.served}/3 · 当前工位 ${['取料','切配','烹调','交付'][s.station]}`,560,590,16,'#f1e0bf','center');
 }
 if(id==='relay'){
  if(s.role==='manual'){plate(ctx,260,100,600,448,true);text(ctx,'说明端 · 航灯复位手册',295,150,24,'#34504a');const lines=['你看不到装置序号，请向操作员询问。','① 序号为偶数：断开青绿线；奇数：断开珊瑚线。','② 序号十位数 ÷ 4 的余数 = 旋钮读数。','③ 序号 ÷ 3 的余数 + 1 = 脉冲读数。','操作员逐步调整并确认，说明端只负责解释规则。'];lines.forEach((t,i)=>text(ctx,t,295,205+i*53,16,'#43574f'));text(ctx,'两个人分别掌握装置与规则，通过交流完成。',295,513,14,'#806849')}
  else{plate(ctx,286,113,548,411);text(ctx,'操作端 · 雾海航灯',316,155,23);text(ctx,'装置序号 '+s.serial,316,193,19,'#b3e7db');text(ctx,'向说明员询问线路、旋钮和脉冲规则。',316,225,14,'#cfdbca');for(const [i,col]of ['#76d9cc','#f29b82'].entries()){ctx.save();ctx.strokeStyle='#081718';ctx.lineWidth=15;ctx.beginPath();ctx.moveTo(355,272+i*56);ctx.bezierCurveTo(470,237+i*56,620,307+i*56,743,272+i*56);ctx.stroke();ctx.strokeStyle=col;ctx.lineWidth=7;ctx.stroke();ctx.restore();if(s.cuts.includes(i?'coral':'teal')){ctx.save();ctx.strokeStyle='#e8ddbb';ctx.lineWidth=4;ctx.beginPath();ctx.moveTo(550,250+i*56);ctx.lineTo(573,294+i*56);ctx.stroke();ctx.restore()}}ring(ctx,416,423,40);text(ctx,String(s.dial),416,435,32,'#f4d795','center');text(ctx,'旋钮读数',416,483,14,'#b0d4c8','center');ring(ctx,673,423,40,'#9ed8d7');text(ctx,String(s.button),673,435,32,'#aee8dd','center');text(ctx,'脉冲读数',673,483,14,'#b0d4c8','center');text(ctx,`步骤 ${Math.min(3,s.stage+1)}/3 · 核对失误 ${s.mistakes}`,560,560,16,'#e7dfb8','center')}
 }
 sceneHeading(ctx,info.title,info.detail);if(s.won||s.phase==='lost'){plate(ctx,342,551,436,66);text(ctx,s.won?'本段完成 · '+info.title:'本轮结束 · 可以重新开始',560,579,19,'#f5deb0','center');text(ctx,s.won?`${Math.floor(s.elapsed)} 秒 · ${s.moves} 次操作 · 结果已保留`:'在下方重新开始，重新安排路线与操作',560,603,13,'#bcded1','center')}
}

export async function createNine({host,input,saved,id,sfx=()=>{}}){
 const info=NINE_INFO[id];if(!info)throw new Error('未知游戏形态');const art=await images([id,'props',...(id==='repair'?['parts']:[])],'assets/game-forms/nine/');if(id==='fold')art.stone=(await images(['limestone'],'assets/game-forms/roll/')).limestone;const {element,ctx}=canvasSurface(host);element.style.touchAction='none';element.setAttribute('aria-label',info.title+'。'+info.help);
 let s=restoreNine(id,saved),active=false,clock=0,held=new Set(),grab=null,digTimer=0;const css=`<style>.nine-controls{background:linear-gradient(115deg,#17313b,#132528)}.nine-fold-controls,.nine-repair-controls,.nine-kitchen-controls{background:linear-gradient(115deg,#e8dec7,#d8d2bc);color:#304f48}.nine-fold-controls button,.nine-repair-controls button,.nine-kitchen-controls button{background:#f5ebd6;color:#334f48;border-color:#9b8c69}.nine-toolbar{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:7px}.nine-toolbar button{min-width:0}.nine-readout{margin:0 0 10px;font-size:13px;font-variant-numeric:tabular-nums}.nine-pad{display:grid;grid-template-columns:repeat(4,1fr);gap:7px;margin-top:9px}.nine-help{font-size:12px;line-height:1.7;margin:10px 0 0;color:inherit;opacity:.85}@media(max-width:650px){.nine-toolbar{grid-template-columns:repeat(2,minmax(0,1fr))}.nine-controls button{padding:8px 5px;font-size:12px}.nine-pad button{min-height:46px}#player-frame.nine-repair-frame:fullscreen{--observation-space:480px}#player-frame.nine-hook-frame:fullscreen,#player-frame.nine-swarm-frame:fullscreen,#player-frame.nine-relay-frame:fullscreen{--observation-space:370px}#player-frame.nine-kitchen-frame:fullscreen{--observation-space:360px}.nine-help{font-size:11px}}</style>`;
 const canMove=['hook','repair','cluster','paint','swarm','kitchen'].includes(id),directions=id==='hook'?[['left','← 左摆'],['right','→ 右摆']]:[['left','← 左'],['up','↑ 上'],['down','↓ 下'],['right','→ 右']],ui=observationPanel(host,'nine-'+id,css+`<style>.nine-hook-controls .nine-pad{grid-template-columns:repeat(2,1fr)}#player-frame[class*="nine-"]:fullscreen{justify-content:flex-start;overflow:hidden;height:100dvh;--observation-space:285px}#player-frame.nine-repair-frame:fullscreen{--observation-space:380px}#player-frame[class*="nine-"]:fullscreen .play-mount{flex:0 0 auto;width:min(100vw,calc(max(160px,100dvh - var(--observation-space) - 56px)*1.77778));height:min(56.25vw,max(160px,100dvh - var(--observation-space) - 56px))!important}#player-frame[class*="nine-"]:fullscreen .nine-controls{flex:1 1 auto;min-height:0;overflow:auto;width:100%;max-width:1120px}@media(max-width:650px){#player-frame.nine-repair-frame:fullscreen{--observation-space:480px}#player-frame.nine-hook-frame:fullscreen,#player-frame.nine-swarm-frame:fullscreen,#player-frame.nine-relay-frame:fullscreen{--observation-space:370px}#player-frame.nine-kitchen-frame:fullscreen{--observation-space:360px}}</style><p class="nine-readout" aria-live="polite"></p><div class="nine-toolbar">${info.actions.map(([key,label])=>`<button type="button" data-command="${key}">${label}</button>`).join('')}<button type="button" data-command="restart">重新开始本段</button></div>${canMove?`<div class="nine-pad" role="group" aria-label="方向控制">${directions.map(([key,label])=>`<button type="button" data-hold="${key}">${label}</button>`).join('')}</div>`:''}<p class="nine-help">${info.help}</p>`);
 ui.panel.classList.add('nine-controls','nine-'+id+'-controls');const buttons=[...ui.panel.querySelectorAll('[data-command]')],pad=[...ui.panel.querySelectorAll('[data-hold]')],readout=ui.panel.querySelector('.nine-readout');
 function stats(){if(id==='hook')return [`挂点 ${s.selected+1}`,`绳长 ${Math.round(s.length)}`,`跌落 ${s.falls}`];if(id==='fold')return [`路段 ${s.node}/7`,foldConnected(s)?'当前通路可接':'需要旋转对齐'];if(id==='repair')return [`安装 ${s.parts.filter(p=>p.placed).length}/3`,`选中 ${REPAIR_NAMES[s.selected]}`,s.clean?'表壳干净':'等待清洁'];if(id==='delve')return [`深度 ${s.depth+1}/22`,`晶矿 ${s.ore}`];if(id==='cluster')return [`收藏 ${s.collected}/28`,`体积 ${Math.round(s.radius)}`];if(id==='paint')return [`覆盖 ${coverage(s).toFixed(1)}%`,`颜料 ${Math.round(s.ink)}%`,`剩余 ${Math.ceil(s.timer)} 秒`];if(id==='swarm')return [`交付 ${s.cargo.filter(c=>c.delivered).length}/3`,`分队 ${s.group} 人`,s.bridge?'桥面接通':'左岸修桥'];if(id==='kitchen')return [`交付 ${s.served}/3`,`手持 ${s.holding<0?'空':s.holding===8?'番茄':s.holding===9?'切配':'热汤'}`,`工位 ${s.station+1}`];return [s.role==='manual'?'说明端':'操作端',`步骤 ${Math.min(3,s.stage+1)}/3`,`核对失误 ${s.mistakes}`]}
 function sync(){const line=stats().join(' · ');if(readout.textContent!==line)readout.textContent=line;for(const b of buttons){const [key,arg]=b.dataset.command.split(':');let allowed=true,selected=false;
  if(id==='hook'){if(['release','reel'].includes(key))allowed=s.anchor>=0;if(key==='anchor')selected=Number(arg)===s.selected;}
  if(id==='fold'){if(key==='rotate')allowed=!s.walk;if(key==='walk')allowed=!s.walk&&Math.abs(s.yaw-s.targetYaw)<.001&&foldConnected(s);}
  if(id==='repair'){const part=s.parts[s.selected];if(key==='select')selected=Number(arg)===s.selected;if(key==='clean')allowed=!s.cover&&!s.clean;if(['rotate','center'].includes(key))allowed=!part.placed;if(key==='place')allowed=!s.cover&&s.clean&&!part.placed;if(key==='remove')allowed=s.parts.some(p=>p.placed);if(key==='cover')allowed=s.parts.every(p=>!p.placed);if(key==='test')allowed=s.clean&&s.parts.every(p=>p.placed);}
  if(id==='paint'){if(key==='swim')selected=s.swim;if(key==='spray')selected=s.paint;}
  if(id==='swarm'){if(key==='select')selected=Number(arg)===s.selected;if(key==='dispatch'){const c=s.cargo[s.selected];allowed=!c.delivered&&(s.selected<2||s.bridge)&&s.group>=c.need&&s.workers.filter(w=>w.job<0).length>=c.need;}}
  if(id==='kitchen'){if(key==='station')selected=Number(arg)===s.station;if(key==='work'){const labels=['取番茄',s.holding===8?`切配 · 还需 ${3-s.chop} 次`:'切配食材',s.stove?(s.cook>=4?'取出热汤':`烹调中 · ${s.cook.toFixed(1)}/4 秒`):'食材入锅','交付热汤'];b.textContent=labels[s.station];const p=KITCHEN_STATIONS[s.station];allowed=Math.hypot(s.p.x-p.x,s.p.y-420)<=85&&(s.station===0?s.holding<0:s.station===1?s.holding===8:s.station===2?s.stove?s.cook>=4&&s.holding<0:s.holding===9:s.holding===11);}}
  if(id==='relay'&&!['role','restart'].includes(key)){b.hidden=s.role==='manual';allowed=s.role==='operator'&&(key==='wire'?s.stage===0:key==='dial'?s.stage===1:key==='button'?s.stage===2:s.stage===1||s.stage===2);}
  if(['anchor','select','station','swim','spray'].includes(key))b.setAttribute('aria-pressed',String(selected));b.disabled=!active||!allowed||(s.phase!=='play'&&key!=='restart'&&key!=='role');
 }pad.forEach(b=>b.disabled=!active||s.phase!=='play')}
 function run(key,arg){if(!active)return false;if(key==='restart'){s=freshNine(id);held.clear();grab=null;digTimer=0;clock=0;sync();return true}if(id==='repair'&&key==='center')key='move',arg={x:553,y:323};const ok=commandNine(s,key,arg);if(ok)sfx('turn');sync();return ok}
 buttons.forEach(b=>b.onclick=()=>{const [key,arg]=b.dataset.command.split(':');run(key,arg!==undefined&&Number.isFinite(Number(arg))?Number(arg):arg)});
 const events=new AbortController();pad.forEach(b=>{const d=b.dataset.hold;b.addEventListener('pointerdown',e=>{if(!active||b.disabled)return;e.preventDefault();held.add(d);b.setPointerCapture(e.pointerId)},{signal:events.signal});for(const name of ['pointerup','pointercancel','lostpointercapture'])b.addEventListener(name,()=>held.delete(d),{signal:events.signal})});
 const point=e=>pointerPosition(element,e);
 element.addEventListener('pointerdown',e=>{if(!active||id!=='repair')return;const p=point(e);for(let i=s.parts.length-1;i>=0;i--)if(!s.parts[i].placed&&Math.hypot(s.parts[i].x-p.x,s.parts[i].y-p.y)<78){s.selected=i;grab={dx:s.parts[i].x-p.x,dy:s.parts[i].y-p.y};element.setPointerCapture(e.pointerId);sync();break}},{signal:events.signal});
 element.addEventListener('pointermove',e=>{if(active&&grab){const p=point(e);run('move',{x:p.x+grab.dx,y:p.y+grab.dy})}},{signal:events.signal});
 element.addEventListener('pointerup',()=>{if(active&&grab)run('place');grab=null},{signal:events.signal});for(const name of ['pointercancel','lostpointercapture'])element.addEventListener(name,()=>grab=null,{signal:events.signal});if(typeof window!=='undefined')window.addEventListener('blur',()=>{held.clear();grab=null},{signal:events.signal});
 element.addEventListener('click',e=>{if(!active||s.phase!=='play')return;const p=point(e);if(id==='hook'){const n=HOOK_ANCHORS.findIndex(a=>Math.hypot(a.x-p.x,a.y-p.y)<45);if(n>=0){run('anchor',n);run('attach')}}else if(id==='fold')run('walk');else if(id==='delve'){const size=43,x=302,offset=clamp((s.p.y-5)*size,0,22*size-460),tx=Math.floor((p.x-x)/size),ty=Math.floor((p.y-108+offset)/size),dx=tx-s.p.x,dy=ty-s.p.y;if(Math.abs(dx)+Math.abs(dy)===1)run('dig',dx===1?1:dx===-1?3:dy===1?2:0)}else if(['cluster','paint','swarm','kitchen'].includes(id)){if(id==='cluster'){const scale=1-clamp((s.radius-22)/180,0,.32);p.x=560+(p.x-560)/scale;p.y=330+(p.y-330)/scale;}run('target',p)}},{signal:events.signal});
 function tick(dt){if(!active)return;dt=Number.isFinite(dt)?clamp(dt,0,.08):0;clock+=dt;const drive={x:(input.x||0)+(held.has('right')?1:0)-(held.has('left')?1:0),y:(input.y||0)+(held.has('down')?1:0)-(held.has('up')?1:0)};
  if(id==='delve'){digTimer-=dt;const directions=[['ArrowUp',0],['KeyW',0],['ArrowRight',1],['KeyD',1],['ArrowDown',2],['KeyS',2],['ArrowLeft',3],['KeyA',3]];for(const [key,dir]of directions)if(input.pressed.has(key)){run('dig',dir);digTimer=.2;break}if(digTimer<=0){for(const [key,dir]of directions)if(input.keys?.has(key)){run('dig',dir);digTimer=.2;break}}}
  if(id==='repair'&&(drive.x||drive.y)){const p=s.parts[s.selected];run('move',{x:p.x+drive.x*180*dt,y:p.y+drive.y*180*dt})}
  if(input.pressed.has('Space'))run(id==='hook'?(s.anchor<0?'attach':'release'):id==='fold'?'walk':id==='repair'?'place':id==='swarm'?'dispatch':id==='kitchen'?'work':id==='paint'?'swim':'verify');if(input.pressed.has('KeyE'))run(id==='hook'?'reel':id==='repair'?'rotate':id==='fold'?'rotate':id==='swarm'?'recall':id==='relay'?'role':'work',id==='fold'?1:undefined);
  const won=s.won;stepNine(s,dt,drive);if(!won&&s.won)sfx('success');sync();
 }
 sync();return {tick,draw(){drawNineScene(ctx,s,art,clock)},onStart(){active=true;sync()},setActive(v){if(active===v)return;active=v;if(!active){held.clear();grab=null}sync()},getState(){return structuredClone(s)},getStatus(){return {goal:s.won?info.title+' · 本段已完成':s.phase==='lost'?'本轮结束，可重开':info.goal,message:s.message||info.help,stats:stats(),actions:[]}},dispose(){events.abort();held.clear();ui.dispose()}};
}
