import {W,H,images,canvasSurface,cover,action} from './showcase-core.js';

// Coordinates and shared borders follow the illustrated peninsula. Routes are
// deliberately explicit: the rule graph never comes from proximity or a tap.
export const REALM_RULES=Object.freeze({maxRounds:8,ordersPerRound:3,recruitCost:6,recruitArmy:3,developCost:8,incomePerLevel:2,maxLevel:2,maxArmy:24,targetProvinces:8});
export const REALM_REGIONS=[
 {id:'west',name:'西垒',x:156,y:355,income:4,owner:'player',army:10,neighbors:['pine','grain','river','south'],polygon:[[50,300],[220,280],[286,332],[242,417],[78,414]]},
 {id:'grain',name:'麦谷',x:343,y:356,income:4,owner:'player',army:6,neighbors:['west','river','marsh','south','sail'],polygon:[[286,332],[402,302],[505,331],[439,406],[363,425],[242,417]]},
 {id:'pine',name:'松岭',x:176,y:245,income:3,owner:'player',army:6,neighbors:['west','snow','river'],polygon:[[50,160],[185,178],[273,222],[220,280],[50,300]]},
 {id:'snow',name:'白脊',x:177,y:116,income:2,owner:'neutral',army:2,neighbors:['pine','falls'],polygon:[[30,74],[225,66],[309,151],[273,222],[185,178],[50,160]]},
 {id:'falls',name:'云瀑',x:393,y:154,income:3,owner:'neutral',army:3,neighbors:['snow','river','pass'],polygon:[[225,66],[452,67],[515,185],[388,228],[273,222],[309,151]]},
 {id:'river',name:'河枢',x:455,y:267,income:5,owner:'neutral',army:3,neighbors:['west','grain','pine','falls','marsh','cliff','pass'],polygon:[[273,222],[388,228],[515,185],[659,207],[621,294],[505,331],[402,302],[286,332],[220,280]]},
 {id:'south',name:'南境',x:249,y:483,income:4,owner:'neutral',army:2,neighbors:['west','grain','sail'],polygon:[[78,414],[242,417],[363,425],[383,507],[282,576],[164,560],[58,470]]},
 {id:'marsh',name:'翠泽',x:568,y:362,income:4,owner:'neutral',army:3,neighbors:['grain','river','sail','port','cliff'],polygon:[[505,331],[621,294],[700,318],[699,389],[584,438],[439,406]]},
 {id:'sail',name:'盐帆',x:525,y:505,income:5,owner:'neutral',army:4,neighbors:['grain','south','marsh','port'],polygon:[[363,425],[439,406],[584,438],[699,389],[737,451],[642,543],[500,583],[383,507]]},
 {id:'port',name:'东港',x:769,y:390,income:5,owner:'rival',army:6,capital:true,neighbors:['marsh','sail','cliff'],polygon:[[700,318],[837,305],[844,438],[737,451],[699,389]]},
 {id:'cliff',name:'赤崖',x:752,y:255,income:4,owner:'rival',army:5,neighbors:['river','marsh','port','pass'],polygon:[[659,207],[823,184],[837,305],[700,318],[621,294]]},
 {id:'pass',name:'岚关',x:656,y:133,income:3,owner:'rival',army:4,neighbors:['falls','river','cliff'],polygon:[[452,67],[780,80],[823,184],[659,207],[515,185]]}
];
const colors={player:'#83dfc3',neutral:'#ddac6b',rival:'#df8f87'},names={player:'青盟',neutral:'中立',rival:'赤盟'};
const region=id=>REALM_REGIONS.find(r=>r.id===id);
export async function createRealm({host,input,saved,notify,sfx}){
 const art=await images(['map'],'assets/game-forms/realm/'),{ctx}=canvasSurface(host),rules=REALM_RULES;
 const defaults={version:1,provinces:REALM_REGIONS.map(r=>({id:r.id,owner:r.owner,army:r.army,level:0,fort:0,recruited:false,developed:false})),selected:'west',source:null,target:null,mode:'inspect',force:'all',round:1,orders:rules.ordersPerRound,gold:30,phase:'player',won:false,score:0,captures:0,transfers:0,recruits:0,developments:0,spent:0,incomeReceived:0,aiActions:0,replays:0,history:['青盟握有西侧三省。八回合内控制八省，或攻下赤盟首府东港。'],lastRound:null,checkpoint:null};
 const restore=raw=>{const out=structuredClone(defaults);if(!raw||typeof raw!=='object')return out;for(const k of Object.keys(out)){if(k==='provinces'||k==='checkpoint')continue;if(typeof out[k]==='number'){if(Number.isFinite(raw[k]))out[k]=Math.max(0,Math.floor(raw[k]))}else if(typeof out[k]==='boolean'){if(typeof raw[k]==='boolean')out[k]=raw[k]}else if(raw[k]!==undefined)out[k]=structuredClone(raw[k])}out.provinces=defaults.provinces.map(p=>{const x=raw.provinces?.find(v=>v.id===p.id);return x?{id:p.id,owner:['player','neutral','rival'].includes(x.owner)?x.owner:p.owner,army:Number.isFinite(x.army)?Math.min(rules.maxArmy,Math.max(1,Math.floor(x.army))):p.army,level:Number.isFinite(x.level)?Math.min(rules.maxLevel,Math.max(0,Math.floor(x.level))):0,fort:Number.isFinite(x.fort)?Math.min(2,Math.max(0,Math.floor(x.fort))):0,recruited:!!x.recruited,developed:!!x.developed}:p});out.round=Math.min(rules.maxRounds,Math.max(1,out.round));out.orders=Math.min(rules.ordersPerRound,out.orders);if(!['player','enemy','summary','won','lost'].includes(out.phase))out.phase='player';if(!region(out.selected))out.selected='west';if(!['inspect','dispatch'].includes(out.mode))out.mode='inspect';if(!['all','half'].includes(out.force))out.force='all';if(!Array.isArray(out.history))out.history=[...defaults.history];out.history=out.history.filter(x=>typeof x==='string').slice(-12);out.checkpoint=raw.checkpoint?.provinces?structuredClone(raw.checkpoint):null;return out};
 let s=restore(saved),enemyTimer=.7,pulse=0,effect=null;
 const province=id=>s.provinces.find(p=>p.id===id),owned=()=>s.provinces.filter(p=>p.owner==='player'),income=()=>owned().reduce((n,p)=>n+region(p.id).income+p.level*rules.incomePerLevel,0),selected=()=>province(s.selected),defense=p=>p.army+p.fort;
 const active=()=>s.phase==='player'&&!s.won,log=text=>{s.history.push(text);s.history=s.history.slice(-12)},canonical=()=>{const cp=structuredClone(s);delete cp.checkpoint;return cp};
 if(!s.checkpoint)s.checkpoint=canonical();
 function deny(text){notify(text);sfx('cards');return false}
 function requireOrder(p){if(!active())return deny('先继续到己方回合，再下达命令。');if(!p||p.owner!=='player')return deny('只能在青盟控制的省区招募、开发或发出部队。');if(s.orders<1)return deny('本回合三道命令已用完，请结束回合。');return true}
 function checkWin(){if(owned().length>=rules.targetProvinces||province('port').owner==='player'){s.won=true;s.phase='won';s.mode='inspect';s.source=s.target=null;s.score=owned().length*120+(rules.maxRounds-s.round+1)*80+s.gold;log('青盟完成半岛协定：控制 '+owned().length+' 省'+(province('port').owner==='player'?'，东港首府已归盟。':'。'));notify('区域战略短局完成：省区连接、调兵、财政与回合决策共同推进了半岛协定。');sfx('success');return true}return false}
 function recruit(){const p=selected();if(!requireOrder(p))return;if(p.recruited)return deny('这一省本回合已招募，下一回合可再次招募。');if(p.army>rules.maxArmy-rules.recruitArmy)return deny('驻军接近上限，请先调兵。');if(s.gold<rules.recruitCost)return deny('招募需要 '+rules.recruitCost+' 金。');s.gold-=rules.recruitCost;s.spent+=rules.recruitCost;s.orders--;p.army+=rules.recruitArmy;p.recruited=true;s.recruits++;effect={id:p.id,text:'+3 驻军',time:1.5};log(region(p.id).name+'招募三队，花费 6 金。');sfx('build')}
 function develop(){const p=selected();if(!requireOrder(p))return;if(p.level>=rules.maxLevel)return deny('这一省的发展已满两级。');if(p.developed)return deny('这一省本回合已开发。');if(s.gold<rules.developCost)return deny('开发需要 '+rules.developCost+' 金。');s.gold-=rules.developCost;s.spent+=rules.developCost;s.orders--;p.level++;p.developed=true;s.developments++;effect={id:p.id,text:'收入 +2',time:1.5};log(region(p.id).name+'发展到 '+p.level+' 级，每回合税收 +2。');sfx('build')}
 function beginDispatch(){const p=selected();if(!requireOrder(p))return;if(p.army<2)return deny('出兵后必须保留一队驻军，请先招募或调入兵力。');s.mode='dispatch';s.source=p.id;s.target=null;notify('已从'+region(p.id).name+'准备出兵。点选金边相邻省区查看结果，再确认。');sfx('turn')}
 function sentArmy(p){return Math.max(0,s.force==='half'?Math.floor((p.army-1)/2):p.army-1)}
 function preview(){const from=province(s.source),to=province(s.target);if(!from||!to)return null;const amount=sentArmy(from),friendly=to.owner==='player',strength=defense(to),capture=!friendly&&amount>strength;return {source:from.id,target:to.id,adjacent:region(from.id).neighbors.includes(to.id),sent:amount,sourceRemaining:from.army-amount,defenders:to.army,fort:to.fort,effectiveDefense:strength,friendly,capture,resultArmy:friendly?Math.min(rules.maxArmy,to.army+amount):capture?amount-strength:Math.max(1,to.army-Math.floor(amount/2)),lost:!friendly?(capture?strength:amount):0,overCapacity:friendly&&to.army+amount>rules.maxArmy}}
 function dispatch(){const p=preview(),from=province(s.source),to=province(s.target);if(!requireOrder(from))return;if(!p||!p.adjacent)return deny('出兵只能到相邻省区，远处省区无法作为目标。');if(p.sent<1)return deny('出兵后必须保留一队驻军。');if(p.overCapacity)return deny('目标驻军将超过 24 队，请切换半数出兵。');from.army-=p.sent;s.orders--;if(p.friendly){to.army+=p.sent;s.transfers++;log(region(from.id).name+'向'+region(to.id).name+'调入 '+p.sent+' 队。');sfx('step')}else if(p.capture){to.owner='player';to.army=p.resultArmy;to.fort=0;to.recruited=false;to.developed=false;s.captures++;log(region(from.id).name+'攻下'+region(to.id).name+'：出兵 '+p.sent+'，消耗 '+p.lost+'，余 '+to.army+'。');sfx('success')}else{to.army=p.resultArmy;log(region(from.id).name+'进攻'+region(to.id).name+'失败：出兵 '+p.sent+' 全部损失，守军余 '+to.army+'。');sfx('slash')}effect={id:to.id,from:from.id,text:p.friendly?'调入 +'+p.sent:p.capture?'归入青盟':'未能攻下',time:1.7};s.selected=to.id;s.source=s.target=null;s.mode='inspect';checkWin()}
 function select(id){if(!active())return;const r=region(id);if(!r)return;if(s.mode==='dispatch'){if(id===s.source){s.target=null;return}if(!region(s.source)?.neighbors.includes(id)){s.target=null;return deny('出兵只能到相邻省区。请点金边标出的邻省。')}s.target=id;sfx('cards')}else{s.selected=id;s.source=s.target=null;sfx('cards')}}
 function ai(){const rivals=s.provinces.filter(p=>p.owner==='rival'),options=[];for(const a of rivals)for(const id of region(a.id).neighbors){const b=province(id);if(b.owner==='player'&&a.army-1>defense(b))options.push({a,b,margin:a.army-1-defense(b)})}options.sort((x,y)=>defense(x.b)-defense(y.b)||y.margin-x.margin||x.a.id.localeCompare(y.a.id));s.aiActions++;if(options.length){const {a,b}=options[0],sent=a.army-1,lost=defense(b);a.army=1;b.owner='rival';b.army=sent-lost;b.fort=0;b.recruited=false;b.developed=false;effect={id:b.id,from:a.id,text:'赤盟占领',time:1.8};sfx('slash');return '赤盟从'+region(a.id).name+'进攻'+region(b.id).name+'：'+sent+' 对 '+lost+'，占领后驻军 '+b.army+'。'}const frontier=rivals.filter(p=>region(p.id).neighbors.some(id=>province(id).owner==='player')),target=(frontier.length?frontier:rivals).sort((a,b)=>defense(a)-defense(b)||a.id.localeCompare(b.id))[0];if(target){target.army=Math.min(rules.maxArmy,target.army+2);target.fort=Math.min(2,target.fort+1);effect={id:target.id,text:'赤盟 +2 / 筑垒',time:1.8};sfx('build');return '赤盟在'+region(target.id).name+'增援两队、筑垒一级，防御 '+defense(target)+'。'}return '赤盟已无控制省区。'}
 function endTurn(){if(!active())return;s.mode='inspect';s.source=s.target=null;s.phase='enemy';enemyTimer=.7;log('第 '+s.round+' 回合结束，赤盟行动。');sfx('turn')}
 function resolveRound(){const finished=s.round,before=owned().length,aiText=ai();log(aiText);const tax=income();s.gold+=tax;s.incomeReceived+=tax;s.lastRound={round:finished,income:tax,ai:aiText,ownedBefore:before,ownedAfter:owned().length};if(!owned().length){s.phase='lost';log('青盟失去所有省区，可以重试本回合。');return}if(checkWin())return;if(s.round>=rules.maxRounds){s.phase='lost';log('八回合期限已到。返回本回合可重新安排军力与命令。');return}s.round++;s.orders=rules.ordersPerRound;for(const p of s.provinces){p.recruited=false;p.developed=false}if(selected()?.owner!=='player')s.selected=owned()[0].id;s.phase='summary';log('第 '+finished+' 回合税收 '+tax+' 金，现有 '+s.gold+' 金。')}
 function continueRound(){if(s.phase!=='summary')return;s.phase='player';s.checkpoint=canonical();sfx('turn')}
 function retry(){const replayCount=s.replays;s=restore(s.checkpoint);s.replays=replayCount;s.phase='player';s.won=false;s.mode='inspect';s.source=s.target=null;s.checkpoint=canonical();enemyTimer=.7;effect=null;notify('已回到第 '+s.round+' 回合开始，资源、驻军和归属一并恢复。')}
 function replay(){const n=s.replays+1;s=structuredClone(defaults);s.replays=n;s.checkpoint=canonical();enemyTimer=.7;effect=null;notify('新的半岛协定开始，三省、三道命令与 30 金已就绪。')}
 function inside(point,polygon){let yes=false;for(let i=0,j=polygon.length-1;i<polygon.length;j=i++){const a=polygon[i],b=polygon[j];if((a[1]>point.y)!==(b[1]>point.y)&&point.x<(b[0]-a[0])*(point.y-a[1])/(b[1]-a[1])+a[0])yes=!yes}return yes}
 function tap(point){if(!active())return;const near=REALM_REGIONS.map(r=>({r,d:Math.hypot(point.x-r.x,point.y-r.y)})).sort((a,b)=>a.d-b.d)[0],hit=near.d<47?near.r:REALM_REGIONS.find(r=>inside(point,r.polygon));if(hit)select(hit.id);else if(s.mode==='dispatch')deny('海面没有通行省区，请点地图上标出的相邻省区。')}
 function tick(dt){pulse+=dt;if(effect){effect.time-=dt;if(effect.time<=0)effect=null}if(s.phase==='enemy'){enemyTimer-=dt;if(enemyTimer<=0)resolveRound();return}if(active()){for(const point of input.pointers)tap(point);if(input.pressed.has('KeyE'))endTurn();if(input.pressed.has('KeyR'))recruit();if(input.pressed.has('KeyC'))beginDispatch()}else if(s.phase==='summary'&&input.pressed.has('Space'))continueRound()}
 function box(x,y,w,h,fill,stroke=null,r=9){ctx.beginPath();ctx.roundRect(x,y,w,h,r);ctx.fillStyle=fill;ctx.fill();if(stroke){ctx.strokeStyle=stroke;ctx.lineWidth=1;ctx.stroke()}}
 function text(value,x,y,size=16,color='#f4e6c8',bold=false,align='left'){ctx.font=`${bold?'bold ':''}${size}px "Microsoft YaHei",sans-serif`;ctx.textAlign=align;ctx.fillStyle=color;ctx.fillText(value,x,y)}
 function path(points){ctx.beginPath();points.forEach((p,i)=>i?ctx.lineTo(p[0],p[1]):ctx.moveTo(p[0],p[1]));ctx.closePath()}
 function wrap(value,x,y,width,size=15,color='#bdcfc8'){ctx.font=`${size}px "Microsoft YaHei",sans-serif`;let line='',row=0;for(const char of value){if(char==='\n'||ctx.measureText(line+char).width>width){text(line,x,y+row*25,size,color);line='';row++;if(char==='\n')continue}line+=char}if(line)text(line,x,y+row*25,size,color);return (row+1)*25}
 function draw(){
  cover(ctx,art.map);ctx.fillStyle='#10291a18';ctx.fillRect(0,0,W,H);
  const src=province(s.source),neighbors=active()?region(src?.id||s.selected)?.neighbors||[]:[],pv=preview();
  for(const r of REALM_REGIONS){const p=province(r.id),focus=r.id===s.selected||r.id===s.target,adj=s.mode==='dispatch'&&neighbors.includes(r.id);path(r.polygon);ctx.fillStyle=colors[p.owner]+(focus?'36':'1c');ctx.fill();ctx.strokeStyle=focus?'#fff0b8':adj?'#ffe2a3':colors[p.owner]+'cc';ctx.lineWidth=focus?3.2:adj?2.6:1.8;ctx.stroke()}
  if(s.mode==='dispatch'&&src){const a=region(src.id);for(const id of neighbors){const b=region(id);ctx.setLineDash([4,6]);ctx.strokeStyle=id===s.target?'#ffe2a6e6':'#ffedbc66';ctx.lineWidth=id===s.target?3:1.4;ctx.beginPath();ctx.moveTo(a.x,a.y);ctx.lineTo(b.x,b.y);ctx.stroke();ctx.setLineDash([])}}
  for(const r of REALM_REGIONS){const p=province(r.id),focus=r.id===s.selected||r.id===s.target,adj=s.mode==='dispatch'&&neighbors.includes(r.id);box(r.x-48,r.y-27,96,53,'#132b29e8',focus?'#ffe7ae':adj?'#f1d5a0':colors[p.owner],7);text(r.name+(r.capital?' ◇':''),r.x,r.y-7,16,colors[p.owner],true,'center');text(String(p.army),r.x-6,r.y+17,22,'#fff2cc',true,'center');if(p.fort)text('垒'+p.fort,r.x+30,r.y+14,11,'#f1c28d',false,'center');ctx.fillStyle=colors[p.owner];ctx.fillRect(r.x-34,r.y+22,68,2)}
  if(effect){const r=region(effect.id);if(effect.from){const a=region(effect.from);ctx.strokeStyle='#f9e9b6';ctx.lineWidth=3;ctx.beginPath();ctx.moveTo(a.x,a.y);ctx.lineTo(r.x,r.y);ctx.stroke()}box(r.x-67,r.y-62,134,25,'#172e2cee','#ead09b');text(effect.text,r.x,r.y-44,13,'#fff0c9',true,'center')}
  box(18,13,820,48,'#14272ce8','#e6ca9666');text('半岛协定',34,44,24,'#f4dfae',true);text('第 '+s.round+'/8 回合',192,42,16);text('青盟 '+owned().length+'/8 省',327,42,16,'#a2edd4');text('金 '+s.gold,490,42,17,'#f7d68f',true);text('命令 '+s.orders+'/3',590,42,16);text('税收 +'+income(),710,42,15,'#c1e0d2');
  box(864,13,241,558,'#14282bea','#e8d6af77',11);text('省区议事厅',884,47,22,'#f3dfb3',true);text(s.mode==='dispatch'?'出兵预览':'省区与军政',884,72,13,'#a5bfb6');ctx.strokeStyle='#b5bc9666';ctx.beginPath();ctx.moveTo(884,88);ctx.lineTo(1083,88);ctx.stroke();
  const p=province(s.target||s.selected),r=region(p.id);text(r.name+(r.capital?' · 半岛首府':''),884,120,21,colors[p.owner],true);text(names[p.owner]+'控制 · 驻军 '+p.army+(p.fort?' / 筑垒 '+p.fort:''),884,147,15,colors[p.owner]);text('税收 '+(r.income+p.level*2)+' 金 / 回合',884,176,17,'#e7d8af');text('发展 '+p.level+'/2 · 基础 '+r.income,884,202,14,'#b8c9bd');
  if(s.phase==='enemy'){text('赤盟正在行动…',884,252,18,'#e6a199',true);wrap('每回合一次进攻；兵力不足时增援筑垒。',884,282,195)}else if(s.phase==='summary'){text('第 '+s.lastRound.round+' 回合结算',884,248,18,'#b3ecd9',true);wrap(s.lastRound.ai,884,278,195);text('收税 +'+s.lastRound.income+' 金',884,405,20,'#f5d79b',true);wrap('查看地图变化，然后继续下一回合。',884,437,195)}else if(s.won||s.phase==='lost'){text(s.won?'协定已经达成':'期限 / 战线结束',884,251,18,s.won?'#b2efd5':'#f0b69d',true);wrap(s.won?'青盟的领土已连接半岛。可以再次开局，尝试另一条路线。':'返回本回合可重新安排命令，或从三省重新开局。',884,285,195);text('控制 '+owned().length+'/12 省',884,397,18);text('评分 '+s.score,884,431,18,'#f4d997')}else if(s.mode==='dispatch'){
   text('来源：'+region(s.source).name,884,242,16,'#c9eddb',true);text('出兵 '+sentArmy(src)+' · 留守 '+(src.army-sentArmy(src)),884,269,16,'#f4deaf');
   if(pv){text('花费：1 道命令',884,302,15);text(pv.friendly?'相邻友省 · 兵力合并':'守军 '+pv.defenders+' + 筑垒 '+pv.fort,884,329,15);wrap(pv.overCapacity?'驻军将超过上限，切换半数。':pv.friendly?'调入后驻军 '+pv.resultArmy+' 队。':pv.capture?'预计攻下，消耗 '+pv.lost+' 队，留下 '+pv.resultArmy+' 队。':'兵力不足，出兵 '+pv.sent+' 队将全部损失；敌军余 '+pv.resultArmy+'。',884,362,194,15,pv.capture||pv.friendly?'#afecd3':'#edb29d');wrap('下方确认出兵执行预览。',884,472,195,14)}else wrap('点击金边相邻省区。虚线只表示可用路线，尚未移动兵力。',884,308,195);
  }else{wrap(p.owner==='player'?'招募：6 金、1 命令，驻军 +3。\n开发：8 金、1 命令，税收 +2。':'可查看军力与税收。先选青盟省区，再向相邻省区出兵。',884,245,195);text('相邻省区',884,380,14,'#e6cf9d',true);wrap(r.neighbors.map(id=>region(id).name).join(' · '),884,406,195,14);wrap('出兵必须留守一队。攻下需要出兵数大于驻军 + 筑垒。',884,475,195,14)}
  box(18,586,1087,32,'#162b2ce8','#e4d5ae44',7);text(s.history.at(-1)||'',34,608,14,'#e6ddc2');
  box(20,550,480,29,'#172d2bdd',null,6);[['player','青盟'],['neutral','中立'],['rival','赤盟']].forEach(([side,name],i)=>{ctx.fillStyle=colors[side];ctx.fillRect(34+i*91,560,11,11);text(name,51+i*91,571,13,colors[side])});text('八省或东港 · 八回合',315,571,13,'#f0dfb8');
 }
 return {tick,draw,getState:()=>({...structuredClone(s),regions:structuredClone(REALM_REGIONS),rules:{...rules},income:income(),owned:owned().length,preview:preview()}),getStatus:()=>{
  const p=selected(),r=region(p.id),common={goal:s.won?'半岛协定完成':s.phase==='lost'?'返回本回合重新安排军政':s.phase==='enemy'?'赤盟行动，观察地图归属与驻军变化':s.phase==='summary'?'本回合结算：税收与赤盟行动已落地':'八回合内控制八省，或攻下首府东港',message:s.mode==='dispatch'?'从'+region(s.source).name+'出兵：点选相邻省区查看结果，再确认。所有行动消耗一道命令；每回合三道。':'点地图选省区。招募 6 金增加三队，开发 8 金增加每回合两金税收。出兵必须留守一队，兵力大于驻军加筑垒才能攻下。',stats:['第 '+s.round+'/8 回合','青盟 '+owned().length+'/8 省','金 '+s.gold,'命令 '+s.orders+'/3','税收 +'+income()]};
  if(s.won)return {...common,actions:[action('再次协定',replay)]};if(s.phase==='lost')return {...common,actions:[action('重试本回合',retry),action('重新开局',replay)]};if(s.phase==='enemy')return {...common,actions:[action('赤盟行动中',()=>{},true)]};if(s.phase==='summary')return {...common,message:s.lastRound.ai+' 税收 +'+s.lastRound.income+' 金。',actions:[action('继续第 '+s.round+' 回合',continueRound),action('重试上回合',retry)]};
  if(s.mode==='dispatch'){const pv=preview();return {...common,actions:[action('确认出兵'+(pv?' · '+pv.sent+' 队 → '+region(pv.target).name:''),dispatch,!pv||pv.sent<1||pv.overCapacity||s.orders<1),action(s.force==='all'?'切换半数出兵':'切换全部出兵',()=>{s.force=s.force==='all'?'half':'all'}),action('取消出兵',()=>{s.mode='inspect';s.source=s.target=null}),action('结束回合 · E',endTurn)]}}return {...common,actions:[action('招募 · '+r.name+' · 6 金 / +3',recruit,p.owner!=='player'||p.recruited||p.army>rules.maxArmy-3||s.gold<6||s.orders<1),action('开发 · '+r.name+' · 8 金 / 税收 +2',develop,p.owner!=='player'||p.developed||p.level>=2||s.gold<8||s.orders<1),action('相邻出兵 · '+r.name,beginDispatch,p.owner!=='player'||p.army<2||s.orders<1),action('结束回合 · E',endTurn),action('重试本回合',retry)]};
 },dispose(){effect=null}};
}
