import {W,H,clamp,images,canvasSurface} from './showcase-core.js';
import {pointerPosition} from './showcase-precision-kit.js';
import {observationPanel,sceneHeading,completion} from './showcase-observation-kit.js?v=20261004-2';

const D=[[0,-1],[1,0],[0,1],[-1,0]],opposite=d=>(d+2)%4;
export const CONDUIT_LEVELS=[
 {cols:5,rows:4,start:1,goal:3,name:'港口供水',path:[[0,1],[1,1],[1,0],[2,0],[3,0],[3,1],[3,2],[2,2],[2,3],[3,3],[4,3]],turns:[2,4,6,8]},
 {cols:6,rows:5,start:0,goal:4,name:'灯塔循环',path:[[0,0],[1,0],[2,0],[2,1],[1,1],[1,2],[1,3],[2,3],[2,2],[3,2],[4,2],[4,1],[4,0],[5,0],[5,1],[5,2],[5,3],[5,4]],turns:[1,3,5,7,9,11,13,15]}
];
export function conduitMask(tile){const base=tile.type==='straight'?10:9,r=((tile.rot%4)+4)%4;return ((base<<r)|(base>>(4-r)))&15}
const direction=(from,to)=>D.findIndex(([dx,dy])=>from[0]+dx===to[0]&&from[1]+dy===to[1]);
export function conduitSolution(level){const def=CONDUIT_LEVELS[level],tiles=Array.from({length:def.cols*def.rows},(_,i)=>({type:i%3?'elbow':'straight',rot:(i*7+level)%4}));def.path.forEach((p,n)=>{const prev=n?direction(p,def.path[n-1]):3,next=n+1<def.path.length?direction(p,def.path[n+1]):1,mask=(1<<prev)|(1<<next),type=opposite(prev)===next?'straight':'elbow';let rot=0;while(conduitMask({type,rot})!==mask)rot++;tiles[p[1]*def.cols+p[0]]={type,rot}});return tiles}
export function conduitFresh(level=0){const tiles=conduitSolution(level),def=CONDUIT_LEVELS[level];def.turns.forEach((n,k)=>{const [x,y]=def.path[n],t=tiles[y*def.cols+x];t.rot=(t.rot+(k%2?3:1))%4});return {version:1,level,tiles,selected:def.start*def.cols,moves:0,history:[],preview:false,phase:'edit',progress:0,won:false,completed:level}}
export function conduitRestore(raw){const level=Number.isInteger(raw?.level)?clamp(raw.level,0,1):0,s=conduitFresh(level);if(raw?.version!==1)return s;if(Array.isArray(raw.tiles)&&raw.tiles.length===s.tiles.length&&raw.tiles.every((t,i)=>t?.type===s.tiles[i].type&&Number.isInteger(t.rot)&&t.rot>=0&&t.rot<=3))s.tiles=raw.tiles.map(t=>({...t}));s.selected=Number.isInteger(raw.selected)?clamp(raw.selected,0,s.tiles.length-1):s.selected;s.moves=Number.isInteger(raw.moves)?clamp(raw.moves,0,100000):0;s.preview=raw.preview===true;s.history=Array.isArray(raw.history)?raw.history.filter(a=>Array.isArray(a)&&a.length===s.tiles.length&&a.every(n=>Number.isInteger(n)&&n>=0&&n<4)).slice(-50):[];s.phase=['edit','flow','cleared','won'].includes(raw.phase)?raw.phase:'edit';s.progress=Number.isFinite(raw.progress)?clamp(raw.progress,0,s.tiles.length+1):0;s.completed=Number.isInteger(raw.completed)?clamp(raw.completed,0,2):level;const trace=conduitTrace(s);if(['cleared','won'].includes(s.phase)&&!trace.reached)s.phase='edit';if(s.phase==='won'&&level!==1)s.phase='cleared';s.won=s.phase==='won';if(s.phase==='cleared')s.completed=Math.max(s.completed,1);if(s.won)s.completed=2;return s}
export function conduitTrace(s){const def=CONDUIT_LEVELS[s.level],cells=[],seen=new Set();let x=0,y=def.start,entry=3;for(let guard=0;guard<s.tiles.length+1;guard++){const index=y*def.cols+x,mask=conduitMask(s.tiles[index]);if(!(mask&(1<<entry)))return {cells,reached:false,fault:{index,edge:entry}};if(seen.has(index))return {cells,reached:false,fault:{index,edge:entry}};seen.add(index);const exit=[0,1,2,3].find(d=>d!==entry&&(mask&(1<<d)));cells.push({index,entry,exit});const nx=x+D[exit][0],ny=y+D[exit][1];if(nx<0||ny<0||nx>=def.cols||ny>=def.rows){const reached=x===def.cols-1&&y===def.goal&&exit===1;return {cells,reached,fault:reached?null:{index,edge:exit}}}x=nx;y=ny;entry=opposite(exit)}return {cells,reached:false,fault:{index:y*def.cols+x,edge:entry}}}
export function conduitRotate(s,index=s.selected){if(s.phase!=='edit'||!Number.isInteger(index)||index<0||index>=s.tiles.length)return false;s.history.push(s.tiles.map(t=>t.rot));if(s.history.length>50)s.history.shift();s.selected=index;s.tiles[index].rot=(s.tiles[index].rot+1)%4;s.moves++;return true}
export function conduitUndo(s){if(s.phase!=='edit'||!s.history.length)return false;const prev=s.history.pop();s.tiles.forEach((t,i)=>t.rot=prev[i]);s.moves=Math.max(0,s.moves-1);return true}
export function conduitLaunch(s){if(s.phase!=='edit')return false;s.phase='flow';s.progress=0;return true}
export function conduitStep(s,dt){if(s.phase!=='flow')return null;const trace=conduitTrace(s);s.progress+=Math.max(0,dt)*2.7;if(s.progress<trace.cells.length+.65)return null;if(trace.reached){s.completed=Math.max(s.completed,s.level+1);s.phase=s.level===1?'won':'cleared';s.won=s.phase==='won';return 'success'}s.phase='edit';s.progress=0;return 'leak'}
export function conduitNext(s){return s.phase==='cleared'?conduitFresh(1):s}
export function conduitGeometry(s){const def=CONDUIT_LEVELS[s.level],size=s.level===0?94:80;return {size,x:(W-def.cols*size)/2,y:112,cols:def.cols,rows:def.rows}}

export async function createConduit({host,input,saved,notify=()=>{},sfx=()=>{}}){
 const art=await images(['cabinet','straight','elbow'],'assets/game-forms/conduit/'),{element,ctx}=canvasSurface(host);element.style.touchAction='none';element.setAttribute('aria-label','铜潮管网：点击铜管旋转；方向键选格，空格旋转；下方按钮启动水泵');
 let s=conduitRestore(saved),active=false,message='把左侧水源接到右侧出水口，点每片铜管旋转。',time=0,fault=null,faultLife=0,angles=s.tiles.map(t=>t.rot*Math.PI/2);
 if(s.won)message='两套供水管网都已恢复。';else if(s.phase==='cleared')message='港口供水恢复，可进入下一套管网。';else if(s.phase==='flow')message='已恢复上次的输送，水流沿接好的线路继续。';else if(s.moves)message='已保留上次的铜管方向，继续调整或启动水泵。';
 const ui=observationPanel(host,'conduit',`<div class="observation-toolbar"><span class="readout" aria-live="polite"></span><button type="button" class="primary pump">启动水泵</button><button type="button" class="preview">连通预览：关</button><button type="button" class="undo">撤销旋转</button></div><div class="conduit-pad" role="group" aria-label="选格和旋转"><button type="button" data-d="3" aria-label="选择左格">← 左格</button><button type="button" data-d="0" aria-label="选择上格">↑ 上格</button><button type="button" class="rotate primary" aria-label="旋转选中">旋转</button><button type="button" data-d="2" aria-label="选择下格">↓ 下格</button><button type="button" data-d="1" aria-label="选择右格">→ 右格</button></div><p class="observation-help">点铜管顺时针旋转；选格按钮适合窄屏。启动后水流沿实际接口前进，断口可继续调整。</p>`);
 const pump=ui.panel.querySelector('.pump'),preview=ui.panel.querySelector('.preview'),undo=ui.panel.querySelector('.undo'),rotate=ui.panel.querySelector('.rotate'),readout=ui.panel.querySelector('.readout'),pad=[...ui.panel.querySelectorAll('[data-d]')];
 const address=i=>String.fromCharCode(65+i%CONDUIT_LEVELS[s.level].cols)+(Math.floor(i/CONDUIT_LEVELS[s.level].cols)+1);
 function sync(){const edit=active&&s.phase==='edit';rotate.disabled=undo.disabled=!edit;undo.disabled=!edit||!s.history.length;pad.forEach(b=>b.disabled=!edit);preview.disabled=!active;preview.textContent='连通预览：'+(s.preview?'开':'关');preview.setAttribute('aria-pressed',String(s.preview));pump.disabled=!active||['flow','won'].includes(s.phase);pump.textContent=s.phase==='flow'?'正在输送…':s.phase==='cleared'?'下一个管网':'启动水泵';readout.textContent=`${s.level+1}/2 · ${CONDUIT_LEVELS[s.level].name} · 选中 ${address(s.selected)} · ${s.moves} 次旋转`}
 function turn(i=s.selected){if(active&&conduitRotate(s,i)){message='已旋转 '+address(i)+'。让两端接口相接。';faultLife=0;sfx('turn');sync()}}
 function select(d){if(!active||s.phase!=='edit')return;const def=CONDUIT_LEVELS[s.level],x=s.selected%def.cols,y=Math.floor(s.selected/def.cols),nx=clamp(x+D[d][0],0,def.cols-1),ny=clamp(y+D[d][1],0,def.rows-1);s.selected=ny*def.cols+nx;sync()}
 pad.forEach(b=>b.onclick=()=>select(Number(b.dataset.d)));rotate.onclick=()=>turn();undo.onclick=()=>{if(active&&conduitUndo(s)){message='已撤销上一次旋转。';faultLife=0;sync()}};preview.onclick=()=>{if(active){s.preview=!s.preview;sync()}};
 pump.onclick=()=>{if(!active)return;if(s.phase==='cleared'){s=conduitNext(s);angles=s.tiles.map(t=>t.rot*Math.PI/2);message='第二个管网有更多转折，逐段接好接口。';faultLife=0;sync();return}if(conduitLaunch(s)){message='水泵启动，观察水流通过铜管的实际路线。';faultLife=0;sfx('water');sync()}};
 const click=e=>{if(!active||s.phase!=='edit')return;const p=pointerPosition(element,e),g=conduitGeometry(s),x=Math.floor((p.x-g.x)/g.size),y=Math.floor((p.y-g.y)/g.size);if(x>=0&&y>=0&&x<g.cols&&y<g.rows)turn(y*g.cols+x)};element.addEventListener('click',click);
 function tick(dt){if(!active)return;dt=Number.isFinite(dt)?Math.max(0,dt):0;time+=dt;faultLife=Math.max(0,faultLife-dt);for(const [key,d] of [['ArrowUp',0],['KeyW',0],['ArrowRight',1],['KeyD',1],['ArrowDown',2],['KeyS',2],['ArrowLeft',3],['KeyA',3]])if(input.pressed.has(key))select(d);if(input.pressed.has('Space')||input.pressed.has('KeyR'))turn();if(input.pressed.has('KeyE'))pump.click();if(input.pressed.has('KeyC'))undo.click();const result=conduitStep(s,dt);if(result){if(result==='success'){message=s.won?'两套供水管网都已恢复。':'港口供水恢复，可进入下一套管网。';sfx('success')}else{fault=conduitTrace(s).fault;faultLife=4;message='水流在 '+address(fault.index)+' 的接口断开。检查光圈处，调整后可再次启动。';sfx('hurt')}sync()}angles.forEach((a,i)=>{let delta=s.tiles[i].rot*Math.PI/2-a;while(delta>Math.PI)delta-=Math.PI*2;while(delta<-Math.PI)delta+=Math.PI*2;angles[i]=a+delta*Math.min(1,dt*14)})}
 function point(g,index,edge){const x=g.x+(index%g.cols+.5)*g.size,y=g.y+(Math.floor(index/g.cols)+.5)*g.size;return {x:x+D[edge][0]*g.size*.5,y:y+D[edge][1]*g.size*.5}}
 function route(ctx,g,cell,fraction,color){const a=point(g,cell.index,cell.entry),b=point(g,cell.index,cell.exit),cx=g.x+(cell.index%g.cols+.5)*g.size,cy=g.y+(Math.floor(cell.index/g.cols)+.5)*g.size;ctx.save();ctx.strokeStyle=color;ctx.lineWidth=4;ctx.lineCap='round';ctx.shadowBlur=9;ctx.shadowColor=color;ctx.beginPath();if(opposite(cell.entry)===cell.exit){ctx.moveTo(a.x,a.y);ctx.lineTo(a.x+(b.x-a.x)*fraction,a.y+(b.y-a.y)*fraction)}else{const steps=Math.max(1,Math.ceil(20*fraction));ctx.moveTo(a.x,a.y);for(let k=1;k<=steps;k++){const t=fraction*k/steps,mt=1-t;ctx.lineTo(mt*mt*a.x+2*mt*t*cx+t*t*b.x,mt*mt*a.y+2*mt*t*cy+t*t*b.y)}}ctx.stroke();ctx.restore()}
 function port(g,side,row,text,lit){const x=side==='left'?g.x-42:g.x+g.cols*g.size+42,y=g.y+(row+.5)*g.size;ctx.save();ctx.shadowColor=lit?'#8cebe5':'#a48d5c';ctx.shadowBlur=lit?16:0;ctx.fillStyle=lit?'#73cfc4':'#383e35';ctx.strokeStyle='#dac599';ctx.lineWidth=2;ctx.beginPath();ctx.arc(x,y,15,0,Math.PI*2);ctx.fill();ctx.stroke();ctx.shadowBlur=0;ctx.textAlign='center';ctx.font='13px "Microsoft YaHei",sans-serif';ctx.fillStyle='#eddfbc';ctx.fillText(text,x,y+34);ctx.strokeStyle=lit?'#87e2cd':'#8c7754';ctx.lineWidth=9;ctx.beginPath();ctx.moveTo(side==='left'?x+15:x-15,y);ctx.lineTo(side==='left'?g.x:g.x+g.cols*g.size,y);ctx.stroke();ctx.restore()}
 function draw(){ctx.drawImage(art.cabinet,0,0,W,H);const g=conduitGeometry(s),def=CONDUIT_LEVELS[s.level],trace=conduitTrace(s);ctx.save();ctx.shadowColor='#000a';ctx.shadowBlur=24;ctx.fillStyle='#07141c';ctx.fillRect(g.x-6,g.y-6,g.cols*g.size+12,g.rows*g.size+12);ctx.restore();s.tiles.forEach((tile,i)=>{const x=g.x+(i%g.cols+.5)*g.size,y=g.y+(Math.floor(i/g.cols)+.5)*g.size;ctx.save();ctx.translate(x,y);ctx.rotate(angles[i]);const im=art[tile.type];const crop=tile.type==='elbow'?[66,65,1138,1092]:[80,80,1096,1088];ctx.drawImage(im,...crop,-g.size/2,-g.size/2,g.size,g.size);ctx.restore()});if(s.preview)trace.cells.forEach(cell=>route(ctx,g,cell,1,'#8dc7b86b'));if(s.phase==='flow'||['cleared','won'].includes(s.phase))trace.cells.forEach((cell,i)=>{const fraction=s.phase==='flow'?clamp(s.progress-i,0,1):1;if(fraction>0)route(ctx,g,cell,fraction,'#9efbea')});ctx.save();const x=g.x+s.selected%g.cols*g.size,y=g.y+Math.floor(s.selected/g.cols)*g.size;ctx.strokeStyle='#ffe0a2';ctx.lineWidth=2.5;ctx.strokeRect(x+3,y+3,g.size-6,g.size-6);ctx.restore();if(faultLife>0&&fault){const p=point(g,fault.index,fault.edge);ctx.save();ctx.strokeStyle='#ffb77a';ctx.shadowColor='#fa925f';ctx.shadowBlur=12;ctx.lineWidth=3;ctx.beginPath();ctx.arc(p.x,p.y,13+Math.sin(time*6)*3,0,Math.PI*2);ctx.stroke();ctx.restore()}port(g,'left',def.start,'水源',true);port(g,'right',def.goal,'出水口',['cleared','won'].includes(s.phase));ctx.save();ctx.fillStyle='#d7c8a9';ctx.font='12px sans-serif';ctx.textAlign='center';for(let c=0;c<g.cols;c++)ctx.fillText(String.fromCharCode(65+c),g.x+(c+.5)*g.size,g.y-13);ctx.textAlign='right';for(let r=0;r<g.rows;r++)ctx.fillText(r+1,g.x-10,g.y+(r+.5)*g.size+5);ctx.restore();sceneHeading(ctx,'铜潮管网',`${s.level+1}/2 ${def.name}     旋转接口 · 连通预览 · 启动水泵`);if(s.phase==='cleared')completion(ctx,'港口供水已接通','水流到达出水口 · 下方进入下一套管网');if(s.won)completion(ctx,'两套管网全部恢复',`灯塔循环接通 · 本套 ${s.moves} 次旋转`)}
 sync();return {tick,draw,onStart(){active=true;sync()},setActive(v){if(active===v)return;active=v;sync()},getState(){return structuredClone(s)},getStatus(){return {goal:s.won?'两套供水管网已恢复':s.phase==='cleared'?'港口供水已完成，进入灯塔循环':'旋转铜管，把水源接到出水口',message,stats:[`管网 ${s.level+1}/2`,`旋转 ${s.moves} 次`,`连通 ${conduitTrace(s).cells.length} 片`,s.phase==='flow'?'水流输送中':s.phase==='edit'?'可调整接口':'已接通'],actions:[]}},dispose(){element.removeEventListener('click',click);ui.dispose()}};
}
