// Generated by scripts/align-lyrics.py from the lyric sheet and a Whisper
// word-level transcript of public/save-your-mac-with-chippytea.mp3.
// Times are seconds into the recording. Do not edit by hand.

export interface LyricWord {
  text: string;
  start: number;
  end: number;
}

export interface LyricLine {
  section: string;
  words: LyricWord[];
}

const w = (text: string, start: number, end: number): LyricWord => ({ text, start, end });

export const lyricLines: LyricLine[] = [
  { section: "intro", words: [w("Oi", 0.0, 0.22), w("mate,", 0.22, 0.72), w("I", 0.72, 0.84), w("just", 0.84, 1.14), w("want", 1.14, 1.38), w("my", 1.38, 1.68), w("chippy", 1.68, 2.12), w("tea!", 2.12, 2.34)] },
  { section: "chorus", words: [w("Ohhhh", 3.54, 4.3), w("chippy", 5.44, 5.73), w("tea,", 5.73, 5.88), w("chippy", 6.52, 7.16), w("tea,", 7.16, 7.48)] },
  { section: "chorus", words: [w("Come", 8.28, 8.72), w("and", 8.72, 8.9), w("save", 8.9, 9.22), w("your", 9.22, 9.68), w("Mac", 9.68, 9.86), w("some", 9.86, 10.26), w("storage", 10.26, 11.04), w("with", 11.04, 11.82), w("chippytea!", 11.82, 13.84)] },
  { section: "chorus", words: [w("Chips", 16.0, 16.76), w("for", 16.76, 17.38), w("me,", 17.38, 17.58), w("space", 17.94, 18.28), w("for", 18.28, 18.9), w("free,", 18.9, 19.26)] },
  { section: "chorus", words: [w("Clear", 19.64, 19.88), w("that", 19.88, 20.26), w("clutter,", 20.26, 20.64), w("keep", 21.36, 21.48), w("your", 21.44, 21.76), w("files,", 21.76, 22.04)] },
  { section: "chorus", words: [w("and", 22.54, 22.66), w("save", 22.62, 23.18), w("your", 23.18, 23.54), w("Mac", 23.54, 23.78), w("with", 23.78, 24.86), w("chippytea!", 24.86, 26.02)] },
  { section: "verse 1", words: [w("My", 28.18, 28.9), w("hard", 28.9, 29.18), w("drive's", 29.18, 29.7), w("full", 29.7, 29.92), w("of", 29.92, 30.28), w("holiday", 30.28, 30.86), w("snaps,", 30.86, 31.96)] },
  { section: "verse 1", words: [w("Old", 31.96, 32.09), w("downloads,", 32.09, 32.48), w("memes,", 32.86, 32.98), w("and", 33.26, 33.38), w("tax", 33.36, 33.56), w("mishaps.", 33.56, 34.36)] },
  { section: "verse 1", words: [w("chippytea", 35.0, 35.46), w("comes", 35.46, 36.08), w("with", 36.08, 36.46), w("a", 36.46, 36.58), w("clever", 36.58, 36.78), w("little", 36.78, 37.28), w("plan:", 37.28, 37.7)] },
  { section: "verse 1", words: [w("Find", 37.9, 38.28), w("those", 38.28, 38.52), w("chunky", 38.52, 38.86), w("files", 38.86, 39.18), w("and", 39.18, 39.52), w("bin", 39.52, 39.72), w("them", 39.72, 40.08), w("when", 40.08, 40.24), w("you", 40.24, 40.46), w("can!", 40.46, 40.72)] },
  { section: "pre-chorus", words: [w("Click-click,", 41.26, 41.82), w("sort", 42.1, 42.22), w("it", 42.2, 42.66), w("out,", 42.66, 42.94)] },
  { section: "pre-chorus", words: [w("Watch", 43.92, 44.36), w("those", 44.36, 44.72), w("little", 44.72, 44.9), w("chips", 44.9, 45.26), w("pop", 45.26, 45.66), w("out!", 45.66, 45.96)] },
  { section: "chorus", words: [w("Ohhhh", 46.4, 46.66), w("chippy", 48.58, 48.81), w("tea,", 48.81, 48.93), w("chippy", 49.56, 49.87), w("tea,", 49.87, 50.02)] },
  { section: "chorus", words: [w("Come", 51.38, 51.8), w("and", 51.8, 51.98), w("save", 51.98, 52.34), w("your", 52.34, 52.76), w("Mac", 52.76, 52.98), w("some", 52.98, 53.4), w("storage", 53.4, 54.06), w("with", 54.06, 54.92), w("chippytea!", 54.92, 55.28)] },
  { section: "chorus", words: [w("Chippy", 55.28, 56.12), w("tea,", 56.12, 56.54), w("chippy", 57.06, 58.27), w("tea!", 58.27, 58.88)] },
  { section: "chorus", words: [w("Chips", 59.52, 59.84), w("for", 59.84, 60.46), w("me,", 60.46, 60.66), w("space", 61.06, 61.36), w("for", 61.36, 61.98), w("free,", 61.98, 62.32)] },
  { section: "chorus", words: [w("Clear", 62.54, 62.88), w("that", 62.88, 63.38), w("clutter,", 63.38, 63.7), w("keep", 64.44, 64.56), w("your", 64.56, 64.86), w("files,", 64.86, 65.24)] },
  { section: "chorus", words: [w("and", 65.68, 65.8), w("save", 65.74, 66.22), w("your", 66.22, 66.62), w("Mac", 66.62, 66.86), w("with", 66.86, 67.92), w("chippytea!", 67.92, 69.08)] },
  { section: "verse 2", words: [w("There's", 71.12, 71.88), w("a", 71.88, 72.0), w("folder", 72.0, 72.28), w("called", 72.28, 72.98), w("\u201cNew", 72.98, 73.38), w("Folder", 73.38, 73.76), w("Two\u201d,", 73.76, 74.34)] },
  { section: "verse 2", words: [w("and", 74.78, 74.9), w("seventeen", 74.84, 75.66), w("copies", 75.66, 76.1), w("of", 76.1, 76.44), w("the", 76.44, 76.58), w("same", 76.58, 76.82), w("old", 76.82, 77.1), w("brew.", 77.1, 77.38)] },
  { section: "verse 2", words: [w("No", 77.92, 78.04), w("need", 78.02, 78.42), w("to", 78.42, 78.72), w("panic,", 78.72, 79.02), w("no", 79.4, 79.56), w("need", 79.56, 79.9), w("to", 79.9, 80.26), w("plead,", 80.26, 80.5)] },
  { section: "verse 2", words: [w("chippytea", 81.2, 81.62), w("finds", 81.62, 82.28), w("the", 82.28, 82.56), w("files", 82.56, 82.76), w("you", 82.76, 83.14), w("don't", 83.14, 83.58), w("need!", 83.58, 83.78)] },
  { section: "bridge", words: [w("Round", 83.78, 84.48), w("and", 84.48, 84.9), w("round", 84.9, 85.38), w("the", 85.8, 85.92), w("folders", 85.86, 86.16), w("go,", 86.16, 86.7)] },
  { section: "bridge", words: [w("High", 87.14, 87.48), w("score", 87.48, 87.9), w("rising,", 88.32, 88.7), w("nice", 88.7, 89.18), w("and", 89.18, 89.52), w("slow!", 89.52, 89.86)] },
  { section: "bridge", words: [w("One", 90.7, 90.82), w("more", 90.76, 91.08), w("chip,", 91.08, 91.44), w("then", 91.74, 91.86), w("one", 91.84, 92.2), w("more", 92.2, 92.64), w("cheer,", 92.64, 92.94)] },
  { section: "bridge", words: [w("Your", 93.46, 93.58), w("Mac's", 93.56, 93.96), w("got", 93.96, 94.14), w("room", 94.14, 94.48), w("for", 94.48, 94.9), w("another", 94.9, 95.34), w("year!", 95.34, 96.08)] },
  { section: "last chorus", words: [w("Ohhhh", 99.74, 100.04), w("chippy", 100.78, 101.09), w("tea,", 101.09, 101.24)] },
  { section: "last chorus", words: [w("chippy", 102.12, 102.57), w("tea,", 102.57, 102.8)] },
  { section: "last chorus", words: [w("Come", 103.62, 104.12), w("and", 104.12, 104.28), w("save", 104.28, 104.56), w("your", 104.56, 105.0), w("Mac", 105.0, 105.28), w("some", 105.28, 105.68), w("storage", 105.68, 106.04), w("with", 106.04, 107.18), w("chippytea!", 107.18, 108.96)] },
  { section: "last chorus", words: [w("Whoa,", 110.02, 110.78), w("whoa!", 110.78, 111.54)] },
  { section: "last chorus", words: [w("Chips", 111.54, 112.16), w("for", 112.16, 112.74), w("me,", 112.74, 112.96), w("space", 113.34, 113.64), w("for", 113.64, 114.26), w("free,", 114.26, 114.64)] },
  { section: "last chorus", words: [w("Clear", 114.98, 115.16), w("that", 115.16, 115.66), w("clutter,", 115.66, 115.94), w("keep", 116.76, 116.88), w("your", 116.86, 117.14), w("files,", 117.14, 117.46)] },
  { section: "last chorus", words: [w("and", 118.0, 118.12), w("save", 118.06, 118.46), w("your", 118.46, 118.94), w("Mac", 118.94, 119.16), w("with", 119.16, 120.32), w("chippytea!", 120.32, 121.02)] },
  { section: "last chorus", words: [w("Chippy", 121.66, 121.91), w("tea!", 121.91, 122.04), w("Chippy", 122.46, 122.69), w("tea!", 122.69, 122.81)] },
  { section: "last chorus", words: [w("Save", 122.8, 123.28), w("your", 123.28, 123.56), w("Mac", 123.56, 123.74), w("with", 123.74, 123.9), w("chippytea!", 123.9, 124.34)] },
  { section: "last chorus", words: [w("Chippy", 124.84, 125.01), w("tea!", 125.01, 125.13), w("Chippy", 125.26, 125.66), w("tea!", 125.66, 125.86)] },
  { section: "last chorus", words: [w("More", 126.34, 126.46), w("space,", 126.46, 126.72), w("more", 127.12, 127.26), w("chips,", 127.26, 127.58)] },
  { section: "last chorus", words: [w("hooray", 129.14, 129.9), w("for", 129.9, 130.28), w("me!", 130.28, 130.78)] },
];
