export const TOUR_STEPS = [
  {
    id: 'original',
    label: '原作体验',
    title: '从原作的互动开始',
    instruction: '点击原作庭院获得焦点，再按 E 投喂，观察鱼群转向和聚集。按 T 切换天气、C 切换镜头，比较同一场景的变化。',
    method: '原作以 Three.js 场景图组织程序化模型，用鱼群规则、自定义水面着色器和后处理逐帧生成画面。',
    value: '观察一次操作怎样带动角色、水面和镜头，为自己的互动场景确定参考。',
    actionLabel: '观察原作',
    topic: null,
    tab: 'original',
  },
  {
    id: 'construction',
    label: '庭院构造',
    title: '把生成图变成可探索空间',
    instruction: '查看生成效果图，再回到庭院拖动镜头，检查池塘、平台和建筑的位置关系。切换“俯瞰布局”，调节池塘尺度或建筑高度，观察空间如何变化。',
    method: '庭院按参数生成几何并用 PBR 材质表现表面，动物形体结合 SDF、Surface Nets 和截面网格构造。',
    value: '把一张设计图转成可调整、可从多角度检查的空间，适合景观预演和网页展示。',
    actionLabel: '查看生成图',
    topic: 'geometry',
    tab: 'scene',
  },
  {
    id: 'water',
    label: '水面反馈',
    title: '看一次扰动怎样改变水面',
    instruction: '加入水波，观察涟漪的传播，也可点击池塘连续加入扰动。在算法实验台切换“波面高度”或“波面法线”，再回到自然画面比较水面数据与反光。',
    method: '128² 双缓冲差分波场以固定步长更新，叠加四组 Gerstner 波，由共同法线驱动水面反光与折射。',
    value: '让点击、落料和动物活动产生环境反馈，适合可交互的水景展示。',
    actionLabel: '加入水波',
    topic: 'water',
    tab: 'scene',
  },
  {
    id: 'fish',
    label: '鱼群对照',
    title: '用同一起点验证鱼群规则',
    instruction: '一键运行两组4秒对照：A使用默认规则，B仅关闭分离。比较真实画面、轨迹与位置差；会替换已有实验结果并清空投喂，结果生成后暂停。',
    method: 'Boids 合成分离、对齐和聚集；A/B 从相同 seed 与初始状态按 1/60 秒实际重播，生成轨迹和画面对照。',
    value: '用可重复的比较判断参数如何改变群体行为，方便为展览或游戏选择运动节奏。',
    actionLabel: '运行鱼群 A/B 对照',
    topic: 'fish',
    tab: 'scene',
  },
  {
    id: 'feeding',
    label: '投喂互动',
    title: '把一个动作串成连续反馈',
    instruction: '开始投喂，观察捏料、松指、六粒饲料落水和鱼的追食。画面下方按本轮区分释放、实际落水与吞食；可暂停检查或提前收手，已撒颗粒会继续模拟。鱼数量为0时仅观察落料与水面反馈，可自行增加鱼数量再观察追食。',
    method: '26 骨骼手通过 CCD 和状态机控制动作，饲料采样共同波面、鱼嘴按几何条件吞食；接触与水动力采用实时近似。',
    value: '把角色、道具和环境按顺序联动，适合游戏操作与互动演示。',
    actionLabel: '开始投喂',
    topic: 'feeding',
    tab: 'scene',
  },
];
