import {Raycaster,Vector2,Vector3,Plane,MOUSE,TOUCH} from 'three';
import {WaterfallEngine} from './gpu.js';
import {DX,GRID,clamp} from './world.js';
import {raycastTerrain,sampleField,surfaceHeight} from './voxel.js';
import {DEFAULT_SOURCE,PROJECT_LIMITS,decodeProject,encodeProject,historySnapshot} from './project.js';
import {DEFAULT_SOURCE_CONFIG,allSources,changeSource} from './sources.js';
import {aimJet,traceJet} from './jet.js';
import {BrushStroke,brushEdits} from './stroke.js';
import {ObjectPicker,ObjectGroupDrag,ObjectSelection,copyObjects,selectionBounds,mirrorSource} from './object-editor.js';
import {CAMERA_VIEW_LIMIT,saveCameraView,removeCameraView} from './camera-views.js';
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const AUTO='waterfalls-lab:v2:autosave',LIBRARY='waterfalls-lab:v2:library';
let toastTimer,saveTimer,saveDirty=false;
function toast(message){$('#toast').textContent=message;$('#toast').classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('#toast').classList.remove('show'),2800);}
const engine=new WaterfallEngine($('#world'),(message,error)=>{if(error){$('#loading').style.display='flex';$('#loading-text').textContent=message;$('#loading').querySelector('small').textContent='请重新加载，或使用支持 WebGPU 的浏览器。';document.body.dataset.status='error';}else toast(message);});
let tool='orbit',history=[],future=[],gesture=null,audio=null,selected=null,brushSize=.85,currentName='我的山谷',pointerHit=null,activeSource=0,brushStrength=.65,mirror=false,temporaryOrbit=false,lastPointer=null,touchTimer=null,touchPointers=new Map(),aiming=false,jetPreview=null;
let activeCameraView=null,immersionTool='orbit';
const ray=new Raycaster(),pointer=new Vector2(),point=new Vector3();
const objectPicker=new ObjectPicker(),selection=new ObjectSelection();
let restored=null;try{const text=localStorage.getItem(AUTO);if(text){restored=decodeProject(text);engine.state=restored.scene;currentName=restored.name;}}catch{}
function camera(){return engine.cameraState();}
function syncCameraViews(){const views=engine.state.cameraViews||[],menu=$('#camera-view-select'),signature=JSON.stringify(views.map(view=>view.name));if(menu.dataset.signature!==signature){menu.dataset.signature=signature;menu.replaceChildren(new Option(views.length?'选择收藏镜头':'还没有收藏镜头',''),...views.map((view,i)=>new Option((i+1)+' · '+view.name,String(i))));}if(activeCameraView!==null&&activeCameraView>=views.length)activeCameraView=null;menu.value=activeCameraView===null?'':String(activeCameraView);$('#camera-view-count').textContent=views.length+' / '+CAMERA_VIEW_LIMIT;$('#camera-view-update').disabled=activeCameraView===null;$('#camera-view-remove').disabled=activeCameraView===null;}
function clearCameraView(){activeCameraView=null;$('#camera-view-name').value='';}
function saveNow(){if(!engine.camera||!saveDirty)return;clearTimeout(saveTimer);saveTimer=null;try{localStorage.setItem(AUTO,encodeProject(engine.state,camera(),currentName));saveDirty=false;$('#autosave-state').textContent='已自动保存';document.body.dataset.saved='yes';}catch{$('#autosave-state').textContent='保存失败，请导出作品文件';document.body.dataset.saved='failed';toast('保存失败，请导出作品文件');}}
function stash(){if(!engine.camera)return;saveDirty=true;document.body.dataset.saved='pending';$('#autosave-state').textContent='正在保存…';$('#work-download').hidden=true;clearTimeout(saveTimer);saveTimer=setTimeout(saveNow,650);}
function saveBeforeLeaving(){if(document.body.dataset.status!=='ready')return;clearTimeout(touchTimer);touchTimer=null;touchPointers.clear();if(gesture)endGesture();stash();saveNow();}
function pushHistory(entry){history.push(entry);if(history.length>60)history.shift();future=[];updateHistory();}
function snapshot(full=false){pushHistory(historySnapshot(engine.state,currentName,camera(),full===true));}
function snapshotCameraViews(){pushHistory({kind:'camera',views:structuredClone(engine.state.cameraViews||[])});}
function updateHistory(){$('#undo').disabled=!history.length;$('#redo').disabled=!future.length;}
function readouts(){document.body.dataset.objects=JSON.stringify(engine.state.objects);document.body.dataset.edits=String(engine.state.edits.length);document.body.dataset.source=JSON.stringify(engine.state.source);const sources=allSources(engine.state);document.body.dataset.sources=JSON.stringify(sources);$('#scene-count').textContent=engine.state.objects.length+' 件造景 · '+engine.state.edits.length+' 次地形编辑 · '+sources.length+' 处水源';const menu=$('#object-select'),signature=engine.state.objects.map(o=>o.id).join('|');if(menu.dataset.signature!==signature){menu.dataset.signature=signature;menu.replaceChildren(new Option(engine.state.objects.length?'选择已有造景':'还没有造景',''));engine.state.objects.forEach((o,i)=>menu.append(new Option((o.type==='rock'?'岩石':'地形')+' '+(i+1),String(i))));}menu.value=selected===null?'':String(selected);const sourceMenu=$('#source-select');if(sourceMenu.options.length!==sources.length){sourceMenu.replaceChildren(...sources.map((source,i)=>new Option('水源 '+(i+1),String(i))));}activeSource=Math.min(activeSource,sources.length-1);sourceMenu.value=String(activeSource);}
function refresh(terrainChanged=false,movingIndices=[]){if(terrainChanged)engine.updateTerrain();else{engine.updateObjects(movingIndices);engine.rebuildWorld();}readouts();syncObjectUI();stash();}
function syncUI(){
  for(const name of ['flow','speed','gravity','viscosity','exposure']){$('#'+name).value=engine.state[name];$('#'+name+'-value').textContent=name==='flow'?Math.round(engine.state[name]*100)+'%':name==='speed'?engine.state[name].toFixed(2)+'×':name==='viscosity'?engine.state[name].toFixed(3):engine.state[name].toFixed(1);}
  $('#surface-smoothing').value=String(engine.state.surfaceSmoothing??1);$('#quality').value=engine.state.quality;$('#mode').value=engine.state.mode;$('#work-name').value=currentName;$('#water-style').value=String(engine.state.waterStyle||0);$('#foam').value=engine.state.foam??.65;$('#foam-value').textContent=Math.round((engine.state.foam??.65)*100)+'%';syncSourceUI();
  $$('[data-preset]').forEach(b=>b.classList.toggle('active',+b.dataset.preset===engine.state.preset));$$('[data-light]').forEach(b=>b.classList.toggle('active',+b.dataset.light===engine.state.sun));
  $('.scene-label>span').textContent=['苔谷 / MOSS CANYON','秋林 / AMBER FOREST','溪阶 / RIVER STEPS'][engine.state.preset];syncCameraViews();
  $('#pause').textContent=engine.state.paused?'▷ 继续水流':'Ⅱ 暂停水流';$('#pause').setAttribute('aria-pressed',String(engine.state.paused));if(engine.camera){const poses={wide:[14,12,23],close:[7.5,7.5,11],top:[.2,24,5],side:[18,8,1]};$$('[data-view]').forEach(b=>b.classList.toggle('active',engine.camera.position.distanceTo(new Vector3(...poses[b.dataset.view]))<.2));}readouts();syncSourceUI();syncObjectUI();updateHistory();
}
function syncObjectUI(){const indices=selection.indices(engine.state.objects);selected=selection.primary(engine.state.objects);const o=selected===null?null:engine.state.objects[selected];document.body.dataset.selection=JSON.stringify(indices);$('#object-select').value=o?String(selected):'';$('#object-controls').hidden=!o;$('#object-properties').hidden=indices.length>1;$('#select-all').disabled=!engine.state.objects.length;$('#selection-clear').disabled=!indices.length;$('#selected-status').textContent=indices.length>1?indices.length+' 件造景 · 一起移动或批量操作':o?(o.type==='rock'?'岩石':'地形')+' · 已选取':'点击选取一件造景';if(o){['x','y','z'].forEach((name,i)=>{$('#obj-'+name).value=o.scale[i];$('#obj-'+name+'-value').textContent=o.scale[i].toFixed(2);$('#object-pos-'+name).value=o.position[i].toFixed(2);});$('#obj-height').value=o.position[1];$('#obj-rotation').value=(o.rotation||0)*180/Math.PI;}}
function clearSelection(){selection.clear();selected=null;engine.selection=null;}
function updateSelection(){selected=selection.primary(engine.state.objects);engine.selection=selection.indices(engine.state.objects);engine.rebuildWorld();syncObjectUI();}
function select(index,additive=false){selection.choose(engine.state.objects,index,additive);updateSelection();}
function selectMany(indices,active=indices.at(-1)){selection.replace(engine.state.objects,indices,active);updateSelection();}
function pick(event){setRay(event);return objectPicker.pick(engine.state.objects,ray.ray.origin.toArray(),ray.ray.direction.toArray(),engine.terrainField)?.index??null;}
function setRay(event){const rect=engine.canvas.getBoundingClientRect();pointer.set((event.clientX-rect.left)/rect.width*2-1,-(event.clientY-rect.top)/rect.height*2+1);ray.setFromCamera(pointer,engine.camera);}
function groundPoint(event,y=null){setRay(event);if(y!==null){const hit=ray.ray.intersectPlane(new Plane(new Vector3(0,1,0),-y),point);return hit?{point:hit.toArray(),normal:[0,1,0]}:null;}const hit=raycastTerrain(engine.terrainField,ray.ray.origin.toArray(),ray.ray.direction.toArray());if(hit)return hit;if(['add','restore','spring','flatten'].includes(tool)){const p=ray.ray.intersectPlane(new Plane(new Vector3(0,1,0),-.24),point);if(p&&Math.abs(p.x)<5.5&&Math.abs(p.z)<4.5)return {point:p.toArray(),normal:[0,1,0]};}return null;}
const hints={orbit:'拖动旋转 · 双指 / 右键平移 · 滚轮缩放',rock:'点击放置岩石 · 大小可调 · 放置后可选取编辑',add:'按住拖动堆筑地形 · 新地形会改变水路',cut:'按住拖动挖掘 · 可挖穿岩壁形成洞口',restore:'按住拖动恢复原有地形 · 不影响摆放物体',spring:'点击移动当前水源 · 新增水源可形成汇流 · 右键旋转视角',smooth:'按住拖动平滑表面 · 保留整体地形 · 右键旋转视角',flatten:'按住拖动削平 · 同一次笔画保持相同高度 · 右键旋转视角',move:'拖动选中造景一起移动 · Ctrl 点击多选 · Shift 升降',erase:'点击移除造景 · 或选取后按 Delete'};
function setTool(value){if(gesture)endGesture();setAim(false);gesture=null;tool=value;engine.controls.enabled=true;engine.controls.mouseButtons.LEFT=value==='orbit'?MOUSE.ROTATE:-1;engine.controls.mouseButtons.RIGHT=value==='orbit'?MOUSE.PAN:MOUSE.ROTATE;engine.controls.mouseButtons.MIDDLE=MOUSE.PAN;engine.controls.touches.ONE=value==='orbit'?TOUCH.ROTATE:-1;engine.controls.touches.TWO=TOUCH.DOLLY_PAN;document.body.classList.toggle('editing',value!=='orbit');$$('[data-tool]').forEach(b=>{const active=b.dataset.tool===value||(b.dataset.tool==='cut'&&['smooth','flatten','restore'].includes(value));b.classList.toggle('active',active);b.setAttribute('aria-pressed',String(active));});$('#hint').textContent=hints[value];$('#edit-title').textContent={rock:'放下石头',add:'堆筑地形',cut:'挖出水路',restore:'恢复地形',spring:'编排水流',smooth:'柔化地形',flatten:'削出平面',move:'编辑造景',erase:'移除造景',orbit:'自由造景'}[value];$('#brush-settings').hidden=['move','erase','spring'].includes(value);$('#restore-brush').hidden=!['add','cut','smooth','flatten','restore'].includes(value);$('#sculpt-settings').hidden=value==='rock';$('#brush-mode').hidden=value==='rock';if(value!=='rock')$('#brush-mode').value=value;$('#brush-strength-setting').hidden=!['smooth','flatten'].includes(value);$('#selection-editor').hidden=!['rock','move','erase'].includes(value);$('#spring-settings').hidden=value!=='spring';$('#brush-cursor').hidden=true;$('#brush-preview').hidden=true;engine.canvas.style.cursor=value==='orbit'?'grab':value==='move'?'move':'crosshair';}
function applyBrushes(hits){
  if(!hits.length)return;
  const edits=brushEdits(hits,{op:tool,radius:brushSize,strength:brushStrength,mirror,level:gesture?.level});
  if(engine.state.edits.length+edits.length>PROJECT_LIMITS.edits){toast('已达到作品文件的地形记录容量，请保存此作品后开始新的造景。');return;}
  engine.state.edits.push(...edits);refresh(true);
}
function cursor(event,hit){
  $('#brush-cursor').hidden=true;const el=$('#brush-preview');if(!hit||!['rock','add','cut','restore','smooth','flatten'].includes(tool)){el.hidden=true;return;}
  const ring=(center,normal)=>{const p=new Vector3(...center),n=new Vector3(...normal),reference=Math.abs(n.y)>.9?new Vector3(1,0,0):new Vector3(0,1,0),u=new Vector3().crossVectors(n,reference).normalize(),v=new Vector3().crossVectors(n,u);let d='';for(let j=0;j<=48;j++){const a=j/48*Math.PI*2,q=p.clone().addScaledVector(u,Math.cos(a)*brushSize).addScaledVector(v,Math.sin(a)*brushSize).addScaledVector(n,.025).project(engine.camera);if(q.z<0||q.z>1)return '';d+=(j?'L':'M')+((q.x*.5+.5)*engine.canvas.clientWidth).toFixed(1)+','+((-q.y*.5+.5)*engine.canvas.clientHeight).toFixed(1);}return d+'Z';};
  el.hidden=false;$('#brush-ring').setAttribute('d',ring(hit.point,hit.normal));$('#brush-mirror-ring').setAttribute('d',mirror?ring([-hit.point[0],hit.point[1],hit.point[2]],[-hit.normal[0],hit.normal[1],hit.normal[2]]):'');
}
function beginEdit(event){
  if(!engine.device||tool==='orbit'||(event.pointerType!=='touch'&&event.button!==0)||event.altKey)return;
  if(tool==='move'||tool==='erase'){
    const index=pick(event),additive=event.ctrlKey||event.metaKey||$('#selection-additive').checked;
    if(tool==='move'&&additive&&(index===null||!selection.ids.has(engine.state.objects[index].id))){select(index,true);return;}
    if(index!==null&&tool==='move'&&selection.ids.has(engine.state.objects[index].id)){selection.active=engine.state.objects[index].id;updateSelection();}else select(index);
    if(index===null){toast('点击可见造景，或从“已有造景”菜单选取。');return;}
    if(tool==='erase'){snapshot();engine.state.objects.splice(index,1);select(null);refresh();return;}
    const indices=selection.indices(engine.state.objects),o=engine.state.objects[index],axis=event.shiftKey?'y':$('#move-axis').value,normal=Math.abs(ray.ray.direction.y)>.08?new Vector3(0,1,0):engine.camera.getWorldDirection(new Vector3()),plane=new Plane().setFromNormalAndCoplanarPoint(normal,new Vector3(...o.position));
    gesture={kind:'move',index,indices,plane,toggleOnClick:additive,startPointer:[event.clientX,event.clientY],moved:false,drag:new ObjectGroupDrag(indices.map(i=>engine.state.objects[i].position),ray.ray.intersectPlane(plane,point)?.toArray(),event.clientY,axis,indices.indexOf(index)),changed:false,dirty:false,timer:null,lastTime:0};
    if(event.type!=='pointerup')engine.canvas.setPointerCapture(event.pointerId);return;
  }
  const hit=groundPoint(event);if(!hit)return;
  if(tool==='rock'&&engine.state.objects.length>=PROJECT_LIMITS.objects){toast('作品最多保存 2,000 件造景，请保存当前作品后开始新的造景。');return;}
  if(tool==='spring'&&aiming){const angles=aimJet(allSources(engine.state)[activeSource],hit.point,engine.state.gravity);if(!angles){toast('当前速度无法到达这里，请增大喷射速度或选择更近的落点。');return;}snapshot();changeSource(engine.state,activeSource,angles);setAim(false);sourceRefresh();toast('喷射方向已调整，轨迹显示预计首次触地位置。');return;}
  snapshot();
  if(tool==='spring'){changeSource(engine.state,activeSource,{position:hit.point.map((v,i)=>clamp(v+hit.normal[i]*.55+(i===1?.2:0),i===0?-5.3:i===1?.3:-4.6,i===0?5.3:i===1?12.4:4.6))});sourceRefresh();toast('水源已移动，水流正在寻找新的路径。');return;}
  if(tool==='rock'){const scale=[brushSize,brushSize*.82,brushSize*.9].map(v=>Math.round(v*100)/100);engine.state.objects.push({id:crypto.randomUUID(),type:'rock',position:[hit.point[0],hit.point[1]+scale[1]*.5,hit.point[2]],scale,rotation:0});select(engine.state.objects.length-1);refresh();return;}
  gesture={kind:'sculpt',stroke:new BrushStroke(hit,brushSize),pending:[],lastTime:performance.now(),level:hit.point[1]};if(event.type!=='pointerup')engine.canvas.setPointerCapture(event.pointerId);applyBrushes([hit]);
}
function flushMove(g){clearTimeout(g.timer);g.timer=null;if(g.dirty){g.dirty=false;g.lastTime=performance.now();refresh(false,g.indices);}}
function moveObject(event){const g=gesture,o=engine.state.objects[g.index];if(!o)return;g.moved ||= Math.hypot(event.clientX-g.startPointer[0],event.clientY-g.startPointer[1])>4;const axis=event.shiftKey?'y':$('#move-axis').value;if(axis!==g.drag.axis)g.plane.setFromNormalAndCoplanarPoint(g.plane.normal,new Vector3(...o.position));setRay(event);const p=axis==='y'?null:ray.ray.intersectPlane(g.plane,point)?.toArray(),positions=g.drag.update(p,event.clientY,axis,+$('#move-snap').value);if(positions.every((position,j)=>position.every((v,i)=>Math.abs(v-engine.state.objects[g.indices[j]].position[i])<1e-8)))return;if(!g.changed){snapshot();g.changed=true;}g.indices.forEach((index,i)=>engine.state.objects[index].position=positions[i]);g.dirty=true;const delay=32-(performance.now()-g.lastTime);if(delay<=0)flushMove(g);else if(g.timer===null)g.timer=setTimeout(()=>{if(gesture===g)flushMove(g);},delay);}
$('#world').addEventListener('pointerdown',event=>{lastPointer=event;if(event.pointerType==='touch'){touchPointers.set(event.pointerId,event);if(touchPointers.size>1){clearTimeout(touchTimer);touchTimer=null;endGesture();return;}clearTimeout(touchTimer);touchTimer=setTimeout(()=>{touchTimer=null;if(touchPointers.size===1)beginEdit(touchPointers.values().next().value);},120);}else beginEdit(event);});
$('#world').addEventListener('pointermove',event=>{
  lastPointer=event;if(event.pointerType==='touch'&&touchPointers.has(event.pointerId))touchPointers.set(event.pointerId,event);if(!engine.device||tool==='orbit'||temporaryOrbit||touchPointers.size>1)return;const hit=groundPoint(event);pointerHit=hit;cursor(event,hit);
  if(!gesture)return;
  if(gesture.kind==='move'){moveObject(event);return;}
  gesture.pending.push(...gesture.stroke.sample(hit));if(performance.now()-gesture.lastTime<45&&gesture.pending.length<64)return;const hits=gesture.pending;gesture.pending=[];gesture.lastTime=performance.now();applyBrushes(hits);
});
function endGesture(event=null){if(gesture?.kind==='move'){if(event)moveObject(event);flushMove(gesture);if(event?.type==='pointerup'&&gesture.toggleOnClick&&!gesture.changed&&!gesture.moved)select(gesture.index,true);syncObjectUI();}if(gesture?.kind==='sculpt'){if(event)gesture.pending.push(...gesture.stroke.sample(groundPoint(event)));applyBrushes(gesture.pending);}gesture=null;stash();}
$('#world').addEventListener('pointerup',event=>{if(event.pointerType==='touch'){if(touchTimer&&touchPointers.size===1){clearTimeout(touchTimer);touchTimer=null;beginEdit(event);}touchPointers.delete(event.pointerId);}endGesture(event);});$('#world').addEventListener('pointercancel',event=>{clearTimeout(touchTimer);touchTimer=null;touchPointers.delete(event.pointerId);endGesture();});$('#world').addEventListener('pointerleave',()=>{$('#brush-cursor').hidden=true;$('#brush-preview').hidden=true;});
$$('[data-tool]').forEach(b=>b.addEventListener('click',()=>setTool(b.dataset.tool)));
function undo(redo=false){if(gesture)endGesture();const from=redo?future:history,to=redo?history:future;if(!from.length)return;const previous=from.pop();if(previous.kind==='camera'){to.push({kind:'camera',views:structuredClone(engine.state.cameraViews||[])});engine.state.cameraViews=previous.views;clearCameraView();syncUI();stash();toast(redo?'已重做镜头编辑。':'已撤销镜头编辑。');return;}to.push(historySnapshot(engine.state,currentName,camera(),previous.full));Object.assign(engine.state,previous.scene);currentName=previous.name;clearSelection();setAim(false);if(previous.full){activeSource=0;clearCameraView();engine.reset();engine.resize();engine.restoreCamera(previous.camera);select(null);readouts();stash();}else{select(null);refresh(true);}syncUI();toast(redo?'已重做造景。':'已撤销造景。');}
$('#undo').addEventListener('click',()=>undo());$('#redo').addEventListener('click',()=>undo(true));
$('#brush-mode').addEventListener('change',event=>setTool(event.target.value));$('#brush-mirror').addEventListener('change',event=>{mirror=event.target.checked;if(lastPointer)cursor(lastPointer,pointerHit);});$('#brush-strength').addEventListener('input',event=>{brushStrength=+event.target.value;$('#brush-strength-value').textContent=Math.round(brushStrength*100)+'%';});
$('#brush-size').addEventListener('input',event=>{brushSize=+event.target.value;$('#brush-value').textContent=brushSize.toFixed(2)+' m';});$('#restore-brush').addEventListener('click',()=>setTool('restore'));
function rangeHistory(el){el.addEventListener('pointerdown',snapshot);el.addEventListener('keydown',event=>{if(!event.repeat&&!event.ctrlKey&&!event.metaKey&&['ArrowUp','ArrowDown','ArrowLeft','ArrowRight','Home','End','PageUp','PageDown'].includes(event.key))snapshot();});}
for(const [i,name] of ['x','y','z'].entries()){const el=$('#obj-'+name);rangeHistory(el);el.addEventListener('input',()=>{if(selected===null)return;engine.state.objects[selected].scale[i]=+el.value;$('#obj-'+name+'-value').textContent=(+el.value).toFixed(2);refresh(false,[selected]);});}
for(const [name,property] of [['height','height'],['rotation','rotation']]){const el=$('#obj-'+name);rangeHistory(el);el.addEventListener('input',()=>{if(selected===null)return;const o=engine.state.objects[selected];if(property==='height')o.position[1]=+el.value;else o.rotation=+el.value*Math.PI/180;refresh(false,[selected]);});}
$('#snap-ground').addEventListener('click',()=>{if(selected===null)return;if(gesture)endGesture();snapshot();const indices=selection.indices(engine.state.objects);for(const index of indices){const o=engine.state.objects[index];o.position[1]=clamp(surfaceHeight(engine.terrainField,o.position[0],o.position[2])+o.scale[1]*.5,.12,12.4);}refresh(false,indices);});
function duplicateSelected(mirrored=false){if(selected===null)return;if(gesture)endGesture();const indices=selection.indices(engine.state.objects);if(engine.state.objects.length+indices.length>PROJECT_LIMITS.objects){toast('这组副本超过作品的 2,000 件容量，可减少选择后再复制。');return;}snapshot();const active=indices.indexOf(selected),start=engine.state.objects.length,copies=copyObjects(engine.state.objects,indices,()=>crypto.randomUUID(),mirrored);engine.state.objects.push(...copies);selectMany(copies.map((o,i)=>start+i),start+active);refresh();if(mirrored)toast('镜像造景已放在山谷另一侧，可继续移动。');}
$('#clone-object').addEventListener('click',()=>duplicateSelected());
$('#mirror-object').addEventListener('click',()=>duplicateSelected(true));
function removeSelected(){if(selected===null)return;if(gesture)endGesture();snapshot();engine.state.objects=engine.state.objects.filter(o=>!selection.ids.has(o.id));select(null);refresh();}
$('#delete-object').addEventListener('click',removeSelected);
$('#object-select').addEventListener('change',event=>{if(gesture)endGesture();select(event.target.value===''?null:+event.target.value,$('#selection-additive').checked);});
$('#select-all').addEventListener('click',()=>{if(gesture)endGesture();selectMany(engine.state.objects.map((o,i)=>i));});
$('#selection-clear').addEventListener('click',()=>{if(gesture)endGesture();select(null);});
function syncSourceUI(){
  const source=allSources(engine.state)[activeSource];if(!source)return;
  $('#source-select').value=String(activeSource);$('#source-delete').disabled=allSources(engine.state).length===1;$('#spring-enabled').checked=source.enabled;
  $('#spring-height').value=source.position[1];$('#spring-height-value').textContent=source.position[1].toFixed(2)+' m';
  for(const name of ['radius','power','yaw','pitch','speed']){$('#spring-'+name).value=source[name];$('#spring-'+name+'-value').textContent=name==='power'?Math.round(source[name]*100)+'%':['yaw','pitch'].includes(name)?Math.round(source[name])+'°':source[name].toFixed(2)+(name==='speed'?' m/s':' m');}
  ['x','y','z'].forEach((name,i)=>$('#source-pos-'+name).value=source.position[i].toFixed(2));
}
function sourceRefresh(){engine.updateSources();readouts();syncSourceUI();stash();}
function setAim(value){aiming=value;$('#source-aim').setAttribute('aria-pressed',String(value));$('#source-aim').textContent=value?'取消瞄准':'瞄准落点';if(tool==='spring')$('#hint').textContent=value?'点击地形选择落点 · 右键旋转视角 · Esc 取消':'点击移动当前水源 · 新增水源可形成汇流 · 右键旋转视角';}
$('#source-aim').addEventListener('click',()=>setAim(!aiming));
$('#source-select').addEventListener('change',event=>{setAim(false);activeSource=+event.target.value;syncSourceUI();});
$('#source-add').addEventListener('click',()=>{if(allSources(engine.state).length>=PROJECT_LIMITS.sources){toast('已达到作品文件的 256 处水源容量。');return;}snapshot();const source=structuredClone(allSources(engine.state)[activeSource]);source.position[0]=clamp(source.position[0]+.9,-5.3,5.3);source.enabled=true;engine.state.extraSources.push(source);activeSource=engine.state.extraSources.length;sourceRefresh();toast('新增水源，可点击地形为它选择出水位置。');});
$('#source-mirror').addEventListener('click',()=>{if(allSources(engine.state).length>=PROJECT_LIMITS.sources){toast('已达到作品文件的 256 处水源容量。');return;}snapshot();setAim(false);engine.state.extraSources.push(mirrorSource(allSources(engine.state)[activeSource]));activeSource=engine.state.extraSources.length;sourceRefresh();toast('镜像水源已创建，位置与水平流向左右对称。');});
$('#source-delete').addEventListener('click',()=>{if(allSources(engine.state).length===1)return;snapshot();if(activeSource===0){const first=engine.state.extraSources.shift();changeSource(engine.state,0,first);}else engine.state.extraSources.splice(activeSource-1,1);activeSource=0;sourceRefresh();});
$('#spring-enabled').addEventListener('change',event=>{snapshot();changeSource(engine.state,activeSource,{enabled:event.target.checked});sourceRefresh();});
for(const name of ['height','radius','power','yaw','pitch','speed']){const el=$('#spring-'+name);rangeHistory(el);el.addEventListener('input',()=>{if(name==='height'){const position=[...allSources(engine.state)[activeSource].position];position[1]=+el.value;changeSource(engine.state,activeSource,{position});}else changeSource(engine.state,activeSource,{[name]:+el.value});sourceRefresh();});}
$('#spring-reset').addEventListener('click',()=>{snapshot();changeSource(engine.state,activeSource,{...DEFAULT_SOURCE_CONFIG,position:[...DEFAULT_SOURCE]});sourceRefresh();});
for(const prefix of ['object','source'])['x','y','z'].forEach((name,i)=>{const el=$('#'+prefix+'-pos-'+name);el.addEventListener('change',()=>{const value=el.valueAsNumber;if(!Number.isFinite(value)){if(prefix==='object')select(selected);else syncSourceUI();return;}if(prefix==='object'&&selected===null)return;snapshot();const position=[...(prefix==='source'?allSources(engine.state)[activeSource].position:engine.state.objects[selected].position)];position[i]=clamp(value,+el.min,+el.max);if(prefix==='source'){changeSource(engine.state,activeSource,{position});sourceRefresh();}else{engine.state.objects[selected].position=position;select(selected);refresh(false,[selected]);}});});
function focus(){if(tool==='spring'){const source=allSources(engine.state)[activeSource];engine.focusAt(source.position,source.radius);}else if(selected!==null){const bounds=selectionBounds(engine.state.objects,selection.indices(engine.state.objects));engine.focusAt(bounds.center,bounds.radius);}else if(pointerHit)engine.focusAt(pointerHit.point,brushSize);else{toast('选取一件造景或水源后即可聚焦。');return;}stash();}
$('#focus-object').addEventListener('click',focus);$('#source-focus').addEventListener('click',focus);
$('#surface-smoothing').addEventListener('change',event=>{engine.state.surfaceSmoothing=+event.target.value;stash();});
$('#water-style').addEventListener('change',event=>{engine.state.waterStyle=+event.target.value;stash();});$('#foam').addEventListener('input',event=>{engine.state.foam=+event.target.value;$('#foam-value').textContent=Math.round(engine.state.foam*100)+'%';stash();});
for(const name of ['flow','speed','gravity','viscosity','exposure'])$('#'+name).addEventListener('input',event=>{engine.state[name]=+event.target.value;syncUI();stash();});
$$('[data-light]').forEach(b=>b.addEventListener('click',()=>{engine.state.sun=+b.dataset.light;engine.shadowDirty=true;syncUI();stash();}));
$$('[data-view]').forEach(b=>b.addEventListener('click',()=>{engine.setView(b.dataset.view);$$('[data-view]').forEach(el=>el.classList.toggle('active',el===b));stash();}));
$('#camera-view-select').addEventListener('change',()=>{const value=$('#camera-view-select').value;activeCameraView=value===''?null:Number(value);const view=engine.state.cameraViews?.[activeCameraView];if(view){engine.restoreCamera(view.camera);$('#camera-view-name').value=view.name;syncUI();stash();}else{clearCameraView();syncCameraViews();}});
function saveView(update=false){if(update&&activeCameraView===null)return;if(gesture)endGesture();try{const result=saveCameraView(engine.state.cameraViews||[],camera(),$('#camera-view-name').value,update?activeCameraView:null);snapshotCameraViews();engine.state.cameraViews=result.views;activeCameraView=result.index;$('#camera-view-name').value=result.views[result.index].name;syncCameraViews();stash();toast(update?'镜头已更新，可撤销恢复。':'当前镜头已收藏，会随作品一起保存。');}catch(e){toast(e.message);}}
$('#camera-view-add').addEventListener('click',()=>saveView());$('#camera-view-update').addEventListener('click',()=>saveView(true));$('#camera-view-remove').addEventListener('click',()=>{if(activeCameraView===null)return;snapshotCameraViews();engine.state.cameraViews=removeCameraView(engine.state.cameraViews||[],activeCameraView);clearCameraView();syncCameraViews();stash();toast('镜头已移除，可撤销恢复。');});
function setImmersive(enabled){if(enabled===document.body.classList.contains('clean'))return;if(enabled){immersionTool=tool;setTool('orbit');document.body.classList.add('clean');}else{document.body.classList.remove('clean');setTool(immersionTool);}$('#immersive-exit').hidden=!enabled;$('#immersive-toggle').setAttribute('aria-pressed',String(enabled));$(enabled?'#immersive-exit':'#immersive-toggle').focus();}
$('#immersive-toggle').addEventListener('click',()=>setImmersive(true));$('#immersive-exit').addEventListener('click',()=>setImmersive(false));
function reset(){if(gesture)endGesture();snapshot(true);engine.state.objects=[];engine.state.edits=[];engine.state.source=[...DEFAULT_SOURCE];engine.state.sourceConfig={...DEFAULT_SOURCE_CONFIG};engine.state.extraSources=[];activeSource=0;clearSelection();engine.reset();select(null);syncUI();stash();toast('风景已重置，可撤销恢复。');}
$('#reset').addEventListener('click',reset);
$$('[data-preset]').forEach(b=>b.addEventListener('click',()=>{if(gesture)endGesture();snapshot(true);engine.state.preset=+b.dataset.preset;engine.state.season=engine.state.preset===1?'autumn':'summer';engine.state.objects=[];engine.state.edits=[];engine.state.source=[...DEFAULT_SOURCE];engine.state.sourceConfig={...DEFAULT_SOURCE_CONFIG};engine.state.extraSources=[];activeSource=0;select(null);engine.reset();syncUI();stash();}));
$('#quality').addEventListener('change',event=>{if(gesture)endGesture();engine.state.quality=event.target.value;engine.reset();engine.resize();stash();toast('画质已更新，造景仍然保留。');});
function pause(){engine.state.paused=!engine.state.paused;syncUI();stash();}$('#pause').addEventListener('click',pause);
$('#panel-toggle').addEventListener('click',()=>{const collapsed=$('#panel-body').hidden;$('#panel-body').hidden=!collapsed;$('#panel-toggle').textContent=collapsed?'−':'+';$('#panel-toggle').setAttribute('aria-expanded',String(collapsed));$('#panel-toggle').setAttribute('aria-label',collapsed?'收起风景控制':'展开风景控制');});
$('#edit-dock-toggle').addEventListener('click',()=>{const collapsed=$('#edit-dock').classList.toggle('dock-collapsed');$('#edit-dock-toggle').setAttribute('aria-expanded',String(!collapsed));$('#edit-dock-toggle').setAttribute('aria-label',collapsed?'展开编辑面板':'收起编辑面板');$('#edit-dock-toggle').textContent=collapsed?'+':'−';});
$('#about-open').addEventListener('click',()=>$('#about').showModal());$('#about-close').addEventListener('click',()=>$('#about').close());
$('#mode').addEventListener('change',e=>{engine.state.mode=+e.target.value;stash();});
$('#inspect').addEventListener('click',async()=>{const out=$('#inspection');out.textContent='正在读取当前模拟状态…';try{const data=await engine.readParticles();let valid=0,finite=0,minJ=Infinity,maxJ=0,active=0,penetration=0;for(let i=0;i<data.length;i+=20){if(data[i+3]<0)continue;active++;if([...data.subarray(i,i+20)].every(Number.isFinite))finite++;if(data[i]>=1&&data[i]<GRID[0]&&data[i+1]>=0&&data[i+1]<GRID[1]&&data[i+2]>=1&&data[i+2]<GRID[2])valid++;const p=[(data[i]-GRID[0]/2)*DX,data[i+1]*DX,(data[i+2]-GRID[2]/2)*DX];if(sampleField(engine.collisionField,p)<-.3)penetration++;minJ=Math.min(minJ,data[i+3]);maxJ=Math.max(maxJ,data[i+3]);}const volume=active?minJ.toFixed(3)+'–'+maxJ.toFixed(3):'无活跃水粒子';out.textContent=`${active.toLocaleString()} 活跃粒子；有限值 ${finite}/${active}；范围内 ${valid}/${active}；固体内 ${penetration}；体积比 ${volume}；累计 ${engine.stats.steps} 子步。`;out.dataset.result=finite===active&&valid===active&&penetration===0?'pass':'fail';document.body.dataset.physics=out.dataset.result;out.dataset.penetration=String(penetration);}catch(e){out.textContent=e.message;}});
$('#capture').addEventListener('click',async()=>{try{if(engine.worldReady!==engine.worldVersion){toast('地形正在重建，完成后即可保存画面。');return;}const blob=await engine.screenshot(),reader=new FileReader();const url=await new Promise((resolve,reject)=>{reader.onload=()=>resolve(reader.result);reader.onerror=reject;reader.readAsDataURL(blob);});$('#capture-preview').src=url;$('#capture-download').href=url;$('#capture-download').download='waterfalls-'+new Date().toISOString().replaceAll(':','-')+'.png';$('#capture-dialog').showModal();}catch(e){toast('保存失败：'+e.message);}});$('#capture-close').addEventListener('click',()=>$('#capture-dialog').close());

function library(){try{const data=JSON.parse(localStorage.getItem(LIBRARY)||'[]');return Array.isArray(data)?data:[];}catch{return [];}}
function renderLibrary(){const list=$('#work-list');list.replaceChildren();const items=library();$('#work-empty').hidden=items.length>0;for(const entry of items){const row=document.createElement('div');row.className='work-row';const button=document.createElement('button');button.className='load-work';button.textContent=entry.name||'我的山谷';button.addEventListener('click',()=>{try{load(decodeProject(entry.text));$('#works').close();toast('作品已打开。');}catch(e){toast(e.message);}});const meta=document.createElement('small');meta.textContent=new Date(entry.updated).toLocaleString('zh-CN');row.append(button,meta);list.append(row);}}
function load(doc){if(gesture)endGesture();snapshot(true);activeSource=0;engine.state=doc.scene;currentName=doc.name;clearSelection();clearCameraView();engine.reset();engine.resize();engine.restoreCamera(doc.camera);syncUI();setTool('orbit');stash();}
$('#works-open').addEventListener('click',()=>{$('#work-name').value=currentName;renderLibrary();$('#works').showModal();});$('#works-close').addEventListener('click',()=>$('#works').close());
$('#save-work').addEventListener('click',()=>{currentName=$('#work-name').value.trim().slice(0,80)||'我的山谷';try{const items=library(),text=encodeProject(engine.state,camera(),currentName),index=items.findIndex(e=>e.name===currentName),entry={name:currentName,updated:Date.now(),text};if(index>=0)items[index]=entry;else items.unshift(entry);localStorage.setItem(LIBRARY,JSON.stringify(items));stash();renderLibrary();$('#work-message').textContent='作品已保存到此浏览器。';}catch{$('#work-message').textContent='本地存储已满，请导出作品文件。';}});
$('#work-name').addEventListener('input',()=>$('#work-download').hidden=true);
$('#export-work').addEventListener('click',()=>{if(gesture)endGesture();currentName=$('#work-name').value.trim().slice(0,80)||'我的山谷';stash();const text=encodeProject(engine.state,camera(),currentName);$('#work-download').href='data:application/json;charset=utf-8,'+encodeURIComponent(text);$('#work-download').download='waterfalls-project.json';$('#work-download').hidden=false;$('#work-message').textContent='作品文件已生成。点击下载即可在另一台设备重新打开。';});
$('#import-work').addEventListener('click',()=>$('#work-file').click());$('#work-file').addEventListener('change',async event=>{const file=event.target.files[0];if(!file)return;try{if(file.size>PROJECT_LIMITS.bytes)throw new Error('作品文件超过 5 MB。');load(decodeProject(await file.text()));$('#works').close();toast('作品文件已打开。');}catch(e){$('#work-message').textContent=e.message;}finally{event.target.value='';}});
$('#restore-work').addEventListener('click',()=>{try{const saved=localStorage.getItem(AUTO);if(!saved)throw new Error('还没有自动保存的作品。');load(decodeProject(saved));$('#works').close();toast('已恢复最近编辑。');}catch(e){$('#work-message').textContent=e.message;}});
$('#tunnel-example').addEventListener('click',()=>{if(gesture)endGesture();snapshot(true);engine.state.preset=0;engine.state.season='summer';engine.state.cameraViews=[];clearCameraView();engine.state.objects=[];engine.state.edits=[...[-2.6,-2.1,-1.6,-1.1,-.6,-.1].map(z=>({op:'cut',center:[0,1.85,z],radius:1.12})),...[5.7,4.7,3.7].map(y=>({op:'cut',center:[0,y,-2.2],radius:1.12}))];engine.state.source=[0,2.5,-2.6];engine.state.sourceConfig={...DEFAULT_SOURCE_CONFIG};engine.state.extraSources=[];activeSource=0;clearSelection();engine.reset();engine.setView('close');currentName='穿山溪流';syncUI();setTool('orbit');stash();$('#works').close();toast('穿山溪流已打开，可继续挖掘或撤销恢复原场景。');});

$('#confluence-example').addEventListener('click',()=>{if(gesture)endGesture();snapshot(true);engine.state.preset=2;engine.state.season='summer';engine.state.cameraViews=[];clearCameraView();engine.state.objects=[];engine.state.edits=[];engine.state.source=[-1.75,10.35,-3.1];engine.state.sourceConfig={...DEFAULT_SOURCE_CONFIG,radius:.32,yaw:20,pitch:-30,speed:2.8};engine.state.extraSources=[{...DEFAULT_SOURCE_CONFIG,position:[1.75,10.35,-3.1],radius:.32,yaw:-20,pitch:-30,speed:2.8}];engine.state.flow=1;activeSource=0;clearSelection();engine.reset();engine.setView('wide');currentName='双瀑汇流';syncUI();setTool('spring');stash();$('#works').close();toast('双瀑汇流已打开，可以逐个调整水源或撤销恢复。');});

$('#sound').addEventListener('click',async()=>{if(!audio){const context=new AudioContext(),buffer=context.createBuffer(1,context.sampleRate*3,context.sampleRate),values=buffer.getChannelData(0);let previous=0;for(let i=0;i<values.length;i++){previous=(previous+Math.random()*.08-.04)/1.02;values[i]=previous*5;}const source=context.createBufferSource();source.buffer=buffer;source.loop=true;const low=context.createBiquadFilter();low.type='lowpass';low.frequency.value=1700;const gain=context.createGain();gain.gain.value=.18;source.connect(low).connect(gain).connect(context.destination);source.start();audio={context,gain,on:true};}else{audio.on=!audio.on;audio.gain.gain.setTargetAtTime(audio.on?.18:0,audio.context.currentTime,.25);}await audio.context.resume();$('#sound').setAttribute('aria-pressed',String(audio.on));$('#sound').classList.toggle('active',audio.on);$('#sound span').textContent=audio.on?'静音':'水声';});
document.addEventListener('keydown',event=>{if($('dialog[open]')||!engine.controls)return;if(event.target.matches('input,select,textarea')||event.target.isContentEditable)return;if(document.body.classList.contains('clean')){if(event.key==='Escape'||event.key.toLowerCase()==='h'){event.preventDefault();setImmersive(false);}else if(event.code==='Space'){event.preventDefault();pause();}return;}if((event.ctrlKey||event.metaKey)&&event.key.toLowerCase()==='z'){event.preventDefault();undo(event.shiftKey);return;}if((event.ctrlKey||event.metaKey)&&event.key.toLowerCase()==='a'&&['rock','move','erase'].includes(tool)){event.preventDefault();$('#select-all').click();return;}if((event.ctrlKey||event.metaKey)&&event.key.toLowerCase()==='d'){event.preventDefault();if(gesture)endGesture();if(tool==='spring')$('#source-add').click();else if(selected!==null)$('#clone-object').click();return;}if(event.key==='Alt'){if(gesture)endGesture();temporaryOrbit=true;engine.controls.mouseButtons.LEFT=MOUSE.ROTATE;return;}if(event.key.toLowerCase()==='f'){focus();return;}if(event.code==='Space'){event.preventDefault();pause();}if(event.key.toLowerCase()==='h'){setImmersive(true);return;}if(event.key==='Escape'){if(aiming)setAim(false);else setTool('orbit');}if(event.key.toLowerCase()==='r')reset();if(event.key==='Delete'||event.key==='Backspace'){event.preventDefault();if(tool==='spring')$('#source-delete').click();else removeSelected();}const keys={v:'orbit',b:'add',x:'cut',g:'move',w:'spring'};if(keys[event.key.toLowerCase()])setTool(keys[event.key.toLowerCase()]);});
document.addEventListener('keyup',event=>{if(event.key==='Alt'){temporaryOrbit=false;setTool(tool);}});window.addEventListener('blur',()=>{temporaryOrbit=false;if(engine.controls)setTool(tool);});
window.addEventListener('pagehide',saveBeforeLeaving);
document.addEventListener('visibilitychange',()=>{if(document.hidden)saveBeforeLeaving();if(audio)audio.gain.gain.setTargetAtTime(document.hidden?0:audio.on?.18:0,audio.context.currentTime,.1);});
function updateJetPreview(){
  const svg=$('#jet-preview');svg.hidden=tool!=='spring'||!$('#show-jet-preview').checked;
  if(svg.hidden||!engine.collisionField)return;
  const source=allSources(engine.state)[activeSource],key=JSON.stringify([source,engine.state.gravity,engine.state.flow]);
  if(jetPreview?.key!==key||jetPreview?.field!==engine.collisionField||jetPreview?.revision!==engine.collisionRevision){const result=traceJet({...source,enabled:source.enabled&&engine.state.flow>0},engine.state.gravity,engine.collisionField);jetPreview={key,field:engine.collisionField,revision:engine.collisionRevision,result};const labels={off:'当前水源未出水',outside:'轨迹离开山谷范围',blocked:'出水口在实体内，可尝试抬高',open:'空中轨迹预计继续延伸'};$('#source-flight-status').textContent=result.impact?'预计首次触地：'+result.impact.map(v=>v.toFixed(2)).join(' / ')+' m':labels[result.reason];}
  const result=jetPreview.result;let d='',connected=false;
  for(const position of result.points){const p=new Vector3(...position).project(engine.camera);if(p.z<0||p.z>1){connected=false;continue;}d+=(connected?'L':'M')+((p.x*.5+.5)*engine.canvas.clientWidth).toFixed(1)+','+((-p.y*.5+.5)*engine.canvas.clientHeight).toFixed(1);connected=true;}
  $('#jet-line').setAttribute('d',d);const marker=$('#jet-impact');marker.style.display='none';
  if(result.impact){const p=new Vector3(...result.impact).project(engine.camera);if(p.z>=0&&p.z<=1){marker.setAttribute('cx',(p.x*.5+.5)*engine.canvas.clientWidth);marker.setAttribute('cy',(-p.y*.5+.5)*engine.canvas.clientHeight);marker.style.display='';}}
}
setInterval(()=>{if(!engine.camera)return;updateJetPreview();$('#fps').textContent=engine.stats.fps||'—';document.body.dataset.frames=String(engine.frame);document.body.dataset.particles=String(engine.count||0);$('#terrain-state').textContent=engine.worldReady===engine.worldVersion?'地形已同步':'正在雕刻…';const sources=allSources(engine.state),container=$('#source-markers');if(container.children.length!==sources.length){container.replaceChildren(...sources.map((source,i)=>{const button=document.createElement('button');button.className='source-marker';button.type='button';button.textContent='水源 '+(i+1);button.setAttribute('aria-label','选取水源 '+(i+1));button.addEventListener('click',()=>{activeSource=i;setTool('spring');syncSourceUI();});return button;}));}sources.forEach((source,i)=>{const p=new Vector3(...source.position).project(engine.camera),marker=container.children[i];marker.hidden=p.z<0||p.z>1||Math.abs(p.x)>1||Math.abs(p.y)>1||(tool!=='spring'&&sources.length===1);marker.classList.toggle('active',tool==='spring'&&i===activeSource);marker.classList.toggle('off',!source.enabled||source.power===0);marker.style.left=((p.x*.5+.5)*engine.canvas.clientWidth)+'px';marker.style.top=((-p.y*.5+.5)*engine.canvas.clientHeight)+'px';});},160);
try{await engine.init();engine.restoreCamera(restored?.camera);engine.controls.addEventListener('end',stash);engine.controls.addEventListener('change',()=>{if(lastPointer&&tool!=='orbit'&&!gesture){pointerHit=groundPoint(lastPointer);cursor(lastPointer,pointerHit);}});$('#loading').style.display='none';document.body.dataset.status='ready';syncUI();setTool('orbit');if(restored)toast('已恢复上次编辑的作品。');if(matchMedia('(max-width:720px)').matches){$('#panel-body').hidden=true;$('#panel-toggle').textContent='+';$('#panel-toggle').setAttribute('aria-expanded','false');$('#panel-toggle').setAttribute('aria-label','展开风景控制');}stash();}catch(error){console.error(error);$('#loading-text').textContent=error.message;$('#loading').querySelector('small').textContent='建议在支持 WebGPU 的 Chrome / Edge 中打开。';document.body.dataset.status='error';}
