const fs=require('fs'),path=require('path'),assert=require('assert');const {chromium}=require('./browser.cjs');const project=path.resolve(__dirname,'..');
(async()=>{const checks=[],errors=[];const browser=await chromium.launch({headless:true,args:['--use-angle=swiftshader','--enable-unsafe-swiftshader','--ignore-gpu-blocklist']});try{
 const page=await browser.newPage({viewport:{width:1440,height:960}});page.on('pageerror',e=>errors.push(e.message));await page.route('https://dumpling-dell.pages.dev/**',r=>r.fulfill({status:200,contentType:'text/html',body:'Original runtime verified in validation.json'}));
 await page.goto('http://127.0.0.1:8962/?style=papercut&group=new#lab',{waitUntil:'domcontentloaded'});await page.waitForFunction(()=>window.styleLab?.styles.length===20);assert.equal(await page.locator('.style-tab:visible').count(),10);checks.push('URL 恢复新增风格分组');
 await page.locator('#open-bun').click();await page.waitForTimeout(1100);await page.locator('#style-gallery').scrollIntoViewIfNeeded();await page.waitForFunction(()=>[...document.querySelectorAll('.gallery-card:not([hidden]) img')].every(i=>i.complete&&i.naturalWidth>0));await page.locator('#style-gallery').screenshot({path:path.join(project,'assets/style-expansion-overview.png')});checks.push('十个新增风格对照图加载并捕获');
 await page.locator('[data-style-filter=all]').click();await page.locator('#style-gallery').scrollIntoViewIfNeeded();await page.waitForFunction(()=>[...document.querySelectorAll('.gallery-card img')].every(i=>i.complete&&i.naturalWidth>0));checks.push('二十张真实风格图片全部加载');
 for(const f of ['style.css','app.js','styles.js','render2d.js','render-extra.js','render3d.js','vendor/three-r160.min.js','THREE-LICENSE.txt',...await page.evaluate(()=>styleLab.styles.map(id=>'assets/style-'+id+'.webp'))]){const r=await page.request.get('http://127.0.0.1:8962/'+f);assert(r.ok(),f);checks.push(f+' HTTP '+r.status())}
 await page.locator('#lab').scrollIntoViewIfNeeded();const captureStyle=await page.addStyleTag({content:'.site-head,.skip{visibility:hidden!important}'});await page.locator('#lab').screenshot({path:path.join(project,'assets/style-lab-overview.png')});await captureStyle.evaluate(el=>el.remove());
 await page.setViewportSize({width:390,height:844});await page.locator('[data-style-filter=new]').click();await page.locator('#lab').scrollIntoViewIfNeeded();assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),'mobile overflow');checks.push('最终手机布局无横向溢出');await page.screenshot({path:path.join(project,'assets/mobile-lab.png')});assert.equal(errors.length,0,errors.join(';'));checks.push('最终资源接入后无运行错误');fs.writeFileSync(path.join(project,'notes/final-check.json'),JSON.stringify({date:'2026-10-02',checks,errors},null,2)+'\n');console.log('FINAL',checks.length,'checks');
 }finally{await browser.close()}})().catch(e=>{console.error(e);process.exitCode=1});

