from pathlib import Path
ROOT=Path(__file__).resolve().parents[1]
target=ROOT/'web/showcase-angler-polished.js'
s=target.read_text(encoding='utf-8')
s=s.replace("const models=await modelsAt('assets/showcase/nature/',NATURE),world=", "const [models,forest]=await Promise.all([modelsAt('assets/showcase/nature/',NATURE),modelsAt('assets/game-forms/polish/',['angler-pine'])]),world=")
start=s.index(' renderer.toneMappingExposure=')
end=s.index(' const matRod=',start)
scene=r'''
 renderer.toneMappingExposure=1.02;scene.fog=new THREE.FogExp2('#778d93',.009);
 const textureLoader=new THREE.TextureLoader(),[skyTexture,shoreTexture]=await Promise.all([textureLoader.loadAsync('assets/game-forms/polish/angler-sky.webp'),textureLoader.loadAsync('assets/game-forms/polish/shore.webp')]);
 skyTexture.colorSpace=THREE.SRGBColorSpace;skyTexture.mapping=THREE.EquirectangularReflectionMapping;scene.background=skyTexture;scene.environment=skyTexture;
 shoreTexture.colorSpace=THREE.SRGBColorSpace;shoreTexture.wrapS=shoreTexture.wrapT=THREE.RepeatWrapping;shoreTexture.anisotropy=Math.min(8,renderer.capabilities.getMaxAnisotropy());
 scene.add(new THREE.HemisphereLight(0xc2d3db,0x333b30,1.55));const sunlight=new THREE.DirectionalLight(0xffd0a1,2.4);sunlight.position.set(-22,12,-44);sunlight.castShadow=true;sunlight.shadow.mapSize.set(1536,1536);sunlight.shadow.camera.left=-24;sunlight.shadow.camera.right=24;sunlight.shadow.camera.top=22;sunlight.shadow.camera.bottom=-22;sunlight.shadow.normalBias=.04;scene.add(sunlight);
 const random=n=>{const x=Math.sin(n*129.63+7.3)*43812.97;return x-Math.floor(x)};
 const noise=(x,z)=>Math.sin(x*.38+Math.cos(z*.23))*Math.cos(z*.27+x*.13)*.55+Math.sin(x*.91-z*.63)*.12;
 const edge=z=>6.8-z*.13+Math.sin(z*.17)*1.15+Math.sin(z*.47)*.38;
 const frontEdge=x=>10.4+Math.sin(x*.23)*.65+Math.sin(x*.64)*.18;
 const terrainMat=new THREE.MeshStandardMaterial({map:shoreTexture,color:0xb3bca1,roughness:1,side:THREE.DoubleSide,vertexColors:true});
 function terrain(cols,rows,point){const pos=[],uv=[],colors=[],indices=[];for(let r=0;r<=rows;r++)for(let c=0;c<=cols;c++){const p=point(c/cols,r/rows);pos.push(p.x,p.y,p.z);uv.push(p.x*.10,p.z*.10);const height=clamp(p.y/2.3,0,1),wet=clamp((p.y+.08)/.65,0,1);colors.push(.50+wet*.18+height*.08,.48+wet*.25,.40+wet*.11)}for(let r=0;r<rows;r++)for(let c=0;c<cols;c++){const a=r*(cols+1)+c,b=a+1,d=a+cols+1,e=d+1;indices.push(a,d,b,b,d,e)}const g=new THREE.BufferGeometry();g.setAttribute('position',new THREE.Float32BufferAttribute(pos,3));g.setAttribute('uv',new THREE.Float32BufferAttribute(uv,2));g.setAttribute('color',new THREE.Float32BufferAttribute(colors,3));g.setIndex(indices);g.computeVertexNormals();const m=new THREE.Mesh(g,terrainMat);m.receiveShadow=true;scene.add(m);return m}
 for(const side of [-1,1])terrain(34,86,(u,v)=>{const z=13-v*105,x=side*(edge(z)-.42+u*27),rise=THREE.MathUtils.smoothstep(u,0,.35);return {x,y:-.14+rise*(1.5+Math.sin(z*.08)*.6)+noise(x,z)*Math.min(1,u*7)+u*u*2.8,z}});
 terrain(70,28,(u,v)=>{const x=-36+u*72,z=frontEdge(x)-.35+v*28;return {x,y:-.12+THREE.MathUtils.smoothstep(v,0,.12)*(.45+noise(x,z)*.2)+v*v*.9,z}});
 const waveUniforms={uTime:{value:s.elapsed},sun:{value:new THREE.Vector3(-.42,.22,-1).normalize()}};
 const water=new THREE.Mesh(new THREE.PlaneGeometry(180,210,110,128),new THREE.ShaderMaterial({uniforms:waveUniforms,transparent:true,depthWrite:false,vertexShader:'uniform float uTime;varying vec3 worldP;varying vec3 waveN;float wave(vec2 p){return sin(p.x*.45+p.y*.11+uTime*.43)*.033+cos(p.y*.31+p.x*.09-uTime*.31)*.022+sin(p.x*.91+p.y*.65+uTime*.71)*.006;}void main(){vec3 p=position;p.z+=wave(p.xy);float dx=(wave(p.xy+vec2(.05,0.))-wave(p.xy-vec2(.05,0.)))/.1;float dy=(wave(p.xy+vec2(0.,.05))-wave(p.xy-vec2(0.,.05)))/.1;worldP=(modelMatrix*vec4(p,1.)).xyz;waveN=normalize(mat3(modelMatrix)*vec3(-dx,-dy,1.));gl_Position=projectionMatrix*viewMatrix*vec4(worldP,1.);}',fragmentShader:'uniform float uTime;uniform vec3 sun;varying vec3 worldP;varying vec3 waveN;void main(){vec3 n=normalize(waveN),v=normalize(cameraPosition-worldP);float ed=6.8-worldP.z*.13+sin(worldP.z*.17)*1.15+sin(worldP.z*.47)*.38;float sideD=ed-abs(worldP.x);float frontD=10.4+sin(worldP.x*.23)*.65+sin(worldP.x*.64)*.18-worldP.z;float depth=min(sideD,frontD);float shallow=1.-smoothstep(.2,3.1,depth);float fres=pow(1.-max(0.,dot(n,v)),3.);float glitter=pow(max(0.,dot(reflect(-sun,n),v)),124.);float soft=pow(max(0.,dot(reflect(-sun,n),v)),18.);vec3 c=mix(vec3(.04,.155,.19),vec3(.12,.29,.26),shallow);c=mix(c,vec3(.43,.51,.55),fres*.65);c+=vec3(1.,.68,.38)*(glitter*.72+soft*.13);float foam=(1.-smoothstep(.06,.52,abs(depth-.12+sin(worldP.z*1.3+uTime*.5)*.08)))*(.17+.14*sin(worldP.x*3.+worldP.z*2.1+uTime));c=mix(c,vec3(.80,.85,.77),max(0.,foam));gl_FragColor=vec4(c,.88);}'}));water.rotation.x=-Math.PI/2;water.position.z=-45;scene.add(water);
 function authored(name,size,x,y,z,angle=0,axis='y'){const o=fitModel(models[name],size,axis);o.traverse(mesh=>{if(mesh.isMesh){mesh.material=Array.isArray(mesh.material)?mesh.material.map(m=>m.clone()):mesh.material.clone();for(const material of Array.isArray(mesh.material)?mesh.material:[mesh.material]){material.metalness=0;material.roughness=.9;if(name==='path_wood')material.color.multiplyScalar(.58)}}});o.position.set(x,y,z);o.rotation.y=angle;scene.add(o);return o}
 const rockMat=new THREE.MeshStandardMaterial({map:shoreTexture,color:0xaaa18b,roughness:1,vertexColors:true});
 function boulder(x,y,z,size,n){const g=new THREE.IcosahedronGeometry(1,3),p=g.attributes.position,colors=[];for(let i=0;i<p.count;i++){const px=p.getX(i),py=p.getY(i),pz=p.getZ(i),d=1+noise(px*4+n,pz*4-n)*.23;p.setXYZ(i,px*d,py*d*.64,pz*d*.88);const shade=.65+Math.max(0,py)*.2+noise(px+n,pz)*.1;colors.push(shade,shade*.96,shade*.85)}g.setAttribute('color',new THREE.Float32BufferAttribute(colors,3));g.computeVertexNormals();const o=new THREE.Mesh(g,rockMat);o.scale.setScalar(size);o.position.set(x,y,z);o.rotation.y=n*.7;o.castShadow=true;o.receiveShadow=true;scene.add(o)}
 for(let i=0;i<31;i++){const side=i%2?-1:1,z=9-Math.floor(i/2)*3.8,size=.3+random(i+18)*.85;boulder(side*(edge(z)+random(i+30)*1.1),size*.15,z,size,i)}
 boulder(-3.4,.35,11.2,1.1,40);boulder(3.8,.23,10.3,.75,42);boulder(-6.1,.17,7.7,.58,46);
 const trees=[];for(const [x,z,h,r]of [[-8.4,4.7,4.9,1.0],[-13.2,-16,5.5,.2],[13.4,-19,6.3,2.3],[-21,-45,7.5,4.1]]){const tree=fitModel(forest['angler-pine'],h,'y');tree.position.set(x,h/2+.7,z);tree.rotation.y=r;tree.traverse(o=>{if(o.isMesh){o.castShadow=true;o.receiveShadow=true}});scene.add(tree);trees.push(tree)}
 const grassGeometry=new THREE.BufferGeometry(),grassPositions=[],grassColors=[];for(let i=0;i<1250;i++){const side=i%2?-1:1,z=10-random(i+200)*72,x=side*(edge(z)+.35+random(i+350)*2.6),base=.08+random(i+520)*.25,height=.16+random(i+700)*.32,w=.015+random(i+920)*.022;grassPositions.push(x-w,base,z,x+w,base,z,x+Math.sin(i)*.11,base+height,z+.08);for(let j=0;j<3;j++)grassColors.push(.24+random(i)*.11,.31+random(i+8)*.12,.15+random(i+9)*.10)}grassGeometry.setAttribute('position',new THREE.Float32BufferAttribute(grassPositions,3));grassGeometry.setAttribute('color',new THREE.Float32BufferAttribute(grassColors,3));grassGeometry.computeVertexNormals();scene.add(new THREE.Mesh(grassGeometry,new THREE.MeshStandardMaterial({vertexColors:true,side:THREE.DoubleSide,roughness:1})));
 const reedMat=new THREE.MeshStandardMaterial({color:0x8c8763,roughness:1});for(let i=0;i<64;i++){const side=i%2?-1:1,z=8-random(i+1500)*20,x=side*(edge(z)+random(i+1600)*.5),h=.55+random(i+1750)*.6;const stalk=new THREE.Mesh(new THREE.CylinderGeometry(.009,.012,h,4),reedMat);stalk.position.set(x,h/2,z);stalk.rotation.z=Math.sin(i)*.07;scene.add(stalk);if(i%3===0){const head=new THREE.Mesh(new THREE.CapsuleGeometry(.029,.13,2,5),new THREE.MeshStandardMaterial({color:0x756046,roughness:1}));head.position.set(x,h-.03,z);scene.add(head)}}
 const canoe=authored('canoe',3.4,3.0,.18,8.3,-.40,'z');canoe.traverse(o=>{if(o.isMesh)o.material.color.multiplyScalar(.55)});authored('canoe_paddle',2.1,3.0,.49,8.3,-.55,'z');for(let i=0;i<3;i++)authored('path_wood',2.4,-.8,.19,10.8-i*1.05,0,'x');
 const timber=new THREE.MeshStandardMaterial({color:0x665345,roughness:.85});for(const x of [-1.9,.3])for(const z of [8.25,10.8]){const pile=new THREE.Mesh(new THREE.CylinderGeometry(.11,.14,1.28,12),timber);pile.position.set(x,.16,z);pile.castShadow=true;scene.add(pile)}
 const lantern=new THREE.Group(),brass=new THREE.MeshStandardMaterial({color:0x806e4c,metalness:.65,roughness:.4});const lampGlass=new THREE.Mesh(new THREE.CylinderGeometry(.11,.13,.28,14),new THREE.MeshStandardMaterial({color:0xffd592,emissive:0xffba69,emissiveIntensity:1.3,transparent:true,opacity:.75,roughness:.2}));lampGlass.position.y=.27;lantern.add(lampGlass);for(const y of [.1,.44]){const cap=new THREE.Mesh(new THREE.CylinderGeometry(.15,.15,.05,14),brass);cap.position.y=y;lantern.add(cap)}const handle=new THREE.Mesh(new THREE.TorusGeometry(.14,.018,6,18,Math.PI),brass);handle.position.y=.50;lantern.add(handle);lantern.position.set(.10,.25,10.6);scene.add(lantern);const lampLight=new THREE.PointLight(0xffbf73,2,3);lampLight.position.set(.1,.7,10.6);scene.add(lampLight);
'''
s=s[:start]+scene+s[end:]
s=s.replace("camera.position.set(10.2,8.1,18.8);camera.lookAt(0,.0,-7.5)","camera.position.set(4.2,3.5,14.4);camera.lookAt(0,.1,-6.8)")
s=s.replace("return {x:-.55+Math.sin(s.angle)*.7,y:2.55-bend*.5,z:8.1-bend*.7}","return {x:-.85+Math.sin(s.angle)*.7,y:2.35-bend*.45,z:6.6-bend*.55}")
s=s.replace("waveUniforms.uTime.value=s.elapsed;canoe.rotation.z=", "waveUniforms.uTime.value=s.elapsed;const cameraPull=s.phase==='fight'?Math.sin(s.fightTime*1.1)*.045:0;camera.position.set(4.2+cameraPull,3.5,14.4);const cameraTarget=floatPoint();camera.lookAt(s.phase==='fight'?cameraTarget.x*.12:0,.1,-6.8+(s.phase==='fight'?clamp((10-s.distance)*.08,-.15,.6):0));camera.fov=s.phase==='fight'?47:48;camera.updateProjectionMatrix();camera.updateMatrixWorld(true);canoe.rotation.z=")
override=".angler-brand{background:transparent;border:0;padding:0;text-shadow:0 2px 6px #071923;max-width:220px}.angler-brand b{font-size:22px;margin:5px 0}.angler-brand small{font-size:9px}.angler-gauge{background:#09212b7a;border-color:#dde8de26;backdrop-filter:blur(5px);width:165px;padding:10px 13px}.angler-gauge strong{font-size:11px}.angler-gauge b{font-size:16px}.angler-cue{top:auto;bottom:19px;min-width:unset;max-width:76%;background:#0b273e75;border:0;border-radius:30px;padding:8px 17px}.angler-cue b{font-size:16px}.angler-cue span{display:none}.angler-bottom{display:none}.angler-marker{background:#102c3980;border:0;border-radius:20px;padding:4px 8px}.angler-end{top:auto;bottom:23px;transform:translateX(-50%);background:#0b2532c9;border:1px solid #e0d0a34d;backdrop-filter:blur(6px);padding:16px 21px}.angler-end b{font-size:23px}.angler-end span{font-size:12px}.angler-controls button{background:linear-gradient(#213540,#13272f);border-color:#817e653b;color:#e6e2cd;border-radius:7px}.angler-controls button[aria-pressed=true]{background:#779ea2;color:#08212e}@media(max-width:760px){.angler-brand{left:12px;top:11px;max-width:155px}.angler-brand b{font-size:18px}.angler-brand span{font-size:9px}.angler-gauge{width:128px;right:11px;top:10px;padding:7px 9px}.angler-gauge b{font-size:13px}.angler-cue{top:auto;bottom:12px;padding:6px 12px}.angler-cue b{font-size:12px}.angler-end{bottom:10px;padding:12px 16px}.angler-end b{font-size:17px}}"
s=s.replace("';host.append(style);",override+"';host.append(style);",1)
s=s.replace("'入岸 '+s.catches.length+' / 2 · '+ANGLER_FISH[s.fishIndex].name", "'入岸 '+s.catches.length+' / 2 · '+({aim:'选择落点',cast:'抛竿落水',wait:'等待咬钩',nibble:'轻微试探',strike:'现在扬竿',fight:'控线拉近',caught:'第一尾抵岸',lost:'重新整理',won:'暮湾任务完成'})[s.phase]")
target.write_text(s,encoding='utf-8');print('Replaced scene and HUD, preserving rules and saved state logic.')
