const fs=require('fs'),path=require('path'),assert=require('assert'),crypto=require('crypto');
const {chromium}=require('./browser.cjs');
const project=path.resolve(__dirname,'..'),origin='http://127.0.0.1:8962/';
(async()=>{const browser=await chromium.launch({headless:true,args:['--use-angle=swiftshader','--enable-unsafe-swiftshader','--ignore-gpu-blocklist']});try{
 const page=await browser.newPage({viewport:{width:1440,height:960}}),errors=[],checks=[],styles=[];
 page.on('pageerror',e=>errors.push(e.message));await page.route('https://dumpling-dell.pages.dev/**',r=>r.fulfill({status:200,contentType:'text/html',body:'Original runtime verified in validation.json; isolated style QA.'}));
 function check(name,value){assert(value,name);checks.push({name,passed:true})}
 await page.goto(origin+'?style=papercut#lab',{waitUntil:'domcontentloaded'});await page.waitForFunction(()=>window.styleLab?.styles.length===20);await page.locator('#lab').scrollIntoViewIfNeeded();
 check('20 个风格已接入',await page.locator('.style-tab').count()===20);check('新风格 URL 可直达',await page.evaluate(()=>styleLab.state.style==='papercut'));
 // Repaint an actual code-rendered canvas at a fixed time so pixel differences
 // measure material parameters rather than animated particles or elapsed time.
 async function fingerprint(){await page.evaluate(async()=>{styleLab.state.paused=true;styleLab.state.t=6;styleLab.state.popAge=2;styleLab.state.particles=[];const {render2D}=await import('./render2d.js');const c=document.querySelector('#canvas2d');render2D(c.getContext('2d'),c,styleLab.state.style,styleLab.state)});return crypto.createHash('sha256').update(await page.locator('#canvas2d').evaluate(c=>c.toDataURL())).digest('hex')}
 for(const id of await page.evaluate(()=>styleLab.extraStyles)){
  await page.evaluate(()=>styleLab.state.paused=false);await page.locator('#style-tab-'+id).click();await page.waitForTimeout(140);check(id+' 被选中',await page.locator('#style-tab-'+id).getAttribute('aria-selected')==='true');check(id+' 有可调材质参数',await page.locator('#style-effect-controls').isVisible());
  const closed=await fingerprint();await page.evaluate(()=>styleLab.state.paused=false);const count=await page.evaluate(()=>styleLab.state.collected);await page.locator('#open-bun').click();await page.waitForTimeout(1050);check(id+' 开盖增加真实收藏',await page.evaluate(n=>styleLab.state.opened&&styleLab.state.collected===n+1,count));const opened=await fingerprint();check(id+' 开盖改变画面',closed!==opened);
  await page.evaluate(()=>styleLab.state.paused=false);const b=await page.locator('#squish-bun').boundingBox();await page.mouse.move(b.x+b.width/2,b.y+b.height/2);await page.mouse.down();await page.waitForFunction(()=>styleLab.state.squash>.45);check(id+' 挤压驱动形变',await page.evaluate(()=>styleLab.state.held));await page.mouse.up();await page.waitForFunction(()=>Math.abs(styleLab.state.squash)<.08);check(id+' 松开后回弹',await page.evaluate(()=>!styleLab.state.held));
  await page.locator('#toggle-night').click();const night=await fingerprint();check(id+' 昼夜改变实际像素',night!==opened);await page.locator('#toggle-night').click();
  for(const value of ['0','100'])await page.locator('#effect-strength').fill(value);
  await page.locator('#effect-strength').fill('0');const low=await fingerprint();await page.locator('#effect-strength').fill('100');const high=await fingerprint();check(id+' 参数确实改变渲染',low!==high);check(id+' 参数输出与状态一致',await page.locator('#effect-value').textContent()==='100%'&&await page.evaluate(()=>styleLab.state.detail===1));
  await page.locator('#effect-strength').fill('65');await fingerprint();await page.locator('#stage').screenshot({path:path.join(project,'web/assets/style-'+id+'.png')});styles.push({id,low,high,openedHash:opened,nightHash:night});console.log('PASS',id);
 }
 await page.evaluate(()=>styleLab.state.paused=false);
 for(const [group,count] of [['new',10],['core',10],['craft',3],['print',5],['digital',2],['all',20]]){await page.locator('[data-style-filter='+group+']').click();check(group+' 分组数量正确',await page.locator('.style-tab:visible').count()===count);check(group+' 选中项可见',await page.locator('.style-tab[aria-selected=true]').isVisible())}
 await page.locator('[data-style-filter=digital]').click();await page.locator('#style-tab-ascii').focus();await page.keyboard.press('ArrowRight');check('分组内键盘切换',await page.evaluate(()=>styleLab.state.style==='wireframe'));await page.keyboard.press('ArrowRight');check('分组内循环切换',await page.evaluate(()=>styleLab.state.style==='ascii'));
 await page.locator('[data-style-filter=all]').click();await page.locator('#style-tab-clay').click();await page.locator('#open-bun').click();await page.waitForFunction(()=>styleLab.rendererType==='WebGL');check('原有三维场景回归可用',await page.evaluate(()=>!styleLab.webglError));await page.locator('#style-tab-pixel').click();check('原有像素玩法入口可用',await page.locator('#mechanism-controls').isVisible());check('原有风格隐藏扩展参数',!await page.locator('#style-effect-controls').isVisible());await page.locator('[data-action=care]').click();check('原有养成仍能操作',await page.evaluate(()=>styleLab.state.care>0));
 await page.setViewportSize({width:390,height:844});await page.locator('[data-style-filter=new]').click();check('390px 无横向溢出',await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));await page.locator('#style-tab-risograph').click();check('手机可访问最后一个风格',await page.evaluate(()=>styleLab.state.style==='risograph'));await page.locator('#effect-strength').fill('85');check('手机可调整参数',await page.evaluate(()=>styleLab.state.detail===.85));
 await page.setViewportSize({width:1440,height:960});await page.locator('[data-style-filter=new]').click();await page.locator('#style-tab-papercut').click();await page.locator('#open-bun').click();await page.waitForTimeout(1300);await fingerprint();await page.locator('#stage').screenshot({path:path.join(project,'assets/style-expansion-preview.png')});
 check('无 JavaScript 错误',errors.length===0);fs.writeFileSync(path.join(project,'notes/style-expansion-check.json'),JSON.stringify({date:'2026-10-02',qaNote:'Only QA isolates the remote original; new style canvases rendered at fixed time to verify pixel changes.',checks,styles,errors},null,2)+'\n');console.log('COMPLETE',checks.length,'checks');
 }finally{await browser.close()}
})().catch(e=>{console.error(e);process.exitCode=1});
