const fs=require('fs'),path=require('path'),assert=require('assert');const {chromium}=require('./browser.cjs');const project=path.resolve(__dirname,'..');
(async()=>{const browser=await chromium.launch({headless:true,args:['--use-angle=swiftshader','--enable-unsafe-swiftshader','--ignore-gpu-blocklist']});try{
 const page=await browser.newPage({viewport:{width:1440,height:960}}),errors=[],checks=[],shots=[];page.on('pageerror',e=>errors.push(e.message));await page.route('https://dumpling-dell.pages.dev/**',r=>r.fulfill({status:200,contentType:'text/html',body:'Original verified separately. Isolated player-experience QA.'}));function check(name,value){assert(value,name);checks.push({name,passed:true});console.log('PASS',name)}
 await page.goto('http://127.0.0.1:8962/?experience=cozy#play-lab',{waitUntil:'domcontentloaded'});await page.waitForFunction(()=>window.playLab?.worlds.length===3);await page.locator('#play-lab').scrollIntoViewIfNeeded();check('主研究是三个游戏体验',await page.locator('[data-play-world]').count()===3);check('旧材质实验默认折叠',!await page.locator('#visual-archive').evaluate(e=>e.open));check('没有开局自动给奖励',await page.evaluate(()=>!playLab.state.berry&&!playLab.state.friendFed&&!playLab.state.complete));
 async function point(x,y){await page.locator('#play-canvas').scrollIntoViewIfNeeded();const r=await page.locator('#play-canvas').boundingBox();await page.mouse.click(r.x+x/960*r.width,r.y+y/560*r.height)}
 async function arrived(){await page.waitForFunction(()=>!playLab.state.pending&&!playLab.state.route.length,null,{timeout:45000});await page.waitForTimeout(130)}
 async function capture(id){await page.locator('.play-stage').screenshot({path:path.join(project,'web/assets/play-'+id+'.png')});shots.push('web/assets/play-'+id+'.webp')}
 await page.locator('#play-static').click();await point(230,270);await page.waitForTimeout(300);check('只看画面对照不触发摘果',await page.evaluate(()=>playLab.state.paused&&!playLab.state.berry));await page.locator('#play-static').click();
 const before=await page.evaluate(()=>({...playLab.state.player}));await point(657,339);check('点击对象先实际行走',await page.evaluate(p=>playLab.state.route.length>0&&Math.hypot(playLab.state.player.x-p.x,playLab.state.player.y-p.y)<30,before));await arrived();check('缺少莓果时不会直接完成关系',await page.evaluate(()=>!playLab.state.friendFed));check('伙伴表达具体需要',(await page.locator('#play-dialogue').textContent()).includes('饿'));
 await point(230,270);await arrived();check('行走到莓果后实际采摘',await page.evaluate(()=>playLab.state.berry));await point(657,339);await arrived();check('送莓果后伙伴关系改变',await page.evaluate(()=>playLab.state.friendFed));check('玩家有两种关系选择',await page.locator('#play-choices').isVisible());await page.locator('#play-static').click();check('画面对照禁用关系选择',await page.locator('#play-choice-follow').isDisabled());await page.locator('#play-static').click();await page.locator('#play-choice-follow').click();check('一起走走形成随行结局',await page.evaluate(()=>playLab.state.choice==='follow'&&playLab.state.complete));await point(722,437);await arrived();check('照顾小花改变世界',await page.evaluate(()=>playLab.state.flowers>0));const friend=await page.evaluate(()=>playLab.hotspots.find(h=>h.id==='friend'));await point(friend.x,friend.y);await arrived();check('随行小团在当前位置回应',(await page.locator('#play-dialogue').textContent()).includes('蹭了蹭'));await capture('cozy');
 await page.locator('#play-reset').click();check('重新体验清空当前世界',await page.evaluate(()=>!playLab.state.complete&&!playLab.state.berry));await point(230,270);await arrived();await point(657,339);await arrived();await page.locator('#play-choice-rest').click();check('另一种选择保留休息结局',await page.evaluate(()=>playLab.state.choice==='rest'&&playLab.state.complete));await page.locator('#play-reset').click();const x=await page.evaluate(()=>playLab.state.player.x);await page.locator('#play-canvas').focus();await page.keyboard.down('ArrowRight');await page.waitForTimeout(500);await page.keyboard.up('ArrowRight');check('键盘可以行走',await page.evaluate(x=>playLab.state.player.x>x+15,x));
 await page.locator('[data-play-world=wonder]').click();await point(786,166);await arrived();check('没有灯石时门不会打开',await page.evaluate(()=>!playLab.state.complete&&playLab.state.runes.length===0));for(const [id,x,y] of [['rune-a',258,292],['rune-b',607,217],['rune-c',716,417]]){await point(x,y);await arrived();check(id+' 因探索而点亮',await page.evaluate(id=>playLab.state.runes.includes(id),id))}check('三盏灯解锁下一步目标',(await page.locator('#play-goal').textContent()).includes('门'));await point(786,166);await arrived();check('探索有真正的世界变化结局',await page.evaluate(()=>playLab.state.complete&&playLab.state.gateGlow>.8));await capture('wonder');
 await page.locator('[data-play-world=playful]').click();await page.waitForFunction(()=>playLab.renderer==='WebGL'&&!playLab.webglError);await page.waitForTimeout(600);for(const id of ['hide-0','hide-1','hide-2','gift']){await page.locator('.play-stage').scrollIntoViewIfNeeded();const p=await page.evaluate(id=>playLab.screenPoint(id),id);assert(p,id);await page.mouse.click(p.x,p.y);await arrived();if(id.startsWith('hide'))check(id+' 通过真实三维拾取找到朋友',await page.evaluate(id=>playLab.state.found.includes(id),id))}check('找齐后获得帽子结局',await page.evaluate(()=>playLab.state.found.length===3&&playLab.state.reward&&playLab.state.complete));await page.waitForFunction(()=>playLab.hatVisible);check('奖励帽子确实显示在人物上',await page.evaluate(()=>playLab.hatVisible));await capture('playful');
 await page.locator('[data-play-world=cozy]').click();check('世界之间切换保留各自进度',await page.evaluate(()=>playLab.state.id==='cozy'&&playLab.state.player.x>448));await page.locator('[data-play-world=cozy]').focus();await page.keyboard.press('ArrowRight');check('游戏体验标签支持键盘',await page.evaluate(()=>playLab.state.id==='wonder'));
 await page.setViewportSize({width:390,height:844});await page.locator('#play-lab').scrollIntoViewIfNeeded();check('手机没有横向溢出',await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));check('手机有方向控制',await page.locator('.play-touch').isVisible());await page.locator('[data-play-world=cozy]').click();await page.locator('#play-reset').click();await page.locator('[data-play-move=ArrowRight]').scrollIntoViewIfNeeded();const initial=await page.evaluate(()=>playLab.state.player.x),btn=await page.locator('[data-play-move=ArrowRight]').boundingBox();await page.mouse.move(btn.x+btn.width/2,btn.y+btn.height/2);await page.mouse.down();await page.waitForTimeout(450);await page.mouse.up();check('手机方向按钮驱动人物行走',await page.evaluate(x=>playLab.state.player.x>x+12,initial));await page.screenshot({path:path.join(project,'assets/play-mobile.png')});
 await page.goto('http://127.0.0.1:8962/?experience=wonder#play-lab',{waitUntil:'domcontentloaded'});await page.waitForFunction(()=>playLab.state.id==='wonder');check('直达链接恢复游戏方向',await page.evaluate(()=>playLab.state.id==='wonder'));check('无 JavaScript 运行错误',errors.length===0);fs.writeFileSync(path.join(project,'notes/play-experience-check.json'),JSON.stringify({date:'2026-10-02',qaNote:'Remote original isolated only during QA. Tests use real pointer/keyboard movement, world state and WebGL picking. Technical checks do not establish emotional value or willingness to play.',checks,screenshots:shots,errors},null,2)+'\n');console.log('COMPLETE',checks.length,'playability checks');
 }finally{await browser.close()}
})().catch(e=>{console.error(e);process.exitCode=1});
