import {withWorldProgress} from './world-progress.js?v=2';
import {createWorldsInterface,renderWorldActions} from './worlds-interface.js?v=6';
import {createDetectiveGame} from './games/detective.js?v=6';
import {createWuxiaGame} from './games/wuxia.js?v=6';
import {createEcologyGame} from './games/ecology.js?v=5';
import {createWastelandGame} from './games/wasteland.js?v=5';
import {createDreamGame} from './games/dream.js?v=6';
import {createArcadeGame} from './games/arcade.js?v=6';
import {gameCatalog,gameIds,gameInfo,gameTab} from './game-catalog.js?v=5';
import {createInnGame} from './games/inn.js?v=5';
import {createIslandsGame} from './games/islands.js?v=6';
import {createMoversGame} from './games/movers.js?v=9';
const $=s=>document.querySelector(s),factories={inn:createInnGame,islands:createIslandsGame,movers:createMoversGame,detective:createDetectiveGame,wuxia:createWuxiaGame,ecology:createEcologyGame,wasteland:createWastelandGame,dream:createDreamGame,arcade:createArcadeGame},cache=new Map(),keys=new Set(),pressed=new Set(),input={x:0,y:0,keys,pressed};
const storagePrefix=new URLSearchParams(location.search).has('qa')?'dumpling-painted-preserved-qa-v1-':'dumpling-painted-preserved-v1-',intro=Object.fromEntries(gameCatalog.map(g=>[g.id,[g.title,g.opening,g.journal]]));
let current=null,id='inn',paused=false,sound=false,audio=null,uiKey='',actionKey='',storageOK=true,lastSave=0,lastUI=0,last=performance.now(),musicBeat=0,musicClock=0,error=null,hostVisible=true;
if(new URLSearchParams(location.search).get('embedded')==='1')document.body.classList.add('embedded');
function load(which){try{const raw=localStorage.getItem(storagePrefix+which)||localStorage.getItem((new URLSearchParams(location.search).has('qa')?'dumpling-product-qa-v3-':'dumpling-extension-v1-')+which);if(!raw)return null;const o=JSON.parse(raw);return o&&o.version===1&&typeof o.state==='object'?o.state:null}catch{return null}}
function saveAll(){let allSaved=true;for(const [which,entry] of cache)try{const s=JSON.stringify({version:1,state:entry.game.getState()});if(s!==entry.saved){localStorage.setItem(storagePrefix+which,s);entry.saved=s}}catch{allSaved=false}storageOK=allSaved;$('#save-status').textContent=storageOK?'进度已保存在此浏览器 · 刷新可继续':'本次可继续游玩 · 浏览器未能保存进度'}
function tone(frequency,start,duration,gain=.035,type='sine'){if(!sound||!audio)return;const o=audio.createOscillator(),g=audio.createGain();o.type=type;o.frequency.setValueAtTime(frequency,start);g.gain.setValueAtTime(.0001,start);g.gain.exponentialRampToValueAtTime(gain,start+.035);g.gain.exponentialRampToValueAtTime(.0001,start+duration);o.connect(g);g.connect(audio.destination);o.start(start);o.stop(start+duration+.03)}
function sfx(kind){if(!sound||!audio)return;const t=audio.currentTime;if(kind==='bump'){tone(110,t,.12,.03,'triangle');tone(78,t+.07,.2,.025,'triangle')}else if(kind==='success'){[523,659,784,1046].forEach((f,i)=>tone(f,t+i*.095,.5,id==='movers'?.06:.045,id==='movers'?'triangle':'sine'))}else{tone(id==='islands'?659:id==='movers'?392:440,t,.22,.03,id==='movers'?'triangle':'sine')}}
const musicProfiles={
 inn:{notes:[60,64,67,69,67,64,62,64,60,55,60,64,67,64,62,60],beat:.55},
 islands:{notes:[57,64,69,71,76,71,69,64,60,67,72,76,79,76,72,67],beat:.55},
 movers:{notes:[60,64,67,64,62,65,69,65,57,60,64,60,55,59,62,59],beat:.78,wave:'sine'},
 detective:{notes:[48,55,58,62,60,58,55,51,48,55,58,63,62,58,55,48],beat:.8},
 wuxia:{notes:[57,60,62,64,67,64,62,60,57,52,57,60,62,64,60,57],beat:.66},
 ecology:{notes:[60,67,72,76,74,72,67,64,62,69,74,77,76,74,69,65],beat:.9},
 wasteland:{notes:[40,47,52,55,54,52,47,43,40,47,51,54,52,51,47,40],beat:1.15,wave:'triangle'},
 dream:{notes:[57,64,68,71,76,71,68,64,60,67,71,74,79,74,71,67],beat:.72},
 arcade:{notes:[45,57,60,64,45,57,62,64,48,60,64,67,50,62,65,69],beat:.22,wave:'triangle'}
};
function music(){if(!audio||!sound)return;const profile=musicProfiles[id],t=audio.currentTime,m=profile.notes[musicBeat%profile.notes.length],f=440*2**((m-69)/12);tone(f,t,profile.beat*1.4,.023,profile.wave||'sine');if(musicBeat%4===0){tone(f/2,t,profile.beat*3,.019,'sine');tone(f*1.5,t+.04,profile.beat*2,.01,'sine')}musicBeat++} 
function list(node,items,empty,limit=Infinity){node.replaceChildren(...(items?.length?items:[empty]).slice(-limit).map(t=>{const li=document.createElement('li');li.textContent=t;return li}))}
function sync(){if(!current)return;const u=withWorldProgress(id,current.getState(),current.getUI()),serialized=JSON.stringify(u);if(serialized!==uiKey){uiKey=serialized;$('#game-title').textContent=u.title||intro[id][0];$('#game-chapter').textContent=u.progress||'第一版';$('#game-goal').textContent=u.goal||intro[id][1];const message=u.message||intro[id][1];if($('#game-message').textContent!==message)$('#game-message').textContent=message;$('#game-controls').textContent=u.controls||'点击场景互动 · 方向键 / WASD 移动';$('#journal-title').textContent=intro[id][2];list($('#game-inventory'),u.inventory,'还没有收进随身口袋的东西');list($('#game-journal'),u.journal,'调查、经历与结果会记在这里。',7)}
 const actions=JSON.stringify(u.actions||[]);if(actions!==actionKey){actionKey=actions;renderWorldActions($('#game-actions'),u.actions||[],runCommand,id)}worldUI.sync(u)}
function runCommand(command){if(paused||worldUI.blocking||!current)return;current.command(command);sync();saveAll();if(!worldUI.blocking)current.element.focus({preventScroll:true})}
function choose(which){if(!factories[which])which='detective';worldUI.close();saveAll();id=which;keys.clear();pressed.clear();paused=false;musicBeat=musicClock=0;uiKey=actionKey='';error=null;$('#game-pause').textContent='暂停';$('#game-pause').setAttribute('aria-pressed','false');$('#pause-screen').hidden=true;document.body.dataset.game=id;document.title=id==='movers'?'搬家日 · Moving Day':'小世界的新故事 · 九种可玩方向';const actionHome=$('.save-box>div'),productHome=$('#moving-top-controls');(!document.body.classList.contains('embedded')?productHome:actionHome).append($('#game-sound'),$('#game-reset'));const meta=gameInfo[id];$('.touch-controls').hidden=!meta.move&&!meta.touch.length;$('.dpad').hidden=!meta.move;document.querySelectorAll('.touch-action-keys [data-game-key]').forEach(b=>{b.hidden=!meta.touch.includes(b.dataset.gameKey);if(b.dataset.gameKey==='KeyE')b.textContent=id==='arcade'?'投递':id==='movers'?'拿起 / 轻放':'互动';if(b.dataset.gameKey==='KeyF')b.textContent=id==='arcade'?'冲刺':id==='dream'?'放回岸上':'投掷'});document.querySelectorAll('[data-game-tab]').forEach(b=>{const selected=b.dataset.gameTab===id;b.setAttribute('aria-selected',String(selected));b.tabIndex=selected?0:-1});$('#game-view').setAttribute('aria-labelledby','tab-'+id);
 if(document.fullscreenElement===$('#game-view')||document.body.classList.contains('embedded'))$('.view-tools').append($('#game-sound'),$('#game-reset'));
 const tabStrip=$('.game-tabs'),selectedTab=$('#tab-'+id);if(tabStrip.scrollWidth>tabStrip.clientWidth)tabStrip.scrollLeft=Math.max(0,selectedTab.offsetLeft-tabStrip.offsetLeft-(tabStrip.clientWidth-selectedTab.offsetWidth)/2);
 for(const [which,e] of cache)e.mount.hidden=which!==id;
 try{if(!cache.has(id)){const mount=document.createElement('div');mount.dataset.world=id;$('#game-mount').append(mount);const game=factories[id]({mount,saved:load(id),onEvent:sfx});game.element.tabIndex=0;game.element.addEventListener('pointerup',()=>game.element.focus({preventScroll:true}));cache.set(id,{game,mount,saved:''})}current=cache.get(id).game;cache.get(id).mount.hidden=false;$('#game-loading').hidden=true;$('#game-loading').classList.remove('error');sync();current.draw()}catch(e){error=e.message;current=null;$('#game-loading').hidden=false;$('#game-loading').classList.add('error');$('#game-loading').textContent='这个世界暂时未能打开：'+e.message+'。可先切换到其他方向。';console.error(e)}
 const u=new URL(location.href);u.searchParams.set('game',id);history.replaceState(null,'',u.pathname+u.search+u.hash);if(document.body.classList.contains('embedded'))parent.postMessage({type:'dumpling-extension-selected',game:id},location.origin)}
$('.game-tabs').replaceChildren(...gameCatalog.map(gameTab));
document.querySelectorAll('[data-game-tab]').forEach((b,i)=>{b.addEventListener('click',()=>choose(b.dataset.gameTab));b.addEventListener('keydown',e=>{if(!['ArrowLeft','ArrowRight','Home','End'].includes(e.key))return;e.preventDefault();const next=e.key==='Home'?0:e.key==='End'?gameIds.length-1:(i+(e.key==='ArrowRight'?1:gameIds.length-1))%gameIds.length,nextId=gameIds[next];choose(nextId);$('#tab-'+nextId).focus()})});
const accepted=['ArrowUp','ArrowDown','ArrowLeft','ArrowRight','KeyW','KeyA','KeyS','KeyD','KeyE','KeyF','Space'];$('#game-view').addEventListener('keydown',e=>{if(worldUI.blocking||e.target.closest('button')||!accepted.includes(e.code))return;e.preventDefault();keys.add(e.code);if(!e.repeat)pressed.add(e.code)});window.addEventListener('keyup',e=>keys.delete(e.code));window.addEventListener('blur',()=>{keys.clear();pressed.clear()});$('#game-view').addEventListener('focusout',e=>{if(!e.relatedTarget||!$('#game-view').contains(e.relatedTarget)){keys.clear();pressed.clear()}});
document.querySelectorAll('[data-game-key]').forEach(b=>{b.addEventListener('pointerdown',e=>{e.preventDefault();if(paused||worldUI.blocking)return;keys.add(b.dataset.gameKey);pressed.add(b.dataset.gameKey);b.setPointerCapture(e.pointerId)});for(const event of ['pointerup','pointercancel','lostpointercapture'])b.addEventListener(event,()=>keys.delete(b.dataset.gameKey))});
$('#game-pause').addEventListener('click',()=>{paused=!paused;keys.clear();pressed.clear();$('#game-pause').textContent=paused?'继续':'暂停';$('#game-pause').setAttribute('aria-pressed',String(paused));$('#pause-screen').hidden=!paused;saveAll()});$('#game-full').addEventListener('click',()=>{const action=document.fullscreenElement=== $('#game-view')?document.exitFullscreen?.():$('#game-view').requestFullscreen?.();action?.catch(()=>{})});
function resetCurrent(){const entry=cache.get(id);if(entry){entry.game.dispose();entry.mount.remove();cache.delete(id)}try{localStorage.removeItem(storagePrefix+id)}catch{}current=null;choose(id)}
$('#game-reset').addEventListener('click',()=>worldUI.confirmReset());
document.addEventListener('fullscreenchange',()=>{const full=document.fullscreenElement=== $('#game-view');$('#game-full').textContent=full?'退出大画面':'大画面';$('#game-full').title=full?'回到普通游戏画面':'放大游戏画面';keys.clear();pressed.clear();if(!document.body.classList.contains('embedded'))(full?$('.view-tools'):$('#moving-top-controls')).append($('#game-sound'),$('#game-reset'))});
$('#game-sound').addEventListener('click',()=>{sound=!sound;$('#game-sound').textContent=sound?'声音：开':'声音：关';$('#game-sound').setAttribute('aria-pressed',String(sound));if(sound)try{audio??=new(window.AudioContext||window.webkitAudioContext)();audio.resume();musicClock=0;sfx('soft')}catch{sound=false;$('#game-sound').textContent='声音暂不可用'}else audio?.suspend()});window.addEventListener('pagehide',saveAll);document.addEventListener('visibilitychange',()=>{keys.clear();pressed.clear();if(document.hidden){saveAll();audio?.suspend()}else if(sound)audio?.resume()});
if(document.body.classList.contains('embedded')){new ResizeObserver(()=>parent.postMessage({type:'dumpling-extension-resize',height:Math.ceil($('.game-shell').getBoundingClientRect().height+32)},location.origin)).observe($('.game-shell'));window.addEventListener('message',e=>{if(e.source===parent&&e.origin===location.origin&&e.data?.type==='dumpling-extension-visibility'){hostVisible=!!e.data.visible;if(!hostVisible){keys.clear();pressed.clear();saveAll()}}})}
function frame(now){const dt=Math.min(.2,(now-last)/1000);last=now;const rect=$('#game-view').getBoundingClientRect(),visible=hostVisible&&rect.bottom>0&&rect.top<innerHeight;if(current&&visible&&!document.hidden){input.x=(keys.has('ArrowRight')||keys.has('KeyD')?1:0)-(keys.has('ArrowLeft')||keys.has('KeyA')?1:0);input.y=(keys.has('ArrowDown')||keys.has('KeyS')?1:0)-(keys.has('ArrowUp')||keys.has('KeyW')?1:0);if(!paused&&!worldUI.blocking){const steps=Math.max(1,Math.ceil(dt*60)),heldInput={...input,pressed:new Set()};for(let step=0;step<steps;step++)current.tick(dt/steps,step===0?input:heldInput);musicClock+=dt;if(sound&&musicClock>musicProfiles[id].beat){musicClock=0;music()}}current.draw();if(now-lastUI>130){lastUI=now;sync()}if(now-lastSave>1100){lastSave=now;saveAll()}}pressed.clear();requestAnimationFrame(frame)}
const worldUI=createWorldsInterface({getId:()=>id,getGame:()=>current,onCommand:runCommand,onReset:resetCurrent});
choose(new URLSearchParams(location.search).get('game')||'detective');requestAnimationFrame(frame);
if(location.hash==='#game-view')requestAnimationFrame(()=>requestAnimationFrame(()=>$('#game-view').scrollIntoView({block:'start',behavior:'instant'})));
window.extensionLab={version:2,games:gameIds.slice(),select:choose,get current(){return id},get state(){return current?.getState()},get targets(){return current?.getTargets?.()||[]},get ui(){return current?.getUI()},get error(){return error},get paused(){return paused},get saved(){try{return JSON.parse(localStorage.getItem(storagePrefix+id))}catch{return null}}};
