import {PLAY_WORLDS,createWorld,hotspots,routeTo,goal,progress,interact,updateWorld,emit} from './play-worlds.js';
import {renderPlay2D} from './play-render2d.js';import {ToyPlayWorld} from './play-render3d.js';
const $=s=>document.querySelector(s),canvas=$('#play-canvas'),mount=$('#play-3d'),keys=new Set(),input={x:0,y:0};let toy=null,state=createWorld('cozy'),sound=false,audio=null,lastNote=0,webglError=null;const worlds=new Map(),reduced=matchMedia('(prefers-reduced-motion: reduce)').matches;
function say(t){state.message=t;$('#play-dialogue').textContent=t}
function note(kind='soft'){if(!sound)return;try{audio??=new (window.AudioContext||window.webkitAudioContext)();audio.resume();const notes=state.id==='wonder'?[261,392,523]:state.id==='playful'?[523,659,784]:[261,329,392],now=audio.currentTime;for(let i=0;i<(kind==='reward'?3:1);i++){const o=audio.createOscillator(),g=audio.createGain();o.type=state.id==='playful'?'triangle':'sine';o.frequency.value=notes[(Math.floor(state.time/2)+i)%3];g.gain.setValueAtTime(.0001,now+i*.11);g.gain.exponentialRampToValueAtTime(kind==='reward'?.085:.035,now+i*.11+.035);g.gain.exponentialRampToValueAtTime(.0001,now+i*.11+.65);o.connect(g);g.connect(audio.destination);o.start(now+i*.11);o.stop(now+i*.11+.7)}}catch{sound=false;$('#play-sound').textContent='声音暂不可用'}}
function sync(){const def=PLAY_WORLDS.find(w=>w.id===state.id);$('#play-goal').textContent=goal(state);$('#play-progress').textContent=progress(state);$('#play-choices').hidden=!(state.id==='cozy'&&state.friendFed&&!state.choice);$('#play-appearance').textContent=def.art;$('#play-title').textContent=def.title;$('#play-emotion').textContent=def.emotion;$('#play-view').setAttribute('aria-labelledby','play-tab-'+def.id);for(const c of ['follow','rest'])$('#play-choice-'+c).disabled=state.paused}
function choose(id){const def=PLAY_WORLDS.find(w=>w.id===id)||PLAY_WORLDS[0];if(state)worlds.set(state.id,state);state=worlds.get(def.id)||createWorld(def.id);keys.clear();input.x=input.y=0;state.route=[];state.pending=null;state.paused=false;lastNote=state.time;$('#play-static').setAttribute('aria-pressed','false');$('#play-static').textContent='对照：只看画面';document.querySelectorAll('[data-play-world]').forEach(b=>{const on=b.dataset.playWorld===def.id;b.setAttribute('aria-selected',String(on));b.tabIndex=on?0:-1});$('#play-invitation').textContent=def.invitation;$('#play-reason').textContent=def.reason;$('#play-loop').textContent=def.loop;$('#play-observe').replaceChildren(...def.observe.map(t=>{const li=document.createElement('li');li.textContent=t;return li}));$('#play-boundary').textContent=def.boundary;canvas.hidden=def.id==='playful';mount.hidden=def.id!=='playful';if(def.id==='playful')try{toy??=new ToyPlayWorld(mount,go);webglError=null}catch(e){webglError=e.message;say('三维暂未能启动，请先体验另外两个世界。')}if(!webglError||def.id!=='playful')say(state.message||def.invitation+' 点击场景，走近看看。');sync();const u=new URL(location.href);u.searchParams.set('experience',def.id);u.searchParams.delete('style');u.searchParams.delete('group');history.replaceState(null,'',u.pathname+u.search+u.hash)}
function go(x,y,id=null){if(state.paused){say('现在正在看画面。切回游玩，再看看世界如何回应你。');return}const near=hotspots(state).filter(h=>h.active).sort((a,b)=>Math.hypot(x-a.x,y-a.y)-Math.hypot(x-b.x,y-b.y))[0];if(!id&&near&&Math.hypot(x-near.x,y-near.y)<46)id=near.id;const h=id&&hotspots(state).find(h=>h.id===id);state.pending=id;state.route=routeTo(state,h?.x??x,h?.y??y);if(id)say('走近'+h.name+'……');else say('在这里走走，看看有什么回应。');if(!state.route.length&&id)act(id)}
function act(id){if(state.paused)return;const result=interact(state,id);say(result.text);if(result.changed)note(result.text.includes('小帽子')||state.complete?'reward':'soft');sync()}
function nearest(){const h=hotspots(state).filter(h=>h.active).sort((a,b)=>Math.hypot(state.player.x-a.x,state.player.y-a.y)-Math.hypot(state.player.x-b.x,state.player.y-b.y))[0];if(h)act(h.id)}
$('#play-world-tabs').replaceChildren(...PLAY_WORLDS.map((w,i)=>{const b=document.createElement('button');b.type='button';b.dataset.playWorld=w.id;b.setAttribute('role','tab');b.setAttribute('aria-controls','play-view');b.id='play-tab-'+w.id;const n=document.createElement('b'),e=document.createElement('span');n.textContent=w.name;e.textContent=w.emotion;b.append(n,e);b.addEventListener('click',()=>choose(w.id));b.addEventListener('keydown',ev=>{if(!['ArrowRight','ArrowLeft','Home','End'].includes(ev.key))return;ev.preventDefault();const j=ev.key==='Home'?0:ev.key==='End'?2:(i+(ev.key==='ArrowRight'?1:2))%3;choose(PLAY_WORLDS[j].id);$('#play-tab-'+PLAY_WORLDS[j].id).focus()});return b}));
canvas.addEventListener('pointerup',e=>{const r=canvas.getBoundingClientRect();go((e.clientX-r.left)/r.width*960,(e.clientY-r.top)/r.height*560)});canvas.addEventListener('pointermove',e=>{const r=canvas.getBoundingClientRect(),x=(e.clientX-r.left)/r.width*960,y=(e.clientY-r.top)/r.height*560;canvas.style.cursor=hotspots(state).some(h=>h.active&&Math.hypot(x-h.x,y-h.y)<45)?'pointer':'crosshair'});
document.querySelectorAll('[data-play-evidence]').forEach(b=>b.addEventListener('click',()=>{choose(b.dataset.playEvidence);$('#play-lab').scrollIntoView({behavior:reduced?'instant':'smooth'});$('#play-tab-'+state.id).focus({preventScroll:true})}));
$('#play-view').addEventListener('keydown',e=>{if(e.target.closest('button')||e.target.matches('input'))return;if(['ArrowUp','ArrowDown','ArrowLeft','ArrowRight','KeyW','KeyA','KeyS','KeyD','KeyE'].includes(e.code)){e.preventDefault();keys.add(e.code);if(e.code==='KeyE')nearest()}});$('#play-view').addEventListener('keyup',e=>keys.delete(e.code));$('#play-view').addEventListener('focusout',()=>keys.clear());window.addEventListener('blur',()=>keys.clear());
document.querySelectorAll('[data-play-move]').forEach(b=>{b.addEventListener('pointerdown',e=>{e.preventDefault();keys.add(b.dataset.playMove);b.setPointerCapture(e.pointerId)});for(const ev of ['pointerup','pointercancel','lostpointercapture'])b.addEventListener(ev,()=>keys.delete(b.dataset.playMove))});$('#play-near').addEventListener('click',nearest);
for(const choice of ['follow','rest'])$('#play-choice-'+choice).addEventListener('click',()=>{if(state.paused)return;state.choice=choice;state.complete=true;emit(state,'heart',state.player.x,state.player.y,8);say(choice==='follow'?'小团跟在身后。你走到哪儿，它就想陪到哪儿。':'小团在树下安心睡了：“下次来，也记得看看我呀。”');sync();note('reward')});
$('#play-reset').addEventListener('click',()=>{worlds.delete(state.id);const id=state.id;state=null;choose(id)});$('#play-sound').addEventListener('click',()=>{sound=!sound;$('#play-sound').textContent=sound?'声音：开':'声音：关';$('#play-sound').setAttribute('aria-pressed',String(sound));if(sound)note()});$('#play-static').addEventListener('click',()=>{state.paused=!state.paused;state.route=[];state.pending=null;$('#play-static').setAttribute('aria-pressed',String(state.paused));$('#play-static').textContent=state.paused?'回到游玩':'对照：只看画面';say(state.paused?'现在只剩画面。切回游玩，比较角色关系、发现和回应带来的变化。':'又能走进这个世界了。点击想去的地方。');sync()});$('#play-full').addEventListener('click',()=>$('#play-view').requestFullscreen?.().catch(()=>say('可以继续在当前画面体验。')));
let last=performance.now();function frame(now){const dt=Math.min(.1,(now-last)/1000);last=now;const r=$('#play-lab').getBoundingClientRect(),visible=r.bottom>0&&r.top<innerHeight;if(visible&&!document.hidden){input.x=(keys.has('ArrowRight')||keys.has('KeyD')?1:0)-(keys.has('ArrowLeft')||keys.has('KeyA')?1:0);input.y=(keys.has('ArrowDown')||keys.has('KeyS')?1:0)-(keys.has('ArrowUp')||keys.has('KeyW')?1:0);updateWorld(state,dt,input);if(!state.route.length&&state.pending){const id=state.pending;state.pending=null;act(id)}if(sound&&!state.paused&&state.time-lastNote>2.6){lastNote=state.time;note()}if(state.id==='playful'){if(!webglError)toy?.render(state)}else renderPlay2D(canvas,state)}requestAnimationFrame(frame)}
if(['#lab','#play-lab'].includes(location.hash))document.querySelector('#play-archive').open=true;if(location.hash==='#lab'){const u=new URL(location.href);u.hash='play-lab';history.replaceState(null,'',u);requestAnimationFrame(()=>$('#play-lab').scrollIntoView({behavior:'instant'}))}choose(new URLSearchParams(location.search).get('experience')||'cozy');requestAnimationFrame(frame);
window.playLab={worlds:PLAY_WORLDS.map(w=>w.id),select:choose,go,interact:act,get state(){return state},get hotspots(){return hotspots(state)},get webglError(){return webglError},get renderer(){return state.id==='playful'?'WebGL':'Canvas2D'},screenPoint:id=>toy?.screenPoint(id),get hatVisible(){return !!toy?.hat.visible}};
