export const STYLES = [
 {id:'pixel',name:'治愈像素',en:'COZY PIXEL ART',engine:'CANVAS 2D',color:'#e6a5ba',definition:'把画面画在小尺寸像素网格上，再放大。粉彩与可爱造型形成柔和的复古游戏体验。',features:['阶梯状轮廓与方块阴影','像素地图、角色与伙伴跟随','开盖弹跳、爱心和收藏反馈'],interaction:'点击蒸笼开盖，按住伙伴挤压；点击地图行走。下方还可以种植、喂食、装修、绘画与钓鱼。',use:'收藏养成、轻度探索、品牌吉祥物、可探索作品集。',method:'原创 Canvas 小场景，240 × 140 像素放大；共用状态驱动反馈。示例不替代原作完整系统。'},
 {id:'flat',name:'扁平插画',en:'FLAT ILLUSTRATION',engine:'CANVAS 2D',color:'#edab4c',definition:'用清晰的色块、几何形状与简化轮廓建立视觉秩序，弱化纹理和真实光照。',features:['平滑曲线与大面积色块','少量层次、明确的轮廓线','图形化云朵、植物与建筑'],interaction:'打开蒸笼，观察几何角色弹出；按住挤压，平滑轮廓随之变形。',use:'品牌互动、儿童内容、产品功能讲解和清晰的知识地图。',method:'直接绘制矢量式路径和规则几何；与像素场景使用不同的造型和构图。'},
 {id:'storybook',name:'手绘绘本',en:'HAND-DRAWN STORYBOOK',engine:'CANVAS 2D',color:'#b99372',definition:'通过纸张颗粒、不完全重合的线条与透明色层，营造亲手绘制的故事插图感觉。',features:['纸纹、铅笔线与轻微不规则轮廓','透明色层叠加的柔和笔触','留白和画页式构图'],interaction:'开盖像翻开故事中的小惊喜；切换夜晚，画页成为蓝调夜景。',use:'儿童故事、情感叙事、教育和文化体验。',method:'程序化纸纹、重复错位路径和透明笔触；属于实时绘本风格实验，未使用扫描画作。'},
 {id:'ink',name:'水墨国风',en:'INK & WASH',engine:'CANVAS 2D',color:'#5c6259',definition:'以墨色浓淡、干湿笔触、山水层次和大片留白组织画面，朱红成为少量强调色。',features:['远山淡墨、近景浓墨的层次','飞白、竹枝、墨点与烟气','朱红印章与亭台剪影'],interaction:'开盖释放墨点与淡烟；按住角色体验柔软反馈，昼夜改变墨色背景。',use:'诗词学习、非遗、古镇探索、东方文化展览。',method:'Canvas 透明墨层、粗细变化笔画与程序化纹理；笔墨表现为近似算法。'},
 {id:'anime',name:'日系动漫',en:'ANIME / CEL SHADING',engine:'CANVAS 2D',color:'#bf93d2',definition:'以人物、表情和对白为核心，用清楚的轮廓线与分区阴影强化角色性格。',features:['大眼睛、头发高光与人物立绘','明确分区的赛璐璐阴影','前景人物与故事式对白'],interaction:'打开蒸笼后，向导会回应新伙伴；按住角色，表情与形变一起变化。',use:'互动剧情、角色养成、IP 展示和人物引导式学习。',method:'原创路径立绘、分区明暗、眨眼和预置对白；不依赖 AI 对话。'},
 {id:'isometric',name:'等距微缩',en:'ISOMETRIC DIORAMA',engine:'CANVAS 2D',color:'#89a796',definition:'用固定斜向投影看到物体的多个面，把场景呈现为可俯看的微缩模型。等距描述的是视角。',features:['菱形地面与建筑三个可见面','前后深度与固定投影关系','微缩房屋、树木和铺装'],interaction:'开盖后伙伴出现在微缩街区；切换夜晚观察窗户和街灯。',use:'空间导览、经营、虚拟展馆和作品房间。',method:'二维等距坐标投影与绘制排序。它可再结合像素、插画或三维美术。'},
 {id:'lowpoly',name:'低多边形 3D',en:'LOW-POLY WORLD',engine:'WEBGL / 3D',color:'#8eb667',definition:'保留模型的多边形面，用简化几何和明暗分面表现立体世界，造型像折纸或积木。',features:['可见三角面与棱角','真实三维遮挡、阴影和透视','锥形树、块状房屋与多面角色'],interaction:'拖动旋转场景，开盖弹出角色；按住挤压。切换昼夜观察投影变化。',use:'三维小镇、空间探索、地图和轻量品牌世界。',method:'Three.js r160、平面着色低分段模型、阴影与透视镜头；无需外部模型。'},
 {id:'clay',name:'黏土玩具 3D',en:'CLAY / TOY WORLD',engine:'WEBGL / 3D',color:'#e6a48e',definition:'圆润体积、柔和材质和厚实造型让场景像手捏的黏土或摆在桌上的收藏玩具。',features:['平滑圆角与柔和高光','球形树冠和玩具尺寸的场景','立体软糯角色与整体形变'],interaction:'拖动查看玩具小岛，打开蒸笼，按住角色感受挤压回弹。',use:'吉祥物、玩具收藏、情绪陪伴和品牌活动。',method:'平滑模型、较高粗糙度材质、柔和灯光和形变动画；未模拟真实黏土流变。'},
 {id:'neon',name:'科技霓虹',en:'NEON / CYBER CITY',engine:'CANVAS 2D',color:'#6dcad5',definition:'用深色空间、发光线条、电子网格和高对比强调色构建未来都市氛围。',features:['霓虹轮廓、光晕与扫描线','透视网格、城市与雨线','开盖触发电子粒子脉冲'],interaction:'激活中央能量舱，释放新伙伴；切换夜晚查看发光层次。',use:'科技产品、科幻探索、互动数据和未来主题展览。',method:'Canvas 加色混合、光晕、多层线条和动态粒子；不是三维城市或光线追踪。'},
 {id:'realistic',name:'写实材质 3D',en:'REALISTIC MATERIAL STUDY',engine:'WEBGL / 3D',color:'#a78b67',definition:'用真实尺寸感、材料纹理、灯光和投影，让物体更接近现实中的桌面静物。',features:['木纹、竹编、陶瓷与石台','蒸笼立体结构与真实投影','柔和侧光、材质高光与蒸气'],interaction:'拖动检查材质和蒸笼结构；开盖、挤压和切换夜灯观察体积变化。',use:'产品展示、餐饮品牌、材料说明与三维展品。',method:'程序化 PBR 材质和三维光照实验；写实取向的合成场景，未达到照片或扫描级复现。'}
];

export const EXTRA_STYLES = [
 {id:'papercut',group:'craft',name:'层叠剪纸',en:'LAYERED PAPER CUT',engine:'CANVAS 2D',color:'#c16c51',effect:'纸层深度',definition:'用有厚度感的纸层、镂空轮廓和层间阴影构成一个纸雕舞台。边缘与遮挡比真实纹理更重要。',features:['多层镂空拱门与纸叶','纸层之间的投影与前后遮挡','折痕角色和裁切蒸笼'],interaction:'开盖后纸片角色弹出；拖动「纸层深度」观察层间投影，夜晚换成深蓝纸剧场。',use:'手工品牌、童话剧场、节日贺卡、文化活动。',method:'独立镂空路径、分层绘制、阴影与折痕线；这是实时纸雕视觉模拟。'},
 {id:'linocut',group:'print',name:'黑白刻版',en:'LINOCUT / RELIEF PRINT',engine:'CANVAS 2D',color:'#343833',effect:'刻线密度',definition:'模拟凸版印刷的视觉语言：大块黑色与纸白形成强烈对比，刻除的细线留下方向、纹理和节奏。',features:['黑白剪影与有方向的刻线','太阳放射线、叶片与山脊纹理','粗糙印边与不均匀墨点'],interaction:'打开带刻纹的蒸笼；调整刻线密度比较疏密关系，夜晚反转纸与墨的明暗。',use:'艺术海报、文学专题、独立出版、文化地图。',method:'路径裁切内的刻线与固定随机墨点，模拟印刷外观；不模拟实体印版或油墨流体。'},
 {id:'cyanotype',group:'print',name:'植物蓝晒',en:'CYANOTYPE PHOTOGRAM',engine:'CANVAS 2D',color:'#2454a0',effect:'曝光反差',definition:'以深蓝纸面和浅色植物剪影呈现蓝晒摄影的感觉。真实蓝晒是感光工艺，这里用程序模拟它的明暗与边缘。',features:['深蓝色纸面与植物负形','半透明羽状叶与日晒边缘','标本页式编号和手写标签'],interaction:'打开标本蒸笼，伙伴成为一枚浅色剪影；调整曝光反差观察蓝白关系。',use:'植物教育、自然档案、摄影故事、诗意作品集。',method:'透明植物路径、曝光色阶、纸面噪声和边缘晕染；不进行真实化学曝光计算。'},
 {id:'stainedglass',group:'craft',name:'透光彩窗',en:'STAINED GLASS',engine:'CANVAS 2D',color:'#b362a5',effect:'透光强度',definition:'将图像拆成彩色玻璃片，深色边框连接碎片，透射光让颜色从内部发亮。',features:['拱形窗格与深色铅条','几何碎片、内部渐变与光斑','玻璃角色与彩色投射光'],interaction:'开盖拼出彩玻璃伙伴；调节透光强度，夜晚观察背光下的颜色。',use:'艺术展览、宗教或建筑文化介绍、装饰品牌。',method:'原创窗格拓扑、玻璃片渐变、暗边与加色光线；没有光线追踪或真实焦散。'},
 {id:'comic',group:'print',name:'漫画网点',en:'HALFTONE COMIC',engine:'CANVAS 2D',color:'#e75e33',effect:'网点强度',definition:'用分镜、粗黑轮廓、网点和拟声字把一次小动作变成有戏剧性的事件。网点与速度线承担阴影和运动。',features:['斜向分镜与放射速度线','橙蓝撞色、粗轮廓和半色调网点','开盖触发 POP! 与表情变化'],interaction:'开盖进入奖励分镜，挤压出现 SQUISH!；调节网点强度比较印刷质感。',use:'活动揭晓、趣味教程、互动漫画、年轻化品牌。',method:'独立分镜构图、裁切网点、动态拟声字与射线；不用漫画扫描图。'},
 {id:'ascii',group:'digital',name:'终端字符',en:'ASCII / TERMINAL ART',engine:'CANVAS 2D',color:'#76b07a',effect:'字符精度',definition:'画面由字符单元组成，文字同时成为轮廓、明暗与图像材料。像在一个会动的终端里探索。',features:['字母与符号组成山、树和角色','有限绿色字符与终端边框','实时状态行、扫描线与闪烁光标'],interaction:'执行 OPEN 获得角色，挤压会改变字符轮廓；字符精度改变实际采样分辨率。',use:'开发者作品集、编程教学、复古终端、技术品牌。',method:'先绘制离屏亮度图，再逐格采样映射字符；场景真的由文字绘制。'},
 {id:'wireframe',group:'digital',name:'结构线框',en:'WIREFRAME / VECTOR DISPLAY',engine:'CANVAS 2D',color:'#4cc6b4',effect:'网格密度',definition:'去掉实体表面，让投影线条显示几何结构。旋转、透视和虚线遮挡提供空间信息，像早期向量显示器。',features:['旋转球面与蒸笼结构线','投影坐标、轴线与虚线背面','网格密度直接改变结构细节'],interaction:'打开线框蒸笼，球面伙伴持续旋转；调整网格密度观察经纬线数量，挤压改变投影形状。',use:'结构教学、生成艺术、科技展览、建模过程说明。',method:'手写三维点旋转与透视投影后用 Canvas 画线；不是 WebGL 实体场景。'},
 {id:'embroidery',group:'craft',name:'刺绣布艺',en:'EMBROIDERY / TEXTILE',engine:'CANVAS 2D',color:'#bd6b85',effect:'针脚密度',definition:'以可见的针脚方向、线束、布纹和刺绣框构成柔软的手工画面。纹理跟随造型而不是覆盖一层噪点。',features:['亚麻织纹与木质绣框','方向变化的长短针和轮廓缝线','花草、线团和柔软织物角色'],interaction:'开盖让绣线伙伴弹出；调整针脚密度，查看布面与填充线的区别。',use:'纺织手工、慢生活品牌、民俗教育、情感故事。',method:'路径裁切内的方向针脚、缝线高光、程序化织纹；不计算真实纤维动力学。'},
 {id:'ukiyoe',group:'print',name:'木版海浪',en:'WOODBLOCK / UKIYO-E INSPIRED',engine:'CANVAS 2D',color:'#47707b',effect:'海浪线密度',definition:'借鉴日本木版画的轮廓、有限套色、渐变色带与装饰性波浪，用有节奏的线条组织自然景物。',features:['靛蓝浪纹、纸色与有限套色','远山、帆船、浪花与竖排题签','不同方向的刻线塑造波浪'],interaction:'伙伴从浪间的蒸笼弹出；调节浪线密度，夜晚成为深靛蓝海景。',use:'旅行故事、文化展览、海洋主题、餐饮包装。',method:'原创波浪路径、方向刻线和色带渐变；风格借鉴，不复制特定历史作品。'},
 {id:'risograph',group:'print',name:'孔版套色',en:'RISOGRAPH INSPIRED PRINT',engine:'CANVAS 2D',color:'#ed7270',effect:'套色偏移',definition:'用少量鲜明色墨叠印、颗粒和套色偏移构成印刷海报。色层相遇处出现新的混合色，误差成为视觉特征。',features:['珊瑚红与蓝色的双墨叠印','可见的套色偏移和颗粒','版式、巨大几何与实验字体'],interaction:'开盖后两个墨色角色叠合；调整套色偏移，看清两层印版如何错开。',use:'独立杂志、音乐活动、艺术工作室、实验作品集。',method:'离屏色层、multiply 叠印、可调偏移和固定颗粒；不控制真实印刷机。'}
];
STYLES.forEach(s=>s.group='core');
STYLES.push(...EXTRA_STYLES);
