import { build } from 'esbuild';
import { copyFile } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';
import {buildEchoAudio} from './build-echo-audio.mjs';
const root = fileURLToPath(new URL('../', import.meta.url));
await build({ entryPoints: [root + 'src/app.js'], bundle: true, minify: true, legalComments: 'linked', outfile: root + 'web/app.js', nodePaths: [root + 'tooling/node_modules'], target: ['es2022'] });
await copyFile(root + 'tooling/node_modules/three/LICENSE', root + 'web/THREE-LICENSE.txt');
await build({entryPoints:[root+'src/garden.js'],bundle:true,minify:true,outfile:root+'web/garden/app.js',target:['es2022']});
await build({entryPoints:[root+'src/ecosystem.js'],bundle:true,minify:true,outfile:root+'web/garden/ecosystem/app.js',target:['es2022']});
await build({entryPoints:[root+'src/drift.js'],bundle:true,minify:true,outfile:root+'web/garden/drift/app.js',target:['es2022']});
await build({entryPoints:[root+'src/children.js'],bundle:true,minify:true,legalComments:'linked',outfile:root+'web/children/app.js',nodePaths:[root+'tooling/node_modules'],target:['es2022']});
await copyFile(root+'tooling/node_modules/three/LICENSE',root+'web/children/THREE-LICENSE.txt');
await build({entryPoints:[root+'src/playground.js'],bundle:true,minify:true,legalComments:'linked',outfile:root+'web/children/game/app.js',nodePaths:[root+'tooling/node_modules'],target:['es2022']});
await copyFile(root+'tooling/node_modules/three/LICENSE',root+'web/children/game/THREE-LICENSE.txt');
await build({entryPoints:[root+'src/echo.js'],bundle:true,minify:true,legalComments:'linked',outfile:root+'web/echo/app.js',nodePaths:[root+'tooling/node_modules'],target:['es2022']});
await copyFile(root+'tooling/node_modules/three/LICENSE',root+'web/echo/THREE-LICENSE.txt');
for(const name of ['concept-lineup-v1.png','kongkong-standard-v1.png'])await copyFile(root+'assets/echo-crew/'+name,root+'web/echo/'+name);
await buildEchoAudio(root);
console.log('Built self-contained web/app.js');
