const $=s=>document.querySelector(s);
const root=$('#skills');
const skills={
  story:{name:'品牌叙事与选型',project:'山野茶社 · 新品活动',task:'让顾客选择试饮茶款和活动目标，导出包含所选茶款的明确需求。',headline:'从吸引注意，到形成选择。',purpose:'动态视觉让人愿意看，选项比较让人知道选什么。我们把品牌内容、选型与行动入口组织成一条任务路径。',effects:[['hero','01 · 动态产品首屏'],['menu','02 · 选项聚焦']],inputs:'品牌资料、自有产品素材、选项差异、活动事实',interaction:'产品叙事、选项比较、当前选择与行动反馈',output:'响应式活动页、选择记录、结构化需求单',user:'理解产品和下一步',userValue:'将卖点、区别和行动放到同一条路径，帮助顾客做出具体选择。',team:'内容、素材和选项可替换',teamValue:'沉淀页面结构、选择状态和输出格式；用于新品牌时更换客户内容和素材。',proofTitle:'现有场景：山野茶社活动页',proof:'编辑品牌，选择一款虚构示例茶与活动目标，再生成需求单。茶款、目标和当前品牌参数会进入技能交付计划。',scene:'brand',evidence:'内容编辑、三款示例茶选择、主题切换、标题动效、需求单与事实 JSON 已运行。真实套餐、价格和产品资料需按客户提供的内容适配。',functional:['内容与当前选择一致','手机布局和键盘操作可用','导出记录保留品牌、目标和选项','缺少素材时有静态替代'],metrics:['访客能否复述产品与下一步','选对产品的耗时和错误数','接入预约后统计有效预约'],missing:['真实产品素材与选项','活动时间、地点和价格','预约服务与送达测试'],deliverables:['活动页与选型原型','品牌、选项和素材配置','需求单与事实 JSON','交互与布局验收记录']},
  explain:{name:'操作式产品解释',project:'模块桌灯 · 选配说明',task:'让客户通过旋转、配色与结构展开理解桌灯，并导出自己的配置。',headline:'让用户操作，看到变化，理解差异。',purpose:'搅汤值得复用的是“输入改变 → 状态反馈”的机制。用于产品时，交互由产品规则驱动，说明与结果随选择同步。',effects:[['broth','03 · 操作与状态反馈']],inputs:'产品结构、参数、约束、解释步骤与标准素材',interaction:'参数调整、状态变化、解释提示、重置与比较',output:'可操作产品说明、配置记录、画面与需求单',user:'把差异看具体',userValue:'通过自己的操作看到配色、结构和状态变化，减少仅凭照片或文字猜测。',team:'统一参数与结果记录',teamValue:'保留参数模型、输入控制和导出契约；新产品需替换几何、素材及真实业务规则。',proofTitle:'现有场景：模块桌灯配置器',proof:'旋转桌灯，调整配色与结构展开，再导出 PNG 或需求单。当前选项会进入这份技能交付计划。',scene:'product',evidence:'参数化空间原型、旋转、结构展开、配置与 PNG 导出已运行。材质和尺寸为演示近似。',functional:['输入参数与画面一致','旋转、重置和键盘操作正确','导出配置与最终选择一致','解释采用客户提供的真实规则'],metrics:['操作后能否正确解释结构','完成选配的耗时和错误数','同一问题的重复求助次数'],missing:['产品尺寸、模型与材质资料','参数范围与业务规则','库存或报价接口（如需）'],deliverables:['产品交互说明原型','参数、约束和说明配置','配置 JSON、需求单与画面','交互与任务验收记录']},
  territory:{name:'区域服务查询',project:'栖庭景观 · 服务查询',task:'让客户确认所在地区是否提供服务，选择服务类型，形成包含地区信息的咨询摘要。',headline:'把“哪里有服务”变成可查询的答案。',purpose:'地图动画提供地域入口，真正的技能是把地区、服务事实和下一步联系起来。用户应先得到准确答案，再形成完整需求。',effects:[['delivery','04 · 地域选择与目标反馈'],['menu','02 · 服务选项']],inputs:'服务区域、坐标、覆盖规则、服务类型和联系方式',interaction:'地区查询、详情反馈、服务选择与缺省引导',output:'服务区域原型、查询结果、地区需求摘要',user:'快速确认是否适用',userValue:'找到自己的地区，看到可提供的服务和下一步，减少来回询问覆盖范围。',team:'把地域数据和展示分开',teamValue:'保留查询、选择、详情与导出流程；客户提供新的区域和规则后可适配复用。',proofTitle:'本地业务原型：区域服务查询',proof:'以下为虚构服务数据，展示查询如何形成可带走的地区需求。原站投送动画不表示这些区域的覆盖。',evidence:'下面的地区查询、未覆盖反馈、服务选择和结果导出真实运行。地图改成客户区域仍需适配。',functional:['地区查询与提供的覆盖资料一致','未覆盖地区给出明确反馈','需求摘要包含地区和服务类型','坐标、详情与行动入口一致'],metrics:['确认覆盖范围的耗时和错误数','咨询摘要中的缺失字段数量','接入咨询后统计有效需求'],missing:['客户确认的服务区域及坐标','真实服务类型和范围','咨询接口与送达测试'],deliverables:['区域查询与服务选择原型','地区、覆盖与服务配置','地区结果 JSON 与需求摘要','数据与任务验收记录']},
  reveal:{name:'内容揭晓与任务反馈',project:'山野茶社 · 冲泡提示',task:'让新顾客揭晓一条冲泡提示，理解要点，并知道接下来可以做什么。',headline:'把一次点击，变成有用的发现。',purpose:'饼干外观可以替换，核心是清楚的开启、展示、重复与重置状态。揭晓内容应帮助用户学会一点知识或完成下一步。',effects:[['fortune','05 · 开启与内容揭晓']],inputs:'自有视觉素材、内容库、展示规则和后续任务',interaction:'点击揭晓、可读内容、状态反馈与重复流程',output:'内容互动原型、内容配置、揭晓与行动记录',user:'拿到有用的提示',userValue:'用小互动带出产品知识，并给出具体行动。内容价值比开启动画更重要。',team:'替换皮肤与内容库',teamValue:'沉淀展示状态机与内容接口，按品牌替换素材和提示；业务奖励需单独接规则与核销。',proofTitle:'本地业务原型：新茶冲泡提示',proof:'揭晓普通知识提示并生成记录。它用于展示内容与行动反馈，不包含真实优惠券或抽奖。',evidence:'下面的揭晓、重复、重置和内容记录真实运行。原站饼干使用照片贴图与 CSS 开裂。',functional:['每次操作与揭晓状态一致','内容完整可读且来源可核对','重复与重置流程正确','本地内容记录准确；真实奖励另接核销'],metrics:['用户能否正确复述知识要点','提示后的相关任务完成率','后续行动点击（真实场景采样）'],missing:['客户确认的提示与行动内容','自有活动素材','奖励规则、资格与核销接口（如需）'],deliverables:['知识提示或任务反馈原型','内容库与展示规则','揭晓结果 JSON 与交付说明','状态与任务验收记录']}
};
const regions={hangzhou:{name:'杭州',available:true,description:'提供庭院改造与日常维护，可先提交现场资料。'},ningbo:{name:'宁波',available:true,description:'提供庭院改造，现场勘察需另行约定。'},shanghai:{name:'上海',available:false,description:'此虚构示例暂未覆盖；可记录需求，进一步确认服务可能性。'}};
const tips=[{title:'先看建议，再调口味。',content:'参考茶叶包装上的冲泡建议，再按自己的口味调整浓度。',action:'记录茶款和口味偏好，再向店员确认冲泡建议。'},{title:'把偏好说具体。',content:'“清淡一点”或“浓一些”的偏好，能帮助店员给出更合适的试饮建议。',action:'在试饮需求中写下口味偏好。'},{title:'保存喜欢的选择。',content:'记下茶款、用水量与冲泡时间，方便下次比较和调整。',action:'保留自己的冲泡记录，再做下一次尝试。'}];
let current=skills[new URL(location.href).searchParams.get('skill')]?new URL(location.href).searchParams.get('skill'):'explain';
const drafts=Object.fromEntries(Object.entries(skills).map(([key,s])=>[key,{project:s.project,task:s.task,scope:'prototype'}]));
let region='hangzhou',service='庭院改造',tipIndex=-1,revealedCount=0,planVisible=false;
const picker=[...root.querySelectorAll('[data-skill]')];
const businessSnapshots=new Map();
function rememberScene(snapshot){const key=({'一场新品试饮活动':'brand','把产品差异展示出来':'product','先看清空间的取舍':'garden'})[snapshot?.场景];if(key)businessSnapshots.set(key,structuredClone(snapshot));}
function regionResult(){const r=regions[region],available=r.available&&!(region==='ningbo'&&service==='日常维护');return{性质:'虚构服务资料，本地查询结果',地区:r.name,所选服务:service,覆盖状态:available?'示例可服务':'示例未覆盖',服务说明:available?r.description:'此虚构示例暂未覆盖该地区或服务；保留需求后进一步确认。',下一步:available?'提交现场资料，确认服务范围和勘察安排':'保留地区需求，进一步确认覆盖'};}
function sceneSnapshot(){try{rememberScene(JSON.parse($('#facts-preview').textContent));}catch{}return businessSnapshots.get(skills[current].scene)||null;}
function taskResult(){if(current==='territory')return regionResult();if(current==='reveal')return{性质:'普通内容提示，本地记录',揭晓次数:revealedCount,已揭晓:tipIndex>=0,当前内容:tipIndex>=0?{...tips[tipIndex]}:null};return sceneSnapshot()||{状态:'尚未选择关联业务场景',操作入口:'#scenes',说明:'点击下方业务场景入口并操作后，当前配置会进入交付计划。'};}
function contract(){const s=skills[current],d=drafts[current];return{schemaVersion:'1.0',skill:'interactive-business-experience',mode:current,技能方向:s.name,项目:d.project.trim()||'未命名项目',用户任务:d.task.trim()||'待确认任务',计划范围:d.scope==='prototype'?'可运行原型':'可运行原型 + 业务接入计划',需要客户提供:s.inputs,交付物:[...s.deliverables,...(d.scope==='integration'?['业务接口约定、错误与成功状态、待接入清单']:[])],当前业务示例结果:taskResult(),当前实现证据:s.evidence,用户价值:s.userValue,团队价值:s.teamValue,功能验收:s.functional,业务价值验证:{指标:s.metrics,基线:'待真实用户采样',方法:'使用相同任务比较原有方式与新原型，记录耗时、错误与结果完整度。',状态:'尚未实测，未承诺转化率或收入提升'},采用前补齐:s.missing,范围说明:'原型和文件在本地运行；业务接入计划不表示已发送咨询、接通预约或完成奖励核销。',研究来源:'https://combinationsoupstudio.com.au/'};}
function markdown(){const c=contract();return`# ${c.项目} · 技能交付计划\n\n技能：${c.skill}\n技能方向：${c.技能方向}\n计划范围：${c.计划范围}\n\n## 要让用户完成的任务\n\n${c.用户任务}\n\n## 需要客户提供\n\n${c.需要客户提供}\n\n## 交付物\n\n${c.交付物.map(x=>'- '+x).join('\n')}\n\n## 当前业务示例结果\n\n\`\`\`json\n${JSON.stringify(c.当前业务示例结果,null,2)}\n\`\`\`\n\n## 已运行的能力与采用范围\n\n${c.当前实现证据}\n\n${c.范围说明}\n\n## 对用户与团队的价值\n\n用户：${c.用户价值}\n团队：${c.团队价值}\n\n## 功能验收\n\n${c.功能验收.map(x=>'- '+x).join('\n')}\n\n## 业务价值如何验证\n\n${c.业务价值验证.指标.map(x=>'- '+x).join('\n')}\n\n${c.业务价值验证.方法}\n基线：${c.业务价值验证.基线}。${c.业务价值验证.状态}。\n\n## 采用前补齐\n\n${c.采用前补齐.map(x=>'- '+x).join('\n')}\n\n研究来源：${c.研究来源}\n项目内技能文件：skills/interactive-business-experience/SKILL.md\n`;}
function updatePlan(){if(planVisible)$('#skill-plan-text').textContent=markdown();$('#skill-plan-project').textContent=drafts[current].project.trim()||'未命名项目';}
function renderProof(){const s=skills[current],proof=$('#skill-proof');proof.replaceChildren();const copy=document.createElement('div');copy.innerHTML='<p class="eyebrow">操作结果 → 交付记录</p><h4></h4><p class="skill-proof-copy"></p>';copy.querySelector('h4').textContent=s.proofTitle;copy.querySelector('.skill-proof-copy').textContent=s.proof;proof.append(copy);
  if(s.scene){const b=document.createElement('button');b.type='button';b.textContent='操作业务场景 →';b.addEventListener('click',()=>{$('#tab-'+s.scene).click();$('#scenes').scrollIntoView({behavior:matchMedia('(prefers-reduced-motion: reduce)').matches?'instant':'smooth'});});proof.append(b);const snapshot=sceneSnapshot(),note=document.createElement('small');note.id='skill-business-snapshot';note.textContent=snapshot?'已记录该场景当前参数；修改后会同步更新。':'进入关联场景后记录实际配置。';copy.append(note);}
  if(current==='territory'){const field=document.createElement('div');field.innerHTML='<label>地区 <select id="skill-region" aria-label="选择示例地区"><option value="hangzhou">杭州</option><option value="ningbo">宁波</option><option value="shanghai">上海</option></select></label><label>服务 <select id="skill-service" aria-label="选择示例服务"><option>庭院改造</option><option>日常维护</option></select></label>';proof.append(field);$('#skill-region').value=region;$('#skill-service').value=service;const result=document.createElement('div');result.className='skill-query-result';result.setAttribute('role','status');result.innerHTML='<b id="skill-region-status"></b><p id="skill-region-description"></p>';copy.append(result);const update=()=>{const result=regionResult();$('#skill-region-status').textContent=result.地区+' / '+result.所选服务+' · '+result.覆盖状态;$('#skill-region-description').textContent=result.服务说明;updatePlan();};$('#skill-region').addEventListener('change',e=>{region=e.target.value;update();});$('#skill-service').addEventListener('change',e=>{service=e.target.value;update();});update();}
  if(current==='reveal'){const controls=document.createElement('div');controls.innerHTML='<button type="button" id="skill-reveal">揭晓提示 ↗</button> <button type="button" id="skill-reveal-reset" hidden>重置</button>';proof.append(controls);const result=document.createElement('div');result.className='skill-query-result';result.setAttribute('role','status');result.innerHTML='<b id="skill-tip-title"></b><p id="skill-tip-content"></p><small id="skill-tip-action"></small>';copy.append(result);const update=()=>{const opened=tipIndex>=0;$('#skill-tip-title').textContent=opened?tips[tipIndex].title:'等待揭晓一条有用的提示';$('#skill-tip-content').textContent=opened?tips[tipIndex].content:'展示的是内容价值与下一步；品牌外观可换成客户自有素材。';$('#skill-tip-action').textContent=opened?'下一步：'+tips[tipIndex].action:'';$('#skill-reveal').textContent=opened?'再看一条 ↗':'揭晓提示 ↗';$('#skill-reveal-reset').hidden=!opened;updatePlan();};$('#skill-reveal').addEventListener('click',()=>{tipIndex=(tipIndex+1)%tips.length;revealedCount++;update();});$('#skill-reveal-reset').addEventListener('click',()=>{tipIndex=-1;revealedCount=0;update();});update();}
}
function select(key,writeURL=true){current=key;const s=skills[key],d=drafts[key];picker.forEach(b=>{const on=b.dataset.skill===key;b.setAttribute('aria-selected',String(on));b.tabIndex=on?0:-1;});$('#skill-workspace').setAttribute('aria-labelledby','skill-tab-'+key);$('#skill-project').value=d.project;$('#skill-task').value=d.task;$('#skill-scope').value=d.scope;for(const [id,text] of Object.entries({'skill-name':s.name,'skill-headline':s.headline,'skill-purpose':s.purpose,'skill-input-description':s.inputs,'skill-interaction-description':s.interaction,'skill-output-description':s.output,'skill-user-title':s.user,'skill-user-value':s.userValue,'skill-team-title':s.team,'skill-team-value':s.teamValue,'skill-acceptance':s.functional.join('；'),'skill-value-measure':s.metrics.join('；')}))$('#'+id).textContent=text;const origin=$('#skill-origin-buttons');origin.replaceChildren();s.effects.forEach(([effect,label])=>{const b=document.createElement('button');b.type='button';b.textContent=label;b.addEventListener('click',()=>{$('#effect-tab-'+effect).click();$('#original-effects').scrollIntoView({behavior:matchMedia('(prefers-reduced-motion: reduce)').matches?'instant':'smooth'});});origin.append(b);});renderProof();updatePlan();if(writeURL){const url=new URL(location.href);url.searchParams.set('skill',key);history.replaceState(null,'',url);}$('#skill-export-status').textContent='';}
picker.forEach((b,i)=>{b.addEventListener('click',()=>select(b.dataset.skill));b.addEventListener('keydown',e=>{let next;if(e.key==='ArrowRight')next=(i+1)%picker.length;else if(e.key==='ArrowLeft')next=(i+picker.length-1)%picker.length;else if(e.key==='Home')next=0;else if(e.key==='End')next=picker.length-1;else return;e.preventDefault();select(picker[next].dataset.skill);picker[next].focus();});});
for(const [id,key] of [['skill-project','project'],['skill-task','task'],['skill-scope','scope']])$('#'+id).addEventListener('input',e=>{drafts[current][key]=e.target.value;updatePlan();});
function download(content,name,type){const a=document.createElement('a'),url=URL.createObjectURL(new Blob([content],{type}));a.href=url;a.download=name;document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),1500);$('#skill-export-status').textContent='已生成本地文件，包含当前任务与示例结果。';}
$('#skill-download-plan').addEventListener('click',()=>download(markdown(),'skill-'+current+'-delivery.md','text/markdown;charset=utf-8'));
$('#skill-download-config').addEventListener('click',()=>download(JSON.stringify(contract(),null,2),'skill-'+current+'-contract.json','application/json;charset=utf-8'));
$('#skill-plan-toggle').addEventListener('click',e=>{planVisible=!planVisible;$('#skill-plan').hidden=!planVisible;e.currentTarget.setAttribute('aria-expanded',String(planVisible));e.currentTarget.textContent=planVisible?'收起交付计划':'预览交付计划';updatePlan();});
window.addEventListener('business-scene-change',e=>{rememberScene(e.detail);updatePlan();const note=$('#skill-business-snapshot');if(note)note.textContent=sceneSnapshot()?'已记录该场景最新参数；再次操作会同步更新。':'进入关联场景后记录实际配置。';});
select(current,false);
