import {useWorldArt} from './worlds-art.js?v=3';
import {drawing,copy,clamp,noise} from './world-draw.js?v=3';
const courses=[
 {name:'旧城夜线',width:1400,platforms:[{x:20,w:230,y:480},{x:325,w:210,y:450},{x:615,w:250,y:414},{x:950,w:425,y:450}],delivery:{x:1260,y:450},par:18},
 {name:'高架急件',width:1700,platforms:[{x:20,w:210,y:480},{x:320,w:160,y:426},{x:590,w:180,y:370},{x:915,w:155,y:438},{x:1220,w:440,y:400}],delivery:{x:1530,y:400},par:24},
 {name:'清晨回信',width:1440,platforms:[{x:20,w:230,y:480},{x:340,w:220,y:450},{x:650,w:240,y:450},{x:990,w:380,y:415}],delivery:{x:1260,y:415},par:22}
];
const initial=()=>({game:'arcade',version:1,course:0,player:{x:90,y:480,vx:0,vy:0,grounded:true,facing:1},checkpoint:0,status:'ready',runTime:0,time:0,falls:0,autoForward:false,best:[null,null,null],completed:[false,false,false],journal:['旧城夜线：跨过楼间空隙，在落脚点附近按E投递。跌落会回到最近屋顶，并加4秒。'],message:'方向键或AD移动，空格跳跃，F短冲刺。先看清屋顶边缘，再起跑。'});
export function createArcadeGame({mount,saved,onEvent=()=>{}}){const d=drawing(mount,'屋顶快递赛：真实跳跃、冲刺、跌落检查点与三条计时路线'),{canvas,c,rect,poly,line,ellipse,text,person,art}=d;let s=saved?.game==='arcade'&&saved.version===1?{...initial(),...copy(saved)}:initial(),camera=0,coyote=.12,jumpBuffer=0,dash=0,cooldown=0,stride=0,disposed=false;s.course=clamp(Math.floor(s.course)||0,0,2);s.best=courses.map((_,i)=>Number.isFinite(s.best?.[i])?s.best[i]:null);s.completed=courses.map((_,i)=>!!s.completed?.[i]);s.autoForward=false;const course=()=>courses[s.course];
 const emit=t=>{try{onEvent(t)}catch{}},say=(t,event='soft')=>{s.message=t;emit(event)};
 function start(){if(s.status==='ready'){s.status='running';say('计时开始。落到新的屋顶会留下检查点；抵达收件柜仍需亲手投递。')}}
 function restart(next=false){const best=copy(s.best),completed=copy(s.completed),journal=s.journal.slice(),index=next?Math.min(s.course+1,2):s.course;s=initial();s.course=index;s.best=best;s.completed=completed;s.journal=journal;s.journal.push((next?'新路线 · ':'重跑 · ')+course().name);dash=0;cooldown=0;coyote=.12;jumpBuffer=0;camera=0;s.autoForward=false;say(next?'第二条路线的高差和间距更大。将跳跃与冲刺组合起来。':'这次可以调整起跳时机，练习更快的路线。')}
 function command(id){if(disposed)return;if(id==='retry')return restart();if(id==='next-route'&&s.status==='delivered'&&s.course<2)return restart(true);if(id.startsWith('route-')&&s.status==='delivered'){const i=Number(id.slice(6));if(!Number.isInteger(i)||i<0||i>=courses.length||!s.completed[i])return;s.course=i;return restart();}if(s.status==='delivered')return;if(id==='auto-forward'){s.autoForward=!s.autoForward;say(s.autoForward?'自动前进已开启。你仍需判断起跳、冲刺与投递；点一次可停下。':'自动前进已停下，可以用方向键接手。');return;}if(id==='jump'){jumpBuffer=.14;if(s.player.grounded||coyote>0){start();s.player.vy=-570;s.player.grounded=false;coyote=0;jumpBuffer=0;emit('jump')}else say('起跳已预备：落地前140毫秒按下，也能接上下一跳。')}if(id==='dash'){if(cooldown<=0){start();dash=.16;cooldown=.85;emit('soft')}else say('冲刺正在恢复。','bump')}if(id==='deliver'){const t=course().delivery;if(s.player.grounded&&Math.abs(s.player.x-t.x)<66){start();s.status='delivered';s.autoForward=false;s.completed[s.course]=true;s.best[s.course]=s.best[s.course]===null?s.runTime:Math.min(s.best[s.course],s.runTime);const grade=s.falls===0&&s.runTime<=course().par?'准点无损':s.falls===0?'稳妥送达':'重试后送达';s.journal.push(course().name+' · '+s.runTime.toFixed(2)+'秒 · '+s.falls+'次跌落 · '+grade);const replies=['收件人把医院寄来的旧照片收好：“谢谢你今晚跑这一趟，家里一直在等。”','夜班技术员接过零件：“这班检修能赶上了。灯亮起来的时候，你也有一份。”','门口的人接过回信：“我以为要再等一天。谢谢你把这个清晨送过来。”'];s.journal.push(replies[s.course]);say(replies[s.course]+' '+grade+'。用时 '+s.runTime.toFixed(2)+' 秒，个人最佳 '+s.best[s.course].toFixed(2)+' 秒。','success')}else say('先跨过屋顶，站到收件柜旁，再按E投递。','bump')}}
 function tick(dt,input={}){if(disposed)return;s.time+=dt;cooldown=Math.max(0,cooldown-dt);jumpBuffer=Math.max(0,jumpBuffer-dt);if(s.status==='delivered')return;const p=s.player,dx=input.x||(s.autoForward?1:0);if(dx){p.facing=Math.sign(dx);start()}if(['Space','KeyW','ArrowUp'].some(k=>input.pressed?.has(k)))command('jump');if(input.pressed?.has('KeyF'))command('dash');if(input.pressed?.has('KeyE'))command('deliver');if(s.status==='delivered')return;if(s.status==='running')s.runTime+=dt;
 const oldY=p.y;if(p.grounded)coyote=.12;else coyote=Math.max(0,coyote-dt);p.vx=dash>0?p.facing*440:dx*235;dash=Math.max(0,dash-dt);p.x=clamp(p.x+p.vx*dt,10,course().width-10);p.vy+=1400*dt;p.y+=p.vy*dt;p.grounded=false;
 if(p.vy>=0){for(let i=0;i<course().platforms.length;i++){const roof=course().platforms[i];if(p.x>roof.x-5&&p.x<roof.x+roof.w+5&&oldY<=roof.y+.2&&p.y>=roof.y){p.y=roof.y;p.vy=0;p.grounded=true;if(i>s.checkpoint){s.checkpoint=i;s.journal.push('检查点 · 第'+(i+1)+'处屋顶');say('已到第'+(i+1)+'处屋顶，跌落后从这里继续。')}break}}}
 if(p.y>670){const roof=course().platforms[s.checkpoint];p.x=roof.x+Math.min(45,roof.w/2);p.y=roof.y;p.vy=0;p.vx=0;p.grounded=true;s.falls++;s.runTime+=4;dash=0;jumpBuffer=0;s.autoForward=false;say('回到最近屋顶，计时加4秒。观察空隙，再选择起跳与冲刺时机。','bump')}
 if(jumpBuffer>0&&p.grounded){p.vy=-570;p.grounded=false;coyote=0;jumpBuffer=0;emit('jump')}
 stride+=Math.abs(p.vx)*dt/20;camera=clamp(p.x-370,0,course().width-960);
 }
 function draw(){if(disposed)return;const route=course();camera=clamp(s.player.x-370,0,route.width-960);if(!art.background('arcade-city',camera*.12)){const sky=c.createLinearGradient(0,0,0,600);sky.addColorStop(0,'#101529');sky.addColorStop(1,'#284651');rect(0,0,960,600,sky);ellipse(765-camera*.05,101,34,34,'#e7dcc433');ellipse(765-camera*.05,101,22,22,'#d8e3d160');
 for(let layer=0;layer<3;layer++)for(let i=0;i<15;i++){const x=i*122-camera*(.1+layer*.2),h=110+noise(i+layer*71)*210,y=530-h,w=92+noise(i+32)*33;rect(x,y,w,h+100,['#172538','#1c303e','#24424a'][layer]);for(let j=0;j<5;j++)for(let k=0;k<Math.floor(h/23);k++)if(noise(i*77+j*11+k+layer*34)>.35)rect(x+9+j*17,y+12+k*23,5,8,(j+k)%3?'#87b9a021':'#e7c89932');line([[x+w/2,y],[x+w/2+2,y-23]],'#314d56',2)}
} for(let i=0;i<35;i++){const x=(i*97+s.time*39)%990,y=(i*139+s.time*147)%620;line([[x,y],[x-8,y+24]],'#89bfce20',1)}
 c.save();c.translate(-camera,0);for(let i=0;i<route.platforms.length;i++){const r=route.platforms[i];const face=c.createLinearGradient(r.x,r.y,r.x+r.w,600);face.addColorStop(0,'#15292f');face.addColorStop(.55,'#2f464b');face.addColorStop(1,'#12252e');rect(r.x,r.y,r.w,600-r.y,face,0,'#38515a');rect(r.x,r.y,r.w,6,'#abc6b0');rect(r.x,r.y+6,r.w,9,'#4c6b67');line([[r.x,r.y+16],[r.x+r.w,r.y+16]],'#081b25',3);for(let row=0;row<7;row++){const yy=r.y+23+row*15;line([[r.x,yy],[r.x+r.w,yy]],'#8b9d9440',.7);for(let col=0;col<Math.ceil(r.w/27);col++)line([[r.x+col*27+(row%2)*13,yy],[r.x+col*27+(row%2)*13,yy+14]],'#081e2955',.8)}for(let j=0;j<Math.floor(r.w/38);j++){const xx=r.x+12+j*38;rect(xx,r.y+35,23,54,'#0c1c24',1,'#4d696966');rect(xx+3,r.y+39,17,45,j%3?'#6f9c9950':'#d0af6980');line([[xx+11,r.y+39],[xx+11,r.y+84]],'#11252c',2);line([[xx+3,r.y+61],[xx+20,r.y+61]],'#11252c',2)}rect(r.x+20,r.y-21,35,21,'#485759',2,'#708485');for(let k=0;k<5;k++)line([[r.x+25+k*6,r.y-16],[r.x+25+k*6,r.y-5]],'#25383c',2);if(i<route.platforms.length-1){line([[r.x+r.w-18,r.y],[r.x+r.w-18,r.y-30]],'#d7a285',3);rect(r.x+r.w-22,r.y-36,9,7,'#e8b367',1)}if(i===s.checkpoint){line([[r.x+15,r.y],[r.x+15,r.y-50]],'#81b4ad',2);poly([[r.x+15,r.y-50],[r.x+37,r.y-43],[r.x+15,r.y-37]],'#59c8b3')}
 text(String(i+1).padStart(2,'0'),r.x+r.w/2,r.y+93,26,'#b8c6b030','center');}
 const destination=route.delivery;rect(destination.x-23,destination.y-69,46,69,'#364e50',3,'#93dcd0');rect(destination.x-17,destination.y-58,34,22,s.status==='delivered'?'#61d6a3':'#e4b88c',1);text(s.status==='delivered'?'已签收':'收件柜',destination.x,destination.y-81,13,'#d9ebe2','center');line([[destination.x+32,destination.y],[destination.x+32,destination.y-107]],'#6ea29f',2);poly([[destination.x+32,destination.y-107],[destination.x+65,destination.y-98],[destination.x+32,destination.y-87]],'#d788a8');if(dash>0)for(let i=1;i<5;i++)line([[s.player.x-s.player.facing*(i*13),s.player.y-39],[s.player.x-s.player.facing*(i*13+17),s.player.y-39]],'#95e9df'+(80-i*13).toString(16),3);const pose=dash>0?3:!s.player.grounded?2:Math.abs(s.player.vx)>1?1:0;art.shadow(s.player.x,s.player.y,13,.32);if(!art.sprite('runner-'+pose,s.player.x,s.player.y,78,{flip:s.player.facing<0,bob:s.player.grounded&&Math.abs(s.player.vx)>1?Math.sin(stride)*1.1:0}))person(s.player.x,s.player.y,'#c18c77',stride,s.status!=='delivered');c.restore();
 rect(23,20,306,77,'#111d2bcc',4,'#39505f');text('屋顶快递赛',41,49,23,'#e0e5d2');text(route.name+' / '+(s.course+1)+' · 2',42,75,13,'#88bbb8');text(s.runTime.toFixed(2)+' s',925,48,26,'#f4d6a4','right');text('跌落 '+s.falls+'  ·  '+(cooldown>0?'冲刺恢复 '+cooldown.toFixed(1)+'s':'冲刺就绪'),925,73,12,'#8dd1c8','right');rect(24,555,912,27,'#101e2bbe',3);text('← → / A D  移动     空格  跳跃     F  冲刺     E  投递  ·  边缘灯标记落脚处',480,574,12,'#c3d6ce','center');
 if(s.status==='delivered'){rect(270,209,420,122,'#132b32ed',4,'#75c4b0');text('包裹已签收',480,245,27,'#dbe9d0','center');text(route.name+' · '+s.runTime.toFixed(2)+'秒 · '+s.falls+'次跌落',480,275,15,'#e7bfa1','center');text(s.course===0?'可继续挑战高架路线，或重跑改善成绩。':'两条路线均可反复挑战，个人最佳会保留。',480,305,12,'#9dbdb8','center')}
 }
 const pointer=e=>{canvas.focus({preventScroll:true});const p=d.point(e),t=course().delivery;if(Math.hypot(p.x-(t.x-camera),p.y-(t.y-35))<52)command('deliver');else say('这是一条操作路线。用方向键移动、空格跳跃、F冲刺；点击收件柜也能投递。')};canvas.addEventListener('pointerup',pointer);
 function getUI(){return {title:'屋顶快递赛',goal:s.status==='delivered'?(s.course<2?'这一单已签收，下一位收件人仍在等；也可以选择已完成的路线。':'三份快递都留有回信，路线成绩分别保留。'):'跨过楼间空隙，到收件柜旁按E投递。跌落回到最近检查点并加4秒。',message:s.message,progress:course().name+' · '+(s.status==='ready'?'等待起跑':s.status==='delivered'?'已签收':s.runTime.toFixed(1)+'秒'),actions:s.status==='delivered'?[...(s.course<2?[{id:'next-route',label:'接下一单 · '+courses[s.course+1].name,primary:true}]:[]),...courses.flatMap((r,i)=>s.completed[i]&&i!==s.course?[{id:'route-'+i,label:'重访 · '+r.name}]:[]),{id:'retry',label:'重跑当前路线'}]:[{id:'auto-forward',label:s.autoForward?'停下自动前进':'开启自动前进（手动跳跃）'},{id:'jump',label:'跳跃 / 预备下一跳'},{id:'dash',label:'冲刺',disabled:cooldown>0},{id:'deliver',label:'交给收件柜',disabled:!s.player.grounded||Math.abs(s.player.x-course().delivery.x)>=66,primary:true},{id:'retry',label:'从起点重跑'}],inventory:['包裹 '+(s.status==='delivered'?'已签收':'携带中'),'当前检查点 '+(s.checkpoint+1)+'/'+course().platforms.length,'跌落 '+s.falls+' 次（每次加4秒）',...courses.map((r,i)=>r.name+'：'+(s.best[i]===null?'尚无成绩':s.best[i].toFixed(2)+'秒'))],journal:s.journal,complete:s.status==='delivered',controls:'AD/方向键移动 · 空格跳跃 · F冲刺 · E投递 · 也可开启自动前进，专心掌握跳跃与冲刺；跌落后会停下。'}}
 draw();return {element:canvas,tick,draw,command,getUI,getState:()=>copy(s),getTargets:()=>[{id:'delivery',x:course().delivery.x-camera,y:course().delivery.y-35}],dispose(){disposed=true;canvas.removeEventListener('pointerup',pointer);canvas.remove()}};
}
