const assets={day:'courtyard.webp',rain:'courtyard-rain.webp',night:'courtyard-night.webp',truck:'truck.webp',box:'box.webp',fridge:'fridge.webp',fragile:'fragile.webp',sofa:'sofa.webp',idle:'worker-0.webp',walk1:'worker-1.webp',walk2:'worker-2.webp',lift:'worker-3.webp',jump:'worker-4.webp',rest:'worker-5.webp'};
export function createMovingArt(canvas,onProgress=()=>{}){const c=canvas.getContext('2d'),images={},status={ready:false,error:null,loaded:0,total:Object.keys(assets).length};
 let loading=false,revision=0;async function load(){if(loading)return;const generation=++revision;loading=true;status.ready=false;status.error=null;status.loaded=0;try{await Promise.all(Object.entries(assets).map(async([id,file])=>{const image=new Image();await new Promise((resolve,reject)=>{const timer=setTimeout(()=>reject(new Error('Timed out loading '+file)),20000);image.onload=()=>{clearTimeout(timer);resolve()};image.onerror=()=>{clearTimeout(timer);reject(new Error('Could not load '+file))};image.src=new URL('../assets/moving-day/'+file,import.meta.url).href});if(generation!==revision)return;images[id]=image;status.loaded++;onProgress()}));if(generation===revision)status.ready=true}catch(e){if(generation===revision){status.error='场景素材未能加载。请检查连接，然后重试。';console.error('Moving Day assets:',e)}}finally{if(generation===revision){loading=false;onProgress()}}}
 const ready=load();
 const sprite=(id,x,y,w,h,mirror=false)=>{const image=images[id];if(!image)return;c.save();c.translate(x,y);if(mirror)c.scale(-1,1);c.drawImage(image,-w/2,-h,w,h);c.restore()};
 const label=(t,x,y,size=11,color='#fff7df',align='center')=>{c.font=`500 ${size}px "Microsoft YaHei",sans-serif`;c.textAlign=align;c.fillStyle=color;c.fillText(t,x,y)};
 const shadow=(x,y,rx=22,alpha=.24)=>{c.save();c.fillStyle=`rgba(28,35,30,${alpha})`;c.beginPath();c.ellipse(x,y+2,rx,5,0,0,Math.PI*2);c.fill();c.restore()};
 function draw(s,o){c.clearRect(0,0,960,600);if(!status.ready){c.fillStyle='#182723';c.fillRect(0,0,960,600);return}c.drawImage(images[o.mood],0,0,960,600);const shade=c.createLinearGradient(0,0,0,200);shade.addColorStop(0,'#15272370');shade.addColorStop(1,'#15272300');c.fillStyle=shade;c.fillRect(0,0,960,200);
   if(o.mood==='rain'){c.strokeStyle='#c8dde330';c.lineWidth=.8;c.beginPath();for(let i=0;i<80;i++){const x=(i*73+s.time*41)%980,y=(i*97+s.time*178)%620;c.moveTo(x,y);c.lineTo(x-6,y+18)}c.stroke()}
   if(o.mood==='night'){for(let i=0;i<17;i++){c.fillStyle=`rgba(255,226,164,${.12+.12*Math.sin(s.time*1.4+i)})`;c.beginPath();c.arc(80+(i*71)%830,190+((i*137)%230)+Math.sin(s.time+i)*8,1.5,0,Math.PI*2);c.fill()}}
   // The loading ramp is geometry in the same coordinates as its collision surface.
   c.beginPath();c.moveTo(o.ramp[0],510);c.lineTo(o.ramp[1],o.floor);c.lineTo(o.ramp[1],o.floor+8);c.lineTo(o.ramp[0],518);c.closePath();c.fillStyle='#8d7c59';c.fill();c.strokeStyle='#d7c194';c.lineWidth=2;c.stroke();for(let i=1;i<9;i++){const x=o.ramp[0]+(o.ramp[1]-o.ramp[0])*i/9,y=510-(510-o.floor)*i/9;c.beginPath();c.moveTo(x,y);c.lineTo(x+5,y+6);c.strokeStyle='#5c58424d';c.lineWidth=1;c.stroke()}
   shadow(860,512,99,.25);sprite('truck',865,514,326,326*images.truck.height/images.truck.width);
   shadow(o.obstacle.x+o.obstacle.w/2,510,26,.15);sprite('box',o.obstacle.x+o.obstacle.w/2,510,o.obstacle.w,o.obstacle.h);
   const cargo=s.cargo.filter(a=>a.id!==s.holding);for(const item of cargo){if(item.broken)continue;const hasSofa=s.cargo.some(a=>a.type==='sofa'),x=item.delivered?(item.type==='fridge'?757:item.type==='sofa'?810:item.type==='box'?798:850):item.x,y=item.delivered?(hasSofa&&item.type!=='sofa'?o.floor-49:o.floor):item.y+item.h/2;shadow(x,y,item.w*.45,item.delivered?.1:.23);sprite(item.type,x,y,item.w,item.h);if(!item.delivered&&s.phase==='playing'){const near=Math.abs(item.x-s.player.x)<95;label(item.name,item.x,item.y-item.h/2-12,10,near?'#fff7df':'#f0e8d1');if(near&&!s.holding){c.fillStyle='#eff0d7';c.beginPath();c.roundRect(item.x-25,item.y-item.h/2-41,50,21,5);c.fill();label('E 拿起',item.x,item.y-item.h/2-27,10,'#25443b')}}}
   const p=s.player,held=s.cargo.find(a=>a.id===s.holding),frame=!p.grounded?'jump':s.liftUntil>s.time?'lift':Math.abs(p.vx)>10?(Math.floor(p.phase*1.4)%2?'walk1':'walk2'):s.orderDone?'rest':'idle';shadow(p.x,p.y,21,p.grounded?.28:.12);const source=images[frame],height=96,width=height*source.width/source.height;sprite(frame,p.x,p.y+Math.sin(p.phase)*Math.min(1.2,Math.abs(p.vx)/100),width,height,p.facing<0);
   if(held){c.save();c.translate(held.x,held.y);c.rotate(held.angle||0);sprite(held.type,0,held.h/2,held.w,held.h);c.restore()}
   for(const part of s.particles){c.globalAlpha=Math.max(0,1-part.age/part.life);c.fillStyle=part.color;c.beginPath();c.arc(part.x,part.y,part.word?3:2,0,Math.PI*2);c.fill()}c.globalAlpha=1;
   if(s.phase==='playing'&&!s.failed){c.fillStyle='#142c244f';c.beginPath();c.roundRect(790,o.floor-134,148,27,6);c.fill();label(s.holding?'送进货车 · 轻放':'已装车 '+s.cargo.filter(a=>a.delivered).length+' / 3',864,o.floor-116,11);}
 }
 return {status,ready,load,draw};
}
