// Selected menu component adapted from Combination Soup Studio's public page.
// Source imagery and component geometry are retained; scrolling is scoped to this module.
import {scope,clamp} from './runtime.js';
const dishes=[
 {name:'Plain Combination',zh:'基础企业网站',price:'$1,490',pre:'from / AUD',desc:'手机适配、服务介绍与明确的咨询入口，帮助小型业务建立完整的网站。',items:['最多 6 页','手机优先布局','联系表单与点击拨号','基础搜索优化'],heat:1,word:'MILD',url:'plain-combination'},
 {name:'Combination + Tom Yum',zh:'本地业务与搜索',price:'Ask',pre:'the kitchen',desc:'增加内容与地区页面，把服务范围、客户评价和本地业务信息讲清楚。',items:['最多 12 页','网站文案','服务地区页面','Google 商家资料','客户评价展示'],heat:3,word:'HOT',url:'combination-tom-yum'},
 {name:'Laksa, Everything In',zh:'网站与在线商店',price:'Ask',pre:'the kitchen',desc:'在网站中加入商品与结账，把商品目录、配送规则和订单流程组织起来。',items:['包含第二档服务','商品目录','购物车与 Stripe','配送、税费与订单邮件'],heat:5,word:'EVERYTHING IN',url:'laksa-everything-in'}
];
export function mount(host,{reduced,onState}){
  host.innerHTML=`<div class="native-effect native-menu"><div class="menu-scroll" tabindex="0" aria-label="在整个演示区域滚动切换三档服务套餐"><div class="native-menu-track"><div class="native-menu-pin"><div class="native-heading"><span>02 / THE MENU</span><h3>Pick your soup.</h3><p>在演示区域滚动，转动原站的餐桌菜单。</p></div><div class="native-menu-body"><article class="native-service-card"><div data-card></div><div class="native-dots" role="group" aria-label="选择套餐">${dishes.map((_,i)=>`<button type="button" data-menu="${i}" aria-label="选择第 ${i+1} 档套餐" aria-pressed="${i===0}">${i+1}</button>`).join('')}</div></article><div class="native-susan"><div class="native-plate"><svg class="native-rimtext" viewBox="0 0 600 600" aria-hidden="true"><defs><path id="cs011-rimp" d="M300,300 m-262,0 a262,262 0 1,1 524,0 a262,262 0 1,1 -524,0"/></defs><text><textPath href="#cs011-rimp">Every site is a bowl of the same good stock · what changes is how much goes in it ·</textPath></text></svg>${dishes.map((s,i)=>`<div class="native-dish dish-${i}"><img src="source-assets/menu-${i+1}.webp" alt="${s.name} 对应的原站汤碗图片"></div>`).join('')}<div class="native-bearing"><svg viewBox="0 0 40 40" aria-hidden="true"><circle cx="20" cy="20" r="17" fill="none" stroke="currentColor" stroke-width="2.5" stroke-dasharray="80 27"/><path d="M33 9 l4 8 -9 -1 z" fill="currentColor"/><circle cx="20" cy="20" r="4" fill="currentColor"/></svg></div></div></div></div><div class="native-module-foot"><span>SCROLL TO SPIN ↓</span><span data-menu-progress>01 / 03</span></div></div></div></div></div>`;
  const life=scope(host),plate=host.querySelector('.native-plate'),scroll=host.querySelector('.menu-scroll'),card=host.querySelector('[data-card]');
  let current=-1,progress=0;
  const base=()=>host.clientWidth<640?0:-90;
  function render(p){progress=clamp(p,0,1);const i=Math.min(2,Math.round(progress*2)),s=dishes[i];plate.style.transform=`rotate(${base()-progress*240}deg)`;host.querySelectorAll('.native-dish').forEach((el,n)=>el.classList.toggle('on',n===i));if(current!==i){current=i;card.innerHTML=`<div class="native-swap"><p class="native-no">NO. ${i+1}</p><h4 data-menu-name>${s.name}</h4><p class="native-price"><b>${s.price}</b><span>${s.pre}</span></p><strong class="native-card-zh">${s.zh}</strong><p class="native-desc">${s.desc}</p><ul>${s.items.map(t=>`<li>${t}</li>`).join('')}</ul><div class="native-chilli" aria-label="辣度 ${s.heat} / 5">${[1,2,3,4,5].map(n=>`<i class="${n<=s.heat?'on':''}"></i>`).join('')}<span>${s.word}</span></div><a class="native-card-more" href="https://combinationsoupstudio.com.au/menu/${s.url}/" target="_blank" rel="noopener">查看原站套餐 →</a></div>`;host.querySelectorAll('[data-menu]').forEach(b=>b.setAttribute('aria-pressed',String(+b.dataset.menu===i)));}host.querySelector('[data-menu-progress]').textContent=String(i+1).padStart(2,'0')+' / 03';onState({当前套餐:i+1,滚动进度:Math.round(progress*100)+'%',转盘角度:Math.round(-progress*240)+'°',素材:'原站三张汤碗照片'});}
  life.listen(scroll,'scroll',()=>render(scroll.scrollTop/(scroll.scrollHeight-scroll.clientHeight)),{passive:true});
  host.querySelectorAll('[data-menu]').forEach(b=>life.listen(b,'click',()=>scroll.scrollTo({top:(scroll.scrollHeight-scroll.clientHeight)*(+b.dataset.menu/2),behavior:reduced?'instant':'smooth'})));
  life.listen(scroll,'keydown',e=>{if(['ArrowLeft','ArrowRight'].includes(e.key)){e.preventDefault();const next=clamp(current+(e.key==='ArrowRight'?1:-1),0,2);scroll.scrollTo({top:(scroll.scrollHeight-scroll.clientHeight)*next/2,behavior:reduced?'instant':'smooth'});}});
  let disposed=false;
  const ro=new ResizeObserver(()=>render(progress));ro.observe(host);render(0);
  function fitRim(){if(disposed)return;const text=host.querySelector('.native-rimtext text'),path=text.querySelector('textPath'),circumference=2*Math.PI*262,n=path.textContent.length;text.style.letterSpacing='0px';for(let k=0;k<3;k++){const length=path.getComputedTextLength();if(!length)return;const cur=parseFloat(text.style.letterSpacing)||0;text.style.letterSpacing=(cur+(circumference-length)/n)+'px';}}
  Promise.all([document.fonts.load('15px SoupMono'),document.fonts.ready]).then(fitRim).catch(()=>{});
  return {dispose(){disposed=true;ro.disconnect();life.dispose();}};
}
