import {T,createStage,bindFPS,moveFPS,fpsCamera,fpsPad,synth,clamp} from './four-playable-stage.js';
import {batchStatic} from './games-art.js';
import {buildDefenseRoom,makeDefenseGuard,poseDefenseGuard} from './defense-detail.js?v=16';
import {makeShotFeedback} from './defense-shot-feedback.js';
const MELEE={trigger:1.45,reach:1.6,frontDot:.45,windup:.85,strike:.22,recovery:.9};
// The attack clock must include render time; hidden intervals must not become attacks.
function defenseLoop(step,draw,needed,afterFrame){let raf=0,last=null,active=true,disposed=false,activeElapsed=0,activeSince=null;const controller=new AbortController(),wallSeconds=()=>activeElapsed+(activeSince===null?0:(performance.now()-activeSince)/1000);function tick(t){raf=0;if(disposed||!active||document.hidden||!needed()){stop();return;}let remaining=Math.max(0,(t-last)/1000);last=t;while(remaining>1e-8){const dt=Math.min(1/120,remaining);step(dt);remaining-=dt;}afterFrame();draw();start();}function start(){if(!raf&&!disposed&&active&&!document.hidden&&needed()){if(last===null)last=performance.now();if(activeSince===null)activeSince=performance.now();raf=requestAnimationFrame(tick);}}function stop(){cancelAnimationFrame(raf);raf=0;last=null;if(activeSince!==null){activeElapsed+=(performance.now()-activeSince)/1000;activeSince=null;}}document.addEventListener('visibilitychange',()=>document.hidden?stop():start(),{signal:controller.signal});return {start,stop,get active(){return active&&!document.hidden&&!disposed;},get wallSeconds(){return wallSeconds();},setActive(v){active=Boolean(v);if(active)start();else stop();},dispose(){disposed=true;active=false;stop();controller.abort();}};}
export function mount(container,h){
 h.css('defense.css');const ctrl=new AbortController(),signal=ctrl.signal,audio=synth(),shell=document.createElement('section');shell.className='lab-demo defense-lab';
 shell.innerHTML='<div class="defense-heading"><div><span>CORE ROOM / 第一人称生存演练</span><h3>守住机房，应对三波机器人</h3></div><b data-defense-phase>等待开始</b></div><div class="defense-metrics"><span>波次 <b data-defense-wave>0 / 3</b></span><span>生命 <b data-defense-health>100</b></span><span>电荷 <b data-defense-energy>12 / 12</b></span><span>停机 <b data-defense-kills>0</b></span></div><div class="defense-viewport"><canvas class="lab-canvas defense-canvas" tabindex="0" aria-label="第一人称室内机器人生存。WASD移动，拖拽或方向键转向，点击或空格射击，R充能"></canvas><span class="defense-crosshair" aria-hidden="true"><i></i><i></i><i></i><i></i><b></b></span><div class="defense-scene-label">CORE-03 <span data-defense-renderer></span></div><div class="defense-hit" data-defense-hit>×</div><div class="defense-feedback" data-defense-feedback></div><div class="defense-damage" data-defense-damage></div><div class="defense-threat" data-defense-threat hidden><b data-defense-threat-text></b><span><i data-defense-threat-progress></i></span></div></div><div class="defense-control-grid">'+fpsPad()+'<div class="defense-fire-controls"><button class="lab-button primary" data-defense-fire>射击 · 空格</button><button class="lab-button" data-defense-aim>瞄准最近机器人</button><button class="lab-button" data-defense-reload>充能 · R</button></div></div><p class="defense-rule">WASD 移动 · ← / → 转向 · 拖动画面瞄准 · 点击画面或空格射击 · R 充能。按钮瞄准只调整视线，射击仍需命中。机器人停步抬臂时会蓄势，后退或绕开可躲过挥击；恢复期间可反击。停机三波即胜。</p><div class="lab-controls"><button class="lab-button primary" data-defense-start>开始生存演练</button><button class="lab-button" data-defense-reset>重置演练</button><button class="lab-button" data-defense-sound aria-pressed="true">声音：开</button><button class="lab-button" data-defense-export>导出演练记录 JSON</button></div><p class="lab-status" role="status" data-defense-status>原创房间与机械机器人，参考第一人称波次生存效果。没有使用或移植 COD 源码与资产。</p>';container.append(shell);const q=s=>shell.querySelector(s),stage=createStage(q('canvas'),{background:'#16222d',fov:70}),canvas=stage.canvas,player={x:0,z:6,yaw:0,pitch:0},counts=[3,4,5],obstacles=[{x:-5,z:0,w:2,d:4},{x:5,z:0,w:2,d:4}],colliderMeshes=[],roomRayMeshes=[],allBots=[];const defaultPixelRatio=stage.supported?stage.renderer.getPixelRatio():1;let state,nextId=1,gun,shotFx,hitFlash=0,damageFlash=0,feedbackTime=0,lastShotResult='none',lastImpact=null,pendingDamage=false;
 const say=t=>{q('[data-defense-status]').textContent=t;h.onStatus(t);},record=(action,detail)=>state.log.push({time:+state.elapsed.toFixed(1),action,detail});
 if(stage.supported){
  gun=buildDefenseRoom(stage,obstacles,colliderMeshes);
  batchStatic(stage.scene,colliderMeshes);
  // Reuse the actual batched room surfaces, so a closed door or rack face stops the shot.
  roomRayMeshes.push(...new Set([...stage.scene.children.filter(o=>o.isMesh),...colliderMeshes]));gun.scale.setScalar(.62);gun.position.set(...Object.values(gun.userData.viewBase));stage.camera.add(gun);stage.scene.add(stage.camera);
  shotFx=makeShotFeedback(stage,gun);
 }
 q('[data-defense-renderer]').textContent=stage.supported?'抬臂蓄势 · 后退避开':'二维演练模式';
 function buildBot(e){if(!stage.supported)return;const g=makeDefenseGuard();g.userData.enemyId=e.id;stage.scene.add(g);e.model=g;e.lenses=[];g.traverse(o=>{if(o.material?.emissive?.getHex())e.lenses.push({material:o.material,intensity:o.material.emissiveIntensity});});const arc=new T.Mesh(new T.RingGeometry(MELEE.reach-.025,MELEE.reach,48,1,Math.PI/2-Math.acos(MELEE.frontDot),2*Math.acos(MELEE.frontDot)),new T.MeshBasicMaterial({color:'#e6a35b',transparent:true,opacity:0,side:T.DoubleSide,depthWrite:false}));arc.rotation.x=Math.PI/2;const cue=new T.Group();cue.add(arc);stage.scene.add(cue);e.cue=cue;e.arc=arc;allBots.push(g,cue);}
 function reset(){for(const g of allBots){stage.scene?.remove(g);g.traverse(o=>{o.geometry?.dispose();o.material?.dispose();});}allBots.length=0;Object.assign(player,{x:0,z:6,yaw:0,pitch:0});state={status:'ready',wave:0,health:100,ammo:12,kills:0,shots:0,hits:0,attacks:0,dodgedAttacks:0,incomingHits:0,elapsed:0,spawned:0,nextSpawn:0,breakTime:0,reload:0,shotCooldown:0,enemies:[],log:[]};keys?.clear();nextId=1;hitFlash=damageFlash=feedbackTime=0;shotFx?.reset();pendingDamage=false;lastShotResult='none';lastImpact=null;q('[data-defense-feedback]').textContent='';sync();draw();}
 function sync(){if(pendingDamage){damageFlash=Math.max(damageFlash,.6);pendingDamage=false;}q('[data-defense-wave]').textContent=state.wave+' / 3';q('[data-defense-health]').textContent=Math.max(0,Math.ceil(state.health));q('[data-defense-energy]').textContent=state.reload>0?'充能中':state.ammo+' / 12';q('[data-defense-kills]').textContent=state.kills;q('[data-defense-phase]').textContent=({ready:'等待开始',playing:'生存进行中',break:'波次间歇',won:'三波存活 ✓',lost:'生命归零'}[state.status]);q('[data-defense-start]').textContent=({ready:'开始生存演练',playing:'演练进行中',break:'演练进行中',won:'演练已完成',lost:'生存挑战已结束'}[state.status]);q('[data-defense-start]').disabled=state.status!=='ready';q('[data-defense-hit]').style.opacity=String(clamp(hitFlash/.18,0,1));q('[data-defense-feedback]').style.opacity=String(clamp(feedbackTime/.25,0,1));q('[data-defense-damage]').style.opacity=String(clamp(damageFlash/.6,0,1)*.75);syncThreat();}
 function beginWave(){state.wave++;state.status='playing';state.spawned=0;state.nextSpawn=.2;record('波次开始',state.wave);say('第 '+state.wave+' 波，机器人正在进入机房。');}
 function spawn(){const pos=[[-3,-10],[3,-10],[-9,-6],[9,-6],[0,-10]][state.spawned%5];const e={id:nextId++,x:pos[0],z:pos[1],hitPulse:0,hp:state.wave===1?2:3,maxHp:state.wave===1?2:3,attackPhase:'pursuit',phaseTime:0,attackCycle:0,attackYaw:0,lastAttackResult:null,lastAttackDistance:null,pendingStrike:false,windupAwaitingDraw:false,warningVisibleClock:null,warningSimulationStart:null,lastWindupWallDuration:null,speed:.72+state.wave*.15};buildBot(e);state.enemies.push(e);state.spawned++;}
 function resolveStrike(e){const dx=player.x-e.x,dz=player.z-e.z,distance=Math.hypot(dx,dz),dot=distance<.0001?1:(dx*Math.sin(e.attackYaw)+dz*Math.cos(e.attackYaw))/distance,hit=distance<=MELEE.reach&&dot>=MELEE.frontDot;e.pendingStrike=true;e.lastWindupWallDuration=loop.wallSeconds-e.warningVisibleClock;e.lastAttackResult=hit?'hit':'miss';e.lastAttackDistance=distance;if(hit){state.health=Math.max(0,state.health-12);state.incomingHits++;damageFlash=.8;pendingDamage=true;record('近身冲击',{enemy:e.id,attack:e.attackCycle,damage:12,distance:+distance.toFixed(3),frontDot:+dot.toFixed(3),visibleWindupWallSeconds:+e.lastWindupWallDuration.toFixed(3),visibleWindupSimulationSeconds:+(state.elapsed-e.warningSimulationStart).toFixed(3),phase:'strike'});audio.play(90,.2,'triangle');}else{state.dodgedAttacks++;record('近身落空',{enemy:e.id,attack:e.attackCycle,distance:+distance.toFixed(3),frontDot:+dot.toFixed(3),reason:distance>MELEE.reach?'out-of-range':'outside-forward-sector',visibleWindupWallSeconds:+e.lastWindupWallDuration.toFixed(3),visibleWindupSimulationSeconds:+(state.elapsed-e.warningSimulationStart).toFixed(3),phase:'strike'});audio.play(145,.09,'triangle');}}
 function updateEnemy(e,dt){const dx=player.x-e.x,dz=player.z-e.z,dist=Math.hypot(dx,dz);e.hitPulse=Math.max(0,e.hitPulse-dt);if(e.attackPhase==='pursuit'){e.attackYaw=Math.atan2(dx,dz);if(dist<=MELEE.trigger){e.attackPhase='windup';e.phaseTime=0;e.windupAwaitingDraw=true;e.attackCycle++;state.attacks++;record('进攻蓄势',{enemy:e.id,attack:e.attackCycle,distance:+dist.toFixed(3),lockedYaw:+e.attackYaw.toFixed(3)});audio.play(340,.12,'triangle');}else if(dist>.0001){const nextX=e.x+dx/dist*e.speed*dt,nextZ=e.z+dz/dist*e.speed*dt,block=(x,z)=>obstacles.some(o=>x>o.x-o.w/2-.35&&x<o.x+o.w/2+.35&&z>o.z-o.d/2-.35&&z<o.z+o.d/2+.35);if(!block(nextX,e.z))e.x=nextX;if(!block(e.x,nextZ))e.z=nextZ;}}else{if(e.windupAwaitingDraw)return;e.phaseTime+=dt;if(e.attackPhase==='windup'&&e.phaseTime>=MELEE.windup&&loop.wallSeconds-e.warningVisibleClock>=MELEE.windup){e.attackPhase='strike';e.phaseTime-=MELEE.windup;resolveStrike(e);}else if(e.attackPhase==='strike'&&e.phaseTime>=MELEE.strike){e.attackPhase='recovery';e.phaseTime-=MELEE.strike;}else if(e.attackPhase==='recovery'&&e.phaseTime>=MELEE.recovery){e.attackPhase='pursuit';e.phaseTime=0;}}}
 function paintEnemy(e){if(!e.model)return;const phase=e.pendingStrike?'strike':e.attackPhase,progress=clamp(e.phaseTime/(MELEE[phase]||1),0,1),walk=phase==='pursuit'?Math.sin(state.elapsed*5+e.id):0,wind=phase==='windup'?.65+.35*progress:0,strike=phase==='strike'?1:phase==='recovery'?1-progress:0;e.model.position.set(e.x+Math.sin(e.attackYaw)*strike*.12,walk*.035,e.z+Math.cos(e.attackYaw)*strike*.12);e.model.rotation.set(-wind*.12+strike*.18-Math.sin(e.hitPulse/.22*Math.PI)*.16,e.attackYaw,0);poseDefenseGuard(e.model,{phase,progress,walk,wind});
  e.cue.position.set(e.x,.027,e.z);e.cue.rotation.y=e.attackYaw;e.arc.material.opacity=phase==='windup'?.16+wind*.5:phase==='strike'?.72:phase==='recovery'?(1-progress)*.12:0;e.arc.material.color.set(phase==='strike'?'#ffe2a5':'#e6a35b');for(const lens of e.lenses)lens.material.emissiveIntensity=lens.intensity+wind*.8+strike*.6;
 }
 function acknowledgeAttackDraw(){for(const e of state?.enemies||[]){e.pendingStrike=false;if(e.windupAwaitingDraw&&e.attackPhase==='windup'){e.windupAwaitingDraw=false;e.warningVisibleClock=loop.wallSeconds;e.warningSimulationStart=state.elapsed;record('蓄势提示',{enemy:e.id,attack:e.attackCycle,phase:'windup'});}}}
 function syncThreat(){const e=state.enemies.filter(e=>e.attackPhase!=='pursuit'&&Math.hypot(e.x-player.x,e.z-player.z)<4).sort((a,b)=>Math.hypot(a.x-player.x,a.z-player.z)-Math.hypot(b.x-player.x,b.z-player.z))[0],cue=q('[data-defense-threat]');cue.hidden=!e;if(!e)return;cue.dataset.phase=e.attackPhase;q('[data-defense-threat-text]').textContent=({windup:'机械臂蓄势 · 后退避开',strike:'机械臂挥击',recovery:'机械臂恢复 · 可以反击'}[e.attackPhase]);q('[data-defense-threat-progress]').style.width=(100*clamp(e.phaseTime/MELEE[e.attackPhase],0,1))+'%';}

 function aim(){const e=[...state.enemies].sort((a,b)=>Math.hypot(a.x-player.x,a.z-player.z)-Math.hypot(b.x-player.x,b.z-player.z))[0];if(!e){say('当前没有机器人可瞄准。');return;}const dx=e.x-player.x,dz=e.z-player.z;player.yaw=Math.atan2(dx,-dz);player.pitch=Math.atan2(1.1-1.7,Math.hypot(dx,dz));draw();say('已把视线转向最近机器人，点击射击。');}
 function reload(){if(state.ammo===12||state.reload>0||!['playing','break'].includes(state.status))return;state.reload=1.3;record('充能','1.3秒');audio.play(260,.2,'triangle');sync();}
 function shoot(){if(!loop?.active||!['playing','break'].includes(state.status)||state.reload>0||state.shotCooldown>0)return;if(state.ammo<=0){say('电荷用尽，按 R 或充能按钮。');return;}state.ammo--;state.shots++;state.shotCooldown=.22;audio.play(190,.09,'sawtooth');fpsCamera(stage,player);let hit=null,point,surface='air',normal,distance=22;
  if(stage.supported){stage.scene.updateMatrixWorld(true);const ray=new T.Raycaster();ray.setFromCamera(new T.Vector2(0,0),stage.camera);const hits=ray.intersectObjects([...state.enemies.map(e=>e.model),...roomRayMeshes],true);const first=hits[0];if(first){point=first.point;distance=first.distance;normal=first.face?.normal.clone().applyMatrix3(new T.Matrix3().getNormalMatrix(first.object.matrixWorld)).normalize()||ray.ray.direction.clone().negate();let obj=first.object;while(obj&&!obj.userData.enemyId)obj=obj.parent;if(obj)hit=state.enemies.find(e=>e.id===obj.userData.enemyId);surface=hit?'robot':'room';}point??=ray.ray.at(22,new T.Vector3());normal??=ray.ray.direction.clone().negate();
  }else{hit=state.enemies.find(e=>Math.abs(Math.atan2(e.x-player.x,-(e.z-player.z))-player.yaw)<.11);}
  feedbackTime=.5;lastShotResult=hit?'hit':'miss';q('[data-defense-feedback]').dataset.kind=lastShotResult;q('[data-defense-feedback]').textContent=hit?'命中':surface==='room'?'环境落点 · 未命中':'未命中';if(!hit)say(surface==='room'?'击中环境表面，未命中机器人；调整瞄准。':'未命中机器人，调整准星后再射击。');if(hit){state.hits++;hit.hp--;hit.hitPulse=.22;hitFlash=.22;lastImpact=point?{x:+point.x.toFixed(2),y:+point.y.toFixed(2),z:+point.z.toFixed(2)}:null;q('[data-defense-hit]').textContent='×';q('[data-defense-feedback]').textContent='命中 · 防护 '+Math.max(0,hit.hp)+' / '+hit.maxHp;say('命中机器人 '+hit.id+'，剩余防护 '+Math.max(0,hit.hp)+'。');record('射击命中',hit.id);if(hit.hp<=0){lastShotResult='stopped';q('[data-defense-feedback]').dataset.kind='stopped';q('[data-defense-feedback]').textContent='机器人停机 ✓';q('[data-defense-hit]').textContent='✓';state.kills++;state.enemies.splice(state.enemies.indexOf(hit),1);if(hit.model)hit.model.visible=false;if(hit.cue)hit.cue.visible=false;audio.play(630,.14);say('机器人 '+hit.id+' 已停机。');}}if(shotFx&&point){shotFx.fire({clock:loop.wallSeconds,elapsed:state.elapsed,ammo:state.ammo,result:lastShotResult,point,normal,surface,enemyId:hit?.id,distance});record('发射呈现',shotFx.getState().lastShot);}sync();draw();
 }
 const keys=bindFPS(canvas,shell,player,ctrl,{shoot});
 const loop=defenseLoop(dt=>{state.elapsed+=dt;state.shotCooldown=Math.max(0,state.shotCooldown-dt);hitFlash=Math.max(0,hitFlash-dt);feedbackTime=Math.max(0,feedbackTime-dt);damageFlash=Math.max(0,damageFlash-dt);if(state.reload>0){state.reload=Math.max(0,state.reload-dt);if(state.reload===0){state.ammo=12;audio.play(740,.1);}}moveFPS(player,keys,dt,{minX:-10.5,maxX:10.5,minZ:-10.4,maxZ:10.4},obstacles,4);
  if(state.status==='break'){state.breakTime-=dt;if(state.breakTime<=0)beginWave();}
  else if(state.status==='playing'){state.nextSpawn-=dt;if(state.spawned<counts[state.wave-1]&&state.nextSpawn<=0){spawn();state.nextSpawn=2.6;}state.enemies.forEach(e=>updateEnemy(e,dt));if(state.health<=0){state.status='lost';record('失败','生命归零');say('生存结束，生命归零。重置后可再练习。');}else if(state.spawned===counts[state.wave-1]&&!state.enemies.length){if(state.wave===3){state.status='won';record('获胜','三波机器人全部停机');say('三波完成，共停机 '+state.kills+' 个机器人。');}else{state.status='break';state.breakTime=2;record('波次完成',state.wave);}}}
 },draw,()=>state&&['playing','break'].includes(state.status),sync);
 function draw(){state?.enemies.forEach(paintEnemy);if(stage.supported){const ratio=loop?.active&&['playing','break'].includes(state?.status)?Math.min(defaultPixelRatio,960/Math.max(canvas.clientWidth,canvas.clientHeight)):defaultPixelRatio;if(Math.abs(stage.renderer.getPixelRatio()-ratio)>.001)stage.renderer.setPixelRatio(ratio);fpsCamera(stage,player);if(shotFx){const recoil=shotFx.update(loop.wallSeconds,state?.elapsed||0,state?.ammo??12);q('.defense-crosshair').style.setProperty('--shot-spread',(recoil.kick*4).toFixed(2)+'px');}stage.draw();acknowledgeAttackDraw();}else{const c=stage.ctx,w=canvas.width=960,hh=canvas.height=540;c.fillStyle='#182631';c.fillRect(0,0,w,hh);c.fillStyle='#496677';c.fillRect(80,80,800,380);c.strokeStyle='#cce3dd';state?.enemies.forEach(e=>{const x=480+(e.x-player.x)*23,y=270+(e.z-player.z)*14;c.fillStyle='#e2b96a';c.fillRect(x-16,y-23,32,46);});c.fillStyle='#daf2ec';c.font='20px system-ui';c.fillText('二维兼容：方向转向 + 瞄准 + 射击仍可操作',110,55);acknowledgeAttackDraw();}}
 shell.addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;if(b.hasAttribute('data-defense-start')){beginWave();sync();canvas.focus({preventScroll:true});audio.play(680,.2);loop.start();}if(b.hasAttribute('data-defense-reset')){loop.stop();reset();say('机房已重置。');}if(b.hasAttribute('data-defense-fire')){shoot();canvas.focus({preventScroll:true});}if(b.hasAttribute('data-defense-aim'))aim();if(b.hasAttribute('data-defense-reload'))reload();if(b.hasAttribute('data-defense-sound')){b.textContent='声音：'+(audio.toggle()?'开':'关');b.setAttribute('aria-pressed',String(audio.enabled));}if(b.hasAttribute('data-defense-export'))h.downloadFile('第一人称机房生存记录.json',JSON.stringify(getState(),null,2),'application/json');},{signal});
 window.addEventListener('keydown',e=>{if(document.activeElement===canvas&&e.key.toLowerCase()==='r'){e.preventDefault();reload();}},{signal});
 function getState(){return {module:'defense',status:state.status,running:loop.active&&['playing','break'].includes(state.status),renderer:stage.supported?'webgl':'canvas',rendering:stage.supported?{drawCalls:stage.renderer.info.render.calls,triangles:stage.renderer.info.render.triangles,pixelRatio:+stage.renderer.getPixelRatio().toFixed(4),defaultPixelRatio,qualityPolicy:"active longest side at most 960px; ready, paused and finished restore default DPR",canvasPixels:{width:canvas.width,height:canvas.height},interactiveResolutionLimit:960,staticDrawCallsSaved:stage.scene.userData.staticDrawCallsSaved||0}:null,wave:state.wave,totalWaves:3,health:Math.round(state.health),ammo:state.ammo,reloading:state.reload>0,kills:state.kills,shots:state.shots,hits:state.hits,attacks:state.attacks,dodgedAttacks:state.dodgedAttacks,incomingHits:state.incomingHits,attackTiming:{clock:"wall-clock",reactionStart:"after first warning draw; active wall clock excludes hidden intervals",maxIntegrationStep:1/120,...MELEE},elapsed:+state.elapsed.toFixed(1),shotPresentation:shotFx?.getState()||null,feedback:{canFire:loop.active&&['playing','break'].includes(state.status)&&state.reload<=0&&state.shotCooldown<=0&&state.ammo>0,lastShotResult,hitConfirmed:hitFlash>0,damageCue:damageFlash>0,lastImpact},player:{x:+player.x.toFixed(2),z:+player.z.toFixed(2),yaw:+player.yaw.toFixed(3),pitch:+player.pitch.toFixed(3)},enemies:state.enemies.map(e=>({id:e.id,x:+e.x.toFixed(2),z:+e.z.toFixed(2),hp:e.hp,attack:{phase:e.attackPhase,phaseElapsed:+e.phaseTime.toFixed(3),cycle:e.attackCycle,lockedYaw:+e.attackYaw.toFixed(3),lastResult:e.lastAttackResult,lastDistance:e.lastAttackDistance===null?null:+e.lastAttackDistance.toFixed(3),visibleWindupWallSeconds:e.lastWindupWallDuration===null?null:+e.lastWindupWallDuration.toFixed(3)}})),artwork:{room:stage.scene?.userData.defenseRoom||null,weapon:gun?.userData.design||null,guards:state.enemies.filter(e=>e.model).map(e=>({id:e.id,...e.model.userData.design}))},scope:'Original FPS room and robots. No COD code/assets ported. Ray hits, simple pursuit, telegraphed directional melee with range-checked strike, cover collision, three waves. Weapon recoil is a bounded visual response only; camera aiming is unchanged. Tracer starts at the actual weapon muzzle; sparks require a real ray intersection. Active play is limited to 960px; ready/paused/finished restore default clarity.',log:state.log.map(x=>({...x}))};}
 reset();return {getState,setActive(v){keys.clear();loop.setActive(v);if(!v){audio.suspend();draw();}},dispose(){loop.dispose();ctrl.abort();audio.dispose();stage.dispose();shell.remove();}};
}




