import {createMotionExport} from './motion-export.js';
import {renderEssay} from './essay-cinema.js';
import {essaySequence,essayContinuityPlan} from './essay-sequence.js';
export async function mount(container,h){
 const fonts=[new FontFace('Field Serif',`url(${new URL('assets/essay-type/noto-serif-sc.woff2',import.meta.url).href})`,{weight:'400 600'}),new FontFace('Field Roman',`url(${new URL('assets/essay-type/cormorant-garamond.woff2',import.meta.url).href})`,{weight:'400 600'})];
 await Promise.all(fonts.map(async font=>{await font.load();document.fonts.add(font);}));
 h.css('essay.css');const e=h.escape,controller=new AbortController();
 let state={theme:'gold',seconds:5,time:3.6,playing:false,scenes:[{title:'提出命题',text:'一次演示，\n等于一件产品吗？'},{title:'找出边界',text:'能运行，只是起点。\n换一份输入，还能得到可靠结果吗？'},{title:'给出结论',text:'留下反馈，复用流程。\n让每一次创作，成为下一次的起点。'}]},raf=0,last=0,active=true,disposed=false,recording={phase:'idle',progress:0};
 const shotNames=['星空提问','工具类比','命题档案','边界之墙','反馈球体','两条成长曲线'],total=()=>state.seconds*6;
 const pointForShot=i=>state.scenes[i===2?0:Math.floor(i/2)],pointIndices=i=>i===2?[0,1]:[Math.floor(i/2)];
 const themes={gold:{bg:'#0b0e13',ink:'#f4edd6',accent:'#edc46f',muted:'#a7a496'},space:{bg:'#0a1225',ink:'#e9f2f4',accent:'#8ecce8',muted:'#8ca3b7'}};
 container.innerHTML=`<div class="essay-lab"><div class="essay-workbench"><aside class="lab-controls essay-controls"><h3>观点 → 论证镜头</h3><p>三段观点展开为六个镜头：命题纸页进入边界检验，检验记录送回反馈，再接到流程积累。</p><label class="lab-field">视觉主题<select data-setting="theme"><option value="gold">论证 · 黑金光线</option><option value="space">探索 · 深空蓝</option></select></label><label class="lab-field">每镜时长 <output data-seconds>5 秒</output><input data-setting="seconds" type="range" min="2" max="8" value="5"></label>${state.scenes.map((s,i)=>`<details class="essay-scene-field" ${i===0?'open':''}><summary>0${i+1} / ${e(s.title)}</summary><label>论证标题<input data-title="${i}" maxlength="25" value="${e(s.title)}"></label><label>观点与解释<textarea data-text="${i}" rows="3" maxlength="100">${e(s.text)}</textarea></label></details>`).join('')}</aside><div class="essay-stage-column"><div class="essay-screen"><canvas class="lab-canvas" width="1280" height="720" aria-label="观点论证的动画画面"></canvas><div class="essay-screen-caption"><span>FIELD SEMINAR / 03</span><span data-shot-name>星空提问</span></div></div><div class="essay-player"><button class="lab-button primary" data-play type="button">播放论证片</button><button class="lab-button" data-restart type="button">从头开始</button><span data-time></span></div><label class="essay-timeline">拖动检查镜头推进<input data-time-slider type="range" min="0" max="30" step="0.1" value="3.6"></label><div class="essay-chapters">${shotNames.map((name,i)=>`<button type="button" data-chapter="${i}"><span>0${i+1}</span><b>${name}</b></button>`).join('')}</div><div class="essay-exports"><button class="lab-button primary" type="button" data-export="webm">导出整片 WebM</button><button class="lab-button" type="button" data-cancel hidden>取消录制</button><button class="lab-button" type="button" data-export="png">导出当前 PNG</button><button class="lab-button" type="button" data-export="svg">导出 SVG（内嵌帧）</button><button class="lab-button" type="button" data-export="script">导出论证脚本</button></div><div class="essay-recording" aria-live="polite"><progress data-progress max="1" value="0" hidden></progress><span data-export-status>WebM 是完整的无声代码动画；录制耗时与片长相同。</span></div><p class="essay-scope">参考已观看的星空、档案、墙、球体与曲线。纸页保留命题，金色记录点串联检验、反馈与积累，这是本例的原创镜头设计；曲线非实测，原作工具链未知。</p></div></div></div>`;
 const root=container.querySelector('.essay-lab'),canvas=root.querySelector('canvas'),ctx=canvas.getContext('2d');
 function draw(){if(disposed)return;updatePlayer(renderEssay(ctx,state,themes[state.theme]));}
 function updatePlayer(shot=Math.min(5,Math.floor(state.time/state.seconds))){root.querySelector('[data-play]').textContent=state.playing?'暂停':'播放论证片';root.querySelector('[data-time]').textContent=`${state.time.toFixed(1)} / ${total()} 秒`;const slider=root.querySelector('[data-time-slider]');slider.max=total();slider.value=state.time;root.querySelector('[data-seconds]').textContent=state.seconds+' 秒';root.querySelector('[data-shot-name]').textContent=shotNames[shot];root.querySelectorAll('[data-chapter]').forEach((b,i)=>b.setAttribute('aria-pressed',String(i===shot)));const continuity=essaySequence(state).continuity;canvas.setAttribute('aria-label',`${shotNames[shot]}：${pointIndices(shot).map(i=>state.scenes[i].title+'，'+state.scenes[i].text).join('；下一步：')}${continuity?'；镜头接力：'+continuity.role:''}`);}
 function pause(){state.playing=false;if(raf)cancelAnimationFrame(raf);raf=0;last=0;updatePlayer();}
 function tick(now){raf=0;if(!active||disposed||!state.playing)return;state.time=Math.min(total(),state.time+(last?Math.min(.2,(now-last)/1000):0));last=now;draw();if(state.time>=total())pause();else raf=requestAnimationFrame(tick);}
 function play(){if(!active||disposed)return;if(state.time>=total())state.time=0;state.playing=true;last=0;raf=requestAnimationFrame(tick);updatePlayer();}
 function exportChange(info){recording=info;if(disposed)return;const busy=info.phase==='recording';root.querySelectorAll('input,select,textarea,[data-play],[data-restart],[data-chapter],[data-export]').forEach(el=>el.disabled=busy);root.querySelector('[data-cancel]').hidden=!busy;root.querySelector('[data-progress]').hidden=!busy;root.querySelector('[data-progress]').value=info.progress;root.querySelector('[data-export-status]').textContent=busy?`正在录制无声 WebM · ${Math.round(info.progress*100)}% · 请保持页面显示`:info.phase==='complete'?'整片 WebM 已生成，可在浏览器或播放器播放。':info.phase==='cancelled'?'录制已取消，未导出不完整视频。':info.error||'准备录制完整的无声代码动画。';if(!busy)h.onStatus(root.querySelector('[data-export-status]').textContent);}
 const movie=createMotionExport({canvas,getDuration:total,getTime:()=>state.time,setTime:t=>state.time=t,render:draw,onChange:exportChange,downloadFile:h.downloadFile});
 root.addEventListener('input',event=>{const target=event.target,value=target.value;pause();if(target.dataset.setting==='theme')state.theme=value;else if(target.dataset.setting==='seconds'){state.seconds=Number(value);state.time=Math.min(state.time,total());}else if(target.dataset.title!==undefined)state.scenes[Number(target.dataset.title)].title=value;else if(target.dataset.text!==undefined)state.scenes[Number(target.dataset.text)].text=value;else if(target.hasAttribute('data-time-slider'))state.time=Number(value);draw();},{signal:controller.signal});
 root.addEventListener('click',event=>{const b=event.target.closest('button');if(!b)return;if(b.hasAttribute('data-cancel'))movie.cancel();else if(b.hasAttribute('data-play'))state.playing?pause():play();else if(b.hasAttribute('data-restart')){pause();state.time=0;draw();}else if(b.dataset.chapter!==undefined){pause();state.time=Number(b.dataset.chapter)*state.seconds+.8;draw();}else if(b.dataset.export){pause();draw();const kind=b.dataset.export;if(kind==='webm')movie.start('研究观点-六镜论证.webm');else if(kind==='png')canvas.toBlob(blob=>{if(blob&&!disposed)h.downloadFile('研究观点-当前帧.png',blob,'image/png');});else if(kind==='svg')h.downloadFile('研究观点-当前帧.svg',`<svg xmlns="http://www.w3.org/2000/svg" width="1280" height="720"><image width="1280" height="720" href="${canvas.toDataURL('image/png')}"/></svg>`,'image/svg+xml');else h.downloadFile('研究观点-论证脚本.json',JSON.stringify({...state,sequence:essaySequence(state),continuityPlan:essayContinuityPlan,shots:shotNames.map((name,i)=>({name,start:i*state.seconds,duration:state.seconds,point:pointForShot(i),pointIndices:pointIndices(i),next:i===2?state.scenes[1]:null})),scope:'原创 Canvas 论证片，示意曲线非实测；原作工具链未知；WebM 无声'},null,2),'application/json');}},{signal:controller.signal});
 document.addEventListener('visibilitychange',()=>{if(document.hidden){pause();movie.cancel();}},{signal:controller.signal});draw();
 return {getState:()=>JSON.parse(JSON.stringify({...state,sequence:essaySequence(state),continuityPlan:essayContinuityPlan,totalSeconds:total(),currentScene:(Math.min(5,Math.floor(state.time/state.seconds))===2?0:Math.floor(Math.min(5,Math.floor(state.time/state.seconds))/2))+1,currentPointIndices:pointIndices(Math.min(5,Math.floor(state.time/state.seconds))),currentShot:Math.min(5,Math.floor(state.time/state.seconds))+1,exporting:movie.isExporting(),recording})),setActive(value){active=Boolean(value);if(!active){pause();movie.cancel();}},dispose(){disposed=true;pause();movie.dispose();controller.abort();root.remove();}};
}


