import {createMotionExport} from './motion-export.js';
import {renderLaunch} from './editorial-film.js';
import {initialEvidence,organizeEvidence,evidenceMarkdown} from './launch-evidence.js';
import {launchSequence,launchSequencePlan} from './launch-sequence.js';
import {launchTypographyState} from './launch-artwork.js';
export function mount(container,h){
 h.css('launch.css');const e=h.escape,controller=new AbortController(),clamp=(v,a=0,b=1)=>Math.max(a,Math.min(b,v));
 let state={product:'Archive',question:'这三个案例，怎样成为可用的研究材料？',evidenceText:initialEvidence,theme:'paper',time:3.2,playing:false,spring:.68,wave:.72,scenes:[{headline:'Observe.',detail:'保留原作观察与来源，成为一张研究卡。',seconds:5},{headline:'Connect.',detail:'相同记录合并，缺少来源留待补充。',seconds:7},{headline:'Keep it.',detail:'每条观察，保留它的来源。',seconds:3}]},raf=0,last=0,active=true,disposed=false,recording={phase:'idle',progress:0};
 const themes={paper:{bg:'#eeeae0',ink:'#151715',accent:'#ff5724',muted:'#75786f'},forest:{bg:'#dfe8d7',ink:'#163b2d',accent:'#ca592f',muted:'#637a62'},midnight:{bg:'#161823',ink:'#f2eee5',accent:'#ab96ec',muted:'#aaa9bc'}},total=()=>state.scenes.reduce((sum,s)=>sum+s.seconds,0);
 const names=['开启','巨型字标','弹性曲线','环形字','满幅点阵','留存成果'];
 container.innerHTML=`<div class="launch-lab"><div class="launch-workbench"><aside class="lab-controls launch-controls"><h3>画面与研究内容</h3><p>一个几何圆点贯穿开关、文字、弹性曲线、环形字和点阵；卖点直接进入真实镜头。</p><label class="lab-field">产品字标<input data-product maxlength="22" value="${e(state.product)}"></label><label class="lab-field">品牌主题<select data-theme><option value="paper">纸白 · 橙色圆点</option><option value="forest">浅绿 · 陶土</option><option value="midnight">午夜 · 紫色</option></select></label><label class="lab-field">弹性程度<input data-motion="spring" type="range" min="0" max="100" value="68"></label><label class="lab-field">点阵幅度<input data-motion="wave" type="range" min="0" max="100" value="72"></label>${state.scenes.map((s,i)=>`<details class="launch-scene-field"><summary>0${i+1} / ${['打开','能力','品牌'][i]}</summary><label>巨型标题<textarea data-headline="${i}" rows="2" maxlength="45">${e(s.headline)}</textarea></label><label>卖点说明<textarea data-detail="${i}" rows="2" maxlength="90">${e(s.detail)}</textarea></label><label>时长（秒）<input data-seconds="${i}" type="number" min="3" max="12" step="1" value="${s.seconds}"></label></details>`).join('')}</aside><div class="launch-stage-column"><div class="launch-screen"><canvas class="lab-canvas" width="1280" height="720" aria-label="几何动效发布片画面"></canvas><div class="launch-screen-caption"><span>GEOMETRY IN MOTION / 04</span><span data-effect>几何开关</span></div></div><div class="launch-player"><button class="lab-button primary" data-play type="button">播放发布片</button><button class="lab-button" data-restart type="button">从头开始</button><span data-clock></span></div><label class="launch-timeline">拖动查看图形怎样变成信息<input data-timeline type="range" min="0" max="15" step="0.1" value="1.2"></label><div class="launch-chapters">${names.map((name,i)=>`<button class="lab-button" type="button" data-scene="${i}"><span>0${i+1}</span><b>${name}</b></button>`).join('')}</div><div class="launch-exports"><button class="lab-button primary" data-export="webm" type="button">导出完整 WebM</button><button class="lab-button" data-cancel type="button" hidden>取消录制</button><button class="lab-button" data-export="png" type="button">导出当前 PNG</button><button class="lab-button" data-export="storyboard" type="button">导出动效分镜</button><button class="lab-button" data-export="json" type="button">导出发布片配方</button></div><div class="launch-recording" aria-live="polite"><progress data-progress max="1" value="0" hidden></progress><span data-export-status>WebM 为完整无声代码动画；录制用时等于片长。</span></div><p class="launch-scope">参考原作已观察的大字、开关、弹性曲线、环形字与点阵波。Canvas 绘制及 MediaRecorder 输出是我们的路线，原作具体工具链未知。</p></div></div></div>`;
 const root=container.querySelector('.launch-lab'),canvas=root.querySelector('canvas'),ctx=canvas.getContext('2d');
 let fontReady=false,fontError='';const displayFace=new FontFace('Launch Display','url('+new URL('../media/fonts/case-04/InterDisplay-Black.woff2',import.meta.url).href+')',{weight:'900',style:'normal'});
 displayFace.load().then(face=>{if(disposed)return;document.fonts.add(face);fontReady=true;draw();}).catch(error=>{fontError=error.message;if(!disposed)h.onStatus('显示字体加载失败，暂不能导出画面。');});

 root.querySelector('.launch-controls>p').textContent='字标、时间与研究记录都可编辑。原始观察与来源保留在成果区，主镜头留给字形、空间和橙点。';
 root.querySelectorAll('.launch-scene-field summary').forEach((s,i)=>s.textContent=`0${i+1} / ${['输入','图形转场','成果'][i]}`);
 root.querySelector('[data-theme]').closest('label').insertAdjacentHTML('afterend',`<details class="launch-evidence-field"><summary>演绎功能 / 证据整理</summary><label>研究问题<input data-question maxlength="60" value="${e(state.question)}"></label><label>研究卡（一行一条：观察 | 来源）<textarea data-evidence rows="7" maxlength="5000">${e(state.evidenceText)}</textarea></label><p data-evidence-summary></p><small>内容与来源完全相同才合并；缺来源留待补。不自动核实链接内容。</small></details>`);
 root.querySelector('.launch-exports').insertAdjacentHTML('afterbegin','<button class="lab-button primary" data-export="evidence" type="button">导出实际证据成果</button>');
 root.querySelector('.launch-exports').insertAdjacentHTML('afterend','<details class="launch-evidence-result"><summary>成片实际整理了什么</summary><div data-evidence-result></div></details>');
 let evidenceKey='';
 function updateEvidence(pack){const key=state.question+'\n'+state.evidenceText;if(key===evidenceKey)return;evidenceKey=key;root.querySelector('[data-evidence-summary]').textContent=`${pack.inputCount} 条输入 → ${pack.includedCount} 条纳入 · ${pack.mergedCount} 条重复合并 · ${pack.pendingCount} 条待补`;root.querySelector('[data-evidence-result]').innerHTML=`<p>${e(pack.question)}</p><ul>${pack.included.map(r=>`<li>${e(r.claim)}<br><a href="${e(r.source)}" target="_blank" rel="noreferrer">${e(r.source)}</a></li>`).join('')||'<li>暂无有来源的观察。</li>'}</ul><p>待补 ${pack.pendingCount} 条</p><ul>${pack.pending.map(r=>`<li>${e(r.claim||'补充观察内容')} · ${e(r.reason)}</li>`).join('')||'<li>暂无待补。</li>'}</ul>`;}
 function frame(){let start=0,index=2;for(let i=0;i<3;i++){if(state.time<start+state.scenes[i].seconds||i===2){index=i;break;}start+=state.scenes[i].seconds;}const local=state.time-start,p=clamp(local/state.scenes[index].seconds);const effect=index===0?(p<.34?0:1):index===1?(p<.4?2:p<.76?3:4):5,range=effect===0?[0,.34]:effect===1?[.34,1]:effect===2?[0,.4]:effect===3?[.4,.76]:effect===4?[.76,1]:[0,1],effectStart=start+range[0]*state.scenes[index].seconds,effectDuration=(range[1]-range[0])*state.scenes[index].seconds,effectProgress=clamp((state.time-effectStart)/effectDuration);const workflow=organizeEvidence(state.evidenceText,state.question),typography=launchTypographyState(ctx,state);return{index,start,local,p,effect,effectStart,effectDuration,effectProgress,scene:state.scenes[index],theme:themes[state.theme],workflow,typography,sequence:launchSequence(state,workflow,typography)};}
 function draw(){if(disposed)return;const f=frame();renderLaunch(ctx,state,f,total());updateEvidence(f.workflow);updatePlayer(f);}
 function updatePlayer(f=frame()){root.querySelector('[data-play]').textContent=state.playing?'暂停':'播放发布片';root.querySelector('[data-clock]').textContent=`${state.time.toFixed(1)} / ${total()} 秒`;const slider=root.querySelector('[data-timeline]');slider.max=total();slider.value=state.time;root.querySelector('[data-effect]').textContent=f.sequence.phase==='complete'?'成果保留 · 整理结束':f.sequence.phase==='closing'?'关闭整理 · 成果可导出':names[f.effect];root.querySelectorAll('[data-scene]').forEach((b,i)=>b.setAttribute('aria-pressed',String(i===f.effect)));const pack=f.workflow||organizeEvidence(state.evidenceText,state.question),content=f.effect===1?pack.records[0]?.claim||'暂无输入':f.effect===5?pack.included.map(r=>r.claim).join('；'):f.scene.detail;canvas.setAttribute('aria-label',`${names[f.effect]} / ${f.sequence.phase}：${f.scene.headline}。${f.scene.detail}。${pack.inputCount} 条输入，${pack.includedCount} 条纳入，${pack.mergedCount} 条合并，${pack.pendingCount} 条待补。${content}`);}
 function pause(){state.playing=false;if(raf)cancelAnimationFrame(raf);raf=0;last=0;updatePlayer();}
 function tick(now){raf=0;if(!active||disposed||!state.playing)return;state.time=Math.min(total(),state.time+(last?Math.min(.2,(now-last)/1000):0));last=now;draw();if(state.time>=total())pause();else raf=requestAnimationFrame(tick);}
 function play(){if(!active||disposed)return;if(state.time>=total())state.time=0;state.playing=true;last=0;raf=requestAnimationFrame(tick);updatePlayer();}
 function exportChange(info){recording=info;if(disposed)return;const busy=info.phase==='recording';root.querySelectorAll('input,select,textarea,[data-play],[data-restart],[data-scene],[data-export]').forEach(el=>el.disabled=busy);root.querySelector('[data-cancel]').hidden=!busy;root.querySelector('[data-progress]').hidden=!busy;root.querySelector('[data-progress]').value=info.progress;root.querySelector('[data-export-status]').textContent=busy?`正在录制完整无声 WebM · ${Math.round(info.progress*100)}% · 保持页面显示`:info.phase==='complete'?'完整 WebM 已生成，可直接播放。':info.phase==='cancelled'?'录制已取消，未导出不完整视频。':info.error||'准备录制完整无声动画。';if(!busy)h.onStatus(root.querySelector('[data-export-status]').textContent);}
 const movie=createMotionExport({canvas,getDuration:total,getTime:()=>state.time,setTime:t=>state.time=t,render:draw,onChange:exportChange,downloadFile:h.downloadFile});
 function storyboard(){let start=0;return `# ${state.product} · 功能动效发布分镜\n\n${state.scenes.map((s,i)=>{const from=start;start+=s.seconds;return `## ${i+1} / ${from}–${start} 秒\n\n标题：${s.headline}\n\n卖点：${s.detail}\n\n画面：${['几何开关开启本地整理，同一圆点进入巨大产品字标；首条真实观察作为画面注记','弹性曲线、环形字、点阵波保留连续圆点接力','实际记录标记移入成果，重复合并，缺来源留待补；巨大成果标题收拢并关闭整理，完整记录仍可导出'][i]}\n`;}).join('\n')}\n弹性：${state.spring}；点阵幅度：${state.wave}。\n\n## 首尾同一时间轴\n\n${launchSequencePlan(state).map(step=>`${step.start.toFixed(2)}–${step.end.toFixed(2)} 秒：${step.action}`).join('\n')}\n\n## 同一输入对应的实际成果\n\n${evidenceMarkdown(organizeEvidence(state.evidenceText,state.question))}\n原创 Canvas + MediaRecorder 无声 WebM；原作具体工具链未知。`;}
 root.addEventListener('input',event=>{const target=event.target,value=target.value;pause();if(target.hasAttribute('data-product'))state.product=value;else if(target.hasAttribute('data-question'))state.question=value;else if(target.hasAttribute('data-evidence'))state.evidenceText=value;else if(target.hasAttribute('data-theme'))state.theme=value;else if(target.dataset.motion)state[target.dataset.motion]=Number(value)/100;else if(target.dataset.headline!==undefined)state.scenes[Number(target.dataset.headline)].headline=value;else if(target.dataset.detail!==undefined)state.scenes[Number(target.dataset.detail)].detail=value;else if(target.dataset.seconds!==undefined){const i=Number(target.dataset.seconds),v=Number(value);state.scenes[i].seconds=Number.isFinite(v)&&v>=3?Math.min(12,Math.round(v)):3;state.time=Math.min(state.time,total());}else if(target.hasAttribute('data-timeline'))state.time=Number(value);draw();},{signal:controller.signal});
 root.addEventListener('click',event=>{const b=event.target.closest('button');if(!b)return;if(b.hasAttribute('data-cancel'))movie.cancel();else if(b.hasAttribute('data-play'))state.playing?pause():play();else if(b.hasAttribute('data-restart')){pause();state.time=0;draw();}else if(b.dataset.scene!==undefined){pause();const i=Number(b.dataset.scene),a=state.scenes[0].seconds,c=state.scenes[1].seconds;state.time=[a*.16,a*.65,a+c*.2,a+c*.58,a+c*.88,a+c+state.scenes[2].seconds*.4][i];draw();}else if(b.dataset.export){if(['png','webm'].includes(b.dataset.export)&&!fontReady)return;pause();draw();if(b.dataset.export==='evidence'){const pack=organizeEvidence(state.evidenceText,state.question);h.downloadFile(pack.filename,evidenceMarkdown(pack),'text/markdown');}else if(b.dataset.export==='webm')movie.start('研究工作台-几何动效.webm');else if(b.dataset.export==='png')canvas.toBlob(blob=>{if(blob&&!disposed)h.downloadFile('研究工作台-动效当前帧.png',blob,'image/png');});else if(b.dataset.export==='storyboard')h.downloadFile('研究工作台-动效分镜.md',storyboard(),'text/markdown');else h.downloadFile('研究工作台-动效配方.json',JSON.stringify({...state,playing:false,totalSeconds:total(),effects:names,workflow:frame().workflow,sequence:frame().sequence,sequencePlan:launchSequencePlan(state),typography:frame().typography,fontReady,scope:'原创无声 Canvas / WebM；Inter Display Black 为本地 OFL 字体，原作字型与工具链未知'},null,2),'application/json');}},{signal:controller.signal});
 document.addEventListener('visibilitychange',()=>{if(document.hidden){pause();movie.cancel();}},{signal:controller.signal});draw();
 return {getState:()=>JSON.parse(JSON.stringify({...state,workflow:frame().workflow,sequence:frame().sequence,sequencePlan:launchSequencePlan(state),totalSeconds:total(),fontReady,fontError,typography:frame().typography,currentScene:frame().index+1,currentEffect:names[frame().effect],effectProgress:frame().effectProgress,effectDuration:frame().effectDuration,exporting:movie.isExporting(),recording})),setActive(value){active=Boolean(value);if(!active){pause();movie.cancel();}},dispose(){disposed=true;pause();movie.dispose();controller.abort();root.remove();}};
}



