// Original CASE 04 motion artwork. Reference frames guide composition, not a claimed source toolchain.
const W=1280,H=720,TAU=Math.PI*2,clamp=v=>Math.max(0,Math.min(1,v));
const ease=v=>{v=clamp(v);return v*v*(3-2*v);},mix=(a,b,p)=>a+(b-a)*p;
const tint=(a,b,p)=>'#'+[1,3,5].map(i=>Math.round(mix(parseInt(a.slice(i,i+2),16),parseInt(b.slice(i,i+2),16),clamp(p))).toString(16).padStart(2,'0')).join('');
const FACE="'Launch Display','Microsoft YaHei',sans-serif";
function disk(c,x,y,r,color){c.fillStyle=color;c.beginPath();c.arc(x,y,Math.max(0,r),0,TAU);c.fill();}
function line(c,ps,color,w=1){c.strokeStyle=color;c.lineWidth=w;c.beginPath();ps.forEach((p,i)=>i?c.lineTo(...p):c.moveTo(...p));c.stroke();}
function copy(c,text,x,y,size,color,{center=false,align='left',weight=500,width=1100,font="Arial,'Microsoft YaHei',sans-serif"}={}){c.font=`${weight} ${size}px ${font}`;while(c.measureText(String(text)).width>width&&size>10)c.font=`${weight} ${--size}px ${font}`;c.textAlign=center?'center':align;c.fillStyle=color;c.fillText(text,x,y);c.textAlign='left';}
function capsule(c,x,y,w,h,color,stroke){c.beginPath();c.roundRect(x,y,w,h,h/2);if(color){c.fillStyle=color;c.fill();}if(stroke){c.strokeStyle=stroke;c.lineWidth=3;c.stroke();}}
function typeLayout(c,state){const word=state.product.trim()||'Archive';let size=300;c.font=`900 ${size}px ${FACE}`;while(c.measureText(word).width>1120&&size>48)c.font=`900 ${--size}px ${FACE}`;const width=c.measureText(word).width,x=(W-width)/2,y=548,index=[...word].findIndex(ch=>ch==='i'||ch==='j');const prefix=index>=0?[...word].slice(0,index).join(''):word;const dotX=index>=0?x+c.measureText(prefix).width+c.measureText([...word][index]).width/2:W/2;const body=c.measureText('n').actualBoundingBoxAscent||size*.55,r=Math.max(22,size*.105),dotY=index>=0?y-body-size*.18:y-(c.measureText(word).actualBoundingBoxAscent||size*.75)-r*1.8;return{word,size,width,x,y,index,dot:{x:dotX,y:dotY,r}};}
function drawWord(c,l,ink,bg){c.font=`900 ${l.size}px ${FACE}`;c.fillStyle=ink;const chars=[...l.word];let prefix='';for(let i=0;i<chars.length;i++){const x=l.x+c.measureText(prefix).width;c.save();if(i===l.index){const body=c.measureText('n').actualBoundingBoxAscent||l.size*.55;c.beginPath();c.rect(x-3,l.y-body-3,c.measureText(chars[i]).width+6,body+15);c.clip();}c.fillText(chars[i],x,l.y);c.restore();prefix+=chars[i];}}
function opening(c,state,f,t,l){const q=f.sequence,open=q.knob.on,handoff=q.input;const base={x:mix(456,824,open),y:335,r:112};c.save();c.globalAlpha=1-handoff;capsule(c,318,197,644,276,tint(t.bg,t.accent,open),t.accent);disk(c,base.x,base.y,112,tint(t.accent,t.bg,open));c.restore();if(handoff){c.save();c.globalAlpha=handoff;drawWord(c,l,t.ink,t.bg);c.restore();disk(c,mix(base.x,l.dot.x,handoff),mix(base.y,l.dot.y,handoff),mix(112,l.dot.r,handoff),tint(t.bg,t.accent,handoff));}}
function typography(c,state,f,t,l){drawWord(c,l,t.ink,t.bg);disk(c,l.dot.x,l.dot.y,l.dot.r,t.accent);const record=f.workflow.records[0];if(record){copy(c,`01 / ${record.claim||'待补观察'}`,76,656,18,t.muted,{width:930});copy(c,record.status==='needs-source'?'来源待补':'来源已保留',1204,656,15,t.muted,{align:'right',width:180});}else copy(c,'写下第一条观察。',76,656,18,t.muted);}
function curve(c,state,f,t,l){const p=f.effectProgress,handoff=ease(p/.17),spring=x=>1-Math.exp(-7*x)*Math.cos((8+state.spring*12)*x),x0=230,y0=537,span=865,height=289,u=clamp((p-.17)/.58),bridge=ease((p-.79)/.21);if(handoff<1){c.save();c.globalAlpha=1-handoff;drawWord(c,l,t.ink,t.bg);c.restore();}c.save();c.globalAlpha=handoff*(1-bridge);line(c,[[x0,143],[x0,y0],[1110,y0]],t.ink,2.4);c.save();c.setLineDash([10,9]);line(c,[[x0,y0-height],[1100,y0-height]],t.muted,1.7);c.restore();const points=[];for(let i=0;i<=230*u;i++){const a=i/230;points.push([x0+a*span,y0-spring(a)*height]);}line(c,points,t.ink,3);for(let i=0;i<=9*u;i++){const a=i/9;disk(c,x0+a*span,y0-spring(a)*height,4,t.ink);}c.restore();const dot={x:x0+u*span,y:y0-spring(u)*height};disk(c,mix(mix(l.dot.x,dot.x,handoff),640,bridge),mix(mix(l.dot.y,dot.y,handoff),360,bridge),mix(mix(l.dot.r,27,handoff),35,bridge),t.accent);}
function orbit(c,state,f,t){const p=f.effectProgress,intro=ease(p/.13),out=ease((p-.83)/.17),phrase=`RESEARCH · ${state.scenes[0].headline} · ${state.scenes[1].headline} · ${state.product} · `.toUpperCase(),chars=[...phrase];c.font=`900 101px ${FACE}`;const widths=chars.map(ch=>c.measureText(ch).width),sum=widths.reduce((a,b)=>a+b,0);let pos=0;const tilt=.77,rx=425,depth=218,rot=-state.time*.52;const glyphs=chars.map((ch,i)=>{const a=(pos+widths[i]/2)/sum*TAU+rot;pos+=widths[i];const x=rx*Math.sin(a),z=depth*Math.cos(a),scale=770/(770-z),y=365+z*tilt*scale;return{ch,a,x,z,scale,y};}).sort((a,b)=>a.z-b.z);
 for(const g of glyphs){c.save();c.translate(640+g.x*g.scale*intro,mix(360,g.y,intro));const tangent=Math.cos(g.a),sx=Math.sign(tangent)*Math.max(.055,Math.abs(tangent))*g.scale;const slope=-depth*Math.sin(g.a)*tilt/(rx*(Math.abs(tangent)<.05?.05:tangent));c.transform(sx,slope*sx,0,g.scale,0,0);c.globalAlpha=(g.z<0?.28:1)*intro*(1-out);c.fillStyle=t.ink;c.font=`900 101px ${FACE}`;c.textAlign='center';c.fillText(g.ch,0,0);c.restore();}disk(c,640,360,mix(35,20,out),t.accent);}
function grid(c,state,f,t){const p=f.effectProgress,enter=ease(p/.13),leave=ease((p-.82)/.18),wave=state.wave,step=34,cx=640,cy=360,ring=122+p*140;for(let y=-1;y<23;y++)for(let x=-1;x<40;x++){const px=x*step+11,py=y*step+3,dist=Math.hypot(px-cx,py-cy),pulse=Math.exp(-Math.pow((dist-ring)/69,2)),ripple=Math.sin(dist*.022-p*TAU*1.5)*wave*7*enter,rad=(2.65+pulse*10.5*wave)*enter*(1-leave);disk(c,px+(px-cx)/Math.max(1,dist)*ripple,py+(py-cy)/Math.max(1,dist)*ripple,rad,t.ink);}disk(c,640,360,20,t.accent);}
function result(c,state,f,t){const p=f.effectProgress,pack=f.workflow,merge=ease(p/.30),fold=f.sequence.fold,close=f.sequence.close;const word=state.scenes[2].headline.replaceAll('\n','').trim()||'留存。';
 if(f.sequence.phase==='folding'||f.sequence.phase==='closing'||f.sequence.phase==='complete'){const k=f.sequence.knob;c.save();c.globalAlpha=1-fold;copy(c,word,640,390,166,t.ink,{center:true,weight:900,font:FACE,width:1080});c.restore();c.save();c.globalAlpha=fold;capsule(c,318,197,644,276,tint(t.accent,t.bg,close),t.accent);c.restore();disk(c,k.x,k.y,k.radius,tint(t.accent,t.bg,fold*(1-close)));if(close>.94){copy(c,state.product||'Archive',640,586,38,t.ink,{center:true,weight:900,font:FACE});copy(c,`${pack.includedCount} 条观察 · 成果可导出`,640,628,19,t.muted,{center:true});}return;}
 // Record marks follow the actual input classification and exact-duplicate IDs.
 const shown=pack.records.slice(0,14);shown.forEach((r,i)=>{const kept=pack.included.findIndex(v=>v.id===(r.duplicateOf||r.id)),pending=pack.pending.findIndex(v=>v.id===r.id),a=i/Math.max(1,shown.length)*TAU,spread=ease(p/.1),start={x:640+Math.cos(a)*264*spread,y:360+Math.sin(a)*163*spread},target=r.status==='needs-source'?{x:100,y:574+Math.min(pending,4)*17}:{x:530+Math.min(kept,6)*94,y:503};const alpha=r.status==='merged'?1-ease((merge-.47)/.35):1;c.save();c.globalAlpha=alpha*(1-fold);disk(c,mix(start.x,target.x,merge),mix(start.y,target.y,merge),mix(20,r.status==='needs-source'?6:14,spread),t.accent);c.restore();});
 c.save();c.globalAlpha=ease(p/.17);copy(c,word,640,367,166,t.ink,{center:true,weight:900,font:FACE,width:1090});copy(c,state.scenes[2].detail,640,439,23,t.muted,{center:true,width:1040});c.restore();copy(c,`${pack.includedCount} KEEP   /   ${pack.mergedCount} MERGED   /   ${pack.pendingCount} TO COMPLETE`,640,625,16,t.muted,{center:true});}
export function renderLaunchArtwork(c,state,f,total){const t=f.theme,dark=f.effect===2?ease((f.effectProgress-.79)/.21):f.effect===3?1-ease((f.effectProgress-.83)/.17):0,theme={...t,bg:tint(t.bg,t.ink,dark),ink:tint(t.ink,t.bg,dark),muted:tint(t.muted,t.bg,dark*.4)};c.fillStyle=theme.bg;c.fillRect(0,0,W,H);const l=typeLayout(c,state);if(f.effect===0)opening(c,state,f,theme,l);else if(f.effect===1)typography(c,state,f,theme,l);else if(f.effect===2)curve(c,state,f,theme,l);else if(f.effect===3)orbit(c,state,f,theme);else if(f.effect===4)grid(c,state,f,theme);else result(c,state,f,theme);return f.effect;}
export function launchTypographyState(c,state){const l=typeLayout(c,state);return{font:'Inter Display Black',fontVersion:'Version 4.001;git-9221beed3',localFont:'media/fonts/case-04/InterDisplay-Black.woff2',license:'SIL Open Font License 1.1 / media/fonts/case-04/OFL.txt',word:l.word,size:l.size,width:l.width,baseline:l.y,dot:l.dot,layout:'oversized-type / quiet-curve / depth-sorted-orbit / full-bleed-grid',scope:'Original local art direction; the reference font and production toolchain are unknown.'};}
