import {T,createStage,solid,box,lightScene,clamp,synth} from './four-playable-stage.js';
import {sampleField,transformNormal} from './mascot-deformation.js';

// Smooth implicit unions create one closed outer skin, without sphere-on-sphere seams.
function partField(part,x,y,z){const c=Math.cos(part.angle||0),s=Math.sin(part.angle||0),dx=x-part.center[0],dy=y-part.center[1],lx=(c*dx+s*dy)/part.radii[0],ly=(-s*dx+c*dy)/part.radii[1],lz=(z-part.center[2])/part.radii[2];if(part.cone){const r=Math.sqrt(Math.max(.006,1-ly*ly))*(.72-.45*clamp(ly,-1,1));return Math.max((Math.hypot(lx,lz)/r-1)*Math.min(part.radii[0],part.radii[2]),(Math.abs(ly)-1)*part.radii[1]);}const power=part.power||2;return ((Math.abs(lx)**power+Math.abs(ly)**power+Math.abs(lz)**power)**(1/power)-1)*Math.min(...part.radii);}
function continuousSkin(parts,bounds,step=.085){
 const count=bounds.map(([a,b])=>Math.ceil((b-a)/step)+1),[nx,ny,nz]=count,points=[],values=new Float32Array(nx*ny*nz),id=(x,y,z)=>(z*ny+y)*nx+x;
 const field=(x,y,z)=>{let v=Infinity;for(const part of parts){const b=partField(part,x,y,z),k=.16,h=Math.max(k-Math.abs(v-b),0)/k;v=Math.min(v,b)-h*h*k*.25;}return Math.max(v,.015-y);};
 for(let z=0;z<nz;z++)for(let y=0;y<ny;y++)for(let x=0;x<nx;x++){const p=[bounds[0][0]+x*(bounds[0][1]-bounds[0][0])/(nx-1),bounds[1][0]+y*(bounds[1][1]-bounds[1][0])/(ny-1),bounds[2][0]+z*(bounds[2][1]-bounds[2][0])/(nz-1)],n=id(x,y,z);points[n]=p;values[n]=field(...p);}
 const positions=[],indices=[],edges=new Map(),tets=[[0,5,1,6],[0,1,2,6],[0,2,3,6],[0,3,7,6],[0,7,4,6],[0,4,5,6]];
 function edge(a,b){const key=a<b?a+':'+b:b+':'+a;if(edges.has(key))return edges.get(key);const t=values[a]/(values[a]-values[b]),p=points[a],q=points[b],n=positions.length/3;positions.push(p[0]+(q[0]-p[0])*t,p[1]+(q[1]-p[1])*t,p[2]+(q[2]-p[2])*t);edges.set(key,n);return n;}
 function triangle(a,b,c){const p=positions.slice(a*3,a*3+3),q=positions.slice(b*3,b*3+3),r=positions.slice(c*3,c*3+3),ux=q[0]-p[0],uy=q[1]-p[1],uz=q[2]-p[2],vx=r[0]-p[0],vy=r[1]-p[1],vz=r[2]-p[2],x=(p[0]+q[0]+r[0])/3,y=(p[1]+q[1]+r[1])/3,z=(p[2]+q[2]+r[2])/3,e=.002,gx=field(x+e,y,z)-field(x-e,y,z),gy=field(x,y+e,z)-field(x,y-e,z),gz=field(x,y,z+e)-field(x,y,z-e);if((uy*vz-uz*vy)*gx+(uz*vx-ux*vz)*gy+(ux*vy-uy*vx)*gz<0)[b,c]=[c,b];indices.push(a,b,c);}
 for(let z=0;z<nz-1;z++)for(let y=0;y<ny-1;y++)for(let x=0;x<nx-1;x++){const cube=[id(x,y,z),id(x+1,y,z),id(x+1,y+1,z),id(x,y+1,z),id(x,y,z+1),id(x+1,y,z+1),id(x+1,y+1,z+1),id(x,y+1,z+1)];for(const tet of tets){const inside=[],outside=[];for(const k of tet)(values[cube[k]]<=0?inside:outside).push(cube[k]);if(!inside.length||!outside.length)continue;if(inside.length===2){const [a,b]=inside,[c,d]=outside,ac=edge(a,c),ad=edge(a,d),bc=edge(b,c),bd=edge(b,d);triangle(ac,ad,bc);triangle(ad,bd,bc);}else{const one=inside.length===1?inside[0]:outside[0],others=inside.length===1?outside:inside;triangle(...others.map(n=>edge(one,n)));}}}
 const normals=[];for(let i=0;i<positions.length;i+=3){const x=positions[i],y=positions[i+1],z=positions[i+2],e=.003,n=new T.Vector3(field(x+e,y,z)-field(x-e,y,z),field(x,y+e,z)-field(x,y-e,z),field(x,y,z+e)-field(x,y,z-e)).normalize();normals.push(n.x,n.y,n.z);}const geometry=new T.BufferGeometry();geometry.setAttribute('position',new T.Float32BufferAttribute(positions,3));geometry.setAttribute('normal',new T.Float32BufferAttribute(normals,3));geometry.setIndex(indices);geometry.computeBoundingSphere();geometry.userData.surfaceField=field;
 const connections=new Map();for(let i=0;i<indices.length;i+=3)for(let j=0;j<3;j++){const a=indices[i+j],b=indices[i+(j+1)%3],key=a<b?a+':'+b:b+':'+a;connections.set(key,(connections.get(key)||0)+1);}geometry.userData.openEdges=[...connections.values()].filter(n=>n!==2).length;return geometry;
}
function skinVolume(positions,indices,directions,coefficient=0){let sum=0;for(let i=0;i<indices.length;i+=3){const a=indices[i]*3,b=indices[i+1]*3,c=indices[i+2]*3,ax=positions[a]+(directions?.[a]||0)*coefficient,ay=positions[a+1]+(directions?.[a+1]||0)*coefficient,az=positions[a+2]+(directions?.[a+2]||0)*coefficient,bx=positions[b]+(directions?.[b]||0)*coefficient,by=positions[b+1]+(directions?.[b+1]||0)*coefficient,bz=positions[b+2]+(directions?.[b+2]||0)*coefficient,cx=positions[c]+(directions?.[c]||0)*coefficient,cy=positions[c+1]+(directions?.[c+1]||0)*coefficient,cz=positions[c+2]+(directions?.[c+2]||0)*coefficient;sum+=ax*(by*cz-bz*cy)+ay*(bz*cx-bx*cz)+az*(bx*cy-by*cx);}return Math.abs(sum/6);}
// Slow frames change the number of integration steps, never the spring's wall-clock duration.
function mascotLoop(step,draw,needed,onFrame){let raf=0,last=null,active=true,disposed=false;const controller=new AbortController();function tick(t){raf=0;if(disposed||!active||document.hidden||!needed()){last=null;return;}const elapsed=Math.max(0,(t-last)/1000);last=t;let remaining=elapsed;while(remaining>1e-8){const dt=Math.min(1/120,remaining);step(dt);remaining-=dt;}onFrame(elapsed);draw();start();}function start(){if(!raf&&!disposed&&active&&!document.hidden&&needed()){if(last===null)last=performance.now();raf=requestAnimationFrame(tick);}}function stop(){cancelAnimationFrame(raf);raf=0;last=null;}document.addEventListener('visibilitychange',()=>document.hidden?stop():start(),{signal:controller.signal});return {start,stop,get active(){return active&&!document.hidden&&!disposed;},setActive(v){active=Boolean(v);if(active)start();else stop();},dispose(){disposed=true;active=false;stop();controller.abort();}};}
export function mount(container,h){
 h.css('mascot.css');const ctrl=new AbortController(),signal=ctrl.signal,audio=synth(),shell=document.createElement('section');shell.className='lab-demo mascot-lab';
 const specs=[{id:'rabbit',name:'粉兔',color:'#f185b2',x:-3.1},{id:'dumpling',name:'橙团',color:'#ff9e70',x:0},{id:'cat',name:'薄荷猫',color:'#51dbba',x:3.1}];
 shell.innerHTML='<div class="mascot-heading"><div><span>SOFT DESK / 立体触碰沙盒</span><h3>戳一下，看它变软、回弹</h3></div><b data-mascot-pokes>0 次触碰</b></div><div class="mascot-viewport"><canvas class="lab-canvas mascot-canvas" tabindex="0" aria-label="原创立体软萌角色。轻戳或拖揉角色，拖动背景转动视角。数字键1到3轻戳不同角色"></canvas><div class="mascot-scene-copy"><b>poke. stretch. bounce.</b><span data-mascot-renderer></span></div><div class="mascot-feel" data-mascot-feel>先开启角色触碰</div></div><div class="mascot-character-controls">'+specs.map(c=>'<button class="lab-button" data-mascot-character="'+c.id+'" aria-pressed="'+(c.id==='rabbit')+'">'+c.name+'</button>').join('')+'<button class="lab-button primary" data-mascot-poke>轻戳当前角色</button></div><div class="mascot-settings"><label class="lab-field">柔软度 <output data-mascot-softness-value>65%</output><input type="range" min="10" max="100" value="65" data-mascot-softness></label><label class="mascot-check"><input type="checkbox" checked data-mascot-gravity>重力与落地回弹</label><button class="lab-button" data-mascot-sound aria-pressed="true">声音：开</button><div class="mascot-view"><button class="lab-button" data-mascot-view="-1">视角 ←</button><button class="lab-button" data-mascot-view="1">视角 →</button></div></div><div class="mascot-mode"><label class="lab-field">体验方式<select data-mascot-mode><option value="sandbox">角色触碰沙盒</option><option value="challenge">我们的可选扩展：30 秒连击</option></select></label><p>默认没有输赢，观察真实网格形变、材质高光和弹跳。连击规则是我们新增的扩展。</p></div><div class="mascot-challenge" data-mascot-challenge hidden><span>命中 <b data-mascot-hits>0 / 12</b></span><span>连击 <b data-mascot-combo>0</b></span><span>时间 <b data-mascot-time>30 秒</b></span><span>目标 <b data-mascot-target>粉兔</b></span></div><p class="mascot-rule">点角色轻戳 · 按住角色拖揉 · 拖背景转视角 · 1 / 2 / 3 轻戳。手机使用角色与轻戳按钮，窄屏显示当前角色。</p><div class="lab-controls"><button class="lab-button primary" data-mascot-start>开启角色触碰</button><button class="lab-button" data-mascot-reset>重置角色</button><button class="lab-button" data-mascot-export>导出触碰记录 JSON</button></div><p class="lab-status" role="status" data-mascot-status>原创角色用程序化网格制作，局部凹陷与弹簧回弹是近似形变。参考原作软胶触碰效果，不宣称复现其混合、黏液或完整软体求解器。</p>';container.append(shell);const q=s=>shell.querySelector(s),stage=createStage(q('canvas'),{background:'#f5edf4',fov:43}),canvas=stage.canvas,models=[],ray=stage.supported?new T.Raycaster():null;let state,envTarget,drag=null,lastPoke=-1;const defaultPixelRatio=stage.supported?stage.renderer.getPixelRatio():1;
 const say=t=>{q('[data-mascot-status]').textContent=t;h.onStatus(t);};
 if(stage.supported){
  stage.renderer.toneMappingExposure=1.05;const key=lightScene(stage,{sky:'#fff7fb',ground:'#eed9e7',power:.85,sun:1.15});key.position.set(-3,8,5);key.shadow.camera.left=-7;key.shadow.camera.right=7;key.shadow.camera.top=7;key.shadow.camera.bottom=-7;key.shadow.mapSize.set(1024,1024);key.shadow.normalBias=.012;key.shadow.radius=4;stage.renderer.shadowMap.type=T.PCFSoftShadowMap;stage.scene.add(box(80,.1,80,'#faf3f7',0,-.08,0,{roughness:.85}));
  const positions=[],indices=[];for(let row=0;row<20;row++){const a=Math.min(Math.PI/2,row/16*Math.PI/2),y=row<=16?4*(1-Math.cos(a)):4+(row-16)*3,z=-4-4*Math.sin(a);positions.push(-30,y,z,30,y,z);if(row<19){const n=row*2;indices.push(n,n+1,n+2,n+1,n+3,n+2);}}const backdrop=new T.BufferGeometry();backdrop.setAttribute('position',new T.Float32BufferAttribute(positions,3));backdrop.setIndex(indices);backdrop.computeVertexNormals();const sweep=solid(backdrop,'#faf3f7',{roughness:.8,side:T.DoubleSide});sweep.castShadow=false;stage.scene.add(sweep);
  const fill=new T.DirectionalLight('#effffb',.65);fill.position.set(4,5,3);stage.scene.add(fill);const rim=new T.DirectionalLight('#fff0f3',.4);rim.position.set(1,6,-4);stage.scene.add(rim);
  const env=new T.Scene();env.background=new T.Color('#eddfeb');for(const [x,y,z,w,hh,d] of [[-4,4,5,4,6,.1],[5,5,2,2,5,.1],[0,8,-1,6,.1,4]]){const m=new T.Mesh(new T.BoxGeometry(w,hh,d),new T.MeshBasicMaterial({color:'#fffafc'}));m.position.set(x,y,z);env.add(m);}const pmrem=new T.PMREMGenerator(stage.renderer);envTarget=pmrem.fromScene(env,.1);stage.scene.environment=envTarget.texture;pmrem.dispose();env.traverse(o=>{o.geometry?.dispose();o.material?.dispose();});
  function gummy(geometry,color,transmission=0){const m=new T.Mesh(geometry,new T.MeshPhysicalMaterial({color,roughness:.23,metalness:0,clearcoat:.8,clearcoatRoughness:.14,envMapIntensity:.85,transmission,thickness:.75,ior:1.37,attenuationColor:new T.Color(color),attenuationDistance:3}));m.castShadow=true;m.receiveShadow=true;return m;}
  function ellipse(group,model,x,y,z,rx,ry,rz,color){const m=gummy(new T.SphereGeometry(1,24,18),color);m.position.set(x,y,z);m.scale.set(rx,ry,rz);m.userData.characterId=model.id;group.add(m);return m;}
  function gel(group,model,parts,bounds){const geometry=continuousSkin(parts,bounds),mesh=gummy(geometry,model.color,.035),rest=new Float32Array(geometry.attributes.position.array),partIds=new Uint8Array(rest.length/3);mesh.userData.characterId=model.id;group.add(mesh);for(const part of parts){const frame=new T.Object3D();frame.position.fromArray(part.center);frame.scale.fromArray(part.radii);frame.rotation.z=part.angle||0;frame.updateMatrix();group.add(frame);model.soft.push({mesh:frame,point:new T.Vector3(0,0,1),role:part.role,part,toLocal:frame.matrix.clone().invert()});}for(let i=0;i<partIds.length;i++){let best=Infinity;parts.forEach((p,j)=>{const value=partField(p,rest[i*3],rest[i*3+1],rest[i*3+2]);if(value<best){best=value;partIds[i]=j;}});}if(parts.some(p=>p.color)){const colors=new Float32Array(rest.length),base=new T.Color(model.color);for(let i=0;i<partIds.length;i++){const x=rest[i*3],y=rest[i*3+1],z=rest[i*3+2],color=base.clone();for(const p of parts.filter(p=>p.color)){const other=Math.min(...parts.filter(q=>!q.color).map(q=>partField(q,x,y,z))),blend=clamp((other-partField(p,x,y,z)+.025)/.11,0,1);color.lerp(new T.Color(p.color),blend);}colors.set([color.r,color.g,color.b],i*3);}geometry.setAttribute('color',new T.BufferAttribute(colors,3));mesh.material.color.set('#ffffff');mesh.material.vertexColors=true;}model.skin={mesh,rest,restNormals:new Float32Array(geometry.attributes.normal.array),raw:new Float32Array(rest.length),directions:new Float32Array(rest.length),partIds,restVolume:skinVolume(rest,geometry.index.array),volumeRatioBefore:1,volumeRatio:1,thicknessRatio:1,compensation:0,minimumJacobian:1,affectedParts:[],dirty:false};}
  function line(group,points,color,r=.026){const m=gummy(new T.TubeGeometry(new T.CatmullRomCurve3(points.map(p=>new T.Vector3(...p))),28,r,8,false),color);m.userData.softPatch=true;m.userData.surfaceDepth=points.reduce((n,p)=>n+p[2],0)/points.length;group.add(m);return m;}
  specs.forEach(s=>{const root=new T.Group(),softGroup=new T.Group(),model={...s,root,group:softGroup,soft:[],q:0,v:0,y:0,vy:0,indent:0,activeSoft:null,stretch:new T.Vector3(),stretchVelocity:new T.Vector3(),dragTarget:new T.Vector3(),dragging:false,followers:[]};root.userData.characterId=s.id;root.add(softGroup);root.position.set(s.x,0,0);models.push(model);stage.scene.add(root);
   if(s.id==='rabbit'){const parts=[{role:'body',center:[0,.55,0],radii:[.64,.57,.53],power:2.3},{role:'head',center:[0,1.28,.03],radii:[.8,.68,.6]}];for(const side of [-1,1])parts.push({role:side<0?'leftEar':'rightEar',center:[side*.36,1.97,.02],radii:[.245,.46,.24],angle:-side*.32},{role:side<0?'leftHand':'rightHand',center:[side*.53,.5,.32],radii:[.19,.27,.23]},{role:side<0?'leftFoot':'rightFoot',center:[side*.34,.14,.4],radii:[.3,.17,.31]});gel(softGroup,model,parts,[[-1.1,1.1],[-.1,2.85],[-.75,.95]]);for(const side of [-1,1]){const inner=ellipse(softGroup,model,side*.375,2,.2,.105,.285,.03,'#ffdce9');inner.rotation.z=-side*.32;inner.userData.softPatch=true;}}
   if(s.id==='dumpling'){gel(softGroup,model,[{role:'body',center:[-.32,.72,0],radii:[.9,.73,.63],power:2.25},{role:'body',center:[.32,.72,0],radii:[.9,.73,.63],power:2.25},{role:'leftFold',center:[-.98,.58,-.06],radii:[.3,.57,.51],angle:.2},{role:'rightFold',center:[.98,.58,-.06],radii:[.3,.57,.51],angle:-.2}],[[-1.45,1.45],[-.1,1.75],[-.8,.9]]);const tip=ellipse(softGroup,model,-.13,1.49,.02,.12,.16,.12,'#efb957');tip.rotation.z=-.35;for(const side of [-1,1]){const points=[];for(let n=0;n<24;n++){const u=n/23;points.push([side*(.65+.045*Math.sin(u*Math.PI*2)),.12+u*1.19,.42]);}line(softGroup,points,'#e8a37d',.009);}}
   if(s.id==='cat'){const parts=[{role:'body',center:[0,.84,0],radii:[1.08,.81,.64],power:2.8}];for(const side of [-1,1])parts.push({role:side<0?'leftEar':'rightEar',center:[side*.78,1.59,.02],radii:[.27,.42,.27],angle:-side*.2,cone:true},{role:side<0?'leftFoot':'rightFoot',center:[side*.4,.15,.48],radii:[.29,.18,.27],color:'#edf7e8'});gel(softGroup,model,parts,[[-1.35,1.35],[-.1,2.25],[-.8,1]]);for(const side of [-1,1]){const inner=ellipse(softGroup,model,side*.78,1.65,.24,.13,.19,.022,'#e8f5d7');inner.rotation.z=-side*.2;inner.userData.softPatch=true;ellipse(softGroup,model,side*.145,.73,.66,.2,.15,.07,'#f0f8ed');}}
   const fy=s.id==='rabbit'?1.36:s.id==='cat'?1.05:.85,fz=s.id==='rabbit'?.61:s.id==='cat'?.665:.66;
   for(const side of [-1,1]){if(s.id==='cat')line(softGroup,[[side*.33-.14,fy+.1,fz],[side*.33-.075,fy+.17,fz+.015],[side*.33,fy+.19,fz+.025],[side*.33+.075,fy+.17,fz+.015],[side*.33+.14,fy+.1,fz]],'#325c54',.026);else{ellipse(softGroup,model,side*.32,fy+.02,fz,.108,.125,.043,'#35273c');ellipse(softGroup,model,side*.32-.032,fy+.077,fz+.057,.041,.044,.018,'#fff8fc');ellipse(softGroup,model,side*.32+.032,fy-.019,fz+.06,.02,.02,.013,'#fff8fc');if(s.id==='rabbit')for(let n=0;n<3;n++){const xx=side*.32+side*(.055+n*.028),yy=fy+.108-n*.022;line(softGroup,[[xx,yy,fz+.028],[xx+side*.017,yy+.025,fz+.03],[xx+side*.03,yy+.045,fz+.028]],'#453344',.012);}}ellipse(softGroup,model,side*.57,fy-.15,fz-.03,.11,.04,.014,'#f0a6b1').userData.softPatch=true;}
   if(s.id==='cat'){ellipse(softGroup,model,0,fy-.23,fz+.07,.045,.03,.018,'#e995ac');line(softGroup,[[-.09,fy-.3,fz+.112],[-.045,fy-.33,fz+.115],[0,fy-.29,fz+.118],[.045,fy-.33,fz+.115],[.09,fy-.3,fz+.112]],'#547365',.016).userData.softPatch=false;}else line(softGroup,[[-.075,fy-.19,fz+.018],[0,fy-.22,fz+.038],[.075,fy-.19,fz+.018]],'#703b50',.015);
   const c=document.createElement('canvas');c.width=c.height=128;const gg=c.getContext('2d'),gradient=gg.createRadialGradient(64,64,3,64,64,62);gradient.addColorStop(0,'rgba(103,70,102,.65)');gradient.addColorStop(.45,'rgba(117,80,115,.23)');gradient.addColorStop(1,'rgba(117,80,115,0)');gg.fillStyle=gradient;gg.fillRect(0,0,128,128);const shadow=new T.Mesh(new T.PlaneGeometry(2.9,2.3),new T.MeshBasicMaterial({map:new T.CanvasTexture(c),transparent:true,opacity:.7,depthWrite:false}));shadow.rotation.x=-Math.PI/2;shadow.position.set(s.x,.012,0);model.shadow=shadow;stage.scene.add(shadow);
  });
 }
 if(!stage.supported)specs.forEach(s=>models.push({...s,q:0,v:0,y:0,vy:0,indent:0,soft:[],activeSoft:null,stretch:new T.Vector3(),stretchVelocity:new T.Vector3(),dragTarget:new T.Vector3(),dragging:false,followers:[]}));
 if(stage.supported){stage.scene.updateMatrixWorld(true);for(const m of models)for(const node of m.group.children){if(!node.geometry||node===m.skin.mesh)continue;node.castShadow=false;if(node.userData.softPatch){node.updateMatrix();const inverse=node.matrix.clone().invert(),pos=node.geometry.attributes.position,field=m.skin.mesh.geometry.userData.surfaceField;for(let i=0;i<pos.count;i++){const p=new T.Vector3(pos.array[i*3],pos.array[i*3+1],pos.array[i*3+2]).applyMatrix4(node.matrix),depth=(p.z-(node.userData.surfaceDepth??node.position.z))*.25;let anchor=m.soft[0].part;for(const soft of m.soft)if(partField(soft.part,p.x,p.y,0)<partField(anchor,p.x,p.y,0))anchor=soft.part;for(let n=0;n<24&&field(p.x,p.y,0)>0;n++){p.x+=(anchor.center[0]-p.x)*.1;p.y+=(anchor.center[1]-p.y)*.1;}let lo=0,hi=1;for(let n=0;n<24;n++){const mid=(lo+hi)/2;if(field(p.x,p.y,mid)<0)lo=mid;else hi=mid;}p.z=(lo+hi)/2+.008+depth;p.applyMatrix4(inverse);pos.array[i*3]=p.x;pos.array[i*3+1]=p.y;pos.array[i*3+2]=p.z;}pos.needsUpdate=true;node.geometry.computeVertexNormals();}node.geometry.computeBoundingSphere();const center=m.group.worldToLocal(node.localToWorld(node.geometry.boundingSphere.center.clone())),f={node,position:node.position.clone(),center};if(node.userData.softPatch){f.rest=new Float32Array(node.geometry.attributes.position.array);f.toGroup=node.matrix.clone();f.toLocal=node.matrix.clone().invert();}m.followers.push(f);}}
 if(stage.supported)for(const m of models){const positions=[],normals=[],colors=[];for(const f of m.followers){const node=f.node,g=node.geometry.toNonIndexed(),p=g.attributes.position,n=g.attributes.normal,color=node.material.color,normalMatrix=new T.Matrix3().getNormalMatrix(node.matrix);for(let i=0;i<p.count;i++){const v=new T.Vector3().fromBufferAttribute(p,i).applyMatrix4(node.matrix),normal=new T.Vector3().fromBufferAttribute(n,i).applyMatrix3(normalMatrix).normalize();positions.push(v.x,v.y,v.z);normals.push(normal.x,normal.y,normal.z);colors.push(color.r,color.g,color.b);}g.dispose();m.group.remove(node);node.geometry.dispose();node.material.dispose();}const g=new T.BufferGeometry();g.setAttribute('position',new T.Float32BufferAttribute(positions,3));g.setAttribute('normal',new T.Float32BufferAttribute(normals,3));g.setAttribute('color',new T.Float32BufferAttribute(colors,3));g.computeBoundingSphere();const material=new T.MeshPhysicalMaterial({color:'#ffffff',vertexColors:true,roughness:.26,metalness:0,clearcoat:.65,clearcoatRoughness:.18,envMapIntensity:.85}),mesh=new T.Mesh(g,material);mesh.userData.characterId=m.id;mesh.receiveShadow=true;mesh.castShadow=false;m.group.add(mesh);m.detail={mesh,rest:new Float32Array(positions),restNormals:new Float32Array(normals),dirty:false};m.followers=[];}
 q('[data-mascot-renderer]').textContent=stage.supported?'轻戳、拖揉，看看它怎么回应':'当前为二维触碰模式';
 function reset(){state={status:'ready',mode:q('[data-mascot-mode]').value,selected:'rabbit',target:'rabbit',pokes:0,hits:0,combo:0,maxCombo:0,misses:0,elapsed:0,remaining:30,softness:65,gravity:true,yaw:0,log:[]};lastPoke=-1;models.forEach(m=>{m.q=m.v=m.y=m.vy=m.indent=0;m.dragging=false;m.inputPending=false;m.stretch.set(0,0,0);m.stretchVelocity.set(0,0,0);m.dragTarget.set(0,0,0);m.activeSoft=null;if(m.skin)m.skin.dirty=true;for(const f of m.followers)f.node.position.copy(f.position);});q('[data-mascot-softness]').value='65';q('[data-mascot-gravity]').checked=true;sync();draw();}
 function sync(){q('[data-mascot-pokes]').textContent=state.pokes+' 次触碰';q('[data-mascot-softness-value]').textContent=state.softness+'%';q('[data-mascot-challenge]').hidden=state.mode!=='challenge';q('[data-mascot-hits]').textContent=state.hits+' / 12';q('[data-mascot-combo]').textContent=state.combo;q('[data-mascot-time]').textContent=Math.ceil(state.remaining)+' 秒';q('[data-mascot-target]').textContent=specs.find(c=>c.id===state.target).name;q('[data-mascot-start]').disabled=state.status!=='ready';q('[data-mascot-start]').textContent=({ready:state.mode==='sandbox'?'开启角色触碰':'开始可选连击挑战',playing:state.mode==='sandbox'?'触碰沙盒已开启':'挑战进行中',won:'挑战已完成',lost:'挑战已结束'}[state.status]);shell.querySelectorAll('[data-mascot-character]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.mascotCharacter===state.selected)));}
 function contact(m,point,mesh){if(!m.soft.length)return;const p=point?m.group.worldToLocal(point.clone()):null;m.activeSoft=point?[...m.soft].sort((a,b)=>partField(a.part,p.x,p.y,p.z)-partField(b.part,p.x,p.y,p.z))[0]:m.soft.find(s=>s.role==='head')||m.soft[0];if(point)m.activeSoft.point.copy(m.activeSoft.mesh.worldToLocal(point.clone()).normalize());else m.activeSoft.point.set(0,0,1);}
 function poke(id,point,mesh){if(state.status!=='playing'||!loop.active){say('先开启角色触碰。');return;}if(state.elapsed-lastPoke<.1)return;lastPoke=state.elapsed;state.selected=id;state.pokes++;const m=models.find(m=>m.id===id);if(m){m.v+=3+state.softness*.035;m.indent=.38*state.softness/100;if(state.gravity)m.vy=3+state.softness*.022;contact(m,point,mesh);}audio.play(id==='rabbit'?690:id==='cat'?560:430,.15,'triangle');
  if(state.mode==='challenge'){if(id===state.target){state.hits++;state.combo++;state.maxCombo=Math.max(state.combo,state.maxCombo);state.target=specs[state.hits%3].id;if(state.hits===12){state.status='won';say('可选连击挑战完成：12 次命中。');}else say('下一次轻戳'+specs[state.hits%3].name+'。');}else{state.misses++;state.combo=0;say('当前目标是'+specs.find(s=>s.id===state.target).name+'。');}}else say('轻戳'+specs.find(s=>s.id===id).name+'，观察凹陷、回弹与落地。');state.log.push({time:+state.elapsed.toFixed(2),character:id,mode:state.mode,softness:state.softness,gravity:state.gravity});sync();loop.start();draw();return m;
 }
 const fieldScratch=new Float64Array(6);
 function fieldDirections(m,x,y,z,out){sampleField(m,x,y,z,out);}
 function updateNormals(m){const s=m.skin,normal=s.mesh.geometry.attributes.normal,j=new Float64Array(9),n=new Float64Array(3);let minimum=Infinity;for(let i=0;i<s.rest.length;i+=3){sampleField(m,s.rest[i],s.rest[i+1],s.rest[i+2],fieldScratch,j,s.compensation);minimum=Math.min(minimum,transformNormal(j,s.restNormals[i],s.restNormals[i+1],s.restNormals[i+2],n));normal.array[i]=n[0];normal.array[i+1]=n[1];normal.array[i+2]=n[2];}normal.needsUpdate=true;s.minimumJacobian=minimum;}
 function thicknessRatio(m,positions){const s=m.skin,part=m.soft.indexOf(m.activeSoft),axis=m.fieldAxis,u=new T.Vector3().crossVectors(axis,Math.abs(axis.y)<.9?new T.Vector3(0,1,0):new T.Vector3(1,0,0)).normalize(),v=new T.Vector3().crossVectors(axis,u),a=m.activeSoft.toLocal.elements,lo=[Infinity,Infinity,Infinity,Infinity],hi=[-Infinity,-Infinity,-Infinity,-Infinity];for(let i=0;i<s.partIds.length;i++){if(s.partIds[i]!==part)continue;for(const [array,offset] of [[s.rest,0],[positions,2]]){const x=array[i*3],y=array[i*3+1],z=array[i*3+2],lx=a[0]*x+a[4]*y+a[8]*z+a[12],ly=a[1]*x+a[5]*y+a[9]*z+a[13],lz=a[2]*x+a[6]*y+a[10]*z+a[14],tu=lx*u.x+ly*u.y+lz*u.z,tv=lx*v.x+ly*v.y+lz*v.z;lo[offset]=Math.min(lo[offset],tu);hi[offset]=Math.max(hi[offset],tu);lo[offset+1]=Math.min(lo[offset+1],tv);hi[offset+1]=Math.max(hi[offset+1],tv);}}return Math.min((hi[2]-lo[2])/Math.max(.0001,hi[0]-lo[0]),(hi[3]-lo[3])/Math.max(.0001,hi[1]-lo[1]));}
 function updateSkin(m){const s=m.skin;s.updated=false;const pos=s.mesh.geometry.attributes.position,index=s.mesh.geometry.index.array,active=!!m.activeSoft&&(m.indent>=.0005||m.stretch.lengthSq()>=.000001);if(!active){if(s.dirty){s.updated=true;s.lastField=null;pos.array.set(s.rest);pos.needsUpdate=true;s.mesh.geometry.attributes.normal.array.set(s.restNormals);s.mesh.geometry.attributes.normal.needsUpdate=true;s.mesh.geometry.computeBoundingSphere();}s.dirty=false;s.volumeRatioBefore=s.volumeRatio=s.thicknessRatio=1;s.compensation=0;s.minimumJacobian=1;s.affectedParts=[];return;}const fieldKey=[m.indent,m.stretch.x,m.stretch.y,m.stretch.z,m.activeSoft.point.x,m.activeSoft.point.y,m.activeSoft.point.z,m.soft.indexOf(m.activeSoft)];if(s.lastField&&fieldKey.every((v,i)=>Math.abs(v-s.lastField[i])<1e-8))return;s.lastField=fieldKey;s.updated=true;s.dirty=true;m.fieldAxis=m.stretch.length()>.03?m.stretch.clone().normalize():m.activeSoft.point.clone();for(let i=0;i<pos.count;i++){const j=i*3;fieldDirections(m,s.rest[j],s.rest[j+1],s.rest[j+2],fieldScratch);for(let k=0;k<3;k++){s.raw[j+k]=s.rest[j+k]+fieldScratch[k];s.directions[j+k]=fieldScratch[k+3];}}
  const rawVolume=skinVolume(s.raw,index);s.volumeRatioBefore=rawVolume/s.restVolume;let coefficient=0;for(let n=0;n<2;n++){const at=skinVolume(s.raw,index,s.directions,coefficient),probe=skinVolume(s.raw,index,s.directions,coefficient+.015),derivative=(probe-at)/.015;if(Math.abs(derivative)<s.restVolume*.002)break;coefficient=clamp(coefficient+(s.restVolume-at)/derivative,-.1,.18);}s.compensation=coefficient;const displacement=m.soft.map(()=>0);for(let i=0;i<pos.count;i++){const j=i*3;for(let k=0;k<3;k++)pos.array[j+k]=s.raw[j+k]+s.directions[j+k]*coefficient;displacement[s.partIds[i]]=Math.max(displacement[s.partIds[i]],Math.hypot(pos.array[j]-s.rest[j],pos.array[j+1]-s.rest[j+1],pos.array[j+2]-s.rest[j+2]));}s.volumeRatio=skinVolume(pos.array,index)/s.restVolume;s.thicknessRatio=thicknessRatio(m,pos.array);s.affectedParts=m.soft.filter((_,i)=>displacement[i]>.003).map(p=>p.role);pos.needsUpdate=true;updateNormals(m);s.mesh.geometry.computeBoundingSphere();}
 function updateDetails(m){const detail=m.detail;if(!detail||!m.skin.updated)return;const pos=detail.mesh.geometry.attributes.position,normal=detail.mesh.geometry.attributes.normal;if(!m.skin.dirty){if(detail.dirty){pos.array.set(detail.rest);normal.array.set(detail.restNormals);pos.needsUpdate=normal.needsUpdate=true;detail.mesh.geometry.computeBoundingSphere();}detail.dirty=false;return;}const j=new Float64Array(9),n=new Float64Array(3);for(let i=0;i<detail.rest.length;i+=3){sampleField(m,detail.rest[i],detail.rest[i+1],detail.rest[i+2],fieldScratch,j,m.skin.compensation);for(let k=0;k<3;k++)pos.array[i+k]=detail.rest[i+k]+fieldScratch[k]+fieldScratch[k+3]*m.skin.compensation;transformNormal(j,detail.restNormals[i],detail.restNormals[i+1],detail.restNormals[i+2],n);normal.array[i]=n[0];normal.array[i+1]=n[1];normal.array[i+2]=n[2];}detail.dirty=true;pos.needsUpdate=normal.needsUpdate=true;detail.mesh.geometry.computeBoundingSphere();}
 const inputStats={received:0,applied:0,coalesced:0,flushedOnRelease:0};
 const drawStats={submitted:0,skipped:0,lastGeometryMs:0,lastSubmitMs:0};let lastSceneKey='';
 function applyPendingDrag(){for(const m of models)if(m.inputPending){m.stretch.copy(m.dragTarget);m.stretchVelocity.set(0,0,0);m.inputPending=false;inputStats.applied++;}}
 function draw(){const began=performance.now();if(stage.supported){const moving=models.some(m=>m.dragging||Math.abs(m.q)+Math.abs(m.v)+Math.abs(m.indent)+Math.abs(m.vy)+m.stretch.length()+m.stretchVelocity.length()>.002),ratio=moving?Math.min(defaultPixelRatio,960/Math.max(canvas.clientWidth,canvas.clientHeight)):defaultPixelRatio;if(Math.abs(stage.renderer.getPixelRatio()-ratio)>.001)stage.renderer.setPixelRatio(ratio);const narrow=canvas.clientWidth<650;models.forEach(m=>{m.root.visible=!narrow||m.id===state.selected;m.root.position.set(narrow?0:m.x,m.y,0);m.shadow.visible=m.root.visible;m.shadow.position.x=narrow?0:m.x;m.shadow.material.opacity=.7*clamp(1-m.y*.16,.3,1);const width=1+m.q*.24,height=clamp(1-m.q*.22,.65,1.35),depth=1+m.q*.12,cross=1/Math.sqrt(width*height*depth);m.group.scale.set(width*cross,height,depth*cross);m.group.rotation.z=Math.sin(m.q*1.2)*.035;
   m.group.updateMatrixWorld(true);updateSkin(m);updateDetails(m);
  });
   const distance=narrow?6.3:Math.max(6.5,12/(canvas.clientWidth/canvas.clientHeight));stage.camera.position.set(Math.sin(state.yaw)*distance,narrow?3:2.9,Math.cos(state.yaw)*distance);stage.camera.lookAt(0,narrow?1.65:1.35,0);const sceneKey=[canvas.clientWidth,canvas.clientHeight,ratio,state.yaw,state.selected,...models.flatMap(m=>[m.y,m.q,m.indent,m.stretch.x,m.stretch.y,m.stretch.z])].map(v=>typeof v==='number'?v.toFixed(5):v).join(',');drawStats.lastGeometryMs=performance.now()-began;if(sceneKey!==lastSceneKey||models.some(m=>m.skin.updated)){lastSceneKey=sceneKey;const submit=performance.now();stage.draw();drawStats.lastSubmitMs=performance.now()-submit;drawStats.submitted++;}else drawStats.skipped++;
  }else{const c=stage.ctx,w=canvas.width=960,hh=canvas.height=540;c.fillStyle='#f4edf5';c.fillRect(0,0,w,hh);specs.forEach((s,i)=>{const x=220+i*260;c.fillStyle=s.color;c.beginPath();c.ellipse(x,300-models[i].y*50,100*(1+models[i].q*.25),115*(1-models[i].q*.22),0,0,Math.PI*2);c.fill();c.fillStyle='#443644';c.beginPath();c.arc(x-30,280,10,0,Math.PI*2);c.arc(x+30,280,10,0,Math.PI*2);c.fill();c.font='22px system-ui';c.fillText(s.name,x-40,455);});}
 const feelText=state.status==='ready'?'开启沙盒后轻戳或拖揉':models.some(m=>m.dragging)?'按住拖揉 · 松开看局部回弹':state.mode==='sandbox'?'自由触碰 · '+specs.find(s=>s.id===state.selected).name:'当前目标 · '+specs.find(s=>s.id===state.target).name;if(q('[data-mascot-feel]').textContent!==feelText)q('[data-mascot-feel]').textContent=feelText;
 }
 const loop=mascotLoop(dt=>{applyPendingDrag();models.forEach(m=>{m.v+=(-85*m.q-11*m.v)*dt;m.q+=m.v*dt;if(m.dragging)m.indent=.22*state.softness/100;else m.indent*=Math.exp(-dt*(5-state.softness*.025));const stiffness=110-state.softness*.65,damping=2*Math.sqrt(stiffness)*.75;if(!m.dragging)for(const axis of ['x','y','z']){m.stretchVelocity[axis]+=(-stiffness*m.stretch[axis]-damping*m.stretchVelocity[axis])*dt;m.stretch[axis]+=m.stretchVelocity[axis]*dt;}if(m.dragging){m.vy=0;}else if(state.gravity){m.vy-=12*dt;m.y+=m.vy*dt;if(m.y<0){m.y=0;m.vy=Math.abs(m.vy)*.4;if(m.vy<.18)m.vy=0;}}else m.y=.1+Math.sin(state.elapsed*2+specs.findIndex(s=>s.id===m.id))*.05;});},draw,()=>state?.status==='playing'||models.some(m=>Math.abs(m.q)+Math.abs(m.v)+Math.abs(m.indent)+Math.abs(m.vy)+m.stretch.length()+m.stretchVelocity.length()>.002),elapsed=>{state.elapsed+=elapsed;if(state.mode==='challenge'&&state.status==='playing'){state.remaining=Math.max(0,30-state.elapsed);if(state.remaining===0){state.status='lost';say('时间结束，命中 '+state.hits+' / 12。');}sync();}});
 function hitAt(e){if(!stage.supported)return null;const rect=canvas.getBoundingClientRect();ray.setFromCamera(new T.Vector2((e.clientX-rect.left)/rect.width*2-1,-(e.clientY-rect.top)/rect.height*2+1),stage.camera);stage.scene.updateMatrixWorld(true);const hit=ray.intersectObjects(models.filter(m=>m.root.visible).map(m=>m.root),true)[0];if(!hit)return null;let obj=hit.object;while(obj&&!obj.userData.characterId)obj=obj.parent;return obj?{id:obj.userData.characterId,point:hit.point,mesh:hit.object}:null;}
 canvas.addEventListener('pointerdown',e=>{canvas.focus({preventScroll:true});const hit=hitAt(e);drag={x:e.clientX,y:e.clientY,id:hit?.id};canvas.setPointerCapture(e.pointerId);if(hit){const m=poke(hit.id,hit.point,hit.mesh);if(m?.activeSoft&&state.status==='playing'){m.dragging=true;m.vy=0;drag.plane=new T.Plane().setFromNormalAndCoplanarPoint(stage.camera.getWorldDirection(new T.Vector3()),hit.point);drag.anchor=hit.point.clone();}}else if(!stage.supported){const r=canvas.getBoundingClientRect();poke(specs[clamp(Math.floor((e.clientX-r.left)/r.width*3),0,2)].id);}},{signal});
 canvas.addEventListener('pointermove',e=>{if(!drag||!loop.active||state.status!=='playing')return;const dx=e.clientX-drag.x;if(drag.id&&drag.plane){const m=models.find(m=>m.id===drag.id),r=canvas.getBoundingClientRect();ray.setFromCamera(new T.Vector2((e.clientX-r.left)/r.width*2-1,-(e.clientY-r.top)/r.height*2+1),stage.camera);const point=ray.ray.intersectPlane(drag.plane,new T.Vector3());if(point&&m?.activeSoft){const a=m.activeSoft.mesh.worldToLocal(drag.anchor.clone()),b=m.activeSoft.mesh.worldToLocal(point);m.dragTarget.copy(b.sub(a)).clampLength(0,.65);inputStats.received++;if(m.inputPending)inputStats.coalesced++;m.inputPending=true;q('[data-mascot-feel]').textContent='按住拖揉 · 松开看局部回弹';}}else if(!drag.id)state.yaw=clamp(state.yaw+dx*.004,-.65,.65);drag.x=e.clientX;drag.y=e.clientY;loop.start();},{signal});function release(){if(models.some(m=>m.inputPending)){inputStats.flushedOnRelease++;applyPendingDrag();}if(drag?.id){const m=models.find(m=>m.id===drag.id);if(m){m.dragging=false;m.dragTarget.set(0,0,0);}}drag=null;loop.start();}canvas.addEventListener('pointerup',release,{signal});canvas.addEventListener('pointercancel',release,{signal});
 shell.addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;if(b.dataset.mascotCharacter){state.selected=b.dataset.mascotCharacter;sync();draw();}if(b.hasAttribute('data-mascot-poke'))poke(state.mode==='challenge'?state.target:state.selected);if(b.hasAttribute('data-mascot-start')){state.status='playing';sync();canvas.focus({preventScroll:true});loop.start();say(state.mode==='sandbox'?'角色触碰沙盒已开启，轻戳或拖揉。':'可选连击开始，目标为粉兔。');}if(b.hasAttribute('data-mascot-reset')){loop.stop();reset();say('角色和触碰记录已重置。');}if(b.dataset.mascotView){state.yaw=clamp(state.yaw+Number(b.dataset.mascotView)*.2,-.65,.65);draw();}if(b.hasAttribute('data-mascot-sound')){b.textContent='声音：'+(audio.toggle()?'开':'关');b.setAttribute('aria-pressed',String(audio.enabled));}if(b.hasAttribute('data-mascot-export'))h.downloadFile('立体角色触碰记录.json',JSON.stringify(getState(),null,2),'application/json');},{signal});
 shell.addEventListener('input',e=>{if(e.target.hasAttribute('data-mascot-softness'))state.softness=+e.target.value;if(e.target.hasAttribute('data-mascot-gravity')){state.gravity=e.target.checked;models.forEach(m=>m.vy=0);}sync();},{signal});
 q('[data-mascot-mode]').addEventListener('change',()=>{loop.stop();reset();say('已切换体验方式，点击开始。');},{signal});window.addEventListener('keydown',e=>{if(document.activeElement===canvas&&['1','2','3'].includes(e.key)&&!e.repeat){e.preventDefault();poke(specs[+e.key-1].id);}},{signal});
 function getState(){return {module:'mascot',status:state.status,mode:state.mode,running:loop.active&&state.status==='playing',renderer:stage.supported?'webgl':'canvas',rendering:stage.supported?{drawCalls:stage.renderer.info.render.calls,triangles:stage.renderer.info.render.triangles,pixelRatio:+stage.renderer.getPixelRatio().toFixed(4),defaultPixelRatio,canvasPixels:{width:canvas.width,height:canvas.height},interactiveResolutionLimit:960,attachmentBatches:models.filter(m=>m.root.visible).length,skinTriangles:models.reduce((n,m)=>n+m.skin.mesh.geometry.index.count/3,0),attachmentTriangles:models.reduce((n,m)=>n+m.detail.mesh.geometry.attributes.position.count/3,0),analyticNormals:true,drawUpdates:{...drawStats},staticDrawCallsSaved:stage.scene.userData.staticDrawCallsSaved||0}:null,input:{...inputStats,pending:models.filter(m=>m.inputPending).length,mode:'one deformation update per animation frame, final pointer target flushed on release'},selected:state.selected,shownCharacters:models.filter(m=>!stage.supported||m.root.visible).map(m=>m.id),target:state.mode==='challenge'?state.target:null,pokes:state.pokes,hits:state.hits,goal:state.mode==='challenge'?12:null,combo:state.combo,maxCombo:state.maxCombo,misses:state.misses,remaining:state.mode==='challenge'?+state.remaining.toFixed(1):null,elapsed:+state.elapsed.toFixed(1),softness:state.softness,gravity:state.gravity,soundEnabled:audio.enabled,viewAngle:+state.yaw.toFixed(2),characters:models.map(m=>({id:m.id,name:m.name,height:+m.y.toFixed(3),deformation:+m.q.toFixed(3),localIndent:+m.indent.toFixed(3),activePart:m.activeSoft?.role||null,dragging:m.dragging,stretch:{x:+m.stretch.x.toFixed(3),y:+m.stretch.y.toFixed(3),z:+m.stretch.z.toFixed(3)},deformedParts:m.skin?.affectedParts||[],vertexCount:m.skin?.mesh.geometry.attributes.position.count||0,surface:m.skin?{type:'continuous-skin',boundaryEdges:m.skin.mesh.geometry.userData.openEdges,restVolume:+m.skin.restVolume.toFixed(4),volumeBeforeCompensation:+m.skin.volumeRatioBefore.toFixed(4),volumeAfterCompensation:+m.skin.volumeRatio.toFixed(4),transverseThicknessRatio:+m.skin.thicknessRatio.toFixed(4),compensationCoefficient:+m.skin.compensation.toFixed(4),minimumJacobian:+m.skin.minimumJacobian.toFixed(4),regions:m.soft.map(s=>s.role)}:null})),scope:'Original continuous procedural skins. Local spring fields and bounded transverse thickness compensation, not exact volume conservation or full soft-body physics. Combo challenge is our optional extension.',log:state.log.map(x=>({...x}))};}
 reset();const layoutObserver=new ResizeObserver(()=>draw());layoutObserver.observe(canvas);return {getState,setActive(v){release();loop.setActive(v);if(!v)audio.suspend();},dispose(){layoutObserver.disconnect();loop.dispose();ctrl.abort();audio.dispose();envTarget?.dispose();stage.dispose();shell.remove();}};
}




