import {T,createStage} from './three-stage.js';
import {buildPianoStudio} from './music-art.js';
import {createPerformance} from './music-performance.js';
import {exportPianoMovie} from './music-offline-export.js';
const themes={calm:[60,64,67,72,69,67,64,62,60,64,65,69,67,64,62,60],bright:[60,67,72,76,74,72,69,67,65,69,74,77,76,72,67,60],night:[57,60,64,69,67,64,60,59,57,60,62,65,64,60,59,57]};
const names={calm:'专注',bright:'明亮',night:'夜间'},hz=midi=>440*2**((midi-69)/12);
export function mount(container,h){
 h.css('music.css');container.innerHTML=`<div class="lab-demo music-demo"><details class="music-film"><summary>观看本例成片 <span>明亮旋律 · 12.8 秒 · 24 帧/秒</span></summary><div class="music-film-content"><video controls playsinline preload="none" poster="../media/field-duet-v15.webp" data-film-src="../media/field-duet-v15.webm" aria-label="第06项目优化后的原创演奏成片"></video><span class="music-film-status" role="status"></span><p>明亮旋律 / 150 BPM / 演奏特写。成片由下方同一场景与乐谱逐帧生成；下方可编辑旋律、节奏与视角，再导出自己的版本。</p></div></details><div class="three-stage"><canvas class="lab-canvas" tabindex="0" aria-label="机器人和猫在实体钢琴上的原创音乐动画"></canvas><div class="stage-overlay"><b>FIELD DUET / 角色钢琴</b><span>32 个音符 · 同一乐谱驱动声音、弹键与角色</span></div><div class="stage-bottom"><span class="music-note-label">等待播放</span><span>拖动旋转 · 可切换演奏视角</span></div></div><div class="music-score" aria-label="音符时间表"></div><div class="lab-controls"><button class="lab-button primary" data-action="play">播放角色与音乐</button><button class="lab-button" data-action="reset">从头开始</button><label class="lab-field">演奏视角<select data-field="shot"><option value="close">演奏特写</option><option value="room">完整琴房</option></select></label><label class="lab-field">原创旋律<select data-field="mood"><option value="calm">专注</option><option value="bright">明亮</option><option value="night">夜间</option></select></label><label class="lab-field">节奏 <output class="tempo-label">90 BPM</output><input data-field="tempo" type="range" min="60" max="150" value="90"></label><label class="lab-field">音量<input data-field="volume" type="range" min="0" max="60" value="25"></label><label class="lab-field music-seek">共用时间线<input data-field="seek" type="range" min="0" max="1000" value="0"></label><button class="lab-button" data-action="wav">导出原创 WAV</button><button class="lab-button" data-action="video">导出音乐动画 WebM</button><button class="lab-button" data-action="python">导出 Python / Blender 脚本</button><button class="lab-button" data-action="png">导出当前画面</button></div><div class="music-workflow"><div><b>01 / 编曲</b><span>32 音符 + 低音事件</span></div><div><b>02 / 共用时间表</b><span>声音、琴键、角色动作</span></div><div><b>03 / 动画交付</b><span>网页 WebM / Blender 脚本</span></div></div><p class="lab-note">参考原作的“角色在实体钢琴上演奏”与 Python → Blender 流程。这里的机器人、猫、场景几何和旋律均为原创；摄影木纹与 HDR 来自 Poly Haven。网页用 Three.js / Web Audio 预览，WebM 按固定时间线逐帧编码并配乐；脚本用 Python 写 WAV、用 bpy 建场景及关键帧。本机未安装 Blender，离线画质与渲染仍待验证；新版网页材质与触键姿态尚未移植到脚本。</p></div>`;
 const $=s=>container.querySelector(s),stage=createStage($('canvas'),{background:'#292321',radius:6.6,target:[0,2.45,.25],yaw:-.15,pitch:.16,minAspect:1.85});
 const state={shot:'close',mood:'calm',tempo:90,volume:25,playing:false,progress:0,noteIndex:-1,playedNotes:0,renderer:stage.supported?'webgl':'canvas',recording:false,workflow:'shared-events → audio + character/key poses',blenderRendered:false,renderedFrames:0,exportedFrames:0};
 let active=true,disposed=false,raf=0,lastIndex=-1,audio,gain,audioOut,clockStart=0,startProgress=0,movieController=null,filmUrl=null,filmLoading=null;const oscillators=new Set(),keys=[],robot=new T.Group(),cat=new T.Group(),arms=[],feet=[];let tail,studio,performanceRig;
 function notes(){return [...themes[state.mood],...themes[state.mood].map((n,i)=>n+(i<8?0:i%4===0?12:0))];}
 function duration(){return notes().length*60/state.tempo;}
 function recipe(){return {schemaVersion:2,title:'FIELD DUET',mood:state.mood,tempo:state.tempo,volume:state.volume,duration:duration(),fps:24,notes:notes().map((midi,i)=>({midi,at:i*60/state.tempo,duration:60/state.tempo,bass:i%4===0?midi-12:null})),source:'https://x.com/kevin_t_ngo/status/2105304249060274631',sourceWorkflow:'Python composition / Python animation / Blender rendering',ours:'Original characters and scene. Browser preview uses Three.js/Web Audio. Export script uses wave and bpy; enhanced browser materials and key-contact poses are not ported to the bpy example.',blenderRendered:false};}
 if(stage.supported){studio=buildPianoStudio(stage,{keys,robot,cat,arms,feet});tail=studio.tail;performanceRig=createPerformance({keys,robot,cat,arms,feet,tail});}

 function score(){const sequence=notes();$('.music-score').innerHTML=sequence.map((n,i)=>`<span style="--note:${(n-50)/40}" data-current="false"><i></i><small>${i+1}</small></span>`).join('');studio?.updateScore(sequence,names[state.mood]);}
 function draw(){const sequence=notes(),index=Math.min(sequence.length-1,Math.floor(state.progress*sequence.length)),fraction=state.progress*sequence.length-index,pulse=Math.sin(Math.PI*fraction);state.noteIndex=state.progress>0||state.playing?index:-1;
  if(stage.supported){performanceRig.update(sequence,state.progress,state.progress>0||state.playing);if(state.shot==='close'){const left=Math.min(robot.position.x-.80,cat.position.x-.96),right=Math.max(robot.position.x+.74,cat.position.x+1.0),span=right-left;stage.setFraming({target:[(left+right)/2,2.52,.55],radius:Math.max(3.85,span*1.25/(2*Math.tan(43*Math.PI/360)*1.85))});}else stage.setFraming({target:[0,2.45,.25],radius:6.6});stage.draw();}
  else{const g=stage.context,c=stage.canvas;c.width=1000;c.height=560;g.fillStyle='#41352f';g.fillRect(0,0,1000,560);g.fillStyle='#b09270';g.fillRect(80,270,840,180);for(let i=0;i<25;i++){g.fillStyle=i===sequence[index]-55?'#eac778':'#eee6cf';g.fillRect(105+i*31.5,300,29,90);}g.fillStyle='#ed947b';g.fillRect(235,190-Math.max(0,pulse)*12,90,85);g.fillStyle='#35302e';g.beginPath();g.ellipse(625,265-Math.max(0,pulse)*10,75,35,0,0,6.28);g.fill();g.fillStyle='#f5e7cf';g.font='23px system-ui';g.fillText('二维兼容预览 · WAV 与 Python 配方仍可导出',90,95);}
  state.renderedFrames++;
  $('.music-score').querySelectorAll('span').forEach((el,i)=>el.dataset.current=String(i===state.noteIndex));$('.music-note-label').textContent=state.noteIndex>=0?`${names[state.mood]} · ${index+1}/${sequence.length} · MIDI ${sequence[index]}`:'等待播放';$('[data-field="seek"]').value=String(Math.round(state.progress*1000));$('[data-action="play"]').textContent=state.playing?'暂停角色与音乐':'播放角色与音乐';$('.tempo-label').textContent=state.tempo+' BPM';}
 function silence(){for(const o of oscillators){try{o.stop();}catch{}}oscillators.clear();}
 async function prepareAudio(){if(!audio){const Context=window.AudioContext||window.webkitAudioContext;if(!Context)return false;audio=new Context();gain=audio.createGain();gain.connect(audio.destination);audioOut=audio.createMediaStreamDestination();gain.connect(audioOut);}if(audio.state==='suspended')await audio.resume();gain.gain.value=state.volume/100;return true;}
 function tone(midi,amplitude=1,at=audio?.currentTime){if(!audio||audio.state!=='running')return;const start=at,beat=60/state.tempo;for(let k=1;k<=4;k++){const o=audio.createOscillator(),envelope=audio.createGain();o.frequency.value=hz(midi)*k;o.type='sine';envelope.gain.setValueAtTime(0,start);envelope.gain.linearRampToValueAtTime(amplitude*.22/(k*k),start+.009);envelope.gain.exponentialRampToValueAtTime(.0001,start+beat*.94);o.connect(envelope);envelope.connect(gain);o.start(start);o.stop(start+beat);oscillators.add(o);o.onended=()=>{oscillators.delete(o);o.disconnect();envelope.disconnect();};}}
 function tick(time){raf=0;if(disposed||!active||!state.playing)return;const clock=audio?.state==='running'?audio.currentTime:time/1000;state.progress=Math.min(1,startProgress+(clock-clockStart)/duration());const i=Math.min(notes().length-1,Math.floor(state.progress*notes().length));if(i!==lastIndex&&state.progress<1){state.playedNotes+=Math.max(0,i-lastIndex);lastIndex=i;}draw();if(state.progress>=1){state.playing=false;silence();stopRecording(false);draw();h.onStatus('乐谱已播放完成。琴键、角色和声音使用同一事件时间表。');return;}raf=requestAnimationFrame(tick);}
 function stopRecording(cancel=true){if(cancel&&movieController){movieController.abort();$('[data-action="video"]').disabled=true;}state.recording=false;}
 function pause(redraw=true){const wasRecording=state.recording;state.playing=false;cancelAnimationFrame(raf);raf=0;silence();stopRecording(true);if(redraw)draw();else $('[data-action="play"]').textContent='播放角色与音乐';if(wasRecording&&!disposed)h.onStatus('录制已取消。重新录制时请保持本页可见。');}
 async function start(){$('.music-film video').pause();if(state.progress>=1)state.progress=0;await prepareAudio();if(disposed||!active)return;startProgress=state.progress;lastIndex=Math.floor(startProgress*notes().length)-1;state.playing=true;draw();clockStart=audio?.state==='running'?audio.currentTime:performance.now()/1000;if(audio?.state==='running'){const sequence=notes(),beat=60/state.tempo,offset=startProgress*duration();for(let i=Math.max(0,lastIndex+1);i<sequence.length;i++){const at=clockStart+Math.max(0,i*beat-offset);tone(sequence[i],1,at);if(i%4===0)tone(sequence[i]-12,.35,at);}}raf=requestAnimationFrame(tick);}
 function wav(){const rate=22050,beat=60/state.tempo,count=Math.ceil((duration()+.2)*rate),sequence=notes(),buf=new ArrayBuffer(44+count*2),v=new DataView(buf);const str=(at,s)=>[...s].forEach((c,i)=>v.setUint8(at+i,c.charCodeAt()));str(0,'RIFF');v.setUint32(4,36+count*2,true);str(8,'WAVE');str(12,'fmt ');v.setUint32(16,16,true);v.setUint16(20,1,true);v.setUint16(22,1,true);v.setUint32(24,rate,true);v.setUint32(28,rate*2,true);v.setUint16(32,2,true);v.setUint16(34,16,true);str(36,'data');v.setUint32(40,count*2,true);for(let s=0;s<count;s++){const t=s/rate,i=Math.floor(t/beat),local=t-i*beat;let value=0;if(i<sequence.length){const env=Math.min(1,local/.009)*Math.exp(-local/(beat*.19));for(let k=1;k<=4;k++){value+=Math.sin(2*Math.PI*hz(sequence[i])*k*local)/(k*k);if(i%4===0)value+=.35*Math.sin(2*Math.PI*hz(sequence[i]-12)*k*local)/(k*k);}value*=env*.22*state.volume/100;}v.setInt16(44+s*2,Math.round(Math.max(-1,Math.min(1,value))*32767),true);}h.downloadFile('角色钢琴-'+names[state.mood]+'.wav',buf,'audio/wav');}
 async function record(){
  if(state.recording){movieController?.abort();pause();h.onStatus('导出已取消，未交付不完整的视频。');return;}
  $('.music-film video').pause();pause();const previous=state.progress,job=new AbortController();movieController=job;state.recording=true;state.progress=0;state.exportedFrames=0;
  const controls=container.querySelectorAll('[data-field], [data-action="wav"], [data-action="python"], [data-action="play"], [data-action="reset"], [data-action="png"]');
  controls.forEach(el=>el.disabled=true);$('[data-action="video"]').textContent='取消导出';stage.setResolutionLimit?.(960);draw();
  try{
   const seconds=duration(),fps=24;
   const output=await exportPianoMovie({canvas:stage.canvas,duration:seconds,fps,notes:notes(),tempo:state.tempo,volume:state.volume,signal:job.signal,
    renderAt(time){if(job.signal.aborted||disposed||!active)throw new DOMException('导出已取消','AbortError');state.progress=Math.min(1,time/seconds);draw();state.exportedFrames++;},
    onProgress(value){if(!disposed&&active)h.onStatus(`正在逐帧生成音乐动画 · ${Math.round(value*100)}% · 输出 24 帧/秒，请保持本页可见。`);}
   });
   if(!job.signal.aborted&&!disposed&&active){h.downloadFile('角色钢琴音乐动画.webm',output,'video/webm');h.onStatus(`音乐动画已导出：${state.exportedFrames} 帧、24 帧/秒，包含同一乐谱生成的音轨。`);}
  }catch(error){if(!disposed)h.onStatus(error.name==='AbortError'?'导出已取消，未交付不完整的视频。':'音乐动画导出失败：'+error.message);}
  finally{if(movieController===job)movieController=null;state.recording=false;controls.forEach(el=>el.disabled=false);$('[data-action="video"]').textContent='导出音乐动画 WebM';$('[data-action="video"]').disabled=false;if(!disposed){stage.setResolutionLimit?.(null);state.progress=previous;draw();}}
 }
 const controller=new AbortController(),signal=controller.signal;
 $('.music-film video').addEventListener('play',()=>pause(false),{signal});
 // A local Blob also provides seekable media on simple static servers that
 // ignore HTTP Range requests. Load once on demand, and release on disposal.
 async function prepareFilm(){
  if(filmUrl||filmLoading)return filmLoading;
  $('.music-film-status').textContent='正在准备成片…';
  filmLoading=(async()=>{try{const video=$('.music-film video'),response=await fetch(new URL(video.dataset.filmSrc,location.href),{signal});if(!response.ok)throw new Error('成片文件暂时未加载');const blob=await response.blob();if(disposed)return;filmUrl=URL.createObjectURL(blob);video.src=filmUrl;video.preload='metadata';video.load();$('.music-film-status').textContent='成片已就绪，可播放或拖动进度。';}catch(error){if(!disposed&&error.name!=='AbortError')$('.music-film-status').textContent='成片暂时未加载，重新展开可重试。';}finally{filmLoading=null;}})();
  return filmLoading;
 }
 $('.music-film').addEventListener('toggle',()=>{if($('.music-film').open)prepareFilm();else $('.music-film video').pause();},{signal});
 container.addEventListener('click',async event=>{const action=event.target.closest('[data-action]')?.dataset.action;if(action==='play'){if(state.playing)pause();else await start();}else if(action==='reset'){pause();state.progress=0;state.playedNotes=0;draw();}else if(action==='wav')wav();else if(action==='png')stage.canvas.toBlob(blob=>blob&&h.downloadFile('角色钢琴画面.png',blob,'image/png'));else if(action==='video')await record();else if(action==='python'){try{const template=await fetch('pipeline/music_blender.py').then(r=>{if(!r.ok)throw new Error('配方脚本未读取');return r.text();});if(disposed)return;const configured=template.replace('DEFAULT_RECIPE = None','DEFAULT_RECIPE = '+JSON.stringify(JSON.stringify(recipe())));h.downloadFile('角色钢琴配方.py',configured,'text/x-python;charset=utf-8');}catch(e){h.onStatus(e.message);}}},{signal});
 container.addEventListener('input',event=>{if(state.recording)return;const field=event.target.dataset.field,value=event.target.value;if(!['shot','mood','tempo','volume','seek'].includes(field))return;if(field==='shot'){pause();state.shot=value;}else if(field==='mood'){pause();state.mood=event.target.value;state.progress=0;score();}else if(field==='tempo'){pause();state.tempo=Number(event.target.value);}else if(field==='volume'){state.volume=Number(event.target.value);if(gain)gain.gain.value=state.volume/100;}else if(field==='seek'){pause();state.progress=Number(value)/1000;}draw();},{signal});
 document.addEventListener('visibilitychange',()=>{if(document.hidden){$('.music-film video').pause();pause();}},{signal});score();draw();
 return {getState:()=>({...state,...recipe(),noteIndex:state.noteIndex,playedNotes:state.playedNotes,playing:state.playing,progress:state.progress,recording:state.recording,audioState:audio?.state||'not-started',characters:['coral-square-robot','continuous-black-cat'],scene:'aged-painted-piano-room',samplePreview:{mood:'bright',tempo:150,shot:'close',duration:12.8,playing:!$('.music-film video').paused,currentTime:$('.music-film video').currentTime},performance:performanceRig?.getState()||null}),setActive(value){active=value;if(!value){$('.music-film video').pause();pause();}else draw();},dispose(){disposed=true;$('.music-film video').pause();pause();controller.abort();if(filmUrl)URL.revokeObjectURL(filmUrl);studio?.dispose();stage.dispose();audio?.close();}};
}






