import {T,createStage,box,solid,label,lightScene,bindFPS,moveFPS,fpsCamera,fpsPad,synth} from './four-playable-stage.js';
import {buildQuest,batchStatic} from './games-art.js';
import {batchRecorders} from './quest-recorder.js';
import {createRecorder} from './quest-character-art.js';
// Case 02 keeps rendering time in its clock; small movement steps preserve collisions.
function questLoop(step,draw,needed,afterFrame){let raf=0,last=null,active=true,disposed=false;const controller=new AbortController();function tick(t){raf=0;if(disposed||!active||document.hidden||!needed()){last=null;return;}let remaining=Math.max(0,(t-last)/1000),frameTime=remaining;last=t;while(remaining>1e-8&&needed()){const dt=Math.min(1/120,remaining);step(dt);remaining-=dt;}afterFrame(frameTime);draw();start();}function start(){if(!raf&&!disposed&&active&&!document.hidden&&needed()){if(last===null)last=performance.now();raf=requestAnimationFrame(tick);}}function stop(){cancelAnimationFrame(raf);raf=0;last=null;}document.addEventListener('visibilitychange',()=>document.hidden?stop():start(),{signal:controller.signal});return {start,stop,get active(){return active&&!document.hidden&&!disposed;},setActive(v){active=Boolean(v);if(active)start();else stop();},dispose(){disposed=true;active=false;stop();controller.abort();}};}
export function mount(container,h){
 h.css('quest.css');const ctrl=new AbortController(),signal=ctrl.signal,audio=synth();
 const sites=[{id:'hub',name:'研究站',x:-4.7,z:12},{id:'archive',name:'档案站',x:-12,z:-8,question:'两份档案的结论不同。先核对什么？',good:'核对时间与来源',bad:'直接挑喜欢的结论',evidence:'档案来源与时间已核对'},{id:'sensor',name:'传感站',x:12,z:-8,question:'传感器的记录突然改变。怎么办？',good:'校准后重读异常段',bad:'删除异常记录',evidence:'异常读数与校准已复核'},{id:'tower',name:'观测塔',x:0,z:-23,question:'两次观察支持不同的判断。怎么办？',good:'保留并比较两次观察',bad:'只留支持自己的记录',evidence:'两次观察差异已保留'}];
 const shell=document.createElement('section');shell.className='lab-demo quest-lab';
 shell.innerHTML='<div class="quest-heading"><div><span>FIELD TERMINAL / 程序化研究街区</span><h3>走进街区，带回三份证据</h3></div><b data-quest-progress>0 / 3</b></div><div class="quest-layout"><div><div class="quest-viewport"><canvas class="lab-canvas quest-canvas" tabindex="0" aria-label="第一人称程序化研究街区，WASD移动，方向键转向，拖动画面观察"></canvas><div class="quest-hud"><span data-quest-location>研究街区 · 第一人称</span><span data-quest-renderer>准备场景</span></div><span class="quest-reticle">＋</span><div class="quest-interaction" data-quest-context hidden><div><b data-quest-context-title></b><span data-quest-context-hint></span></div><button class="lab-button" data-quest-talk data-quest-context-action>走近记录员</button></div><div class="quest-bottom">FIELD JOURNAL · 街区漫游与证据归档</div></div>'+fpsPad()+'<p class="quest-hint">WASD 移动 · ← / → 转向 · 拖动画面观察 · E 交谈</p></div><aside class="quest-terminal"><div class="quest-terminal-head">FIELD-01 <span>● ONLINE</span></div><nav class="quest-tabs"><button class="lab-button" data-quest-tab="task">任务</button><button class="lab-button" data-quest-tab="gear">装备</button><button class="lab-button" data-quest-tab="map">地图</button></nav><section data-quest-panel="task"><h4>证据核对任务</h4><div data-quest-dialog>开始后步行到标牌旁，或在地图页选择路线。</div><ul data-quest-evidence></ul></section><section data-quest-panel="gear" hidden><h4>野外记录装备</h4><ul><li>来源核对器 · 就绪</li><li>传感器校准器 · 就绪</li><li>双次观察档案 <b data-quest-archive-count>0 份</b></li></ul><p>这是任务记录装备，不含原作武器或完整战斗。</p></section><section data-quest-panel="map" hidden><h4>街区路线</h4><p>研究站在南侧，两处核对站在中央，观测塔在北侧。</p><div class="quest-route">'+sites.map(s=>'<button class="lab-button" data-quest-travel="'+s.id+'">步行到'+s.name+'</button>').join('')+'</div></section><button class="lab-button primary" data-quest-talk>与附近站点交谈</button></aside></div><div class="lab-controls"><button class="lab-button primary" data-quest-start>开始街区任务</button><button class="lab-button" data-quest-reset>重置街区</button><button class="lab-button" data-quest-sound aria-pressed="true">提示声音：开</button><button class="lab-button" data-quest-export>导出任务记录 JSON</button></div><p class="lab-status" role="status" data-quest-status>原创小街区保留程序化场景、分支任务、终端记录与合成声音，不宣称复现原作完整 RPG。</p>';
 container.append(shell);const q=s=>shell.querySelector(s),stage=createStage(q('canvas'),{background:'#aaa38a',fov:68}),canvas=stage.canvas;
 const obstacles=[{x:-12,z:7,w:10,d:10},{x:12,z:7,w:10,d:10},{x:-19,z:-21,w:9,d:12},{x:19,z:-21,w:9,d:12}],beacons=[],markers=[],recorders=[];let state,target=null,route=[],recorderBatch=null;
 const player={x:0,z:15,yaw:0,pitch:0},keys=bindFPS(canvas,shell,player,ctrl);
 const say=t=>{q('[data-quest-status]').textContent=t;h.onStatus(t);},log=(action,detail)=>state.log.push({time:+state.elapsed.toFixed(1),action,detail});
 if(stage.supported){
  stage.scene.fog=new T.Fog('#aaa38a',23,72);lightScene(stage,{sky:'#d2d1b9',ground:'#354136',power:1.05,sun:2.4});buildQuest(stage,obstacles,sites,beacons);
  // Replace only the four uniquely identified recorder groups before batching.
  // Check both exact location and original torso/hat/backpack structure.
  const originalStaff=sites.map(site=>stage.scene.children.filter(o=>o.isGroup&&Math.abs(o.position.x-site.x-2.7)<1e-7&&o.position.y===0&&Math.abs(o.position.z-site.z+.8)<1e-7&&o.children.some(m=>m.isMesh&&m.material.color?.getHex()===0x657c70&&m.position.y===1.13&&m.scale.y===.42)&&o.children.some(m=>m.isMesh&&m.position.y===1.925)&&o.children.some(m=>m.isMesh&&m.position.z===-.23)));
  if(originalStaff.some(matches=>matches.length!==1))throw new Error('02 记录员结构已变更，无法安全替换人物。');
  const geometries=new Set(),materials=new Set(),retainedGeometry=new Set(),retainedMaterial=new Set();
  originalStaff.flat().forEach(g=>{g.traverse(o=>{if(o.geometry)geometries.add(o.geometry);for(const m of (Array.isArray(o.material)?o.material:[o.material]))if(m)materials.add(m);});stage.scene.remove(g);});
  stage.scene.traverse(o=>{if(o.geometry)retainedGeometry.add(o.geometry);for(const m of (Array.isArray(o.material)?o.material:[o.material]))if(m)retainedMaterial.add(m);});
  geometries.forEach(g=>{if(!retainedGeometry.has(g))g.dispose();});materials.forEach(m=>{if(!retainedMaterial.has(m))m.dispose();});
  batchStatic(stage.scene,beacons);
  sites.forEach((site,i)=>{const actor=createRecorder(site,i);recorders.push(actor);stage.scene.add(actor.root);const group=new T.Group(),pending=label(site.name+' · '+(site.id==='hub'?'提交证据':'待核对'),'#eed6a0','#233d31'),checked=label(site.name+' · '+(site.id==='hub'?'已归档 ✓':'已核对 ✓'),'#ccedc8','#245343');pending.scale.set(.68,.68,1);checked.scale.copy(pending.scale);pending.castShadow=checked.castShadow=false;group.add(pending,checked);group.position.set(site.x+2.7,2.43,site.z-.8);stage.scene.add(group);markers.push({site,group,pending,checked});});recorderBatch=batchRecorders(stage.scene,recorders);stage.renderer.shadowMap.autoUpdate=false;stage.renderer.shadowMap.needsUpdate=true;
 }
 q('[data-quest-renderer]').textContent=stage.supported?'走近站点 · E 交谈':'二维地图模式 · 选择站点路线';
 function panel(tab){shell.querySelectorAll('[data-quest-panel]').forEach(e=>e.hidden=e.dataset.questPanel!==tab);shell.querySelectorAll('[data-quest-tab]').forEach(e=>e.setAttribute('aria-pressed',String(e.dataset.questTab===tab)));}
 function sync(){q('[data-quest-progress]').textContent=state.evidence.length+' / 3';q('[data-quest-archive-count]').textContent=state.evidence.length+' 份';q('[data-quest-evidence]').innerHTML=state.evidence.map(id=>'<li>✓ '+h.escape(sites.find(s=>s.id===id).evidence)+'</li>').join('');q('[data-quest-start]').disabled=state.status!=='ready';q('[data-quest-start]').textContent=({ready:'开始街区任务',playing:'街区任务进行中',won:'任务已完成'}[state.status]);}
 function reset(){Object.assign(player,{x:0,z:15,yaw:0,pitch:0});state={status:'ready',elapsed:0,actorTime:0,evidence:[],dialogueSite:null,responses:{},log:[]};target=null;route=[];keys.clear();recorders.forEach(a=>a.reset());q('[data-quest-dialog]').textContent='开始后步行到站点，核对三份证据。';panel('task');sync();draw();}
 function respond(s,kind){state.responses[s.id]={kind,at:state.actorTime};}
 function updateRecorders(dt=0){recorders.forEach((a,i)=>a.update({time:state.actorTime,player,playing:state.status==='playing',dialogue:state.dialogueSite===sites[i].id,response:state.responses[sites[i].id],done:state.evidence.includes(sites[i].id),completed:state.status==='won'&&sites[i].id==='hub'},dt));}
 function dialog(s,response='talk'){state.dialogueSite=s.id;respond(s,response);const dx=s.x+2.7-player.x,dz=s.z-.8-player.z;player.yaw=Math.atan2(dx,-dz);player.pitch=-.035;panel('task');draw();if(s.id==='hub')q('[data-quest-dialog]').innerHTML=state.evidence.length===3?'<h4>研究站 · 证据齐全</h4><button class="lab-button primary" data-quest-submit>提交三份证据</button>':'<p>还缺 '+(3-state.evidence.length)+' 份，前往三个核对站。</p>';else if(state.evidence.includes(s.id))q('[data-quest-dialog]').textContent='✓ '+s.evidence;else q('[data-quest-dialog]').innerHTML='<h4>'+h.escape(s.name)+'</h4><p>'+h.escape(s.question)+'</p><button class="lab-button" data-quest-choice="good" data-site="'+s.id+'">'+h.escape(s.good)+'</button><button class="lab-button" data-quest-choice="bad" data-site="'+s.id+'">'+h.escape(s.bad)+'</button><p data-quest-feedback></p>';audio.play(520,.13);say('正在'+s.name+'核对记录。');}
 function talk(){if(state.status!=='playing'){say('先开始街区任务。');return;}const s=nearby().distance<3.3?nearby().site:null;if(s)dialog(s);else say('走近标牌旁再交谈，也可在地图页选择步行路线。');}
 function nearby(){const ranked=sites.map(site=>({site,distance:Math.hypot(site.x+2.7-player.x,site.z-.8-player.z)}));return ranked.sort((a,b)=>a.distance-b.distance)[0];}
 function context(){const n=nearby(),near=n.distance<3.3,done=state.evidence.includes(n.site.id),active=state.status==='playing';q('[data-quest-context]').hidden=!active;q('[data-quest-context-title]').textContent=n.site.name+'记录员 · '+n.distance.toFixed(1)+' m';q('[data-quest-context-hint]').textContent=near?(done?'这份记录已核对；可再次查看。':n.site.id==='hub'?'归还记录，核对归档进度。':'现在可交谈；核对后这里会显示 ✓。'):'靠近头顶标牌的记录员，再按 E。';q('[data-quest-context-action]').disabled=!near;q('[data-quest-context-action]').textContent=near?'E · '+(done?'查看记录':'交谈'):'走近记录员';shell.querySelector('.quest-terminal [data-quest-talk]').textContent=near?'与'+n.site.name+'记录员交谈':'走近记录员后交谈';}
 function draw(){updateRecorders();context();if(stage.supported){const lens=state.dialogueSite&&nearby().distance<3.3?56:68;if(stage.camera.fov!==lens){stage.camera.fov=lens;stage.camera.updateProjectionMatrix();}fpsCamera(stage,player);beacons.forEach((m,i)=>{const done=state.evidence.includes(sites[i].id)||(sites[i].id==='hub'&&state.status==='won');m.material.color.set(done?'#add9ac':'#dcbd7a');m.material.emissive.set(done?'#86ca8d':'#e6bc6d');m.material.emissiveIntensity=done?2.1:1;});markers.forEach(m=>{const done=state.evidence.includes(m.site.id)||(m.site.id==='hub'&&state.status==='won');m.pending.visible=!done;m.checked.visible=done;m.group.lookAt(stage.camera.position);});recorderBatch?.update();stage.draw();}else{const c=stage.ctx,w=canvas.width=960,hh=canvas.height=540;c.fillStyle='#4c5a47';c.fillRect(0,0,w,hh);c.fillStyle='#25352c';c.fillRect(425,40,110,460);c.fillRect(190,240,580,45);sites.forEach(s=>{c.fillStyle='#bbe0aa';c.fillRect(480+s.x*16,340+s.z*10,35,30);c.font='20px system-ui';c.fillText(s.name,450+s.x*16,320+s.z*10);});c.fillStyle='#f7d999';c.beginPath();c.arc(480+player.x*16,340+player.z*10,10,0,Math.PI*2);c.fill();}q('[data-quest-location]').textContent=target?'前往'+target.name:'研究街区 / 自由漫游';}
 function planRoute(destination){
  const blocked=(x,z)=>x<-29||x>29||z<-32||z>22||obstacles.some(o=>x>o.x-o.w/2-.55&&x<o.x+o.w/2+.55&&z>o.z-o.d/2-.55&&z<o.z+o.d/2+.55);
  function nearest(x,z){let best=null;for(let dx=-3;dx<=3;dx++)for(let dz=-3;dz<=3;dz++){const xx=Math.round(x)+dx,zz=Math.round(z)+dz;if(!blocked(xx,zz)&&(!best||Math.hypot(xx-x,zz-z)<best.distance))best={x:xx,z:zz,distance:Math.hypot(xx-x,zz-z)};}return best;}
  const start=nearest(player.x,player.z),end=nearest(destination.x,destination.z);if(!start||!end)return [];
  const key=p=>p.x+','+p.z,startKey=key(start),endKey=key(end),queue=[start],previous=new Map([[startKey,null]]);let found=false;
  for(let n=0;n<queue.length;n++){const p=queue[n];if(key(p)===endKey){found=true;break;}for(const [dx,dz] of [[0,-1],[1,0],[-1,0],[0,1]]){const next={x:p.x+dx,z:p.z+dz},k=key(next);if(!blocked(next.x,next.z)&&!previous.has(k)){previous.set(k,key(p));queue.push(next);}}}
  if(!found)return [];const path=[];for(let k=endKey;k!==null;k=previous.get(k)){const [x,z]=k.split(',').map(Number);path.push({x,z});}path.reverse();path.push({x:destination.x,z:destination.z});return path;
 }
 const actorFinishing=()=>state?.status==='won'&&state.actorTime-(state.responses.hub?.at??-3)<2.2;
 const loop=questLoop(dt=>{state.actorTime+=dt;if(state.status==='playing'){state.elapsed+=dt;if(target&&!keys.size){const point=route[0]||target,dx=point.x-player.x,dz=point.z-player.z;if(Math.hypot(dx,dz)<.18){route.shift();if(!route.length){const s=target;target=null;dialog(s);}}else{player.yaw=Math.atan2(dx,-dz);moveFPS(player,new Set(['forward']),dt,{minX:-30,maxX:30,minZ:-33,maxZ:23},obstacles,6);}}else{if(keys.size){target=null;route=[];}moveFPS(player,keys,dt,{minX:-30,maxX:30,minZ:-33,maxZ:23},obstacles,5);}}},draw,()=>state?.status==='playing'||actorFinishing(),updateRecorders);
 shell.addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;
  if(b.dataset.questTab)panel(b.dataset.questTab);
  if(b.hasAttribute('data-quest-start')){state.status='playing';log('开始','程序化街区任务');audio.play(650,.2);sync();canvas.focus({preventScroll:true});loop.start();}
  if(b.hasAttribute('data-quest-reset')){loop.stop();reset();say('街区与记录已重置。');}
  if(b.dataset.questTravel){if(state.status!=='playing'){say('先开始街区任务。');return;}target=sites.find(s=>s.id===b.dataset.questTravel);route=planRoute(target);if(!route.length){target=null;say('暂时找不到安全路线，请先走到街道再尝试。');return;}log('前往',target.name);say('正在步行前往'+target.name);loop.start();}
  if(b.hasAttribute('data-quest-talk'))talk();
  if(b.dataset.questChoice&&state.status==='playing'){const s=sites.find(s=>s.id===b.dataset.site);if(Math.hypot(s.x+2.7-player.x,s.z-.8-player.z)>=3.3){say('你已离开'+s.name+'记录员，请走近后继续核对。');return;}if(b.dataset.questChoice==='good'&&!state.evidence.includes(s.id)){state.evidence.push(s.id);log('取得证据',s.evidence);audio.play(880,.22);sync();dialog(s,'confirm');say(s.name+'记录员确认完成，标牌、证据灯与终端记录同步。');}else if(b.dataset.questChoice==='bad'){respond(s,'review');q('[data-quest-feedback]').textContent='这会丢失核对依据，请换一种方法。';log('判断未通过',s.name);audio.play(170,.2,'triangle');draw();}}
  if(b.hasAttribute('data-quest-submit')&&state.status==='playing'&&state.evidence.length===3){const hub=sites[0];if(Math.hypot(hub.x+2.7-player.x,hub.z-.8-player.z)>=3.3){say('你已离开研究站记录员，请走近后提交归档。');return;}state.status='won';respond(hub,'confirm');log('任务完成','三份证据已归档');target=null;route=[];keys.clear();sync();say('任务完成，研究站记录员确认归档。');q('[data-quest-dialog]').innerHTML='<h4>归档完成 ✓</h4><p>可导出真实任务记录。</p>';audio.play(1000,.3);draw();loop.start();}
  if(b.hasAttribute('data-quest-sound')){b.textContent='提示声音：'+(audio.toggle()?'开':'关');b.setAttribute('aria-pressed',String(audio.enabled));audio.play();}
  if(b.hasAttribute('data-quest-export'))h.downloadFile('程序化街区任务记录.json',JSON.stringify(getState(),null,2),'application/json');
 },{signal});
 window.addEventListener('keydown',e=>{if(document.activeElement===canvas&&e.key.toLowerCase()==='e'){e.preventDefault();talk();}},{signal});
 function getState(){return {module:'quest',status:state.status,running:loop.active&&state.status==='playing',renderer:stage.supported?'webgl':'canvas',rendering:stage.supported?{drawCalls:stage.renderer.info.render.calls,triangles:stage.renderer.info.render.triangles,staticDrawCallsSaved:stage.scene.userData.staticDrawCallsSaved||0}:null,position:{x:+player.x.toFixed(2),z:+player.z.toFixed(2)},yaw:+player.yaw.toFixed(3),evidence:state.evidence.map(id=>({id,title:sites.find(s=>s.id===id).evidence})),elapsed:+state.elapsed.toFixed(1),destination:target?.id||null,dialogueSite:state.dialogueSite,interaction:{site:nearby().site.id,distance:+nearby().distance.toFixed(2),canTalk:state.status==='playing'&&nearby().distance<3.3,sites:sites.map(s=>({id:s.id,checked:state.evidence.includes(s.id)||(s.id==='hub'&&state.status==='won'),marker:s.id==='hub'?(state.status==='won'?'已归档':'提交证据'):state.evidence.includes(s.id)?'已核对':'待核对'}))},recorders:{clock:+state.actorTime.toFixed(3),animating:stage.supported&&loop.active&&(state.status==='playing'||actorFinishing()),actors:recorders.map(a=>a.getState())},soundEnabled:audio.enabled,assets:'Original modeled geometry, canvas labels and synthesized tones; local CC0 photo-scanned PBR textures and HDR lighting.',scope:'Original small RPG prototype with connected recorder poses, event-driven facial geometry and finite gaze; no speech lip-sync, original source, combat or VATS reproduced.',log:state.log.map(x=>({...x}))};}
 reset();return {getState,setActive(v){keys.clear();loop.setActive(v);if(!v)audio.suspend();},dispose(){loop.dispose();ctrl.abort();audio.dispose();stage.dispose();shell.remove();}};
}

