// Original scene craft: shaped foliage, layered building details, atmospheric sky and water.
// Source clips are references only; no source geometry or media is reused here.
import '../demo/runtime/vendor/three-r160.min.js';
const T=globalThis.THREE;
const rng=seed=>()=>{seed=(seed*16807)%2147483647;return (seed-1)/2147483646;};
export function addMesh(parent,geometry,material,x=0,y=0,z=0){const m=new T.Mesh(geometry,material);m.position.set(x,y,z);m.castShadow=m.receiveShadow=true;parent.add(m);return m;}
export function craftBox(parent,w,h,d,material,x=0,y=0,z=0){return addMesh(parent,new T.BoxGeometry(w,h,d),material,x,y,z);}
export function craftBeam(parent,a,b,radius,material){const start=new T.Vector3(...a),end=new T.Vector3(...b),vector=end.clone().sub(start);const m=addMesh(parent,new T.CylinderGeometry(radius*.82,radius,vector.length(),8),material);m.position.copy(start.add(end).multiplyScalar(.5));m.quaternion.setFromUnitVectors(new T.Vector3(0,1,0),vector.normalize());return m;}
// Keep detailed solids but batch their draw calls. Instanced leaves and animated objects remain separate.
export function batchStatic(group){group.updateMatrixWorld(true);const buckets=new Map(),inverse=group.matrixWorld.clone().invert();group.traverse(o=>{if(!o.isMesh||o.isInstancedMesh||Array.isArray(o.material)||o.material?.isShaderMaterial)return;const key=o.material;let bucket=buckets.get(key);if(!bucket){bucket=[];buckets.set(key,bucket);}bucket.push(o);});for(const [material,list] of buckets){if(list.length<3)continue;const positions=[],normals=[],uvs=[];for(const o of list){let g=o.geometry.clone();if(g.index){const next=g.toNonIndexed();g.dispose();g=next;}g.applyMatrix4(inverse.clone().multiply(o.matrixWorld));const p=g.attributes.position,n=g.attributes.normal,u=g.attributes.uv;positions.push(...p.array);if(n)normals.push(...n.array);else for(let i=0;i<p.count;i++)normals.push(0,1,0);if(u)uvs.push(...u.array);else for(let i=0;i<p.count;i++)uvs.push(0,0);o.parent.remove(o);g.dispose();}const merged=new T.BufferGeometry();merged.setAttribute('position',new T.Float32BufferAttribute(positions,3));merged.setAttribute('normal',new T.Float32BufferAttribute(normals,3));merged.setAttribute('uv',new T.Float32BufferAttribute(uvs,2));addMesh(group,merged,material);}return group;}
export function reliefTexture(kind='plaster',repeat=1){const c=document.createElement('canvas');c.width=c.height=512;const x=c.getContext('2d'),random=rng(912);x.fillStyle=kind==='roof'?'#bbb0a3':kind==='wood'?'#c4bcb1':'#e7e2d6';x.fillRect(0,0,512,512);for(let n=0;n<15000;n++){const white=random()>.5;x.fillStyle=white?'rgba(255,255,245,.15)':'rgba(39,31,22,.12)';x.fillRect(random()*512,random()*512,kind==='wood'?random()*35+3:random()*4+1,kind==='wood'?random()*1.5+.3:random()*3+1);}if(kind==='roof'){for(let row=0;row<16;row++)for(let col=-1;col<10;col++){const xx=col*58+(row%2)*29,yy=row*32;x.fillStyle=`rgba(21,14,12,${.1+random()*.15})`;x.fillRect(xx+2,yy+1,54,30);x.strokeStyle='#e9e1cf55';x.lineWidth=2;x.strokeRect(xx+2,yy+1,54,30);}}const t=new T.CanvasTexture(c);t.wrapS=t.wrapT=T.RepeatWrapping;t.repeat.set(repeat,repeat);t.colorSpace=T.SRGBColorSpace;t.anisotropy=8;return t;}
export function atmosphericSky(scene,{tropical=false}={}){
  const uniforms={top:{value:new T.Color(tropical?'#427fae':'#8b8f8c')},horizon:{value:new T.Color(tropical?'#d9e4db':'#f6d8a8')},sunDirection:{value:new T.Vector3(-.6,.23,-.7).normalize()},warmth:{value:.8},clouds:{value:tropical?.28:.18}};
  const mat=new T.ShaderMaterial({side:T.BackSide,depthWrite:false,uniforms,vertexShader:'varying vec3 vWorld;void main(){vWorld=position;gl_Position=projectionMatrix*modelViewMatrix*vec4(position,1.);}',fragmentShader:`varying vec3 vWorld;uniform vec3 top,horizon,sunDirection;uniform float warmth,clouds;float hash(vec2 p){return fract(sin(dot(p,vec2(127.1,311.7)))*43758.5453);}float noise(vec2 p){vec2 i=floor(p),f=fract(p);f=f*f*(3.-2.*f);return mix(mix(hash(i),hash(i+vec2(1.,0.)),f.x),mix(hash(i+vec2(0.,1.)),hash(i+vec2(1.,1.)),f.x),f.y);}void main(){vec3 d=normalize(vWorld);float h=max(d.y,0.);vec3 c=mix(horizon,top,pow(h,.48));float s=max(dot(d,sunDirection),0.);c+=vec3(1.,.64,.3)*pow(s,35.)*.19*warmth+c*.02;float n=noise(d.xz/max(.14,h)*2.8)*.65+noise(d.xz/max(.14,h)*7.)*.35;float cl=smoothstep(.56,.78,n)*smoothstep(.06,.38,h);c=mix(c,vec3(.93,.92,.86),cl*clouds*.65);c+=vec3(1.,.79,.48)*pow(s,900.)*2.*warmth;gl_FragColor=vec4(c,1.);}`});
  const sky=addMesh(scene,new T.SphereGeometry(65,32,16),mat);sky.castShadow=sky.receiveShadow=false;sky.frustumCulled=false;sky.renderOrder=-2;scene.userData.skyMesh=sky;
  return {update({top,horizon,sunDirection,warmth,clouds}={}){if(top)uniforms.top.value.set(top);if(horizon)uniforms.horizon.value.set(horizon);if(sunDirection)uniforms.sunDirection.value.copy(sunDirection).normalize();if(warmth!==undefined)uniforms.warmth.value=warmth;if(clouds!==undefined)uniforms.clouds.value=clouds;},mesh:sky};
}
function leafGeometry(){const g=new T.BufferGeometry(),v=[],i=[];for(let n=0;n<=4;n++){const f=n/4,w=Math.sin(f*Math.PI)*.085;v.push(-w,f*.32,Math.sin(f*Math.PI)*.027,w,f*.32,Math.sin(f*Math.PI)*.027);if(n<4){const a=n*2;i.push(a,a+1,a+2,a+1,a+3,a+2);}}g.setAttribute('position',new T.Float32BufferAttribute(v,3));g.setIndex(i);g.computeVertexNormals();return g;}
const broadLeaf=leafGeometry();broadLeaf.userData.shared=true;
export function deciduousTree(parent,{x=0,z=0,scale=1,seed=1,wood,leaf}={}){
  const random=rng(seed+357),group=new T.Group();group.position.set(x,0,z);group.scale.setScalar(scale);parent.add(group);const bark=wood||new T.MeshStandardMaterial({color:'#504432',roughness:1});const leaves=leaf||new T.MeshStandardMaterial({color:'#668747',roughness:.88,side:T.DoubleSide,emissive:'#345021',emissiveIntensity:.08});
  craftBeam(group,[0,0,0],[.13,3.7,0],.16,bark);const centers=[];
  for(let branch=0;branch<9;branch++){const a=branch*2.4+seed,y=2.4+(branch%3)*.43,end=[Math.cos(a)*(1.12+random()*.4),y+.45+random()*.5,Math.sin(a)*(1.12+random()*.4)];craftBeam(group,[.03,y-.65,0],end,.065,bark);centers.push(new T.Vector3(...end));}
  centers.push(new T.Vector3(0,4,0));const foliage=new T.InstancedMesh(broadLeaf,leaves,850),dummy=new T.Object3D(),color=new T.Color();
  for(let n=0;n<850;n++){const c=centers[n%centers.length],a=random()*Math.PI*2,b=Math.acos(random()*2-1),r=Math.pow(random(),.34)*.8;dummy.position.set(c.x+Math.sin(b)*Math.cos(a)*r,c.y+Math.cos(b)*r*.85,c.z+Math.sin(b)*Math.sin(a)*r);dummy.rotation.set(random()*Math.PI,random()*6.28,random()*6.28);dummy.scale.setScalar(1.05+random()*.6);dummy.updateMatrix();foliage.setMatrixAt(n,dummy.matrix);color.setHSL(.22+random()*.055,.34+random()*.23,.22+random()*.12);foliage.setColorAt(n,color);}foliage.castShadow=foliage.receiveShadow=true;group.add(foliage);batchStatic(group);return group;
}
function frondGeometry(){const v=[],idx=[];const point=f=>new T.Vector3(f*3.2,Math.sin(f*Math.PI)*.50-f*f*1.25,0);for(let n=1;n<27;n++){const f=n/28,c=point(f),length=Math.sin(f*Math.PI)*.69+.08;for(const side of [-1,1]){const start=v.length/3;for(let k=0;k<=3;k++){const q=k/3,width=Math.sin(q*Math.PI)*.054;const xx=c.x+q*.35,yy=c.y-q*q*.32+.08*Math.sin(q*Math.PI),zz=side*q*length;v.push(xx-width,yy,zz,xx+width,yy+.014,zz);}for(let k=0;k<3;k++){const a=start+k*2;idx.push(a,a+1,a+2,a+1,a+3,a+2);}}}const g=new T.BufferGeometry();g.setAttribute('position',new T.Float32BufferAttribute(v,3));g.setIndex(idx);g.computeVertexNormals();return g;}
const palmFrond=frondGeometry();palmFrond.userData.shared=true;
export function featherPalm(parent,{x=0,z=0,y=0,height=5,seed=1,wood,leaf}={}){
  const group=new T.Group();group.position.set(x,y,z);parent.add(group);const bend=Math.sin(seed*2.1)*.65,curve=new T.CatmullRomCurve3([new T.Vector3(0,0,0),new T.Vector3(bend*.18,height*.25,0),new T.Vector3(bend*.7,height*.7,.12),new T.Vector3(bend,height,.2)]);addMesh(group,new T.TubeGeometry(curve,18,.14,10,false),wood);
  // Trunk rings are actual relief; leaves are separate pinnate leaflets, never solid zigzag slabs.
  for(let n=1;n<19;n++){const p=curve.getPoint(n/20),ring=addMesh(group,new T.TorusGeometry(.148,.012,3,10),wood,p.x,p.y,p.z);ring.rotation.x=Math.PI/2;}
  const crown=new T.Group();crown.position.copy(curve.getPoint(1));group.add(crown);const leaves=new T.InstancedMesh(palmFrond,leaf,10),dummy=new T.Object3D();for(let n=0;n<10;n++){dummy.rotation.set((n%3-1)*.10,n*Math.PI*.2+seed*.11,.06+(n%3)*.12);dummy.scale.setScalar(.77+(n%4)*.09);dummy.updateMatrix();leaves.setMatrixAt(n,dummy.matrix);leaves.setColorAt(n,new T.Color().setHSL(.25+n*.003,.50,.35+(n%3)*.028));}leaves.castShadow=leaves.receiveShadow=true;crown.add(leaves);batchStatic(group);return group;
}
export function roofTiles(parent,{width,depth,height,rise,material}={}){const half=width/2,angle=Math.atan2(rise,half),slope=Math.hypot(half+.30,rise),unitW=.35,unitD=.36;for(const side of [-1,1]){const group=new T.Group();group.position.set(side*half/2,height+rise/2,0);group.rotation.z=-side*angle;parent.add(group);const count=Math.ceil(slope/unitW)*Math.ceil((depth+.55)/unitD),tile=new T.InstancedMesh(new T.BoxGeometry(unitW+.04,.075,unitD+.035),material,count),d=new T.Object3D();let n=0;for(let a=-slope/2;a<slope/2;a+=unitW)for(let b=-(depth+.55)/2;b<(depth+.55)/2;b+=unitD){d.position.set(a,.12+(Math.round(a/unitW)%2)*.009,b);d.rotation.set(0,0,0);d.updateMatrix();tile.setMatrixAt(n++,d.matrix);}tile.count=n;tile.castShadow=tile.receiveShadow=true;group.add(tile);} }
export function fabricCanopy(parent,width,depth,height,color){const g=new T.PlaneGeometry(width,depth,24,12);g.rotateX(-Math.PI/2);const p=g.attributes.position;for(let n=0;n<p.count;n++){const x=p.getX(n),z=p.getZ(n);p.setY(n,-.16*Math.sin((x/width+.5)*Math.PI)+Math.sin(x*15)*.018-z*.15);}g.computeVertexNormals();const c=document.createElement('canvas');c.width=256;c.height=64;const ctx=c.getContext('2d');for(let n=0;n<8;n++){ctx.fillStyle=n%2?'#e9dfc6':color;ctx.fillRect(n*32,0,32,64);}const t=new T.CanvasTexture(c);t.colorSpace=T.SRGBColorSpace;const mat=new T.MeshStandardMaterial({map:t,roughness:1,side:T.DoubleSide});const m=addMesh(parent,g,mat,0,height,0);for(let n=0;n<8;n++){const valance=craftBox(parent,width/8,.25,.045,new T.MeshStandardMaterial({color:n%2?'#e9dfc6':color,roughness:1}),(n+.5)*width/8-width/2,height-.27,depth/2);valance.position.y+=Math.sin(n)*.015;}return m;}
export function barrel(parent,wood,metal,x,y,z,size=.65){const g=new T.CylinderGeometry(size*.40,size*.36,size,12,4),p=g.attributes.position;for(let n=0;n<p.count;n++){const yy=p.getY(n),f=1+.12*(1-Math.pow(yy/(size*.5),2));p.setX(n,p.getX(n)*f);p.setZ(n,p.getZ(n)*f);}g.computeVertexNormals();const b=addMesh(parent,g,wood,x,y+size/2,z);for(const dy of [-size*.31,size*.31]){const band=addMesh(parent,new T.TorusGeometry(size*.413,.025,4,12),metal,x,y+size/2+dy,z);band.rotation.x=Math.PI/2;}return b;}
export function oceanMaterial(shore){return new T.ShaderMaterial({transparent:true,side:T.DoubleSide,depthWrite:false,uniforms:{time:{value:0},light:{value:1},shore:{value:shore},skyColor:{value:new T.Color('#bfd9df')},skyMap:{value:null},hasSky:{value:0},boat:{value:new T.Vector2(-15,7)}},vertexShader:`
+varying vec3 world;varying vec3 normalW;uniform float time;
+void main(){vec3 p=position;p.y+=sin(p.x*.75+time)*.12+sin(p.z*.52-time*.72)*.15;world=(modelMatrix*vec4(p,1.)).xyz;normalW=normalize(mat3(modelMatrix)*vec3(-cos(p.x*.75+time)*.09,1.,-cos(p.z*.52-time*.72)*.078));gl_Position=projectionMatrix*viewMatrix*vec4(world,1.);}`.replace(/^\+/gm,''),fragmentShader:`
+varying vec3 world;varying vec3 normalW;uniform float time,light,shore,hasSky;uniform vec3 skyColor;uniform sampler2D skyMap;uniform vec2 boat;
+float hash(vec2 p){return fract(sin(dot(p,vec2(127.1,311.7)))*43758.5453);}
+float noise(vec2 p){vec2 i=floor(p),f=fract(p);f=f*f*(3.-2.*f);return mix(mix(hash(i),hash(i+vec2(1.,0.)),f.x),mix(hash(i+vec2(0.,1.)),hash(i+vec2(1.,1.)),f.x),f.y);}
+float fineWave(vec2 p){return sin(p.x*3.4+p.y*2.2+time*1.30)*.030+cos(p.y*5.2-p.x*2.6-time*1.10)*.018+noise(p*8.+vec2(time*.16,-time*.21))*.022;}
+void main(){
+ float coast=shore+sin(world.z*.14)*1.1+sin(world.z*.38)*.45;if(world.x>coast+.18)discard;float depth=max(0.,coast-world.x);vec3 eye=normalize(cameraPosition-world);
+ float dx=(fineWave(world.xz+vec2(.02,0.))-fineWave(world.xz-vec2(.02,0.)))/.04;
+ float dz=(fineWave(world.xz+vec2(0.,.02))-fineWave(world.xz-vec2(0.,.02)))/.04;
+ vec2 bc=world.xz-boat;float br=length(bc);float contact=cos(br*8.-time*2.4)*exp(-br*.42)*.025;
+ vec3 ripple=normalize(normalW+vec3(-dx+bc.x/max(br,.1)*contact,0.,-dz+bc.y/max(br,.1)*contact));
+ float fresnel=.035+.965*pow(1.-max(dot(ripple,eye),0.),5.);
+ vec3 shallow=vec3(.035,.38,.27),deep=vec3(.008,.10,.17);vec3 color=mix(shallow,deep,smoothstep(0.,24.,depth));
+ float n=noise(world.xz*1.8+vec2(time*.08,time*.06));float caustic=pow(max(0.,sin((world.x+world.z*.74)*4.+n*7.-time*.5)),9.)+pow(max(0.,sin((world.z-world.x*.61)*4.3-n*5.+time*.6)),11.);
+ color+=vec3(.18,.32,.24)*caustic*.48*(1.-smoothstep(0.,11.,depth));
+ vec3 reflection=skyColor;vec3 reflected=reflect(-eye,ripple);if(hasSky>.5){vec2 uv=vec2(atan(reflected.z,reflected.x)/6.2831853+.5,acos(clamp(reflected.y,-1.,1.))/3.1415926);reflection=texture2D(skyMap,uv).rgb;reflection*=.7;}
+ color=mix(color,reflection,fresnel*.80);
+ float foam=pow(max(0.,sin(depth*5.-time*1.5+n*3.)),9.)*(1.-smoothstep(.05,2.,depth));
+ float hullFoam=pow(max(0.,sin(br*6.-time*2.)),18.)*exp(-br*.7)*.2;
+ color=mix(color,vec3(.89,.94,.81),clamp(foam*.72+hullFoam,0.,.8));
+ vec3 sun=normalize(vec3(-.5,.8,.3));float glint=pow(max(dot(reflect(-sun,ripple),eye),0.),90.);color+=vec3(1.,.92,.72)*glint*1.6;
+ color*=1.-exp(-dot(bc*vec2(.8,.42),bc*vec2(.8,.42)))*.13;
+ color=mix(color,skyColor,1.-exp(-length(world-cameraPosition)*.005));
+ float alpha=mix(.44,.95,smoothstep(0.,8.,depth));gl_FragColor=vec4(color*(.24+light*.76),alpha);
+#include <tonemapping_fragment>
+#include <colorspace_fragment>
+}`.replace(/^\+/gm,'')});}
