import {T,createStage,box,solid,label,lightScene,clamp,synth} from './four-playable-stage.js';
import {makeBall,batchStatic} from './games-art.js';
import {buildCoveredRallyArena,makeRallyCoupe} from './soccer-art.js?v=16';
import {createSoccerFeedback,createSoccerLoop} from './soccer-feedback.js';
export function mount(container,h){
 h.css('soccer.css');const ctrl=new AbortController(),signal=ctrl.signal,audio=synth(),shell=document.createElement('section');shell.className='lab-demo soccer-lab';
 shell.innerHTML='<div class="soccer-heading"><div><span>RALLY LAB / 三维车球物理</span><h3>驾驶、腾空，把球送进门</h3></div><b data-soccer-phase>等待开局</b></div><div class="soccer-scoreboard"><span>进球 <b data-soccer-score>0 / 3</b></span><span>剩余 <b data-soccer-time>90 秒</b></span><span>BOOST <b data-soccer-boost-value>100</b></span><span>球高 <b data-soccer-height>1.05</b></span></div><div class="soccer-viewport"><canvas class="lab-canvas soccer-canvas" tabindex="0" aria-label="三维车球竞技。W加速，AD转向，Shift加速推进，空格跳跃，C切换追车或跟球相机"></canvas><div class="soccer-camera-label" data-soccer-camera-label>CHASE CAM / 追车相机</div><div class="soccer-renderer" data-soccer-renderer></div><div class="soccer-goal" data-soccer-goal></div><div class="soccer-speedhud"><div><b data-soccer-speed>0.0</b><small> m/s</small></div><span data-soccer-drivecue>准备出发</span></div></div><div class="soccer-control-grid"><div class="soccer-pad"><button class="lab-button" data-soccer-move="forward">↑ 加速</button><button class="lab-button" data-soccer-move="left">← 转向</button><button class="lab-button" data-soccer-move="back">↓ 倒车</button><button class="lab-button" data-soccer-move="right">转向 →</button><button class="lab-button primary" data-soccer-boost>BOOST · 长按</button><button class="lab-button" data-soccer-jump>跳跃 · 空格</button><button class="lab-button" data-soccer-brake>刹车 · X</button><button class="lab-button" data-soccer-camera>切换跟球相机 · C</button></div><div class="soccer-physics"><label class="lab-field">滚动摩擦 <output data-soccer-friction-value>20%</output><input type="range" min="0" max="100" value="20" data-soccer-friction></label><label class="lab-field">球体弹性 <output data-soccer-restitution-value>72%</output><input type="range" min="10" max="95" value="72" data-soccer-restitution></label></div></div><p class="soccer-rule">W / ↑ 加速，S / ↓ 倒车，A D / ← → 转向；Shift 长按 BOOST，空格跳跃，X 刹车，C 换相机。手机长按驾驶和 BOOST 按钮。目标是远端橙色球门，90 秒内进 3 球。</p><div class="lab-controls"><button class="lab-button primary" data-soccer-start>开始三维车球挑战</button><button class="lab-button" data-soccer-reset>重置比赛</button><button class="lab-button" data-soccer-export>导出物理体验记录 JSON</button></div><p class="lab-status" role="status" data-soccer-status>原创场馆、车辆与简化三维物理。球与车辆具有真实高度、重力和碰撞；不含原作空中翻滚、联机或完整车辆刚体模拟。</p>';container.append(shell);const q=s=>shell.querySelector(s),stage=createStage(q('canvas'),{background:'#accbdc',fov:66}),canvas=stage.canvas,keys=new Set();let state,carModel,ballModel,ballShadow,carShadow,boostFlame,carFeedback,ballSpinX=0,ballSpinZ=0,flash=0,camFresh=true,frameDt=1/60,wheelAngle=0;const lookTarget=new T.Vector3();
 const say=t=>{q('[data-soccer-status]').textContent=t;h.onStatus(t);};
 if(stage.supported){
  const sun=lightScene(stage,{sky:'#d9ecf4',ground:'#263f43',power:.75,sun:3.1});sun.position.set(-29,26,14);sun.shadow.mapSize.set(2048,2048);sun.shadow.normalBias=.025;buildCoveredRallyArena(stage);batchStatic(stage.scene);carModel=makeRallyCoupe();carFeedback=createSoccerFeedback(carModel);boostFlame=carModel.userData.flame;stage.scene.add(carModel);ballModel=makeBall();stage.scene.add(ballModel);
  ballShadow=solid(new T.CircleGeometry(1.2,32),'#173c36',{transparent:true,opacity:.25,depthWrite:false});ballShadow.rotation.x=-Math.PI/2;carShadow=solid(new T.CircleGeometry(1.5,32),'#173c36',{transparent:true,opacity:.25,depthWrite:false});carShadow.rotation.x=-Math.PI/2;stage.scene.add(ballShadow,carShadow);
 }
 q('[data-soccer-renderer]').textContent=stage.supported?'RALLY LAB / 车球挑战':'二维驾驶模式';
 function roundReset(){state.car={x:0,y:.65,z:17,vx:0,vy:0,vz:0,yaw:0};state.ball={x:[0,-3,3][state.score%3],y:1.05,z:8,vx:0,vy:0,vz:0};keys.clear();camFresh=true;wheelAngle=0;ballSpinX=ballSpinZ=0;carFeedback?.reset();}
 function reset(){state={status:'ready',score:0,elapsed:0,remaining:90,boost:100,boosting:false,friction:20,restitution:72,cameraMode:'chase',collisions:0,jumps:0,maxBallHeight:1.05,log:[]};carFeedback?.reset(true);roundReset();flash=0;q('[data-soccer-friction]').value='20';q('[data-soccer-restitution]').value='72';sync();draw();}
 function sync(){q('[data-soccer-score]').textContent=state.score+' / 3';q('[data-soccer-time]').textContent=Math.ceil(state.remaining)+' 秒';q('[data-soccer-boost-value]').textContent=Math.round(state.boost);q('[data-soccer-height]').textContent=state.ball.y.toFixed(2);q('[data-soccer-friction-value]').textContent=state.friction+'%';q('[data-soccer-restitution-value]').textContent=state.restitution+'%';q('[data-soccer-phase]').textContent=({ready:'等待开局',playing:'车球挑战进行中',won:'三球达成 ✓',lost:'时间结束'}[state.status]);q('[data-soccer-start]').textContent=({ready:'开始三维车球挑战',playing:'挑战进行中',won:'挑战已完成',lost:'挑战已结束'}[state.status]);q('[data-soccer-start]').disabled=state.status!=='ready';q('[data-soccer-camera]').textContent=state.cameraMode==='chase'?'切换跟球相机 · C':'切换追车相机 · C';q('[data-soccer-camera-label]').textContent=state.cameraMode==='chase'?'CHASE CAM / 追车相机':'BALL CAM / 跟球相机';q('[data-soccer-goal]').textContent=flash>0?'GOAL! 进球':'';const speed=Math.hypot(state.car.vx,state.car.vz);q('[data-soccer-speed]').textContent=speed.toFixed(1);q('[data-soccer-drivecue]').textContent=state.status!=='playing'?({ready:'准备出发',won:'目标达成',lost:'挑战结束'}[state.status]):state.boosting?'BOOST 推进':keys.has('forward')||keys.has('back')?'驱动中':speed>1?'惯性滑行':'低速调整';}
 function jump(){if(state.status!=='playing'||!loop.active||state.car.y>.7)return;state.car.vy=7.2;state.jumps++;audio.play(450,.15);state.log.push({time:+state.elapsed.toFixed(1),action:'车辆跳跃'});}
 function brake(){if(state.status!=='playing'||!loop.active)return;const c=state.car,oldVx=c.vx,oldVz=c.vz;c.vx*=.12;c.vz*=.12;carFeedback?.step({car:c,forwardAcceleration:((c.vx-oldVx)*Math.sin(c.yaw)-(c.vz-oldVz)*Math.cos(c.yaw))/.05,lateralAcceleration:0,landed:false,landingSpeed:0,impulse:0,impulseForward:0,impulseSide:0,brakeDelta:(c.vx-oldVx)*Math.sin(c.yaw)-(c.vz-oldVz)*Math.cos(c.yaw)},.009);draw();sync();}
 function cameraToggle(){state.cameraMode=state.cameraMode==='chase'?'ball':'chase';sync();draw();}
 function goal(){state.score++;flash=1.3;state.log.push({time:+state.elapsed.toFixed(1),action:'进球',score:state.score,friction:state.friction,restitution:state.restitution});audio.play(900,.3);if(state.score===3){state.status='won';say('三球达成！耗时 '+state.elapsed.toFixed(1)+' 秒。');}else{say('第 '+state.score+' 球，下一球换了横向位置。');roundReset();}}
 function physics(dt){const c=state.car,b=state.ball,oldVx=c.vx,oldVz=c.vz,oldBallX=b.x,oldBallZ=b.z;let landed=false,landingSpeed=0,contactImpulse=0,impulseForward=0,impulseSide=0;const e=state.restitution/100,f=Number(keys.has('forward'))-Number(keys.has('back')),turn=Number(keys.has('right'))-Number(keys.has('left')),speed=Math.hypot(c.vx,c.vz);c.yaw+=turn*1.9*clamp(speed/7,.28,1)*dt*(f<0?-1:1);state.boosting=keys.has('boost')&&state.boost>0;state.boost=clamp(state.boost+(state.boosting?-28:8)*dt,0,100);const force=18*f+(state.boosting?26:0);c.vx+=Math.sin(c.yaw)*force*dt;c.vz-=Math.cos(c.yaw)*force*dt;const drag=.7+state.friction/100*1.8;c.vx*=Math.exp(-drag*dt);c.vz*=Math.exp(-drag*dt);const lateral=c.vx*Math.cos(c.yaw)+c.vz*Math.sin(c.yaw);c.vx-=Math.cos(c.yaw)*lateral*Math.min(1,dt*5);c.vz-=Math.sin(c.yaw)*lateral*Math.min(1,dt*5);const top=state.boosting?29:19,s=Math.hypot(c.vx,c.vz);if(s>top){c.vx*=top/s;c.vz*=top/s;}wheelAngle-=(c.vx*Math.sin(c.yaw)-c.vz*Math.cos(c.yaw))*dt/.38;c.vy-=12*dt;c.x+=c.vx*dt;c.z+=c.vz*dt;c.y+=c.vy*dt;if(c.y<.65){landed=c.vy<-.5&&c.y-c.vy*dt>.651;landingSpeed=landed?-c.vy:0;c.y=.65;c.vy=0;}b.vy-=9.8*dt;const rolling=b.y<=1.08?(.08+state.friction/100*.9):.04;b.vx*=Math.exp(-rolling*dt);b.vz*=Math.exp(-rolling*dt);b.x+=b.vx*dt;b.z+=b.vz*dt;b.y+=b.vy*dt;if(b.y<1.05){b.y=1.05;b.vy=Math.abs(b.vy)*e;if(b.vy<.3)b.vy=0;}
  const dx=b.x-c.x,dy=b.y-c.y,dz=b.z-c.z,d=Math.hypot(dx,dy,dz),r=2.3;if(d<r){const nx=dx/(d||1),ny=dy/(d||1),nz=dz/(d||1),over=r-d;b.x+=nx*over*.8;b.y+=ny*over*.8;b.z+=nz*over*.8;c.x-=nx*over*.2;c.z-=nz*over*.2;const rel=(b.vx-c.vx)*nx+(b.vy-c.vy)*ny+(b.vz-c.vz)*nz;if(rel<0){const impulse=-(1+e)*rel/1.333;b.vx+=impulse*nx;b.vy+=impulse*ny;b.vz+=impulse*nz;c.vx-=impulse*nx/3;c.vz-=impulse*nz/3;state.collisions++;contactImpulse=impulse;impulseForward=impulse*(nx*Math.sin(c.yaw)-nz*Math.cos(c.yaw))/3;impulseSide=impulse*(nx*Math.cos(c.yaw)+nz*Math.sin(c.yaw))/3;audio.play(140,.07,'triangle');}}
  if(b.z<-27&&Math.abs(b.x)<4.5&&b.y<3.1){goal();return;}for(const obj of [c,b]){const rad=obj===c?1.15:1.05;if(obj.x<-20+rad){obj.x=-20+rad;obj.vx=Math.abs(obj.vx)*e;}if(obj.x>20-rad){obj.x=20-rad;obj.vx=-Math.abs(obj.vx)*e;}const opening=obj===b&&Math.abs(b.x)<4.5&&b.y<3.1;if(obj.z<-27+rad&&!opening){obj.z=-27+rad;obj.vz=Math.abs(obj.vz)*e;}if(obj.z>27-rad){obj.z=27-rad;obj.vz=-Math.abs(obj.vz)*e;}}
  if(b.y>15){b.y=15;b.vy=-Math.abs(b.vy)*e;}state.maxBallHeight=Math.max(state.maxBallHeight,b.y);ballSpinX+=(b.z-oldBallZ)/1.05;ballSpinZ-=(b.x-oldBallX)/1.05;carFeedback?.step({car:c,forwardAcceleration:((c.vx-oldVx)*Math.sin(c.yaw)-(c.vz-oldVz)*Math.cos(c.yaw))/dt,lateralAcceleration:((c.vx-oldVx)*Math.cos(c.yaw)+(c.vz-oldVz)*Math.sin(c.yaw))/dt,landed,landingSpeed,impulse:contactImpulse,impulseForward,impulseSide},dt);
 }
 function draw(){if(stage.supported){const c=state.car,b=state.ball;carModel.position.set(c.x,c.y,c.z);carModel.rotation.y=-c.yaw;carFeedback.draw(wheelAngle,Number(keys.has('right'))-Number(keys.has('left')));boostFlame.visible=state.boosting;boostFlame.scale.z=.86+Math.sin(state.elapsed*48)*.14;ballModel.position.set(b.x,b.y,b.z);ballModel.rotation.x=ballSpinX;ballModel.rotation.z=ballSpinZ;ballShadow.position.set(b.x,.07,b.z);ballShadow.scale.setScalar(clamp(1-b.y*.025,.55,1));carShadow.position.set(c.x,.06,c.z);const speed=Math.hypot(c.vx,c.vz);let fx=Math.sin(c.yaw),fz=-Math.cos(c.yaw);if(state.cameraMode==='ball'){const d=Math.hypot(b.x-c.x,b.z-c.z);if(d>2.6){fx=(b.x-c.x)/d;fz=(b.z-c.z)/d;}}const distance=6.4+Math.min(2.2,speed*.09),desired=new T.Vector3(clamp(c.x-fx*distance+fz*.7,-25,25),c.y+3+Math.min(.5,speed*.025),clamp(c.z-fz*distance-fx*.7,-31,31)),motionX=speed>1&&(c.vx*Math.sin(c.yaw)-c.vz*Math.cos(c.yaw))>0?c.vx/speed:fx,motionZ=speed>1&&(c.vx*Math.sin(c.yaw)-c.vz*Math.cos(c.yaw))>0?c.vz/speed:fz,ahead=4.5+Math.min(3,speed*.18),target=state.cameraMode==='ball'?new T.Vector3(b.x,b.y,b.z):new T.Vector3(c.x+motionX*ahead,c.y+.7,c.z+motionZ*ahead),fov=66+Math.min(8,speed*.27)+(state.boosting?2:0);if(camFresh){stage.camera.position.copy(desired);lookTarget.copy(target);stage.camera.fov=fov;camFresh=false;}else{stage.camera.position.lerp(desired,1-Math.exp(-7*frameDt));lookTarget.lerp(target,1-Math.exp(-9*frameDt));stage.camera.fov+=(fov-stage.camera.fov)*(1-Math.exp(-4*frameDt));}stage.camera.lookAt(lookTarget);stage.camera.updateProjectionMatrix();stage.draw();}else{const g=stage.ctx,w=canvas.width=960,hh=canvas.height=540;g.fillStyle='#254d48';g.fillRect(0,0,w,hh);g.strokeStyle='#cce3be';g.strokeRect(120,30,720,480);g.strokeRect(405,5,150,40);g.fillStyle='#edc26c';g.fillRect(480+state.car.x*16-12,270+state.car.z*8-20,24,40);g.fillStyle='#e8ede2';g.beginPath();g.arc(480+state.ball.x*16,270+state.ball.z*8,14,0,Math.PI*2);g.fill();}}
 const loop=createSoccerLoop(dt=>{const used=Math.min(dt,state.remaining);frameDt=used;state.elapsed+=used;state.remaining=Math.max(0,90-state.elapsed);flash=Math.max(0,flash-used);for(let i=0,n=Math.ceil(used/.009);i<n&&state.status==='playing';i++)physics(used/n);if(state.remaining===0&&state.status==='playing'){state.status='lost';say('时间结束，进球 '+state.score+' / 3。');}sync();},draw,()=>state?.status==='playing');
 const mapping={w:'forward',ArrowUp:'forward',s:'back',ArrowDown:'back',a:'left',ArrowLeft:'left',d:'right',ArrowRight:'right',Shift:'boost'};
 window.addEventListener('keydown',e=>{if(document.activeElement!==canvas||state.status!=='playing'||!loop.active)return;const k=mapping[e.key]||mapping[e.key.toLowerCase()];if(k){e.preventDefault();keys.add(k);}if(!e.repeat&&e.code==='Space'){e.preventDefault();jump();}if(!e.repeat&&e.key.toLowerCase()==='c'){e.preventDefault();cameraToggle();}if(e.key.toLowerCase()==='x'){e.preventDefault();brake();}},{signal});
 window.addEventListener('keyup',e=>keys.delete(mapping[e.key]||mapping[e.key.toLowerCase()]),{signal});window.addEventListener('blur',()=>keys.clear(),{signal});canvas.addEventListener('pointerdown',()=>canvas.focus({preventScroll:true}),{signal});
 shell.querySelectorAll('[data-soccer-move],[data-soccer-boost]').forEach(b=>{const k=b.dataset.soccerMove||'boost';b.addEventListener('pointerdown',e=>{e.preventDefault();if(state.status==='playing'&&loop.active){keys.add(k);b.setPointerCapture(e.pointerId);canvas.focus({preventScroll:true});}},{signal});b.addEventListener('pointerup',()=>keys.delete(k),{signal});b.addEventListener('pointercancel',()=>keys.delete(k),{signal});});
 shell.addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;if(b.hasAttribute('data-soccer-start')){state.status='playing';sync();canvas.focus({preventScroll:true});loop.start();say('向远端橙色球门推进。先直行，观察撞球后真实弹起。');}if(b.hasAttribute('data-soccer-reset')){loop.stop();reset();say('比赛已重置。');}if(b.hasAttribute('data-soccer-camera'))cameraToggle();if(b.hasAttribute('data-soccer-brake'))brake();if(b.hasAttribute('data-soccer-jump'))jump();if(b.hasAttribute('data-soccer-export'))h.downloadFile('三维车球物理记录.json',JSON.stringify(getState(),null,2),'application/json');},{signal});
 shell.addEventListener('input',e=>{if(e.target.hasAttribute('data-soccer-friction'))state.friction=+e.target.value;if(e.target.hasAttribute('data-soccer-restitution'))state.restitution=+e.target.value;sync();},{signal});
 function getState(){const round=o=>Object.fromEntries(Object.entries(o).map(([k,v])=>[k,+v.toFixed(3)]));return {module:'soccer',status:state.status,running:loop.active&&state.status==='playing',renderer:stage.supported?'webgl':'canvas',arenaArtwork:stage.supported?{...stage.scene.userData.rallyArena}:null,vehicleArtwork:carModel?.userData.design||null,rendering:stage.supported?{drawCalls:stage.renderer.info.render.calls,triangles:stage.renderer.info.render.triangles,staticDrawCallsSaved:stage.scene.userData.staticDrawCallsSaved||0}:null,score:state.score,goal:3,remaining:+state.remaining.toFixed(1),elapsed:+state.elapsed.toFixed(1),boost:+state.boost.toFixed(1),boosting:state.boosting,friction:state.friction,restitution:state.restitution,cameraMode:state.cameraMode,speed:+Math.hypot(state.car.vx,state.car.vz).toFixed(2),cameraFov:stage.supported?+stage.camera.fov.toFixed(2):null,cameraTarget:stage.supported?round({x:lookTarget.x,y:lookTarget.y,z:lookTarget.z}):null,cameraPosition:stage.supported?round({x:stage.camera.position.x,y:stage.camera.position.y,z:stage.camera.position.z}):null,collisions:state.collisions,jumps:state.jumps,vehicleFeedback:carFeedback?.getState()||null,wheelRotationX:+wheelAngle.toFixed(4),ballRotation:{x:+ballSpinX.toFixed(3),z:+ballSpinZ.toFixed(3)},maxBallHeight:+state.maxBallHeight.toFixed(3),car:round(state.car),ball:round(state.ball),scope:'Original simplified 3D sphere contacts, gravity, ground traction and goals; no full car rigid-body, air roll or multiplayer.',log:state.log.map(x=>({...x}))};}
 reset();return {getState,setActive(v){keys.clear();loop.setActive(v);if(!v)audio.suspend();},dispose(){loop.dispose();ctrl.abort();audio.dispose();stage.dispose();shell.remove();}};
}


