// CASE 07: our original procedural research market. The source clip's tooling is unconfirmed.
import '../demo/runtime/vendor/three-r160.min.js';
import {surfaceTexture} from './world-stage.js';
import {batchStatic,atmosphericSky,roofTiles,fabricCanopy,barrel,reliefTexture,craftBox,addMesh} from './scenic-craft.js';

import {pbrMaterial,photoEnvironment,roundedBoxGeometry} from './visual-materials.js';
import {exhibitContents,buildExhibit} from './village-exhibits.js';
import {buildLaneHouse} from './village-architecture.js?v=16';
import {marketTree} from './village-trees.js?v=16-r2';
const T = globalThis.THREE;
const clamp = (value, min, max) => Math.min(max, Math.max(min, value));
const booths = [
  {id:'visual-systems',number:'01',title:'视觉系统展位',color:'#477c62',category:'品牌与展示',description:'把研究成果做成可复用的网页与视觉系统。这里展示品牌叙事、主题皮肤与交互展陈的组合。',takeaway:'一个研究集市可以承载多个作品展位，点击后呈现各项目的用途与下一步。'},
  {id:'product-lab',number:'02',title:'产品原型展位',color:'#b9724f',category:'交互与产品',description:'将产品概念变成可操作的原型：访问者选择展位、观察三维场景，并留下实际参观记录。',takeaway:'空间展示与项目详情共享展位数据，适合线上产品发布会或创作成果展。'},
  {id:'research-notes',number:'03',title:'研究档案展位',color:'#4a7183',category:'研究与知识',description:'用可浏览的空间串起案例、结论与来源。参观任务帮助访客主动探索，而非只阅读一份长文档。',takeaway:'可在活动后导出访问记录，检查哪些研究主题被看过，并生成个人回顾。'}
].map(booth=>({...booth,...exhibitContents[booth.id]}));
const entryPose={x:-2.55,z:10.8,yaw:.04,pitch:-.02};
const boothSites={ 'visual-systems':{x:-4.6,z:-.3,yaw:.13,approach:{x:-4.35,z:2.0,yaw:.1,pitch:0}}, 'product-lab':{x:2.6,z:-6.1,yaw:.1,approach:{x:2.8,z:-3.9,yaw:.1,pitch:0}}, 'research-notes':{x:4.5,z:.2,yaw:-.12,approach:{x:5.4,z:2.5,yaw:.37,pitch:0}}};
const times = {morning:{label:'晨光',sky:'#c6dfdf',sun:'#fff3d3',ground:'#527657',ambient:.95,intensity:2.7},dusk:{label:'黄昏',sky:'#ecd7ad',sun:'#ffc47b',ground:'#707048',ambient:.60,intensity:2.35},night:{label:'夜景',sky:'#233447',sun:'#8abde6',ground:'#223a39',ambient:.7,intensity:.8}};

export function mount(container,h){
  h.css('village.css');
  const state={time:'dusk',treeDensity:20,selected:null,visits:[],view:{yaw:.40,elevation:.54,distance:34},mode:'walk',position:{...entryPose},discovered:[],reached:[],walkingDistance:0,proximity:null,renderer:'loading'};
  let alive=true,active=true,renderer,scene,camera,sun,hemisphere,treeGroup,windowMaterial,treeTrunkGeometry,treeCrownGeometry,renderCount=0,skyCraft,photoLight;
  const textures=[],materials=[],geometries=[],listeners=[];
  const keys=new Set(),colliders=[],buildings=[],nearArchitecture=[],architectureGlass=[],stallGroups=new Map(),exhibitModels=new Map();let walkFrame=0,lastWalk=0;
  const off=(node,event,handler,options)=>{node.addEventListener(event,handler,options);listeners.push(()=>node.removeEventListener(event,handler,options));};
  const esc=h.escape || (value=>String(value).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c])));
  container.innerHTML=`<section class="village-lab lab-demo"><div class="village-layout"><div class="village-stage"><canvas class="lab-canvas" tabindex="0" aria-label="研究集市三维场景：拖动或方向键环绕，点击三个展位查看研究成果"></canvas><div class="village-scene-caption"><strong>RESEARCH MARKET · 07</strong><span data-scene-time>黄昏 / 原创程序化场景</span></div><div class="village-camera-bar"><div class="village-camera-actions"><button type="button" data-camera="left" aria-label="向左环绕">↶</button><button type="button" data-camera="right" aria-label="向右环绕">↷</button><button type="button" data-camera="in" aria-label="拉近场景">＋</button><button type="button" data-camera="out" aria-label="拉远场景">−</button><button type="button" data-camera="reset" aria-label="恢复全景">⌂</button></div><span class="village-camera-hint">拖动环绕 · 滚轮缩放 · 点击展位</span></div></div><div class="village-panel"><section class="lab-controls"><h4 class="village-section-title">01 / 编辑展会环境</h4><div class="village-time-controls">${Object.entries(times).map(([key,value])=>`<button type="button" class="lab-button" data-time="${key}" aria-pressed="${key===state.time}">${value.label}</button>`).join('')}</div><label class="village-density" for="village-tree-density">树木密度 <output data-density>${state.treeDensity} 棵</output></label><input id="village-tree-density" type="range" min="0" max="24" value="${state.treeDensity}" step="1" aria-label="树木密度"></section><section class="lab-controls"><h4 class="village-section-title">02 / 参观研究展位</h4><div class="village-stall-buttons">${booths.map(booth=>`<button type="button" class="village-stall-button" data-booth="${booth.id}" aria-pressed="false" data-visited="false"><span>${booth.number} ${booth.title}</span><small>未发现 · 带我参观 →</small></button>`).join('')}</div></section><article class="village-exhibit" aria-live="polite"><span class="village-exhibit-tag">SELECT AN EXHIBIT</span><h4>进入我们的研究集市</h4><p>从入口石巷走进主广场，观察建筑后逐渐露出的展位；走近后按 E 查看。右侧列表提供明确的直达参观入口。</p></article><section class="village-task"><strong data-progress-label>参观任务 · 0 / 3</strong><div class="village-progress" aria-hidden="true">${booths.map(()=>'<i data-done="false"></i>').join('')}</div><p data-progress-copy>从石巷走入广场，发现并参观三处展位。列表按钮也可直接带你到展位。</p></section><section class="village-handoff"><div class="village-export-controls"><button type="button" class="lab-button primary" data-export="json">导出参观记录</button><button type="button" class="lab-button" data-export="png">保存场景 PNG</button></div><p data-village-status role="status">正在建立三维集市…</p><p class="village-note">原创场景几何与交互，使用 Poly Haven CC0 摄影材质和天空光照。原作者工具链未公开。</p></section></div></div></section>`;
  const q=selector=>container.querySelector(selector),qa=selector=>[...container.querySelectorAll(selector)];
  q('.village-camera-hint').textContent='拖动看向 · WASD / 下方按钮步行';
  q('.village-camera-actions').insertAdjacentHTML('afterend','<button class="lab-button village-mode-button" type="button" data-mode>切换布局鸟瞰</button>');
  q('.village-stage').insertAdjacentHTML('afterend','<div class="village-walk-panel"><div class="village-walk-buttons"><button class="lab-button" data-walk="forward" type="button">前进 ↑</button><button class="lab-button" data-walk="left" type="button">左移 ←</button><button class="lab-button" data-walk="back" type="button">后退 ↓</button><button class="lab-button" data-walk="right" type="button">右移 →</button><button class="lab-button primary" data-interact type="button">查看附近展位</button></div><p data-arrival>沿石路走近展位，再查看研究内容。原作参考：眼平村镇集市与黄昏空间光线。</p></div>');
  q('.village-stage').insertAdjacentHTML('beforeend','<div class="village-proximity" data-proximity hidden><span data-proximity-number></span><div><b data-proximity-role></b><small data-proximity-action></small></div></div>');
  const sceneColumn=document.createElement('div');sceneColumn.className='village-scene-column';const sceneStage=q('.village-stage'),walkPanel=q('.village-walk-panel');sceneStage.before(sceneColumn);sceneColumn.append(sceneStage,walkPanel);
  const canvas=q('canvas');
  const status=text=>{q('[data-village-status]').textContent=text;h.onStatus?.(text);};
  const mat=(color,extra={})=>{const item=new T.MeshStandardMaterial({color,roughness:.85,...extra});materials.push(item);return item;};
  const geo=item=>{geometries.push(item);return item;};
  const palette={wood:mat('#594631'),plaster:mat('#ead7b7'),roof:mat('#9c5744'),stone:mat('#b0a891'),leaf:mat('#e2eed4',{side:T.DoubleSide,emissive:'#324524',emissiveIntensity:.07}),leafLight:mat('#c8dcae',{side:T.DoubleSide}),trunk:mat('#675441'),copper:mat('#6e7669',{metalness:.5}),soil:mat('#65734e')};
  palette.plaster.bumpMap=reliefTexture('plaster',2);palette.plaster.bumpScale=.10;palette.roof.map=reliefTexture('roof',2);palette.roof.bumpMap=palette.roof.map;palette.roof.bumpScale=.07;
  palette.wood=pbrMaterial('brown_planks_03',{repeat:[1,1],normal:.25,color:'#dfc4a3',onLoad:()=>draw()});palette.trunk=pbrMaterial('brown_planks_03',{repeat:[1,3],normal:.4,color:'#9d8669',onLoad:()=>draw()});
  for(const key of ['stone']){const texture=surfaceTexture(key==='stone'?'stone':'wood',key==='stone'?2:1);textures.push(texture);palette[key].map=texture;palette[key].roughness=.93;}
  function mesh(geometry,material,x=0,y=0,z=0,parent=scene){const item=new T.Mesh(geometry,material);item.position.set(x,y,z);item.castShadow=true;item.receiveShadow=true;parent.add(item);return item;}
  function box(w,height,depth,material,x,y,z,parent=scene){return mesh(geo(new T.BoxGeometry(w,height,depth)),material,x,y,z,parent);}
  function beam(start,end,width,material,parent){const a=new T.Vector3(...start),b=new T.Vector3(...end),line=b.clone().sub(a);const item=box(width,line.length(),width,material,0,0,0,parent);item.position.copy(a.clone().add(b).multiplyScalar(.5));item.quaternion.setFromUnitVectors(new T.Vector3(0,1,0),line.normalize());return item;}
  function labelTexture(text,subtitle){const c=document.createElement('canvas');c.width=512;c.height=160;const ctx=c.getContext('2d');ctx.fillStyle='#f9eccb';ctx.fillRect(0,0,512,160);ctx.strokeStyle='#765636';ctx.lineWidth=8;ctx.strokeRect(5,5,502,150);ctx.fillStyle='#354b34';ctx.textAlign='center';ctx.font='bold 39px sans-serif';ctx.fillText(text,256,70);ctx.font='19px sans-serif';ctx.fillStyle='#9d7047';ctx.fillText(subtitle,256,116);const texture=new T.CanvasTexture(c);texture.colorSpace=T.SRGBColorSpace;textures.push(texture);return texture;}
  function pavingTexture(){const c=document.createElement('canvas');c.width=c.height=512;const ctx=c.getContext('2d');ctx.fillStyle='#8f9079';ctx.fillRect(0,0,512,512);let seed=47;const random=()=>{seed=(seed*16807)%2147483647;return (seed-1)/2147483646;};for(let row=0;row<16;row++){for(let col=-1;col<16;col++){const x=col*36+(row%2)*18,y=row*32;const shade=155+Math.round(random()*30);ctx.fillStyle=`rgb(${shade+8},${shade+5},${shade-9})`;ctx.fillRect(x+1,y+1,33,29);ctx.strokeStyle='rgba(63,62,42,.2)';ctx.strokeRect(x+1,y+1,33,29);}}const texture=new T.CanvasTexture(c);texture.colorSpace=T.SRGBColorSpace;texture.wrapS=texture.wrapT=T.RepeatWrapping;texture.repeat.set(4,4);textures.push(texture);return texture;}
  function house(x,z,width=3.7,height=4.0,depth=3.5,rotation=0,laneDetail=null){
    const group=new T.Group();group.position.set(x,0,z);group.rotation.y=rotation;group.userData.building=true;buildings.push(group);scene.add(group);
    colliders.push({minX:x-width/2-.15,maxX:x+width/2+.15,minZ:z-depth/2-.15,maxZ:z+depth/2+.15});
    if(laneDetail!==null){const detail=buildLaneHouse(group,{T,width,height,depth,index:laneDetail,mat,geo,mesh,box,beam,palette,registerGlass:m=>architectureGlass.push(m),onLoad:()=>draw(),textures,batchStatic,roofTiles});nearArchitecture.push({position:{x,z},width,height,depth,...detail});return group;}
    box(width,height,depth,palette.plaster,0,height/2,0,group);box(width+.12,.65,depth+.12,palette.stone,0,.30,0,group);
    for(const side of [-1,1])for(let row=0;row<3;row++)for(let n=0;n<Math.ceil(width/.7);n++){const stone=box(.64,.20,.16,palette.stone,-width/2+.35+n*.7+(row%2)*.09,.15+row*.23,side*(depth/2+.08),group);stone.rotation.z=Math.sin(n*17+row)*.018;}
    const rise=1.45,half=width/2,angle=Math.atan2(rise,half),slope=Math.hypot(half+.3,rise);
    const shape=new T.Shape();shape.moveTo(-half,0);shape.lineTo(half,0);shape.lineTo(0,rise);shape.closePath();
    for(const side of [-1,1]){const face=mesh(geo(new T.ShapeGeometry(shape)),palette.plaster,0,height,side*(depth/2+.001),group);if(side<0)face.rotation.y=Math.PI;}
    [-1,1].forEach(side=>{const roof=box(slope,.19,depth+.55,palette.roof,side*half/2,height+rise/2,0,group);roof.rotation.z=-side*angle;});roofTiles(group,{width,depth,height,rise,material:palette.roof});
    for(const side of [-1,1]){const front=side*(depth/2+.07);[-half,0,half].forEach(pos=>box(.16,height+.04,.15,palette.wood,pos,height/2,front,group));[.8,2.2,height].forEach(y=>box(width+.12,.13,.16,palette.wood,0,y,front,group));beam([-half,2.2,front],[0,height,front],.11,palette.wood,group);beam([0,height,front],[half,2.2,front],.11,palette.wood,group);beam([-half,height,front],[0,height+rise,front],.12,palette.wood,group);beam([0,height+rise,front],[half,height,front],.12,palette.wood,group);box(.12,rise,.13,palette.wood,0,height+rise/2,front,group);
      for(const wx of [-width*.26,width*.26]){box(.79,.91,.12,palette.wood,wx,3.05,front+.01,group);box(.61,.71,.14,windowMaterial,wx,3.05,front+.03,group);box(.05,.74,.16,palette.wood,wx,3.05,front+.07,group);box(.67,.05,.16,palette.wood,wx,3.05,front+.07,group);}
    }
    box(.96,1.72,.18,palette.wood,0,.94,depth/2+.1,group);for(let n=0;n<7;n++)box(.115,1.60,.04,palette.wood,-.40+n*.13,.94,depth/2+.22,group);for(const yy of [.42,1.4])box(.86,.07,.06,palette.copper,0,yy,depth/2+.25,group);mesh(geo(new T.SphereGeometry(.06,12,8)),palette.copper,.28,.94,depth/2+.29,group);
    for(const wx of [-width*.26,width*.26]){box(.82,.12,.40,palette.wood,wx,2.54,depth/2+.20,group);for(const side of [-1,1]){const shutter=box(.29,.92,.08,palette.wood,wx+side*.52,3.05,depth/2+.13,group);shutter.rotation.y=side*.23;for(let n=0;n<6;n++)box(.25,.055,.06,palette.copper,wx+side*.52,2.68+n*.14,depth/2+.19,group);}for(let n=0;n<9;n++){const petal=mesh(geo(new T.SphereGeometry(.075,6,5)),mat(n%2?'#be7154':'#ebc077'),wx-.3+n*.075,2.66+Math.sin(n)*.06,depth/2+.20,group);petal.scale.set(.8,.6,1);}}
    for(const side of [-1,1]){[-depth/2,0,depth/2].forEach(pos=>box(.16,height,.13,palette.wood,side*half,height/2,pos,group));box(.15,.13,depth,palette.wood,side*half,2.2,0,group);}
    box(.55,1.1,.6,palette.stone,width*.28,height+1,depth*.25,group);
    batchStatic(group);return group;
  }
  const exhibitTextures=booths.map(booth=>{if(!booth.image)return null;const t=new T.TextureLoader().load(new URL(booth.image,import.meta.url).href,()=>draw());t.colorSpace=T.SRGBColorSpace;textures.push(t);return t;});
  function stall(booth,x,z){const group=new T.Group();group.position.set(x,0,z);group.userData.booth=booth.id;group.rotation.y=boothSites[booth.id].yaw;stallGroups.set(booth.id,group);scene.add(group);const cloth=mat(booth.color),cream=mat('#e9debe');box(3,.86,1.35,palette.wood,0,.48,0,group);for(let n=0;n<13;n++)box(.20,.75,.045,palette.wood,-1.37+n*.23,.48,.70,group);box(3.17,.12,1.5,palette.plaster,0,.95,0,group);for(const xx of [-1.43,1.43])for(const zz of [-.65,.65])box(.10,2.7,.10,palette.wood,xx,1.4,zz,group);fabricCanopy(group,3.4,2.2,2.78,booth.color);
    const signMaterial=new T.MeshStandardMaterial({map:labelTexture(`${booth.number} · ${booth.title}`,'RESEARCH / OPEN EXHIBITION'),roughness:.9});materials.push(signMaterial);box(2.1,.53,.10,palette.wood,0,2.16,.74,group);box(1.98,.44,.12,signMaterial,0,2.16,.79,group);
    exhibitModels.set(booth.id,buildExhibit(group,booth,{T,box,mesh,geo,mat,palette,textures,heroTexture:exhibitTextures[Number(booth.number)-1],sites:boothSites}));
    // The common stall structure stays in the same place; each collection now has its own silhouette.
    barrel(group,palette.wood,palette.copper,booth.id==='research-notes'?-1.92:1.85,0,-.12,booth.id==='product-lab'?.55:.75);
    batchStatic(group);return group;}
  function tree(x,z,scale=1,seed=0,hero=false){const g=marketTree(treeGroup,{x,z,scale,seed,leafCount:hero?4000:1200,wood:palette.trunk,leaf:palette.leaf});if(!hero)g.traverse(o=>{o.castShadow=false;});return g;}
  function updateTrees(){if(renderer)renderer.shadowMap.needsUpdate=true;if(!treeGroup)return;for(const item of [...treeGroup.children]){item.traverse(o=>{if(o.geometry&&o.geometry!==undefined&&!o.geometry.userData.shared)o.geometry.dispose();});treeGroup.remove(item);}for(let n=0;n<Math.max(0,state.treeDensity-2);n++){const side=n%2?-1:1;const layer=Math.floor(n/2);const x=side*(12.1+(layer%2)*1.0),z=-10.5+layer*1.75;tree(x,z,.70+(n%4)*.11,n);}if(state.treeDensity>0)tree(3.2,-3.5,1.48,23,true);if(state.treeDensity>1)tree(-2.3,-3.7,1.46,25,true);draw();}
  function setup(){scene=new T.Scene();scene.background=new T.Color(times.dusk.sky);scene.fog=new T.Fog(times.dusk.sky,35,80);camera=new T.PerspectiveCamera(42,1,.1,100);renderer=new T.WebGLRenderer({canvas,antialias:true,alpha:false,preserveDrawingBuffer:true});renderer.setPixelRatio(Math.min(devicePixelRatio,1.7));renderer.outputColorSpace=T.SRGBColorSpace;renderer.toneMapping=T.ACESFilmicToneMapping;renderer.toneMappingExposure=1;renderer.shadowMap.enabled=true;renderer.shadowMap.type=T.PCFSoftShadowMap;renderer.shadowMap.autoUpdate=false;renderer.shadowMap.needsUpdate=true;hemisphere=new T.HemisphereLight('#fff2d2','#69794e',.7);scene.add(hemisphere);sun=new T.DirectionalLight('#ffc47b',3.5);sun.position.set(-13,20,9);sun.castShadow=true;sun.shadow.mapSize.set(2048,2048);sun.shadow.camera.left=-19;sun.shadow.camera.right=19;sun.shadow.camera.top=20;sun.shadow.camera.bottom=-20;sun.shadow.camera.near=.5;sun.shadow.camera.far=70;sun.shadow.normalBias=.04;sun.shadow.bias=-.0002;scene.add(sun);windowMaterial=mat('#8c9f8c',{emissive:'#ffcf81',emissiveIntensity:.35});
    photoLight=photoEnvironment({supported:true,scene,renderer},{outdoor:true,onLoad:()=>draw()});skyCraft=atmosphericSky(scene);Object.values(palette).forEach(m=>m.envMapIntensity=.18);box(110,.6,110,palette.soil,0,-.38,-1);const stone=pbrMaterial('cobblestone_floor_08',{repeat:[12,13],normal:.7,roughness:.75,color:'#80796b',onLoad:()=>draw()});box(25,.13,27,stone,0,-.04,-1.5);

    // Uneven damp pockets catch sky between paving stones, without obstructing the visit path.
    const damp=mat('#69746b',{roughness:.16,metalness:.06,transparent:true,opacity:.36,depthWrite:false,envMapIntensity:.7});
    for(const [x,z,rx,rz] of [[-2.7,7.1,.46,.92],[-2.3,3.7,.76,.35],[.3,.9,.8,.42],[2.5,-1.8,.49,.77]]){const g=geo(new T.CircleGeometry(1,28)),p=g.attributes.position;for(let n=1;n<p.count;n++){const f=1+.08*Math.sin(n*2.41)+.06*Math.cos(n*3.73);p.setX(n,p.getX(n)*f);p.setY(n,p.getY(n)*f);}const wet=mesh(g,damp,x,.031,z);wet.rotation.x=-Math.PI/2;wet.scale.set(rx,rz,1);wet.castShadow=false;}
    house(-7,5.8,4.4,4.5,5,0,0);house(1.4,6,6,4.3,4.6,0,1);
    house(-8,-6,4.0,4.1,3.8,.15);house(-8,-1,3.4,3.5,3.2,.06);house(8,-6,4.1,4.5,4.0,-.12);house(8,-1,3.5,3.7,3.4,-.08);house(-4.4,-10.8,3.9,4.0,3.4,0);house(4.4,-10.8,3.9,4.5,3.4,0);
    const tower=house(0,-11.7,2.2,6.5,2.6,0);mesh(geo(new T.ConeGeometry(2,2.9,4)),palette.roof,0,8.7,0,tower).rotation.y=Math.PI/4;const clockMaterial=new T.MeshBasicMaterial({map:labelTexture('RESEARCH','07 / THE VILLAGE')});materials.push(clockMaterial);box(1.85,.6,.05,clockMaterial,0,5.5,1.35,tower);
    mesh(geo(new T.CylinderGeometry(1.45,1.65,.34,24)),palette.stone,0,.14,-2);mesh(geo(new T.CylinderGeometry(1.17,1.17,.10,24)),mat('#547c81',{metalness:.12,roughness:.18}),0,.32,-2);mesh(geo(new T.CylinderGeometry(.12,.27,1.15,10)),palette.stone,0,.85,-2);mesh(geo(new T.SphereGeometry(.29,12,8)),palette.stone,0,1.52,-2);
    booths.forEach(booth=>{const site=boothSites[booth.id];stall(booth,site.x,site.z);});
    booths.forEach(booth=>{const site=boothSites[booth.id];colliders.push({minX:site.x-1.65,maxX:site.x+1.65,minZ:site.z-.9,maxZ:site.z+.9});});colliders.push({minX:-1.4,maxX:1.4,minZ:-3.4,maxZ:-.6});
    treeGroup=new T.Group();scene.add(treeGroup);updateTrees();
    for(const x of [-10.4,10.4]){for(const z of [-8,-.7,6]){box(.09,2.5,.09,palette.wood,x,1.25,z);box(.39,.5,.39,palette.wood,x,2.55,z);box(.28,.32,.28,windowMaterial,x,2.55,z+.04);const light=new T.PointLight('#ffd194',1.6,5,2);light.position.set(x,2.55,z);light.userData.lamp=true;scene.add(light);}}
    for(const side of [-1,1]){for(const z of [-6,-1,5]){barrel(scene,palette.wood,palette.copper,side*9.7,0,z,.85);const crate=box(.8,.7,.7,palette.wood,side*9,.35,z+.5);for(const yy of [.16,.42,.66])box(.86,.04,.76,palette.copper,side*9,yy,z+.5);}}
    state.renderer='webgl';resize();applyTime('dusk');updateArrival();status('沿入口石巷进入集市。屋后还有展位，走近后按 E 查看。');
  }
  function draw(){if(!alive||!active||!renderer)return;if(state.mode==='walk'){camera.rotation.order='YXZ';camera.position.set(state.position.x,1.68,state.position.z);camera.rotation.set(state.position.pitch,state.position.yaw,0);}else{const {yaw,elevation,distance}=state.view;camera.position.set(Math.sin(yaw)*Math.cos(elevation)*distance,Math.sin(elevation)*distance+1.4,Math.cos(yaw)*Math.cos(elevation)*distance-2);camera.lookAt(0,1.4,-2);}if(scene.userData.skyMesh)scene.userData.skyMesh.position.copy(camera.position);discoverVisible();updateArrival();renderer.render(scene,camera);renderCount++;}
  function resize(){if(!renderer||!alive)return;const rect=canvas.getBoundingClientRect();if(rect.width<1||rect.height<1)return;renderer.setSize(Math.round(rect.width),Math.round(rect.height),false);camera.aspect=rect.width/rect.height;camera.fov=state.mode==='walk'?68:camera.aspect<1.2?53:42;camera.updateProjectionMatrix();draw();}
  function applyTime(time){if(renderer)renderer.shadowMap.needsUpdate=true;state.time=time;qa('[data-time]').forEach(button=>button.setAttribute('aria-pressed',String(button.dataset.time===time)));q('[data-scene-time]').textContent=`${times[time].label} / 眼平集市漫游`;if(scene){const option=times[time];scene.background.set(option.sky);scene.fog=new T.FogExp2(option.sky,time==='dusk'?.024:time==='night'?.038:.016);sun.color.set(option.sun);sun.intensity=option.intensity;sun.position.set(-13,time==='dusk'?7:time==='morning'?11:18,-11);hemisphere.color.set(option.sky);hemisphere.groundColor.set(option.ground);hemisphere.intensity=option.ambient;windowMaterial.emissiveIntensity=time==='night'?1.8:time==='dusk'?.55:.08;architectureGlass.forEach(m=>m.emissiveIntensity=time==='night'?.38:time==='dusk'?.055:.005);scene.children.filter(item=>item.userData.lamp).forEach(light=>light.intensity=time==='night'?7:time==='dusk'?2:0);renderer.toneMappingExposure=time==='night'?1.05:.94;skyCraft?.update({top:time==='night'?'#111e32':time==='dusk'?'#7b8992':'#7cbbd2',horizon:option.sky,sunDirection:sun.position,warmth:time==='night'?0:1,clouds:time==='night'?.05:.25});}draw();}
  function architectureState(){return {nearHouseCount:nearArchitecture.length,windowCount:nearArchitecture.reduce((n,h)=>n+h.windowCount,0),shutterLeafCount:nearArchitecture.reduce((n,h)=>n+h.shutterLeafCount,0),hingeCount:nearArchitecture.reduce((n,h)=>n+h.hingeCount,0),archDoorCount:nearArchitecture.reduce((n,h)=>n+h.archDoorCount,0),recessDepth:.20,eaveLayers:3,brickCourses:3,glassEmissiveIntensity:architectureGlass[0]?.emissiveIntensity??null,nearHouses:nearArchitecture.map(item=>({...item,position:{...item.position}})),scope:'Only the two existing lane houses are detailed. Building positions, original footprint collisions, eye height and three exhibit collections remain the same. Fixed original architecture, not interactive doors or source assets.'};}
  function choose(id,via=state.mode==='overview'?'overview':'near-view'){const booth=booths.find(item=>item.id===id);if(!booth)return;state.selected=id;if(!state.visits.some(item=>item.id===id))state.visits.push({id,title:booth.title,visitedAt:new Date().toISOString(),via,positionAtView:{...state.position},distanceAtView:Number(Math.hypot(state.position.x-boothSites[id].x,state.position.z-boothSites[id].z).toFixed(2)),relatedCases:[...booth.relatedCases],shownObjects:[...booth.objects]});q('.village-exhibit').innerHTML=`<span class="village-exhibit-tag">EXHIBIT ${booth.number} / ${esc(booth.category)}</span><h4>${esc(booth.title)}</h4><p>${esc(booth.description)}</p><ul class="village-object-list">${booth.objects.map(object=>`<li>${esc(object)}</li>`).join('')}</ul><p>${esc(booth.takeaway)}</p>${id==='research-notes'?'<div class="village-visit-receipt" data-visit-receipt></div>':''}<a class="lab-button village-project-link" href="${esc(booth.page)}" target="_blank" rel="noopener">${esc(booth.pageLabel)} ↗</a><p class="village-exhibit-boundary">${esc(booth.boundary)}</p>`;qa('[data-booth]').forEach(button=>{const visited=state.visits.some(item=>item.id===button.dataset.booth);button.setAttribute('aria-pressed',String(button.dataset.booth===id));button.dataset.visited=String(visited);button.querySelector('small').textContent=visited?'已参观 ✓':state.discovered.includes(button.dataset.booth)?'已发现 · 带我参观 →':'未发现 · 带我参观 →';});q('[data-progress-label]').textContent=`参观任务 · ${state.visits.length} / 3`;qa('.village-progress i').forEach((item,n)=>item.dataset.done=String(n<state.visits.length));q('[data-progress-copy]').textContent=state.visits.length===3?'已收集全部研究摘要，可以导出本次访问记录。':'继续探索另外的展位，补齐研究回顾。';draw();updateReceipt();status(state.visits.length===3?'参观任务完成：三个研究展位均已看过。':`已参观「${booth.title}」，完成 ${state.visits.length} / 3。`);}
  function updateReceipt(){const receipt=q('[data-visit-receipt]');if(!receipt)return;const copy=`<b>本次真实参观凭证</b><div><span>发现 <strong>${state.discovered.length}/3</strong></span><span>走近 <strong>${state.reached.length}/3</strong></span><span>查看 <strong>${state.visits.length}/3</strong></span></div><small>步行 ${state.walkingDistance.toFixed(1)} 米 · 列表直达单独标记，不计入步行距离。</small>`;if(receipt.innerHTML!==copy)receipt.innerHTML=copy;}
  function fallback(){state.renderer='2d-fallback';canvas.hidden=true;const stage=q('.village-stage');stage.classList.add('village-is-fallback');const panel=document.createElement('div');panel.className='village-fallback';panel.innerHTML=`<strong>研究集市 · 展位导航</strong><p>当前设备没有可用的 WebGL，已切换为二维展位列表。参观与记录导出仍可使用。</p><div class="village-fallback-map">${booths.map(item=>`<button type="button" data-fallback-booth="${item.id}">${item.number}<br>${item.title}</button>`).join('')}</div>`;stage.insertBefore(panel,canvas);q('.village-camera-bar').hidden=true;q('.village-scene-caption').hidden=true;qa('[data-time]').forEach(button=>button.disabled=true);qa('[data-walk]').forEach(button=>button.disabled=true);q('[data-interact]').disabled=true;q('[data-arrival]').textContent='二维展位导航；没有第一人称三维漫游。';q('input[type=range]').disabled=true;q('[data-export=png]').disabled=true;qa('[data-fallback-booth]').forEach(button=>off(button,'click',()=>choose(button.dataset.fallbackBooth)));status('当前为二维降级模式；没有三维渲染或场景截图。');}
  try{setup();}catch(error){const constructionFailed=Boolean(renderer);console.error('Research market initialization:',error);renderer?.dispose();renderer=null;scene=null;fallback();if(constructionFailed)status('三维场景构建未完成：'+error.message+'。这不是 WebGL 兼容性检测结果。');}
  qa('[data-time]').forEach(button=>off(button,'click',()=>{applyTime(button.dataset.time);status(`环境已切换为${times[state.time].label}。`);}));
  off(q('input[type=range]'),'input',event=>{state.treeDensity=Number(event.target.value);q('[data-density]').value=`${state.treeDensity} 棵`;updateTrees();status(`集市周边现有 ${state.treeDensity} 棵树。`);});
  qa('[data-booth]').forEach(button=>off(button,'click',()=>{state.position={...boothSites[button.dataset.booth].approach};state.mode='walk';if(!state.reached.includes(button.dataset.booth))state.reached.push(button.dataset.booth);q('[data-mode]').textContent='切换布局鸟瞰';resize();choose(button.dataset.booth,'guided-shortcut');updateArrival();}));
  function discoverVisible(){if(!scene||state.mode!=='walk')return;scene.updateMatrixWorld(true);camera.updateMatrixWorld(true);const frustum=new T.Frustum().setFromProjectionMatrix(camera.projectionMatrix.clone().multiply(camera.matrixWorldInverse));for(const booth of booths){if(state.discovered.includes(booth.id))continue;const group=stallGroups.get(booth.id);if(!group)continue;const target=group.localToWorld(new T.Vector3(0,2.16,.80)),distance=camera.position.distanceTo(target);if(distance>18||!frustum.containsPoint(target))continue;const ray=new T.Raycaster(camera.position,target.clone().sub(camera.position).normalize(),.05,distance-.1);if(ray.intersectObjects(buildings,true).length===0){state.discovered.push(booth.id);const button=q(`[data-booth="${booth.id}"]`);if(button&&!state.visits.some(v=>v.id===booth.id))button.querySelector('small').textContent='已发现 · 带我参观 →';}}}
  function updateArrival(){const nearest=booths.map(booth=>({booth,distance:Math.hypot(state.position.x-boothSites[booth.id].x,state.position.z-boothSites[booth.id].z)})).sort((a,b)=>a.distance-b.distance)[0],near=state.mode==='walk'&&nearest.distance<3.4,viewed=state.visits.some(item=>item.id===nearest.booth.id);state.proximity={id:nearest.booth.id,distance:Number(nearest.distance.toFixed(2)),canView:near,viewed};q('[data-arrival]').textContent=near?`已走近${nearest.booth.title}：${nearest.booth.role}。${viewed?'已记录查看，可按 E 再看。':'按 E 或下方按钮查看实际内容。'}`:state.position.z>3.5&&state.position.x<0?'沿前方石巷进入主广场；建筑后面的展位会随着步行露出。':'主广场已展开。拖动看向其它摊位，走近后按 E 查看。';if(near&&!state.reached.includes(nearest.booth.id))state.reached.push(nearest.booth.id);q('[data-proximity]').hidden=!near;q('[data-proximity-number]').textContent=nearest.booth.number;q('[data-proximity-role]').textContent=nearest.booth.role;q('[data-proximity-action]').textContent=(viewed?'已查看 · E 再看':'E / 查看这处陈列')+` · ${nearest.distance.toFixed(1)} 米`;for(const [id,model]of exhibitModels)model.feedback({near:near&&id===nearest.booth.id,viewed:state.visits.some(item=>item.id===id)});updateReceipt();return nearest;}
  function walkStep(forward,side,amount){const dx=(-Math.sin(state.position.yaw)*forward+Math.cos(state.position.yaw)*side)*amount,dz=(-Math.cos(state.position.yaw)*forward-Math.sin(state.position.yaw)*side)*amount;const blocked=(x,z)=>colliders.some(c=>x>c.minX-.28&&x<c.maxX+.28&&z>c.minZ-.28&&z<c.maxZ+.28);const old={...state.position},x=clamp(old.x+dx,-12.5,12.5),z=clamp(old.z+dz,-12.5,12.5);if(!blocked(x,state.position.z))state.position.x=x;if(!blocked(state.position.x,z))state.position.z=z;state.walkingDistance+=Math.hypot(state.position.x-old.x,state.position.z-old.z);updateArrival();draw();}
  function walkTick(time){walkFrame=0;if(!active||!alive||document.hidden)return;const dt=lastWalk?Math.min(.045,(time-lastWalk)/1000):0;lastWalk=time;walkStep(Number(keys.has('forward'))-Number(keys.has('back')),Number(keys.has('right'))-Number(keys.has('left')),3.2*dt);if(keys.size)walkFrame=requestAnimationFrame(walkTick);}
  function scheduleWalk(){if(!walkFrame&&active&&alive){lastWalk=0;walkFrame=requestAnimationFrame(walkTick);}}
  function interact(){const nearest=updateArrival();if(nearest.distance<3.4)choose(nearest.booth.id);else status('先走近一个展位，再查看研究内容。');}
  off(q('[data-mode]'),'click',()=>{state.mode=state.mode==='walk'?'overview':'walk';q('[data-mode]').textContent=state.mode==='walk'?'切换布局鸟瞰':'进入集市漫游';resize();});
  qa('[data-walk]').forEach(button=>off(button,'pointerdown',event=>{event.preventDefault();state.mode='walk';keys.add(button.dataset.walk);canvas.focus({preventScroll:true});resize();scheduleWalk();}));off(window,'pointerup',()=>keys.clear());off(window,'blur',()=>keys.clear());off(q('[data-interact]'),'click',interact);
  off(canvas,'keydown',event=>{if(state.mode!=='walk'||!active)return;const key={w:'forward',ArrowUp:'forward',s:'back',ArrowDown:'back',a:'left',ArrowLeft:'left',d:'right',ArrowRight:'right'}[event.key.toLowerCase()]||{ArrowUp:'forward',ArrowDown:'back',ArrowLeft:'left',ArrowRight:'right'}[event.key];if(key){event.preventDefault();keys.add(key);scheduleWalk();}if(event.key.toLowerCase()==='e')interact();});off(window,'keyup',event=>keys.delete({w:'forward',s:'back',a:'left',d:'right',ArrowUp:'forward',ArrowDown:'back',ArrowLeft:'left',ArrowRight:'right'}[event.key]||{w:'forward',s:'back',a:'left',d:'right'}[event.key.toLowerCase()]));
  function move(command){if(state.mode==='walk'){if(command==='left')state.position.yaw+=.24;if(command==='right')state.position.yaw-=.24;if(command==='in')walkStep(1,0,.7);if(command==='out')walkStep(-1,0,.7);if(command==='reset')state.position={...entryPose};updateArrival();;}else{if(command==='left')state.view.yaw-=.24;if(command==='right')state.view.yaw+=.24;if(command==='in')state.view.distance=clamp(state.view.distance-2.5,21,44);if(command==='out')state.view.distance=clamp(state.view.distance+2.5,21,44);if(command==='reset')state.view={yaw:.40,elevation:.54,distance:34};}draw();}
  qa('[data-camera]').forEach(button=>off(button,'click',()=>move(button.dataset.camera)));
  let drag=null;
  off(canvas,'pointerdown',event=>{if(!renderer)return;drag={id:event.pointerId,x:event.clientX,y:event.clientY,startX:event.clientX,startY:event.clientY,moved:false};canvas.setPointerCapture(event.pointerId);});
  off(canvas,'pointermove',event=>{if(!drag||event.pointerId!==drag.id)return;const dx=event.clientX-drag.x,dy=event.clientY-drag.y;if(state.mode==='walk'){state.position.yaw-=dx*.004;state.position.pitch=clamp(state.position.pitch-dy*.003,-.9,.9);}else{state.view.yaw-=dx*.006;state.view.elevation=clamp(state.view.elevation+dy*.004,.2,1.05);}drag.moved ||= Math.hypot(event.clientX-drag.startX,event.clientY-drag.startY)>7;drag.x=event.clientX;drag.y=event.clientY;draw();});
  off(canvas,'pointerup',event=>{if(!drag)return;const moved=drag.moved;drag=null;if(canvas.hasPointerCapture(event.pointerId))canvas.releasePointerCapture(event.pointerId);if(moved||!scene)return;const rect=canvas.getBoundingClientRect(),pointer=new T.Vector2(((event.clientX-rect.left)/rect.width)*2-1,-((event.clientY-rect.top)/rect.height)*2+1);const ray=new T.Raycaster();ray.setFromCamera(pointer,camera);for(const hit of ray.intersectObjects(scene.children,true)){let object=hit.object;while(object&&!object.userData.booth)object=object.parent;if(object?.userData.booth){const id=object.userData.booth,site=boothSites[id];if(state.mode==='overview'||Math.hypot(state.position.x-site.x,state.position.z-site.z)<3.4)choose(id);else status('已看到'+booths.find(b=>b.id===id).title+'；先沿石路走近，再按 E 查看。');break;}}});
  off(canvas,'pointercancel',()=>drag=null);off(canvas,'wheel',event=>{if(!renderer)return;event.preventDefault();state.view.distance=clamp(state.view.distance+Math.sign(event.deltaY)*1.5,21,44);draw();},{passive:false});off(canvas,'keydown',event=>{if(state.mode==='walk')return;const command={ArrowLeft:'left',ArrowRight:'right','+':'in','=':'in','-':'out',Home:'reset'}[event.key];if(command){event.preventDefault();move(command);}});
  off(q('[data-export=json]'),'click',()=>{const record={schemaVersion:2,product:'我们的研究集市',caseReference:7,createdAt:new Date().toISOString(),environment:{time:state.time,timeLabel:times[state.time].label,treeDensity:state.treeDensity},architecture:architectureState(),spatialVisit:{entry:{...entryPose},discovered:[...state.discovered],reached:[...state.reached],walkingDistance:Number(state.walkingDistance.toFixed(2))},exhibits:booths.map(booth=>({id:booth.id,role:booth.role,objects:[...booth.objects],relatedCases:[...booth.relatedCases],page:booth.page,defaultRecipe:booth.defaultRecipe||null,boundary:booth.boundary})),view:{...state.view},renderer:state.renderer,selectedExhibit:state.selected,visitedExhibits:state.visits.map(item=>({...item,summary:booths.find(booth=>booth.id===item.id).takeaway})),task:{target:3,visited:state.visits.length,complete:state.visits.length===3},implementation:'Original procedural village and static exhibit models; the source author’s toolchain is unconfirmed.'};h.downloadFile('research-market-visit.json',JSON.stringify(record,null,2),'application/json');status(`已导出参观记录：${state.visits.length} / 3 个展位。`);});
  off(q('[data-export=png]'),'click',()=>{if(!renderer)return;const wasActive=active;active=true;draw();active=wasActive;canvas.toBlob(blob=>{if(blob&&alive){h.downloadFile('research-market-scene.png',blob,'image/png');status('已保存当前三维场景 PNG。');}},'image/png');});
  off(document,'visibilitychange',()=>{if(document.hidden){keys.clear();cancelAnimationFrame(walkFrame);walkFrame=0;}});const observer=new ResizeObserver(resize);observer.observe(canvas);
  return {getState(){return {caseId:7,time:state.time,treeDensity:state.treeDensity,selected:state.selected,visits:state.visits.map(item=>({...item})),view:{...state.view},mode:state.mode,position:{...state.position},reached:[...state.reached],proximity:state.proximity?{...state.proximity}:null,architecture:architectureState(),exhibits:booths.map(booth=>({id:booth.id,role:booth.role,objects:[...booth.objects],relatedCases:[...booth.relatedCases],page:booth.page,defaultRecipe:booth.defaultRecipe||null})),space:{phase:state.position.z>3.5&&state.position.x<0?'entrance-lane':'market-square',discovered:[...state.discovered],booths:booths.map(b=>({id:b.id,...boothSites[b.id]})),entry:{...entryPose}},walkingDistance:Number(state.walkingDistance.toFixed(2)),renderer:state.renderer,renderCount,renderStats:renderer?{drawCalls:renderer.info.render.calls,triangles:renderer.info.render.triangles,pixelRatio:renderer.getPixelRatio()}:null,treeArt:treeGroup?treeGroup.children.map(g=>({...g.userData.art})):[],assets:{geometry:'Two recessed lane facades with aligned timber grain, contact wear and joinery; connected four-tier branch sprays and three static content-specific exhibit collections',materials:'Original facade and timber textures; Poly Haven CC0 photographed ground/stone maps and HDR lighting',exhibitImages:'Actual local case 01 and 06 runtime screenshots; no source movie frame is used as a scene texture.'}};},setActive(value){active=Boolean(value);drag=null;keys.clear();cancelAnimationFrame(walkFrame);walkFrame=0;if(active)resize();},dispose(){alive=false;active=false;keys.clear();cancelAnimationFrame(walkFrame);walkFrame=0;observer.disconnect();listeners.forEach(cleanup=>cleanup());photoLight?.dispose();renderer?.dispose();textures.forEach(texture=>texture.dispose());materials.forEach(material=>material.dispose());geometries.forEach(geometry=>geometry.dispose());scene?.traverse(o=>{o.geometry?.dispose();for(const m of Array.isArray(o.material)?o.material:[o.material]){if(!m)continue;for(const v of Object.values(m))if(v?.isTexture)v.dispose();m.dispose();}});scene?.clear();container.innerHTML='';}};
}



