import '../demo/runtime/vendor/three-r160.min.js';
export const T=globalThis.THREE;
export const clamp=(v,a,b)=>Math.min(b,Math.max(a,v));

// Independent first-person stage. Camera position is never replaced by an orbit preset.
export function createExplorer(element,{start={x:0,z:10,yaw:0,pitch:0},ground=()=>0,bounds=36,onFrame=()=>false,move=null,eyeHeight=()=>1.68,eyeOffset=()=>({x:0,z:0})}={}){
  let canvas=element,renderer,scene,camera,active=true,disposed=false,raf=0,last=0,drag=null,steps=0;
  const keys=new Set(),colliders=[],abort=new AbortController(),signal=abort.signal;
  let pose={...start},distance=0,renderCount=0;
  try{renderer=new T.WebGLRenderer({canvas,antialias:true,preserveDrawingBuffer:true});}
  catch{const replacement=canvas.cloneNode(true);canvas.replaceWith(replacement);canvas=replacement;return {supported:false,canvas,context:canvas.getContext('2d'),dispose(){},setActive(){},getPose:()=>({...pose}),getStats:()=>({distance:0,steps:0,renderCount:0}),setPose(value){pose={...pose,...value};},setKey(){},draw(){},invalidate(){},colliders};}
  renderer.setPixelRatio(Math.min(devicePixelRatio||1,1.6));renderer.outputColorSpace=T.SRGBColorSpace;renderer.toneMapping=T.ACESFilmicToneMapping;renderer.toneMappingExposure=1;renderer.shadowMap.enabled=true;renderer.shadowMap.type=T.PCFSoftShadowMap;renderer.shadowMap.autoUpdate=false;renderer.shadowMap.needsUpdate=true;
  scene=new T.Scene();camera=new T.PerspectiveCamera(68,1,.08,180);camera.rotation.order='YXZ';
  function blocked(x,z){return colliders.some(c=>c.kind==='circle'?Math.hypot(x-c.x,z-c.z)<c.r+.32:x>c.minX-.32&&x<c.maxX+.32&&z>c.minZ-.32&&z<c.maxZ+.32);}
  function draw(){if(disposed||!active)return;const rect=canvas.getBoundingClientRect();if(rect.width<2||rect.height<2)return;renderer.setSize(rect.width,rect.height,false);camera.aspect=rect.width/rect.height;camera.fov=rect.width<600?88:68;camera.updateProjectionMatrix();const offset=eyeOffset({...pose});camera.position.set(pose.x+(offset.x||0),ground(pose.x,pose.z)+eyeHeight({...pose}),pose.z+(offset.z||0));camera.rotation.set(pose.pitch,pose.yaw,0);if(scene.userData.skyMesh)scene.userData.skyMesh.position.copy(camera.position);renderer.render(scene,camera);renderCount++;}
  function tick(time){raf=0;if(!active||disposed||document.hidden)return;const dt=last?Math.min(.045,(time-last)/1000):0;last=time;let forward=Number(keys.has('forward'))-Number(keys.has('back')),side=Number(keys.has('right'))-Number(keys.has('left'));const length=Math.hypot(forward,side),oldX=pose.x,oldZ=pose.z;const vehicle=move?.(dt,{...pose},{forward,side,fast:keys.has('fast')});if(vehicle){const {keepMoving,...nextPose}=vehicle;pose={...pose,...nextPose};}else if(length){forward/=length;side/=length;const speed=(keys.has('fast')?6:3.5)*dt,dx=(-Math.sin(pose.yaw)*forward+Math.cos(pose.yaw)*side)*speed,dz=(-Math.cos(pose.yaw)*forward-Math.sin(pose.yaw)*side)*speed;const x=clamp(pose.x+dx,-bounds,bounds),z=clamp(pose.z+dz,-bounds,bounds);if(!blocked(x,pose.z))pose.x=x;if(!blocked(pose.x,z))pose.z=z;}const moved=Math.hypot(pose.x-oldX,pose.z-oldZ);distance+=moved;if(moved>.00001)steps++;const moving=onFrame(dt,{...pose});draw();if(moving||length||vehicle?.keepMoving)raf=requestAnimationFrame(tick);}
  function invalidate(){if(!raf&&active&&!disposed&&!document.hidden){last=0;raf=requestAnimationFrame(tick);}}
  const mapping={w:'forward',ArrowUp:'forward',s:'back',ArrowDown:'back',a:'left',ArrowLeft:'left',d:'right',ArrowRight:'right',Shift:'fast'};
  window.addEventListener('keydown',event=>{if(!active||disposed||document.activeElement!==canvas)return;const key=mapping[event.key]||mapping[event.key.toLowerCase()];if(key){event.preventDefault();keys.add(key);invalidate();}},{signal});
  window.addEventListener('keyup',event=>keys.delete(mapping[event.key]||mapping[event.key.toLowerCase()]),{signal});window.addEventListener('blur',()=>keys.clear(),{signal});window.addEventListener('pointerup',()=>keys.clear(),{signal});window.addEventListener('pointercancel',()=>keys.clear(),{signal});
  canvas.addEventListener('pointerdown',event=>{drag={x:event.clientX,y:event.clientY};canvas.setPointerCapture(event.pointerId);canvas.focus({preventScroll:true});},{signal});
  canvas.addEventListener('pointermove',event=>{if(!drag||!active)return;pose.yaw-=(event.clientX-drag.x)*.004;pose.pitch=clamp(pose.pitch-(event.clientY-drag.y)*.003,-1.05,1.05);drag={x:event.clientX,y:event.clientY};draw();},{signal});canvas.addEventListener('pointerup',()=>drag=null,{signal});canvas.addEventListener('pointercancel',()=>drag=null,{signal});
  const observer=new ResizeObserver(draw);observer.observe(canvas);document.addEventListener('visibilitychange',()=>{if(document.hidden){cancelAnimationFrame(raf);raf=0;keys.clear();drag=null;}else invalidate();},{signal});
  return {supported:true,canvas,renderer,scene,camera,colliders,draw,invalidate,getPose:()=>({...pose}),getCameraPosition:()=>({x:camera.position.x,y:camera.position.y,z:camera.position.z}),getStats:()=>({distance:Number(distance.toFixed(2)),steps,renderCount,drawCalls:renderer.info.render.calls,triangles:renderer.info.render.triangles,pixelRatio:renderer.getPixelRatio()}),setPose(value){pose={...pose,...value};draw();invalidate();},setKey(key,pressed){if(pressed&&active){keys.add(key);canvas.focus({preventScroll:true});invalidate();}else keys.delete(key);},setActive(value){active=Boolean(value);keys.clear();drag=null;if(!active){cancelAnimationFrame(raf);raf=0;}else{draw();invalidate();}},dispose(){disposed=true;active=false;cancelAnimationFrame(raf);abort.abort();observer.disconnect();keys.clear();const textures=new Set(),materials=new Set(),geometries=new Set();scene.traverse(object=>{if(object.geometry)geometries.add(object.geometry);const list=Array.isArray(object.material)?object.material:[object.material];for(const material of list){if(!material)continue;materials.add(material);for(const value of Object.values(material))if(value?.isTexture)textures.add(value);}});geometries.forEach(g=>g.dispose());materials.forEach(m=>m.dispose());textures.forEach(t=>t.dispose());renderer.dispose();scene.clear();}};
}

export function surfaceTexture(kind='wood',repeat=1){const c=document.createElement('canvas');c.width=c.height=256;const x=c.getContext('2d');x.fillStyle=kind==='stone'?'#c9c5b3':kind==='sand'?'#dad2b4':'#c5b392';x.fillRect(0,0,256,256);let seed=93;const random=()=>{seed=seed*16807%2147483647;return seed/2147483647;};for(let i=0;i<1800;i++){const alpha=.025+random()*.14;x.fillStyle=`rgba(${random()>.5?'255,246,210':'30,26,17'},${alpha})`;if(kind==='wood')x.fillRect(random()*256,random()*256,random()*30+10,random()*1.3+.3);else x.fillRect(random()*256,random()*256,2+random()*4,1+random()*3);}if(kind==='stone'){for(let row=0;row<8;row++)for(let col=-1;col<8;col++){x.strokeStyle='#5b5a4866';x.lineWidth=2;x.strokeRect(col*34+(row%2)*17,row*32,33,31);}}if(kind==='wood'){x.strokeStyle='#392d1e55';x.lineWidth=2;for(let i=0;i<8;i++){x.beginPath();x.moveTo(0,i*32);x.lineTo(256,i*32);x.stroke();}}const texture=new T.CanvasTexture(c);texture.colorSpace=T.SRGBColorSpace;texture.wrapS=texture.wrapT=T.RepeatWrapping;texture.repeat.set(repeat,repeat);return texture;}
export function material(color,options={}){return new T.MeshStandardMaterial({color,roughness:.88,...options});}
export function box(parent,w,h,d,mat,x=0,y=0,z=0){const object=new T.Mesh(new T.BoxGeometry(w,h,d),mat);object.position.set(x,y,z);object.castShadow=object.receiveShadow=true;parent.add(object);return object;}
export function mesh(parent,geometry,mat,x=0,y=0,z=0){const object=new T.Mesh(geometry,mat);object.position.set(x,y,z);object.castShadow=object.receiveShadow=true;parent.add(object);return object;}
