import test from 'node:test';
import assert from 'node:assert/strict';
import {schoolSnapshot,boidsForces,createShoreline,signedShoreDistance,shorelineSteering,turnStep,bodyOverlap,resolveBodies} from '../src/fish-steering.js';
const fish=(id,x=0,z=0,heading=0,y=-.2)=>({id,x,y,z,heading,size:.6,speed:.18,pitch:0});
const near=(a,b,e=1e-10)=>assert.ok(Math.abs(a-b)<e,`${a} ≠ ${b}`);

test('snapshot detaches positions and headings from mutable scene nodes',()=>{const source=[{id:4,heading:.6,speed:.2,pitch:.2,group:{position:{x:1,y:2,z:3},scale:{x:.7}}}],snapshot=schoolSnapshot(source);
 source[0].group.position.x=7;source[0].heading=2;assert.equal(snapshot[0].x,1);assert.equal(snapshot[0].heading,.6);assert.equal(snapshot[0].size,.7);});
test('Boids separation steers close fish away, alignment/cohesion respond to neighbours',()=>{const values=boidsForces([fish(0),fish(1,.2,0,Math.PI/2)],0);
 assert.ok(values.separation.x<0);assert.ok(values.alignment.z<-.99);near(values.cohesion.x,.2);assert.equal(values.neighbors,1);});
test('Boids steering is invariant to neighbour update order',()=>{const snapshot=[fish(0),fish(1,.2,.1),fish(2,-.3,.2,1),fish(3,1,.2,-1)],a=boidsForces(snapshot,0),b=boidsForces([snapshot[2],snapshot[0],snapshot[3],snapshot[1]],1);
 for(const key of ['separation','alignment','cohesion']){near(a[key].x,b[key].x);near(a[key].z,b[key].z);}assert.equal(a.neighbors,b.neighbors);});
test('coincident fish get opposite finite separation; distant/deep fish do not repel',()=>{const snapshot=[fish(2),fish(5)],a=boidsForces(snapshot,0),b=boidsForces(snapshot,1);near(a.separation.x,-b.separation.x);near(a.separation.z,-b.separation.z);
 const deep=boidsForces([fish(0),fish(1,.1,0,0,-1),fish(2,5)],0);near(deep.separation.x,0);assert.equal(deep.neighbors,1);});
test('signed shoreline distances and gradients point outward at every pond scale',()=>{for(const scale of [.65,1,1.25]){const shore=createShoreline(scale),inside=signedShoreDistance(shore,-.5,-.15),outside=signedShoreDistance(shore,8,0);
 assert.ok(inside.distance<0);assert.ok(outside.distance>0);assert.ok(outside.nx>.9);near(Math.hypot(outside.nx,outside.nz),1);}});
test('predictive shoreline steering reacts before the body crosses the bank',()=>{const shore=createShoreline(),f=fish(0,3.65,0);f.speed=.35;
 assert.ok(signedShoreDistance(shore,f.x,f.z).distance<0);const steer=shorelineSteering(shore,f);assert.ok(steer.x<-.1);assert.ok(steer.look>.8);});
test('turning follows the shortest wrapped angle and limits angular acceleration',()=>{let heading=Math.PI-.02,rate=0;for(let i=0;i<100;i++){const prev=rate,next=turnStep(heading,rate,-Math.PI+.02,.02);heading=next.heading;rate=next.rate;
 assert.ok(Math.abs(rate-prev)<=2.5*.02+1e-12);assert.ok(Math.abs(rate)<=1.8+1e-12);}assert.ok(heading>Math.PI-.02);assert.ok(Math.abs(Math.atan2(Math.sin(heading-(-Math.PI+.02)),Math.cos(heading-(-Math.PI+.02))))<.01);});
test('lowering turn limits brakes momentum gradually and dt=0 preserves orientation',()=>{const next=turnStep(0,3,0,.02,{maxRate:1,acceleration:2});near(next.rate,2.96);assert.deepEqual(turnStep(1,.3,2,0),{heading:1,rate:.3});});
test('three spine spheres detect head/tail overlap beyond root sphere radius',()=>{const a=fish(0),b=fish(1,.42);assert.ok(Math.hypot(a.x-b.x,a.z-b.z)>(a.size+b.size)*.1);assert.ok(bodyOverlap(a,b)>.05);});
test('body collision is symmetric, bounded and reduces overlap',()=>{const pair=[fish(0),fish(1,.10,.03)],original=pair.map(f=>({...f})),before=bodyOverlap(...pair),result=resolveBodies(pair,{iterations:3,maxCorrection:.018});
 near(pair[0].x+pair[1].x,original[0].x+original[1].x);near(pair[0].z+pair[1].z,original[0].z+original[1].z);assert.ok(bodyOverlap(...pair)<before);assert.ok(result.contacts>0);
 for(let i=0;i<2;i++)assert.ok(Math.hypot(pair[i].x-original[i].x,pair[i].y-original[i].y,pair[i].z-original[i].z)<=.054+1e-12);});
test('coincident crowded fish resolve finitely without drifting the school centroid',()=>{const cluster=Array.from({length:8},(_,i)=>fish(i)),result=resolveBodies(cluster,{iterations:3,maxCorrection:.015});
 assert.ok(result.contacts>0);near(cluster.reduce((s,f)=>s+f.x,0),0);near(cluster.reduce((s,f)=>s+f.z,0),0);
 for(const f of cluster){assert.ok(Number.isFinite(f.x+f.y+f.z));assert.ok(Math.hypot(f.x,f.y+.2,f.z)<=.045+1e-12);}});
test('vertically separated bodies do not receive horizontal collision impulses',()=>{const pair=[fish(0),fish(1,0,0,0,-.8)],before=structuredClone(pair);resolveBodies(pair);assert.deepEqual(pair,before);});
