import {normalize,escapeHTML as esc} from './core.js';
const raw=JSON.parse(document.querySelector('#prototype-config').textContent),c=normalize(raw),root=document.querySelector('#app');document.documentElement.style.setProperty('--accent',c.branding.accent);const rgb=c.branding.accent.match(/[0-9a-f]{2}/g).map(v=>parseInt(v,16));document.documentElement.style.setProperty('--accent-ink',rgb[0]*.2126+rgb[1]*.7152+rgb[2]*.0722>160?'#273528':'#ffffff');
const $=s=>document.querySelector(s),download=(data,name,type='application/json')=>{const blob=data instanceof Blob?data:new Blob([typeof data==='string'?data:JSON.stringify(data,null,2)],{type}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),10000);};
root.innerHTML=`<header class="p-header"><strong>${esc(c.name)}</strong><span>首版交互原型</span></header><main><div class="p-intro"><p class="p-kicker">${c.product.kind==='toilet'&&c.template==='product'?'BATHROOM / 比较与选型':c.template==='product'?'CONFIGURE / 选定一套外观':'SERVICE / 确认适用范围'}</p><h1>${esc(c.branding.title)}</h1><p>${esc(c.branding.tagline)}</p></div><div id="task"></div></main><footer>本地原型 · ${c.template==='product'?'原创概念模型，真实型号和尺寸需替换':'默认示例规则，采用前请由业务方确认'}${c.useAI?' · AI 服务待接入':''}</footer>`;
const report=(type,result)=>parent.postMessage({type:'foundry-'+type,instanceId:raw._instanceId||'standalone',productName:c.name,template:c.template,result},'*');
addEventListener('error',e=>report('error',{message:e.message||'本地模块读取失败'}));
addEventListener('unhandledrejection',e=>report('error',{message:e.reason?.message||'本地模块初始化失败'}));
const sizeObserver=new ResizeObserver(()=>report('resize',{height:Math.ceil(document.body.scrollHeight)}));sizeObserver.observe(document.body);addEventListener('pagehide',()=>sizeObserver.disconnect());
if(c.template==='product'&&c.product.kind==='headphones'){
  const {mountHeadphones}=await import('./headphone-preview.js?v=20261003-14');
  const mounted=mountHeadphones($('#task'),c,report);addEventListener('pagehide',()=>mounted.dispose());
}else if(c.template==='product'&&c.product.kind==='toilet'){
  const {mountToilet}=await import('./toilet-preview.js?v=20261002-11');
  const mounted=await mountToilet({config:c,host:$('#task'),report,download});addEventListener('pagehide',()=>mounted.dispose());
}else if(c.template==='product'){
  const p=c.product,features=p.features;$('#task').innerHTML=`<div class="p-product"><div class="p-stage"><canvas id="product-canvas" tabindex="0" aria-label="产品三维预览，可用方向键旋转或按钮切换视角"></canvas><span class="p-model-label">${esc(p.name)} / 概念形体</span><div class="p-views"><button data-view="hero" aria-pressed="true">产品视角</button><button data-view="front" aria-pressed="false">正面</button>${features.structure?'<button data-view="structure" aria-pressed="false">查看结构</button>':''}</div><span id="render-status" class="p-render-status" role="status">正在准备画面…</span></div><aside class="p-options"><span class="p-kicker">YOUR SELECTION</span><h2>选择你的配置</h2><fieldset><legend>灯体配色</legend><div class="p-colors">${p.colors.map((v,i)=>`<label><input type="radio" name="color" value="${v.value}" ${i===0?'checked':''}><i style="background:${v.value}"></i><span>${esc(v.label)}</span></label>`).join('')}</div></fieldset>${features.finish?'<label class="p-field">表面效果<select id="finish"><option value="matte">细腻哑光</option><option value="gloss">亮面涂层</option></select></label>':''}${features.light?'<label class="p-field">灯光亮度 <output id="light-value">70%</output><input id="light" type="range" min="0" max="100" value="70"></label>':''}${features.structure?'<label class="p-field">结构展开 <output id="explode-value">0%</output><input id="explode" type="range" min="0" max="100" value="0"></label>':''}<div class="p-result"><span>当前选择</span><strong id="selection"></strong><p id="selection-detail"></p></div><button id="save-config" class="p-primary">带走这套配置</button><button id="save-image" class="p-secondary">导出当前画面</button><p class="p-small" id="export-status" role="status">配置仅保存在导出文件中，没有提交订单。</p></aside></div>`;
  const state={...p.initial,spin:false,room:'studio',setting:'interior',reflections:true,view:'hero'};let renderer;
  const snapshot=()=>({schemaVersion:'1.0',product:c.name,item:p.name,dataMode:'concept-model',selection:{color:state.color,colorName:p.colors.find(v=>v.value===state.color)?.label,finish:state.finish,lightPercent:state.light,structurePercent:state.explode},observation:renderer?.getViewState(),submitted:false});
  function update(){const s=snapshot();$('#selection').textContent=s.selection.colorName+' · '+(state.finish==='gloss'?'亮面涂层':'细腻哑光');$('#selection-detail').textContent=`灯光 ${state.light}% · ${state.explode?'结构展开 '+state.explode+'%':'完整装配'}`;if($('#light-value'))$('#light-value').textContent=state.light+'%';if($('#explode-value'))$('#explode-value').textContent=state.explode+'%';renderer?.draw();report('result',s);}
  $('#product-canvas').addEventListener('product-render-state',e=>{if(e.detail.contextLost){$('#render-status').textContent='画面暂时不可用，请重新构建';report('error',{message:'WebGL 画面暂时不可用'});return;}const compatible=e.detail.renderer==='canvas';$('#render-status').textContent=compatible?'二维兼容预览':'拖动旋转 · 滚轮缩放';if(compatible){state.setting='studio';state.reflections=false;$('[data-view=front]').disabled=true;}report('ready',{renderer:e.detail.renderer});if(renderer)report('result',snapshot());});
  const {createProductRenderer}=await import('../product-renderer.js?v=20261002-8');renderer=createProductRenderer($('#product-canvas'),()=>state);
  document.querySelectorAll('[name=color]').forEach(el=>el.addEventListener('change',()=>{state.color=el.value;update();}));$('#finish')?.addEventListener('change',e=>{state.finish=e.target.value;update();});
  for(const key of ['light','explode'])$('#'+key)?.addEventListener('input',e=>{state[key]=Number(e.target.value);update();});
  document.querySelectorAll('[data-view]').forEach(b=>b.addEventListener('click',()=>{state.view=b.dataset.view;state.explode=state.view==='structure'?78:0;if($('#explode'))$('#explode').value=state.explode;document.querySelectorAll('[data-view]').forEach(el=>el.setAttribute('aria-pressed',String(el===b)));renderer.setView(state.view);update();}));
  $('#save-config').addEventListener('click',()=>{download(snapshot(),'product-selection.json');$('#export-status').textContent='已导出当前配置，可交给团队继续讨论。';});$('#save-image').addEventListener('click',()=>{renderer.draw();$('#product-canvas').toBlob(blob=>{if(blob){download(blob,'product-preview.png');$('#export-status').textContent='已导出当前画面。';}},'image/png');});
  document.querySelectorAll('[name=color]').forEach(el=>el.checked=el.value===state.color);if($('#finish'))$('#finish').value=state.finish;for(const key of ['light','explode'])if($('#'+key))$('#'+key).value=state[key];addEventListener('pagehide',()=>renderer?.dispose());update();
}else{
  const rules=c.coverage;$('#task').innerHTML=`<div class="p-query"><section class="p-query-form"><span class="p-kicker">01 / CHOOSE A REGION</span><h2>你需要在哪里提供服务？</h2><label class="p-field">地区<select id="region">${rules.regions.map(r=>`<option value="${r.id}">${esc(r.name)}</option>`).join('')}</select></label><label class="p-field">需求说明<textarea id="request-note" maxlength="400" placeholder="例如：两盏灯，安装在客厅和书房。"></textarea></label><button id="query" class="p-primary">查询${esc(rules.serviceName)}范围</button><p class="p-small">可用地区 ${rules.regions.filter(r=>r.available).length} / ${rules.regions.length} · 本地规则</p></section><section id="query-result" class="p-query-result" aria-live="polite"><span class="p-kicker">02 / YOUR RESULT</span><div class="p-result-icon" aria-hidden="true">↗</div><h2 id="query-title">先选地区，再看结果。</h2><p id="query-detail">查询后得到明确的服务状态和下一步。</p><div id="query-summary" class="p-result" hidden></div><button id="save-request" class="p-secondary" disabled>带走查询摘要</button><p class="p-small" id="export-status" role="status">没有提交预约或发送咨询。</p></section></div>`;
  let result=null;const snapshot=()=>result?{schemaVersion:'1.0',product:c.name,dataMode:'local-rules-unconfirmed',region:result.name,service:rules.serviceName,available:result.available,detail:result.detail,note:$('#request-note').value.trim(),submitted:false}:null;
  function summary(){if(!result)return;const s=snapshot();$('#query-summary').textContent=s.region+' / '+s.service+(s.note?' · '+s.note:'');report('result',s);}
  $('#query').addEventListener('click',()=>{result=rules.regions.find(r=>r.id===$('#region').value);$('#query-result').dataset.available=String(result.available);$('#query-title').textContent=result.name+' · '+(result.available?'在当前服务范围内':'暂未覆盖');$('#query-detail').textContent=result.detail||(result.available?'可记录需求，具体安排需人工确认。':'先保留需求，待服务范围更新。');$('#query-summary').hidden=false;$('#save-request').disabled=false;summary();});
  $('#region').addEventListener('change',()=>{result=null;$('#query-result').removeAttribute('data-available');$('#query-title').textContent='地区已改变，请重新查询。';$('#query-detail').textContent='上一个地区的结果不用于当前选择。';$('#query-summary').hidden=true;$('#save-request').disabled=true;report('result',null);});$('#request-note').addEventListener('input',summary);
  $('#save-request').addEventListener('click',()=>{const s=snapshot();if(!s)return;download(s,'service-request.json');$('#export-status').textContent='已导出当前地区与需求，供团队确认。';});report('ready',{renderer:'dom'});
}
