import {createRequire} from 'node:module';
import {writeFile} from 'node:fs/promises';
import {fileURLToPath} from 'node:url';
import {build} from 'esbuild';
const require=createRequire('C:/Users/yun68/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/package.json');
const {chromium}=require('playwright'),root=fileURLToPath(new URL('../',import.meta.url));
const browser=await chromium.launch({headless:true,args:['--enable-webgl','--ignore-gpu-blocklist','--enable-unsafe-swiftshader']});const errors=[];
try{const page=await browser.newPage({viewport:{width:1536,height:1120}});page.setDefaultTimeout(60000);
 page.on('pageerror',e=>{errors.push(e.message);console.log(e.message);});page.on('console',m=>{if(m.type()==='error'){errors.push(m.text());console.log(m.text().slice(0,6000));}});
 await page.goto('http://127.0.0.1:8947/#scene',{timeout:90000});await page.waitForFunction(()=>window.__courtyard?.frameIndex>2,null,{timeout:120000});await page.evaluate(()=>window.__courtyard.active=false);
 const clip=await page.locator('#scene-canvas').boundingBox();const render=async name=>{await page.evaluate(()=>{const c=window.__courtyard;if(c.transition){const t=c.transition;c.camera.position.copy(t.to);c.controls.target.copy(t.toTarget);c.camera.fov=t.fov;c.camera.updateProjectionMatrix();c.transition=null;}c.controls.update();c.water.update(c.time,c.settings,c.sunDirection,c.sun.color,0);c.water.renderPasses([c.school.group,c.school.food],[c.waterfall.group,c.interaction.rig.root]);c.composer.render();document.body.classList.add('clean-scene');});await page.screenshot({path:root+'assets/'+name+'.png',clip,timeout:90000});};
 const advance=seconds=>page.evaluate(seconds=>{const c=window.__courtyard;for(let t=0;t<seconds-1e-7;t+=.025)c.updateDynamics(Math.min(.025,seconds-t));},seconds);
 const closeHand=()=>page.evaluate(()=>{const c=window.__courtyard,p=c.interaction.grain.getWorldPosition(c.interaction.rig.root.position.clone());
  window.__feedShot={position:c.camera.position.clone(),target:c.controls.target.clone(),fov:c.camera.fov};c.camera.position.set(p.x-.23,p.y+.25,p.z+.22);c.controls.target.copy(p).add({x:.018,y:.012,z:0});c.camera.fov=44;c.camera.updateProjectionMatrix();c.transition=null;c.controls.update();});
 const restoreShot=()=>page.evaluate(()=>{const c=window.__courtyard,s=window.__feedShot;c.camera.position.copy(s.position);c.controls.target.copy(s.target);c.camera.fov=s.fov;c.camera.updateProjectionMatrix();c.controls.update();});
 await page.locator('#feed').click();await advance(1.18);await render('feeding-pinch-v4');await closeHand();await render('feeding-grasp-close-v4');await restoreShot();
 await advance(.62);await render('feeding-release-v4');await closeHand();await render('feeding-release-close-v4');await restoreShot();
 await advance(.30);await closeHand();await render('feeding-open-close-v4');await restoreShot();await advance(.10);await render('feeding-water-v4');
 const hand=await page.evaluate(()=>{const h=window.__courtyard.interaction;return {mode:h.mode,emitted:h.emitted,total:h.totalPellets,gap:h.rig.pinchGap,held:h.grain.children.filter(m=>m.visible).length};});
 const eat=await page.evaluate(()=>{const c=window.__courtyard;let event=null;for(let i=0;i<800;i++){c.updateDynamics(.025);const m=c.school.food.children.find(m=>m.userData.particle?.swallow&&!m.userData.particle.eaten);if(m){const f=m.userData.particle.swallow.fish;event={fish:c.school.fish.indexOf(f),time:c.time,mouth:f.mouthOpen,pellet:m.position.toArray(),mouthPosition:c.school.mouthWorld(f).toArray()};window.__biteFish=f;break;}}
  if(window.__biteFish){const f=window.__biteFish,p=f.group.position;c.camera.position.set(p.x+Math.cos(f.heading)*.52-Math.sin(f.heading)*.34,.30,p.z-Math.sin(f.heading)*.52-Math.cos(f.heading)*.34);c.controls.target.copy(c.school.mouthWorld(f));c.camera.fov=44;c.camera.updateProjectionMatrix();c.transition=null;}return event;});await render('koi-eating-v4');
 await page.evaluate(()=>{const c=window.__courtyard;c.interaction.stop();c.school.feedUntil=0;c.school.food.visible=false;c.school.fish.forEach((f,i)=>f.group.visible=i===0);const f=c.school.fish[0];f.group.position.set(-.4,-.081,2.85);f.group.rotation.set(0,0,.23);f.group.scale.setScalar(.64);f.mouthOpen=.93;f.state.uMouth.value=.93;f.state.uPhase.value=.5;f.state.uAmp.value=.020;
  c.camera.position.set(.23,.30,3.12);c.controls.target.set(-.08,.02,2.85);c.camera.fov=47;c.camera.updateProjectionMatrix();c.controls.update();});await render('koi-head-open-v4');
 const legacy=await build({stdin:{contents:"import {KoiSchool} from './src/fish-v3.js';window.__oldKoi=KoiSchool;",resolveDir:root},bundle:true,format:'iife',write:false,nodePaths:[root+'tooling/node_modules']});await page.addScriptTag({content:legacy.outputFiles[0].text});
 await page.evaluate(()=>{const c=window.__courtyard,old=new window.__oldKoi(c.scene,c.water);old.fish.forEach((f,i)=>f.group.visible=i===0);const f=old.fish[0],fresh=c.school.fish[0];f.group.position.copy(fresh.group.position);f.group.quaternion.copy(fresh.group.quaternion);f.group.scale.copy(fresh.group.scale);c.school.group.visible=false;old.food.visible=false;window.__oldSchool=old;});await render('koi-head-before-v4');
 await page.evaluate(()=>{const c=window.__courtyard;c.scene.remove(window.__oldSchool.group);c.scene.remove(window.__oldSchool.food);c.school.group.visible=true;const f=c.school.fish[0];f.mouthOpen=.05;f.state.uMouth.value=.05;});await render('koi-head-closed-v4');
 await page.evaluate(()=>{const c=window.__courtyard;c.school.fish[0].state.uMouth.value=.3;c.camera.position.set(-.05,.76,3.58);c.controls.target.set(-.4,.015,2.85);c.camera.fov=46;c.camera.updateProjectionMatrix();c.controls.update();});await render('koi-body-v4');
 console.log(JSON.stringify({hand,eat,errors:errors.length}));await writeFile(root+'notes/koi-capture-v4.json',JSON.stringify({hand,eat,errors},null,2));
}finally{await browser.close();}
