import {createRequire} from 'node:module';
import assert from 'node:assert/strict';
import {writeFile} from 'node:fs/promises';
import {fileURLToPath} from 'node:url';
const require=createRequire('C:/Users/yun68/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/package.json');
const {chromium}=require('playwright'),root=fileURLToPath(new URL('../',import.meta.url));
const browser=await chromium.launch({headless:true,args:['--enable-webgl','--ignore-gpu-blocklist','--enable-unsafe-swiftshader']});
const errors=[],checks=[];const check=(name,value)=>{assert.ok(value,name);checks.push(name);console.log('PASS '+name);};
try{
  const page=await browser.newPage({viewport:{width:1536,height:1120},deviceScaleFactor:1});page.setDefaultTimeout(60000);
  page.on('pageerror',e=>errors.push(e.message));page.on('console',m=>{if(m.type()==='error')errors.push(m.text());});
  await page.goto('http://127.0.0.1:8947/#scene',{timeout:90000});await page.waitForFunction(()=>window.__courtyard?.frameIndex>3,null,{timeout:120000});await page.evaluate(()=>window.__courtyard.active=false);
  const render=async(name)=>{await page.evaluate(()=>{const c=window.__courtyard;if(c.transition){const t=c.transition;c.camera.position.copy(t.to);c.controls.target.copy(t.toTarget);c.camera.fov=t.fov;c.camera.updateProjectionMatrix();c.transition=null;}if(c.followAnimal){const v=c.animals.getView(c.followAnimal);c.camera.position.set(...v.position);c.controls.target.set(...v.target);}c.controls.update();c.water.update(c.time,c.settings,c.sunDirection,c.sun.color,0);c.water.renderPasses([c.school.group,c.school.food],[c.waterfall.group,c.interaction.rig.root]);c.composer.render();document.body.classList.add('clean-scene');});
    const clip=await page.locator('#scene-canvas').boundingBox();await page.screenshot({path:root+'assets/'+name+'.png',clip,timeout:90000});await page.evaluate(()=>document.body.classList.remove('clean-scene'));};
  const advance=seconds=>page.evaluate(seconds=>{const c=window.__courtyard;for(let t=0;t<seconds-1e-7;t+=.05)c.updateDynamics(Math.min(.05,seconds-t));},seconds);
  check('GPU 半浮点涟漪可用',await page.evaluate(()=>window.__courtyard.water.simulation.enabled));
  const wave=await page.evaluate(()=>{const c=window.__courtyard,s=c.water.simulation;s.reset();c.water.addRipple(-.5,-.15,c.time,.035);for(let i=0;i<22;i++)s.update(1/60);
    const values=new Uint16Array(s.size*s.size*4);c.renderer.readRenderTargetPixels(s.targets[s.index],0,0,s.size,s.size,values);let count=0,outside=0;for(let y=0;y<s.size;y++)for(let x=0;x<s.size;x++){const k=(y*s.size+x)*4;if(values[k]!==0){count++;if(s.mask.image.data[k]===0)outside++;}}const steps=s.stepCount;s.update(0);return {count,outside,steps,paused:s.stepCount===steps};});
  check('涟漪从扰动点向邻域传播',wave.count>25);check('池岸遮罩外高度保持零',wave.outside===0);check('暂停不推进 GPU 模拟',wave.paused);
  check('折射目标保存深度纹理',await page.evaluate(()=>!!window.__courtyard.water.refractionTarget.depthTexture&&window.__courtyard.water.material.uniforms.refractionDepth.value===window.__courtyard.water.refractionTarget.depthTexture));
  const state=await page.evaluate(()=>{const c=window.__courtyard,h=c.interaction.rig,g=h.mesh.geometry;let valid=true;const w=g.attributes.skinWeight,p=g.attributes.position;
    for(let i=0;i<w.count;i++){const sum=w.getX(i)+w.getY(i)+w.getZ(i)+w.getW(i);if(Math.abs(sum-1)>.0001||!Number.isFinite(p.getX(i)+p.getY(i)+p.getZ(i)))valid=false;}return {valid,bones:h.bones.length,vertices:p.count};});
  check('手部几何与骨骼权重有效',state.valid&&state.bones>=16&&state.vertices>1000);
  await page.locator('#feed').click();check('投喂进入手部伸出阶段',await page.evaluate(()=>window.__courtyard.interaction.mode==='feed'&&window.__courtyard.interaction.rig.root.visible));
  await advance(2);check('食物释放并建立鱼群目标',await page.evaluate(()=>{const c=window.__courtyard;return c.interaction.released&&c.school.feedUntil>c.time&&c.school.feedPoint.z>=3;}));
  await render('feeding-v2');await advance(4);check('投喂结束后手部退场',await page.evaluate(()=>window.__courtyard.interaction.mode==='idle'&&!window.__courtyard.interaction.rig.root.visible));
  await page.locator('#stroke').click();await advance(4);check('锦鲤靠近后进入实际抚摸阶段',await page.evaluate(()=>{const c=window.__courtyard;return c.interaction.contact&&c.interaction.phase==='contact'&&c.school.strokeTarget.fish.group.position.distanceTo(c.interaction.point)<.22;}));
  await render('stroking-v2');await advance(7);check('抚摸退出释放鱼群控制',await page.evaluate(()=>window.__courtyard.interaction.mode==='idle'&&window.__courtyard.school.strokeTarget===null));
  await page.evaluate(()=>{const c=window.__courtyard;c.updateSettings({fishCount:0});c.stroke();});check('无鱼时禁止抚摸且给出反馈',await page.evaluate(()=>window.__courtyard.interaction.mode==='idle'&&document.querySelector('#scene-toast').textContent.includes('增加锦鲤')));
  await page.evaluate(()=>{const c=window.__courtyard;c.updateSettings({fishCount:7});c.animals.reset();});
  await page.locator('[data-animal="frog"]').click();await advance(.4);check('青蛙跳跃抬升并切换伸腿模型',await page.evaluate(()=>{const f=window.__courtyard.animals.frog;return f.state==='jump'&&f.root.position.y>.3&&f.body.geometry===f.leapGeo;}));await render('frog-v2');
  await advance(.5);check('青蛙落到另一片睡莲',await page.evaluate(()=>{const f=window.__courtyard.animals.frog;return f.state==='rest'&&f.pad===1&&Math.abs(f.root.position.y-.043)<.001;}));
  await page.locator('[data-animal="turtle"]').click();await advance(3);check('乌龟从晒台进入游泳状态',await page.evaluate(()=>{const t=window.__courtyard.animals.turtle;return t.state==='swim'&&t.root.position.y<0;}));await render('turtle-v2');
  await advance(32);check('乌龟完整循环后回到晒台',await page.evaluate(()=>window.__courtyard.animals.turtle.state==='bask'));
  await page.locator('[data-animal="dragonfly"]').click();await advance(.8);check('三只蜻蜓重新起飞',await page.evaluate(()=>window.__courtyard.animals.dragonflies.length===3&&window.__courtyard.animals.dragonflies.every(d=>d.state==='fly')));await render('dragonfly-v2');
  await page.locator('#view-select').selectOption('reference');await page.evaluate(()=>window.__courtyard.setView('reference',true));await render('scene-v2-final');
  await page.locator('#feed').click();await page.locator('#stop-interaction').click();check('用户可主动结束手部互动',await page.evaluate(()=>window.__courtyard.interaction.mode==='idle'));
  await page.evaluate(()=>{const c=window.__courtyard;c.reset();c.setView('reference',true);});await render('scene-v2-final');
  await page.screenshot({path:root+'assets/studio-v2-final.png',fullPage:true});
  await page.setViewportSize({width:390,height:844});await page.evaluate(()=>window.__courtyard.resize());await render('scene-mobile-v2');
  check('移动端无横向溢出',await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));
  check('移动端六个主要动作均在画布内',await page.evaluate(()=>{const box=document.querySelector('#viewport').getBoundingClientRect();return ['feed','stroke','tour-toggle','pause-toggle','audio-toggle','capture'].every(id=>{const r=document.getElementById(id).getBoundingClientRect();return r.left>=box.left&&r.right<=box.right&&r.bottom<=box.bottom;});}));
  await page.screenshot({path:root+'assets/mobile-v2.png',fullPage:true});
  check('浏览器与着色器错误为零',errors.length===0);await writeFile(root+'notes/v2-validation.json',JSON.stringify({checks,errors,wave,hand:state,method:'Headless Chromium / software WebGL. Action state machines advanced deterministically in 0.05s simulation steps; selected frames rendered. Not a hardware performance benchmark.'},null,2));
  console.log(JSON.stringify({checks:checks.length,errors}));
}finally{await browser.close();}
