import {createRequire} from 'node:module';
import {writeFile} from 'node:fs/promises';
import {fileURLToPath} from 'node:url';
import assert from 'node:assert/strict';
const require=createRequire('C:/Users/yun68/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/package.json');
const {chromium}=require('playwright'),root=fileURLToPath(new URL('../',import.meta.url));
const browser=await chromium.launch({headless:true,args:['--enable-webgl','--ignore-gpu-blocklist','--enable-unsafe-swiftshader']});
const checks=[],errors=[],requests=[],evidence={};
const check=(name,value)=>{assert.ok(value,name);checks.push(name);console.log('PASS '+name);};
try{const page=await browser.newPage({viewport:{width:1536,height:1120}});page.setDefaultTimeout(60000);
 page.on('pageerror',e=>errors.push(e.message));page.on('console',m=>{if(m.type()==='error')errors.push(m.text());});page.on('request',r=>requests.push(r.url()));
 await page.goto('http://127.0.0.1:8947/#scene',{timeout:90000});await page.waitForFunction(()=>window.__courtyard?.frameIndex>2,null,{timeout:120000});await page.evaluate(()=>window.__courtyard.active=false);
 const advance=seconds=>page.evaluate(seconds=>{const c=window.__courtyard;for(let t=0;t<seconds-1e-7;t+=.05)c.updateDynamics(Math.min(.05,seconds-t));},seconds);
 evidence.mesh=await page.evaluate(()=>{const r=window.__courtyard.interaction.rig,g=r.mesh.geometry,p=g.attributes.position,w=g.attributes.skinWeight,n=g.attributes.normal;let valid=true,inward=0;
  for(let i=0;i<p.count;i++){if(!Number.isFinite(p.getX(i)+p.getY(i)+p.getZ(i))||Math.abs(w.getX(i)+w.getY(i)+w.getZ(i)+w.getW(i)-1)>.0001)valid=false;
   if(p.getX(i)<-.04&&p.getX(i)>-.17&&(p.getY(i)+.0023)*n.getY(i)+(p.getZ(i)-.0028)*n.getZ(i)<0)inward++;}
  const tex=r.material.userData.skinTexture;return {valid,inward,vertices:p.count,bones:r.bones.length,texture:tex.image?.width,skinPath:tex.image?.src,nails:r.nails.filter(n=>n.isSkinnedMesh&&n.skeleton===r.mesh.skeleton).length,palmSamples:r.palmSamples.length};});
 check('连续手臂网格与归一化骨骼权重',evidence.mesh.valid&&evidence.mesh.vertices>20000&&evidence.mesh.bones===26);
 check('手腕接缝外法线方向正确',evidence.mesh.inward===0);
 check('皮肤贴图加载到实际三维材质',evidence.mesh.texture>=1000&&evidence.mesh.skinPath.endsWith('hand-skin-albedo-v3.png'));
 check('五片指甲与手指共享表面骨骼权重',evidence.mesh.nails===5);
 check('掌面接触采样覆盖有效',evidence.mesh.palmSamples>=20&&evidence.mesh.palmSamples<=64);
 await page.locator('#compare').evaluate(e=>e.value='100');await page.locator('#compare').dispatchEvent('input');await page.locator('#hand-inspect').click();await advance(.1);
 check('近景查看清除参考图并显示手部',await page.evaluate(()=>window.__courtyard.interaction.mode==='inspect'&&window.__courtyard.interaction.rig.root.visible&&document.querySelector('#reference-overlay').hidden));
 const open=await page.evaluate(()=>window.__courtyard.interaction.rig.bones.map(b=>b.quaternion.toArray()));
 await page.evaluate(()=>window.__courtyard.controls.dispatchEvent({type:'start'}));check('查看模式允许掌心角度并保持手部',await page.evaluate(()=>window.__courtyard.interaction.mode==='inspect'&&window.__courtyard.controls.maxPolarAngle>2));
 await advance(3.1);evidence.pinch=await page.evaluate(open=>{const h=window.__courtyard.interaction,H=h.rig,grain=h.grain.getWorldPosition(H.root.position.clone()),a=H.tips.index.getWorldPosition(H.root.position.clone()),b=H.tips.thumb.getWorldPosition(H.root.position.clone());return {gap:a.distanceTo(b),grainVisible:h.grain.visible,grainError:grain.distanceTo(a.add(b).multiplyScalar(.5)),changed:H.bones.filter((bone,i)=>bone.quaternion.toArray().some((v,j)=>Math.abs(v-open[i][j])>.01)).length};},open);
 check('拇指和食指形成毫米级捏合',evidence.pinch.gap>.005&&evidence.pinch.gap<.014);
 check('捏合过程中多关节独立弯曲',evidence.pinch.changed>=8);
 check('持有饲料位于两指之间',evidence.pinch.grainVisible&&evidence.pinch.grainError<.0001);
 await page.locator('#feed').click();check('查看模式可直接进入投喂',await page.evaluate(()=>window.__courtyard.interaction.mode==='feed'));
 await advance(1.25);check('伸手阶段没有提前落下的饲料',await page.evaluate(()=>window.__courtyard.interaction.emitted===0&&window.__courtyard.school.food.children.every(m=>!m.visible)));
 await advance(.45);evidence.release=await page.evaluate(()=>{const c=window.__courtyard,H=c.interaction.rig,m=c.school.food.children.find(m=>m.userData.particle),p=m?.userData.particle,center=H.tips.index.getWorldPosition(H.root.position.clone()).add(H.tips.thumb.getWorldPosition(H.root.position.clone())).multiplyScalar(.5);return {count:c.interaction.emitted,gap:p?.origin.distanceTo(center),y:m?.position.y,originY:p?.origin.y,vY:p?.velocity.y,time:p?.time,now:c.time};});
 check('饲料从当前指尖位置释放',evidence.release.count>0&&evidence.release.gap<.010);
 await advance(.1);evidence.fall=await page.evaluate(()=>{const c=window.__courtyard,m=c.school.food.children[0],p=m.userData.particle,age=c.time-p.time;return {age,y:m.position.y,expected:p.origin.y+p.velocity.y*age-4.905*age*age};});
 check('离手饲料按重力下落',evidence.fall.age>.09&&Math.abs(evidence.fall.y-evidence.fall.expected)<.0001);
 const frozen=await page.evaluate(()=>{const c=window.__courtyard;c.updateSettings({paused:true});c.active=true;return {frame:c.frameIndex,time:c.time,timer:c.interaction.timer,food:c.school.food.children.filter(m=>m.visible).map(m=>m.position.toArray())};});
 await page.waitForFunction(n=>window.__courtyard.frameIndex>n,frozen.frame,{timeout:90000});
 const afterPause=await page.evaluate(()=>{const c=window.__courtyard;c.active=false;return {time:c.time,timer:c.interaction.timer,food:c.school.food.children.filter(m=>m.visible).map(m=>m.position.toArray())};});
 check('暂停冻结手部阶段和饲料位置',frozen.time===afterPause.time&&frozen.timer===afterPause.timer&&JSON.stringify(frozen.food)===JSON.stringify(afterPause.food));
 await page.evaluate(()=>window.__courtyard.updateSettings({paused:false}));await advance(2.3);
 evidence.food=await page.evaluate(()=>{const c=window.__courtyard;return {emitted:c.interaction.emitted,landed:c.school.food.children.filter(m=>m.userData.particle?.landed).length,visible:c.school.food.children.filter(m=>m.visible).map(m=>m.position.y)};});
 console.log('Food evidence '+JSON.stringify(evidence.food));
 check('分次释放18粒饲料且落到水面',evidence.food.emitted===18&&evidence.food.landed>0&&evidence.food.visible.every(y=>y>.025&&y<.045));
 await advance(1.3);check('投喂完成后自然退场',await page.evaluate(()=>window.__courtyard.interaction.mode==='idle'&&!window.__courtyard.interaction.rig.root.visible));
 await page.locator('#stroke').click();await advance(4);
 evidence.contact=await page.evaluate(()=>{const h=window.__courtyard.interaction;return {mode:h.mode,phase:h.phase,touching:h.touching,clearance:h.rig.contactClearance,wet:h.rig.wet};});
 check('锦鲤靠近后手掌进入实际接触',evidence.contact.mode==='stroke'&&evidence.contact.phase==='contact'&&evidence.contact.touching);
 check('掌面保持在鱼背表面外',evidence.contact.clearance>=.0014&&evidence.contact.clearance<.025);
 check('接触后皮肤湿润度逐渐增加',evidence.contact.wet>.45&&evidence.contact.wet<=.8);
 await page.locator('#stop-interaction').click();check('主动结束抚摸立即释放鱼群',await page.evaluate(()=>window.__courtyard.interaction.mode==='idle'&&window.__courtyard.school.strokeTarget===null));
 await page.locator('#hand-inspect').click();await page.locator('#view-select').selectOption('aerial');check('切换普通镜头退出手部近景并恢复俯角限制',await page.evaluate(()=>window.__courtyard.interaction.mode==='idle'&&window.__courtyard.controls.maxPolarAngle<Math.PI/2));
 await page.setViewportSize({width:390,height:844});await page.evaluate(()=>window.__courtyard.resize());
 check('移动端可使用手部查看且没有横向溢出',await page.locator('#hand-inspect').isVisible()&&await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));
 check('手部着色器与脚本错误为零',errors.length===0);
 check('手部资产全部本地加载',requests.every(u=>u.startsWith('http://127.0.0.1:8947/')||u.startsWith('blob:')||u.startsWith('data:')));
 await writeFile(root+'notes/hand-validation.json',JSON.stringify({date:new Date().toISOString(),checks,evidence,errors,method:'Headless Chromium / software WebGL, simulated 0.05s action steps with real paused frame and actual mesh materials. Not hardware performance or measured anatomy.'},null,2));
 console.log(JSON.stringify({checks:checks.length,evidence,errors}));
}finally{await browser.close();}
