// Run only after explicit user authorization for isolated local-browser QA.
import {createRequire} from 'node:module';
import {readFile,writeFile} from 'node:fs/promises';
import {fileURLToPath} from 'node:url';
import {createHash} from 'node:crypto';
import assert from 'node:assert/strict';

if(!process.argv.includes('--approved-local-browser'))throw new Error('Explicit approval required before launching isolated browser QA.');
const root=fileURLToPath(new URL('../',import.meta.url));
const expected='713cfa3c73643e367b8d27efc33151be35aa64817ff1f412e1eff48ffeb30bae';
const bundle=createHash('sha256').update(await readFile(root+'web/app.js')).digest('hex');
assert.equal(bundle,expected,'QA target is the reviewed final build');
const scriptSha256=createHash('sha256').update(await readFile(fileURLToPath(import.meta.url))).digest('hex');
const require=createRequire('C:/Users/yun68/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/package.json');
const {chromium}=require('playwright');
const checks=[],captures=[],errors=[],warnings=[],externalRequests=[];
let browser,page;
const check=(name,condition,evidence)=>{assert.ok(condition,name);checks.push({name,passed:true,...evidence?{evidence}:{}});console.log('PASS '+name);};
const readText=(page,id)=>page.locator('#'+id).innerText();
async function capture(page,name){await page.screenshot({path:root+'assets/'+name,type:'jpeg',quality:90});captures.push('assets/'+name);}
try{
 browser=await chromium.launch({headless:true,args:['--enable-webgl','--ignore-gpu-blocklist']});
 page=await browser.newPage({viewport:{width:1280,height:960},deviceScaleFactor:1});
 page.setDefaultTimeout(60000);
 page.on('pageerror',e=>errors.push(e.message));
 page.on('console',m=>{if(m.type()==='warning')warnings.push(m.text());});
 await page.route('**/*',route=>{const url=new URL(route.request().url());if(['data:','blob:'].includes(url.protocol)||url.origin==='http://127.0.0.1:8947')return route.continue();externalRequests.push(url.href);return route.abort();});
 await page.goto('http://127.0.0.1:8947/?v=713cfa3c#scene',{waitUntil:'domcontentloaded',timeout:90000});
 await page.waitForFunction(()=>document.getElementById('scene-loader')?.hidden,null,{timeout:120000});
 check('new scene initializes and feeding feedback is initially hidden',!await page.locator('#feeding-feedback').isVisible());
 await page.locator('#setting-fishCount').press('Home');
 check('fish-count control can select zero',await page.locator('#setting-fishCount').inputValue()==='0');
 await page.locator('#feed').click();
 await page.locator('#feeding-feedback').waitFor({state:'visible'});
 check('zero-fish main feed keeps zero and explains observation-only behavior',await page.locator('#setting-fishCount').inputValue()==='0'&&/当前无鱼/.test(await readText(page,'feeding-status')));
 await page.waitForFunction(()=>document.getElementById('feeding-counts')?.textContent.includes('本轮释放 6/6 粒'),null,{timeout:120000});
 await page.waitForFunction(()=>document.getElementById('feeding-counts')?.textContent.includes('实际落水 6 粒'),null,{timeout:60000});
 await page.locator('#feeding-pause').click();
 const frozen=await readText(page,'feeding-counts');
 check('actual six-pellet release and landing have a separate zero swallow count',/本轮释放 6\/6 粒/.test(frozen)&&/实际落水 6 粒/.test(frozen)&&/吞食 0 粒/.test(frozen),frozen);
 check('pause has a truthful pressed state and status',await page.locator('#feeding-pause').getAttribute('aria-pressed')==='true'&&/模拟已暂停/.test(await readText(page,'feeding-status')));
 await page.keyboard.press('Tab');
 check('keyboard can move from pause to a feedback action',['feeding-stop','feeding-again'].includes(await page.evaluate(()=>document.activeElement?.id)));
 await page.locator('#feeding-feedback').scrollIntoViewIfNeeded();
 await capture(page,'feeding-desktop-v16.jpg');
 if(await page.locator('#feeding-stop').isVisible())await page.locator('#feeding-stop').click();
 check('hand withdrawal preserves the frozen batch',await readText(page,'feeding-counts')===frozen);
 if(!await page.locator('#glb-panel').evaluate(el=>el.open))await page.locator('#glb-panel > summary').click();
 await page.locator('#model-file').setInputFiles({name:'invalid.glb',mimeType:'model/gltf-binary',buffer:Buffer.from('invalid')});
 await page.waitForFunction(()=>document.getElementById('scene-toast')?.textContent.startsWith('模型导入失败'));
 check('rejected GLB retains the previous feed record',await page.locator('#feeding-feedback').isVisible()&&await readText(page,'feeding-counts')===frozen);
 await page.locator('#model-file').setInputFiles(root+'web/assets/binding-example.glb');
 await page.waitForFunction(()=>document.getElementById('model-status')?.textContent.includes('binding-example.glb'),null,{timeout:90000});
 check('accepted unbound model clears feeding feedback and disables feeding',!await page.locator('#feeding-feedback').isVisible()&&!await page.locator('#feed').isEnabled());
 await page.locator('#clear-model').click();
 await page.waitForFunction(()=>document.getElementById('model-status')?.textContent==='尚未导入模型');
 check('returning to courtyard does not revive the previous round',!await page.locator('#feeding-feedback').isVisible()&&await page.locator('#feed').isEnabled());
 await page.locator('#feed').click();await page.locator('#feeding-pause').click();
 const freshCounts=await readText(page,'feeding-counts'),freshRelease=/本轮释放 (\d+)\/6 粒/.exec(freshCounts),freshCumulative=/场景累计释放 (\d+) 粒/.exec(freshCounts);
 check('fresh courtyard cumulative releases include only the new round',freshRelease&&freshCumulative&&freshRelease[1]===freshCumulative[1],freshCounts);
 await page.locator('#feeding-stop').click();
 check('manual withdrawal identifies the stopped hand without inventing swallowed pellets',/提前停止/.test(await readText(page,'feeding-status'))&&/吞食 0 粒/.test(await readText(page,'feeding-counts')));
 await page.setViewportSize({width:390,height:844});
 await page.locator('#feeding-feedback').scrollIntoViewIfNeeded();
 const mobile=await page.locator('#feeding-feedback').evaluate(el=>({pageWidth:document.documentElement.scrollWidth,clientWidth:document.documentElement.clientWidth,buttons:[...el.querySelectorAll('button')].map(b=>{const r=b.getBoundingClientRect();return {id:b.id,height:r.height,width:r.width};}).filter(b=>b.height>0&&b.width>0)}));
 check('mobile page has no horizontal overflow and feedback action targets are at least 44px',mobile.pageWidth<=mobile.clientWidth&&['feeding-pause','feeding-again'].every(id=>mobile.buttons.some(b=>b.id===id))&&mobile.buttons.every(b=>b.height>=44&&b.width>=44),mobile);
 await capture(page,'feeding-mobile-v16.jpg');
 await page.locator('#feeding-again').click();
 await page.locator('#feeding-pause').click();
 check('mobile repeat-feed keeps zero fish and can pause the new hand',await page.locator('#setting-fishCount').inputValue()==='0'&&/当前无鱼/.test(await readText(page,'feeding-status'))&&await page.locator('#feeding-stop').isVisible()&&await page.locator('#feeding-pause').getAttribute('aria-pressed')==='true');
 const activeMobile=await page.locator('#feeding-feedback').evaluate(el=>[...el.querySelectorAll('button')].map(b=>{const r=b.getBoundingClientRect();return {id:b.id,height:r.height,width:r.width};}).filter(b=>b.height>0&&b.width>0));
 check('mobile paused active feed retains all three accessible action targets',['feeding-pause','feeding-stop','feeding-again'].every(id=>activeMobile.some(b=>b.id===id))&&activeMobile.every(b=>b.height>=44&&b.width>=44),activeMobile);
 await capture(page,'feeding-mobile-active-v16.jpg');
 await page.locator('#reset').click();
 check('reset clears the feeding panel and restores seven fish',!await page.locator('#feeding-feedback').isVisible()&&await page.locator('#setting-fishCount').inputValue()==='7');
 check('no uncaught page errors or external requests',errors.length===0&&externalRequests.length===0,{errors,externalRequests});
}catch(error){checks.push({name:'browser verification execution',passed:false,error:error.message});if(page)try{await capture(page,'feeding-failure-v16.jpg');}catch{}throw error;
}finally{
 await writeFile(root+'notes/browser-v16-validation.json',JSON.stringify({date:new Date().toISOString(),clientDate:'2026-10-03',version:16,bundleSha256:bundle,scriptSha256,authorization:{reply:'继续优化',context:'Reply to the preceding explicit request for isolated localhost Playwright acceptance.'},method:'User-authorized isolated headless Chromium, real UI actions and read-only DOM observations. Uses software-capable WebGL; not a hardware performance or full accessibility test.',checks,passed:checks.filter(c=>c.passed).length,failed:checks.filter(c=>!c.passed).length,captures,errors,warnings,externalRequests},null,2)+'\n');
 if(browser)await browser.close();
}
