import {createRequire} from 'node:module';
import {readFile,writeFile} from 'node:fs/promises';
import {createHash} from 'node:crypto';
import {fileURLToPath} from 'node:url';
import assert from 'node:assert/strict';
const require=createRequire('C:/Users/yun68/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/package.json');
const {chromium}=require('playwright'),root=fileURLToPath(new URL('../',import.meta.url));
const {habitatClearance}=await import('../src/habitat-geometry.js');
const browser=await chromium.launch({headless:true,args:['--enable-webgl','--ignore-gpu-blocklist','--enable-unsafe-swiftshader']});
const checks=[],errors=[],requests=[],evidence={};let fatal=null;
const check=(name,ok)=>{assert.ok(ok,name);checks.push(name);console.log('PASS '+name);};
try{
 const page=await browser.newPage({viewport:{width:1536,height:1120},deviceScaleFactor:1});
 page.on('pageerror',e=>errors.push(e.message));page.on('console',m=>{if(m.type()==='error')errors.push(m.text());});page.on('request',r=>requests.push(r.url()));
 await page.goto('http://127.0.0.1:8947/?v=6#scene',{timeout:90000});
 await page.waitForFunction(()=>window.__courtyard?.frameIndex>2,null,{timeout:120000});
 await page.evaluate(()=>window.__courtyard.active=false);
 check('完整场景实际 WebGL 启动',await page.evaluate(()=>!window.__courtyard.renderer.getContext().isContextLost()));
 await page.locator('#exp-open').click();
 await page.locator('#exp-separation-weight').evaluate(e=>e.value='3.15');await page.locator('#exp-separation-weight').dispatchEvent('input');
 check('滑块改变实际分离权重及读数',await page.evaluate(()=>window.__courtyard.school.experiment.separation===3.15&&document.querySelector('#exp-separation-value').textContent==='3.15'));
 await page.locator('#exp-separation').uncheck();await page.locator('#exp-alignment').uncheck();await page.locator('#exp-cohesion').uncheck();
 evidence.disabledForces=await page.evaluate(()=>{const c=window.__courtyard;c.updateDynamics(1/60);return c.school.fish.slice(0,c.settings.fishCount).map(f=>f.debugForces);});
 check('关闭三条规则后实际加权向量为零',evidence.disabledForces.every(f=>['separation','alignment','cohesion'].every(k=>Math.hypot(f[k].x,f[k].z)<1e-10)));
 await page.locator('#exp-reset').click();await page.locator('#exp-vectors').check();await page.locator('#exp-spheres').check();
 await page.evaluate(()=>{const c=window.__courtyard;for(let i=0;i<120;i++)c.updateDynamics(1/60);c.setView('pond',true);c.renderCurrent();});
 evidence.overlays=await page.evaluate(()=>{const c=window.__courtyard;return {visible:c.experiment.group.visible,spheres:c.experiment.spheres.count,fish:c.settings.fishCount,lines:c.experiment.lines.map(l=>({key:l.key,count:l.object.geometry.drawRange.count}))};});
 check('观察层使用实际行为向量与每鱼三个碰撞球',evidence.overlays.visible&&evidence.overlays.spheres===evidence.overlays.fish*3&&evidence.overlays.lines.some(l=>l.count>0));
 await page.locator('#scene-canvas').screenshot({path:root+'assets/algorithm-vectors-v6.png',timeout:90000});
 await page.locator('#exp-normal-correction').uncheck();
 check('法线开关更新全部鱼的实际着色器 uniform',await page.evaluate(()=>window.__courtyard.school.fish.every(f=>f.state.uNormalCorrection.value===0)));
 await page.locator('#exp-water-debug').selectOption('height');await page.evaluate(()=>window.__courtyard.renderCurrent());
 check('水面高度模式接入实际水面着色器',await page.evaluate(()=>window.__courtyard.water.material.uniforms.debugMode.value===1));
 await page.locator('#scene-canvas').screenshot({path:root+'assets/water-height-v6.png',timeout:90000});
 await page.locator('#exp-water-debug').selectOption('normal');await page.evaluate(()=>window.__courtyard.renderCurrent());
 check('水面法线模式成功渲染',await page.evaluate(()=>window.__courtyard.water.material.uniforms.debugMode.value===2));
 await page.locator('#scene-canvas').screenshot({path:root+'assets/water-normal-v6.png',timeout:90000});
 await page.locator('#exp-reset').click();await page.locator('#view-select').selectOption('aerial');await page.locator('#exp-vectors').check();await page.evaluate(()=>window.__courtyard.setView('aerial',true));await page.locator('#exp-duration').evaluate(e=>e.value='4');await page.locator('#exp-duration').dispatchEvent('input');
 await page.locator('#exp-baseline').click();await page.locator('#exp-run-a').click();await page.waitForFunction(()=>window.__courtyard.experiment.results.baseline,null,{timeout:90000});await page.locator('#exp-run-b').click();await page.waitForFunction(()=>window.__courtyard.experiment.results.current,null,{timeout:90000});
 evidence.same=await page.evaluate(()=>window.__courtyard.experiment.getState({includeImages:false}));
 check('相同起点种子和参数的真实 A/B 轨迹完全一致',evidence.same.difference?.sameTrajectory&&evidence.same.difference.meanPosition===0&&evidence.same.results.baseline.elapsed>3.99);
 check('重播结束暂停且两组真实画面可见',await page.evaluate(()=>window.__courtyard.settings.paused&&document.querySelectorAll('#exp-comparison img').length===2));
 await page.locator('#exp-cohesion-weight').evaluate(e=>e.value='4.5');await page.locator('#exp-cohesion-weight').dispatchEvent('input');await page.locator('#exp-run-b').click();await page.waitForFunction(()=>window.__courtyard.experiment.results.current,null,{timeout:90000});
 evidence.changed=await page.evaluate(()=>window.__courtyard.experiment.getState({includeImages:false}));
 check('仅改变 B 聚集权重产生不同轨迹且 A 结果保留',!evidence.changed.difference.sameTrajectory&&evidence.changed.difference.meanPosition>.01&&evidence.changed.results.baseline.signature===evidence.same.results.baseline.signature);
 await page.locator('#algorithm-experiments').screenshot({path:root+'assets/experiment-panel-v6.png',timeout:90000});
 await page.locator('#glb-panel summary').click();await page.locator('#binding-demo').click();
 await page.waitForFunction(()=>window.__courtyard.binding.applied,null,{timeout:60000});await page.evaluate(()=>window.__courtyard.active=false);
 evidence.binding=await page.evaluate(()=>{const c=window.__courtyard;return {binding:c.binding.exportData(),dynamics:c.hasDynamics,waterLevel:c.water.mesh.position.y,domain:c.water.domain,fishVisible:c.school.group.visible,rootVisible:c.root.visible,positions:c.school.fish.map(f=>f.group.position.toArray())};});
 check('程序 GLB 示例绑定独立水面鱼群与水位',evidence.binding.dynamics&&await page.locator('#view-select').inputValue()==='aerial'&&evidence.binding.waterLevel===.65&&evidence.binding.fishVisible&&!evidence.binding.rootVisible&&evidence.binding.binding.habitat.obstacles.length===2);
 check('方形涟漪域保持物理单元各向同性',evidence.binding.domain.width===evidence.binding.domain.height);
 check('绑定后投喂与鱼体观察入口启用',!await page.locator('#feed').isDisabled()&&!await page.locator('#fish-inspect').isDisabled());
 evidence.boundBodies=await page.evaluate(()=>{const c=window.__courtyard;let samples=[],finite=true;for(let i=0;i<1800;i++){c.updateDynamics(1/60);for(const f of c.school.fish.slice(0,c.settings.fishCount)){finite&&=f.group.position.toArray().every(Number.isFinite);if(i%15===0)for(const b of f.debugBodies)samples.push({x:b.x,z:b.z,radius:b.radius});}}return {finite,samples,habitat:c.school.habitat};});
 const clearances=evidence.boundBodies.samples.map(b=>habitatClearance(evidence.boundBodies.habitat,b.x,b.z)-b.radius);evidence.boundBodies.minClearance=Math.min(...clearances);delete evidence.boundBodies.samples;
 check('绑定鱼群运行30模拟秒后有限且三个球未穿岸或柱体',evidence.boundBodies.finite&&evidence.boundBodies.minClearance>=-1e-5);
 await page.evaluate(()=>{const c=window.__courtyard;c.setView('aerial',true);c.renderCurrent();});await page.locator('#scene-canvas').screenshot({path:root+'assets/bound-scene-v6.png',timeout:90000});
 await page.locator('#feed').click();
 evidence.boundFeed=await page.evaluate(()=>{const c=window.__courtyard;for(let i=0;i<1200;i++)c.updateDynamics(.025);const particles=c.school.food.children.filter(m=>m.userData.particle).map(m=>({landed:m.userData.particle.landed,eaten:m.userData.particle.eaten,expired:!!m.userData.particle.expired,landY:m.userData.particle.landY}));return {consumed:c.school.consumed,emitted:c.interaction.emitted,point:c.interaction.point?.toArray(),particles,mode:c.interaction.mode,drops:c.water.nextDrop};});
 check('绑定投喂六粒从手释放落水并被鱼吞食',evidence.boundFeed.emitted===6&&evidence.boundFeed.particles.length===6&&evidence.boundFeed.consumed===6&&evidence.boundFeed.particles.every(p=>p.eaten&&!p.expired)&&evidence.boundFeed.mode==='idle'&&evidence.boundFeed.drops>0);
 const exported=page.waitForEvent('download');await page.locator('#binding-export').click();await (await exported).saveAs(root+'notes/binding-export-v6.json');
 const binding=JSON.parse(await readFile(root+'notes/binding-export-v6.json','utf8'));
 check('绑定 JSON 导出实际模型指纹和参数',binding.modelSha256.length===64&&binding.modelScale===1&&binding.habitat.waterLevel===.65);
 await page.locator('#binding-disable').click();
 check('关闭绑定仅保留静态 GLB 与草稿',await page.evaluate(()=>!!window.__courtyard.imported&&!window.__courtyard.hasDynamics&&!window.__courtyard.water.mesh.visible&&window.__courtyard.binding.draft.polygon.length===4&&document.querySelector('#feed').disabled&&document.querySelector('#exp-baseline').disabled));
 await page.locator('#binding-file').setInputFiles({name:'binding.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(binding))});await page.waitForFunction(()=>window.__courtyard.hasDynamics);
 check('同模型同倍率的绑定 JSON 重新应用',await page.evaluate(()=>window.__courtyard.binding.applied.feedPoint.x===-1.2));
 const invalidScale={...binding,modelScale:null};await page.locator('#binding-file').setInputFiles({name:'missing-scale.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(invalidScale))});await page.waitForFunction(()=>document.querySelector('#scene-toast').textContent.includes('倍率'));check('拒绝缺失数值倍率的绑定并保持原绑定',await page.evaluate(()=>window.__courtyard.hasDynamics));
 const bad={...binding,modelSha256:'0'.repeat(64)};await page.locator('#binding-file').setInputFiles({name:'mismatch.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(bad))});
 await page.waitForFunction(()=>document.querySelector('#scene-toast').textContent.includes('不匹配'));
 check('拒绝异模型绑定文件并保持原绑定',await page.evaluate(()=>window.__courtyard.hasDynamics&&window.__courtyard.binding.applied.waterLevel===.65));
 // Exercise actual pointer picking instead of directly mutating the draft.
 await page.locator('#binding-feed-mode').click();
 await page.locator('#scene-canvas').scrollIntoViewIfNeeded();
 const pick=await page.evaluate(()=>{const c=window.__courtyard;c.setView('aerial',true);const p=c.school.fish[0].group.position.clone().set(-.7,.65,.85).project(c.camera),r=c.canvas.getBoundingClientRect();return {x:r.left+(p.x+1)*r.width/2,y:r.top+(1-p.y)*r.height/2};});await page.mouse.click(pick.x,pick.y);
 check('点击模型水位平面准确标记投喂点',await page.evaluate(()=>Math.abs(window.__courtyard.binding.draft.feedPoint.x+.7)<.02&&Math.abs(window.__courtyard.binding.draft.feedPoint.z-.85)<.02));
 await page.locator('#binding-apply').click();
 await page.locator('#exp-baseline').click();await page.locator('#exp-run-a').click();await page.waitForFunction(()=>window.__courtyard.experiment.results.baseline,null,{timeout:90000});await page.locator('#exp-run-b').click();await page.waitForFunction(()=>window.__courtyard.experiment.results.current,null,{timeout:90000});
 evidence.boundSame=await page.evaluate(()=>window.__courtyard.experiment.getState({includeImages:false}).difference);
 check('同一动态绑定模型上的 A/B 可重复',evidence.boundSame.sameTrajectory&&evidence.boundSame.meanPosition===0);
 await page.locator('[data-setting="modelScale"]').evaluate(e=>e.value='1.2');await page.locator('[data-setting="modelScale"]').dispatchEvent('input');
 check('模型倍率变化使绑定和旧基线失效',await page.evaluate(()=>!window.__courtyard.hasDynamics&&!window.__courtyard.experiment.baseline&&window.__courtyard.binding.draft.polygon.length===0));
 await page.locator('#binding-file').setInputFiles({name:'old-scale.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(binding))});await page.waitForFunction(()=>document.querySelector('#scene-toast').textContent.includes('倍率'));
 check('拒绝不匹配倍率的旧绑定',await page.evaluate(()=>!window.__courtyard.hasDynamics));
 await page.locator('#clear-model').click();await page.locator('#exp-reset').click();
 check('返回庭院恢复水面鱼群与默认实验参数',await page.evaluate(()=>window.__courtyard.root.visible&&window.__courtyard.hasDynamics&&!window.__courtyard.school.habitat&&window.__courtyard.experiment.parameters.cohesion===.22));
 await page.setViewportSize({width:390,height:844});await page.evaluate(()=>window.__courtyard.resize());
 check('手机宽度实验与绑定无横向溢出',await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth));
 await page.locator('#algorithm-experiments').screenshot({path:root+'assets/experiment-mobile-v6.png',timeout:90000});
 await page.locator('[data-tab="tech"]').click();
 check('技术页保留七主题映射和新增实验实景流程',await page.evaluate(()=>document.querySelectorAll('.effect-map tbody tr').length===7&&document.querySelector('#tech').textContent.includes('动态层')&&document.querySelector('#tech').textContent.includes('固定 1/60')));
 check('浏览器脚本与着色器无错误',errors.length===0);
 check('运行资源请求全部本地',requests.every(u=>u.startsWith('http://127.0.0.1:8947/')||u.startsWith('blob:')||u.startsWith('data:')));
}catch(e){fatal=e.stack||e.message;console.error(fatal);}
finally{
 const sha=createHash('sha256').update(await readFile(root+'web/app.js')).digest('hex');
 await writeFile(root+'notes/v6-browser-validation.json',JSON.stringify({clientDate:'2026-10-02',timeZone:'Asia/Shanghai',bundleSha256:sha,checks,errors,fatal,evidence,method:'Real Chromium with SwiftShader; UI controls and actual pointer marking. Fixed-step simulation advances behavior, full composer rendering captures canvas images. No hardware FPS or scan/photorealism claim.'},null,2));await browser.close();
}
console.log(JSON.stringify({passed:checks.length,errors,fatal}));assert.ok(!fatal&&errors.length===0,'v6 validation failed');
