import {useWorldArt} from './worlds-art.js?v=4';
const ECO_W=960,ECO_H=600;
const SEASONS=[{name:'春融',rain:2,evap:1},{name:'旱夏',rain:0,evap:3},{name:'秋汛',rain:3,evap:1}];
const PLOTS=[{id:'plot-upland',name:'北侧林缘',x:398,y:248,water:3,wet:false},{id:'plot-marsh',name:'浅湾湿地',x:657,y:267,water:5,wet:true},{id:'plot-slope',name:'西南旱坡',x:345,y:413,water:2,wet:false},{id:'plot-shore',name:'南侧滨岸',x:605,y:426,water:4,wet:true}];
const PLANTS={bare:'保留裸地',reed:'芦苇湿地',flowers:'野花草甸',wood:'混交林苗'};
const GATES={hold:{name:'截留',delta:2},balanced:{name:'均衡',delta:0},drain:{name:'排流',delta:-2}};
const clamp=(v,a,b)=>Math.max(a,Math.min(b,v)),clone=v=>JSON.parse(JSON.stringify(v)),rand=n=>{const v=Math.sin(n*91.13+43.91)*19419.18;return v-Math.floor(v)};

export function createEcologyGame({mount,saved,onEvent=()=>{}}){
 const canvas=document.createElement('canvas');canvas.width=ECO_W;canvas.height=ECO_H;canvas.tabIndex=0;canvas.style.cssText='width:100%;height:100%;display:block;touch-action:manipulation';canvas.setAttribute('aria-label','小小生态岛：调查地块，选择植被，调整水闸，观察三季演替');mount.append(canvas);const ctx=canvas.getContext('2d'),art=useWorldArt(ctx,'ecology');
 const initial={version:1,game:'ecology',year:1,season:0,gate:'balanced',labor:3,seeds:{reed:2,flowers:2,wood:2},patches:PLOTS.map(p=>({...p,plant:'bare',age:0,health:3})),selected:'plot-upland',research:'mosaic',annualReports:[],avatar:{x:236,y:330,heading:0},work:null,observations:[],history:[],journal:['第1年：四块地有不同水位。植被需要经过季节演替，物种不会因点击立即出现。'],message:'先调查林缘、湿地或旱坡。每季只有3点劳动，苗木也有限；选择不同布局，看看后果。',complete:false,checkpoint:null,time:0};
 let s=saved?.game==='ecology'?{...initial,...clone(saved),seeds:{...initial.seeds,...saved.seeds},avatar:{...initial.avatar,...saved.avatar},patches:PLOTS.map(p=>({...p,...saved.patches?.find(q=>q.id===p.id)}))}:initial;let pending=null,stride=0,bump=0,disposed=false;const emit=t=>{try{onEvent(t)}catch{}},log=t=>{s.journal.push(t);s.journal=s.journal.slice(-24)},say=t=>{s.message=t};
 const selected=()=>s.patches.find(p=>p.id===s.selected)||s.patches[0];
 const researchGoals={mosaic:{name:'让三种生境共存',test:()=>['reed','flowers','wood'].every(k=>s.patches.some(p=>p.plant===k&&p.health>0&&p.age>0))&&s.observations.length>=3},wetland:{name:'让泽蛙返回双湿地',test:()=>s.observations.some(o=>o.id==='frog')},canopy:{name:'让林栖鸟留在双林冠',test:()=>s.patches.filter(p=>p.plant==='wood'&&p.age>=2&&p.health>0&&p.water>=2&&p.water<=6).length>=2}};
 if(!researchGoals[s.research])s.research='mosaic';
 function researchResult(){return researchGoals[s.research].test()}
 function chapterSnapshot(){const {checkpoint,history,journal,time,...data}=s;return clone(data)}
 function busy(){if(s.work){say('调查员还在完成这次干预。等劳动结束后再作下一项决定。');emit('bump');return true}return false}
 function investigate(p){s.selected=p.id;say(p.name+'：水位 '+p.water+'/9，'+PLANTS[p.plant]+'，生长 '+p.age+' 季，健康 '+p.health+'/3。芦苇适合水位3–9；野花2–5；林苗2–6，树木第二季才形成林冠。');emit('soft')}
 function setWork(kind,data={}){if(busy())return false;if(s.complete&&kind!=='new-year'){say('这一年的观察已经完成。可以回退上一季修正，或继续新一年。');return false}if(s.labor<1){say('这一季的劳动已经用完。推进季节补充劳动，或回退上一季重新布局。');emit('bump');return false}if(!s.checkpoint||s.checkpoint.season!==s.season)s.checkpoint=chapterSnapshot();s.labor--;s.work={kind,...data,remaining:1.15,phase:'walk'};say(kind==='plant'?'调查员带着苗木走向'+selected().name+'。苗木和劳动已计入支出，物种要等演替后观察。':kind==='clear'?'调查员正在移除这一块植被。苗木不会退回，腾出的裸地可以重新选择。':'调查员正在调整水闸。新的水位影响将在季节结算时出现。');emit('soft');return true}
 function population(){const alive=s.patches.filter(p=>p.health>0&&p.age>0),wet=alive.filter(p=>p.plant==='reed'&&p.water>=3),flowers=alive.filter(p=>p.plant==='flowers'&&p.water>=2&&p.water<=5),woods=alive.filter(p=>p.plant==='wood'&&p.age>=2&&p.water>=2&&p.water<=6),out=[];if(wet.length)out.push({id:'dragonfly',name:'蜻蜓',count:wet.length*2,plot:wet[0].id});if(wet.length>=2)out.push({id:'frog',name:'泽蛙',count:wet.length,plot:wet.at(-1).id});if(flowers.length)out.push({id:'butterfly',name:'草甸蝶',count:flowers.length*3,plot:flowers[0].id});if(woods.length)out.push({id:'bird',name:'林栖鸟',count:woods.length,plot:woods[0].id});if(wet.length&&flowers.length&&woods.length)out.push({id:'heron',name:'涉禽',count:1,plot:wet[0].id});return out}
 function forecastPatches(patches,season,delta){
 const canopy=patches.filter(p=>p.plant==='wood'&&p.age>=2&&p.health>0);
 return patches.map(p=>{const shade=canopy.some(q=>q.id!==p.id&&Math.hypot(q.x-p.x,q.y-p.y)<225)?1:0;
  const water=clamp(p.water+season.rain-season.evap+delta+(p.wet?1:0)+shade,0,9);
  const good=p.plant==='bare'||(p.plant==='reed'?water>=3:p.plant==='flowers'?water>=2&&water<=5:water>=2&&water<=6);
  return {...p,before:p.water,oldHealth:p.health,water,age:p.age+(p.plant==='bare'?0:1),health:clamp(p.health+(good?0:-2),0,3),reason:good?'适合当前植被':'水位超出适宜范围'};
 });
}
 function evolve(){const season=SEASONS[s.season],dead=[],records=[],preview=forecastPatches(s.patches,season,GATES[s.gate].delta);for(let i=0;i<s.patches.length;i++){const p=s.patches[i],next=preview[i];p.water=next.water;if(p.plant!=='bare'){p.age=next.age;p.health=next.health;if(p.health===0)dead.push(p.name);records.push(p.name+' '+PLANTS[p.plant]+' 水位'+p.water+' 健康'+p.health)}}s.observations=population();const summary='第'+s.year+'年 '+season.name+'：'+(s.observations.length?s.observations.map(o=>o.name).join('、'):'尚未出现稳定栖息者')+(dead.length?'；'+dead.join('、')+'植被失活':'');s.history.push({year:s.year,season:season.name,gate:s.gate,patches:clone(s.patches),species:clone(s.observations),summary});s.history=s.history.slice(-12);log(summary);log('水位规则：旧水位 + 降雨'+season.rain+' − 蒸发'+season.evap+' + 水闸'+GATES[s.gate].delta+'；滨岸/浅湾另+1，邻近成熟林冠另+1。');s.season++;s.labor=3;s.complete=s.season>=3;if(s.complete){const r={year:s.year,research:s.research,success:researchResult(),species:s.observations.map(o=>o.name),alive:s.patches.filter(p=>p.plant!=='bare'&&p.health>0).length};s.annualReports=[...(s.annualReports||[]).filter(a=>a.year!==s.year),r].slice(-12);log('年度课题 · '+researchGoals[s.research].name+'：'+(r.success?'已达成':'尚未达成')+'；存活地块 '+r.alive+'/4。');}s.work=null;pending=null;if(s.complete)say(summary+'。三季记录完成。查看手账比较布局；可回退上一季，或沿着现有植被继续新一年。');else say(summary+'。下一季是'+SEASONS[s.season].name+'，劳动恢复3点。可以调整布局与水闸后再推进。');emit('success')}
 function finishWork(){const w=s.work;if(!w)return;const p=s.patches.find(p=>p.id===w.plot);if(w.kind==='advance'){evolve();return}if(w.kind==='plant'){p.plant=w.plant;p.age=0;p.health=3;log(p.name+'栽下'+PLANTS[w.plant]+'：'+w.plant+'苗−1，劳动−1。');say('苗木已经落在'+p.name+'。它还不是成熟栖息地；推进季节后观察水位、生长与物种。')}if(w.kind==='clear'){p.plant='bare';p.age=0;p.health=3;log(p.name+'移除植被，劳动−1。');say(p.name+'重新留出裸地。已有生境消失，需要新的布局慢慢恢复。')}if(w.kind==='gate'){s.gate=w.gate;log('水闸调为'+GATES[w.gate].name+'，劳动−1；下一季水位变化'+(GATES[w.gate].delta>=0?'+':'')+GATES[w.gate].delta+'。');say('水闸已调为'+GATES[w.gate].name+'。河道流速已经改变，水位与物种将在下一季响应。')}s.work=null;emit('soft')}
 function command(id){if(disposed)return false;if(id.startsWith('research-')){const key=id.slice(9);if(!researchGoals[key]||s.work||s.season!==0||s.checkpoint)return false;s.research=key;say('今年的观察课题：'+researchGoals[key].name+'。它将按季末实际生境评估；开始劳动后不可更换。');return true;}if(s.work&&id!=='field-ledger')return !busy();if(id.startsWith('plot-')){const p=s.patches.find(p=>p.id===id);if(!p)return false;pending={id,x:p.x,y:p.y};say('走近'+p.name+'，记录土壤与水位……');return true}if(id==='water-gate'){pending={id,x:250,y:200};say('走到水闸旁，观察截留、均衡和排流三种选择。');return true}if(id==='field-ledger'){say(s.history.length?s.history.slice(-3).map(x=>x.summary).join(' / '):'手账还没有季末记录。先完成干预，再推进季节；不同植被需要不同水位。');return true}if(id==='rewind-season'){if(!s.checkpoint){say('还没有可以回退的季初。');return false}const history=clone(s.history),journal=[...s.journal],time=s.time,restore=clone(s.checkpoint);s={...s,...restore,history,journal,time,work:null,checkpoint:null,complete:false};log('回到上一季的干预起点，保留旧观察记录用于比较。');say('回到上一季的起点。水位、苗木和劳动都恢复；手账保留之前的结果，方便调整后对照。');pending=null;emit('soft');return true}if(id==='new-year'){if(!s.complete)return false;s.year++;s.season=0;s.complete=false;s.checkpoint=null;s.labor=3;for(const k of Object.keys(s.seeds))s.seeds[k]+=2;for(const p of s.patches)if(p.health===0){p.plant='bare';p.age=0;p.health=3}s.work=null;log('第'+s.year+'年开始：保留存活植被，补充各2份苗木。');say('存活的林冠与湿地留下来了。新一年各补2份苗木，看看后续演替，或修复失活地块。');emit('soft');return true}if(id==='advance-season'||id==='season-calendar'){if(s.complete)return false;if(!s.checkpoint)s.checkpoint=chapterSnapshot();s.work={kind:'advance',remaining:1.2,phase:'observe'};say('一季过去，调查员正在核对水位与栖息记录……');return true}if(id.startsWith('gate-')){const gate=id.slice(5);if(!GATES[gate])return false;if(s.gate===gate){say('水闸已经是'+GATES[gate].name+'，无需再花劳动。');return true}return setWork('gate',{gate,x:250,y:200})}if(id==='clear-plot')return setWork('clear',{plot:selected().id,x:selected().x,y:selected().y});if(id.startsWith('plant-')){const plant=id.slice(6);if(!['reed','flowers','wood'].includes(plant))return false;if(s.seeds[plant]<1){say('这一种苗木已用完。调整其他地块，或在新一年补充苗木。');emit('bump');return false}if(setWork('plant',{plant,plot:selected().id,x:selected().x,y:selected().y})){s.seeds[plant]--;return true}return false}if(id==='interact'){const p=s.patches.reduce((a,b)=>Math.hypot(a.x-s.avatar.x,a.y-s.avatar.y)<Math.hypot(b.x-s.avatar.x,b.y-s.avatar.y)?a:b);if(Math.hypot(p.x-s.avatar.x,p.y-s.avatar.y)<60)investigate(p);else say('走近一块地，或直接点击调查标记。');return true}return false}
 function moveTo(x,y,dt){const a=s.avatar,dx=x-a.x,dy=y-a.y,d=Math.hypot(dx,dy),v=125*dt;if(d<=v){a.x=x;a.y=y;return true}a.x+=dx/d*v;a.y+=dy/d*v;a.heading=Math.atan2(dx,dy);stride+=dt*8;return false}
 function tick(dt,input={}){if(disposed)return;dt=clamp(+dt||0,0,.1);s.time+=dt;bump=Math.max(0,bump-dt);if(s.work){const w=s.work;if(w.phase==='walk'){if(moveTo(w.x,w.y,dt))w.phase='tend'}else{w.remaining-=dt;if(w.remaining<=0)finishWork()}}else if(pending){if(moveTo(pending.x,pending.y,dt)){if(pending.id==='water-gate')say('水闸当前'+GATES[s.gate].name+'。截留每季+2水位，排流−2，均衡0。修改消耗1劳动。');else if(pending.id!=='walk')investigate(s.patches.find(p=>p.id===pending.id));pending=null}}else if(input.x||input.y){const d=Math.hypot(input.x||0,input.y||0);s.avatar.x=clamp(s.avatar.x+(input.x||0)/d*120*dt,200,770);s.avatar.y=clamp(s.avatar.y+(input.y||0)/d*120*dt,180,490);s.avatar.heading=Math.atan2(input.x,input.y);stride+=dt*8}if(input.pressed?.has('KeyE')||input.pressed?.has('e'))command('interact')}
 function getUI(){const p=selected(),next=SEASONS[Math.min(s.season,2)],off=!!s.work||s.complete;return {patchForecast:s.complete?s.patches.map(p=>({...p,before:p.water,oldHealth:p.health,reason:'季末记录'})):forecastPatches(s.patches,next,GATES[s.gate].delta),title:'小小生态岛 · 第'+s.year+'年自然观察',goal:s.complete?'年度课题 · '+researchGoals[s.research].name+'：'+(researchResult()?'已达成':'尚未达成')+'。保留布局继续观察，或回退做对照。':'课题 · '+researchGoals[s.research].name+' / 第'+(s.season+1)+'季 '+next.name+'：降雨+'+next.rain+'、蒸发−'+next.evap+'；让植被布局与水位相互适应',message:s.message,progress:'三季观察 '+Math.min(s.season,3)+'/3 · 劳动 '+s.labor+'/3 · 水闸 '+GATES[s.gate].name,actions:[...Object.entries(researchGoals).map(([k,g])=>({id:'research-'+k,label:(s.research===k?'✓ ':'')+g.name,disabled:!!s.work||s.season!==0||!!s.checkpoint})),...['reed','flowers','wood'].map(k=>({id:'plant-'+k,label:p.name+'栽'+PLANTS[k]+'（苗1 / 劳动1）',disabled:off||s.seeds[k]<1||s.labor<1})),{id:'clear-plot',label:'移除所选植被（劳动1）',disabled:off||p.plant==='bare'||s.labor<1},...Object.keys(GATES).map(k=>({id:'gate-'+k,label:'水闸 '+GATES[k].name+'（水位'+(GATES[k].delta>=0?'+':'')+GATES[k].delta+' / 劳动1）',disabled:off||s.gate===k||s.labor<1})),{id:'advance-season',label:'推进'+next.name+' · 核对生态后果',disabled:off,primary:true},{id:'rewind-season',label:'回退上一季 · 保留对照记录',disabled:!!s.work||!s.checkpoint},{id:'new-year',label:'保留布局，开始新一年',disabled:!s.complete,primary:s.complete},{id:'field-ledger',label:'查看季末观察手账'}],inventory:['年度课题：'+researchGoals[s.research].name+' / '+(researchResult()?'当前已达成':'仍在观察'),'芦苇苗 '+s.seeds.reed,'野花苗 '+s.seeds.flowers,'林苗 '+s.seeds.wood,'所选 '+p.name+'：水位 '+p.water+'/9，健康 '+p.health+'/3',...s.observations.map(o=>o.name+' '+o.count+' 处活动')],journal:[...(s.annualReports||[]).map(r=>'第'+r.year+'年课题 · '+researchGoals[r.research].name+'：'+(r.success?'达成':'未达成')+' / '+r.species.join('、')),...s.journal],complete:s.complete,controls:'点地块调查 · 点苗木或操作按钮干预 · 点日历推进季节 · 水位范围为本岛观察模型的规则'} }
 const targets=()=>[...s.patches.map(p=>({id:p.id,x:p.x,y:p.y})),{id:'water-gate',x:250,y:200},{id:'season-calendar',x:855,y:96},{id:'field-ledger',x:855,y:502},{id:'plant-reed',x:228,y:554},{id:'plant-flowers',x:410,y:554},{id:'plant-wood',x:592,y:554}];
 function pointer(e){const r=canvas.getBoundingClientRect(),x=(e.clientX-r.left)/r.width*ECO_W,y=(e.clientY-r.top)/r.height*ECO_H,t=targets().filter(t=>Math.hypot(t.x-x,t.y-y)<Math.max(44,22*ECO_W/r.width)).sort((a,b)=>Math.hypot(a.x-x,a.y-y)-Math.hypot(b.x-x,b.y-y))[0];if(t)command(t.id);else if(x>195&&x<790&&y>170&&y<500)pending={id:'walk',x,y}}
 canvas.addEventListener('pointerup',pointer);
 function ellipse(x,y,rx,ry,col){ctx.fillStyle=col;ctx.beginPath();ctx.ellipse(x,y,rx,ry,0,0,Math.PI*2);ctx.fill()}
 function stroke(points,col,width=1){ctx.beginPath();points.forEach((p,i)=>i?ctx.lineTo(...p):ctx.moveTo(...p));ctx.strokeStyle=col;ctx.lineWidth=width;ctx.lineCap='round';ctx.lineJoin='round';ctx.stroke()}
 function text(str,x,y,size=12,col='#4c5e50',font='sans-serif'){ctx.fillStyle=col;ctx.font=size+'px '+font;ctx.fillText(str,x,y)}
 function reed(p){const stage=p.health===0?2:p.age?1:0;if(art.sprite('reed-'+stage,p.x+Math.sin(s.time*1.1)*.6,p.y+12,p.age?68:39))return;const healthy=p.health>0,col=healthy?'#668f6b':'#968667';for(let i=0;i<17;i++){const x=p.x+(rand(i+p.x)*2-1)*43,y=p.y+(rand(i+55+p.y)*2-1)*25,h=14+Math.min(p.age,3)*8+rand(i)*17,sway=Math.sin(s.time*1.7+i)*3;stroke([[x,y],[x+sway,y-h]],col,1.8);stroke([[x,y-8],[x-9,y-21],[x-14,y-25]],col,1);stroke([[x,y-11],[x+9,y-25]],col,1);ellipse(x+sway,y-h-3,2.2,6,healthy?'#a28b65':'#87775f')}}
 function flower(p){const stage=p.health===0?2:p.age?1:0;if(art.sprite('flowers-'+stage,p.x+Math.sin(s.time*1.1)*.6,p.y+12,p.age?52:29))return;const alive=p.health>0;for(let i=0;i<20;i++){const x=p.x+(rand(i+p.x+17)*2-1)*49,y=p.y+(rand(i+p.y+113)*2-1)*29,h=8+Math.min(p.age,2)*5;stroke([[x,y],[x+Math.sin(s.time+i)*1.2,y-h]],alive?'#789875':'#95836c',1);for(let a=0;a<5;a++)ellipse(x+Math.cos(a*1.256)*3,y-h+Math.sin(a*1.256)*3,2,2,alive?['#c8a693','#d6c79b','#b6a4bd'][i%3]:'#a39685');ellipse(x,y-h,1.5,1.5,'#877c55')}}
 function tree(p){const stage=p.health===0?2:p.age?1:0;if(art.sprite('wood-'+stage,p.x+Math.sin(s.time*1.1)*.6,p.y+12,p.age?Math.min(108,57+p.age*13):42))return;for(let i=0;i<5;i++){const x=p.x+(rand(i+p.x+23)*2-1)*38,y=p.y+(rand(i+p.y+313)*2-1)*23,age=Math.min(p.age,4),h=15+age*10;stroke([[x,y],[x-1,y-h]],'#83735e',2.4);if(p.health>0){ellipse(x,y-h+7,8+age*4,9+age*3,['#78937a','#90a07b','#6f8b77'][i%3]);ellipse(x-5,y-h+1,8+age*3,9+age*3,'#8da18a');ellipse(x+8,y-h+8,7+age*3,8+age*3,'#93a686')}else{stroke([[x,y-h*.6],[x-9,y-h*.9]],'#8e8170',1.5);stroke([[x,y-h*.7],[x+8,y-h]],'#8e8170',1.5)}}}
 function organism(o,i){const p=s.patches.find(p=>p.id===o.plot),t=s.time,a=i*2.4+t*(o.id==='bird'?.35:.55),x=p.x+Math.cos(a)*35,y=p.y+Math.sin(a*.8)*23;if(o.id==='frog'){ellipse(x,y,5.2,3.3,'#536e54');ellipse(x-4,y+3,3,1.6,'#708769');ellipse(x+4,y+3,3,1.6,'#708769')}else if(o.id==='heron'){stroke([[x,y+12],[x+2,y-7],[x+6,y-13]],'#686e65',2.4);ellipse(x,y,7,3,'#d3d8cd');stroke([[x,y+4],[x-2,y+18],[x,y+20]],'#8b8170',1);stroke([[x+6,y-13],[x+15,y-13]],'#aa936c',1.3)}else if(o.id==='butterfly'){const flap=Math.abs(Math.sin(t*8+i));ellipse(x-3,y,4*flap+1,3,'#bda978');ellipse(x+3,y,4*flap+1,3,'#c8b384');stroke([[x,y-3],[x,y+4]],'#817665',.8)}else if(o.id==='dragonfly'){stroke([[x-7,y-2],[x+7,y+2]],'#899ead',1);stroke([[x-6,y+3],[x+6,y-3]],'#899ead',1);stroke([[x,y-4],[x,y+5]],'#687d77',1)}else{stroke([[x-8,y],[x,y-4-Math.sin(t*5+i)*2],[x+8,y]],'#687d73',1.8)}}
 function draw(){if(disposed)return;ctx.clearRect(0,0,ECO_W,ECO_H);if(!art.background('ecology-terrain')){ctx.fillStyle='#e9e8dd';ctx.fillRect(0,0,ECO_W,ECO_H);for(let i=0;i<400;i++){ctx.fillStyle=i%2?'#69786608':'#ffffff35';ctx.fillRect(rand(i)*960,rand(i+332)*600,1,1)}ctx.fillStyle='#f4f1e8';ctx.fillRect(24,22,912,556);ctx.strokeStyle='#b8bfb0';ctx.lineWidth=1;ctx.strokeRect(24.5,22.5,911,555);text('FIELD STATION  /  ECOLOGICAL SUCCESSION',48,52,11,'#788779','monospace');text('小小生态岛',48,88,27,'#485d50','Georgia');text('第'+s.year+'年 · '+(s.complete?'三季记录完成':SEASONS[s.season].name)+'  /  当前水闸：'+GATES[s.gate].name,48,112,12);text('劳动 '+s.labor+' / 3',50,164,13);text('水位 0–9',50,189,11,'#7c8776');text('植被需经过季节',50,209,10,'#7c8776');text('才能形成栖息地',50,226,10,'#7c8776');
  // Organic contour map and meandering water, rather than a regular garden grid.
  ctx.beginPath();ctx.moveTo(240,170);ctx.bezierCurveTo(378,106,575,150,708,176);ctx.bezierCurveTo(842,226,824,362,733,452);ctx.bezierCurveTo(634,525,421,505,271,466);ctx.bezierCurveTo(161,429,181,252,240,170);ctx.closePath();ctx.fillStyle='#ccd3b7';ctx.fill();ctx.strokeStyle='#96a991';ctx.stroke();for(let i=0;i<4;i++){ctx.beginPath();ctx.ellipse(472,325,238-i*28,155-i*21,-.07,0,Math.PI*2);ctx.strokeStyle='#8e9e821b';ctx.stroke()}for(let i=0;i<160;i++){const x=246+rand(i+903)*493,y=178+rand(i+834)*280;stroke([[x,y],[x-1,y-3]],'#899d8030',.8)}
}else{ctx.fillStyle='#f4f4e8dd';ctx.fillRect(24,22,912,104);text('小小生态岛',45,60,25,'#385840','Georgia');text('第'+s.year+'年 · '+(s.complete?'三季记录完成':SEASONS[s.season].name)+'  /  水闸 '+GATES[s.gate].name,47,88,12);text('劳动 '+s.labor+' / 3 · 每次干预影响下一季',47,111,11,'#617b60');}  ctx.beginPath();ctx.moveTo(298,162);ctx.bezierCurveTo(413,169,483,222,564,258);ctx.bezierCurveTo(700,317,691,369,703,480);ctx.strokeStyle='#91ada8';ctx.lineWidth=s.gate==='drain'?23:s.gate==='hold'?12:17;ctx.stroke();ctx.beginPath();ctx.moveTo(303,164);ctx.bezierCurveTo(409,182,472,224,564,258);ctx.bezierCurveTo(682,307,689,368,703,474);ctx.strokeStyle='#dce6d7';ctx.lineWidth=2;ctx.setLineDash([9,13]);ctx.lineDashOffset=-s.time*(s.gate==='drain'?12:s.gate==='hold'?2:6);ctx.stroke();ctx.setLineDash([]);
  for(const p of s.patches){const wet=p.water>5;ellipse(p.x,p.y+8,58+Math.max(0,p.water-4)*3,34,wet?'#9db7b087':'#b6bea287');if(p.water>=8)ellipse(p.x,p.y+9,64,38,'#89aaa485');if(p.plant==='reed')reed(p);if(p.plant==='flowers')flower(p);if(p.plant==='wood')tree(p);if(p.plant==='bare'){for(let i=0;i<12;i++)stroke([[p.x+(rand(i+p.x)*2-1)*35,p.y+rand(i+p.y)*12],[p.x+(rand(i+p.x)*2-1)*35-2,p.y+rand(i+p.y)*12-4]],'#96a37b',1)}ctx.strokeStyle=p.id===s.selected?'#5e7b62':'#8da18a55';ctx.lineWidth=p.id===s.selected?1.8:1;ctx.setLineDash([4,5]);ctx.beginPath();ctx.ellipse(p.x,p.y+4,67,44,0,0,Math.PI*2);ctx.stroke();ctx.setLineDash([]);ctx.fillStyle='#edf0e1e8';ctx.beginPath();ctx.roundRect(p.x-57,p.y+49,114,36,4);ctx.fill();text(p.name,p.x-38,p.y+62,12,'#365441');text('水'+p.water+' · '+PLANTS[p.plant],p.x-44,p.y+78,10,'#526a55');if(p.health===0)text('失活',p.x+18,p.y-25,12,'#9c6d58')}
  for(const o of s.observations)for(let i=0;i<Math.min(o.count,5);i++)organism(o,i);ctx.fillStyle='#7f8a70';ctx.fillRect(232,177,35,42);ctx.fillStyle='#c8c8b3';ctx.fillRect(236,178,29,36);stroke([[226,211],[272,190]],'#78846e',3);text('水闸',232,159,11);text(GATES[s.gate].name,222,239,11);const a=s.avatar,bob=s.work&&s.work.phase==='tend'?Math.sin(s.time*5)*1.8:Math.sin(stride)*1.2;if(art.ready('ecologist')){art.shadow(a.x,a.y,9,.2);art.sprite('ecologist',a.x,a.y,59,{bob})}else{ellipse(a.x,a.y+3,7,3,'#65776124');ctx.fillStyle='#4b5b50';ctx.fillRect(a.x-4,a.y-13,3,15);ctx.fillRect(a.x+1,a.y-13,3,15);ctx.fillStyle='#849181';ctx.fillRect(a.x-6,a.y-29+bob,12,18);ellipse(a.x,a.y-35+bob,4.7,5.4,'#b9a78e');ctx.fillStyle='#5f6a5e';ctx.fillRect(a.x-6,a.y-40+bob,12,3);stroke([[a.x+5,a.y-23+bob],[a.x+10,a.y-18+bob]],'#849181',3);ctx.fillStyle='#d5c9a4';ctx.fillRect(a.x+7,a.y-21+bob,6,8);}if(s.work){text(s.work.kind==='advance'?'季节演替中':'现场干预中',a.x-28,a.y-53,10,'#4e6953')}
  ctx.fillStyle='#e5e0cc';ctx.fillRect(813,61,93,65);ctx.strokeStyle='#aab39f';ctx.strokeRect(813.5,61.5,92,64);text(s.complete?'年度完成':'推进季节',826,85,12);text(s.complete?'看手账':SEASONS[s.season].name,826,108,15,'#5e755d','Georgia');ctx.fillStyle='#e2dec9';ctx.fillRect(806,446,108,81);ctx.strokeStyle='#b6bba5';ctx.strokeRect(806.5,446.5,107,80);text('观察手账',818,468,12);text(s.observations.length+' 类栖息活动',818,490,10);text(s.history.length+' 季记录',818,510,10);for(let i=0;i<3;i++){ctx.fillStyle=['#d9dfc9','#ece0c4','#d0d9c9'][i];ctx.fillRect(146+i*182,534,164,37);text(['芦苇苗  '+s.seeds.reed,'野花苗  '+s.seeds.flowers,'林苗  '+s.seeds.wood][i],164+i*182,557,12)}text('苗木 ×1  +  劳动 ×1；种下后需推进季节',729,557,9,'#7f8773');
 }
 draw();return {element:canvas,tick,draw,command,getUI,getState:()=>clone(s),getTargets:()=>targets(),dispose(){disposed=true;canvas.removeEventListener('pointerup',pointer);canvas.remove()}};
}
