import {ISLAND_AREAS,currentTargets,canWalk,pathTo} from './islands-world.js';
import {createIslandArt} from './islands-art.js?v=6';

export function createIslandsGame({mount,saved,onEvent=()=>{}}){
 const initial={version:1,game:'islands',area:'camp',player:{x:.1,z:1.7,heading:0},tools:[],discoveries:[],bridgeOpen:false,sealOpen:false,reported:false,herb:false,towerStarted:false,wind:0,star:0,windAligned:false,starAligned:false,beaconLit:false,towerReported:false,journal:['风帆湾的旧航图缺了一块。队长请你寻找遗迹上的两种线索。'],message:'营地工具箱和灯架都能调查。先去哪一边，由你决定。'};
 const s={...initial,...(saved?.game==='islands'?saved:{}),player:{...initial.player,...saved?.player},tools:Array.isArray(saved?.tools)?saved.tools.filter(x=>['rope','lantern'].includes(x)):[],discoveries:Array.isArray(saved?.discoveries)?saved.discoveries.filter(x=>['crystal','rubbing'].includes(x)):[],journal:Array.isArray(saved?.journal)?saved.journal.slice(-20):initial.journal};if(!ISLAND_AREAS[s.area])s.area='camp';if(!canWalk(s,s.player.x,s.player.z))Object.assign(s.player,ISLAND_AREAS[s.area].spawn);
 if(s.reported&&!s.towerStarted&&s.message.includes('尚未开放'))s.message='航图已定位云塔。第二章的航路开放了：前往云塔岛，调查熄灭的归航灯。';
 if(s.area==='tower'&&s.beaconLit&&s.message.includes('塔基失去了光'))s.message='你回到亮灯的云塔。桥与星环仍保留，归航灯继续为远行的人指路。';
 let route=[],pending=null,time=0,walking=false,stride=0,transition=0,disposed=false,bumpAge=0,pulse=0;const event=t=>{try{onEvent(t)}catch{}},say=t=>{s.message=t},log=t=>{if(!s.journal.includes(t))s.journal.push(t);s.journal=s.journal.slice(-20)};
 const art=createIslandArt({mount,state:s,onPoint:(x,z,id)=>walkTo(x,z,id)});
 function enter(area){s.area=area;Object.assign(s.player,ISLAND_AREAS[area].spawn);route=[];pending=null;transition=1;art.setArea();event('success');say(area==='tower'&&s.beaconLit?'风帆回到亮灯的云塔。你接通的桥与校准的星环还在，归航灯继续为远行的人指路。':area==='tower'?'你抵达真正的云塔岛。塔基失去了光；左侧风向台能接通右岸，旧星纹是校准星环的线索。':area==='ruins'?'风帆穿过云隙，真正抵达回声拱门。左边风晶在鸣响；右边的旧桥被封印挡住。':'回到风帆湾。营地地图和陈列台等着你的新发现。');log(area==='tower'?(s.beaconLit?'重访云塔：接通的桥与亮起的归航灯依然保留。':'第二章 · 风帆抵达云塔岛，调查失明的归航灯。'):area==='ruins'?'亲手架好绳桥，航路抵达回声拱门。':'带着遗迹发现返回风帆湾。')}
 function action(id){const t=currentTargets(s).find(t=>t.id===id);if(!t)return false;if(Math.hypot(s.player.x-t.x,s.player.z-t.z)>1.05){say('这里还隔着一段路。先走近，再调查。');event('bump');return false}pulse=1;switch(id){
  case 'camp-tower':if(!s.reported){say('先把遗迹里的两份发现归档，航图才能定位云塔。');event('bump');break;}s.towerStarted=true;enter('tower');break;
  case 'tower-note':log('守灯人留言：风晶指向东，星纹的三角朝上。风向接通桥，星环点亮灯。');say('“风晶指向东；星纹上方是三角。没有归航灯时，远行的人只能等。请替我把它重新点亮。”');break;
  case 'tower-wind':if(s.windAligned){say('风向台已锁在东向，新桥稳稳接到了右侧星环。');break;}s.wind=(s.wind+1)%3;if(s.wind===1){s.windAligned=true;log('以风晶校准东向：云塔右侧绳桥真正接通。');say('东向与风晶共鸣。右侧桥板落稳，星环平台已经能走过去。');art.refresh();event('success');}else{say('风向台现在指向'+['北','东','南'][s.wind]+'。看看守灯人的留言，再旋转校准。');art.refresh();}break;
  case 'tower-star':if(s.starAligned){say('三角已经朝上。星环的光线连到了云塔。');break;}s.star=(s.star+1)%3;if(s.star===2){s.starAligned=true;log('旋转星环，让三角朝上；归航灯获得星光。');say('三角朝上，与旧拓片一致。星环的细光连向塔基，可以返回开灯了。');event('success');}else say('星环现在是'+['圆','方','三角'][s.star]+'朝上。你的拓片和守灯人的留言保留了校准线索。');art.refresh();break;
  case 'tower-beacon':if(!s.windAligned||!s.starAligned){say('塔基没有光。先校准左岸风向，再过桥旋转右岸星环。');event('bump');}else if(!s.beaconLit){s.beaconLit=true;log('归航灯亮起：云海中等待的风帆开始向营地返回。');say('你推上开关。塔顶的金色光束扫过云海，远处等候的风帆回应了一次灯闪。回营地告诉队长，这次你带回了一条能用的归路。');art.refresh();event('success');}else say(s.towerReported?'归航灯仍在转动。营地已经记下这条归路，远处的风帆正沿着灯光回家。':'归航灯仍在转动。回到营地，把新的航路记进图里。');break;
  case 'tower-return':enter('camp');break;
  case 'camp-rope':if(!s.tools.includes('rope')){s.tools.push('rope');log('取得结实的绳索：可以连接营地断桥。');say('工具箱里有一卷绳索。带到东边的锚柱，就能真正接通断桥。');event('success')}else say('绳索已在背包里，锚柱就在营地东边。');break;
  case 'camp-lantern':if(!s.tools.includes('lantern')){s.tools.push('lantern');log('取得探险灯：可照亮遗迹里的封印槽。');say('你取下了一盏探险灯。队长说：“古老的槽口，得用光去读。”');event('success')}else say('探险灯仍在背包上，遗迹封印需要它。');break;
  case 'camp-anchor':if(!s.tools.includes('rope')){say('断桥缺了一段绳索。西边工具箱里有修桥的材料。');event('bump')}else if(!s.bridgeOpen){s.bridgeOpen=true;log('用绳索架好断桥：东边航台成为真正可走的地方。');say('绳索系紧，木板落稳。东侧的航台已经能走过去了。');art.refresh();event('success')}else say('你架好的桥还在。沿木板走到航台，可以再去遗迹。');break;
  case 'camp-depart':if(s.bridgeOpen)enter('ruins');else{say('航台还隔着空海。先用绳索接通断桥。');event('bump')}break;
  case 'camp-herb':if(!s.herb){s.herb=true;log('调查羽叶草，把第一份营地标本夹入册中。');say('羽叶草的叶脉像小小的羽毛。你夹下落叶，陈列台多了一份标本。');art.refresh();event('soft')}else say('这株羽叶草已经记录了。营地陈列台里可以看见它的叶片。');break;
  case 'camp-map':if(s.beaconLit&&!s.towerReported){s.towerReported=true;log('第二章归档：云塔归航灯重新亮起，两片浮岛有了夜间航路。');say('队长在航图上画下金色航线：“你找回来的不只是标本。今晚出发的人，知道怎么回家了。” 两章完成，归航灯与营地记录都保留。');art.refresh();event('success');}else if(s.towerReported)say('航图上的金色航线连接营地、遗迹和云塔。桥、星纹与归航灯已经归档；可以再乘风帆看看自己的成果。');else if(s.discoveries.length===2&&!s.reported){s.reported=true;log('将风晶与星纹归档：空白航图显现出下一座云塔。');say('队长把你的风晶和星纹并排放上航图：“它们指向同一座云塔！”第一章完成。航路已定位，现在可以接着前往云塔，调查熄灭的归航灯。');art.refresh();event('success')}else if(s.reported)say('航图保留了你的绳桥、遗迹和两项发现。云塔航路已经开放。带着风晶与星纹，去看看归航灯为什么失明。');else if(s.discoveries.length)say('航图已经标出你去过的遗迹。再带回另一种线索，就能判断下一站。');else say('队长指着空白航图：“回声拱门就在云隙后面。风晶和星纹，或许能拼出它的来历。”');break;
  case 'camp-shelf':say(s.discoveries.length||s.herb?'羽叶草、风晶和星纹会在这里保留。每件陈列都来自你亲手调查过的地方。':'陈列台还有空位。去调查营地的羽叶草，或者带回遗迹发现。');break;
  case 'ruins-return':enter('camp');break;
  case 'ruins-obelisk':log('石碑记载：守灯人用风晶校准航向，用星纹记录归路。');say('石碑写着：“风晶让来人知道方向，星纹让远行者记得归路。”两处线索可以按自己的顺序寻找。');event('soft');break;
  case 'ruins-lamp':if(!s.tools.includes('lantern')){say('槽口沉在黑暗里。营地的探险灯能读出它；风帆可以带你回去取。');event('bump')}else if(!s.sealOpen){s.sealOpen=true;log('探险灯照亮封印：星纹平台的石门真实打开。');say('灯光填满槽口，古老的石门缓缓升起。现在可以走上右侧星纹平台了。');art.refresh();event('success')}else say('你照亮的封印仍在。右侧星纹平台已经能通行。');break;
  case 'ruins-crystal':if(!s.discoveries.includes('crystal')){s.discoveries.push('crystal');log('在风鸣小岛记录风晶，带回一枚自然掉落的碎片。');say(s.discoveries.length===2?'风晶低鸣，与你拓下的星纹方向一致。两条线索凑齐了，回营地把它们放上航图。':'风晶在风里低鸣。你拾起自然落下的碎片；另一边的星纹也许能解释它。');art.refresh();event('success')}else say('风晶仍在鸣响，你已取走自然掉落的碎片。营地陈列保留了这次发现。');break;
  case 'ruins-rubbing':if(!s.discoveries.includes('rubbing')){s.discoveries.push('rubbing');log('在星纹平台拓下星盘，发现它指向一座未到访的云塔。');say(s.discoveries.length===2?'星纹与你记录的风晶方向重合。两条线索凑齐了，回营地把它们放上航图。':'你拓下星盘的纹路：一座云塔藏在线条交会处。风晶应该能校准它的方向。');art.refresh();event('success')}else say('这张星纹已经拓进册中。遗迹原石留在原处，营地航图保留了你的记录。');break;
 }return true}
 function walkTo(x,z,id=null){const target=id&&currentTargets(s).find(t=>t.id===id);if(id&&!target)return false;if(target&&Math.hypot(s.player.x-target.x,s.player.z-target.z)<=1.05)return action(id);const path=pathTo(s,target?.x??x,target?.z??z);if(id&&path.distance>1.04){say(id==='camp-depart'?'那边隔着空海，先用绳索接通断桥。':id==='ruins-rubbing'?'右侧平台被封印挡住，需要先用探险灯照亮槽口。':'暂时到不了那里，找找可以改变通路的工具。');event('bump');return false}route=path.points;pending=id;if(id)say('走近'+target.name+'……');else if(!route.length)say('脚下是空海。沿岛面与已经接通的桥走。');if(!route.length&&pending){const p=pending;pending=null;action(p)}return true}
 function command(id){if(typeof id==='object'&&id){if(id.type==='move')return walkTo(id.x,id.z??id.y);if(id.id)id=id.id}if(id==='interact'){const t=currentTargets(s).reduce((a,b)=>Math.hypot(s.player.x-a.x,s.player.z-a.z)<Math.hypot(s.player.x-b.x,s.player.z-b.z)?a:b);return action(t.id)}return walkTo(0,0,id)}
 function tick(dt,input={}){if(disposed)return;dt=Math.min(.1,Math.max(0,dt));time+=dt;bumpAge=Math.max(0,bumpAge-dt);pulse=Math.max(0,pulse-dt*1.3);transition=Math.max(0,transition-dt*.75);const dx=Number(input.x)||0,dz=Number(input.y)||0,p=s.player;walking=false;if(dx||dz){route=[];pending=null;const len=Math.hypot(dx,dz),v=2.7*dt,xx=p.x+dx/len*v,zz=p.z+dz/len*v;if(canWalk(s,xx,p.z)){walking||=Math.abs(xx-p.x)>.001;p.x=xx}if(canWalk(s,p.x,zz)){walking||=Math.abs(zz-p.z)>.001;p.z=zz}p.heading=Math.atan2(dx,dz);if(!walking&&bumpAge===0){say(s.area==='camp'&&!s.bridgeOpen?'岛边是空海。绳索能接通东边的桥。':'沿岛面和桥走，脚下的空海没有道路。');event('bump');bumpAge=1.5}}else if(route.length){const a=route[0],x=a.x-p.x,z=a.z-p.z,d=Math.hypot(x,z),v=2.7*dt;if(d<=v){p.x=a.x;p.z=a.z;route.shift()}else{p.x+=x/d*v;p.z+=z/d*v;p.heading=Math.atan2(x,z)}walking=true}if(walking)stride+=dt*9;if(!route.length&&pending){const id=pending;pending=null;action(id)}if(input.pressed?.has('KeyE')||input.pressed?.has('e')||input.pressed?.has('Enter'))command('interact');art.update({time,walking,stride,transition,pulse})}
 function getUI(){const hasRope=s.tools.includes('rope'),hasLamp=s.tools.includes('lantern');let goal;if(s.towerReported)goal='两章探险已归档；航图、标本与亮起的归航灯会保留';else if(s.area==='tower')goal=s.beaconLit?'归航灯已亮，乘风帆回营归档':!s.windAligned?'读守灯人留言，校准左侧风向台':!s.starAligned?'跨过新桥，依照星纹旋转右侧星环':'回到塔基，亲手点亮归航灯';else if(s.beaconLit)goal='把云塔点亮的归航灯记入营地航图';else if(s.reported)goal='第二章已开放：从航台前往云塔岛，修复归航灯';else if(s.discoveries.length===2)goal=s.area==='camp'?'把两项发现放上营地航图，完成第一章':'两条线索齐了，乘风帆回营地归档';else if(s.area==='camp')goal=!hasRope?'取得绳索，接通东边断桥；探险灯也值得带上':!s.bridgeOpen?'走到断桥锚柱，用绳索架桥':'沿新桥抵达航台，前往真正的遗迹岛';else goal='自由选择探索顺序：左侧风晶，右侧星纹；石碑记录它们的关系';const actions=s.area==='camp'?[{id:'camp-rope',label:hasRope?'查看绳索箱':'取得修桥绳索'},{id:'camp-lantern',label:hasLamp?'查看探险灯架':'取得探险灯'},{id:'camp-anchor',label:s.bridgeOpen?'查看绳桥':'用绳索架桥',primary:hasRope&&!s.bridgeOpen},{id:'camp-depart',label:'前往遗迹岛',disabled:!s.bridgeOpen,primary:s.bridgeOpen&&!s.reported},{id:'camp-map',label:s.beaconLit&&!s.towerReported?'归档云塔航路':s.discoveries.length===2&&!s.reported?'归档两条线索':'查看营地航图',primary:s.beaconLit&&!s.towerReported||s.discoveries.length===2&&!s.reported},{id:'camp-shelf',label:'查看留下的标本'},...(s.reported?[{id:'camp-tower',label:s.towerReported?'重访亮灯的云塔':s.towerStarted?'重访云塔岛':'继续第二章 · 云塔归航灯',primary:!s.towerStarted&&!s.towerReported}]:[])]:s.area==='tower'?[{id:'tower-note',label:'读守灯人的留言'},{id:'tower-wind',label:s.windAligned?'查看东向风标':'前往左岸，旋转风向台',primary:!s.windAligned},{id:'tower-star',label:s.starAligned?'查看对齐的星环':'前往右岸，旋转星环',disabled:!s.windAligned,primary:s.windAligned&&!s.starAligned},{id:'tower-beacon',label:s.beaconLit?'查看归航灯':'回塔基，点亮归航灯',disabled:!s.windAligned||!s.starAligned,primary:s.starAligned&&!s.beaconLit},{id:'tower-return',label:'乘风帆回营地',primary:s.beaconLit}]:[{id:'ruins-obelisk',label:'阅读守灯人的石碑'},{id:'ruins-crystal',label:s.discoveries.includes('crystal')?'再看风晶':'调查左侧风晶'},{id:'ruins-lamp',label:s.sealOpen?'查看照亮的封印':'用探险灯打开石门',primary:hasLamp&&!s.sealOpen},{id:'ruins-rubbing',label:s.discoveries.includes('rubbing')?'再看星盘':'拓下右侧星纹',disabled:!s.sealOpen},{id:'ruins-return',label:'乘风帆回营地',primary:s.discoveries.length===2}];return {title:'浮岛探险社 · '+ISLAND_AREAS[s.area].name,goal,message:s.message,progress:(s.towerStarted?'第二章 · '+(s.towerReported?'航路已归档':s.beaconLit?'归航灯已亮':s.starAligned?'星环已对齐':s.windAligned?'右岸桥已接通':'云塔待校准')+' / ':'第一章 · ')+'遗迹发现 '+s.discoveries.length+' / 2 · '+(s.reported?'已归档':s.bridgeOpen?'航路已接通':'航路待接通'),actions,inventory:[...s.tools.map(x=>x==='rope'?'修桥绳索':'探险灯'),...(s.herb?['羽叶草标本']:[]),...s.discoveries.map(x=>x==='crystal'?'风晶碎片':'星纹拓片')],journal:[...s.journal],complete:s.towerReported||(s.reported&&!s.towerStarted),controls:'点击岛面行走 · 点击物件走近调查 · WASD / 方向键 · E 调查身边物件'} }
 return {element:art.element,tick,draw(){if(!disposed)art.draw()},command,getUI,getState(){return JSON.parse(JSON.stringify(s))},getTargets(){return currentTargets(s).map(t=>({id:t.id,...art.project(t.x,t.z)}))},dispose(){disposed=true;art.dispose()}};
}
