import {getArtDirection,getArtClock} from '../art-direction.js?v=2';
import {createSpatialKit} from './spatial-kit.js?v=1';
import {buildSpatialScene} from './spatial-scenes.js?v=1';

export function createSpatialWorld({mount,kind,onSelect}){
 const T=window.THREE;if(!T)throw new Error('立体世界需要本地 Three.js 渲染器');
 const root=document.createElement('div');root.className='spatial-world';root.setAttribute('aria-label',kind==='inn'?'可旋转的立体旅店':'可旋转的立体温室');mount.append(root);
 const renderer=new T.WebGLRenderer({antialias:true});renderer.setPixelRatio(Math.min(devicePixelRatio||1,1.5));renderer.outputColorSpace=T.SRGBColorSpace;renderer.toneMapping=T.ACESFilmicToneMapping;renderer.shadowMap.enabled=true;renderer.shadowMap.type=T.PCFSoftShadowMap;renderer.shadowMap.autoUpdate=false;
 const element=renderer.domElement;element.tabIndex=0;element.setAttribute('aria-label',kind==='inn'?'三维旅店：拖动旋转，点击旅人、房间或家具互动':'三维温室：拖动旋转，点击设施检查');root.append(element);
 const scene=new T.Scene(),camera=new T.PerspectiveCamera(38,1.6,.1,130),modelRoot=new T.Group();scene.add(modelRoot);
 const ambient=new T.HemisphereLight('#f4edd9','#596d77',1.65);scene.add(ambient);const sun=new T.DirectionalLight('#fff0d2',3.5);sun.position.set(-9,16,12);sun.castShadow=true;sun.shadow.mapSize.set(1536,1536);Object.assign(sun.shadow.camera,{left:-16,right:16,top:15,bottom:-15,near:.5,far:60});sun.shadow.bias=-.0004;sun.shadow.normalBias=.035;scene.add(sun);const rim=new T.DirectionalLight('#bfdfed',1.1);rim.position.set(8,7,-10);scene.add(rim);
 const hud=document.createElement('div');hud.className='spatial-hud';const title=document.createElement('strong'),hint=document.createElement('small');hint.textContent='拖动旋转 · 点场景标签互动';hud.append(title,hint);const weather=document.createElement('span');weather.className='spatial-weather';const labels=document.createElement('div');labels.className='spatial-labels';const controls=document.createElement('div');controls.className='spatial-camera';controls.setAttribute('aria-label','三维镜头控制');root.append(hud,weather,labels,controls);
 const left=document.createElement('div'),right=document.createElement('div');left.className=right.className='spatial-camera-group';controls.append(left,right);const targets=new Map(),lights=[];
 let kit=null,model=null,look='',active=false,disposed=false,width=0,height=0,lastShadow=-1,selected='',cutaway=true,showMarkers=true,yaw=.56,pitch=.60,distance=kind==='inn'?29:31,drag=null;
 const ray=new T.Raycaster(),ndc=new T.Vector2();
 function cameraUpdate(){const framedDistance=distance*Math.max(1,1.6/camera.aspect);camera.position.set(Math.sin(yaw)*Math.cos(pitch)*framedDistance,Math.sin(pitch)*framedDistance+1.0,Math.cos(yaw)*Math.cos(pitch)*framedDistance);camera.lookAt(0,1.5,0);camera.updateMatrixWorld();}
 function reset(){yaw=.56;pitch=.60;distance=kind==='inn'?29:31;cameraUpdate();}
 function button(parent,name,text,action){const b=document.createElement('button');b.type='button';b.setAttribute('aria-label',name);b.textContent=text;b.addEventListener('click',()=>{action();cameraUpdate()});parent.append(b);return b}
 const markers=button(root,'切换场景标记','标记：开',()=>{showMarkers=!showMarkers;markers.textContent=showMarkers?'标记：开':'标记：关';markers.setAttribute('aria-pressed',String(showMarkers))});markers.className='spatial-marker-toggle';markers.setAttribute('aria-pressed','true');
 button(left,'镜头向左转动','↶',()=>yaw-=Math.PI/6);button(left,'镜头向右转动','↷',()=>yaw+=Math.PI/6);button(left,'恢复初始视角','复位',reset);
 button(right,'拉近镜头','＋',()=>distance=Math.max(20,distance-2));button(right,'拉远镜头','−',()=>distance=Math.min(42,distance+2));const shell=button(right,'切换建筑剖面','完整外壳',()=>{cutaway=!cutaway;shell.textContent=cutaway?'完整外壳':'展开剖面';shell.setAttribute('aria-pressed',String(!cutaway));if(model)model.outer.visible=!cutaway;renderer.shadowMap.needsUpdate=true});shell.setAttribute('aria-pressed','false');
 function addTarget(id,name,group,anchor,short){group.userData.spatialTarget=id;const label=document.createElement('button');label.type='button';label.className='spatial-label';label.dataset.spatialTarget=id;label.setAttribute('aria-label',name);const nameNode=document.createElement('span'),statusNode=document.createElement('span');nameNode.className='spatial-label-name';statusNode.className='spatial-label-status';label.append(nameNode,statusNode);label.addEventListener('click',()=>select(id));labels.append(label);targets.set(id,{id,name,group,anchor:new T.Vector3(...anchor),short,label,nameNode,statusNode});}
 function addLight(x,y,z,color,intensity,range){const light=new T.PointLight(color,intensity,range,1.6);light.position.set(x,y,z);scene.add(light);lights.push(light);return light}
 function select(id){selected=id;onSelect(id);element.focus({preventScroll:true});}
 function build(){model?.dispose();kit?.dispose();for(const l of lights)scene.remove(l);lights.length=0;targets.clear();labels.replaceChildren();look=getArtDirection();kit=createSpatialKit(T,modelRoot,look);model=buildSpatialScene(kit,kind,addTarget,addLight);model.outer.visible=!cutaway;const night=look==='cinematic';scene.background=new T.Color(night?'#152b3c':look==='voxel'?'#91b8c1':'#c9d4cf');scene.fog=new T.Fog(scene.background,42,100);ambient.intensity=night?.55:1.65;sun.intensity=night?2.8:3.5;sun.color.set(night?'#a4c5e5':'#fff0d2');rim.intensity=night?1.3:1.1;renderer.toneMappingExposure=night?1.25:1.0;title.textContent=kind==='inn'?'THE SEVEN-DAY INN':'THE LAST GREENHOUSE';lastShadow=-1;renderer.shadowMap.needsUpdate=true;}
 function targetPoint(t){return t.anchor.clone().applyMatrix4(t.group.matrixWorld).project(camera)}
 function update(s,info={}){if(disposed||!active)return;if(look!==getArtDirection())build();const box=root.getBoundingClientRect();if(box.width!==width||box.height!==height){width=Math.max(1,box.width);height=Math.max(1,box.height);renderer.setSize(width,height,false);camera.aspect=width/height;camera.updateProjectionMatrix()}cameraUpdate();const time=getArtClock(),u=model.update(s,info,time);modelRoot.updateMatrixWorld(true);weather.textContent=u.weather;const occupied=[{left:width-84,right:width-6,top:48,bottom:100}];
  hint.textContent=cutaway?'拖动旋转 · 点场景标签互动':'拖动环绕 · 展开剖面查看内部';
  for(const t of targets.values()){const p=targetPoint(t),label=t.label;label.hidden=!cutaway||!showMarkers||!t.group.visible||p.z>1||p.z< -1;if(label.hidden)continue;const status=u.statuses?.[t.id]||'',name=width<520?t.short:t.name;if(t.nameNode.textContent!==name)t.nameNode.textContent=name;if(t.statusNode.textContent!==status)t.statusNode.textContent=status;t.statusNode.hidden=!status;label.setAttribute('aria-pressed',String(t.id===selected));
   const cardW=Math.max(44,name.length*(width<520?9:11)+20,status.length*9+20),cardH=width<520||status?44:30,minY=width<520?104:80,baseX=Math.max(cardW/2+6,Math.min(width-cardW/2-6,(p.x+1)*width/2)),baseY=Math.max(minY,Math.min(height-65,(1-p.y)*height/2));let x=baseX,y=baseY;
   const offsets=[0,-50,50,-100,100,-150,150].flatMap(dy=>[0,-56,56,-112,112].map(dx=>({dx,dy,cost:dx*dx+dy*dy}))).sort((a,b)=>a.cost-b.cost);
   for(const {dx,dy}of offsets){const cx=Math.max(cardW/2+6,Math.min(width-cardW/2-6,baseX+dx)),cy=Math.max(minY,Math.min(height-65,baseY+dy)),rect={left:cx-cardW/2,right:cx+cardW/2,top:cy-cardH,bottom:cy};if(!occupied.some(a=>rect.left<a.right+4&&rect.right>a.left-4&&rect.top<a.bottom+4&&rect.bottom>a.top-4)){x=cx;y=cy;break}}
   occupied.push({left:x-cardW/2,right:x+cardW/2,top:y-cardH,bottom:y});label.style.left=x+'px';label.style.top=y+'px';
  }if(time-lastShadow>.25){renderer.shadowMap.needsUpdate=true;lastShadow=time}renderer.render(scene,camera);}
 function down(e){if(e.button!==0)return;drag={id:e.pointerId,x:e.clientX,y:e.clientY,startX:e.clientX,startY:e.clientY,moved:false};element.setPointerCapture(e.pointerId);element.focus({preventScroll:true})}
 function move(e){if(!drag||drag.id!==e.pointerId)return;const dx=e.clientX-drag.x,dy=e.clientY-drag.y;if(Math.hypot(e.clientX-drag.startX,e.clientY-drag.startY)>5)drag.moved=true;if(drag.moved){yaw-=dx*.007;pitch=Math.max(.27,Math.min(1.18,pitch+dy*.005))}drag.x=e.clientX;drag.y=e.clientY;cameraUpdate()}
 function up(e){if(!drag||drag.id!==e.pointerId)return;const click=!drag.moved;drag=null;try{element.releasePointerCapture(e.pointerId)}catch{}if(!click||!cutaway)return;const b=element.getBoundingClientRect();ndc.set((e.clientX-b.left)/b.width*2-1,-(e.clientY-b.top)/b.height*2+1);ray.setFromCamera(ndc,camera);const hits=ray.intersectObjects([...targets.values()].filter(t=>t.group.visible).map(t=>t.group),true);if(hits.length){let node=hits[0].object;while(node&&!node.userData.spatialTarget)node=node.parent;if(node)select(node.userData.spatialTarget)}}
 function cancel(){drag=null}
 element.addEventListener('pointerdown',down);element.addEventListener('pointermove',move);element.addEventListener('pointerup',up);element.addEventListener('pointercancel',cancel);
 reset();return {element,root,get active(){return active},setActive(value){active=value;root.hidden=!value;if(!value)drag=null},update,projectTargets(){if(!cutaway)return [];cameraUpdate();modelRoot.updateMatrixWorld(true);return [...targets.values()].filter(t=>t.group.visible).map(t=>{const p=targetPoint(t);return {id:t.id,x:(p.x+1)*480,y:(1-p.y)*300}})},dispose(){disposed=true;element.removeEventListener('pointerdown',down);element.removeEventListener('pointermove',move);element.removeEventListener('pointerup',up);element.removeEventListener('pointercancel',cancel);model?.dispose();kit?.dispose();renderer.dispose();root.remove()}};
}
