// Shared geometry builders. Voxel mode uses actual box geometry for round forms.
export function createSpatialKit(T,root,mode){
 const materials=new Map(),owned=new Set(),geometries=new Set();
 const voxel=mode==='voxel',night=mode==='cinematic';
 function material(color,options={}){const key=color+'/'+JSON.stringify(options);if(!materials.has(key)){const m=new T.MeshStandardMaterial({color,roughness:night?.72:.92,flatShading:voxel,...options});if(options.opacity<1){m.transparent=true;m.depthWrite=false;m.side=T.DoubleSide}materials.set(key,m);owned.add(m)}return materials.get(key)}
 function mesh(parent,geometry,color,x=0,y=0,z=0,options={}){geometries.add(geometry);const m=new T.Mesh(geometry,color?.isMaterial?color:material(color,options));m.position.set(x,y,z);m.castShadow=m.material.opacity>.5;m.receiveShadow=true;parent.add(m);return m}
 const group=(parent=root,x=0,y=0,z=0)=>{const g=new T.Group();g.position.set(x,y,z);parent.add(g);return g};
 const box=(parent,x,y,z,w,h,d,color,options={})=>mesh(parent,new T.BoxGeometry(w,h,d),color,x,y,z,options);
 const cylinder=(parent,x,y,z,rt,rb,h,color,options={})=>mesh(parent,voxel?new T.BoxGeometry(Math.max(rt,rb)*2,h,Math.max(rt,rb)*2):new T.CylinderGeometry(rt,rb,h,12),color,x,y,z,options);
 const orb=(parent,x,y,z,r,color,scale=[1,1,1])=>{const m=mesh(parent,voxel?new T.BoxGeometry(r*2,r*2,r*2):new T.SphereGeometry(r,12,8),color,x,y,z);m.scale.set(...scale);return m};
 function rod(parent,a,b,r,color){const av=new T.Vector3(...a),bv=new T.Vector3(...b),delta=bv.clone().sub(av);const m=cylinder(parent,0,0,0,r,r,delta.length(),color);m.position.copy(av.add(bv).multiplyScalar(.5));m.quaternion.setFromUnitVectors(new T.Vector3(0,1,0),delta.normalize());return m}
 function pine(parent,x,z,h=3){const g=group(parent,x,0,z);cylinder(g,0,h*.26,0,.09,.15,h*.52,'#756550');for(let i=0;i<3;i++){const size=h*(.37-i*.055);if(voxel)box(g,0,h*(.43+i*.16),0,size*1.9,h*.30,size*1.9,['#486c60','#568576','#679583'][i]);else mesh(g,new T.ConeGeometry(size,h*.66,7),'#5d8872',0,h*(.53+i*.16),0)}return g}
 function plant(parent,x,y,z,size=1){const g=group(parent,x,y,z);cylinder(g,0,.18*size,0,.18*size,.13*size,.36*size,'#b27451');cylinder(g,0,.36*size,0,.15*size,.15*size,.025*size,'#493e32');rod(g,[0,.36*size,0],[0,1.0*size,0],.022*size,'#477554');const leaves=[];for(let i=0;i<6;i++){const sign=i%2?1:-1,m=orb(g,sign*.15*size,(.52+i*.07)*size,(i%3-1)*.06*size,.15*size,i%2?'#769873':'#527d5b',[1.3,.28,.64]);m.rotation.z=sign*.36;leaves.push(m)}return {group:g,leaves}}
 function actor(parent,x,z,color,hat=false){const g=group(parent,x,0,z),rig=group(g),coat=material(color).clone();owned.add(coat);cylinder(rig,0,1.15,0,.20,.25,.64,coat);box(rig,0,.8,0,.43,.08,.31,'#4a5558');const legs=[],arms=[];for(const sign of[-1,1]){const leg=group(rig,sign*.11,.79,0);box(leg,0,-.32,0,.14,.64,.15,'#394e5c');box(leg,0,-.70,.065,.18,.13,.31,'#61574b');legs.push(leg);const arm=group(rig,sign*.25,1.44,0);box(arm,0,-.23,0,.12,.47,.13,coat);orb(arm,0,-.49,0,.068,'#ddaf88');arms.push(arm)}cylinder(rig,0,1.51,0,.07,.08,.12,'#dfb58f');orb(rig,0,1.7,0,.15,'#e4ba92',[.88,1.13,.93]);orb(rig,0,1.80,-.025,.15,'#3e4140',[1,.48,.98]);for(const x of[-.046,.046])orb(rig,x,1.71,.137,.016,'#253948',[1,1,.4]);if(hat){cylinder(rig,0,1.87,0,.24,.24,.05,'#d8b06c');cylinder(rig,0,1.94,0,.15,.18,.13,'#ba8e56')}const book=box(rig,0,1.10,.35,.34,.055,.24,'#eed8a6'),cup=cylinder(arms[1],0,-.40,.13,.065,.053,.12,'#ece2c8');book.visible=cup.visible=false;return {group:g,rig,legs,arms,coat,book,cup,lastX:x,lastZ:z,phase:x*.8+z}}
 function updateActor(a,x,z,time,pose='idle',visible=true){a.group.visible=visible;const dx=x-a.lastX,dz=z-a.lastZ,walking=Math.hypot(dx,dz)>.002;a.group.position.set(x,0,z);if(walking)a.group.rotation.y=Math.atan2(dx,dz);a.rig.position.y=Math.sin(time*1.8+a.phase)*.008;for(let i=0;i<2;i++){a.legs[i].rotation.x=walking?Math.sin(time*8+i*Math.PI+a.phase)*.43:0;a.arms[i].rotation.x=walking?-Math.sin(time*8+i*Math.PI+a.phase)*.3:['tea','read','sketch'].includes(pose)?-1.05:Math.sin(time*1.6+i+a.phase)*.025}a.book.visible=['read','sketch'].includes(pose);a.cup.visible=pose==='tea';a.lastX=x;a.lastZ=z}
 return {T,root,mode,voxel,night,material,mesh,group,box,cylinder,orb,rod,pine,plant,actor,updateActor,dispose(){for(const g of geometries)g.dispose();for(const m of owned)m.dispose();root.clear()}};
}
