import {createRequire} from 'node:module';
import {mkdir,readFile,writeFile} from 'node:fs/promises';
import {fileURLToPath} from 'node:url';
import assert from 'node:assert/strict';
const require=createRequire('C:/Users/yun68/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/package.json');
const {chromium}=require('playwright'),sharp=require('sharp');
const root=fileURLToPath(new URL('../',import.meta.url)),base='http://127.0.0.1:8975/';
await mkdir(root+'notes/demo-downloads',{recursive:true});
const browser=await chromium.launch({headless:true});
const page=await browser.newPage({viewport:{width:1440,height:1050},acceptDownloads:true,reducedMotion:'reduce'});
const checks=[],errors=[],requests=[];
page.on('pageerror',error=>errors.push(error.message));page.on('request',request=>requests.push(request.url()));
const check=(name,passed)=>{assert.ok(passed,name);checks.push({name,passed:true});};
const snapshot=()=>page.evaluate(()=>ArcDemo.getSnapshot());
const image=()=>page.locator('#product-canvas').evaluate(canvas=>canvas.toDataURL());
const change=async(action,name)=>{const before=await image();await action();await page.waitForFunction(before=>document.querySelector('#product-canvas').toDataURL()!==before,before);check(name,await image()!==before);};
const download=async(id,name)=>{const [item]=await Promise.all([page.waitForEvent('download'),page.locator(id).click()]);const path=root+'notes/demo-downloads/'+name;await item.saveAs(path);return readFile(path);};
try{
  await page.goto(base+'demo/',{waitUntil:'networkidle'});
  await page.waitForFunction(()=>ArcDemo?.getRendererType()==='webgl'&&ArcDemo.getSnapshot().observation.environmentReady);
  check('实际使用本地WebGL与室内环境',(await snapshot()).observation.renderer==='webgl');
  check('演示不请求第三方资源',requests.every(url=>url.startsWith(base)));
  const stats=await sharp(Buffer.from((await image()).split(',')[1],'base64')).stats();
  check('画布有实际渲染像素',stats.channels.slice(0,3).some(channel=>channel.stdev>25));
  await page.screenshot({path:root+'assets/qa/our-demo-desktop.png',fullPage:true});
  await change(()=>page.locator('[data-view="structure"]').click(),'结构操作实际改变画面');
  check('结构展开和进度同步',(await snapshot()).configuration.explode===82&&await page.locator('#task-progress [data-complete="true"]').count()===1);
  await page.locator('[data-part="shade"]').click();
  check('部件聚焦有对应说明',(await page.locator('#part-description').innerText()).includes('灯罩')&&(await snapshot()).observation.part==='shade');
  await page.locator('[data-preset="desk"]').click();
  check('返回整体场景同步清除部件聚焦',await page.locator('[data-part][aria-pressed="true"]').count()===0&&(await snapshot()).observation.part===null);
  await page.locator('#save-a').click();
  const saved=(await snapshot()).referenceA;
  check('方案A保存真实当前配置',saved.configuration.color==='#356873'&&saved.configuration.light===70);
  await change(()=>page.locator('[data-preset="night"]').click(),'夜间预设实际改变画面');
  check('A未被方案B覆盖并准确对比',(await snapshot()).referenceA.configuration.color==='#356873'&&(await snapshot()).configuration.color==='#e7d9be'&&await page.locator('#comparison tr[data-changed="true"]').count()===3);
  await page.locator('#project-name').fill('我们的研究工作台 · 夜间评审');
  await page.locator('#notes').fill('先确认结构，再比较夜间显示效果；当前方案交给团队评审。');
  const json=JSON.parse((await download('#export-json','arc-configuration.json')).toString('utf8'));
  check('JSON下载包含当前选择和完整A对照',json.project.name.includes('夜间评审')&&json.configuration.room==='night'&&json.referenceA.configuration.room==='studio'&&json.differences.length===3);
  const md=(await download('#export-md','arc-brief.md')).toString('utf8');
  check('需求单下载包含真实用途和差异',md.includes('先确认结构')&&md.includes('海湾蓝 → 纸沙色')&&md.includes('日光 → 夜景'));
  const png=await download('#export-png','arc-preview.png');
  const meta=await sharp(png).metadata();
  check('PNG下载有正确像素和尺寸',meta.format==='png'&&meta.width>500&&meta.height>500&&png.length>10000);
  await page.locator('#restore-a').click();
  check('恢复A同步控件并清除配置差异',(await snapshot()).configuration.color==='#356873'&&await page.locator('#room').inputValue()==='studio'&&await page.locator('#comparison tr[data-changed="true"]').count()===0);
  await page.locator('[data-preset="photo"]').click();
  await page.reload({waitUntil:'networkidle'});
  check('刷新恢复当前配置且保留A',(await snapshot()).configuration.color==='#b66e50'&&(await snapshot()).referenceA.configuration.color==='#356873');
  await page.locator('#tour').click();
  check('自动体验明确进入运行状态',await page.locator('#tour').getAttribute('aria-pressed')==='true');
  await page.locator('[data-color="#e7d9be"]').click();
  check('手动调整终止自动体验并保留选择',await page.locator('#tour').getAttribute('aria-pressed')==='false'&&(await snapshot()).configuration.color==='#e7d9be');
  await page.locator('#reset').click();
  check('重置当前方案不删除已保存A',(await snapshot()).configuration.light===70&&(await snapshot()).referenceA.configuration.light===70);
  for(const width of [390,768,1440]){
    await page.setViewportSize({width,height:1050});
    await page.waitForFunction(()=>document.querySelector('#product-canvas').width>0);
    check(`独立演示在${width}px无页面横向溢出`,await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1));
    if(width===390)check('手机对照表同时显示A与当前方案',await page.locator('.comparison-scroll').evaluate(element=>element.scrollWidth<=element.clientWidth+1));
    if(width===390){
      await page.locator('[data-color="#b66e50"]').click();
      const beforeMobile=await image();
      check('手机调参时模型确实在屏幕之外',await page.locator('#product-canvas').evaluate(canvas=>canvas.getBoundingClientRect().bottom<0));
      const mobilePng=await download('#export-png','arc-mobile-preview.png');
      const currentMobile=await image();
      const renderedRaw=await sharp(Buffer.from(currentMobile.split(',')[1],'base64')).raw().toBuffer();
      const exportedRaw=await sharp(mobilePng).raw().toBuffer();
      check('模型离屏时导出仍刷新最新配置像素',currentMobile!==beforeMobile&&exportedRaw.equals(renderedRaw)&&(await snapshot()).configuration.color==='#b66e50');
      await page.screenshot({path:root+'assets/qa/our-demo-mobile.png',fullPage:true});
    }
  }
  await page.goto(base+'demo/?embedded=1',{waitUntil:'networkidle'});
  check('补充实验保留独立嵌入模式',await page.locator('.outer-intro').isHidden()&&await page.locator('#product-canvas').isVisible());
  await page.locator('#tour').click();
  await page.evaluate(()=>window.postMessage({type:'demo-visibility',visible:false},location.origin));
  await page.waitForFunction(()=>document.querySelector('#tour').getAttribute('aria-pressed')==='false');
  check('补充实验收到隐藏消息时停止自动体验',await page.locator('#tour').getAttribute('aria-pressed')==='false');
  const fallbackBrowser=await chromium.launch({headless:true,args:['--disable-webgl']});
  const fallback=await fallbackBrowser.newPage({viewport:{width:390,height:1050}});
  await fallback.goto(base+'demo/',{waitUntil:'networkidle'});
  check('无WebGL时明确降级并保留选配',await fallback.evaluate(()=>ArcDemo.getRendererType()==='canvas')&&await fallback.locator('#setting').isDisabled()&&await fallback.locator('#spin').isDisabled());
  await fallback.locator('[data-preset="night"]').click();
  check('降级配置与画面能力同步',await fallback.evaluate(()=>ArcDemo.getSnapshot().configuration.setting==='studio')&&await fallback.locator('#setting').inputValue()==='studio');
  await fallbackBrowser.close();
  check('无JavaScript运行错误',errors.length===0);
  await writeFile(root+'notes/demo-verification.json',JSON.stringify({checkedAt:'2026-10-02',checks,errors,scope:'Local concept renderer and task workflow. No real-product dimensions, lighting measurements, ordering or commercial outcome validation.'},null,2)+'\n');
  console.log(JSON.stringify({passed:checks.length,errors}));
}finally{await browser.close();}
