import React, {useEffect} from 'react';
const repo='https://github.com/richiemcilroy/chippytea';
const archive='https://github.com/yydshly/0930_codex_project/tree/main/projects/016-chippytea-lab';
const scenes=[
  {id:'gravity',name:'引力花园',characters:'懒石头园丁 × 急性子风精灵',line:'让一颗发现，长成自己的花园。',effect:'吹种、旋流、接力、岛面选位，种子生根、抽芽、展叶。拖动改变风向；最近四株实际落点保存在本机。',music:'MiniMax 配乐已生成',clip:'gravity-v10.mp4'},
  {id:'moon',name:'月亮修补铺',characters:'严肃裁缝 × 淘气月亮',line:'每补一针，接住一个想法。',effect:'追逐、拉线、补丁飞行、三针缝合。拖动牵回月亮，留下补丁与本机想法计数。',music:'静音演出 · 配乐待生成',clip:'moon-v10.mp4'},
  {id:'shadow',name:'影子排练场',characters:'夸张影子 × 害羞光团',line:'你给一点光，我换一种模样。',effect:'追光、旋身、镜像共舞和谢幕。拖灯改变动作；留住当时姿势，最近三份实际动作与参数成为前排小观众。',music:'MiniMax 配乐已生成',clip:'shadow-v10.mp4'}
];
const products=[
 ['知识收藏 / 研究归档','发现 → 种子','确认收藏后触发生长；把实际资料与世界变化关联，支持回看、撤销与来源追溯。'],
 ['任务 / 习惯 / 专注','完成 → 一幕成长','以已确认的任务或专注结果触发角色回应，用短演出表达进展，避免打断后续工作。'],
 ['文件 / 素材整理','整理 → 场景舒展','分类与归档结果变成空间变化。真实文件操作仍需独立引擎、复核和恢复策略。'],
 ['创作成果 / 品牌展示','能力 → 可玩的故事','把产品能力和作品输出组织成可参与的小场景，建立自己的角色、幽默与品牌语言。'],
 ['互动课程 / 新手引导','学习 → 角色回应','把步骤和练习结果映射成动作、对白与进度，保留清晰说明和无声体验。'],
 ['音乐叙事编辑器','素材与歌曲 → 可编排场景','发展段落、词级时间、角色动作和事件脚本的编辑工具；当前尚无完整编辑器。']
];
function Head({n,title,children}:{n:string;title:string;children?:React.ReactNode}){return <div className="overview-heading"><span>{n}</span><div><h2>{title}</h2>{children&&<p>{children}</p>}</div></div>}
export function Overview(){
 useEffect(()=>{document.title='Chippytea Lab · 完整理解与声画展示';},[]);
 return <div className="overview">
 <a className="overview-skip" href="#entries">跳到全部展示入口</a>
 <header className="overview-header"><a href="./" className="overview-brand">Chippytea Lab <span>016 · 声画体验研究</span></a><nav aria-label="总览导航"><a href="#map">引导图</a><a href="#entries">全部效果</a><a href="#understanding">能力与价值</a><a href="#products">产品扩展</a><a href="#resources">相关链接</a></nav><a href="../../">研究集 ↗</a></header>
 <main>
 <section className="overview-hero" id="top"><p className="overview-eyebrow">FUNCTION → STORY → PARTICIPATION</p><h1>让真实功能结果，<br/><em>长出可参与的声画体验。</em></h1><p className="overview-lead">从 Chippytea 的 Mac 清理产品与互动官网出发，理解它如何让功能、图像、动作与音乐共同成立，再发展我们的原创角色和小世界。</p><div className="overview-actions"><a className="overview-button primary" href="#entries">进入三个原创演出 ↓</a><a className="overview-button" href="./?view=source">操作原作对照</a><a className="overview-button" href="./research.html">阅读完整研究档案</a></div><div className="overview-facts"><span><b>3</b> 原创世界</span><span><b>32 秒</b> 每场四幕</span><span><b>2 首</b> MiniMax 配乐</span><span><b>6 类</b> 产品扩展方向</span></div><p className="overview-small">研究基线 f245695 · 演出 v10 · 2026-10-08 整理发布。月亮配乐待生成；世界互动存于当前浏览器，真实业务接入与收益待验证。</p></section>
 <section className="overview-map" id="map"><div className="overview-map-title"><div><p className="overview-eyebrow">OUR UNDERSTANDING</p><h2>一张图看清：能力、价值、原理、样式与产品</h2></div><div><a href="./assets/chippytea-understanding-map-v1.png" target="_blank" rel="noreferrer">打开原图 ↗</a><a href="./assets/chippytea-understanding-map-v1.png" download>下载 PNG ↓</a></div></div><a href="./assets/chippytea-understanding-map-v1.png" target="_blank" rel="noreferrer"><img src="./assets/chippytea-understanding-map-v1.png" width="1536" height="1024" alt="我们已经生成的 Chippytea 理解总览图：源库能力、价值、声画编排原理、引力花园、月亮修补铺、影子排练场与六类产品扩展"/></a><p className="overview-small">沿用此前生成的原图，内容和图像文件保持一致。图中产品映射为待接入方案。</p></section>
 <section className="overview-section" id="entries"><Head n="01" title="全部展示入口">先看效果，再看它如何与功能发生关系。每场都可暂停、跳幕、重演、拖动和留下本机记忆；声音需要主动开启。</Head><div className="overview-scenes">{scenes.map((s,i)=><article className={'overview-scene '+s.id} key={s.id}><div className="overview-scene-title"><span>0{i+1} / ORIGINAL WORLD</span><h3>{s.name}</h3><p>{s.characters}</p></div><video controls playsInline preload="none" poster={'./assets/concepts/'+s.id+'.png'} src={'./assets/previews/'+s.clip} aria-label={s.name+' v10 离线演出预览'}/><p className="overview-small">v10 离线渲染预览；实际网页互动从下方进入。{s.id==='moon'?'本片无配乐。':'本片含实际 MiniMax 配乐。'}</p><h4>{s.line}</h4><p>{s.effect}</p><span className="overview-badge">{s.music}</span><a className="overview-button primary" href={'./?view=experience&scene='+s.id+'&v=10'}>进入{s.name} →</a></article>)}</div><div className="overview-other-entries"><a href="./?view=source"><b>原作对照</b><span>模拟清理、墨线种子、成果动画与短音效、逐词歌词与互动歌曲 →</span></a><a href="./?view=folio"><b>历史纸墨实验</b><span>24 秒静音预演：笔记联接、批注、装订与真实编号落印 →</span></a><a href="./?view=research&mode=records"><b>资料与研究回执</b><span>已有资料与回执的只读快照、核验依据、搜索和 JSON 导出 →</span></a><a href="./research.html"><b>完整研究档案</b><span>源库研究、原创设计、日常场景分析、音乐提示与验收记录 →</span></a></div></section>
 <section className="overview-section" id="understanding"><Head n="02" title="源库的能力是什么？">Chippytea 是完整的 Mac 清理产品，加一个富有表现力的互动官网。原生功能和网页表达分别承担不同责任。</Head><div className="overview-two"><article className="overview-card"><p className="overview-eyebrow">REAL APPLICATION</p><h3>先发现、审阅，再操作和记账</h3><ul><li>扫描获准位置，识别依赖、构建目录、已知缓存、日志、下载和大文件，解释占用与后果。</li><li>用户审阅，检查对象与活动状态，再决定保留、移入废纸篓或执行符合条件的永久清理。</li><li>完成后保守核算成果，每 100 MB 计一个 chip；估算和移入废纸篓不计奖，永久操作也可能记零。</li><li>SwiftUI 提供原生界面与系统整合；Rust 与 SQLite 支持扫描、索引、复核和账本。</li></ul><p className="overview-small">Mac 原生引擎未在本项目实机运行。网页演示使用虚构文件，不执行清理。</p><a href={repo+'/tree/f245695/native/Chippytea'}>原生结构 ↗</a> · <a href={repo+'/blob/f245695/core/src/accounting.rs'}>成果核算 ↗</a></article><article className="overview-card"><p className="overview-eyebrow">EXPRESSIVE WEBSITE</p><h3>把功能延展成可玩的声画场景</h3><ul><li>奶油纸底、可控墨线、角色和控件共享一套视觉规则。</li><li>收集飞行动画、容器回应、数字变化和短提示音表达同一次成果。</li><li>音频时间驱动歌词、段落与换场，用户点击加入角色表演。</li><li>React、SVG、Canvas、CSS 与 Web Audio 分别负责状态、绘图、动作和声音。</li></ul><p>我们参考的是可阅读复用的实现和编排思路；将它用于新产品还要设计自己的角色、接口与内容。</p><a href="./?view=source#style">操作手绘原语 →</a> · <a href="./?view=source#music">打开歌曲场景 →</a></article></div></section>
 <section className="overview-section" id="principle"><Head n="03" title="原理：同一含义，共同编排">功能决定发生了什么；图像给出角色与世界；动画表达过程和回应；音乐组织节奏与情绪。</Head><ol className="overview-flow">{['功能事件','确认结果','声画编排','用户参与','世界积累'].map((x,i)=><li key={x}><small>0{i+1}</small><strong>{x}</strong></li>)}</ol><div className="overview-two"><article className="overview-card"><h3>时间驱动 + 事件驱动</h3><p>有音乐时用真实播放器 currentTime 统一四幕，频谱给角色和环境提供细微回应；点击、拖动、收藏触发独立动作，暂停也能完成小戏。无配乐场景使用视觉时钟。</p><p>固定种子让墨线有共同规则，状态机让角色有动作与回应，持续存储让使用积累成为世界的一部分。</p><a href={repo+'/blob/f245695/site/lib/ink.ts'}>原作 ink.ts ↗</a> · <a href={repo+'/blob/f245695/site/components/Karaoke.tsx'}>原作 Karaoke ↗</a></article><article className="overview-card"><span className="overview-badge">业务映射示例 · 待接入</span><h3>确认收藏 → 种子生长 → 花园记住</h3><p>真实收藏完成，种子才落地；园丁接住、幼苗生长，音乐在动作节点回应。多次使用留下可回看的变化。</p><p>当前花园保存本机选位，月亮保存标记，影子保存姿势；这些还没有关联真实收藏内容、任务完成凭证或研究入册 API。</p></article></div></section>
 <section className="overview-section" id="value"><Head n="04" title="对我们的价值是什么？">把抽象的完成和积累，表达成能理解、能参与、能记住的结果。源码减少重复实现，质量仍依赖原创创意、美术、旋律和节奏。</Head><div className="overview-values"><article><span>01</span><h3>结果可感知</h3><p>动作解释过程，角色回应强调完成，让一次操作与结果之间的关系更清楚。</p></article><article><span>02</span><h3>形成产品性格</h3><p>原创角色、关系和世界规则，让功能与画风、声音共同构成可识别的品牌。</p></article><article><span>03</span><h3>沉淀可复用方法</h3><p>保留时钟、段落、动作、素材、反馈与存储的编排结构，为不同场景持续创作。</p></article></div><p className="overview-note">完成率、回访、传播或商业收益尚未测量。下一步应选择一个真实业务事件接入，再用实际用户验证价值。</p></section>
 <section className="overview-section" id="products"><Head n="05" title="可扩展成哪些产品？">以下是可探索方向。先确定功能要表达的含义，再设计适合它的角色与规则，逐步补业务和验收。</Head><div className="overview-products">{products.map(([name,rule,desc],i)=><article className="overview-card" key={name}><span className="overview-eyebrow">DIRECTION 0{i+1}</span><h3>{name}</h3><strong>{rule}</strong><p>{desc}</p></article>)}</div></section>
 <section className="overview-section" id="resources"><Head n="06" title="相关链接与完整资料">原作、当前效果、历史研究和下一步连接都从这里进入。</Head><div className="overview-resources"><article className="overview-card"><h3>原作与来源</h3><a href="https://www.chippytea.com/" target="_blank" rel="noreferrer">Chippytea 原作官网 ↗</a><a href={repo} target="_blank" rel="noreferrer">源库 GitHub ↗</a><a href={repo+'/tree/f245695'}>研究固定快照 f245695 ↗</a><a href="https://huggingface.co/spaces/MiniMaxAI/MiniMax-Music3">MiniMax Music3 来源 ↗</a><a href="./source-notice.html">来源、改编与许可 →</a></article><article className="overview-card"><h3>我们的完整档案</h3><a href="./research.html">阅读研究、设计与验收全文 →</a><a href="./research.html#music">配乐提示与生成记录 →</a><a href="./research.html#qa">历史证据与本次发布检查 →</a><a href="./?view=research&mode=records">资料快照与真实回执 →</a><a href={archive}>GitHub 源码与制作资料 ↗</a><a href="./publication-manifest.json">本次公开资源清单 JSON →</a></article><article className="overview-card"><h3>可连接的已有研究</h3><a href="../004-rhythm-drop/">004 · Rhythm Drop：声音与音乐叙事 →</a><a href="../008-cellmotion/">008 · CellMotion：可编辑文字动效 →</a><a href="../010-dumpling-style-lab/">010 · Dumpling：原创画风与生活产品 →</a><a href="../015-ai-creative-products/">015 · AI Creative Products：创作效果与交付 →</a><p className="overview-small">这些是方法连接，尚未完成跨项目业务集成。</p></article></div><div className="overview-note"><b>使用范围</b><p>公开站为静态展示。三场世界记忆存在当前站点的 localStorage，本机旧存档不会自动迁移；研究回执为构建时快照，重新核验与保存需运行本机 Python 服务。默认无声，可暂停和选择减少动态；月亮与历史纸墨配乐待生成。</p><p>源代码与绘图路径为 MIT，原曲和 MiniMax 音乐权益单独说明。原作歌曲从官网远程播放，网络不可用时可前往原官网。公开展示未运行 Mac 清理引擎，也未验证商业收益。</p></div></section>
 </main><footer className="overview-footer"><span>功能提供含义 · 声画编排体验 · 参与留下积累</span><a href="#top">回到顶部 ↑</a><a href="../../">返回研究集</a></footer></div>;
}

